#!/usr/bin/env python3
"""W25 T3c -- (a) THIRD, INDEPENDENT re-decision of the N=8 all-blocked X_3
object; (b) the next rung: is there an all-blocked X_4 point at N = 8?

(a) The BLOCKED verdicts are re-derived by a THIRD Singular route --
    saturation `sat(I, s*k00*k11*k22)` tested for the unit ideal -- instead of
    the Rabinowitsch dimension used by both deciders, plus an explicit search
    over a large exact cap library over Q and over Z[omega] (a sufficient
    witness test: any hit would refute the verdict).  Note the Rabinowitsch
    computation over Q already decides emptiness over the ALGEBRAIC CLOSURE,
    so omega is covered; the Z[omega] search is a ledger-20 belt-and-braces.

(b) X_4 at N = 8 is generated by the site-linear projection with the 4-near-
    constant words, and every produced object is screened for all-blockedness.
"""
from __future__ import annotations

import json
import random
import sys
import time
from collections import Counter
from fractions import Fraction
from itertools import combinations

BASE = ("/Users/rishi/workplace/krenn-conjecture/computations/"
        "unaudited-x3core-w25-2026-08-15")
W23BASE = ("/Users/rishi/workplace/krenn-conjecture/computations/"
           "unaudited-pure-core-w23-2026-08-15")
sys.path.insert(0, BASE)
sys.path.insert(0, W23BASE)
import w25_core as C                                            # noqa: E402
import w25_walk as WK                                           # noqa: E402
import w25_decide as D                                          # noqa: E402
import w23_decide as W23D                                       # noqa: E402
import run_t2_u2 as T2                                          # noqa: E402
import run_t3b_escalation as T3B                                # noqa: E402

N = 8
RES = {}
RAN = []


def control(name):
    RAN.append(name)


def decide_by_saturation(src, p, q, sites, tag, timeout=3600):
    """Third route: BLOCKED  <=>  sat(I, s*k00*k11*k22) is the unit ideal."""
    isrc, _ = C.clear_denominators(src)
    eqs, s, kap = D.sym_cap_error(isrc, p, q, sites)
    gens = [D._sing(e) for e in eqs]
    nz = "(" + D._sing(s) + ")*(" + ")*(".join(D._sing(k) for k in kap) + ")"
    lines = ['LIB "elim.lib";',
             f'ring zzS=0,({",".join(D.KVARS)}),dp;',
             "ideal zzI=" + (",".join(gens) if gens else "0") + ";",
             f"poly zzf={nz};",
             "list zzL=sat(zzI,zzf);",
             "ideal zzT=std(zzL[1]);",
             f'"SAT {tag} "+string(dim(zzT))+" "+string(size(zzT));']
    script = "\n".join(lines)
    C.no_shadow_guard(script, set(D.KVARS))
    out = C.run_singular(script, timeout=timeout)
    ln = [x for x in out.splitlines() if x.startswith(f"SAT {tag} ")]
    assert ln, out
    parts = ln[0].split()
    dim = int(parts[2])
    return ("BLOCKED" if dim == -1 else "WITNESS"), dim


def big_cap_library(rng, n=600):
    out = list(D.cap_library())
    vals = [Fraction(x) for x in (-2, -1, 0, 1, 2, 3)]
    for _ in range(n):
        K = [[rng.choice(vals) for _ in range(3)] for _ in range(3)]
        out.append(K)
    w = C.OMEGA
    ovals = [C.Om(0), C.Om(1), C.Om(-1), w, w * w, C.Om(1) + w, C.Om(1) - w]
    for _ in range(n):
        K = [[rng.choice(ovals) for _ in range(3)] for _ in range(3)]
        out.append(K)
    return out


def screen(src, tag, n=N):
    live = [(p, q) for p, q in combinations(range(n), 2) if C.live(src, p, q)]
    order = sorted(live, key=lambda pq: -C.matrix_rank(C.oriented(src, *pq)))
    dec = []
    for (p, q) in order:
        U = tuple(x for x in range(n) if x not in (p, q))
        v, d, _ = D.decide_pair(src, p, q, U, f"{tag}_{p}{q}", primes=())
        dec.append([[p, q], v])
        if v == "WITNESS":
            return {"n_live": len(live), "witness": [p, q],
                    "all_blocked": False, "n_decided": len(dec)}
    return {"n_live": len(live), "witness": None, "all_blocked": bool(live),
            "n_decided": len(dec), "verdicts": dec}


def main():
    t0 = time.time()
    rng = random.Random(4242)
    src, rec = T3B.load_candidate()

    print("=" * 74)
    print("(a1) THIRD ROUTE: saturation instead of Rabinowitsch, every live "
          "pair of the N=8 all-blocked X_3 object")
    print("=" * 74)
    rows = []
    dis = 0
    for p, q in combinations(range(N), 2):
        if not C.live(src, p, q):
            continue
        U = tuple(x for x in range(N) if x not in (p, q))
        v3, d3 = decide_by_saturation(src, p, q, U, f"S{p}{q}")
        rows.append({"pair": [p, q], "sat_verdict": v3, "sat_dim": d3})
        if v3 != "BLOCKED":
            dis += 1
    print(f"   {len(rows)} live pairs; saturation route says BLOCKED on "
          f"{len(rows) - dis}; disagreements with the two Rabinowitsch "
          f"deciders: {dis}")
    RES["third_route"] = {"rows": rows, "disagreements": dis}
    control("T3c_a1_third_route")

    print("=" * 74)
    print("(a2) explicit cap search over Q and Z[omega] (sufficient test)")
    print("=" * 74)
    caps = big_cap_library(rng)
    hits = []
    for p, q in combinations(range(N), 2):
        if not C.live(src, p, q):
            continue
        U = tuple(x for x in range(N) if x not in (p, q))
        K = D.cheap_witness(src, p, q, U, caps=caps)
        if K is not None:
            hits.append([p, q])
    print(f"   {len(caps)} caps x 21 live pairs: explicit witnesses found "
          f"{len(hits)} (must be 0) {hits[:3]}")
    RES["cap_search"] = {"caps": len(caps), "hits": hits}
    assert not hits
    control("T3c_a2_cap_search")

    print("=" * 74)
    print("(a3) the SAME cap search on the positive control must FIRE")
    print("=" * 74)
    col, w, base = T2.build_n_diagonal(N, rng, extra=2)
    pos = []
    for p, q in combinations(range(N), 2):
        if not C.live(base, p, q):
            continue
        U = tuple(x for x in range(N) if x not in (p, q))
        if D.cheap_witness(base, p, q, U, caps=caps) is not None:
            pos.append([p, q])
    print(f"   diagonal X_3 control at N=8: explicit witnesses found at "
          f"{len(pos)} live pairs (must be > 0)")
    RES["cap_search_control"] = {"hits": len(pos)}
    assert pos
    control("T3c_a3_cap_search_control")

    print("=" * 74)
    print("(a4) how rigid is X_3?  site-system kernel dimensions, N=6 vs N=8")
    print("=" * 74)
    ne = C.near_exact_six_site()
    d6 = WK.site_dims(ne, 6, 3)
    d8 = WK.site_dims(src, N, 3)
    d8b = WK.site_dims(base, N, 3)
    print(f"   N=6, committed near-exact source, X_3 kernel dims: {d6}")
    print(f"   N=8, the all-blocked X_3 object,   X_3 kernel dims: {d8}")
    print(f"   N=8, a diagonal X_3 source,        X_3 kernel dims: {d8b}")
    print("   => the X_3 variety is DRAMATICALLY less rigid at N=8; that is "
          "why the rung that bites at N=6 does not bite at N=8.")
    RES["rigidity"] = {"n6": d6, "n8_candidate": d8, "n8_diagonal": d8b}
    control("T3c_a4_rigidity")

    print("=" * 74)
    print("(b) THE NEXT RUNG: X_4 at N = 8")
    print("=" * 74)
    seeds = []
    for t in range(6):
        col2, w2, s2 = T2.build_n_diagonal(N, rng, extra=rng.choice([0, 2, 3]))
        if s2 is not None:
            seeds.append(s2)
    stats = []
    reach = 0
    for si, s0 in enumerate(seeds):
        cur, dims = WK.site_solve(s0, 0, N, 4, keep_particular=True)
        if cur is None:
            stats.append({"seed": si, "reach_X4": False})
            continue
        ok4, bw = C.in_Xk(cur, N, 4)
        if not ok4:
            stats.append({"seed": si, "reach_X4": False, "raw": False})
            continue
        reach += 1
        sc = screen(cur, f"X4s{si}")
        stats.append({"seed": si, "reach_X4": True, "dims": dims,
                      "n_live": sc["n_live"], "all_blocked": sc["all_blocked"],
                      "defects": len(C.mixed_defects(cur, N))})
        print(f"   seed {si}: reached X_4 (site-0 kernel dims {dims}); live "
              f"{sc['n_live']}; ALL-BLOCKED {sc['all_blocked']}", flush=True)
        for k in range(4):
            walked = cur
            good = True
            for st in range(rng.randint(1, 3)):
                nxt, dm = WK.site_solve(walked, rng.randrange(N), N, 4, rng,
                                        spread=rng.choice([1, 2, 3]))
                if nxt is None:
                    good = False
                    break
                walked = nxt
            if not good:
                continue
            okw, bww = C.in_Xk(walked, N, 4)
            assert okw, ("walk left X_4", bww)
            sc2 = screen(walked, f"X4w{si}{k}")
            stats.append({"seed": si, "walk": k, "n_live": sc2["n_live"],
                          "all_blocked": sc2["all_blocked"],
                          "defects": len(C.mixed_defects(walked, N))})
            if sc2["all_blocked"]:
                blocks = {f"{a},{b}": [[str(x) for x in r]
                                       for r in walked[(a, b)]]
                          for a, b in combinations(range(N), 2)}
                RES.setdefault("x4_allblocked", []).append(
                    {"seed": si, "walk": k, "blocks": blocks,
                     "verdicts": sc2.get("verdicts")})
                print(f"      >>> ALL-BLOCKED X_4 CANDIDATE at N=8 "
                      f"(seed {si}, walk {k}) -- stored", flush=True)
    nab = sum(1 for s in stats if s.get("all_blocked"))
    print(f"   X_4 objects at N=8 screened: "
          f"{sum(1 for s in stats if 'n_live' in s)}; reached X_4 from "
          f"{reach}/{len(seeds)} diagonal seeds; ALL-BLOCKED {nab}")
    RES["x4"] = {"stats": stats, "all_blocked": nab, "reached": reach,
                 "seeds": len(seeds)}
    control("T3c_b_x4")

    declared = ["T3c_a1_third_route", "T3c_a2_cap_search",
                "T3c_a3_cap_search_control", "T3c_a4_rigidity", "T3c_b_x4"]
    missing = [x for x in declared if x not in RAN]
    print(f"CONTROL MANIFEST: declared {len(declared)}, ran {len(RAN)}, "
          f"missing {missing}")
    RES["manifest"] = {"declared": declared, "ran": RAN, "missing": missing}
    RES["seconds"] = round(time.time() - t0, 1)
    assert not missing
    with open(f"{BASE}/results_t3c_n8_rungs.json", "w") as fh:
        json.dump(RES, fh, indent=1, default=str)
    print(f"wrote results_t3c_n8_rungs.json ({RES['seconds']}s)")


if __name__ == "__main__":
    main()
