//! One-pass H18PIV2 scalar fold for D14:222 R2-2-4 and R2-2-2-2.
mod fold {
include!("../unaudited-codex-orbit0-hidden-k16-children-prefix-2026-08-23/run_hidden_children_prefix.rs");
const INPUT:&str="computations/unaudited-codex-orbit0-hidden-k16-k2-full-orbit-2026-08-23/checkpoint_k18_22_pivotable.bin";
const TOTAL:u64=158_439_965;
const DIR:&str="computations/unaudited-codex-orbit0-k22-hidden-collected-k18-2026-08-24/";
#[derive(Clone,Default)]struct K18Plan{q4:i64,k2:Vec<(u8,u8,[u8;12])>}
#[derive(Clone,Copy,Default)]struct Sink{parents:u64,pivots:u64,mid:u64,terminal:u64,charge:i128}
#[derive(Clone,Copy)]struct Parent3{row:Row,weight_before_p3:i128,witness_pair:Row,p2:u8,t2:u8,pair_uses:u64,orbit:u16,stabilizer:u16,m2:u8}
fn decode_parent(rec:&[u8;80])->Parent3{let mut row=[0;24];row.copy_from_slice(&rec[..24]);let mut witness=[0;24];witness.copy_from_slice(&rec[40..64]);assert_eq!(rec[78],1);Parent3{row:Row(row),weight_before_p3:i128::from_le_bytes(rec[24..40].try_into().unwrap()),witness_pair:Row(witness),p2:rec[64],t2:rec[65],pair_uses:u64::from_le_bytes(rec[66..74].try_into().unwrap()),orbit:u16::from_le_bytes(rec[74..76].try_into().unwrap()),stabilizer:u16::from_le_bytes(rec[76..78].try_into().unwrap()),m2:rec[79]}}
fn hex24(row:&Row)->String{row.0.iter().map(|x|format!("{:02x}",x)).collect()}
fn plan18(row:&Row,s:[u8;12],p:usize,prof:[u8;29],e:&Engine,c:&CEnv)->K18Plan{
 let mut q4=0i64;for t in &c.k4[p]{let z=child_sig(s,p,t,e);assert_eq!(z.iter().map(|&x|x as usize).sum::<usize>(),2);assert!(!pivotable_sig(z,e));let ck=abstract_ckey(&prof,p,t,e,c);q4+=*c.dual.get(&ck).unwrap_or(&0)}
 let mut k2=Vec::new();for(ti,t)in e.all_k2[p].iter().enumerate(){let s20=child_sig(s,p,t,e);assert_eq!(s20.iter().map(|&x|x as usize).sum::<usize>(),4);let ps=available(s20,e);if !ps.is_empty(){assert_eq!(ps.len(),1);k2.push((ti as u8,ps[0]as u8,s20))}}
 K18Plan{q4,k2}
}
fn response20(row:&Row,s:[u8;12],p:usize,prof:[u8;29],e:&Engine,c:&CEnv)->i64{let mut q=0;for t in &e.all_k2[p]{let z=child_sig(s,p,t,e);assert_eq!(z.iter().map(|&x|x as usize).sum::<usize>(),2);assert!(!pivotable_sig(z,e));q+=*c.dual.get(&abstract_ckey(&prof,p,t,e,c)).unwrap_or(&0)}q}
fn literal4(row:&Row,s:[u8;12],p:usize,e:&Engine,c:&CEnv)->i64{let mut q=0;for t in &c.k4[p]{let child=replace_anchor(row,&e.anchors[p],t);let z=child_sig(s,p,t,e);assert_eq!(signature(&child.0,e),z);assert!(!pivotable_sig(z,e));q+=*c.dual.get(&literal_ckey(&child,c)).unwrap_or(&0)}q}
fn literal2(row:&Row,s:[u8;12],p:usize,e:&Engine,c:&CEnv)->i64{let mut q=0;for t in &e.all_k2[p]{let child=replace_anchor(row,&e.anchors[p],t);let z=child_sig(s,p,t,e);assert_eq!(signature(&child.0,e),z);assert!(!pivotable_sig(z,e));q+=*c.dual.get(&literal_ckey(&child,c)).unwrap_or(&0)}q}
fn hmap(h:&std::collections::BTreeMap<(u8,u8),u64>)->String{h.iter().map(|(&(a,b),v)|format!("\"{}_{}\":{}",a,b,v)).collect::<Vec<_>>().join(",")}
pub fn run(){let args:Vec<_>=std::env::args().collect();let(mut start,mut count,mut samples)=(0u64,TOTAL,false);let mut output=format!("{}results_k22_hidden_collected_k18.json",DIR);let mut i=1;while i<args.len(){match args[i].as_str(){"--start"=>{start=args[i+1].parse().unwrap();i+=2},"--count"=>{count=args[i+1].parse().unwrap();i+=2},"--samples"=>{samples=true;i+=1},"--output"=>{output=args[i+1].clone();i+=2},_=>panic!("bad argument")}}assert!(count>0&&start<=TOTAL&&count<=TOTAL-start);let begun=Instant::now();let e=parse();let c=cenv();let mut f=File::open(INPUT).unwrap();let mut h=[0u8;80];f.read_exact(&mut h).unwrap();assert_eq!(&h[..8],b"H18PIV2\0");assert_eq!(i128::from_le_bytes(h[8..24].try_into().unwrap()),U);assert_eq!(u16::from_le_bytes(h[28..30].try_into().unwrap()),80);assert_eq!(u64::from_le_bytes(h[48..56].try_into().unwrap()),TOTAL);assert_eq!(u64::from_le_bytes(h[56..64].try_into().unwrap()),1);assert_eq!(i128::from_le_bytes(h[64..80].try_into().unwrap()),724_159_651_336_720_220_160);f.seek(SeekFrom::Start(80+80*start)).unwrap();let mut r=BufReader::with_capacity(16<<20,f);let mut cache18:HashMap<PKey,K18Plan>=HashMap::new();let mut cache20:HashMap<PKey,i64>=HashMap::new();let(mut hit18,mut miss18,mut hit20,mut miss20)=(0u64,0u64,0u64,0u64);let(mut a,mut b)=(Sink::default(),Sink::default());let(mut source_mass,mut source_l1)=(0i128,0i128);let mut hist=std::collections::BTreeMap::new();let sample_indices:HashSet<u64>=if samples{(0..257).map(|j|start+j*(count-1)/256).collect()}else{HashSet::new()};let mut lines=vec!["input_index\trow\twitness_pair\tweight_w2\tm2\tm3\tselected_p3\tR224_children\tR224_charge_scaled_U\tpivotable_K20\tselected_p4\tR2222_children\tR2222_charge_scaled_U".to_string()];
 for off in 0..count{let idx=start+off;let mut rec=[0u8;80];r.read_exact(&mut rec).unwrap();let x=decode_parent(&rec);let s=signature(&x.row.0,&e);assert_eq!(s.iter().map(|&z|z as usize).sum::<usize>(),6);let ps=available(s,&e);let m3=ps.len();assert!(m3>0);assert_eq!(x.weight_before_p3%(m3 as i128),0);assert_eq!(U%((x.m2 as i128)*(m3 as i128)),0);source_mass+=x.weight_before_p3;source_l1+=x.weight_before_p3.abs();a.parents+=1;b.parents+=1;let wa=-x.weight_before_p3/(m3 as i128);let mut sample_a=0i128;let mut sample_b=0i128;let(mut smid,mut sp4,mut sbn)=(0u64,0u64,0u64);
  for p3 in ps{a.pivots+=1;let prof=path_profile(&x.row,p3,&e,&c);let key=PKey{profile:prof,sig:s,pivot:p3 as u8};let plan=if let Some(z)=cache18.get(&key){hit18+=1;z.clone()}else{miss18+=1;let z=plan18(&x.row,s,p3,prof,&e,&c);cache18.insert(key,z.clone());z};a.terminal+=60;a.charge+=wa*(plan.q4 as i128);if sample_indices.contains(&idx){assert_eq!(literal4(&x.row,s,p3,&e,&c),plan.q4);sample_a+=wa*(plan.q4 as i128)}
   for(ti,p4,s20)in plan.k2{b.mid+=1;smid+=1;let row20=replace_anchor(&x.row,&e.anchors[p3],&e.all_k2[p3][ti as usize]);assert_eq!(signature(&row20.0,&e),s20);let ps4=available(s20,&e);assert_eq!(ps4,vec![p4 as usize]);let m4=ps4.len();assert_eq!(x.weight_before_p3%((m3*m4)as i128),0);b.pivots+=1;sp4+=1;let prof20=path_profile(&row20,p4 as usize,&e,&c);let k20=PKey{profile:prof20,sig:s20,pivot:p4};let q=if let Some(&z)=cache20.get(&k20){hit20+=1;z}else{miss20+=1;let z=response20(&row20,s20,p4 as usize,prof20,&e,&c);cache20.insert(k20,z);z};let wb=x.weight_before_p3/((m3*m4)as i128);b.terminal+=12;sbn+=12;b.charge+=wb*(q as i128);if sample_indices.contains(&idx){assert_eq!(literal2(&row20,s20,p4 as usize,&e,&c),q);sample_b+=wb*(q as i128)}*hist.entry((x.m2,m3 as u8)).or_default()+=1;
   }}
  if sample_indices.contains(&idx){lines.push(format!("{}\t{}\t{}\t{}\t{}\t{}\t{}\t{}\t{}\t{}\t{}\t{}\t{}",idx,hex24(&x.row),hex24(&x.witness_pair),x.weight_before_p3,x.m2,m3,m3,60*m3,sample_a,smid,sp4,sbn,sample_b))}
 }
 assert_eq!(a.parents,count);assert_eq!(a.terminal,60*a.pivots);assert_eq!(b.parents,count);assert_eq!(b.mid,b.pivots);assert_eq!(b.terminal,12*b.pivots);if start==0&&count==TOTAL{assert_eq!(source_mass,724_159_651_336_720_220_160);assert_eq!(a.pivots,399_275_484);assert_eq!(a.terminal,23_956_529_040);assert_eq!(b.mid,570_281_318);assert_eq!(lines.len(),if samples{258}else{1})}let elapsed=begun.elapsed().as_secs_f64();if start==0&&count==TOTAL{assert!(elapsed<600.0,"hard 600-second gate exceeded")}let projected=elapsed*TOTAL as f64/count as f64;let status=if start==0&&count==TOTAL{"PASS_COMPLETE_TWO_SINK_HIDDEN_COLLECTED_K18_K22_CHARGE"}else{"PASS_BOUNDED_TWO_SINK_HIDDEN_COLLECTED_K18_K22_GATE"};let sample_path=format!("{}.samples.tsv",output);if samples{let tmp=format!("{}.tmp",sample_path);std::fs::write(&tmp,format!("{}\n",lines.join("\n"))).unwrap();rename(tmp,&sample_path).unwrap()}let text=format!("{{\n  \"status\":\"{}\",\n  \"scale_U\":\"{}\",\n  \"input\":\"{}\",\n  \"input_interval\":[{},{}],\n  \"input_records\":{},\n  \"input_weight_sum_scaled_U\":\"{}\",\n  \"input_weight_l1_scaled_U\":\"{}\",\n  \"sinks\":{{\n    \"D14:222|R:2-2-4\":{{\"selected_K18_pivots\":{},\"terminal_K4_tails\":{},\"full_occurrences\":{},\"irreducible_occurrences\":{},\"full_charge_scaled_U\":\"{}\",\"irreducible_charge_scaled_U\":\"{}\",\"sign\":\"-w2/m3\"}},\n    \"D14:222|R:2-2-2-2\":{{\"pivotable_K20_children\":{},\"selected_K20_pivots\":{},\"terminal_K2_tails\":{},\"full_occurrences\":{},\"irreducible_occurrences\":{},\"full_charge_scaled_U\":\"{}\",\"irreducible_charge_scaled_U\":\"{}\",\"sign\":\"+w2/(m3*m4)\"}}\n  }},\n  \"cache\":{{\"K18_keys\":{},\"K18_hits\":{},\"K18_misses\":{},\"K20_keys\":{},\"K20_hits\":{},\"K20_misses\":{}}},\n  \"m2_m3_pivotable_K20_hist\":{{{}}},\n  \"literal_samples\":{},\n  \"literal_sample_ledger\":{},\n  \"terminality\":\"both K22 sinks have anchor-signature mass 2, below every pivot mass 4\",\n  \"scope\":\"two separately named K22 scalar sinks only; no parent-row output, K23, or K24\",\n  \"elapsed_seconds\":{:.6},\n  \"projected_full_seconds\":{:.6}\n}}\n",status,U,INPUT,start,start+count,count,source_mass,source_l1,a.pivots,a.terminal,a.terminal,a.terminal,a.charge,a.charge,b.mid,b.pivots,b.terminal,b.terminal,b.terminal,b.charge,b.charge,cache18.len(),hit18,miss18,cache20.len(),hit20,miss20,hmap(&hist),if samples{sample_indices.len()}else{0},if samples{format!("\"{}\"",sample_path)}else{"null".to_string()},elapsed,projected);let tmp=format!("{}.tmp",output);std::fs::write(&tmp,&text).unwrap();rename(tmp,&output).unwrap();print!("{}",text)}
}
fn main(){fold::run()}
