//! Exact remainder-rooted literal-provider screen and capped projected shell.
use std::collections::{BTreeMap,HashMap,HashSet};
use std::fs::{File,read,read_to_string};
use std::io::{BufReader,BufWriter,Read,Write};
use std::time::{Duration,Instant};

const ROOT:&str="computations/unaudited-codex-orbit0-filtered-k17-census-2026-08-23/";
const INPUT:&str="computations/unaudited-codex-orbit0-filtered-k16-run-2026-08-23/checkpoint_reduced_k17.bin";
const REMAINDER:&str="computations/unaudited-codex-orbit0-k17-colour-content-rank-referee-2026-08-23/target_remainder_common_support.tsv";
const OUTDIR:&str="computations/unaudited-codex-orbit0-k17-colour-content-remainder-shell-2026-08-23/";
const LIMIT:usize=100_000;
const CAP:Duration=Duration::from_secs(180);
const PERMS:[[usize;3];6]=[[0,1,2],[0,2,1],[1,0,2],[1,2,0],[2,0,1],[2,1,0]];

#[derive(Clone,Copy,Eq,Hash,Ord,PartialEq,PartialOrd)]struct ContentKey([u8;37]);
fn cell_decode(mut id:u8)->(u8,u8,u8,u8){let colour=id%9;id/=9;let a=colour/3;let b=colour%3;let mut u=0u8;while id>=7-u{id-=7-u;u+=1}(u,u+1+id,a,b)}
fn cell_id(u:usize,v:usize,a:u8,b:u8)->u8{let edge=u*(15-u)/2+(v-u-1);(9*edge+3*a as usize+b as usize)as u8}
fn key_text(k:&ContentKey)->String{(0..k.0[0]as usize).map(|i|format!("{}:{}:{}",k.0[1+3*i],k.0[2+3*i],k.0[3+3*i])).collect::<Vec<_>>().join(";")}
fn parse_key(text:&str)->ContentKey{let components:Vec<[u8;3]>=text.split(';').map(|part|{let values:Vec<u8>=part.split(':').map(|x|x.parse().unwrap()).collect();[values[0],values[1],values[2]]}).collect();let mut key=[0u8;37];key[0]=components.len()as u8;for(i,c)in components.iter().enumerate(){key[1+3*i..4+3*i].copy_from_slice(c)}ContentKey(key)}
fn content_key(row:&[u8;24])->ContentKey{let mut adj=[[0u8;2];24];let mut deg=[0usize;24];for &cell in row{let(u,v,a,b)=cell_decode(cell);let x=(3*u+a)as usize;let y=(3*v+b)as usize;adj[x][deg[x]]=y as u8;deg[x]+=1;adj[y][deg[y]]=x as u8;deg[y]+=1}assert!(deg.iter().all(|&x|x==2));let mut seen=[false;24];let mut raw=[[0u8;3];12];let mut nc=0usize;for start in 0..24{if seen[start]{continue}let mut stack=[0u8;24];let mut top=1usize;stack[0]=start as u8;seen[start]=true;while top>0{top-=1;let x=stack[top]as usize;raw[nc][x%3]+=1;for &yy in &adj[x]{let y=yy as usize;if !seen[y]{seen[y]=true;stack[top]=yy;top+=1}}}nc+=1}let mut best=None;for perm in PERMS{let mut comps=Vec::with_capacity(nc);for source in &raw[..nc]{let mut target=[0u8;3];for old in 0..3{target[perm[old]]=source[old]}comps.push(target)}comps.sort_unstable();let mut key=[0u8;37];key[0]=nc as u8;for(i,c)in comps.iter().enumerate(){key[1+3*i..4+3*i].copy_from_slice(c)}if best.map_or(true,|old|key<old){best=Some(key)}}ContentKey(best.unwrap())}
fn perfect_matchings(vertices:&[usize],out:&mut Vec<Vec<(usize,usize)>>,prefix:&mut Vec<(usize,usize)>){if vertices.is_empty(){out.push(prefix.clone());return}let first=vertices[0];for i in 1..vertices.len(){let second=vertices[i];let mut rest=Vec::with_capacity(vertices.len()-2);rest.extend_from_slice(&vertices[1..i]);rest.extend_from_slice(&vertices[i+1..]);prefix.push((first,second));perfect_matchings(&rest,out,prefix);prefix.pop();}}
fn term(word:&[u8;8],matching:&[(usize,usize)],anchors:&[bool;252])->([u8;4],u8){let mut row=[0u8;4];for(i,&(u,v))in matching.iter().enumerate(){row[i]=cell_id(u,v,word[u],word[v])}row.sort_unstable();let k=row.iter().filter(|&&c|!anchors[c as usize]).count()as u8;(row,k)}
fn remove_term(row:&[u8;24],selected:&[u8;4])->[u8;20]{let mut out=[0u8;20];let(mut si,mut oi)=(0usize,0usize);for &cell in row{if si<4&&cell==selected[si]{si+=1}else{out[oi]=cell;oi+=1}}assert_eq!((si,oi),(4,20));out}
fn make_row(mult:&[u8;20],term:&[u8;4])->[u8;24]{let mut row=[0u8;24];row[..20].copy_from_slice(mult);row[20..].copy_from_slice(term);row.sort_unstable();row}
fn encode_vector(vector:&BTreeMap<ContentKey,u16>)->Vec<u8>{let mut out=Vec::with_capacity(2+39*vector.len());out.extend_from_slice(&(vector.len()as u16).to_le_bytes());for(key,value)in vector{out.extend_from_slice(&key.0);out.extend_from_slice(&value.to_le_bytes())}out}
fn decode_vector(encoded:&[u8])->Vec<(ContentKey,u16)>{let n=u16::from_le_bytes([encoded[0],encoded[1]])as usize;let mut out=Vec::with_capacity(n);let mut p=2;for _ in 0..n{let mut key=[0u8;37];key.copy_from_slice(&encoded[p..p+37]);p+=37;let value=u16::from_le_bytes([encoded[p],encoded[p+1]]);p+=2;out.push((ContentKey(key),value))}assert_eq!(p,encoded.len());out}

fn options(row:&[u8;24])->[Vec<u8>;28]{let mut out:[Vec<u8>;28]=std::array::from_fn(|_|Vec::new());for &cell in row{let(u,v,_,_)=cell_decode(cell);let edge=(u as usize)*(15-u as usize)/2+(v-u-1)as usize;if !out[edge].contains(&cell){out[edge].push(cell)}}for x in &mut out{x.sort_unstable()}out}
fn provider_label(row:&[u8;24],selected:&[u8;4],word:&[u8;8])->[u8;28]{let multiplier=remove_term(row,selected);let mut label=[0u8;28];label[..8].copy_from_slice(word);label[8..].copy_from_slice(&multiplier);label}

fn screen_row(row:&[u8;24],providers:&mut HashSet<[u8;28]>){let opts=options(row);fn go(row:&[u8;24],opts:&[Vec<u8>;28],mask:u16,selected:&mut Vec<u8>,word:&mut[u8;8],providers:&mut HashSet<[u8;28]>){if providers.len()>=2{return}if mask==0xff{if !word.iter().all(|&x|x==word[0]){let mut chosen=[0u8;4];chosen.copy_from_slice(selected);chosen.sort_unstable();providers.insert(provider_label(row,&chosen,word));}return}let u=(0..8).find(|&i|mask&(1<<i)==0).unwrap();for v in u+1..8{if mask&(1<<v)!=0{continue}let edge=u*(15-u)/2+(v-u-1);for &cell in &opts[edge]{let(_,_,a,b)=cell_decode(cell);word[u]=a;word[v]=b;selected.push(cell);go(row,opts,mask|(1<<u)|(1<<v),selected,word,providers);selected.pop();if providers.len()>=2{return}}}}go(row,&opts,0,&mut Vec::new(),&mut[0u8;8],providers)}

struct State{wanted:HashSet<ContentKey>,profiles:HashSet<Vec<u8>>,coordinates:HashSet<ContentKey>,matchings:Vec<Vec<(usize,usize)>>,cache:HashMap<[u8;8],Vec<([u8;4],u8)>>,anchors:[bool;252],columns:u64,pure:u64,k_hist:[u64;5],cap:Option<&'static str>,start:Instant}
impl State{
 fn visit(&mut self,row:&[u8;24],selected:[u8;4],word:[u8;8]){if self.cap.is_some(){return}if word.iter().all(|&x|x==word[0]){self.pure+=1;return}let selected_k=selected.iter().filter(|&&c|!self.anchors[c as usize]).count()as u8;let multiplier=remove_term(row,&selected);if !self.cache.contains_key(&word){self.cache.insert(word,self.matchings.iter().map(|m|term(&word,m,&self.anchors)).collect());}let mut vector=BTreeMap::new();for(term,k)in &self.cache[&word]{if *k==selected_k{*vector.entry(content_key(&make_row(&multiplier,term))).or_insert(0u16)+=1}}assert!(!vector.is_empty());self.columns+=1;self.k_hist[selected_k as usize]+=1;let encoded=encode_vector(&vector);if self.profiles.insert(encoded){for key in vector.keys(){self.coordinates.insert(*key);}if self.profiles.len()>=LIMIT{self.cap=Some("100000_distinct_vectors")}else if self.coordinates.len()>=LIMIT{self.cap=Some("100000_coordinates")}}if self.start.elapsed()>=CAP{self.cap=Some("180_second_cap")}}
 fn row(&mut self,row:&[u8;24]){let opts=options(row);fn go(state:&mut State,row:&[u8;24],opts:&[Vec<u8>;28],mask:u16,selected:&mut Vec<u8>,word:&mut[u8;8]){if state.cap.is_some(){return}if mask==0xff{let mut chosen=[0u8;4];chosen.copy_from_slice(selected);chosen.sort_unstable();state.visit(row,chosen,*word);return}let u=(0..8).find(|&i|mask&(1<<i)==0).unwrap();for v in u+1..8{if mask&(1<<v)!=0{continue}let edge=u*(15-u)/2+(v-u-1);for &cell in &opts[edge]{let(_,_,a,b)=cell_decode(cell);word[u]=a;word[v]=b;selected.push(cell);go(state,row,opts,mask|(1<<u)|(1<<v),selected,word);selected.pop();if state.cap.is_some(){return}}}}go(self,row,&opts,0,&mut Vec::new(),&mut[0u8;8])}
}

fn open_rows()->(BufReader<File>,u64){let mut r=BufReader::with_capacity(1<<22,File::open(INPUT).unwrap());let mut magic=[0u8;8];r.read_exact(&mut magic).unwrap();assert_eq!(&magic,b"K17RED2\0");let mut nb=[0u8;8];r.read_exact(&mut nb).unwrap();(r,u64::from_le_bytes(nb))}
fn main(){let start=Instant::now();let remainder_lines=read_to_string(REMAINDER).unwrap();let wanted:HashSet<_>=remainder_lines.lines().skip(1).map(|line|parse_key(line.split('\t').nth(1).unwrap())).collect();assert_eq!(wanted.len(),4612);
    // Exhaustive low-incidence screen: keep at most two distinct literal source labels per coordinate.
    let mut providers:HashMap<ContentKey,HashSet<[u8;28]>>=wanted.iter().map(|&k|(k,HashSet::new())).collect();let mut row_hits:HashMap<ContentKey,u64>=wanted.iter().map(|&k|(k,0)).collect();let(mut reader,n)=open_rows();for _ in 0..n{let mut row=[0u8;24];let mut value=[0u8;16];reader.read_exact(&mut row).unwrap();reader.read_exact(&mut value).unwrap();let key=content_key(&row);if let Some(count)=row_hits.get_mut(&key){*count+=1;let set=providers.get_mut(&key).unwrap();if set.len()<2{screen_row(&row,set)}}}let zero=providers.values().filter(|x|x.is_empty()).count();let unique=providers.values().filter(|x|x.len()==1).count();let multiple=providers.values().filter(|x|x.len()>=2).count();
    let mut screen=BufWriter::new(File::create(format!("{}remainder_provider_screen.tsv",OUTDIR)).unwrap());writeln!(screen,"colour_content_type\ttarget_rows\tdistinct_literal_provider_lower_bound").unwrap();let mut keys:Vec<_>=wanted.iter().copied().collect();keys.sort_unstable();for key in &keys{writeln!(screen,"{}\t{}\t{}",key_text(key),row_hits[key],providers[key].len()).unwrap()}screen.flush().unwrap();
    // Capped full-vector census rooted only at remainder coordinates.
    let coord_lines=read_to_string(format!("{}k17_colour_content_first_shell_coordinates.tsv",ROOT)).unwrap();let initial:HashSet<_>=coord_lines.lines().skip(1).map(|line|parse_key(line.split('\t').nth(1).unwrap())).collect();assert_eq!(initial.len(),16412);let frozen=[0u8,4,8,117,121,125,198,202,206,243,247,251];let structure=read("computations/unaudited-codex-orbit0-filtered-k16-run-2026-08-23/filtered_k16_structure.bin").unwrap();assert_eq!(&structure[27..39],&frozen);let mut anchors=[false;252];for &c in &frozen{anchors[c as usize]=true}let mut matchings=Vec::new();perfect_matchings(&(0..8).collect::<Vec<_>>(),&mut matchings,&mut Vec::new());let mut state=State{wanted:wanted.clone(),profiles:HashSet::new(),coordinates:initial,matchings,cache:HashMap::new(),anchors,columns:0,pure:0,k_hist:[0;5],cap:None,start};let(mut reader,n)=open_rows();let mut processed=0u64;let mut rooted_rows=0u64;while processed<n&&state.cap.is_none(){let mut row=[0u8;24];let mut value=[0u8;16];reader.read_exact(&mut row).unwrap();reader.read_exact(&mut value).unwrap();let key=content_key(&row);if state.wanted.contains(&key){rooted_rows+=1;state.row(&row)}processed+=1}
    let mut coordinates:Vec<_>=state.coordinates.iter().copied().collect();coordinates.sort_unstable();let index:HashMap<_,_>=coordinates.iter().enumerate().map(|(i,k)|(*k,i)).collect();let mut cw=BufWriter::new(File::create(format!("{}remainder_shell_coordinates.tsv",OUTDIR)).unwrap());writeln!(cw,"coordinate_id\tcolour_content_type").unwrap();for(i,k)in coordinates.iter().enumerate(){writeln!(cw,"{}\t{}",i,key_text(k)).unwrap()}cw.flush().unwrap();let mut profiles:Vec<_>=state.profiles.into_iter().collect();profiles.sort_unstable();let mut vw=BufWriter::new(File::create(format!("{}remainder_shell_vectors.tsv",OUTDIR)).unwrap());writeln!(vw,"vector_id\tsparse_integer_vector").unwrap();let mut total_nnz=0usize;for(i,encoded)in profiles.iter().enumerate(){let vector=decode_vector(encoded);total_nnz+=vector.len();let text=vector.iter().map(|(k,v)|format!("{}:{}",index[k],v)).collect::<Vec<_>>().join(",");writeln!(vw,"{}\t{}",i,text).unwrap()}vw.flush().unwrap();let terminal=state.cap.unwrap_or("complete_all_55191349_rows");let status=if state.cap.is_none(){"PASS_COMPLETE_REMAINDER_ROOTED_SHELL"}else{"BOUNDED_CAP"};let result=format!("{{\n  \"status\":\"{}\",\n  \"terminal\":\"{}\",\n  \"low_incidence_screen\":{{\"scope\":\"all 55191349 checkpoint rows\",\"zero_provider_coordinates\":{},\"unique_provider_coordinates\":{},\"at_least_two_provider_coordinates\":{},\"target_row_incidence_sum\":{}}},\n  \"census\":{{\"checkpoint_rows_processed\":{},\"remainder_rooted_rows\":{},\"literal_mixed_source_columns_visited\":{},\"pure_skipped\":{},\"distinct_projected_vectors\":{},\"coordinates\":{},\"new_coordinates\":{},\"vector_nnz\":{},\"K_histogram\":[{},{},{},{},{}]}},\n  \"elapsed_seconds\":{:.3},\n  \"scope\":\"Literal mixed-word K17 same-filtration providers rooted at the 4612 common modular remainder coordinates; finite low-incidence screen exhaustive, projected shell subject to stated cap; no full-shell/nonmembership inference.\"\n}}\n",status,terminal,zero,unique,multiple,row_hits.values().sum::<u64>(),processed,rooted_rows,state.columns,state.pure,profiles.len(),coordinates.len(),coordinates.len()-16412,total_nnz,state.k_hist[0],state.k_hist[1],state.k_hist[2],state.k_hist[3],state.k_hist[4],start.elapsed().as_secs_f64());File::create(format!("{}results_remainder_shell.json",OUTDIR)).unwrap().write_all(result.as_bytes()).unwrap();print!("{}",result)}
