#!/usr/bin/env python3
"""Mechanically derive final rep4 runner from its pinned hardened group runner."""
import hashlib,os
from pathlib import Path
HERE=Path(__file__).resolve().parent;ROOT=HERE.parents[1];BASE=ROOT/'computations/unaudited-codex-n8-x5-rep4-groups76-125-exact-q-conditional-held-2026-08-26/run_groups76_125.py';BASE_SHA='3e5a744b6017dc0ba4a4d9789039bb4697d20fd1b42332195dc015cfd1e91abd';VERIFIER_SHA='fc44d47caef2915dc8cf7dc384d544e8c858e4be8de372b08d01a30abb3b90eb'
def sha(path):return hashlib.sha256(path.read_bytes()).hexdigest()
assert sha(BASE)==BASE_SHA;text=BASE.read_text();changes=[]
def once(old,new,label):
 global text
 assert text.count(old)==1,(label,text.count(old));text=text.replace(old,new);changes.append(label)
once('"""Conditional refusal-locked sequential rep4 groups76..125 exact-Q runner."""','"""Final provenance-replaying sequential rep4 groups126..161 exact-Q runner."""','doc')
old="HERE=Path(__file__).resolve().parent;ROOT=HERE.parents[1];LEDGER=HERE/'source_ledger.json';NORMALIZED=HERE/'normalized_dependencies.json';SINGULAR=Path('/usr/local/bin/Singular');GTIMEOUT=Path('/usr/local/bin/gtimeout');LEDGER_SHA='b311e566fab04932f0c49a285ac3190ae4ac7a02f102799a9a2c6b34a949e4bb';SINGULAR_SHA="
new="HERE=Path(__file__).resolve().parent;ROOT=HERE.parents[1];LEDGER=HERE/'source_ledger.json';FUTURE=HERE/'future_dependencies.json';VERIFIER=HERE/'dependency_verifier.py';NORMALIZED=HERE/'normalized_dependencies.json';SINGULAR=Path('/usr/local/bin/Singular');GTIMEOUT=Path('/usr/local/bin/gtimeout');LEDGER_SHA='fa301fd4d1e61626781cedd3ecb362189671b042c9cba8cfbe68977bb79ceb38';FUTURE_SHA='18b7cae58e965187bcbb97ef7a319aacd92fccb6be4010d9630caad83ef77e75';VERIFIER_SHA='"+VERIFIER_SHA+"';SINGULAR_SHA=";once(old,new,'paths_pins')
once('SELECTED=tuple(range(76,126))','SELECTED=tuple(range(126,162))','selection')
old="assert sha(LEDGER)==LEDGER_SHA and sha(SINGULAR)==SINGULAR_SHA and sha(GTIMEOUT)==GTIMEOUT_SHA;assert NORMALIZED.is_file(),'HELD: future PASS groups1..25 and26..75 dependencies have not been normalized';dep=json.loads(NORMALIZED.read_text());assert dep['schema']=='KRENN_X5_REP4_GROUPS76_125_NORMALIZED_DEPENDENCIES_V1' and dep['status']=='PASS_NORMALIZED_EXACT_CLOSED_UNION_0_75' and dep['groups_closed_by_first']==list(range(1,26)) and dep['groups_closed_by_middle']==list(range(26,76)) and dep['closed_union']==list(range(76)) and dep['duplicates']==dep['missing']==dep['extra']==[]\nfor rel,want in zip(dep['dependency_manifest_paths'],dep['dependency_manifest_sha256']):assert sha(ROOT/rel)==want\nfor rel,want in zip(dep['dependency_result_paths'],dep['dependency_result_sha256']):assert sha(ROOT/rel)==want"
new="assert sha(LEDGER)==LEDGER_SHA and sha(FUTURE)==FUTURE_SHA and sha(VERIFIER)==VERIFIER_SHA and sha(SINGULAR)==SINGULAR_SHA and sha(GTIMEOUT)==GTIMEOUT_SHA;assert NORMALIZED.is_file(),'HELD: all three future dependencies have not been normalized';dep=json.loads(NORMALIZED.read_text());assert dep['schema']=='KRENN_X5_REP4_GROUPS126_161_NORMALIZED_DEPENDENCIES_V1' and dep['status']=='PASS_NORMALIZED_EXACT_CLOSED_UNION_0_125' and dep['groups_closed_by_first']==list(range(1,26)) and dep['groups_closed_by_middle']==list(range(26,76)) and dep['groups_closed_by_third']==list(range(76,126)) and dep['closed_union']==list(range(126)) and dep['duplicates']==dep['missing']==dep['extra']==[]\nfrom dependency_verifier import verify_payload\nreplay=verify_payload(json.loads(FUTURE.read_text()),dep,ROOT);assert replay['status']=='PASS_REPLAYED_ALL_SIX_DEPENDENCY_ARTIFACTS_EXACT_UNION_0_125' and replay['closed_union']==list(range(126))"
once(old,new,'three_dependency_replay')
once("[x['ordinal'] for x in lanes]==list(range(1,51))","[x['ordinal'] for x in lanes]==list(range(1,37))",'lane_count')
text=text.replace('KRENN_X5_REP4_GROUPS76_125','KRENN_X5_REP4_GROUPS126_161');changes.append('schemas');text=text.replace('CONDITIONAL_REP4_GROUPS76_125_ONLY','CONDITIONAL_REP4_GROUPS126_161_ONLY');changes.append('statuses')
assert text.count("'required_closed_union':list(range(76))")==3;text=text.replace("'required_closed_union':list(range(76))","'required_closed_union':list(range(126))");changes.append('closed_union')
assert text.count("'maximum_lane_count':50")==2;text=text.replace("'maximum_lane_count':50","'maximum_lane_count':36");changes.append('max_lanes')
old_pin="'source_ledger_sha256':LEDGER_SHA,'normalized_dependencies_sha256':dep_sha";new_pin="'source_ledger_sha256':LEDGER_SHA,'dependency_verifier_sha256':VERIFIER_SHA,'normalized_dependencies_sha256':dep_sha";assert text.count(old_pin)==2;text=text.replace(old_pin,new_pin);changes.append('acceptance_clearance_verifier_pins')
once("'status':'PASS_ALL_50_UNIT'","'status':'PASS_ALL_36_UNIT'",'batch_status');tmp=HERE/'run_groups126_161.py.tmp';tmp.write_text(text);os.replace(tmp,HERE/'run_groups126_161.py');print({'status':'PASS_DERIVED_FINAL_REP4_RUNNER_ZERO_RUN','changes':changes,'runner_sha256':sha(HERE/'run_groups126_161.py')})
