//! Target-rooted literal K17 source-vector profile census; hard stop at 100k.
use std::collections::{BTreeMap,HashMap,HashSet};
use std::fs::{File,read_to_string};
use std::io::{BufReader,BufWriter,Read,Write};
use std::time::{Duration,Instant};

const INPUT:&str="computations/unaudited-codex-orbit0-filtered-k16-run-2026-08-23/checkpoint_reduced_k17.bin";
const TARGET:&str="computations/unaudited-codex-orbit0-filtered-k17-census-2026-08-23/k17_colour_content_target.tsv";
const COORDS:&str="computations/unaudited-codex-orbit0-filtered-k17-census-2026-08-23/k17_colour_content_first_shell_coordinates.tsv";
const VECTORS:&str="computations/unaudited-codex-orbit0-filtered-k17-census-2026-08-23/k17_colour_content_first_shell_vectors.tsv";
const RESULT:&str="computations/unaudited-codex-orbit0-filtered-k17-census-2026-08-23/results_k17_colour_content_first_shell.json";
const LIMIT:usize=100_000;
const CAP:Duration=Duration::from_secs(150);
const PERMS:[[usize;3];6]=[[0,1,2],[0,2,1],[1,0,2],[1,2,0],[2,0,1],[2,1,0]];

#[derive(Clone,Copy,Eq,Hash,Ord,PartialEq,PartialOrd)]struct ContentKey([u8;37]);
fn cell_decode(mut id:u8)->(u8,u8,u8,u8){let colour=id%9;id/=9;let a=colour/3;let b=colour%3;let mut u=0u8;while id>=7-u{id-=7-u;u+=1}(u,u+1+id,a,b)}
fn cell_id(u:usize,v:usize,a:u8,b:u8)->u8{let edge=u*(15-u)/2+(v-u-1);(9*edge+3*a as usize+b as usize)as u8}
fn key_text(k:&ContentKey)->String{(0..k.0[0]as usize).map(|i|format!("{}:{}:{}",k.0[1+3*i],k.0[2+3*i],k.0[3+3*i])).collect::<Vec<_>>().join(";")}
fn parse_key(text:&str)->ContentKey{let components:Vec<[u8;3]>=text.split(';').map(|part|{let values:Vec<u8>=part.split(':').map(|x|x.parse().unwrap()).collect();[values[0],values[1],values[2]]}).collect();let mut key=[0u8;37];key[0]=components.len()as u8;for(i,c)in components.iter().enumerate(){key[1+3*i..4+3*i].copy_from_slice(c)}ContentKey(key)}
fn content_key(row:&[u8;24])->ContentKey{let mut adjacency=[[0u8;2];24];let mut degree=[0usize;24];for &cell in row{let(u,v,a,b)=cell_decode(cell);let x=(3*u+a)as usize;let y=(3*v+b)as usize;adjacency[x][degree[x]]=y as u8;degree[x]+=1;adjacency[y][degree[y]]=x as u8;degree[y]+=1}assert!(degree.iter().all(|&x|x==2));let mut seen=[false;24];let mut raw=[[0u8;3];12];let mut nc=0usize;for start in 0..24{if seen[start]{continue}let mut stack=[0u8;24];let mut top=1usize;stack[0]=start as u8;seen[start]=true;while top>0{top-=1;let x=stack[top]as usize;raw[nc][x%3]+=1;for &yy in &adjacency[x]{let y=yy as usize;if !seen[y]{seen[y]=true;stack[top]=yy;top+=1}}}nc+=1}let mut best=None;for perm in PERMS{let mut comps=Vec::with_capacity(nc);for source in &raw[..nc]{let mut target=[0u8;3];for old in 0..3{target[perm[old]]=source[old]}comps.push(target)}comps.sort_unstable();let mut key=[0u8;37];key[0]=nc as u8;for(i,c)in comps.iter().enumerate(){key[1+3*i..4+3*i].copy_from_slice(c)}if best.map_or(true,|old|key<old){best=Some(key)}}ContentKey(best.unwrap())}
fn perfect_matchings(vertices:&[usize],out:&mut Vec<Vec<(usize,usize)>>,prefix:&mut Vec<(usize,usize)>){if vertices.is_empty(){out.push(prefix.clone());return}let first=vertices[0];for i in 1..vertices.len(){let second=vertices[i];let mut rest=Vec::with_capacity(vertices.len()-2);rest.extend_from_slice(&vertices[1..i]);rest.extend_from_slice(&vertices[i+1..]);prefix.push((first,second));perfect_matchings(&rest,out,prefix);prefix.pop();}}
fn term(word:&[u8;8],matching:&[(usize,usize)],anchors:&[bool;252])->([u8;4],u8){let mut row=[0u8;4];for(i,&(u,v))in matching.iter().enumerate(){row[i]=cell_id(u,v,word[u],word[v])}row.sort_unstable();let k=row.iter().filter(|&&c|!anchors[c as usize]).count()as u8;(row,k)}
fn remove_term(row:&[u8;24],selected:&[u8;4])->[u8;20]{let mut out=[0u8;20];let(mut si,mut oi)=(0usize,0usize);for &cell in row{if si<4&&cell==selected[si]{si+=1}else{out[oi]=cell;oi+=1}}assert_eq!((si,oi),(4,20));out}
fn make_row(mult:&[u8;20],term:&[u8;4])->[u8;24]{let mut row=[0u8;24];row[..20].copy_from_slice(mult);row[20..].copy_from_slice(term);row.sort_unstable();row}
fn encode_vector(vector:&BTreeMap<ContentKey,u16>)->Vec<u8>{let mut out=Vec::with_capacity(2+39*vector.len());out.extend_from_slice(&(vector.len()as u16).to_le_bytes());for(key,value)in vector{out.extend_from_slice(&key.0);out.extend_from_slice(&value.to_le_bytes())}out}
fn decode_vector(encoded:&[u8])->Vec<(ContentKey,u16)>{let n=u16::from_le_bytes([encoded[0],encoded[1]])as usize;let mut out=Vec::with_capacity(n);let mut p=2;for _ in 0..n{let mut key=[0u8;37];key.copy_from_slice(&encoded[p..p+37]);p+=37;let value=u16::from_le_bytes([encoded[p],encoded[p+1]]);p+=2;out.push((ContentKey(key),value))}assert_eq!(p,encoded.len());out}

struct State{profiles:HashSet<Vec<u8>>,coordinates:HashSet<ContentKey>,target:HashMap<ContentKey,(String,String)>,matchings:Vec<Vec<(usize,usize)>>,completion_cache:HashMap<[u8;8],Vec<([u8;4],u8)>>,anchors:[bool;252],columns:u64,pure_skips:u64,k_hist:[u64;5],cap:Option<&'static str>,start:Instant}
impl State{
 fn visit(&mut self,row:&[u8;24],selected:[u8;4],word:[u8;8]){if self.cap.is_some(){return}if word.iter().all(|&x|x==word[0]){self.pure_skips+=1;return}let selected_k=selected.iter().filter(|&&c|!self.anchors[c as usize]).count()as u8;let multiplier=remove_term(row,&selected);if !self.completion_cache.contains_key(&word){let completions=self.matchings.iter().map(|m|term(&word,m,&self.anchors)).collect();self.completion_cache.insert(word,completions);}let completions=&self.completion_cache[&word];let mut vector=BTreeMap::new();for(term,k)in completions.iter(){if *k!=selected_k{continue}let child=make_row(&multiplier,term);*vector.entry(content_key(&child)).or_insert(0u16)+=1}assert!(!vector.is_empty());self.columns+=1;self.k_hist[selected_k as usize]+=1;let encoded=encode_vector(&vector);if self.profiles.insert(encoded){for key in vector.keys(){self.coordinates.insert(*key);}if self.profiles.len()>=LIMIT{self.cap=Some("100000_distinct_vectors")}else if self.coordinates.len()>=LIMIT{self.cap=Some("100000_coordinates")}}if self.start.elapsed()>=CAP{self.cap=Some("150_second_cap")}}
 fn divisors(&mut self,row:&[u8;24]){let mut options:[Vec<u8>;28]=std::array::from_fn(|_|Vec::new());for &cell in row{let(u,v,_,_)=cell_decode(cell);let edge=(u as usize)*(15-u as usize)/2+(v-u-1)as usize;if !options[edge].contains(&cell){options[edge].push(cell)}}for x in &mut options{x.sort_unstable()}fn go(state:&mut State,row:&[u8;24],options:&[Vec<u8>;28],mask:u16,selected:&mut Vec<u8>,word:&mut[u8;8]){if state.cap.is_some(){return}if mask==0xff{let mut term=[0u8;4];term.copy_from_slice(selected);term.sort_unstable();state.visit(row,term,*word);return}let u=(0..8).find(|&i|mask&(1<<i)==0).unwrap();for v in u+1..8{if mask&(1<<v)!=0{continue}let edge=u*(15-u)/2+(v-u-1);for &cell in &options[edge]{let(_,_,a,b)=cell_decode(cell);word[u]=a;word[v]=b;selected.push(cell);go(state,row,options,mask|(1<<u)|(1<<v),selected,word);selected.pop();if state.cap.is_some(){return}}}}go(self,row,&options,0,&mut Vec::new(),&mut[0u8;8])}
}

fn main(){let start=Instant::now();let mut target=HashMap::new();for(index,line)in read_to_string(TARGET).unwrap().lines().enumerate(){if index==0{assert_eq!(line,"colour_content_type\tnumerator\tdenominator");continue}let parts:Vec<_>=line.split('\t').collect();target.insert(parse_key(parts[0]),(parts[1].to_string(),parts[2].to_string()));}assert_eq!(target.len(),6800);let frozen_anchors=[0u8,4,8,117,121,125,198,202,206,243,247,251];let mut anchors=[false;252];for &cell in &frozen_anchors{anchors[cell as usize]=true}let structure=std::fs::read("computations/unaudited-codex-orbit0-filtered-k16-run-2026-08-23/filtered_k16_structure.bin").unwrap();assert_eq!(&structure[27..39],&frozen_anchors);let mut matchings=Vec::new();perfect_matchings(&(0..8).collect::<Vec<_>>(),&mut matchings,&mut Vec::new());assert_eq!(matchings.len(),105);let mut state=State{profiles:HashSet::new(),coordinates:target.keys().copied().collect(),target,matchings,completion_cache:HashMap::new(),anchors,columns:0,pure_skips:0,k_hist:[0;5],cap:None,start};let f=File::open(INPUT).unwrap();let mut reader=BufReader::with_capacity(1<<22,f);let mut magic=[0u8;8];reader.read_exact(&mut magic).unwrap();assert_eq!(&magic,b"K17RED2\0");let mut nb=[0u8;8];reader.read_exact(&mut nb).unwrap();let n=u64::from_le_bytes(nb);let mut processed=0u64;while processed<n&&state.cap.is_none(){let mut row=[0u8;24];let mut vb=[0u8;16];reader.read_exact(&mut row).unwrap();reader.read_exact(&mut vb).unwrap();state.divisors(&row);processed+=1;if processed%1000==0{eprintln!("ROWS {} columns={} profiles={} coords={} elapsed={:.1}",processed,state.columns,state.profiles.len(),state.coordinates.len(),start.elapsed().as_secs_f64())}}
    let mut coordinates:Vec<_>=state.coordinates.iter().copied().collect();coordinates.sort_unstable();let index:HashMap<_,_>=coordinates.iter().enumerate().map(|(i,k)|(*k,i)).collect();let mut cw=BufWriter::new(File::create(COORDS).unwrap());writeln!(cw,"coordinate_id\tcolour_content_type\ttarget_numerator\ttarget_denominator").unwrap();for(i,key)in coordinates.iter().enumerate(){let(n,d)=state.target.get(key).cloned().unwrap_or_else(||("0".into(),"1".into()));writeln!(cw,"{}\t{}\t{}\t{}",i,key_text(key),n,d).unwrap()}cw.flush().unwrap();let mut profiles:Vec<_>=state.profiles.into_iter().collect();profiles.sort_unstable();let mut vw=BufWriter::new(File::create(VECTORS).unwrap());writeln!(vw,"vector_id\tsparse_integer_vector").unwrap();let(mut min_nnz,mut max_nnz,mut total_nnz)=(usize::MAX,0usize,0usize);for(i,encoded)in profiles.iter().enumerate(){let vector=decode_vector(encoded);min_nnz=min_nnz.min(vector.len());max_nnz=max_nnz.max(vector.len());total_nnz+=vector.len();let text=vector.iter().map(|(k,v)|format!("{}:{}",index[k],v)).collect::<Vec<_>>().join(",");writeln!(vw,"{}\t{}",i,text).unwrap()}vw.flush().unwrap();let terminal=state.cap.unwrap_or("complete_all_target_rows");let status=if terminal=="complete_all_target_rows"{"PASS_COMPLETE"}else{"BOUNDED_CAP"};let result=format!("{{\n  \"status\":\"{}\",\n  \"terminal\":\"{}\",\n  \"target_rows_processed\":{},\n  \"literal_mixed_source_columns_visited\":{},\n  \"pure_word_divisors_skipped\":{},\n  \"distinct_projected_vectors\":{},\n  \"coordinate_count\":{},\n  \"new_coordinates_beyond_target\":{},\n  \"vector_nnz_min\":{},\n  \"vector_nnz_max\":{},\n  \"vector_nnz_total\":{},\n  \"selected_term_K_histogram\":[{},{},{},{},{}],\n  \"elapsed_seconds\":{:.3},\n  \"scope\":\"Literal mixed-word K17 same-filtration completion vectors touching streamed target rows; target-rooted first shell only, no rank.\"\n}}\n",status,terminal,processed,state.columns,state.pure_skips,profiles.len(),coordinates.len(),coordinates.len()-6800,if profiles.is_empty(){0}else{min_nnz},max_nnz,total_nnz,state.k_hist[0],state.k_hist[1],state.k_hist[2],state.k_hist[3],state.k_hist[4],start.elapsed().as_secs_f64());File::create(RESULT).unwrap().write_all(result.as_bytes()).unwrap();print!("{}",result)}
