use std::collections::{HashMap,HashSet};
use std::convert::TryInto;
use std::fs::read;
use std::hash::{Hash,Hasher};
use std::sync::Arc;
use std::thread;
use std::time::Instant;

const DIR:&str="computations/unaudited-codex-orbit0-filtered-k16-run-2026-08-23/";
const HERE:&str="computations/unaudited-codex-orbit0-filtered-k18-charge-2026-08-23/";
const S:i128=281_801_520;
#[derive(Clone,Copy,Eq,Ord,PartialEq,PartialOrd)]struct Row([u8;24]);
impl Hash for Row{fn hash<H:Hasher>(&self,s:&mut H){s.write(&self.0)}}
#[derive(Clone)]struct R8{row:[u8;12],size:u32,coefficient:i64}
#[derive(Clone)]struct E{perms:Vec<[u8;12]>,pos:[i8;252],piv:Vec<[u8;12]>,factor:Vec<Vec<Vec<[u8;4]>>>,records:Vec<R8>,anchors:Vec<[u8;4]>,tails:Vec<Vec<Vec<[u8;4]>>>,cover:HashSet<[u8;12]>,cells:[[u8;4];252],dual:HashMap<CKey,i64>}
#[derive(Clone,Copy,Eq,Hash,PartialEq)]struct CKey([u8;13]);
#[derive(Clone,Copy,Eq,Hash,PartialEq)]struct RKey{profile:[u8;29],sig:[u8;12],pivot:u8,degree:u8}
#[derive(Clone,Copy,Default)]struct Stat{full_n:u64,irr_n:u64,full_q:i128,irr_q:i128}
impl Stat{fn add(&mut self,x:Stat){self.full_n+=x.full_n;self.irr_n+=x.irr_n;self.full_q+=x.full_q;self.irr_q+=x.irr_q}}
fn u32le(x:&[u8])->u32{u32::from_le_bytes(x.try_into().unwrap())}fn u64le(x:&[u8])->u64{u64::from_le_bytes(x.try_into().unwrap())}fn i64le(x:&[u8])->i64{i64::from_le_bytes(x.try_into().unwrap())}
fn parse()->E{let b=read(format!("{}filtered_k16_structure.bin",DIR)).unwrap();let mut p=0;assert_eq!(&b[..11],b"K16DIRECT1\0");p+=11;let nt=u32le(&b[p..p+4])as usize;p+=4;let nr=u32le(&b[p..p+4])as usize;p+=4;let np=u32le(&b[p..p+4])as usize;p+=4;let na=u32le(&b[p..p+4])as usize;p+=4;assert_eq!((nt,nr,np,na),(384,485,78,12));let ac=&b[p..p+12];p+=12;let mut pos=[-1i8;252];for(i,&c)in ac.iter().enumerate(){pos[c as usize]=i as i8}let mut perms=Vec::new();for _ in 0..nt{p+=252;let mut q=[0u8;12];q.copy_from_slice(&b[p..p+12]);p+=12;perms.push(q)}let mut records=Vec::new();for _ in 0..nr{let mut row=[0u8;12];row.copy_from_slice(&b[p..p+12]);p+=12;let size=u32le(&b[p..p+4]);p+=4;let coefficient=i64le(&b[p..p+8]);p+=8;records.push(R8{row,size,coefficient})}let mut piv=Vec::new();for _ in 0..np{let mut x=[0u8;12];x.copy_from_slice(&b[p..p+12]);p+=12;piv.push(x)}let mut factor=vec![vec![Vec::new();3];3];for f in 0..3{for d in 0..3{let n=u32le(&b[p..p+4])as usize;p+=4;for _ in 0..n{let mut x=[0u8;4];x.copy_from_slice(&b[p..p+4]);p+=4;factor[f][d].push(x)}}}assert_eq!(p,b.len());
 let a=read(format!("{}filtered_k17_aux.bin",DIR)).unwrap();let mut q=8;let scale=u64le(&a[q..q+8]);q+=8;assert_eq!(scale,S as u64);let nc=u32le(&a[q..q+4])as usize;q+=4;let npa=u32le(&a[q..q+4])as usize;q+=4;let mut cover=HashSet::new();for _ in 0..nc{let mut x=[0u8;12];x.copy_from_slice(&a[q..q+12]);q+=12;cover.insert(x);}let mut anchors=Vec::new();let mut tails=vec![vec![Vec::new();3];npa];for i in 0..npa{let mut x=[0u8;4];x.copy_from_slice(&a[q..q+4]);q+=4;anchors.push(x);for _ in 0..12{let mut y=[0u8;4];y.copy_from_slice(&a[q..q+4]);q+=4;tails[i][0].push(y)}for _ in 0..32{let mut y=[0u8;4];y.copy_from_slice(&a[q..q+4]);q+=4;tails[i][1].push(y)}}assert_eq!(q,a.len());let k4=read(format!("{}filtered_k18_k4.bin",HERE)).unwrap();assert_eq!(&k4[..7],b"K18K4A1");let mut z=7;for i in 0..78{for _ in 0..60{let mut y=[0u8;4];y.copy_from_slice(&k4[z..z+4]);z+=4;tails[i][2].push(y)}}assert_eq!(z,k4.len());
 let c=read(format!("{}filtered_k17_cycle_aux.bin",DIR)).unwrap();let mut x=8;let mut cells=[[0u8;4];252];for v in &mut cells{v.copy_from_slice(&c[x..x+4]);x+=4}let nd=u32le(&c[x..x+4])as usize;x+=4;let mut dual=HashMap::new();for _ in 0..nd{let mut k=[0u8;13];k.copy_from_slice(&c[x..x+13]);x+=13;let v=i64le(&c[x..x+8]);x+=8;dual.insert(CKey(k),v);}assert_eq!(x,c.len());E{perms,pos,piv,factor,records,anchors,tails,cover,cells,dual}}
fn sig(row:&Row,e:&E)->[u8;12]{let mut s=[0u8;12];for &c in &row.0{let i=e.pos[c as usize];if i>=0{s[i as usize]+=1}}s}fn smove(s:[u8;12],p:&[u8;12])->[u8;12]{let mut x=[0;12];for i in 0..12{x[p[i]as usize]=s[i]}x}fn csig(s:[u8;12],e:&E)->[u8;12]{e.perms.iter().map(|p|smove(s,p)).min().unwrap()}fn avail(s:[u8;12],e:&E)->Vec<usize>{e.piv.iter().enumerate().filter_map(|(j,p)|if(0..12).all(|i|s[i]>=p[i]){Some(j)}else{None}).collect()}fn tsig(t:&[u8;4],e:&E)->[u8;12]{let mut s=[0;12];for &c in t{let i=e.pos[c as usize];if i>=0{s[i as usize]+=1}}s}fn child_sig(s:[u8;12],p:usize,t:&[u8;4],e:&E)->[u8;12]{let z=tsig(t,e);let mut x=[0;12];for i in 0..12{x[i]=s[i]-e.piv[p][i]+z[i]}x}fn valid(s:[u8;12],e:&E)->Vec<usize>{let mut o=Vec::new();for p in avail(s,e){if e.tails[p][0].iter().all(|t|{let c=child_sig(s,p,t,e);!avail(c,e).is_empty()||e.cover.contains(&csig(c,e))}){o.push(p)}}assert!(!o.is_empty());o}
fn make(r:&R8,a:&[u8;4],b:&[u8;4],c:&[u8;4])->Row{let mut x=[0;24];x[..12].copy_from_slice(&r.row);x[12..16].copy_from_slice(a);x[16..20].copy_from_slice(b);x[20..].copy_from_slice(c);x.sort_unstable();Row(x)}fn replace(row:&Row,a:&[u8;4],t:&[u8;4])->Row{let mut x=[0;24];let(mut j,mut k)=(0,0);for &c in &row.0{if j<4&&c==a[j]{j+=1}else{x[k]=c;k+=1}}assert_eq!((j,k),(4,20));x[20..].copy_from_slice(t);x.sort_unstable();Row(x)}fn remove(row:&Row,a:&[u8;4])->[u8;20]{let mut x=[0;20];let(mut j,mut k)=(0,0);for &c in &row.0{if j<4&&c==a[j]{j+=1}else{x[k]=c;k+=1}}assert_eq!((j,k),(4,20));x}
fn ckey(row:&Row,e:&E)->CKey{let mut adj=[[0u8;2];24];let mut deg=[0usize;24];for &c in &row.0{let[u,v,a,b]=e.cells[c as usize];let x=(3*u+a)as usize;let y=(3*v+b)as usize;adj[x][deg[x]]=y as u8;deg[x]+=1;adj[y][deg[y]]=x as u8;deg[y]+=1}assert!(deg.iter().all(|&d|d==2));let mut seen=[false;24];let mut parts=[0u8;12];let mut n=0;for st in 0..24{if seen[st]{continue}let mut stack=[0u8;24];let(mut top,mut size)=(1,0u8);stack[0]=st as u8;seen[st]=true;while top>0{top-=1;let x=stack[top]as usize;size+=1;for &yy in &adj[x]{let y=yy as usize;if !seen[y]{seen[y]=true;stack[top]=yy;top+=1}}}parts[n]=size;n+=1}parts[..n].sort_unstable();let mut k=[0;13];k[0]=n as u8;k[1..1+n].copy_from_slice(&parts[..n]);CKey(k)}fn charge(row:&Row,e:&E)->i64{*e.dual.get(&ckey(row,e)).unwrap_or(&0)}
fn profile(row:&Row,p:usize,e:&E)->[u8;29]{let m=remove(row,&e.anchors[p]);let mut edges=[(0u8,0u8);20];let mut adj=[[255u8;2];24];let mut deg=[0usize;24];for(i,&c)in m.iter().enumerate(){let[u,v,a,b]=e.cells[c as usize];let x=3*u+a;let y=3*v+b;edges[i]=(x,y);adj[x as usize][deg[x as usize]]=i as u8;deg[x as usize]+=1;adj[y as usize][deg[y as usize]]=i as u8;deg[y as usize]+=1}let mut eid=[-1i8;24];for(i,&c)in e.anchors[p].iter().enumerate(){let[u,v,a,b]=e.cells[c as usize];let x=(3*u+a)as usize;let y=(3*v+b)as usize;assert_eq!((eid[x],eid[y]),(-1,-1));eid[x]=(2*i)as i8;eid[y]=(2*i+1)as i8}let mut partner=[255u8;8];let mut lens=[0u8;8];let mut used=[false;20];for s in 0..8{if partner[s]!=255{continue}let mut v=eid.iter().position(|&x|x==s as i8).unwrap();let mut prev=255u8;let mut len=0u8;loop{let edge=*adj[v].iter().find(|&&x|x!=255&&x!=prev).unwrap();used[edge as usize]=true;let(a,b)=edges[edge as usize];v=if a as usize==v{b as usize}else{a as usize};prev=edge;len+=1;if eid[v]>=0{let t=eid[v]as usize;assert_ne!(s,t);partner[s]=t as u8;partner[t]=s as u8;lens[s]=len;lens[t]=len;break}}}let mut closed=[0u8;12];let mut nc=0;for seed in 0..20{if used[seed]{continue}let mut edge=seed as u8;let mut v=edges[seed].0 as usize;let start=v;let mut len=0u8;loop{used[edge as usize]=true;let(a,b)=edges[edge as usize];v=if a as usize==v{b as usize}else{a as usize};len+=1;if v==start{break}edge=*adj[v].iter().find(|&&x|x!=edge).unwrap()}closed[nc]=len;nc+=1}closed[..nc].sort_unstable();let mut out=[0;29];out[..8].copy_from_slice(&partner);out[8..16].copy_from_slice(&lens);out[16]=nc as u8;out[17..17+nc].copy_from_slice(&closed[..nc]);out}
fn resp(row:&Row,s:[u8;12],p:usize,d:usize,e:&E,cache:&mut HashMap<RKey,(i64,i64,u64,u64)>)->(i64,i64,u64,u64){let key=RKey{profile:profile(row,p,e),sig:s,pivot:p as u8,degree:d as u8};if let Some(&v)=cache.get(&key){return v}let mut fq=0;let mut iq=0;let mut fnn=0;let mut inn=0;for t in &e.tails[p][d-2]{let c=replace(row,&e.anchors[p],t);let q=charge(&c,e);fq+=q;fnn+=1;if avail(child_sig(s,p,t,e),e).is_empty(){iq+=q;inn+=1}}let v=(fq,iq,fnn,inn);cache.insert(key,v);v}
fn rworker(e:Arc<E>,start:usize,step:usize)->([Stat;3],usize){let mut out=[Stat::default();3];let mut cache=HashMap::new();for ri in(start..e.records.len()).step_by(step){let r=&e.records[ri];let positive=(r.coefficient as i128)*(r.size as i128);let dm=-positive*S;
 // direct K18: 2+4+4 and 3+3+4.
 for low in 0..3{let o:Vec<_>=(0..3).filter(|&x|x!=low).collect();for a in &e.factor[low][0]{for b in &e.factor[o[0]][2]{for c in &e.factor[o[1]][2]{let row=match low{0=>make(r,a,b,c),1=>make(r,b,a,c),_=>make(r,b,c,a)};let q=charge(&row,&e)as i128;out[0].full_n+=1;out[0].full_q+=dm*q;if avail(sig(&row,&e),&e).is_empty(){out[0].irr_n+=1;out[0].irr_q+=dm*q}}}}}
 for hi in 0..3{let o:Vec<_>=(0..3).filter(|&x|x!=hi).collect();for a in &e.factor[o[0]][1]{for b in &e.factor[o[1]][1]{for c in &e.factor[hi][2]{let row=match hi{0=>make(r,c,a,b),1=>make(r,a,c,b),_=>make(r,a,b,c)};let q=charge(&row,&e)as i128;out[0].full_n+=1;out[0].full_q+=dm*q;if avail(sig(&row,&e),&e).is_empty(){out[0].irr_n+=1;out[0].irr_q+=dm*q}}}}}
 // K14 -> K18 K4.
 for a in &e.factor[0][0]{for b in &e.factor[1][0]{for c in &e.factor[2][0]{let head=make(r,a,b,c);let s=sig(&head,&e);let ps=valid(s,&e);let w=positive*S/(ps.len()as i128);assert_eq!(positive*S%(ps.len()as i128),0);for p in ps{let(fq,iq,fnn,inn)=resp(&head,s,p,4,&e,&mut cache);out[1].full_n+=fnn;out[1].irr_n+=inn;out[1].full_q+=w*(fq as i128);out[1].irr_q+=w*(iq as i128)}}}}
 // K15 -> K18 K3.
 for hi in 0..3{let o:Vec<_>=(0..3).filter(|&x|x!=hi).collect();for a in &e.factor[o[0]][0]{for b in &e.factor[o[1]][0]{for c in &e.factor[hi][1]{let head=match hi{0=>make(r,c,a,b),1=>make(r,a,c,b),_=>make(r,a,b,c)};let s=sig(&head,&e);let ps=avail(s,&e);let w=positive*S/(ps.len()as i128);for p in ps{let(fq,iq,fnn,inn)=resp(&head,s,p,3,&e,&mut cache);out[2].full_n+=fnn;out[2].irr_n+=inn;out[2].full_q+=w*(fq as i128);out[2].irr_q+=w*(iq as i128)}}}}}
 }(out,cache.len())}
fn rec(data:&[u8],i:usize)->(Row,i64){let off=16+i*32;let mut r=[0;24];r.copy_from_slice(&data[off..off+24]);(Row(r),i64le(&data[off+24..off+32]))}fn nrec(data:&[u8])->usize{u64le(&data[8..16])as usize}fn lower(data:&[u8],x:u8)->usize{let(mut l,mut h)=(0,nrec(data));while l<h{let m=(l+h)/2;if rec(data,m).0.0[0]<x{l=m+1}else{h=m}}l}
fn kworker(e:Arc<E>,d:Arc<Vec<u8>>,z:Arc<Vec<u8>>,lo:u8,hi:u8)->(Stat,usize){let(mut i,ie)=(lower(&d,lo),lower(&d,hi));let(mut j,je)=(lower(&z,lo),lower(&z,hi));let mut out=Stat::default();let mut cache=HashMap::new();while i<ie||j<je{let a=if i<ie{Some(rec(&d,i))}else{None};let b=if j<je{Some(rec(&z,j))}else{None};let row=if a.is_none(){b.unwrap().0}else if b.is_none(){a.unwrap().0}else{a.unwrap().0.min(b.unwrap().0)};let mut v=0i64;if let Some((r,x))=a{if r==row{v+=x;i+=1}}if let Some((r,x))=b{if r==row{v-=x;j+=1}}if v==0{continue}let s=sig(&row,&e);let ps=avail(s,&e);if ps.is_empty(){continue}let w=-(v as i128)*S/(ps.len()as i128);assert_eq!(-(v as i128)*S%(ps.len()as i128),0);for p in ps{let(fq,iq,fnn,inn)=resp(&row,s,p,2,&e,&mut cache);out.full_n+=fnn;out.irr_n+=inn;out.full_q+=w*(fq as i128);out.irr_q+=w*(iq as i128)}}(out,cache.len())}
fn main(){let begun=Instant::now();let e=Arc::new(parse());let workers=8;let mut jobs=Vec::new();for t in 0..workers{let x=e.clone();jobs.push(thread::spawn(move||rworker(x,t,workers)))}let mut r=[Stat::default();3];let mut cache=0;for j in jobs{let(a,c)=j.join().unwrap();for i in 0..3{r[i].add(a[i])}cache+=c}let d=Arc::new(read(format!("{}checkpoint_direct_k16.bin",DIR)).unwrap());let z=Arc::new(read(format!("{}frozen_k14_k2_response.bin",DIR)).unwrap());let mut jobs=Vec::new();for t in 0..workers{let x=e.clone();let a=d.clone();let b=z.clone();let lo=(252*t/workers)as u8;let hi=(252*(t+1)/workers)as u8;jobs.push(thread::spawn(move||kworker(x,a,b,lo,hi)))}let mut k=Stat::default();for j in jobs{let(a,c)=j.join().unwrap();k.add(a);cache+=c}let out=format!("{{\"scale\":{},\"direct\":[{},{},{},{}],\"K14_K4\":[{},{},{},{}],\"K15_K3\":[{},{},{},{}],\"K16_K2\":[{},{},{},{}],\"cache_entries\":{},\"elapsed_seconds\":{:.3}}}",S,r[0].full_n,r[0].irr_n,r[0].full_q,r[0].irr_q,r[1].full_n,r[1].irr_n,r[1].full_q,r[1].irr_q,r[2].full_n,r[2].irr_n,r[2].full_q,r[2].irr_q,k.full_n,k.irr_n,k.full_q,k.irr_q,cache,begun.elapsed().as_secs_f64());std::fs::write(format!("{}results_k18_charge_raw.json",HERE),&out).unwrap();println!("{}",out)}
