#!/usr/bin/env python3
"""P5 decisive prototype: construct the TRUE mixed arc at the committed exact
generic-L rational point, order by order, by solving the selected M30
compatibility row for the newest bend, then testing whether the other 38
compatibility rows (26 further mixed germs + the pure rows) vanish for free.

This is the numeric point-analogue of the Nakayama principality statement
   M_i = a_i*M30 + tau*sum_j B_ij*M_j
and of the tau-saturated special-fibre criterion of
`notes/tau-saturated-special-fibre-nakayama-criterion.md`:
if the mixed ideal is generated by M30 then killing M30 order by order must
kill every other row automatically.

It also produces the TRUE bend sequence r_0, r_1, r_2, ... whose generating
function is the object the notes conjecture to be
   N(T)/((1+z0*T)(1+z30*T)(1+z52*T)).
Berlekamp-Massey on that exact rational sequence reports the true recurrence.

Read-only with respect to the repository.
"""

from fractions import Fraction as QQ
import argparse
import importlib.util
import sys
import time
from pathlib import Path

COMP = Path("/Users/rishi/workplace/krenn-conjecture/computations")
sys.path.insert(0, str(Path(__file__).resolve().parent))

from impulse_response_point import (  # noqa: E402
    Dual, ZERO, ONE, evaluate_row, berlekamp_massey, load_module,
)


class Graph:
    def __init__(self, base, point, P5, maximum_order, bends, rows):
        layout = base["layout"]
        self.layout = layout
        self.P5 = P5
        self.tau = base["tau"]
        self.z46 = layout["a"][46]
        self.dynamic = set(base["local_variables"]) | {self.z46}
        self.pivots = base["pivots"]
        self.normal, self.transverse, self.obstruction = rows
        self.b = point[layout["a"][44]] + point[layout["a"][45]]
        self.series = {
            variable: [ZERO] * (maximum_order + 1)
            for variable in self.dynamic
        }
        self.series[self.tau][1] = ONE
        for order, value in enumerate(bends):
            if order <= maximum_order:
                self.series[self.z46][order] = value
        self.cache = {}

    def product_coefficient(self, monomial, order):
        key = (monomial, order)
        hit = self.cache.get(key)
        if hit is not None:
            return hit
        if not monomial:
            answer = ONE if order == 0 else ZERO
        else:
            head = self.series[monomial[0]]
            tail = monomial[1:]
            answer = ZERO
            for degree in range(order + 1):
                value = head[degree]
                if not value:
                    continue
                rest = self.product_coefficient(tail, order - degree)
                if rest:
                    answer = answer + value * rest
        self.cache[key] = answer
        return answer

    def row_coefficient(self, row, order):
        answer = ZERO
        for monomial, scalar in row.items():
            value = self.product_coefficient(monomial, order)
            if value:
                answer = answer + value * scalar
        return answer

    def step(self, order):
        layout = self.layout
        self.cache = {}
        incoming = [self.row_coefficient(row, order) for row in self.normal]
        for pivot, value in zip(self.pivots, incoming):
            self.series[layout["y"][pivot]][order] = -value
        self.cache = {}
        incoming = [self.row_coefficient(row, order)
                    for row in self.transverse]
        for parameter, value in zip(self.P5.P5_NORMAL_VARIABLES, incoming):
            self.series[layout["n"][parameter]][order] = -value / self.b
        self.cache = {}
        assert not any(self.row_coefficient(row, order)
                       for row in self.normal + self.transverse), \
            f"graph residual at order {order}"
        return [self.row_coefficient(row, order) for row in self.obstruction]


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--max-bend", type=int, default=14)
    arguments = parser.parse_args()

    t0 = time.time()
    R4 = load_module("p5_r4_true", "verify_n8_p5_generic_L_koszul_ward_r4.py")
    G = R4.G
    F2 = R4.F2
    P5 = G.P5
    base = F2.audit(return_data=True)
    POINTMOD = load_module("p5_point_true",
                           "analyze_n8_p5_full_point_weierstrass.py")
    point = POINTMOD.exact_point(base)
    layout = base["layout"]
    a = layout["a"]
    z = lambda parameter: point[a[parameter]]
    s = point[base["first_bend"]]
    t = point[base["second_bend"]]
    r3 = POINTMOD.third_bend_root(layout, point, s, t)
    e1 = z(0) + z(30) + z(52)
    e2 = z(0) * z(30) + z(0) * z(52) + z(30) * z(52)
    e3 = z(0) * z(30) * z(52)
    unit = QQ(1, 2) * z(11) * z(16) ** 2 * z(41)
    u = z(26) + z(45)
    print(f"[{time.time()-t0:.1f}s] point ready. C*u={unit*u}", flush=True)

    dynamic = set(base["local_variables"]) | {a[46]}
    PURE = G.F2.SCHUR.audit(return_data=True)["pure_stricts"]
    print("pure rows", len(PURE), [len(x) for x in PURE], flush=True)
    rows = (
        [evaluate_row(x, point, dynamic) for x in base["normal"]],
        [evaluate_row(x, point, dynamic) for x in base["transverse"]],
        [evaluate_row(x, point, dynamic) for x in list(base["obstruction"]) + list(PURE)],
    )

    bends = [z(46), s, t, r3]
    naive = list(bends)
    for k in range(4, arguments.max_bend + 1):
        start = time.time()
        maximum_order = k + 3
        trial = [Dual(value) for value in bends] + [Dual(0, 1)]
        graph = Graph(base, point, P5, maximum_order, trial, rows)
        history = []
        for order in range(1, maximum_order + 1):
            history.append(graph.step(order))
        terminal = history[-1]
        slope = terminal[29].b
        assert slope == unit * u, (
            f"newest-bend M30 slope changed at k={k}: {slope}")
        value = -terminal[29].a / slope
        bends.append(value)
        naive.append(-(e1 * naive[-1] + e2 * naive[-2] + e3 * naive[-3]))

        # every other row, evaluated at the solved bend
        residual_rows = [
            (row + 1, item.a + item.b * value)
            for row, item in enumerate(terminal)
            if item.a + item.b * value
        ]
        # and all strictly lower orders must already vanish
        earlier = [
            (order + 1, row + 1)
            for order, values in enumerate(history[:-1])
            for row, item in enumerate(values)
            if item.a + item.b * value
        ]
        agree = "SAME as three-step" if value == naive[-1] else "DIFFERS"
        print(
            f"k={k:2d} [{time.time()-start:5.1f}s] r{k} solved; {agree}; "
            f"other rows nonzero at order {maximum_order}: "
            f"{[row for row, _ in residual_rows]}; "
            f"earlier-order violations: {earlier[:6]}",
            flush=True,
        )
        if agree == "DIFFERS":
            print(f"    true r{k} = {value}", flush=True)
            print(f"    naive r{k} = {naive[-1]}", flush=True)

    print("\n--- true bend sequence ---", flush=True)
    for index, value in enumerate(bends):
        print(f"r_{index} = {value}", flush=True)
    connection, length = berlekamp_massey(bends)
    print(f"\nBerlekamp-Massey on the true bend sequence: length={length}",
          flush=True)
    print(f"connection={connection}", flush=True)
    print(f"conjectured connection = [1, {e1}, {e2}, {e3}]", flush=True)


if __name__ == "__main__":
    main()
