use std::collections::{HashMap,HashSet};
use std::convert::TryInto;
use std::fs::{read,File,rename};
use std::hash::{Hash,Hasher};
use std::io::{BufWriter,Write};
use std::sync::Arc;
use std::thread;
use std::time::Instant;

const DIR:&str="computations/unaudited-codex-orbit0-filtered-k16-run-2026-08-23/";
const OUT:&str="computations/unaudited-codex-orbit0-k19-profile-census-2026-08-23/";
const SCALE:u64=281_801_520;

#[derive(Clone,Copy,Eq,Ord,PartialEq,PartialOrd)]struct Row([u8;24]);
impl Hash for Row{fn hash<H:Hasher>(&self,s:&mut H){s.write(&self.0)}}
#[derive(Clone)]struct R8{row:[u8;12]}
#[derive(Clone)]struct E{perms:Vec<[u8;12]>,pos:[i8;252],piv:Vec<[u8;12]>,factor:Vec<Vec<Vec<[u8;4]>>>,records:Vec<R8>,anchors:Vec<[u8;4]>,tails:Vec<Vec<Vec<[u8;4]>>>,cover:HashSet<[u8;12]>,cells:[[u8;4];252]}
#[derive(Clone,Copy,Eq,Hash,Ord,PartialEq,PartialOrd)]struct Key{profile:[u8;29],sig:[u8;12],pivot:u8,degree:u8}
#[derive(Clone)]struct Stat{heads:u64,children:u64,pivotable:u64,outgoing:u64,first:[u64;79],second:[u64;79],products:HashMap<u16,u64>}
impl Default for Stat{fn default()->Self{Self{heads:0,children:0,pivotable:0,outgoing:0,first:[0;79],second:[0;79],products:HashMap::new()}}}
impl Stat{fn add(&mut self,x:Stat){self.heads+=x.heads;self.children+=x.children;self.pivotable+=x.pivotable;self.outgoing+=x.outgoing;for i in 0..79{self.first[i]+=x.first[i];self.second[i]+=x.second[i]}for(k,v)in x.products{*self.products.entry(k).or_default()+=v}}}
fn u32le(x:&[u8])->u32{u32::from_le_bytes(x.try_into().unwrap())}fn u64le(x:&[u8])->u64{u64::from_le_bytes(x.try_into().unwrap())}
fn parse()->E{let b=read(format!("{}filtered_k16_structure.bin",DIR)).unwrap();let mut p=0;assert_eq!(&b[..11],b"K16DIRECT1\0");p+=11;let nt=u32le(&b[p..p+4])as usize;p+=4;let nr=u32le(&b[p..p+4])as usize;p+=4;let np=u32le(&b[p..p+4])as usize;p+=4;let na=u32le(&b[p..p+4])as usize;p+=4;assert_eq!((nt,nr,np,na),(384,485,78,12));let ac=&b[p..p+12];p+=12;let mut pos=[-1i8;252];for(i,&c)in ac.iter().enumerate(){pos[c as usize]=i as i8}let mut perms=Vec::new();for _ in 0..nt{p+=252;let mut q=[0;12];q.copy_from_slice(&b[p..p+12]);p+=12;perms.push(q)}let mut records=Vec::new();for _ in 0..nr{let mut row=[0;12];row.copy_from_slice(&b[p..p+12]);p+=12;p+=12;records.push(R8{row})}let mut piv=Vec::new();for _ in 0..np{let mut x=[0;12];x.copy_from_slice(&b[p..p+12]);p+=12;piv.push(x)}let mut factor=vec![vec![Vec::new();3];3];for f in 0..3{for d in 0..3{let n=u32le(&b[p..p+4])as usize;p+=4;for _ in 0..n{let mut x=[0;4];x.copy_from_slice(&b[p..p+4]);p+=4;factor[f][d].push(x)}}}assert_eq!(p,b.len());
 let a=read(format!("{}filtered_k17_aux.bin",DIR)).unwrap();assert_eq!(&a[..8],b"K17AUX1\0");let mut q=8;assert_eq!(u64le(&a[q..q+8]),SCALE);q+=8;let nc=u32le(&a[q..q+4])as usize;q+=4;let npa=u32le(&a[q..q+4])as usize;q+=4;let mut cover=HashSet::new();for _ in 0..nc{let mut x=[0;12];x.copy_from_slice(&a[q..q+12]);q+=12;cover.insert(x);}let mut anchors=Vec::new();let mut tails=vec![vec![Vec::new();2];npa];for i in 0..npa{let mut x=[0;4];x.copy_from_slice(&a[q..q+4]);q+=4;anchors.push(x);for _ in 0..12{let mut y=[0;4];y.copy_from_slice(&a[q..q+4]);q+=4;tails[i][0].push(y)}for _ in 0..32{let mut y=[0;4];y.copy_from_slice(&a[q..q+4]);q+=4;tails[i][1].push(y)}}assert_eq!(q,a.len());
 let c=read(format!("{}filtered_k17_cycle_aux.bin",DIR)).unwrap();assert_eq!(&c[..8],b"K17CYC1\0");let mut x=8;let mut cells=[[0;4];252];for v in &mut cells{v.copy_from_slice(&c[x..x+4]);x+=4}E{perms,pos,piv,factor,records,anchors,tails,cover,cells}}
fn sig(row:&Row,e:&E)->[u8;12]{let mut s=[0;12];for &c in &row.0{let i=e.pos[c as usize];if i>=0{s[i as usize]+=1}}s}fn smove(s:[u8;12],p:&[u8;12])->[u8;12]{let mut x=[0;12];for i in 0..12{x[p[i]as usize]=s[i]}x}fn csig(s:[u8;12],e:&E)->[u8;12]{e.perms.iter().map(|p|smove(s,p)).min().unwrap()}fn avail(s:[u8;12],e:&E)->Vec<usize>{e.piv.iter().enumerate().filter_map(|(j,p)|if(0..12).all(|i|s[i]>=p[i]){Some(j)}else{None}).collect()}fn tsig(t:&[u8;4],e:&E)->[u8;12]{let mut s=[0;12];for &c in t{let i=e.pos[c as usize];if i>=0{s[i as usize]+=1}}s}fn child_sig(s:[u8;12],p:usize,t:&[u8;4],e:&E)->[u8;12]{let z=tsig(t,e);let mut x=[0;12];for i in 0..12{x[i]=s[i]-e.piv[p][i]+z[i]}x}fn valid(s:[u8;12],e:&E)->Vec<usize>{let mut o=Vec::new();for p in avail(s,e){if e.tails[p][0].iter().all(|t|{let c=child_sig(s,p,t,e);!avail(c,e).is_empty()||e.cover.contains(&csig(c,e))}){o.push(p)}}assert!(!o.is_empty());o}
fn make(r:&R8,a:&[u8;4],b:&[u8;4],c:&[u8;4])->Row{let mut x=[0;24];x[..12].copy_from_slice(&r.row);x[12..16].copy_from_slice(a);x[16..20].copy_from_slice(b);x[20..].copy_from_slice(c);x.sort_unstable();Row(x)}fn replace(row:&Row,a:&[u8;4],t:&[u8;4])->Row{let mut x=[0;24];let(mut j,mut k)=(0,0);for &c in &row.0{if j<4&&c==a[j]{j+=1}else{x[k]=c;k+=1}}assert_eq!((j,k),(4,20));x[20..].copy_from_slice(t);x.sort_unstable();Row(x)}fn remove(row:&Row,a:&[u8;4])->[u8;20]{let mut x=[0;20];let(mut j,mut k)=(0,0);for &c in &row.0{if j<4&&c==a[j]{j+=1}else{x[k]=c;k+=1}}assert_eq!((j,k),(4,20));x}
fn profile(row:&Row,p:usize,e:&E)->[u8;29]{let m=remove(row,&e.anchors[p]);let mut edges=[(0u8,0u8);20];let mut adj=[[255u8;2];24];let mut deg=[0usize;24];for(i,&c)in m.iter().enumerate(){let[u,v,a,b]=e.cells[c as usize];let x=3*u+a;let y=3*v+b;edges[i]=(x,y);adj[x as usize][deg[x as usize]]=i as u8;deg[x as usize]+=1;adj[y as usize][deg[y as usize]]=i as u8;deg[y as usize]+=1}let mut eid=[-1i8;24];for(i,&c)in e.anchors[p].iter().enumerate(){let[u,v,a,b]=e.cells[c as usize];let x=(3*u+a)as usize;let y=(3*v+b)as usize;assert_eq!((eid[x],eid[y]),(-1,-1));eid[x]=(2*i)as i8;eid[y]=(2*i+1)as i8}let mut partner=[255;8];let mut lens=[0;8];let mut used=[false;20];for s in 0..8{if partner[s]!=255{continue}let mut v=eid.iter().position(|&x|x==s as i8).unwrap();let mut prev=255;let mut len=0;loop{let edge=*adj[v].iter().find(|&&x|x!=255&&x!=prev).unwrap();used[edge as usize]=true;let(a,b)=edges[edge as usize];v=if a as usize==v{b as usize}else{a as usize};prev=edge;len+=1;if eid[v]>=0{let t=eid[v]as usize;partner[s]=t as u8;partner[t]=s as u8;lens[s]=len;lens[t]=len;break}}}let mut closed=[0;12];let mut nc=0;for seed in 0..20{if used[seed]{continue}let mut edge=seed as u8;let mut v=edges[seed].0 as usize;let start=v;let mut len=0;loop{used[edge as usize]=true;let(a,b)=edges[edge as usize];v=if a as usize==v{b as usize}else{a as usize};len+=1;if v==start{break}edge=*adj[v].iter().find(|&&x|x!=edge).unwrap()}closed[nc]=len;nc+=1}closed[..nc].sort_unstable();let mut out=[0;29];out[..8].copy_from_slice(&partner);out[8..16].copy_from_slice(&lens);out[16]=nc as u8;out[17..17+nc].copy_from_slice(&closed[..nc]);out}
fn record(row:&Row,first:usize,e:&E,st:&mut Stat,keys:&mut HashSet<Key>){st.children+=1;st.first[first]+=1;let s=sig(row,e);let ps=avail(s,e);if ps.is_empty(){return}st.pivotable+=1;let second=ps.len();st.second[second]+=1;assert_eq!((SCALE as u128)*(SCALE as u128)%((first*second)as u128),0);for p in ps{st.outgoing+=1;*st.products.entry((first*second)as u16).or_default()+=1;keys.insert(Key{profile:profile(row,p,e),sig:s,pivot:p as u8,degree:2});}}
fn worker(kind:&str,e:Arc<E>,start:usize,step:usize)->(Stat,HashSet<Key>){let mut st=Stat::default();let mut keys=HashSet::new();for ri in(start..e.records.len()).step_by(step){let r=&e.records[ri];if kind=="direct"{for d2 in 0..3{for d3 in 0..3{if d2==d3{continue}let d4=3-d2-d3;for a in &e.factor[d2][0]{for b in &e.factor[d3][1]{for c in &e.factor[d4][2]{let mut z:[Option<&[u8;4]>;3]=[None,None,None];z[d2]=Some(a);z[d3]=Some(b);z[d4]=Some(c);st.heads+=1;record(&make(r,z[0].unwrap(),z[1].unwrap(),z[2].unwrap()),1,&e,&mut st,&mut keys)}}}}}for a in &e.factor[0][1]{for b in &e.factor[1][1]{for c in &e.factor[2][1]{st.heads+=1;record(&make(r,a,b,c),1,&e,&mut st,&mut keys)}}}}
 else if kind=="k14"{for a in &e.factor[0][0]{for b in &e.factor[1][0]{for c in &e.factor[2][0]{st.heads+=1;let head=make(r,a,b,c);let s=sig(&head,&e);let ps=valid(s,&e);let n=ps.len();for p in ps{for t in &e.tails[p][1]{record(&replace(&head,&e.anchors[p],t),n,&e,&mut st,&mut keys)}}}}}}
 else if kind=="k15"{for hi in 0..3{let o:Vec<_>=(0..3).filter(|&x|x!=hi).collect();for a in &e.factor[o[0]][0]{for b in &e.factor[o[1]][0]{for c in &e.factor[hi][1]{st.heads+=1;let head=match hi{0=>make(r,c,a,b),1=>make(r,a,c,b),_=>make(r,a,b,c)};let s=sig(&head,&e);let ps=avail(s,&e);let n=ps.len();for p in ps{for t in &e.tails[p][0]{record(&replace(&head,&e.anchors[p],t),n,&e,&mut st,&mut keys)}}}}}}}
 else{panic!("bad lineage")}}(st,keys)}
fn write_results(kind:&str,st:&Stat,mut keys:HashSet<Key>,elapsed:f64){let mut v:Vec<_>=keys.drain().collect();v.sort_unstable();let kt=format!("{}keys_{}.bin.tmp",OUT,kind);let kf=format!("{}keys_{}.bin",OUT,kind);let mut w=BufWriter::new(File::create(&kt).unwrap());w.write_all(b"K19KEY1\0").unwrap();w.write_all(&(v.len()as u64).to_le_bytes()).unwrap();for k in &v{w.write_all(&k.profile).unwrap();w.write_all(&k.sig).unwrap();w.write_all(&[k.pivot,k.degree]).unwrap()}w.flush().unwrap();drop(w);rename(kt,kf).unwrap();let hist=|a:&[u64;79]|(1..79).filter(|&i|a[i]!=0).map(|i|format!("\"{}\":{}",i,a[i])).collect::<Vec<_>>().join(",");let mut products:Vec<_>=st.products.iter().collect();products.sort_unstable();let ph=products.iter().map(|(k,v)|format!("\"{}\":{}",k,v)).collect::<Vec<_>>().join(",");let text=format!("{{\"status\":\"PASS_EXACT_PROFILE_CENSUS\",\"lineage\":\"{}\",\"heads\":{},\"children\":{},\"pivotable_children\":{},\"outgoing_pivot_uses\":{},\"K19_K2_tail_operations\":{},\"unique_enriched_keys\":{},\"first_denominator_hist\":{{{}}},\"second_denominator_hist\":{{{}}},\"product_denominator_hist\":{{{}}},\"scale\":{},\"elapsed_seconds\":{:.3}}}",kind,st.heads,st.children,st.pivotable,st.outgoing,st.outgoing*12,v.len(),hist(&st.first),hist(&st.second),ph,SCALE,elapsed);let jt=format!("{}stats_{}.json.tmp",OUT,kind);let jf=format!("{}stats_{}.json",OUT,kind);std::fs::write(&jt,&text).unwrap();rename(jt,jf).unwrap();println!("{}",text)}
#[cfg(not(feature="hidden_k16_parent_prefix"))]
fn main(){let begun=Instant::now();let kind=std::env::args().nth(1).expect("lineage direct|k14|k15");let e=Arc::new(parse());let workers=8;let mut jobs=Vec::new();for t in 0..workers{let x=e.clone();let k=kind.clone();jobs.push(thread::spawn(move||worker(&k,x,t,workers)))}let mut st=Stat::default();let mut sets=Vec::new();for j in jobs{let(a,b)=j.join().unwrap();st.add(a);sets.push(b)}sets.sort_unstable_by_key(|s|std::cmp::Reverse(s.len()));let mut all=sets.remove(0);for s in sets{all.reserve(s.len());for k in s{all.insert(k);}}write_results(&kind,&st,all,begun.elapsed().as_secs_f64())}
