import PhysicalReflection

#print axioms KrennAllOrders.PhysicalReflection.reindexWord
#print axioms KrennAllOrders.PhysicalReflection.sign_reindexWord
#print axioms KrennAllOrders.PhysicalReflection.pairing_reindex
#print axioms KrennAllOrders.PhysicalReflection.indexedMomentTensor
#print axioms KrennAllOrders.PhysicalReflection.indexedMomentTensor_reindex
#print axioms KrennAllOrders.PhysicalReflection.pairing_indexedMoment_roots_eq_zero
#print axioms KrennAllOrders.PhysicalReflection.receivingWord
#print axioms KrennAllOrders.PhysicalReflection.receivingWord_at
#print axioms KrennAllOrders.PhysicalReflection.originalResponseTensor
#print axioms KrennAllOrders.PhysicalReflection.originalResponseTensor_eq_moments
#print axioms KrennAllOrders.PhysicalReflection.originalResponseTensor_reflection
#print axioms KrennAllOrders.PhysicalReflection.wordExponent_eq_constant_iff
#print axioms KrennAllOrders.PhysicalReflection.retainedCoefficient_pureRootWord_word
#print axioms KrennAllOrders.PhysicalReflection.original_linear_response
#print axioms KrennAllOrders.PhysicalReflection.wordExponent_congr_list
#print axioms KrennAllOrders.PhysicalReflection.oddResponsePolynomial_congr_word
#print axioms KrennAllOrders.PhysicalReflection.original_linear_response_of_constant
#print axioms KrennAllOrders.PhysicalReflection.retainedSites_nonempty
#print axioms KrennAllOrders.PhysicalReflection.originalResponseTensor_linear_pair
#print axioms KrennAllOrders.PhysicalReflection.originalResponseTensor_false
#print axioms KrennAllOrders.PhysicalReflection.originalResponseTensor_true
#print axioms KrennAllOrders.PhysicalReflection.pure_response_cross
#print axioms KrennAllOrders.PhysicalReflection.originalResponseTensor_linear_mixed
#print axioms KrennAllOrders.PhysicalReflection.mixed_response_cross
