//! Cross-agent, no-full-rerun referee of 257 D14 R3-2-2 literal continuations.
mod referee {
#![allow(dead_code,unused_imports)]
include!("../unaudited-codex-orbit0-filtered-k18-charge-2026-08-23/run_k18_charge.rs");
const TSV:&str="computations/unaudited-codex-orbit0-k21-d14-322-charge-2026-08-24/results_k21_d14_322_charge.json.samples.tsv";
const OUT:&str="computations/unaudited-codex-orbit0-k21-d14-322-charge-2026-08-24/results_cross_agent_nonzero_referee.json";
const U:i128=400_591_699_200;
const HEADS:usize=838_080;
fn hex(row:&Row)->String{row.0.iter().map(|x|format!("{:02x}",x)).collect()}
fn literal_response(row19:&Row,s19:[u8;12],p3:usize,e:&E)->(i64,u64){let(mut q,mut n)=(0i64,0u64);for t in &e.tails[p3][0]{let row21=replace(row19,&e.anchors[p3],t);let s21=child_sig(s19,p3,t,e);assert_eq!(sig(&row21,e),s21);assert_eq!(s21.iter().map(|&x|x as usize).sum::<usize>(),3);assert!(avail(s21,e).is_empty());q+=charge(&row21,e);n+=1}(q,n)}
fn find_nonzero(row14:&Row,e:&E)->(usize,usize,usize,usize,usize,usize,usize,usize,i64,u64){let s14=sig(row14,e);let ps1=valid(s14,e);let m1=ps1.len();for &p1 in &ps1{for(t3,t)in e.tails[p1][1].iter().enumerate(){let row17=replace(row14,&e.anchors[p1],t);let s17=child_sig(s14,p1,t,e);assert_eq!(sig(&row17,e),s17);let ps2=avail(s17,e);let m2=ps2.len();if m2==0{continue}for &p2 in &ps2{for(t2,t)in e.tails[p2][0].iter().enumerate(){let row19=replace(&row17,&e.anchors[p2],t);let s19=child_sig(s17,p2,t,e);assert_eq!(sig(&row19,e),s19);let ps3=avail(s19,e);let m3=ps3.len();if m3==0{continue}for &p3 in &ps3{let(q,n)=literal_response(&row19,s19,p3,e);if q!=0{return(p1,t3,p2,t2,p3,m1,m2,m3,q,n)}}}}}}panic!("sampled nonzero head lacks a nonzero literal terminal continuation")}
pub fn run(){let begun=Instant::now();let e=parse();let raw=std::fs::read_to_string(TSV).unwrap();let mut it=raw.lines();let header=it.next().unwrap();assert_eq!(header,"sample_bin\thead_index\tr8_index\trow14\tsource_mass\tp1_uses\tK17_candidates\tpivotable_K17\tp2_uses\tK19_candidates\tpivotable_K19\tp3_uses\tK21_children\tcharge_scaled_U\twitness_p1\twitness_t3\twitness_p2\twitness_t2\twitness_p3\tm1\tm2\tm3\twitness_terminal_q\twitness_row17\twitness_row19");let(mut rows,mut recorded_children,mut nonzero_children,mut recorded_matches,mut weighted)=(0usize,0u64,0u64,0usize,0i128);let mut previous=None;
 for line in it{let x:Vec<_>=line.split('\t').collect();assert_eq!(x.len(),25);let bin=x[0].parse::<usize>().unwrap();let head=x[1].parse::<usize>().unwrap();let ri=x[2].parse::<usize>().unwrap();assert_eq!(bin,rows);assert_eq!(head*257/HEADS,bin);if let Some(p)=previous{assert!(p<head)}previous=Some(head);assert_eq!(ri,head/1728);let rem=head%1728;let(ai,bi,ci)=(rem/144,(rem/12)%12,rem%12);let r=&e.records[ri];let row14=make(r,&e.factor[0][0][ai],&e.factor[1][0][bi],&e.factor[2][0][ci]);assert_eq!(hex(&row14),x[3]);let mass=(r.size as i128)*(r.coefficient as i128);assert_eq!(mass,x[4].parse::<i128>().unwrap());assert_ne!(x[13].parse::<i128>().unwrap(),0);let s14=sig(&row14,&e);assert_eq!(s14.iter().map(|&z|z as usize).sum::<usize>(),10);
  let(p1,t3,p2,t2,p3,m1,m2,m3,q,n)=find_nonzero(&row14,&e);assert_eq!(n,12);let denom=(m1*m2*m3)as i128;assert_eq!(U%denom,0);weighted+=mass*(U/denom)*(q as i128);nonzero_children+=n;
  let(rp1,rt3,rp2,rt2,rp3)=(x[14].parse::<usize>().unwrap(),x[15].parse::<usize>().unwrap(),x[16].parse::<usize>().unwrap(),x[17].parse::<usize>().unwrap(),x[18].parse::<usize>().unwrap());let ps1=valid(s14,&e);assert!(ps1.contains(&rp1));assert_eq!(ps1.len(),x[19].parse().unwrap());let row17=replace(&row14,&e.anchors[rp1],&e.tails[rp1][1][rt3]);assert_eq!(hex(&row17),x[23]);let s17=sig(&row17,&e);assert_eq!(s17.iter().map(|&z|z as usize).sum::<usize>(),7);let ps2=avail(s17,&e);assert!(ps2.contains(&rp2));assert_eq!(ps2.len(),x[20].parse().unwrap());let row19=replace(&row17,&e.anchors[rp2],&e.tails[rp2][0][rt2]);assert_eq!(hex(&row19),x[24]);let s19=sig(&row19,&e);assert_eq!(s19.iter().map(|&z|z as usize).sum::<usize>(),5);let ps3=avail(s19,&e);assert!(ps3.contains(&rp3));assert_eq!(ps3.len(),x[21].parse().unwrap());let(rq,rn)=literal_response(&row19,s19,rp3,&e);assert_eq!(rq,x[22].parse().unwrap());assert_eq!(rn,12);recorded_children+=rn;recorded_matches+=1;let _=(p1,t3,p2,t2,p3);rows+=1;}
 assert_eq!((rows,recorded_matches),(257,257));assert_eq!(recorded_children,3084);assert_eq!(nonzero_children,3084);let out=format!("{{\n  \"status\":\"PASS_CROSS_AGENT_257_DISTRIBUTED_NONZERO_D14_322_K21_REFEREE\",\n  \"strict_lineage_id\":\"D14:222|R:3-2-2\",\n  \"distributed_source_heads\":257,\n  \"recorded_witness_literal_terminal_K21_children\":{},\n  \"independently_selected_nonzero_terminal_K21_children\":{},\n  \"recorded_witness_rows_and_terminal_charges_matched\":{},\n  \"independent_nonzero_branch_charge_scaled_U\":\"{}\",\n  \"all_U_divisions_exact\":true,\n  \"all_literal_K21_children_terminal\":true,\n  \"elapsed_seconds\":{:.6},\n  \"scope\":\"cross-agent 257-head literal replay only; no full aggregate rerun and no K22\"\n}}\n",recorded_children,nonzero_children,recorded_matches,weighted,begun.elapsed().as_secs_f64());std::fs::write(OUT,&out).unwrap();print!("{}",out)}
}
fn main(){referee::run()}
