mod base {
include!("../unaudited-codex-orbit0-k19-profile-census-2026-08-23/run_k19_profile_census.rs");
use std::io::{BufReader,Read};
const WOUT:&str="computations/unaudited-codex-orbit0-k19-charge-2026-08-23/";
const K4:&str="computations/unaudited-codex-orbit0-filtered-k18-charge-2026-08-23/filtered_k18_k4.bin";
#[derive(Default,Clone,Copy)]struct Q{full_n:u64,irr_n:u64,full:i128,irr:i128,keys:u64,zeros:u64,signed:i128,l1:i128}
impl Q{fn add(&mut self,x:Q){self.full_n+=x.full_n;self.irr_n+=x.irr_n;self.full+=x.full;self.irr+=x.irr;self.keys+=x.keys;self.zeros+=x.zeros;self.signed+=x.signed;self.l1+=x.l1}}
struct S{r:BufReader<File>,left:u64,cur:Option<(Key,i128)>}
impl S{fn new(mode:&str,t:usize)->Self{let mut r=BufReader::with_capacity(1<<20,File::open(format!("{}run_{}_{}.bin",WOUT,mode,t)).unwrap());let mut h=[0;15];r.read_exact(&mut h).unwrap();assert_eq!(&h[..7],b"K19WGT1");let left=u64::from_le_bytes(h[7..].try_into().unwrap());let mut s=Self{r,left,cur:None};s.bump();s}fn bump(&mut self){if self.left==0{self.cur=None}else{let mut z=[0;59];self.r.read_exact(&mut z).unwrap();let mut p=[0;29];p.copy_from_slice(&z[..29]);let mut s=[0;12];s.copy_from_slice(&z[29..41]);let k=Key{profile:p,sig:s,pivot:z[41],degree:z[42]};let v=i128::from_le_bytes(z[43..59].try_into().unwrap());self.left-=1;self.cur=Some((k,v))}}}
fn aux(e:&E)->(Vec<Vec<[u8;4]>>,HashMap<[u8;13],i64>){let b=read(K4).unwrap();assert_eq!(&b[..7],b"K18K4A1");let mut p=7;let mut k4=vec![Vec::new();78];for i in 0..78{for _ in 0..60{let mut x=[0;4];x.copy_from_slice(&b[p..p+4]);p+=4;k4[i].push(x)}}assert_eq!(p,b.len());let c=read(format!("{}filtered_k17_cycle_aux.bin",DIR)).unwrap();assert_eq!(&c[..8],b"K17CYC1\0");let mut z=8+252*4;let n=u32le(&c[z..z+4])as usize;z+=4;let mut dual=HashMap::new();for _ in 0..n{let mut k=[0;13];k.copy_from_slice(&c[z..z+13]);z+=13;let v=i64::from_le_bytes(c[z..z+8].try_into().unwrap());z+=8;dual.insert(k,v);}assert_eq!(z,c.len());assert_eq!(e.anchors.len(),78);(k4,dual)}
fn masses()->Vec<i128>{let b=read(format!("{}filtered_k16_structure.bin",DIR)).unwrap();let mut p=11;let _nt=u32le(&b[p..p+4])as usize;p+=4;let nr=u32le(&b[p..p+4])as usize;p+=4;p+=8+12+384*(252+12);let mut out=Vec::new();for _ in 0..nr{p+=12;let size=u32le(&b[p..p+4])as i128;p+=4;let c=i64::from_le_bytes(b[p..p+8].try_into().unwrap())as i128;p+=8;out.push(size*c)}out}
fn row_cycle(row:&Row,e:&E)->[u8;13]{let mut adj=[[0u8;2];24];let mut deg=[0usize;24];for &c in &row.0{let[u,v,a,b]=e.cells[c as usize];let x=(3*u+a)as usize;let y=(3*v+b)as usize;adj[x][deg[x]]=y as u8;deg[x]+=1;adj[y][deg[y]]=x as u8;deg[y]+=1}assert!(deg.iter().all(|&d|d==2));let mut seen=[false;24];let mut parts=[0;12];let mut n=0;for st in 0..24{if seen[st]{continue}let mut stack=[0u8;24];stack[0]=st as u8;let(mut top,mut len)=(1,0);seen[st]=true;while top>0{top-=1;let x=stack[top]as usize;len+=1;for &y in &adj[x]{if !seen[y as usize]{seen[y as usize]=true;stack[top]=y;top+=1}}}parts[n]=len;n+=1}parts[..n].sort_unstable();let mut k=[0;13];k[0]=n as u8;k[1..1+n].copy_from_slice(&parts[..n]);k}
fn key_cycle(k:&Key,tail:&[u8;4],e:&E)->[u8;13]{let p=k.pivot as usize;let mut label=[255u8;24];for(i,&c)in e.anchors[p].iter().enumerate(){let[u,v,a,b]=e.cells[c as usize];label[(3*u+a)as usize]=(2*i)as u8;label[(3*v+b)as usize]=(2*i+1)as u8}let mut adj=[[(255u8,0u8);2];8];let mut deg=[0usize;8];let mut edge=|a:usize,b:usize,w:u8|{adj[a][deg[a]]=(b as u8,w);deg[a]+=1;adj[b][deg[b]]=(a as u8,w);deg[b]+=1;};for a in 0..8{let b=k.profile[a]as usize;if a<b{edge(a,b,k.profile[8+a])}}for &c in tail{let[u,v,a,b]=e.cells[c as usize];let x=label[(3*u+a)as usize];let y=label[(3*v+b)as usize];assert!(x<8&&y<8);edge(x as usize,y as usize,1)}assert!(deg.iter().all(|&x|x==2));let mut parts=[0u8;12];let nc=k.profile[16]as usize;parts[..nc].copy_from_slice(&k.profile[17..17+nc]);let mut n=nc;let mut seen=[false;8];for st in 0..8{if seen[st]{continue}let mut stack=[0u8;8];stack[0]=st as u8;let(mut top,mut twice)=(1,0u16);seen[st]=true;while top>0{top-=1;let x=stack[top]as usize;for &(y,w)in &adj[x]{twice+=w as u16;if !seen[y as usize]{seen[y as usize]=true;stack[top]=y;top+=1}}}assert_eq!(twice%2,0);parts[n]=(twice/2)as u8;n+=1}parts[..n].sort_unstable();let mut out=[0;13];out[0]=n as u8;out[1..1+n].copy_from_slice(&parts[..n]);out}
fn eval(k:&Key,w:i128,e:&E,k4:&Vec<Vec<[u8;4]>>,dual:&HashMap<[u8;13],i64>)->Q{let p=k.pivot as usize;let tails:&Vec<[u8;4]>=match k.degree{2=>&e.tails[p][0],3=>&e.tails[p][1],4=>&k4[p],_=>panic!("degree")};let mut q=Q::default();q.keys=1;q.signed=w;q.l1=w.abs();for t in tails{let z=*dual.get(&key_cycle(k,t,e)).unwrap_or(&0)as i128;q.full_n+=1;q.full+=w*z;if avail(child_sig(k.sig,p,t,e),e).is_empty(){q.irr_n+=1;q.irr+=w*z}}q}
fn merge(mode:&str,e:&E,k4:&Vec<Vec<[u8;4]>>,dual:&HashMap<[u8;13],i64>)->Q{let mut s:Vec<_>=(0..8).map(|t|S::new(mode,t)).collect();let tmp=format!("{}weights_{}.bin.tmp",WOUT,mode);let dst=format!("{}weights_{}.bin",WOUT,mode);let mut w=BufWriter::new(File::create(&tmp).unwrap());w.write_all(b"K19SUM1\0").unwrap();w.write_all(&0u64.to_le_bytes()).unwrap();let mut out=Q::default();loop{let m=s.iter().filter_map(|x|x.cur.map(|y|y.0)).min();if m.is_none(){break}let k=m.unwrap();let mut v=0;for x in &mut s{if x.cur.map(|y|y.0)==Some(k){v+=x.cur.unwrap().1;x.bump()}}if v==0{out.zeros+=1;continue}w.write_all(&k.profile).unwrap();w.write_all(&k.sig).unwrap();w.write_all(&[k.pivot,k.degree]).unwrap();w.write_all(&v.to_le_bytes()).unwrap();out.add(eval(&k,v,e,k4,dual))}w.flush().unwrap();drop(w);let mut f=std::fs::OpenOptions::new().write(true).open(&tmp).unwrap();f.write_all(b"K19SUM1\0").unwrap();f.write_all(&out.keys.to_le_bytes()).unwrap();drop(f);rename(tmp,dst).unwrap();out}
fn direct_worker(e:Arc<E>,dual:Arc<HashMap<[u8;13],i64>>,start:usize,step:usize)->Q{let ms=masses();let mut out=Q::default();for ri in(start..e.records.len()).step_by(step){let r=&e.records[ri];let w=-ms[ri]*(SCALE as i128)*(SCALE as i128);for hi in 0..3{let o:Vec<_>=(0..3).filter(|&x|x!=hi).collect();for a in &e.factor[o[0]][1]{for b in &e.factor[o[1]][2]{for c in &e.factor[hi][2]{let row=match hi{0=>make(r,c,a,b),1=>make(r,a,c,b),_=>make(r,a,b,c)};let z=*dual.get(&row_cycle(&row,&e)).unwrap_or(&0)as i128;out.full_n+=1;out.full+=w*z;if avail(sig(&row,&e),&e).is_empty(){out.irr_n+=1;out.irr+=w*z}}}}}}out}
fn save(mode:&str,q:Q,elapsed:f64){let text=format!("{{\"status\":\"PASS_EXACT_K19_COMPONENT_CHARGE\",\"mode\":\"{}\",\"scale\":{},\"full_evaluations\":{},\"irreducible_evaluations\":{},\"full_charge_scaled\":{},\"irreducible_charge_scaled\":{},\"merged_keys\":{},\"exact_zero_keys\":{},\"signed_weight_scaled\":{},\"l1_weight_scaled\":{},\"elapsed_seconds\":{:.3}}}",mode,(SCALE as u128)*(SCALE as u128),q.full_n,q.irr_n,q.full,q.irr,q.keys,q.zeros,q.signed,q.l1,elapsed);let a=format!("{}results_{}.json.tmp",WOUT,mode);let b=format!("{}results_{}.json",WOUT,mode);std::fs::write(&a,&text).unwrap();rename(a,b).unwrap();println!("{}",text)}
fn selftest(e:&E,k4:&Vec<Vec<[u8;4]>>){let mut n=0;for r in e.records.iter().take(8){for a in e.factor[0][0].iter().take(4){for b in e.factor[1][0].iter().take(4){for c in e.factor[2][0].iter().take(4){let row=make(r,a,b,c);let s=sig(&row,e);for p in avail(s,e){let k=Key{profile:profile(&row,p,e),sig:s,pivot:p as u8,degree:2};for(d,tails)in [(2,&e.tails[p][0]),(3,&e.tails[p][1]),(4,&k4[p])]{let mut z=k;z.degree=d;for t in tails.iter().step_by(7){assert_eq!(key_cycle(&z,t,e),row_cycle(&replace(&row,&e.anchors[p],t),e));n+=1}}}}}}}assert!(n>1000);let text=format!("{{\"status\":\"PASS_LITERAL_PROFILE_CHARGE_SELFTEST\",\"comparisons\":{}}}",n);std::fs::write(format!("{}results_profile_charge_selftest.json",WOUT),&text).unwrap();println!("{}",text)}
pub fn run(){let begun=Instant::now();let mode=std::env::args().nth(1).expect("mode");let e=Arc::new(parse());let(k4,d)=aux(&e);if mode=="selftest"{selftest(&e,&k4)}else if mode=="direct_k19"{let dual=Arc::new(d);let mut jobs=Vec::new();for t in 0..8{let a=e.clone();let b=dual.clone();jobs.push(thread::spawn(move||direct_worker(a,b,t,8)))}let mut q=Q::default();for j in jobs{q.add(j.join().unwrap())}save(&mode,q,begun.elapsed().as_secs_f64())}else{let q=merge(&mode,&e,&k4,&d);save(&mode,q,begun.elapsed().as_secs_f64())}}
}
fn main(){base::run()}
