mod base {
include!("../unaudited-codex-orbit0-k19-profile-census-2026-08-23/run_k19_profile_census.rs");
const WOUT:&str="computations/unaudited-codex-orbit0-k19-charge-2026-08-23/";
#[derive(Default)]struct WStat{heads:u64,parents:u64,pivots:u64,run_keys:u64,signed:i128,l1:i128}
fn addw(row:&Row,first:usize,sign_mass:i128,degree:u8,e:&E,map:&mut HashMap<Key,i128>,st:&mut WStat){st.parents+=1;let s=sig(row,e);let ps=avail(s,e);if ps.is_empty(){return}let second=ps.len();assert_eq!((SCALE as u128)*(SCALE as u128)%((first*second)as u128),0);let w=sign_mass*(SCALE as i128)*(SCALE as i128)/((first*second)as i128);for p in ps{st.pivots+=1;let k=Key{profile:profile(row,p,e),sig:s,pivot:p as u8,degree};let z=map.entry(k).or_default();*z+=w;if *z==0{map.remove(&k);}}}
fn masses()->Vec<i128>{let b=read(format!("{}filtered_k16_structure.bin",DIR)).unwrap();let mut p=11;let _nt=u32le(&b[p..p+4])as usize;p+=4;let nr=u32le(&b[p..p+4])as usize;p+=4;p+=8;p+=12;p+=384*(252+12);let mut out=Vec::new();for _ in 0..nr{p+=12;let size=u32le(&b[p..p+4])as i128;p+=4;let c=i64::from_le_bytes(b[p..p+8].try_into().unwrap())as i128;p+=8;out.push(size*c)}out}
fn rec(data:&[u8],i:usize)->(Row,i64){let o=16+32*i;let mut r=[0;24];r.copy_from_slice(&data[o..o+24]);(Row(r),i64::from_le_bytes(data[o+24..o+32].try_into().unwrap()))}
fn write_run(mode:&str,t:usize,map:HashMap<Key,i128>,mut st:WStat){let mut v:Vec<_>=map.into_iter().filter(|x|x.1!=0).collect();v.sort_unstable_by_key(|x|x.0);st.run_keys=v.len()as u64;for x in &v{st.signed+=x.1;st.l1+=x.1.abs()}let tmp=format!("{}run_{}_{}.bin.tmp",WOUT,mode,t);let dst=format!("{}run_{}_{}.bin",WOUT,mode,t);let mut w=BufWriter::new(File::create(&tmp).unwrap());w.write_all(b"K19WGT1").unwrap();w.write_all(&(v.len()as u64).to_le_bytes()).unwrap();for(k,x)in v{w.write_all(&k.profile).unwrap();w.write_all(&k.sig).unwrap();w.write_all(&[k.pivot,k.degree]).unwrap();w.write_all(&x.to_le_bytes()).unwrap()}w.flush().unwrap();drop(w);rename(tmp,dst).unwrap();let text=format!("{{\"mode\":\"{}\",\"thread\":{},\"heads\":{},\"parents\":{},\"pivots\":{},\"run_keys\":{},\"signed_scaled\":{},\"l1_scaled\":{}}}",mode,t,st.heads,st.parents,st.pivots,st.run_keys,st.signed,st.l1);let a=format!("{}run_{}_{}.json.tmp",WOUT,mode,t);let b=format!("{}run_{}_{}.json",WOUT,mode,t);std::fs::write(&a,text).unwrap();rename(a,b).unwrap()}
fn source_worker(mode:&str,e:Arc<E>,ms:Arc<Vec<i128>>,start:usize,step:usize)->(HashMap<Key,i128>,WStat){let mut map=HashMap::new();let mut st=WStat::default();for ri in(start..e.records.len()).step_by(step){let r=&e.records[ri];let mass=ms[ri];if mode=="k17_direct_k2"{for d2 in 0..3{for d3 in 0..3{if d2==d3{continue}let d4=3-d2-d3;for a in &e.factor[d2][0]{for b in &e.factor[d3][1]{for c in &e.factor[d4][2]{let mut z:[Option<&[u8;4]>;3]=[None,None,None];z[d2]=Some(a);z[d3]=Some(b);z[d4]=Some(c);st.heads+=1;addw(&make(r,z[0].unwrap(),z[1].unwrap(),z[2].unwrap()),1,mass,2,&e,&mut map,&mut st)}}}}}for a in &e.factor[0][1]{for b in &e.factor[1][1]{for c in &e.factor[2][1]{st.heads+=1;addw(&make(r,a,b,c),1,mass,2,&e,&mut map,&mut st)}}}}
 else if mode=="k17_k14_k2"{for a in &e.factor[0][0]{for b in &e.factor[1][0]{for c in &e.factor[2][0]{st.heads+=1;let head=make(r,a,b,c);let s=sig(&head,&e);let ps=valid(s,&e);let n=ps.len();for p in ps{for tail in &e.tails[p][1]{addw(&replace(&head,&e.anchors[p],tail),n,-mass,2,&e,&mut map,&mut st)}}}}}}
 else if mode=="k17_k15_k2"{for hi in 0..3{let o:Vec<_>=(0..3).filter(|&x|x!=hi).collect();for a in &e.factor[o[0]][0]{for b in &e.factor[o[1]][0]{for c in &e.factor[hi][1]{st.heads+=1;let head=match hi{0=>make(r,c,a,b),1=>make(r,a,c,b),_=>make(r,a,b,c)};let s=sig(&head,&e);let ps=avail(s,&e);let n=ps.len();for p in ps{for tail in &e.tails[p][0]{addw(&replace(&head,&e.anchors[p],tail),n,-mass,2,&e,&mut map,&mut st)}}}}}}}
 else{panic!("bad source mode")}}(map,st)}
fn file_worker(mode:&str,e:Arc<E>,data:Arc<Vec<u8>>,start:usize,step:usize)->(HashMap<Key,i128>,WStat){let mut map=HashMap::new();let mut st=WStat::default();let n=u64le(&data[8..16])as usize;for i in(start..n).step_by(step){let(row,v)=rec(&data,i);st.heads+=1;let sign_mass=if mode=="k16_k14_k3"{v as i128}else{-(v as i128)};let degree=if mode=="k15_k4"{4}else{3};addw(&row,1,sign_mass,degree,&e,&mut map,&mut st)}(map,st)}
pub fn run(){let mode=std::env::args().nth(1).expect("mode");let e=Arc::new(parse());let workers=8;let mut jobs=Vec::new();if mode.starts_with("k17_"){let ms=Arc::new(masses());for t in 0..workers{let a=e.clone();let b=ms.clone();let m=mode.clone();jobs.push(thread::spawn(move||{let(x,s)=source_worker(&m,a,b,t,workers);write_run(&m,t,x,s)}))}}else{let path=match mode.as_str(){"k15_k4"=>format!("{}checkpoint_direct_k15.bin",DIR),"k16_direct_k3"=>format!("{}checkpoint_direct_k16.bin",DIR),"k16_k14_k3"=>format!("{}frozen_k14_k2_response.bin",DIR),_=>panic!("bad mode")};let data=Arc::new(read(path).unwrap());let magic=match mode.as_str(){"k15_k4"=>b"K15CHK1\0", "k16_direct_k3"=>b"K16DIR1\0",_=>b"K16RESP1"};assert_eq!(&data[..8],magic);for t in 0..workers{let a=e.clone();let b=data.clone();let m=mode.clone();jobs.push(thread::spawn(move||{let(x,s)=file_worker(&m,a,b,t,workers);write_run(&m,t,x,s)}))}}for j in jobs{j.join().unwrap()}let a=format!("{}generated_{}.json.tmp",WOUT,mode);let b=format!("{}generated_{}.json",WOUT,mode);std::fs::write(&a,format!("{{\"status\":\"PASS_ATOMIC_THREAD_RUNS\",\"mode\":\"{}\",\"threads\":8,\"scale\":{}}}",mode,SCALE)).unwrap();rename(a,b).unwrap();println!("PASS {}",mode)}
}
fn main(){base::run()}
