#!/usr/bin/env python3
"""Mechanically derive final runner from the pinned hardened v1 group runner."""
import hashlib,os
from pathlib import Path
HERE=Path(__file__).resolve().parent;ROOT=HERE.parents[1];BASE=ROOT/'computations/unaudited-codex-n8-x5-rep2-groups76-125-exact-q-conditional-held-2026-08-26/run_groups76_125.py';BASE_SHA='c1aa9303186a1a1e1efaa867471192b69b746aac52741ad227d901db34cbe24a';VERIFIER_SHA='b784729f817f2986fac597009b65698e62fc8a0ba944447c21b95cd5dde29ff5'
def sha(path):return hashlib.sha256(path.read_bytes()).hexdigest()
assert sha(BASE)==BASE_SHA;text=BASE.read_text();changes=[]
def once(old,new,label):
 global text
 assert text.count(old)==1,(label,text.count(old));text=text.replace(old,new);changes.append(label)
once('"""Refusal-locked sequential rep2 exact-Q groups76..125 executor."""','"""Final provenance-replaying sequential rep2 exact-Q groups126..161 executor."""','doc')
once("HERE=Path(__file__).resolve().parent;LEDGER=HERE/'source_ledger.json';NORMALIZED=HERE/'normalized_dependencies.json';SINGULAR=Path('/usr/local/bin/Singular');GTIMEOUT=Path('/usr/local/bin/gtimeout')","HERE=Path(__file__).resolve().parent;ROOT=HERE.parents[1];LEDGER=HERE/'source_ledger.json';FUTURE=HERE/'future_dependencies.json';VERIFIER=HERE/'dependency_verifier.py';NORMALIZED=HERE/'normalized_dependencies.json';SINGULAR=Path('/usr/local/bin/Singular');GTIMEOUT=Path('/usr/local/bin/gtimeout')",'paths')
once("LEDGER_SHA='4aa023638d439fd1250b66593d93dd29dd4472831449ff571e2730bf6950b4ce';FUTURE_SHA='5173f8f03b8eb7feff428573cb6a0b2813ef1e6cb1d4c4696543c30585e522e4';SINGULAR_SHA=","LEDGER_SHA='c34b3616bef36d49c63904e676c540208a24dd2057eb176153ad03034db0b8a6';FUTURE_SHA='ab8198b3c9745368e51f1f5c481d81b62823f7255d046a80e3d94a7c2cad0e9c';VERIFIER_SHA='"+VERIFIER_SHA+"';SINGULAR_SHA=",'pins')
once('SELECTED=tuple(range(76,126))','SELECTED=tuple(range(126,162))','selection')
once("assert sha(LEDGER)==LEDGER_SHA and sha(HERE/'future_dependencies.json')==FUTURE_SHA and sha(SINGULAR)==SINGULAR_SHA and sha(GTIMEOUT)==GTIMEOUT_SHA","assert sha(LEDGER)==LEDGER_SHA and sha(FUTURE)==FUTURE_SHA and sha(VERIFIER)==VERIFIER_SHA and sha(SINGULAR)==SINGULAR_SHA and sha(GTIMEOUT)==GTIMEOUT_SHA",'pins_assert')
old="assert NORMALIZED.is_file(),'HELD: both future dependencies have not been normalized'\ndependency=json.loads(NORMALIZED.read_text());assert dependency['schema']=='KRENN_X5_REP2_GROUPS76_125_NORMALIZED_DEPENDENCIES_V1' and dependency['status']=='PASS_NORMALIZED_EXACT_CLOSED_UNION_0_75' and dependency['groups_closed_by_first']==list(range(1,26)) and dependency['groups_closed_by_middle']==list(range(26,76)) and dependency['closed_union']==list(range(76)) and dependency['duplicates']==dependency['missing']==dependency['extra']==[]\nassert len(dependency['dependency_manifest_sha256'])==len(dependency['dependency_result_sha256'])==2 and all(len(x)==64 for x in dependency['dependency_manifest_sha256']+dependency['dependency_result_sha256'])"
new="assert NORMALIZED.is_file(),'HELD: all three future dependencies have not been normalized'\ndependency=json.loads(NORMALIZED.read_text());assert dependency['schema']=='KRENN_X5_REP2_GROUPS126_161_NORMALIZED_DEPENDENCIES_V1' and dependency['status']=='PASS_NORMALIZED_EXACT_CLOSED_UNION_0_125' and dependency['groups_closed_by_first']==list(range(1,26)) and dependency['groups_closed_by_middle']==list(range(26,76)) and dependency['groups_closed_by_third_v2']==list(range(76,126)) and dependency['closed_union']==list(range(126)) and dependency['duplicates']==dependency['missing']==dependency['extra']==[]\nassert len(dependency['dependency_manifest_sha256'])==len(dependency['dependency_result_sha256'])==3 and all(len(x)==64 for x in dependency['dependency_manifest_sha256']+dependency['dependency_result_sha256'])\nfrom dependency_verifier import verify_payload\nreplay=verify_payload(json.loads(FUTURE.read_text()),dependency,ROOT);assert replay['status']=='PASS_REPLAYED_ALL_SIX_DEPENDENCY_ARTIFACTS_EXACT_UNION_0_125' and replay['closed_union']==list(range(126))"
once(old,new,'three_dependency_replay')
once("[x['ordinal'] for x in lanes]==list(range(1,51))","[x['ordinal'] for x in lanes]==list(range(1,37))",'lane_count')
text=text.replace('KRENN_X5_REP2_GROUPS76_125','KRENN_X5_REP2_GROUPS126_161');changes.append('schemas')
text=text.replace('CONDITIONAL_REP2_GROUPS76_125_ONLY','CONDITIONAL_REP2_GROUPS126_161_ONLY');changes.append('statuses')
assert text.count("'required_closed_union':list(range(76))")==3;text=text.replace("'required_closed_union':list(range(76))","'required_closed_union':list(range(126))");changes.append('closed_union')
assert text.count("'maximum_lane_count':50")==2;text=text.replace("'maximum_lane_count':50","'maximum_lane_count':36");changes.append('max_lanes')
old_pin="'source_ledger_sha256':LEDGER_SHA,'normalized_dependencies_sha256':dependency_sha";new_pin="'source_ledger_sha256':LEDGER_SHA,'dependency_verifier_sha256':VERIFIER_SHA,'normalized_dependencies_sha256':dependency_sha";assert text.count(old_pin)==2;text=text.replace(old_pin,new_pin);changes.append('acceptance_clearance_verifier_pins')
once("'status':'PASS_ALL_50_UNIT'","'status':'PASS_ALL_36_UNIT'",'batch_status')
tmp=HERE/'run_groups126_161.py.tmp';tmp.write_text(text);os.replace(tmp,HERE/'run_groups126_161.py');print({'status':'PASS_DERIVED_FINAL_RUNNER_ZERO_RUN','changes':changes,'runner_sha256':sha(HERE/'run_groups126_161.py')})
