#!/usr/bin/env python3
"""Materialize the three-stage null-hash dependency contract; never solve."""
import json,os
from pathlib import Path
HERE=Path(__file__).resolve().parent
def atomic(path,value):tmp=path.with_suffix(path.suffix+'.tmp');tmp.write_text(json.dumps(value,indent=2,sort_keys=True)+'\n');os.replace(tmp,path)
deps=[
 {'name':'groups1_25','manifest_path':'computations/unaudited-codex-n8-x5-rep2-first25-exact-q-terminal-referee-2026-08-26/FINAL_MANIFEST.sha256','result_path':'computations/unaudited-codex-n8-x5-rep2-first25-exact-q-terminal-referee-2026-08-26/results_referee.json','result_schema':'KRENN_X5_REP2_FIRST25_EXACT_Q_TERMINAL_REFEREE_V1','result_status':'PASS_ALL_25_EXACT_Q_UNIT_IDEALS','groups_closed':list(range(1,26)),'manifest_sha256':None,'result_sha256':None,'satisfied':False},
 {'name':'groups26_75','manifest_path':'computations/unaudited-codex-n8-x5-rep2-groups26-75-exact-q-terminal-referee-2026-08-26/FINAL_MANIFEST.sha256','result_path':'computations/unaudited-codex-n8-x5-rep2-groups26-75-exact-q-terminal-referee-2026-08-26/results_referee.json','result_schema':'KRENN_X5_REP2_GROUPS26_75_EXACT_Q_TERMINAL_REFEREE_V1','result_status':'PASS_ALL_50_EXACT_Q_UNIT_IDEALS','groups_closed':list(range(26,76)),'manifest_sha256':None,'result_sha256':None,'satisfied':False},
 {'name':'groups76_125_v2','manifest_path':'computations/unaudited-codex-n8-x5-rep2-groups76-125-exact-q-terminal-referee-v2-2026-08-26/FINAL_MANIFEST.sha256','result_path':'computations/unaudited-codex-n8-x5-rep2-groups76-125-exact-q-terminal-referee-v2-2026-08-26/results_referee.json','result_schema':'KRENN_X5_REP2_GROUPS76_125_EXACT_Q_TERMINAL_REFEREE_V2','result_status':'PASS_ALL_50_EXACT_Q_UNIT_IDEALS','groups_closed':list(range(76,126)),'manifest_sha256':None,'result_sha256':None,'satisfied':False}]
contract={'schema':'KRENN_X5_REP2_GROUPS126_161_FUTURE_DEPENDENCIES_V1','status':'UNSATISFIED_THREE_NULL_HASH_PAIRS','baseline_closed_group':0,'required_closed_union':list(range(126)),'dependencies':deps,'satisfied':False,'admission':'all three future manifests and results must exist, replay exactly, match strict schemas/statuses/group lists, and normalize to duplicate-free union 0..125; null hashes never authorize execution'};atomic(HERE/'future_dependencies.json',contract);print(json.dumps({'status':contract['status'],'dependencies':3,'null_hashes':6},sort_keys=True))
