#!/usr/bin/env python3
"""A6 / B6: A6's COMPLETED PROOF of the key lemma behind Theorem W14.3.

LEMMA.  C_h  cap  tr * S^{h-1} = 0, where C_h = iota_h(Sigma_h) is the
Cartan component in S^h(V (x) W) and tr = K00 + K11 + K22.

PROOF.  By apolarity, C_h = (I_2)_h^perp where I_2 is the ideal of 2x2
minors of the dual matrix (y_ij), and <l*g, D> = <g, l(d)D>.  With
l = tr, l(d) = T := sum_i d/dy_ii, a derivation.  So tr*g in C_h forces
g perp T((I_2)_h); hence the lemma follows from

  (*)  T((I_2)_h) = S^{h-1}   for all h >= 2.

BASE h = 2.  For c != d pick e outside {c,d}: the minor
m = y_ee y_cd - y_ed y_ce has T(m) = y_cd exactly.  For the principal
minor y_aa y_bb - y_ab y_ba, T = y_aa + y_bb; the three such sums span
the diagonal 3-space.  Hence T((I_2)_2) = S^1.

STEP h-1 -> h.  Let X = T((I_2)_h) and let phi: S -> k[t] be the
quotient by the ideal generated by L = {y_ab (a != b), y_aa - y_bb}
(so phi(y_aa) = t, phi(y_ab) = 0), whose degree-(h-1) part has
codimension 1.  For z in (I_2)_{h-1} and any variable:
   T(z y_ab) = T(z) y_ab            (a != b, since T(y_ab) = 0)
   T(z y_aa) = T(z) y_aa + z
By induction T((I_2)_{h-1}) = S^{h-2}, so T(z) ranges over all of
S^{h-2}; the first line gives S^{h-2} y_ab  in X, and subtracting two
copies of the second line (same z, different a) gives
S^{h-2}(y_aa - y_bb) in X.  Hence X contains the whole codimension-one
subspace (L)_{h-1}.  Finally take m = y00 y11 - y01 y10 and
u = y00^{h-2}: T(mu) = T(m)u + m T(u) lies in X and
   phi(T(mu)) = phi(y00+y11) t^{h-2} + t^2 (h-2) t^{h-3} = h t^{h-1},
nonzero in characteristic 0.  So X is not inside (L)_{h-1}, whence
X = S^{h-1}.  QED

This script CHECKS every computational step of that proof.
"""
import json
from itertools import combinations, combinations_with_replacement
import a6_bcore as B

def minors():
    out = []
    for (i, k) in combinations(range(3), 2):
        for (j, l) in combinations(range(3), 2):
            out.append(({(B.kx(i, j), B.kx(k, l)): 1, (B.kx(i, l), B.kx(k, j)): -1},
                        (i, k, j, l)))
    return out

def norm(p):
    return {tuple(sorted(m)): c for m, c in p.items() if c}

def T(p):
    """the derivation sum_i d/dy_ii on dual monomials (tuples of var ids)"""
    out = {}
    for m, c in p.items():
        for d in (0, 4, 8):
            cnt = m.count(d)
            if not cnt:
                continue
            rest = list(m)
            rest.remove(d)
            k = tuple(sorted(rest))
            out[k] = out.get(k, 0) + c * cnt
    return {m: c for m, c in out.items() if c}

res = {}
# base case: T of the 9 minors spans S^1
rows = [B.prow(norm(T(norm(m))), 1) for m, _ in minors()]
res["base_h2_rank_of_T_minors"] = len(B.rref(rows)[1])
res["base_h2_is_full_9"] = res["base_h2_rank_of_T_minors"] == 9
# named identities from the proof
nm = {}
for (m, (i, k, j, l)) in minors():
    nm[(i, k, j, l)] = norm(T(norm(m)))
def show(t):
    return {"".join(str(v) for v in mm): c for mm, c in nm[t].items()}
res["T(y00y11-y01y10)"] = show((0, 1, 0, 1))
res["T(y01y12-y02y11)"] = show((0, 1, 1, 2))

# (*) verified directly: T((I_2)_h) = S^{h-1} for h = 2,3,4
direct = {}
for h in (2, 3, 4):
    gen = []
    for (m, _) in minors():
        for u in combinations_with_replacement(range(9), h - 2):
            gen.append(B.prow(norm(T(norm(B.pmul(m, {u: 1})))), h - 1))
    r = B.rank_mod_p(gen)
    direct[h] = {"rank_of_T(I_h)": r, "dim_S_{h-1}": len(B.midx(9, h - 1)),
                 "surjective": r == len(B.midx(9, h - 1))}
res["T_of_ideal_is_onto"] = direct

# the phi-computation of the induction step, symbolically for h = 3..6
phi = {}
for h in range(3, 7):
    m = {(B.kx(0, 0), B.kx(1, 1)): 1, (B.kx(0, 1), B.kx(1, 0)): -1}
    u = {tuple([B.kx(0, 0)] * (h - 2)): 1}
    Tmu = norm(T(norm(B.pmul(m, u))))
    # phi: y_aa -> t, y_ab -> 0
    tot = 0
    for mm, c in Tmu.items():
        if all(v in (0, 4, 8) for v in mm):
            tot += c
    phi[h] = {"phi(T(m*u)) = c*t^{h-1}, c =": tot, "expected h =": h,
              "match": tot == h}
res["induction_step_phi_coefficient"] = phi

# mutation controls
ctl = {}
# wrong derivation (only d/dy00) must NOT be onto at h=2
def T1(p):
    out = {}
    for m, c in p.items():
        cnt = m.count(0)
        if cnt:
            rest = list(m); rest.remove(0)
            k = tuple(sorted(rest)); out[k] = out.get(k, 0) + c * cnt
    return {m: c for m, c in out.items() if c}
rows1 = [B.prow(norm(T1(norm(m))), 1) for m, _ in minors()]
ctl["single_partial_not_onto"] = len(B.rref(rows1)[1]) < 9
# a non-ideal generator set (random quadrics) may still be onto -> check the
# checker discriminates by using ONLY principal minors (should be onto? test)
rowsP = [B.prow(norm(T(norm(m))), 1) for m, t in minors()
         if t[0] == t[2] and t[1] == t[3]]
ctl["only_principal_minors_rank"] = len(B.rref(rowsP)[1])
res["controls"] = ctl
json.dump(res, open("results_B6c_proof.json", "w"), indent=1, default=str)
print(json.dumps(res, indent=1, default=str))
