#!/usr/bin/env python3
"""Run an exact checker in the repository's three deterministic modes.

The checker remains responsible for the mathematics.  This wrapper freezes
the executable, source and dependency hashes, stdout/stderr, return codes,
and the requested result artifacts after each of ``std``, ``-O``, and
``-I -S``.  A run is accepted only when every mode succeeds and every result
artifact is byte-identical.
"""

from __future__ import annotations

import argparse
from hashlib import sha256
import json
import os
from pathlib import Path
import platform
import subprocess
import sys
import time

from msolve_io import file_sha256


TOOLKIT_VERSION = "1"


def atomic_json(path: Path, value: dict) -> None:
    temporary = path.with_suffix(path.suffix + ".tmp")
    temporary.write_text(json.dumps(value, indent=2, sort_keys=True) + "\n")
    temporary.replace(path)


def logical_digest(value: dict) -> str:
    payload = {
        "toolkit_version": value["toolkit_version"],
        "proof_status": value["proof_status"],
        "scope": value["scope"],
        "script_sha256": value["script"]["sha256"],
        "source_sha256": [item["sha256"] for item in value["sources"]],
        "script_args": value["script_args"],
        "modes": [{
            "name": mode["name"],
            "pythonhashseed": mode["pythonhashseed"],
            "status": mode["status"],
            "artifact_sha256": [item["sha256"]
                                for item in mode["artifacts"]],
            "artifact_logical_sha256": [
                item.get("logical_sha256", item.get("result_sha256"))
                for item in mode["artifacts"]],
        } for mode in value["modes"]],
    }
    return sha256(json.dumps(payload, sort_keys=True,
                             separators=(",", ":")).encode()).hexdigest()


def hash_artifacts(paths: list[Path]) -> list[dict]:
    result = []
    for path in paths:
        if not path.is_file():
            raise FileNotFoundError(f"missing checker artifact: {path}")
        record = {"path": str(path), "bytes": path.stat().st_size,
                  "sha256": file_sha256(path)}
        if path.suffix == ".json":
            try:
                value = json.loads(path.read_text())
            except Exception as error:
                record["json_error"] = f"{type(error).__name__}: {error}"
            else:
                if isinstance(value, dict):
                    for key in ("logical_sha256", "result_sha256"):
                        if isinstance(value.get(key), str):
                            record[key] = value[key]
        result.append(record)
    return result


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--python", default=sys.executable)
    parser.add_argument("--artifact", action="append", type=Path,
                        required=True)
    parser.add_argument("--source", action="append", type=Path, default=[])
    parser.add_argument("--manifest", type=Path, required=True)
    parser.add_argument("--timeout", type=float, default=300)
    parser.add_argument("--scope", required=True)
    parser.add_argument("script", type=Path)
    parser.add_argument("script_args", nargs=argparse.REMAINDER)
    args = parser.parse_args()

    script_args = list(args.script_args)
    if script_args[:1] == ["--"]:
        script_args.pop(0)
    sources = [args.script, *args.source]
    for path in [*sources, *args.artifact]:
        # Artifacts may be generated by the checker, so only source existence
        # is checked before the first run.
        if path in sources and not path.is_file():
            raise SystemExit(f"missing source: {path}")

    modes = [
        ("std", [], "0"),
        ("optimized", ["-O"], "1"),
        ("isolated_no_site", ["-I", "-S"], "2"),
    ]
    manifest = {
        "toolkit_version": TOOLKIT_VERSION,
        "proof_status": "exact_checker_replay",
        "scope": args.scope,
        "created_unix": time.time(),
        "host": platform.platform(),
        "cwd": os.getcwd(),
        "python": args.python,
        "script": {"path": str(args.script),
                   "sha256": file_sha256(args.script)},
        "sources": [{"path": str(path), "sha256": file_sha256(path)}
                    for path in args.source],
        "script_args": script_args,
        "artifact_paths": [str(path) for path in args.artifact],
        "modes": [],
    }
    args.manifest.parent.mkdir(parents=True, exist_ok=True)
    atomic_json(args.manifest, manifest)

    for name, flags, hash_seed in modes:
        command = [args.python, *flags, str(args.script), *script_args]
        stdout_path = Path(str(args.manifest) + f".{name}.stdout.log")
        stderr_path = Path(str(args.manifest) + f".{name}.stderr.log")
        environment = dict(os.environ)
        environment["PYTHONHASHSEED"] = hash_seed
        started = time.monotonic()
        timed_out = False
        with stdout_path.open("w") as stdout, stderr_path.open("w") as stderr:
            try:
                completed = subprocess.run(
                    command, stdout=stdout, stderr=stderr, text=True,
                    env=environment, timeout=args.timeout, check=False)
                returncode = completed.returncode
            except subprocess.TimeoutExpired:
                timed_out = True
                returncode = None
        elapsed = time.monotonic() - started
        record = {
            "name": name, "command": command, "pythonhashseed": hash_seed,
            "elapsed_seconds": elapsed, "returncode": returncode,
            "timed_out": timed_out,
            "stdout": {"path": str(stdout_path),
                       "bytes": stdout_path.stat().st_size,
                       "sha256": file_sha256(stdout_path)},
            "stderr": {"path": str(stderr_path),
                       "bytes": stderr_path.stat().st_size,
                       "sha256": file_sha256(stderr_path)},
        }
        if not timed_out and returncode == 0:
            record["artifacts"] = hash_artifacts(args.artifact)
            record["status"] = "completed"
        else:
            record["status"] = "timeout" if timed_out else "process_error"
        manifest["modes"].append(record)
        atomic_json(args.manifest, manifest)
        if record["status"] != "completed":
            raise SystemExit(f"checker mode {name} failed: {record['status']}")

    reference = [(item["path"], item["sha256"])
                 for item in manifest["modes"][0]["artifacts"]]
    for mode in manifest["modes"][1:]:
        observed = [(item["path"], item["sha256"])
                    for item in mode["artifacts"]]
        if observed != reference:
            manifest["status"] = "artifact_mismatch"
            atomic_json(args.manifest, manifest)
            raise SystemExit(f"checker artifacts differ in mode {mode['name']}")

    manifest["status"] = "completed_exact_replay"
    manifest["logical_sha256"] = logical_digest(manifest)
    atomic_json(args.manifest, manifest)
    print(f"checker modes: PASS ({manifest['logical_sha256']})")


if __name__ == "__main__":
    main()
