#!/usr/bin/env python3
"""Independent finite audit of the orbit-0 anchor strategy.

This checker verifies the representative and its full S8 x S3 stabilizer.
It also records the elementary homogeneous-degree implication which makes a
cutoff-13 identity for any single anchor chart a global identity.
"""

from __future__ import annotations

from hashlib import sha256
from itertools import permutations
import json
from math import factorial
from pathlib import Path


HERE = Path(__file__).resolve().parent
OUT = HERE / "results_orbit0_global_strategy.json"
SITES = tuple(range(8))
COLOURS = tuple(range(3))
M0 = ((0, 1), (2, 3), (4, 5), (6, 7))
TRIPLE = (M0, M0, M0)


def canonical_matching(edges):
    return tuple(sorted(tuple(sorted(edge)) for edge in edges))


def act(triple, site_permutation, colour_permutation):
    moved = tuple(canonical_matching(
        (site_permutation[left], site_permutation[right])
        for left, right in matching
    ) for matching in triple)
    inverse_colour = [None] * 3
    for source, target in enumerate(colour_permutation):
        inverse_colour[target] = source
    return tuple(moved[inverse_colour[target]] for target in COLOURS)


def main():
    orbit = set()
    stabilizer = []
    for site_permutation in permutations(SITES):
        for colour_permutation in permutations(COLOURS):
            image = act(TRIPLE, site_permutation, colour_permutation)
            orbit.add(image)
            if image == TRIPLE:
                stabilizer.append((site_permutation, colour_permutation))

    group_order = factorial(8) * factorial(3)
    site_matching_stabilizer = (2 ** 4) * factorial(4)
    assert len(orbit) == 105
    assert len(stabilizer) == 2304
    assert len(stabilizer) == site_matching_stabilizer * factorial(3)
    assert len(orbit) * len(stabilizer) == group_order

    anchors = tuple((colour, left, right, colour, colour)
                    for colour in COLOURS for left, right in M0)
    assert len(set(anchors)) == 12

    output = {
        "status": "exact finite audit",
        "orbit": 0,
        "representative": TRIPLE,
        "anchor_cells": anchors,
        "anchor_cell_count": len(anchors),
        "group": "S8 x S3",
        "group_order": group_order,
        "site_matching_stabilizer_order": site_matching_stabilizer,
        "colour_stabilizer_order": factorial(3),
        "full_anchor_stabilizer_order": len(stabilizer),
        "orbit_size": len(orbit),
        "orbit_stabilizer_check": len(orbit) * len(stabilizer) == group_order,
        "homogeneous_global_implication": {
            "T": "H0*H1*H2 is chart-independent and homogeneous of degree 12",
            "I_mix": "global chart-independent homogeneous ideal generated by all 6558 mixed H_z in degree 4",
            "K_anchor": "chart-dependent ideal generated by the 240 cells outside the 12 anchors",
            "degree_12_part_of_K_anchor_power_13": 0,
            "conclusion": "for this or any fixed chart, T in I_mix + K_anchor^13 implies T in I_mix",
        },
    }
    canonical = json.dumps(output, indent=2, sort_keys=True) + "\n"
    OUT.write_text(canonical)
    print(canonical, end="")
    print("sha256", sha256(canonical.encode()).hexdigest())


if __name__ == "__main__":
    main()
