#!/usr/bin/env python3
"""Exact compact mate-H unit conditional on the two-prime slice support."""

from __future__ import annotations

from collections import Counter
from hashlib import sha256
import importlib.util
import json
from pathlib import Path
import sys


HERE = Path(__file__).resolve().parent
CORE_PATH = (HERE.parent /
             "unaudited-codex-n8-orbit0-normalized-78-2026-08-20" /
             "audit_polarized_superpair_core_identity.py")
SLICE_RESULT = HERE / "results_generic_cycle_left_slices_mate_export.json"
OUT = HERE / "results_mate_compact_identity.json"
ZERO_CELLS = frozenset((1, 2, 6, 10, 14, 18, 21, 22))
FORCED_Q = frozenset((0, 4, 5, 6, 8, 9, 10, 12, 13, 14, 15))
CHOSEN_Q = (0, 12, 5, 6)


def load(name, path):
    spec = importlib.util.spec_from_file_location(name, path)
    module = importlib.util.module_from_spec(spec)
    sys.modules[name] = module
    assert spec.loader is not None
    spec.loader.exec_module(module)
    return module


CORE = load("generic_cycle_mate_compact_core", CORE_PATH)


def require(condition, detail):
    if not condition:
        raise RuntimeError(detail)


def clean(poly):
    return Counter({monomial: coefficient for monomial, coefficient in poly.items()
                    if coefficient})


def add(*polys):
    result = Counter()
    for poly in polys:
        result.update(poly)
    return clean(result)


def scale(poly, coefficient):
    return clean(Counter({monomial: coefficient*value
                          for monomial, value in poly.items()}))


def multiply(*polys):
    result = Counter({(): 1})
    for poly in polys:
        updated = Counter()
        for left, lc in result.items():
            for right, rc in poly.items():
                updated[tuple(sorted(left+right))] += lc*rc
        result = clean(updated)
    return result


def specialize(poly):
    return clean(Counter({monomial: coefficient
                          for monomial, coefficient in poly.items()
                          if not any(variable in ZERO_CELLS
                                     for variable in monomial)}))


def q(index):
    bits = tuple((index >> (3-site)) & 1 for site in range(4))
    return specialize(CORE.q_orientation(bits))


def main():
    slices = json.loads(SLICE_RESULT.read_text())
    records = slices["records"]
    require(len(records) == 2 and all(
        set(record["cofactor_support"]) == ZERO_CELLS
        and {15-index for index in record["Q_support"]} == FORCED_Q
        for record in records), "two-prime slice incidence supports changed")

    h = specialize(CORE.pure_hafnian())
    e = {edge: specialize(CORE.e_pair(*edge))
         for edge in CORE.SUPER_EDGES}
    t = {triple: specialize(CORE.t_triple(*triple))
         for triple in __import__("itertools").combinations(range(4), 3)}
    q_values = {index: q(index) for index in range(16)}
    structural_q_zeros = {index for index, poly in q_values.items() if not poly}
    require(structural_q_zeros == {4, 8, 13, 14},
            "structural Q-zero set changed")
    require(set(CHOSEN_Q).issubset(FORCED_Q),
            "chosen compact Q rows ceased to be directional consequences")

    # Specialize the exact polarized identity, selecting one available zero
    # factor for each nonstructural complementary Q pair and one e row in
    # each complementary edge pair.
    rhs = Counter()
    for poly in t.values():
        rhs = add(rhs, poly)
    rhs = add(rhs,
              multiply(q_values[0], q_values[15]),
              multiply(q_values[3], q_values[12]),
              multiply(q_values[5], q_values[10]),
              multiply(q_values[6], q_values[9]))
    rhs = add(rhs,
              scale(multiply(e[(0, 1)], e[(2, 3)]), -1),
              scale(multiply(e[(0, 2)], e[(1, 3)]), -1),
              scale(multiply(e[(0, 3)], e[(1, 2)]), -1))
    require(h == rhs, "specialized polarized Hafnian identity changed")

    # The displayed RHS is in the ideal generated by precisely 3 e, 4 t,
    # and 4 forced Q rows.  Append a fresh u variable and replay the explicit
    # Rabinowitsch unit 1 = u*rhs - (u*H-1).
    u_index = 24
    u = Counter({(u_index,): 1})
    one = Counter({(): 1})
    rabinowitsch = add(multiply(u, h), scale(one, -1))
    certificate = add(multiply(u, rhs), scale(rabinowitsch, -1))
    require(certificate == one, "compact mate-H unit failed")
    mutation = add(certificate, t[(0, 1, 2)])
    require(mutation != one, "compact identity mutation failed")

    result = {
        "status": "UNAUDITED exact compact conditional mate-H UNIT PASS",
        "ambient_quotient": (
            "Q[x0,...,x23,u]/(x1,x2,x6,x10,x14,x18,x21,x22)"),
        "zero_cells_from_left_cofactors": sorted(ZERO_CELLS),
        "structural_Q_zeros": sorted(structural_q_zeros),
        "directionally_forced_Q_zeros": sorted(FORCED_Q),
        "compact_generators": {
            "e_rows": ["e_01", "e_02", "e_03"],
            "triangle_rows": ["t_012", "t_013", "t_023", "t_123"],
            "Q_rows": [f"Q_{index}" for index in CHOSEN_Q],
            "ordinary_count": 11,
            "mate_H_rabinowitsch": "u*H-1",
        },
        "identity": {
            "H": (
                "sum(t_ijk) + Q0*Q15 + Q3*Q12 + Q5*Q10 + Q6*Q9 "
                "- e01*e23 - e02*e13 - e03*e12"),
            "unit": "1 = u*(displayed H expansion) - (u*H-1)",
            "literal_replay": True,
            "mutation_control": True,
        },
        "conclusion": (
            "Any left presentation with the declared cofactor/Q incidence "
            "support has no mate satisfying e/t, complement Q, and mate-H "
            "liveness. The mate cofactor rows forced by left X are not "
            "needed in this compact core."),
        "scope_guard": (
            "The polynomial identity is exact over Q. Its application to "
            "the generic-cycle A=B=0 component is currently two-prime "
            "generic-slice evidence because the left incidence support has "
            "not been proved constant over a characteristic-zero dense open."),
        "source_hashes": {
            "core": sha256(CORE_PATH.read_bytes()).hexdigest(),
            "slice_result": sha256(SLICE_RESULT.read_bytes()).hexdigest(),
        },
        "must_fire": [
            "two-prime support agreement",
            "four structural Q zeros",
            "specialized polarized Hafnian identity",
            "explicit Rabinowitsch unit",
            "triangle-row mutation",
        ],
    }
    logical = json.dumps(result, sort_keys=True, separators=(",", ":"))
    result["result_sha256"] = sha256(logical.encode("ascii")).hexdigest()
    OUT.write_text(json.dumps(result, indent=2, sort_keys=True)+"\n")
    print("generic-cycle compact mate-H identity: PASS")
    print("zero/Q/core", len(ZERO_CELLS), len(FORCED_Q), 11)
    print("result", result["result_sha256"])


if __name__ == "__main__":
    main()
