"""AUDIT A1 / CLAIM 4 -- EXACT certification of the counterexample to W3's
phase-only reduction.

THE WITNESS.  n = 8.  Thirteen cells (only colours 0 and 1 occur):

    a0=(0,1|0,1)  a1=(0,3|0,1)  a2=(0,4|0,0)  a3=(0,7|0,1)  a4=(1,2|1,0)
    a5=(1,5|0,0)  a6=(2,3|0,1)  a7=(2,6|0,0)  a8=(3,4|1,0)  a9=(3,7|0,0)
    a10=(4,5|0,1) a11=(5,6|1,0) a12=(6,7|0,1)

Live words and their fibres (every other word has an EMPTY fibre, so its
GHZ equation 0 = 0 holds identically):

   pure  00000000 :  a2 a5 a7 a9                             = 1
   mixed 01000100 :  a0 a7 a9 a10 + a2 a4 a9 a11             = 0    (2 terms)
   mixed 00010001 :  a2 a5 a6 a12 + a3 a5 a7 a8              = 0    (2 terms)
   mixed 01010101 :  a0 a6 a10 a12 + a1 a4 a10 a12
                                        + a3 a4 a8 a11       = 0    (3 terms)

NO mixed fibre is a singleton, so W3's M9 is silent.

FORCED MODULUS CONDITION.  Write T1 = a0 a6 a10 a12, T2 = a1 a4 a10 a12,
T3 = a3 a4 a8 a11.  Dividing the two 2-term equations by the nonzero cells
a9 and a5 gives a0 a7 a10 = -a2 a4 a11 and a2 a6 a12 = -a3 a7 a8, whence

     T1 = (a0 a7 a10)(a6 a12)/a7 = -(a2 a4 a11)(a6 a12)/a7
        = -(a2 a6 a12)(a4 a11)/a7 = (a3 a7 a8)(a4 a11)/a7 = T3 .

So the 3-term equation collapses to 2 T1 + T2 = 0, i.e.

              |a1 a4| = 2 |a0 a6|                                  (*)

(*) is a modulus-level NECESSARY condition on this support.  It is not a
singleton fibre and not a missing pure row, and it is VIOLATED by all moduli
= 1.  By W3's own crux lemma L1 every gauge transform multiplies all terms
of one fibre by the same factor, so on the whole gauge orbit of the
all-moduli-1 point |T1| = |T2|; (*) is therefore violated on that entire
orbit, not just at the base point.

Meanwhile the system IS solvable over C with support exactly S: see SOL.
"""

from __future__ import annotations

from fractions import Fraction

from a1_core import COLS, all_words, phi
from a1_phase import fibres, is_mixed

N = 8

CELLS = [
    (0, 1, 0, 1), (0, 3, 0, 1), (0, 4, 0, 0), (0, 7, 0, 1), (1, 2, 1, 0),
    (1, 5, 0, 0), (2, 3, 0, 1), (2, 6, 0, 0), (3, 4, 1, 0), (3, 7, 0, 0),
    (4, 5, 0, 1), (5, 6, 1, 0), (6, 7, 0, 1),
]
S = frozenset(CELLS)

# a0..a12 in the order of CELLS
VALS = [1, -2, 1, 1, 1, 1, 1, 1, -1, 1, 1, -1, 1]
SOL = {c: Fraction(v) for c, v in zip(CELLS, VALS)}


def full_ghz_check(a):
    """Evaluate EVERY one of the 3^8 GHZ equations exactly."""
    bad_mixed = []
    pures = {}
    for w in all_words(N):
        val = phi(a, w, N, Fraction(0), Fraction(1))
        if len(set(w)) == 1:
            pures[w[0]] = val
        elif val != 0:
            bad_mixed.append((w, val))
    return bad_mixed, pures


def unit_modulus_impossible():
    """Exact statement of the obstruction, re-derived symbolically."""
    import sympy as sp

    a = sp.symbols("a0:13")
    idx = {c: i for i, c in enumerate(CELLS)}
    fib = fibres(N, S)
    eqs = {}
    for w, terms in fib.items():
        eqs[w] = sum(sp.prod([a[idx[k]] for k in M]) for M in terms)
    e2a = eqs[(0, 1, 0, 0, 0, 1, 0, 0)]
    e2b = eqs[(0, 0, 0, 1, 0, 0, 0, 1)]
    e3 = eqs[(0, 1, 0, 1, 0, 1, 0, 1)]
    T1 = a[idx[(0, 1, 0, 1)]] * a[idx[(2, 3, 0, 1)]] * a[idx[(4, 5, 0, 1)]] \
        * a[idx[(6, 7, 0, 1)]]
    T2 = a[idx[(0, 3, 0, 1)]] * a[idx[(1, 2, 1, 0)]] * a[idx[(4, 5, 0, 1)]] \
        * a[idx[(6, 7, 0, 1)]]
    T3 = a[idx[(0, 7, 0, 1)]] * a[idx[(1, 2, 1, 0)]] * a[idx[(3, 4, 1, 0)]] \
        * a[idx[(5, 6, 1, 0)]]
    # T1 - T3 must lie in the ideal generated by the two 2-term equations
    # after saturating by the cell variables; check it by explicit cofactors.
    a9 = a[idx[(3, 7, 0, 0)]]
    a5 = a[idx[(1, 5, 0, 0)]]
    a7 = a[idx[(2, 6, 0, 0)]]
    c1 = a[idx[(2, 3, 0, 1)]] * a[idx[(6, 7, 0, 1)]]          # cofactor of e2a
    c2 = a[idx[(1, 2, 1, 0)]] * a[idx[(5, 6, 1, 0)]]          # cofactor of e2b
    lhs = sp.expand(a7 * a9 * a5 * (T1 - T3))
    rhs = sp.expand(a5 * c1 * e2a - a9 * c2 * e2b)
    return sp.simplify(lhs - rhs) == 0, sp.expand(e3 - (2 * T1 + T2)), \
        sp.simplify(sp.expand(e3 - T1 - T2 - T3))


if __name__ == "__main__":
    print("AUDIT A1 / claim 4 -- exact certification of the phase witness")
    print("=" * 78)
    fib = fibres(N, S)
    sing = [w for w, t in fib.items() if is_mixed(w) and len(t) == 1]
    print(f"support size {len(S)}; live words {len(fib)}; "
          f"singleton mixed fibres {len(sing)} (M9 {'FIRES' if sing else 'silent'})")
    print("live pure rows:", sorted(w[0] for w in fib if not is_mixed(w)))

    bad, pures = full_ghz_check(SOL)
    print(f"\n[exact] all 3^8 GHZ equations at SOL: violated MIXED equations = "
          f"{len(bad)}; pure values = {pures}")
    print(f"[exact] every cell of SOL is nonzero: "
          f"{all(v != 0 for v in SOL.values())}; moduli = "
          f"{sorted(set(abs(v) for v in SOL.values()))}")

    ok, collapse, sanity = unit_modulus_impossible()
    print(f"\n[symbolic] T1 - T3 is a cofactor combination of the two 2-term "
          f"equations: {ok}")
    print(f"[symbolic] 3-term equation minus (2*T1 + T2) = {collapse}")
    print(f"[symbolic] 3-term equation equals T1+T2+T3: {sanity == 0}")

    # the modulus statement, evaluated at the witness and at all-ones
    T1v = SOL[(0, 1, 0, 1)] * SOL[(2, 3, 0, 1)] * SOL[(4, 5, 0, 1)] * SOL[(6, 7, 0, 1)]
    T2v = SOL[(0, 3, 0, 1)] * SOL[(1, 2, 1, 0)] * SOL[(4, 5, 0, 1)] * SOL[(6, 7, 0, 1)]
    print(f"\n[exact] at SOL: |T1| = {abs(T1v)}, |T2| = {abs(T2v)}  -> "
          f"|T2| = 2|T1| holds")
    print("[exact] at all-moduli-1 (and on its whole gauge orbit, by L1) "
          "|T1| = |T2|, so |T2| = 2|T1| forces |T1| = 0: IMPOSSIBLE.")

    # MUTATION CONTROLS
    print("\nMUTATION CONTROLS")
    m = dict(SOL)
    m[(0, 3, 0, 1)] = Fraction(-1)         # break |T2| = 2|T1|
    bad2, pures2 = full_ghz_check(m)
    print(f"  mutant a1 = -1 (all moduli 1): violated mixed equations = "
          f"{len(bad2)} -> " + ("KILLED" if bad2 else "*** SURVIVED ***"))
    m = dict(SOL)
    m[(5, 6, 1, 0)] = Fraction(1)          # flip a sign in the 2-term chain
    bad3, _ = full_ghz_check(m)
    print(f"  mutant a11 = +1: violated mixed equations = {len(bad3)} -> "
          + ("KILLED" if bad3 else "*** SURVIVED ***"))
    m = dict(SOL)
    del m[(0, 3, 0, 1)]                    # shrink the support
    bad4, _ = full_ghz_check(m)
    print(f"  mutant: cell a1 deleted (support shrinks): violated mixed = "
          f"{len(bad4)} -> " + ("KILLED" if bad4 else
                                "*** SURVIVED: support not minimal ***"))
