//! Source-faithful H18PIV2 fold for the strict K24 singleton
//! D14:222|R:2-2-2-4.  Scalar terminal output only; no K25 or row/column output.
mod fold {
include!("k24_hidden_base.rs");
const INPUT:&str="computations/unaudited-codex-orbit0-hidden-k16-k2-full-orbit-2026-08-23/checkpoint_k18_22_pivotable.bin";
const TOTAL:u64=158_439_965;
const DEFAULT_OUT:&str="computations/unaudited-codex-orbit0-k24-hidden-collected-k18-2026-08-24/results_k24_hidden_collected_k18.json";
const ID:&str="D14:222|R:2-2-2-4";

#[derive(Clone,Default)]struct K18Plan{k2:Vec<(u8,u8,[u8;12])>}
#[derive(Clone,Copy,Default)]struct Sink{parents:u64,p3_uses:u64,k20:u64,pivotable_k20:u64,p4_uses:u64,terminal:u64,charge:i128}
#[derive(Clone,Copy)]struct Parent{row:Row,weight_before_p3:i128,witness_pair:Row,p2:u8,t2:u8,pair_uses:u64,orbit:u16,stabilizer:u16,m2:u8}
fn decode(rec:&[u8;80])->Parent{let mut row=[0;24];row.copy_from_slice(&rec[..24]);let mut witness=[0;24];witness.copy_from_slice(&rec[40..64]);assert_eq!(rec[78],1);Parent{row:Row(row),weight_before_p3:i128::from_le_bytes(rec[24..40].try_into().unwrap()),witness_pair:Row(witness),p2:rec[64],t2:rec[65],pair_uses:u64::from_le_bytes(rec[66..74].try_into().unwrap()),orbit:u16::from_le_bytes(rec[74..76].try_into().unwrap()),stabilizer:u16::from_le_bytes(rec[76..78].try_into().unwrap()),m2:rec[79]}}
fn hex24(row:&Row)->String{row.0.iter().map(|x|format!("{:02x}",x)).collect()}
fn plan18(row:&Row,s:[u8;12],p:usize,e:&Engine,c:&CEnv)->K18Plan{let _prof=path_profile(row,p,e,c);let mut k2=Vec::new();for(ti,t)in e.all_k2[p].iter().enumerate(){let s20=child_sig(s,p,t,e);assert_eq!(s20.iter().map(|&x|x as usize).sum::<usize>(),4);let ps=available(s20,e);if !ps.is_empty(){assert_eq!(ps.len(),1);k2.push((ti as u8,ps[0]as u8,s20))}}K18Plan{k2}}
fn response20_k4(row:&Row,s:[u8;12],p:usize,prof:[u8;29],e:&Engine,c:&CEnv)->i64{let mut q=0;for t in &c.k4[p]{let z=child_sig(s,p,t,e);assert_eq!(z.iter().map(|&x|x as usize).sum::<usize>(),0);assert!(!pivotable_sig(z,e));q+=*c.dual.get(&abstract_ckey(&prof,p,t,e,c)).unwrap_or(&0)}q}
fn literal4(row:&Row,s:[u8;12],p:usize,e:&Engine,c:&CEnv)->i64{let mut q=0;for t in &c.k4[p]{let child=replace_anchor(row,&e.anchors[p],t);let z=child_sig(s,p,t,e);assert_eq!(signature(&child.0,e),z);assert_eq!(z.iter().map(|&x|x as usize).sum::<usize>(),0);assert!(!pivotable_sig(z,e));q+=*c.dual.get(&literal_ckey(&child,c)).unwrap_or(&0)}q}
fn hist(m:&std::collections::BTreeMap<(u8,u8,u8),u64>)->String{m.iter().map(|(&(a,b,c),v)|format!("\"{}_{}_{}\":{}",a,b,c,v)).collect::<Vec<_>>().join(",")}

pub fn run(){
 let args:Vec<_>=std::env::args().collect();let(mut start,mut count,mut samples)=(0u64,TOTAL,false);let mut output=DEFAULT_OUT.to_string();let mut i=1;while i<args.len(){match args[i].as_str(){"--start"=>{start=args[i+1].parse().unwrap();i+=2},"--count"=>{count=args[i+1].parse().unwrap();i+=2},"--samples"=>{samples=true;i+=1},"--output"=>{output=args[i+1].clone();i+=2},_=>panic!("bad argument")}}
 assert!(count>0&&start<=TOTAL&&count<=TOTAL-start);let begun=Instant::now();let e=parse();let c=cenv();assert_eq!(std::fs::metadata(INPUT).unwrap().len(),80+80*TOTAL);let mut f=File::open(INPUT).unwrap();let mut header=[0u8;80];f.read_exact(&mut header).unwrap();assert_eq!(&header[..8],b"H18PIV2\0");assert_eq!(i128::from_le_bytes(header[8..24].try_into().unwrap()),U);assert_eq!(u16::from_le_bytes(header[28..30].try_into().unwrap()),80);assert_eq!(u64::from_le_bytes(header[48..56].try_into().unwrap()),TOTAL);assert_eq!(u64::from_le_bytes(header[56..64].try_into().unwrap()),1);assert_eq!(i128::from_le_bytes(header[64..80].try_into().unwrap()),724_159_651_336_720_220_160);f.seek(SeekFrom::Start(80+80*start)).unwrap();let mut reader=BufReader::with_capacity(16<<20,f);
 let mut cache18:HashMap<PKey,K18Plan>=HashMap::new();let mut cache20:HashMap<PKey,i64>=HashMap::new();let(mut hit18,mut miss18,mut hit20,mut miss20)=(0u64,0u64,0u64,0u64);let mut sink=Sink::default();let(mut source_mass,mut source_l1)=(0i128,0i128);let mut denominators=std::collections::BTreeMap::new();let sample_indices:HashSet<u64>=if samples{(0..257).map(|j|start+j*(count-1)/256).collect()}else{HashSet::new()};let mut lines=vec!["input_index\tK18_row\tretained_K16_pair_witness\tweight_before_p3_scaled_U\tp2\tt2\tpair_uses\torbit\tstabilizer\tm2\tm3\tselected_p3_uses\tpivotable_K20_children\tselected_p4_uses\tterminal_K4_children\tliteral_charge_scaled_U".to_string()];
 for off in 0..count{let idx=start+off;let mut rec=[0u8;80];reader.read_exact(&mut rec).unwrap();let x=decode(&rec);let s18=signature(&x.row.0,&e);assert_eq!(s18.iter().map(|&z|z as usize).sum::<usize>(),6);let ps3=available(s18,&e);let m3=ps3.len();assert!(m3>0);assert_eq!(x.weight_before_p3%(m3 as i128),0);assert_eq!(U%((x.m2 as i128)*(m3 as i128)),0);sink.parents+=1;source_mass+=x.weight_before_p3;source_l1+=x.weight_before_p3.abs();let(mut sample_charge,mut sample_k20,mut sample_p4,mut sample_terminal)=(0i128,0u64,0u64,0u64);
  for p3 in ps3{sink.p3_uses+=1;let prof18=path_profile(&x.row,p3,&e,&c);let key18=PKey{profile:prof18,sig:s18,pivot:p3 as u8};let plan=if let Some(z)=cache18.get(&key18){hit18+=1;z.clone()}else{miss18+=1;let z=plan18(&x.row,s18,p3,&e,&c);cache18.insert(key18,z.clone());z};
   for(t1,p4,s20)in plan.k2{sink.k20+=1;sink.pivotable_k20+=1;sample_k20+=1;let row20=replace_anchor(&x.row,&e.anchors[p3],&e.all_k2[p3][t1 as usize]);assert_eq!(signature(&row20.0,&e),s20);let ps4=available(s20,&e);assert_eq!(ps4,vec![p4 as usize]);let m4=ps4.len();assert_eq!(m4,1);assert_eq!(x.weight_before_p3%((m3*m4)as i128),0);assert_eq!(U%((x.m2 as i128)*(m3 as i128)*(m4 as i128)),0);sink.p4_uses+=1;sample_p4+=1;let prof20=path_profile(&row20,p4 as usize,&e,&c);let key20=PKey{profile:prof20,sig:s20,pivot:p4};let q=if let Some(&z)=cache20.get(&key20){hit20+=1;z}else{miss20+=1;let z=response20_k4(&row20,s20,p4 as usize,prof20,&e,&c);cache20.insert(key20,z);z};let weight=x.weight_before_p3/((m3*m4)as i128);sink.terminal+=60;sink.charge+=weight*(q as i128);if sample_indices.contains(&idx){assert_eq!(literal4(&row20,s20,p4 as usize,&e,&c),q);sample_terminal+=60;sample_charge+=weight*(q as i128)}*denominators.entry((x.m2,m3 as u8,m4 as u8)).or_default()+=1;
   }}
  if sample_indices.contains(&idx){lines.push(format!("{}\t{}\t{}\t{}\t{}\t{}\t{}\t{}\t{}\t{}\t{}\t{}\t{}\t{}\t{}\t{}",idx,hex24(&x.row),hex24(&x.witness_pair),x.weight_before_p3,x.p2,x.t2,x.pair_uses,x.orbit,x.stabilizer,x.m2,m3,m3,sample_k20,sample_p4,sample_terminal,sample_charge))}
 }
 assert_eq!(sink.parents,count);assert_eq!(sink.k20,sink.pivotable_k20);assert_eq!(sink.k20,sink.p4_uses);assert_eq!(sink.terminal,60*sink.p4_uses);if start==0&&count==TOTAL{assert!(samples,"full production requires the 257-record source-backed literal ledger");assert_eq!(lines.len(),258);assert_eq!(source_mass,724_159_651_336_720_220_160);assert_eq!(sink.p3_uses,399_275_484);assert_eq!(sink.k20,570_281_318);assert_eq!(sink.terminal,34_216_879_080);}let elapsed=begun.elapsed().as_secs_f64();if start==0&&count==TOTAL{assert!(elapsed<600.0,"hard 600-second gate exceeded")}let projected=elapsed*TOTAL as f64/count as f64;let status=if start==0&&count==TOTAL{"PASS_COMPLETE_HIDDEN_COLLECTED_K18_K24_SINGLETON_CHARGE"}else{"PASS_BOUNDED_HIDDEN_COLLECTED_K18_K24_GATE"};
 let sample_path=format!("{}.samples.tsv",output);if samples{let tmp=format!("{}.tmp",sample_path);std::fs::write(&tmp,format!("{}\n",lines.join("\n"))).unwrap();rename(tmp,&sample_path).unwrap()}let text=format!("{{\n  \"status\":\"{}\",\n  \"degree\":24,\n  \"scale_U\":\"{}\",\n  \"input\":\"{}\",\n  \"input_interval\":[{},{}],\n  \"input_records\":{},\n  \"strict_id\":\"{}\",\n  \"input_weight_sum_scaled_U\":\"{}\",\n  \"input_weight_l1_scaled_U\":\"{}\",\n  \"selected_K18_p3_uses\":{},\n  \"pivotable_K20_children\":{},\n  \"selected_K20_p4_uses\":{},\n  \"terminal_K4_tails\":{},\n  \"full_occurrences\":{},\n  \"irreducible_occurrences\":{},\n  \"full_charge_scaled_U\":\"{}\",\n  \"irreducible_charge_scaled_U\":\"{}\",\n  \"sign_rule\":\"H18 weight w; K2 response gives -w/m3; terminal K4 response gives +w/(m3*m4)\",\n  \"m2_m3_m4_hist\":{{{}}},\n  \"cache\":{{\"K18_keys\":{},\"K18_hits\":{},\"K18_misses\":{},\"K20_K4_keys\":{},\"K20_K4_hits\":{},\"K20_K4_misses\":{}}},\n  \"literal_sample_source_records\":{},\n  \"literal_sample_ledger\":{},\n  \"terminality\":\"every K24 K4 child has active-anchor mass 0, hence no frozen pivot\",\n  \"full_equals_irreducible\":true,\n  \"elapsed_seconds\":{:.6},\n  \"projected_full_seconds\":{:.6},\n  \"scope\":\"strict singleton D14:222|R:2-2-2-4 scalar only; no rows/columns, K25, membership, or conjecture verdict\"\n}}\n",status,U,INPUT,start,start+count,count,ID,source_mass,source_l1,sink.p3_uses,sink.k20,sink.p4_uses,sink.terminal,sink.terminal,sink.terminal,sink.charge,sink.charge,hist(&denominators),cache18.len(),hit18,miss18,cache20.len(),hit20,miss20,if samples{sample_indices.len()}else{0},if samples{format!("\"{}\"",sample_path)}else{"null".to_string()},elapsed,projected);let tmp=format!("{}.tmp",output);std::fs::write(&tmp,&text).unwrap();rename(tmp,&output).unwrap();print!("{}",text)
}
}
fn main(){fold::run()}
