#!/usr/bin/env python3
"""Discovery probe for the eight cofactor orientation classes over Q.

Gauge-fix the three star-edge choices to diagonal.  The remaining bits on
12,13,23 give eight endpoint-switching classes, in three S4 orbits according
to the weight 0,2,4 of the four triangle parities.  For representatives, ask
Singular for basic Groebner/dimension data of the ideal generated by six
e_ij, four t_ijk, and the twelve selected cofactor entries.

This is a probe, not a proof artifact: timeouts and nonzero remainders are
reported without interpretation.
"""

from __future__ import annotations

from collections import Counter
import importlib.util
from itertools import combinations, product
import json
from pathlib import Path
import subprocess


HERE = Path(__file__).resolve().parent
CORE_PATH = HERE / "audit_polarized_superpair_core_identity.py"
OUT = HERE / "results_probe_cofactor_orientation_classes.json"


def load_core():
    spec = importlib.util.spec_from_file_location("n8_orientation_core", CORE_PATH)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


CORE = load_core()


def require(condition, detail):
    if not condition:
        raise RuntimeError(detail)


def derivative(poly, variable):
    answer = Counter()
    for monomial, coefficient in poly.items():
        multiplicity = monomial.count(variable)
        if multiplicity:
            reduced = list(monomial)
            reduced.remove(variable)
            answer[tuple(reduced)] += coefficient * multiplicity
    return CORE.clean(answer)


def singular(poly):
    if not poly:
        return "0"
    terms = []
    for monomial, coefficient in sorted(poly.items()):
        factors = [f"x{variable}" for variable in monomial]
        body = "*".join(factors) if factors else "1"
        terms.append(f"({coefficient})*{body}")
    return "+".join(terms)


def orientation_bits(tail):
    return (0, 0, 0) + tuple(tail)


def triangle_parities(bits):
    b01, b02, b03, b12, b13, b23 = bits
    return (b01 ^ b02 ^ b12,
            b01 ^ b03 ^ b13,
            b02 ^ b03 ^ b23,
            b12 ^ b13 ^ b23)


def equations(bits):
    equations = []
    for edge in CORE.SUPER_EDGES:
        equations.append(CORE.add(CORE.ONE, CORE.permanent(*edge)))
    for triple in combinations(range(4), 3):
        equations.append(CORE.t_triple(*triple))
    z = CORE.pure_hafnian()
    for edge_index, bit in enumerate(bits):
        entries = (0, 3) if bit == 0 else (1, 2)
        for entry in entries:
            equations.append(derivative(z, 4 * edge_index + entry))
    return equations, z


def run_probe(bits, timeout=45):
    eqs, z = equations(bits)
    variables = ",".join(f"x{i}" for i in range(24))
    command = (
        f"ring R=0,({variables}),dp; "
        f"ideal I={','.join(singular(poly) for poly in eqs)}; "
        "ideal G=std(I); "
        "print(\"BEGIN\"); size(G); dim(G); vdim(G); "
        f"poly h={singular(z)}; poly r=reduce(h,G); size(r); "
        "print(\"END\"); quit;"
    )
    try:
        completed = subprocess.run(["Singular", "-q", "-c", command],
                                   text=True, capture_output=True,
                                   timeout=timeout, check=False)
        return {
            "returncode": completed.returncode,
            "stdout": completed.stdout.splitlines(),
            "stderr": completed.stderr.splitlines(),
            "timeout": False,
        }
    except subprocess.TimeoutExpired as error:
        return {
            "returncode": None,
            "stdout": (error.stdout or "").splitlines()
                      if isinstance(error.stdout, str) else [],
            "stderr": (error.stderr or "").splitlines()
                      if isinstance(error.stderr, str) else [],
            "timeout": True,
        }


def main():
    classes = []
    for tail in product((0, 1), repeat=3):
        bits = orientation_bits(tail)
        parities = triangle_parities(bits)
        classes.append({
            "tail_12_13_23": list(tail),
            "edge_bits_01_02_03_12_13_23": list(bits),
            "triangle_parities_012_013_023_123": list(parities),
            "triangle_parity_weight": sum(parities),
        })
    require(Counter(row["triangle_parity_weight"] for row in classes)
            == {0: 1, 2: 6, 4: 1}, "orientation class census changed")

    representatives = {}
    for weight in (0, 2, 4):
        row = next(row for row in classes
                   if row["triangle_parity_weight"] == weight)
        representatives[str(weight)] = {
            "class": row,
            "probe": run_probe(tuple(row["edge_bits_01_02_03_12_13_23"])),
        }
    result = {
        "status": "UNAUDITED characteristic-zero orientation-class probe",
        "endpoint_switching_classes": classes,
        "S4_orbit_weights": {"0": 1, "2": 6, "4": 1},
        "representative_probes": representatives,
        "scope": "Discovery Groebner data only; no closure claim.",
    }
    OUT.write_text(json.dumps(result, indent=2, sort_keys=True) + "\n")
    for weight, row in representatives.items():
        print("weight", weight, "timeout", row["probe"]["timeout"],
              "stdout", row["probe"]["stdout"][-8:])


if __name__ == "__main__":
    main()
