mod eval {
 #![allow(dead_code)]
 include!("../unaudited-codex-orbit0-filtered-k18-charge-2026-08-23/run_k18_charge.rs");
 use std::fs::{File,metadata,rename};use std::io::{BufReader,Read,Seek,SeekFrom,Write};
 const P:&str="computations/unaudited-codex-orbit0-k16-k2-full-export-2026-08-23/checkpoint_k16_k2_profiles_merged.bin";
 const OUT:&str="computations/unaudited-codex-orbit0-k16-k2-full-export-2026-08-23/results_k16_k2_group_charge.json";
 const SAMPLES:&str="computations/unaudited-codex-orbit0-k16-k2-full-export-2026-08-23/k16_k2_group_charge_samples.tsv";
 const H:usize=128;const R:usize=104;const U:i128=400_591_699_200;const N:u64=6_876_260;const WORKERS:usize=8;const GATE:f64=600.0;
 #[derive(Default)]struct Sum{records:u64,tail_evals:u64,full_occ:u64,irr_tail_evals:u64,irr_occ:u64,full_coeff:i128,irr_coeff:i128,full_charge:i128,irr_charge:i128,weight:i128,uses:u64,first:Option<[u8;42]>,last:Option<[u8;42]>,samples:Vec<String>}
 fn i128x(x:&[u8])->i128{i128::from_le_bytes(x.try_into().unwrap())}fn u64x(x:&[u8])->u64{u64::from_le_bytes(x.try_into().unwrap())}fn hx(x:&[u8])->String{x.iter().map(|b|format!("{:02x}",b)).collect()}
 fn worker(e:Arc<E>,start:u64,end:u64,begun:Arc<Instant>)->Sum{let mut f=File::open(P).unwrap();f.seek(SeekFrom::Start(H as u64+R as u64*start)).unwrap();let mut r=BufReader::with_capacity(1<<20,f);let mut z=Sum::default();let mut prior=None;for index in start..end{let mut x=[0u8;R];r.read_exact(&mut x).unwrap();let mut key=[0u8;42];key.copy_from_slice(&x[..42]);if let Some(p)=prior{assert!(p<key)}prior=Some(key);if z.first.is_none(){z.first=Some(key)}z.last=Some(key);let weight=i128x(&x[42..58]);let uses=u64x(&x[58..66]);assert_ne!(weight,0);assert!(uses>0);let mut rr=[0u8;24];rr.copy_from_slice(&x[66..90]);let row=Row(rr);let source=u64x(&x[90..98]);let p1=x[98]as usize;let tail1=x[99]as usize;let p=x[100]as usize;let m1=x[101]as i128;let m2=x[102]as usize;let packet=x[103];assert_eq!(p,key[41]as usize);let s=sig(&row,&e);assert_eq!(&s[..],&key[29..41]);assert_eq!(&profile(&row,p,&e)[..],&key[..29]);let ps=avail(s,&e);assert_eq!(ps.len(),m2);assert!(ps.contains(&p));assert!(m1>0&&U%(m1*m2 as i128)==0);assert_eq!(packet,255);assert!(source<24_097_095);assert!(p1<78&&tail1<12);
   let(mut fq,mut iq,mut inn)=(0i64,0i64,0u64);for t in &e.tails[p][0]{let c=replace(&row,&e.anchors[p],t);let q=charge(&c,&e);fq+=q;z.tail_evals+=1;z.full_occ+=uses;if avail(child_sig(s,p,t,&e),&e).is_empty(){iq+=q;inn+=1;z.irr_tail_evals+=1;z.irr_occ+=uses}}
   assert_eq!(e.tails[p][0].len(),12);z.records+=1;z.uses+=uses;z.weight+=weight;z.full_coeff+=12*weight;z.irr_coeff+=(inn as i128)*weight;z.full_charge+=weight*(fq as i128);z.irr_charge+=weight*(iq as i128);
   if index%25_000==0{z.samples.push(format!("{}\t{}\t{}\t{}\t{}\t{}\t{}\t{}\t{}",index,hx(&key),weight,uses,fq,iq,inn,packet,source))}
   if index%250_000==0{assert!(begun.elapsed().as_secs_f64()<580.0)}
  }z}
 pub fn run(){let begun=Arc::new(Instant::now());let mut h=[0u8;H];File::open(P).unwrap().read_exact(&mut h).unwrap();assert_eq!(&h[..8],b"K16MRG1\0");assert_eq!(u64x(&h[32..40]),281);assert_eq!(u64x(&h[40..48]),63_918_401);assert_eq!(u64x(&h[48..56]),1_614_846_654);assert_eq!(u64x(&h[56..64]),N);assert_eq!(u64x(&h[64..72]),203_023);assert_eq!(u64x(&h[72..80]),1_604_299_948);assert_eq!(i128x(&h[80..96]),i128x(&h[96..112]));assert_eq!(u64x(&h[112..120]),10_546_706);assert_eq!(u64x(&h[120..128]),2_049_974_172);assert_eq!(metadata(P).unwrap().len(),H as u64+R as u64*N);
  let e=Arc::new(parse());let mut jobs=Vec::new();for w in 0..WORKERS{let start=N*w as u64/WORKERS as u64;let end=N*(w as u64+1)/WORKERS as u64;let ee=e.clone();let bb=begun.clone();jobs.push(thread::spawn(move||worker(ee,start,end,bb)))}let mut parts=Vec::new();for j in jobs{parts.push(j.join().unwrap())}for i in 1..parts.len(){assert!(parts[i-1].last.unwrap()<parts[i].first.unwrap())}let mut z=Sum::default();for mut q in parts{z.records+=q.records;z.tail_evals+=q.tail_evals;z.full_occ+=q.full_occ;z.irr_tail_evals+=q.irr_tail_evals;z.irr_occ+=q.irr_occ;z.full_coeff+=q.full_coeff;z.irr_coeff+=q.irr_coeff;z.full_charge+=q.full_charge;z.irr_charge+=q.irr_charge;z.weight+=q.weight;z.uses+=q.uses;z.samples.append(&mut q.samples)}assert_eq!(z.records,N);assert_eq!(z.tail_evals,12*N);assert_eq!(z.full_occ,12*1_604_299_948);assert_eq!(z.weight,i128x(&h[96..112]));assert_eq!(z.uses,1_604_299_948);assert_eq!(z.full_coeff,12*z.weight);assert!(begun.elapsed().as_secs_f64()<GATE);
  z.samples.sort();let stmp=format!("{}.tmp",SAMPLES);let mut sw=File::create(&stmp).unwrap();writeln!(sw,"record_index\tkey_hex\tweight_scaled\tuses\tfull_response\tirreducible_response\tirreducible_tails\twitness_packet\twitness_source").unwrap();for x in&z.samples{writeln!(sw,"{}",x).unwrap()}sw.sync_all().unwrap();drop(sw);rename(&stmp,SAMPLES).unwrap();
  let text=format!(concat!("{{\n  \"status\":\"PASS_K16_K2_GROUPED_OCCURRENCEWISE_K20_CHARGE\",\n  \"scope\":\"preaggregated six-ID group D16:{{224,233,242,323,332,422}}|R:2-2; no per-ID scalar reconstruction, rows, K21, or cleanup\",\n",
   "  \"scale_U\":\"{}\",\n  \"workers\":{},\n  \"profile_records\":{},\n  \"profile_tail_evaluations\":{},\n  \"full_source_occurrences\":{},\n  \"irreducible_profile_tail_evaluations\":{},\n  \"irreducible_source_occurrences\":{},\n",
   "  \"input_profile_uses\":{},\n  \"input_weight_scaled\":\"{}\",\n  \"full_coefficient_mass_scaled\":\"{}\",\n  \"irreducible_coefficient_mass_scaled\":\"{}\",\n  \"full_77_charge_scaled\":\"{}\",\n  \"irreducible_77_charge_scaled\":\"{}\",\n",
   "  \"literal_key_guards\":{},\n  \"sample_rows\":{},\n  \"individual_id_charges\":null,\n  \"individual_id_guard\":\"producer checkpoint preaggregated direct K16 packet weights; only grouped subtotal is source-faithful\",\n  \"elapsed_seconds\":{:.6}\n}}\n"),
   U,WORKERS,z.records,z.tail_evals,z.full_occ,z.irr_tail_evals,z.irr_occ,z.uses,z.weight,z.full_coeff,z.irr_coeff,z.full_charge,z.irr_charge,z.records,z.samples.len(),begun.elapsed().as_secs_f64());let tmp=format!("{}.tmp",OUT);std::fs::write(&tmp,&text).unwrap();rename(&tmp,OUT).unwrap();print!("{}",text)}
}
fn main(){eval::run()}
