"""Translate the external U7D witness into our cell/holonomy model and run
our obstruction dichotomy on it.

UNAUDITED EXTERNAL STRESS TEST.  External repo pinned at
https://github.com/YesterdaysLemon/krenn-gu-research/tree/f17afa1c8e72aeba51dafdf1e38afeb903591750

Our model (notes/2026-08-11-signed-matching-holonomy-programme.md):

  cells        a_uv(i, j);  their r=1 matrix-unit table is one cell per pair
  gauge        (C*)^{V x 3},  a_uv(i,j) -> b_{u,i} b_{v,j} a_uv(i,j)
  invariants   L = ker( Z^{cells} --unsigned incidence--> Z^{V x 3} )
               = Zaslavsky's even-cycle (frame) lattice of the cell graph
  L_S          the sublattice generated by the two-term fibre relations of a
               support S, with the sign character epsilon: L_S -> {+-1}
  O1           lambda in L_S with trivial exponent dependency and
               epsilon(lambda) = -1   (a 1 = -1 certificate)
  O2           a mixed fibre whose live terms occupy one class of the
               L_S-character quotient (one-term case = unique matching)
  O3           an ordinary integral certificate on a visible-cell atom

Executable form of O1, mirroring computations/search_n8_binomial_support_full_sat.py
`hnf_odd_relation` and computations/verify_f3_toric_obstruction.py
`find_odd_integer_certificate`: an integer relation among the binomial
exponent rows with ZERO exponent sum and ODD coefficient sum.  The HNF here
is written from scratch (no python-flint dependency) and is mutation-tested
in mutation_controls.py.
"""

from __future__ import annotations

import itertools
from fractions import Fraction

from u7d_witness_data import BRIDGE, CROSS, CYCLE_WORDS, EXPOSED_WORD, TABLE
from verify_u7d_witness import (
    COLOURS,
    ORDER,
    build_fibres,
    circulation,
    matchings_lowest_first,
)

Cell = tuple[int, int, int, int]          # (u, v, label at u, label at v)
Node = tuple[int, int]                    # (vertex, colour)


def support_cells() -> list[Cell]:
    """Their support as cells of our general bicoloured model."""
    return sorted((u, v, i, j) for (u, v), (i, j, _) in TABLE.items())


def cell_of_edge(edge) -> Cell:
    """The unique live cell on a physical pair (r = 1)."""
    left_label, right_label, _ = TABLE[edge]
    return (edge[0], edge[1], left_label, right_label)


def incidence_row(cell: Cell) -> dict[Node, int]:
    """Unsigned incidence image of a cell in Z^{V x 3}."""
    u, v, i, j = cell
    row: dict[Node, int] = {}
    row[(u, i)] = row.get((u, i), 0) + 1
    row[(v, j)] = row.get((v, j), 0) + 1
    return row


# --------------------------------------------------------------------------
# exact integer linear algebra
# --------------------------------------------------------------------------
def _kernel_basis(rows: list[list[Fraction]], width: int) -> list[list[Fraction]]:
    """Rational basis of {x : x^T M = 0} for M the stacked incidence rows."""
    columns = len(rows[0])
    work = [[rows[r][c] for r in range(width)] for c in range(columns)]
    pivots = []
    pivot = 0
    for column in range(width):
        target = next((r for r in range(pivot, len(work)) if work[r][column]), None)
        if target is None:
            continue
        work[pivot], work[target] = work[target], work[pivot]
        head = work[pivot][column]
        work[pivot] = [entry / head for entry in work[pivot]]
        for r in range(len(work)):
            if r != pivot and work[r][column]:
                factor = work[r][column]
                work[r] = [a - factor * b for a, b in zip(work[r], work[pivot])]
        pivots.append(column)
        pivot += 1
    free = [c for c in range(width) if c not in pivots]
    basis = []
    for column in free:
        vector = [Fraction(0)] * width
        vector[column] = Fraction(1)
        for index, pivot_column in enumerate(pivots):
            vector[pivot_column] = -work[index][column]
        basis.append(vector)
    return basis


def rational_rank(rows: list[list[Fraction]]) -> int:
    """Exact rank over Q by fraction-free-ish Gaussian elimination."""
    work = [row[:] for row in rows]
    pivot = 0
    columns = len(work[0]) if work else 0
    for column in range(columns):
        target = next((r for r in range(pivot, len(work)) if work[r][column]), None)
        if target is None:
            continue
        work[pivot], work[target] = work[target], work[pivot]
        head = work[pivot][column]
        work[pivot] = [entry / head for entry in work[pivot]]
        for r in range(len(work)):
            if r != pivot and work[r][column]:
                factor = work[r][column]
                work[r] = [a - factor * b for a, b in zip(work[r], work[pivot])]
        pivot += 1
    return pivot


def hnf_with_transform(rows: list[list[int]]):
    """Row Hermite form H = U * M with U unimodular; integers throughout."""
    matrix = [list(row) for row in rows]
    transform = [[1 if a == b else 0 for b in range(len(rows))]
                 for a in range(len(rows))]
    pivot = 0
    columns = len(matrix[0]) if matrix else 0
    for column in range(columns):
        while True:
            nonzero = [r for r in range(pivot, len(matrix)) if matrix[r][column]]
            if len(nonzero) <= 1:
                break
            nonzero.sort(key=lambda r: abs(matrix[r][column]))
            low, high = nonzero[0], nonzero[1]
            quotient = matrix[high][column] // matrix[low][column]
            matrix[high] = [a - quotient * b
                            for a, b in zip(matrix[high], matrix[low])]
            transform[high] = [a - quotient * b
                               for a, b in zip(transform[high], transform[low])]
        nonzero = [r for r in range(pivot, len(matrix)) if matrix[r][column]]
        if not nonzero:
            continue
        target = nonzero[0]
        matrix[pivot], matrix[target] = matrix[target], matrix[pivot]
        transform[pivot], transform[target] = transform[target], transform[pivot]
        if matrix[pivot][column] < 0:
            matrix[pivot] = [-entry for entry in matrix[pivot]]
            transform[pivot] = [-entry for entry in transform[pivot]]
        for r in range(pivot):
            if matrix[r][column]:
                quotient = matrix[r][column] // matrix[pivot][column]
                if quotient:
                    matrix[r] = [a - quotient * b
                                 for a, b in zip(matrix[r], matrix[pivot])]
                    transform[r] = [a - quotient * b
                                    for a, b in zip(transform[r], transform[pivot])]
        pivot += 1
    return matrix, transform


def odd_relation(rows: list[list[int]]):
    """Our O1 test: integers c_k with sum c_k d_k = 0 and sum c_k odd.

    Encode epsilon in an extra Z/2 coordinate: append 1 to every exponent row
    and adjoin the row (0, ..., 0, 2).  An odd relation exists iff the unit
    vector (0, ..., 0, 1) lies in the row lattice.
    """
    if not rows:
        return None
    width = len(rows[0])
    augmented = [list(row) + [1] for row in rows]
    augmented.append([0] * width + [2])
    matrix, transform = hnf_with_transform(augmented)
    for index, row in enumerate(matrix):
        if any(row[:width]) or row[width] != 1:
            continue
        coefficients = transform[index][:len(rows)]
        epsilon_coefficient = transform[index][len(rows)]
        assert sum(coefficients) + 2 * epsilon_coefficient == 1
        assert all(sum(coefficients[k] * rows[k][column]
                       for k in range(len(rows))) == 0
                   for column in range(width))
        return tuple(coefficients)
    return None


# --------------------------------------------------------------------------
# C. the invariant lattice and the gauge reconciliation
# --------------------------------------------------------------------------
def analyse_lattice():
    """Compare our L to their diagonal-gauge invariants on their support."""
    print("\nC. INVARIANT LATTICE AND GAUGE RECONCILIATION")
    cells = support_cells()
    nodes = [(vertex, colour) for vertex in range(ORDER)
             for colour in range(COLOURS)]
    node_index = {node: position for position, node in enumerate(nodes)}

    full_rows = []
    for cell in cells:
        row = [Fraction(0)] * len(nodes)
        for node, value in incidence_row(cell).items():
            row[node_index[node]] += value
        full_rows.append(row)
    rank_full = rational_rank([list(row) for row in full_rows])
    print(f"  support cells |S|                      : {len(cells)}")
    print(f"  rank of unsigned incidence on S        : {rank_full}")
    print(f"  rank L_S = ker(Z^S -> Z^(V x 3))       : {len(cells) - rank_full}")

    # the GHZ subtorus they use: prod_v b_{v,c} = 1 for every colour.
    # Its invariants are ker(Z^S -> Z^(V x 3) / <u_0, u_1, u_2>).
    ghz_rows = []
    for row in full_rows:
        reduced = list(row)
        for colour in range(COLOURS):
            mean = sum(row[node_index[(v, colour)]] for v in range(ORDER))
            for v in range(ORDER):
                reduced[node_index[(v, colour)]] -= Fraction(mean, ORDER)
        ghz_rows.append(reduced)
    rank_ghz = rational_rank(ghz_rows)
    print(f"  rank of GHZ-restricted incidence on S  : {rank_ghz}"
          "   (their 'incidence rank 18')")
    print(f"  rank L_GHZ (their invariants)          : {len(cells) - rank_ghz}")

    # the three extra L_GHZ directions are the pure matching indicators:
    # each has endpoint character u_c = sum_v e_{v,c}, zero in the GHZ quotient
    cell_index_local = {cell: position for position, cell in enumerate(cells)}
    pure_indicators = []
    for colour in range(COLOURS):
        word = (colour,) * ORDER
        matching = next(m for m in matchings_lowest_first(tuple(range(ORDER)))
                        if all(TABLE[e][0] == colour and TABLE[e][1] == colour
                               for e in m))
        row = [Fraction(0)] * len(cells)
        for edge in matching:
            row[cell_index_local[cell_of_edge(edge)]] += 1
        pure_indicators.append(row)
        del word, matching
    kernel_basis = _kernel_basis(full_rows, len(cells))
    combined = rational_rank([list(r) for r in kernel_basis + pure_indicators])
    print(f"  rank( L_S + <1_{{M_0}}, 1_{{M_1}}, 1_{{M_2}}> )         : {combined}")
    assert combined == len(cells) - rank_ghz, "pure indicators do not span the gap"
    print("  => L_S <= L_GHZ with rank gap 3 spanned exactly by the three pure")
    print("     matching indicators (character u_c, killed by the GHZ torus).")
    print("     Our torus is STRICTLY larger, so our invariance demand is")
    print("     strictly stronger; z passes it anyway.")

    exponent = circulation()
    z = [0] * len(cells)
    cell_index = {cell: position for position, cell in enumerate(cells)}
    for edge, value in exponent.items():
        z[cell_index[cell_of_edge(edge)]] += value
    image = [0] * len(nodes)
    for position, value in enumerate(z):
        if not value:
            continue
        for node, count in incidence_row(cells[position]).items():
            image[node_index[node]] += value * count
    assert not any(image), "z is NOT in our L_S"
    print("  z = sum_i (1_{B_i} - 1_{E_i}) lies in ker(unsigned incidence),")
    print("     i.e. in OUR L (not merely in the weaker GHZ-invariant lattice).")
    print("  => THEIR H IS OUR EXPONENT-LOCAL-SYSTEM HOLONOMY on their support.")

    # Zaslavsky picture: the cell graph of the support
    adjacency: dict[Node, list[Node]] = {node: [] for node in nodes}
    for cell in cells:
        u, v, i, j = cell
        adjacency[(u, i)].append((v, j))
        adjacency[(v, j)].append((u, i))
    seen: dict[Node, int] = {}
    components = 0
    bipartite_components = 0
    for node in nodes:
        if node in seen or not adjacency[node]:
            continue
        components += 1
        stack = [(node, 0)]
        seen[node] = 0
        member = []
        bipartite = True
        while stack:
            current, parity = stack.pop()
            member.append(current)
            for neighbour in adjacency[current]:
                if neighbour not in seen:
                    seen[neighbour] = 1 - parity
                    stack.append((neighbour, 1 - parity))
                elif seen[neighbour] == parity:
                    bipartite = False
        bipartite_components += int(bipartite)
    used_nodes = sum(1 for node in nodes if adjacency[node])
    print(f"  cell graph of S: {used_nodes} used nodes, {len(cells)} edges, "
          f"{components} components, {bipartite_components} bipartite")
    print(f"  frame-lattice rank |E| - |V_used| + #bipartite = "
          f"{len(cells) - used_nodes + bipartite_components}"
          f"  (matches rank L_S = {len(cells) - rank_full})")

    # shape of z itself
    z_edges = [cells[p] for p, value in enumerate(z) if value]
    degree: dict[Node, int] = {}
    for cell in z_edges:
        u, v, i, j = cell
        degree[(u, i)] = degree.get((u, i), 0) + 1
        degree[(v, j)] = degree.get((v, j), 0) + 1
    print(f"  support(z): {len(z_edges)} cells on {len(degree)} nodes, "
          f"degree multiset {sorted(degree.values())}, coefficients "
          f"{sorted({value for value in z if value})}")

    # every node has degree 2, so support(z) is a disjoint union of cycles
    z_adjacency: dict[Node, list[Node]] = {node: [] for node in degree}
    for cell in z_edges:
        u, v, i, j = cell
        z_adjacency[(u, i)].append((v, j))
        z_adjacency[(v, j)].append((u, i))
    visited: set[Node] = set()
    lengths = []
    for node in z_adjacency:
        if node in visited:
            continue
        length = 0
        current, previous = node, None
        while current not in visited:
            visited.add(current)
            length += 1
            nxt = next(n for n in z_adjacency[current] if n != previous)
            previous, current = current, nxt
        lengths.append(length)
    print(f"  z decomposes into cycles of lengths {sorted(lengths)} in the")
    print("     cell graph -- all EVEN, so z is an even-cycle (frame) element,")
    print("     NOT an odd handcuff.  In our corpus the odd handcuffs are the")
    print("     carriers of every 1 = -1 certificate, so this is the exact")
    print("     structural reason O1 has nothing to work with here.")
    assert all(length % 2 == 0 for length in lengths), "odd cycle in support(z)"
    return cells, cell_index, z


# --------------------------------------------------------------------------
# D. run the dichotomy
# --------------------------------------------------------------------------
def fibre_relations(fibres, words, cells, cell_index):
    """Binomial exponent rows d = 1_{M_a} - 1_{M_b} for two-term fibres."""
    rows = []
    provenance = []
    for word in words:
        terms = fibres.get(word, [])
        if len(terms) != 2:
            continue
        (m_a, _, _), (m_b, _, _) = sorted(terms, key=lambda item: not item[2])
        row = [0] * len(cells)
        for edge in m_a:
            row[cell_index[cell_of_edge(edge)]] += 1
        for edge in m_b:
            row[cell_index[cell_of_edge(edge)]] -= 1
        rows.append(row)
        provenance.append(word)
    return rows, provenance


def classify(name, fibres, mixed_words, pure_words, cells, cell_index):
    """Apply O1/O2 to one subsystem and report the label."""
    print(f"\n  --- subsystem: {name} ---")
    print(f"      mixed target-zero equations : {len(mixed_words)}")
    print(f"      pure nonzero equations      : {len(pure_words)}")

    sizes: dict[int, int] = {}
    singletons = []
    for word in mixed_words:
        size = len(fibres.get(word, []))
        sizes[size] = sizes.get(size, 0) + 1
        if size == 1:
            singletons.append(word)
    print(f"      mixed fibre size census     : "
          f"{ {k: sizes[k] for k in sorted(sizes)} }")

    for word in pure_words:
        assert fibres.get(word), f"pure fibre {word} is empty"

    o2 = bool(singletons)
    if o2:
        sample = "".join(map(str, singletons[0]))
        print(f"      O2 (singleton class)        : FIRES on {len(singletons)} "
              f"one-term mixed fibres, e.g. {sample}")
    else:
        print("      O2 (singleton class)        : does not fire "
              "(no one-term mixed fibre)")

    rows, provenance = fibre_relations(fibres, mixed_words, cells, cell_index)
    print(f"      binomial exponent rows      : {len(rows)} "
          f"({', '.join(''.join(map(str, w)) for w in provenance)})")
    rank = rational_rank([[Fraction(v) for v in row] for row in rows]) if rows else 0
    print(f"      rank of the exponent rows   : {rank}"
          f"  (relation lattice rank {len(rows) - rank})")
    relation = odd_relation(rows)
    if relation is None:
        o1 = False
        print("      O1 (odd holonomy 1 = -1)    : DOES NOT FIRE -- every "
              "integer dependency among the binomial rows has even coefficient "
              "sum")
    else:
        o1 = True
        support = {provenance[k]: relation[k]
                   for k in range(len(rows)) if relation[k]}
        print(f"      O1 (odd holonomy 1 = -1)    : FIRES with coefficients "
              f"{ {''.join(map(str, w)): c for w, c in support.items()} }")
    return {"O1": o1, "O2": o2, "singletons": len(singletons),
            "rows": len(rows), "relation_rank": len(rows) - rank}


def main():
    """Run the translation and the classification."""
    print("UNAUDITED EXTERNAL STRESS TEST -- U7D under OUR machinery")
    print("external repo pinned at commit "
          "f17afa1c8e72aeba51dafdf1e38afeb903591750")
    cells, cell_index, z = analyse_lattice()
    fibres = build_fibres()

    all_words = list(itertools.product(range(COLOURS), repeat=ORDER))
    pure = [(colour,) * ORDER for colour in range(COLOURS)]
    all_mixed = [word for word in all_words if word not in pure]

    print("\nD. OBSTRUCTION DICHOTOMY ON THEIR SUPPORT")

    their = classify(
        "THEIR claimed subsystem (3 pure nonzero + the 3 cycle fibres zero)",
        fibres, list(CYCLE_WORDS), pure, cells, cell_index)

    full = classify(
        "FULL Krenn-Gu target Delta_(8,3) on their label support",
        fibres, all_mixed, pure, cells, cell_index)

    print("\n  VERDICT")
    assert not their["O1"], "CRITICAL: O1 fired on a subsystem they satisfy"
    assert not their["O2"], "CRITICAL: O2 fired on a subsystem they satisfy"
    print("    * on THEIR subsystem our machinery issues NO certificate:")
    print("      not O1 (the odd 3-cycle relation sums to z != 0, so the")
    print("      character is a VALUE H = -1, not a collision 1 = -1),")
    print("      not O2 (both cycle fibres have two terms in distinct")
    print("      classes).  Label: LIVE / satisfiable -- consistent with")
    print("      their exact rational point and its moment-balanced")
    print("      representative over C.  NO BUG.")
    assert full["O2"], "expected the full target to be killed by O2"
    print("    * on the FULL target their label support is DEAD by O2:")
    print(f"      {full['singletons']} one-term mixed fibres (the")
    print("      unique-perfect-matching case), e.g. eta = "
          f"{''.join(map(str, EXPOSED_WORD))}.  This is the same fact as")
    print("      their own U7D exclusion theorem's Laurent unit ideal.")
    print(f"    * O1 on the full system: {'fires' if full['O1'] else 'does not fire'}"
          " -- recorded for the ledger; it is not")
    print("      in conflict with their complex point, which satisfies only")
    print("      the three cycle equations, not the singleton ones.")
    print("    * O3 (integral atom): not searched; O2 already decides.")


if __name__ == "__main__":
    main()
