#!/usr/bin/env python3
"""Build the zero-run held plan and refusal ledger."""
import ast,copy,hashlib,json,os
from pathlib import Path
H=Path(__file__).resolve().parent;R=H.parents[1];C=R/'computations';P=C/'unaudited-codex-n8-x5-rep5-smallest65-third-factor-reduction-design-2026-08-26';S=P/'sources/V_a24_10_Q_design.sing';O=C/'unaudited-codex-n8-x5-rep5-strict-zero-recursive-factor-tree-capped-2026-08-26'
PINS={P/'MANIFEST.sha256':'f3388b5a475d6f8689818e46979b1e620c28bad04ce3daa48a1b8881ea95f060',S:'cb669d5e09f59d3a32f5b86d2daedc84ad9fa997851eccc83269dc7604db813a',O/'MANIFEST.sha256':'3b7ea71a498114de022c534ca5a195847216b7efc3a1a45d177afb929cf6d847',O/'results_capped_outcome.json':'620c84e770b0ba7d475e1e14d7b184493890feb0fb6ef2e035c8154ff3265442',O/'results_referee.json':'fbc9f2033b9df18c669702e51400dbd3997f0add05b56214fce8dd9761a777c2'}
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
for p,h in PINS.items():assert sha(p)==h
for script in ('factor_tree_driver.py','run_held.py','prove_invariants.py','build_held.py','validate_held.py','seal_manifest.py'):ast.parse((H/script).read_text())
assert not any((H/x).exists() for x in ('CLEARANCE.json','result.json','watchdog.json','stdout.log','stderr.log','checkpoint/CURRENT.json'))
def atomic(p,v):t=p.with_suffix(p.suffix+'.tmp');t.write_text(json.dumps(v,indent=2,sort_keys=True)+'\n');os.replace(t,p)
plan={'schema':'KRENN_X5_REP5_FACTOR_TREE_RESUMABLE_HELD_PLAN_V1','status':'APPROVED_HELD_ZERO_RUN','pins':{str(p.relative_to(R)):h for p,h in PINS.items()},'artifacts':{'driver':{'path':'factor_tree_driver.py','sha256':sha(H/'factor_tree_driver.py')},'watchdog':{'path':'run_held.py','sha256':sha(H/'run_held.py')},'invariant_proof':{'path':'results_invariants.json','sha256':sha(H/'results_invariants.json')}},'roots':{'count':18,'derivation':'recomputed from pinned cb669d5e source under frozen 22-step strict policy','previous_smallest':[48,147,600],'previous_smallest_complete_factors':10},'canonical_state':{'logical_fields':['zero_bitmask','unit_bitmask'],'invariant':'zero & unit == 0; each variable is unassigned, zero, or localized-nonzero','polynomial_derivation':'specialize every zero coordinate; divide maximal common powers of every localized coordinate; primitive-sign normalize; deduplicate and sort generators','key':'SHA256(schema,source SHA,zero mask,unit mask,canonical generator SHA)','sequence_independent':True,'dedup_sound':'equal key means identical localized/specialized syntactic ideal and identical future admissible assignments'},'finite_state_proof':{'variables':64,'assignment_bound':'3^64','depth_bound':64,'cycle_impossible':'each edge assigns exactly one previously unassigned variable'},'branching':{'candidate':'unassigned coordinate dividing every monomial of at least one canonical generator','frozen_order':['descending divisible-generator count','ascending V-child term count','ascending V-child generator count','ascending coordinate name'],'children':['D: mark localized nonzero','V: mark zero'],'coverage':'D(x) union V(x)'},'checkpoint':{'format':'immutable gzip JSON shards plus full frontier generation','commit_order':['atomic shard','atomic frontier','atomic CURRENT pointer'],'resume':'verify config, every shard/frontier size+SHA, state keys and generator digests before expansion','checkpoint_every_nodes':250,'orphan_rule':'files not named by CURRENT are ignored','result_absent_on_partial_or_resource_abort':True},'resources':{'max_new_nodes_per_lane':25000,'global_node_cap':2000000,'native_wall_seconds':480,'wrapper_wall_seconds':510,'rss_gib':8,'poll_seconds':0.25,'process_group':True,'direct_libproc':True,'term_then_kill':True},'acceptance':{'pass_status':'PASS_EXACT_ALL_18_ROOTS_STRUCTURAL_UNIT','requirements':['frontier empty','every state key replay-valid','zero factor-exhausted nonunit leaves','reverse DAG truth true for all 18 roots','atomic result','watchdog PASS/no breach'],'reject_status':'REJECT_FACTOR_EXHAUSTED_NONUNIT_LEAF','partial_status':'PARTIAL_FRONTIER_SEALED','no_closure_from_partial':True},'clearance':{'manager_nonce_required':True,'expiry_required':True,'resource_clear_required':True,'exclusive_marker_required':True,'template':'CLEARANCE_TEMPLATE.json','currently_authorized':False},'scope':{'rep5_nodes_expanded':0,'singular_runs':0,'launches':0,'closure_claim':False,'nine_stratum_ledger_preserved':True}}
atomic(H/'HELD_PLAN.json',plan)
template={'schema':'KRENN_X5_REP5_FACTOR_TREE_CLEARANCE_V1','approved':False,'nonce':'REPLACE_ME','expected_nonce':'REPLACE_ME','expires_utc':'REPLACE_ME','plan_sha256':'REPLACE_AFTER_SEAL','driver_sha256':plan['artifacts']['driver']['sha256'],'source_sha256':PINS[S],'rss_gib':8,'native_wall_seconds':480,'wrapper_wall_seconds':510,'max_new_nodes':25000,'global_node_cap':2000000,'resource_clear_manifest':'REPLACE_ME'};atomic(H/'CLEARANCE_TEMPLATE.json',template)
def validate(v):
 assert v['status']=='APPROVED_HELD_ZERO_RUN' and v['roots']['count']==18 and v['canonical_state']['sequence_independent'] and v['finite_state_proof']['assignment_bound']=='3^64' and v['finite_state_proof']['depth_bound']==64
 assert v['checkpoint']['checkpoint_every_nodes']==250 and v['checkpoint']['result_absent_on_partial_or_resource_abort'] and v['resources']=={'max_new_nodes_per_lane':25000,'global_node_cap':2000000,'native_wall_seconds':480,'wrapper_wall_seconds':510,'rss_gib':8,'poll_seconds':0.25,'process_group':True,'direct_libproc':True,'term_then_kill':True}
 assert not v['acceptance']['no_closure_from_partial'] is False and not v['clearance']['currently_authorized'] and v['scope']=={'rep5_nodes_expanded':0,'singular_runs':0,'launches':0,'closure_claim':False,'nine_stratum_ledger_preserved':True}
mut=[lambda v:v.__setitem__('status','PASS'),lambda v:v['roots'].__setitem__('count',17),lambda v:v['canonical_state'].__setitem__('sequence_independent',False),lambda v:v['finite_state_proof'].__setitem__('assignment_bound','2^64'),lambda v:v['finite_state_proof'].__setitem__('depth_bound',65),lambda v:v['checkpoint'].__setitem__('checkpoint_every_nodes',0),lambda v:v['checkpoint'].__setitem__('result_absent_on_partial_or_resource_abort',False),lambda v:v['resources'].__setitem__('max_new_nodes_per_lane',25001),lambda v:v['resources'].__setitem__('global_node_cap',2000001),lambda v:v['resources'].__setitem__('rss_gib',9),lambda v:v['resources'].__setitem__('wrapper_wall_seconds',500),lambda v:v['resources'].__setitem__('direct_libproc',False),lambda v:v['acceptance'].__setitem__('no_closure_from_partial',False),lambda v:v['clearance'].__setitem__('currently_authorized',True),lambda v:v['scope'].__setitem__('rep5_nodes_expanded',1),lambda v:v['scope'].__setitem__('launches',1),lambda v:v['scope'].__setitem__('closure_claim',True),lambda v:v['scope'].__setitem__('nine_stratum_ledger_preserved',False)]
tests={}
for i,f in enumerate(mut,1):
 x=copy.deepcopy(plan);f(x)
 try:validate(x)
 except (AssertionError,KeyError,TypeError):tests[f'hostile_{i:02d}']=True
 else:tests[f'hostile_{i:02d}']=False
assert len(tests)==18 and all(tests.values());atomic(H/'results_hostiles.json',{'schema':'KRENN_X5_REP5_FACTOR_TREE_HELD_HOSTILES_V1','status':'PASS_18_HELD_HOSTILES','tests':tests,'rep5_nodes_expanded':0,'launches':0});print(json.dumps({'status':plan['status'],'roots':18,'assignment_bound':'3^64','node_caps':[25000,2000000],'checkpoint_every':250,'hostiles':18,'rep5_nodes':0,'launches':0},sort_keys=True))
