#!/usr/bin/env python3
"""Stream the finite source-faithful first P5 Rees-chart generators.

No ambient normal graph is substituted.  The 196 smooth normal directions
remain independent variables, while the eleven P5-transverse tangent
directions receive one extra radial weight.  The later L/F1/F2/G centers are
therefore to be recovered by tau saturation rather than hard-coded offsets.
"""

from collections import Counter
from fractions import Fraction
from hashlib import sha256
import argparse
import importlib.util
import json
from pathlib import Path


HERE = Path(__file__).resolve().parent


def load_module(name, filename):
    spec = importlib.util.spec_from_file_location(name, HERE / filename)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


AMBIENT = load_module(
    "n8_ambient_standard_basis_for_p5_finite_rees",
    "analyze_n8_ambient_local_standard_basis.py",
)
P5 = load_module(
    "n8_p5_degree6_for_finite_rees",
    "verify_n8_p5_degree6_compatibility_kills_h0.py",
)
TAILS = load_module(
    "n8_p5_degree7_for_finite_rees",
    "verify_n8_p5_streamed_degree7_mixed_tails.py",
)
CUBIC = AMBIENT.CUBIC
QQ = Fraction

EXPECTED_COMPLETE_LEDGER_SHA256 = (
    "3952965184121360b4f0137715233f51b4a9377b87f0766499c087619efdcf84"
)
EXPECTED_SINGULAR_EXPORT_SHA256 = (
    "40eef6843e77706aba2b6b15655743f90adbbbc7350df31bed5ff685912a83db"
)


def require(condition, detail):
    if not condition:
        raise RuntimeError(detail)


def add(target, source, scale=QQ(1)):
    CUBIC.add_scaled(target, source, scale)


def multiply(left, right):
    return CUBIC.multiply_polynomials(left, right)


def polynomial_digest(source):
    encoded = [
        [list(monomial), coefficient.numerator, coefficient.denominator]
        for monomial, coefficient in sorted(source.items())
    ]
    return sha256(json.dumps(encoded, separators=(",", ":")).encode()).hexdigest()


def polynomial_family_digest(sources):
    digest = sha256()
    for source in sources:
        digest.update(polynomial_digest(source).encode())
    return digest.hexdigest()


def derivative(source, variable):
    answer = {}
    for monomial, coefficient in source.items():
        multiplicity = monomial.count(variable)
        if not multiplicity:
            continue
        output = list(monomial)
        output.remove(variable)
        output = tuple(output)
        answer[output] = coefficient * multiplicity
    return answer


def singular_polynomial(source, names):
    terms = []
    for monomial, coefficient in sorted(source.items()):
        coefficient = QQ(coefficient)
        scalar = (
            str(coefficient.numerator)
            if coefficient.denominator == 1
            else f"({coefficient.numerator}/{coefficient.denominator})"
        )
        product = "*".join(names[variable] for variable in monomial)
        terms.append(scalar if not product else f"{scalar}*{product}")
    return "+".join(terms).replace("+-", "-") or "0"


def variable_names(layout):
    names = [None] * layout["variable_count"]
    names[layout["tau"]] = "tau"
    for parameter, variable in layout["a"].items():
        names[variable] = f"z{parameter}"
    for parameter, variable in layout["n"].items():
        names[variable] = f"n{parameter}"
    for pivot, variable in layout["y"].items():
        names[variable] = f"y{pivot}"
    require(all(name is not None for name in names), "unnamed Rees variable")
    require(len(set(names)) == len(names), "duplicate Rees variable name")
    return names


class SingularExporter:
    """Stream the exact finite ideal without retaining encoded strings."""

    IDEAL_NAMES = {
        "normal": "N",
        "obstruction": "Q",
        "tangent_cubic": "C",
    }

    def __init__(self, path, names):
        self.output = Path(path).open("w")
        self.digest = sha256()
        self.names = names
        self.active = None
        self.count = 0
        self.write(
            "// Generated by analyze_n8_p5_finite_rees_chart.py\n"
            f"ring R=0,({','.join(names)}),dp;\n"
        )

    def write(self, value):
        self.output.write(value)
        self.digest.update(value.encode())

    def begin(self, label):
        require(self.active is None, "nested Singular ideal export")
        self.active = label
        self.count = 0
        self.write(f"ideal {self.IDEAL_NAMES[label]}=\n")

    def append(self, source):
        require(self.active is not None, "Singular export has no active ideal")
        if self.count:
            self.write(",\n")
        self.write(singular_polynomial(source, self.names))
        self.count += 1

    def end(self):
        require(self.active is not None and self.count,
                "empty Singular ideal export")
        self.write(";\n")
        self.active = None

    def target(self, name, source):
        require(self.active is None, "target emitted inside Singular ideal")
        self.write(
            f"poly {name}={singular_polynomial(source, self.names)};\n"
        )

    def close(self):
        require(self.active is None, "unfinished Singular ideal export")
        self.write(
            "ideal I=N,Q,C;\n"
            "// Next: tau-saturate I, localize the generic-L chart, and\n"
            "// reduce H0 and H1.  Do not infer membership from this export.\n"
        )
        self.output.close()
        return self.digest.hexdigest()


def variable_layout(reducer):
    tau = 0
    free = tuple(
        parameter for parameter in range(56)
        if parameter not in P5.P5_NORMAL_SET
    )
    require(len(free) == 45, "P5 free parameter count changed")
    a = {parameter: 1 + index for index, parameter in enumerate(free)}
    n_start = 1 + len(free)
    n = {
        parameter: n_start + index
        for index, parameter in enumerate(P5.P5_NORMAL_VARIABLES)
    }
    directions = TAILS.normal_directions(reducer)
    pivots = tuple(sorted(directions))
    require(len(pivots) == 196, "ambient normal direction count changed")
    y_start = n_start + len(n)
    y = {pivot: y_start + index for index, pivot in enumerate(pivots)}
    return {
        "tau": tau,
        "a": a,
        "n": n,
        "y": y,
        "directions": directions,
        "variable_count": y_start + len(y),
    }


def coordinate_forms(reducer, layout):
    tau = layout["tau"]
    inverse_normals = {}
    for pivot, direction in layout["directions"].items():
        for coordinate, coefficient in direction.items():
            inverse_normals.setdefault(coordinate, []).append(
                (pivot, coefficient)
            )

    answer = []
    for coordinate, tangent in enumerate(reducer._tangent_coordinate_forms):
        form = {}
        for parameter, coefficient in tangent.items():
            if parameter in P5.P5_NORMAL_SET:
                if parameter == 15:
                    # P5 has z15=z16 at its exceptional divisor.
                    add(form, {
                        tuple(sorted((tau, layout["a"][16]))): coefficient
                    })
                add(form, {
                    tuple(sorted((tau, tau, layout["n"][parameter]))):
                    coefficient
                })
            else:
                add(form, {
                    tuple(sorted((tau, layout["a"][parameter]))): coefficient
                })
        for pivot, coefficient in inverse_normals.get(coordinate, ()):
            add(form, {
                tuple(sorted((tau, tau, layout["y"][pivot]))): coefficient
            })
        answer.append(form)
    require(len(answer) == 252, "ambient coordinate-form count changed")
    return answer


def substitute(source, forms):
    answer = {}
    maximum_intermediate = 0
    for ambient_monomial, coefficient in source.items():
        term = {(): QQ(coefficient)}
        for coordinate in ambient_monomial:
            term = multiply(term, forms[coordinate])
            maximum_intermediate = max(maximum_intermediate, len(term))
        add(answer, term)
    return answer, maximum_intermediate


def tau_valuation(source, tau):
    require(source, "zero substituted Rees generator")
    return min(monomial.count(tau) for monomial in source)


def divide_tau(source, tau, valuation):
    answer = {}
    for monomial, coefficient in source.items():
        output = list(monomial)
        for _index in range(valuation):
            output.remove(tau)
        answer[tuple(output)] = coefficient
    return answer


def polynomial_degree(source):
    return max(map(len, source), default=-1)


def tau_degree(source, tau):
    return max((monomial.count(tau) for monomial in source), default=-1)


def pure_residual(reducer, colour):
    pure_word = (
        AMBIENT.LOCAL.SECOND.PURE_WORD_0
        if colour == 0 else AMBIENT.LOCAL.SECOND.PURE_WORD_1
    )
    selected_word = (
        AMBIENT.LOCAL.SECOND.MIXED_WORD_0
        if colour == 0 else AMBIENT.LOCAL.SECOND.MIXED_WORD_1
    )
    answer = {}
    for degree in range(5):
        add(answer, CUBIC.hasse_form(pure_word, degree))
    selected = AMBIENT.full_polynomial(
        reducer,
        {AMBIENT.LOCAL.THIRD.MIXED_WORD_INDEX[selected_word]: QQ(1)},
    )
    add(answer, selected, QQ(-1))
    return answer


def substitute_tau_zero_normals(source, tau, normal_offsets):
    """Set tau=0 and solve y_p=-q_p(a) in the identity normal block."""

    answer = {}
    for monomial, coefficient in source.items():
        if tau in monomial:
            continue
        term = {(): coefficient}
        for variable in monomial:
            if variable in normal_offsets:
                term = multiply(term, normal_offsets[variable])
                term = {
                    output: -value for output, value in term.items()
                }
            else:
                term = multiply(term, {(variable,): QQ(1)})
        add(answer, term)
    return answer


def generator_data(limit=None, verbose=True, singular_path=None):
    require(not (limit is not None and singular_path is not None),
            "a Singular export requires the complete generator set")
    reducer = AMBIENT.LOCAL.LocalReducer()
    normal, obstruction, cubic = AMBIENT.finite_generators()
    groups = (
        ("normal", normal, 2),
        ("obstruction", obstruction, 3),
        ("tangent_cubic", cubic, 4),
    )
    layout = variable_layout(reducer)
    forms = coordinate_forms(reducer, layout)
    exporter = (
        SingularExporter(singular_path, variable_names(layout))
        if singular_path is not None else None
    )
    form_terms = [len(source) for source in forms]
    normal_pivots = tuple(reducer.jacobian_pivots)
    require(
        set(normal_pivots) == set(layout["directions"]),
        "normal-generator pivots no longer match the dual directions",
    )
    y_variables = frozenset(layout["y"].values())
    n_variables = frozenset(layout["n"].values())
    records = []
    targets = []
    totals = Counter()
    degree_distributions = Counter()
    normal_identity_rows = 0
    normal_offsets = {}
    obstruction_initials = []
    processed = 0
    for label, sources, expected_valuation in groups:
        if exporter is not None:
            exporter.begin(label)
        for number, source in enumerate(sources, 1):
            if limit is not None and processed >= limit:
                break
            transformed, maximum_intermediate = substitute(source, forms)
            valuation = tau_valuation(transformed, layout["tau"])
            require(valuation >= expected_valuation,
                    f"{label} {number} lost expected tau divisibility")
            strict = divide_tau(transformed, layout["tau"], valuation)
            if exporter is not None:
                exporter.append(strict)
            source_degree = polynomial_degree(source)
            transformed_tau_degree = tau_degree(transformed, layout["tau"])
            strict_tau_degree = tau_degree(strict, layout["tau"])
            degree_bound = 2 * source_degree - valuation
            require(
                strict_tau_degree <= degree_bound,
                f"{label} {number} violated the finite tau-degree bound",
            )
            if label == "normal":
                # Modulo tau the divided normal row has the form
                # y_p + q_p(a).  The exact y-block is therefore I_196.
                pivot = normal_pivots[number - 1]
                expected = {(layout["y"][pivot],): QQ(1)}
                tau_zero_y = {
                    monomial: coefficient
                    for monomial, coefficient in strict.items()
                    if layout["tau"] not in monomial
                    and any(variable in y_variables for variable in monomial)
                }
                require(
                    tau_zero_y == expected,
                    f"normal {number} lost its tau-zero identity y-pivot",
                )
                require(
                    not any(
                        layout["tau"] not in monomial
                        and any(variable in n_variables for variable in monomial)
                        for monomial in strict
                    ),
                    f"normal {number} acquired a tau-zero transverse term",
                )
                tau_zero = {
                    monomial: coefficient
                    for monomial, coefficient in strict.items()
                    if layout["tau"] not in monomial
                }
                add(tau_zero, expected, QQ(-1))
                require(
                    all(
                        all(variable in layout["a"].values()
                            for variable in monomial)
                        for monomial in tau_zero
                    ),
                    f"normal {number} tau-zero offset is not a base polynomial",
                )
                normal_offsets[layout["y"][pivot]] = tau_zero
                normal_identity_rows += 1
            elif label == "obstruction":
                require(len(normal_offsets) == 196,
                        "obstruction reached before the normal graph")
                initial = substitute_tau_zero_normals(
                    strict, layout["tau"], normal_offsets
                )
                require(
                    all(
                        sum(variable in n_variables for variable in monomial)
                        <= 1
                        for monomial in initial
                    ),
                    f"obstruction {number} is nonlinear in the transverse block",
                )
                obstruction_initials.append(initial)
            record = {
                "group": label,
                "number": number,
                "source_terms": len(source),
                "source_degree": source_degree,
                "tau_valuation": valuation,
                "transformed_tau_degree": transformed_tau_degree,
                "strict_tau_degree": strict_tau_degree,
                "strict_tau_degree_bound": degree_bound,
                "strict_terms": len(strict),
                "strict_sha256": polynomial_digest(strict),
                "maximum_term_product": maximum_intermediate,
            }
            records.append(record)
            totals[f"{label}_generators"] += 1
            totals[f"{label}_source_terms"] += len(source)
            totals[f"{label}_strict_terms"] += len(strict)
            totals["maximum_strict_terms"] = max(
                totals["maximum_strict_terms"], len(strict)
            )
            totals["maximum_term_product"] = max(
                totals["maximum_term_product"], maximum_intermediate
            )
            totals[f"{label}_maximum_source_degree"] = max(
                totals[f"{label}_maximum_source_degree"], source_degree
            )
            totals[f"{label}_maximum_strict_tau_degree"] = max(
                totals[f"{label}_maximum_strict_tau_degree"],
                strict_tau_degree,
            )
            degree_distributions[
                f"{label}:source_degree:{source_degree}"
            ] += 1
            degree_distributions[
                f"{label}:valuation:{valuation}"
            ] += 1
            degree_distributions[
                f"{label}:strict_tau_degree:{strict_tau_degree}"
            ] += 1
            processed += 1
            if verbose:
                print(label, number, len(source), valuation, len(strict),
                      record["strict_sha256"], flush=True)
        if limit is not None and processed >= limit:
            break
        if exporter is not None:
            exporter.end()

    if limit is None:
        require(len(normal_offsets) == 196, "normal offset graph is incomplete")
        require(len(obstruction_initials) == 39,
                "obstruction initial family is incomplete")
        b = {
            (layout["a"][44],): QQ(1),
            (layout["a"][45],): QQ(1),
        }
        for column, row in enumerate(P5.B_PIVOT_ROWS):
            for other, parameter in enumerate(P5.P5_NORMAL_VARIABLES):
                expected = b if column == other else {}
                require(
                    derivative(
                        obstruction_initials[row], layout["n"][parameter]
                    ) == expected,
                    f"first-Rees bI pivot changed at row {row + 1}, "
                    f"column n{parameter}",
                )
        for colour in (0, 1):
            source = pure_residual(reducer, colour)
            transformed, maximum_intermediate = substitute(source, forms)
            valuation = tau_valuation(transformed, layout["tau"])
            require(valuation >= 2, f"H{colour} residual lost tau^2")
            strict = divide_tau(transformed, layout["tau"], valuation)
            initial_remainder = substitute_tau_zero_normals(
                strict, layout["tau"], normal_offsets
            )
            require(
                not initial_remainder,
                f"H{colour} initial remainder survived normal elimination",
            )
            source_degree = polynomial_degree(source)
            strict_tau_degree = tau_degree(strict, layout["tau"])
            degree_bound = 2 * source_degree - valuation
            require(strict_tau_degree <= degree_bound,
                    f"H{colour} violated the finite tau-degree bound")
            targets.append({
                "name": f"H{colour}-selected_mixed_{colour}",
                "source_terms": len(source),
                "source_degree": source_degree,
                "tau_valuation": valuation,
                "transformed_tau_degree": tau_degree(
                    transformed, layout["tau"]
                ),
                "strict_tau_degree": strict_tau_degree,
                "strict_tau_degree_bound": degree_bound,
                "strict_terms": len(strict),
                "strict_sha256": polynomial_digest(strict),
                "maximum_term_product": maximum_intermediate,
                "tau_zero_normal_remainder_terms": 0,
            })
            if exporter is not None:
                exporter.target(f"H{colour}", strict)
        if exporter is not None:
            export_digest = exporter.close()
            require(
                export_digest == EXPECTED_SINGULAR_EXPORT_SHA256,
                "complete Singular export changed",
            )
    return {
        "layout": {
            "variables": layout["variable_count"],
            "tau": 1,
            "P5_base": len(layout["a"]),
            "P5_transverse": len(layout["n"]),
            "ambient_normal": len(layout["y"]),
        },
        "coordinate_forms": {
            "total_terms": sum(form_terms),
            "maximum_terms": max(form_terms),
            "nonzero_forms": sum(bool(value) for value in form_terms),
        },
        "normal_schur_block": {
            "checked_rows": normal_identity_rows,
            "expected_rows": 196 if limit is None else min(limit, 196),
            "tau_zero_y_jacobian": "I_196" if limit is None else "checked prefix",
            "consequence": (
                "the divided normal rows are y_p+q_p(a)+tau*R_p; "
                "the 196 normals are a tau-adic regular sequence and may be "
                "eliminated by formal Schur/Hensel substitution"
            ),
        },
        "first_p5_transverse_block": {
            "checked_rows": len(obstruction_initials),
            "initial_terms": sum(map(len, obstruction_initials)),
            "maximum_initial_terms": max(
                map(len, obstruction_initials), default=0
            ),
            "initial_sha256": polynomial_family_digest(
                obstruction_initials
            ),
            "transverse_degree_at_most_one": True,
            "pivot_jacobian": (
                "(z44+z45)*I_11" if limit is None else "not checked"
            ),
        },
        "records": records,
        "pure_targets": targets,
        "degree_distributions": dict(sorted(degree_distributions.items())),
        "totals": dict(totals),
        "complete": limit is None,
        "scope_guard": (
            "finite first P5 Rees-chart source generators; tau saturation "
            "and generic-L component localization not yet computed"
        ),
    }


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--limit", type=int)
    parser.add_argument("--quiet", action="store_true")
    parser.add_argument(
        "--summary",
        action="store_true",
        help="print the exact digest and compact ledger without record bodies",
    )
    parser.add_argument(
        "--singular",
        type=Path,
        help="stream the complete 244-generator ideal and H0/H1 targets",
    )
    arguments = parser.parse_args()
    ledger = generator_data(
        arguments.limit, not arguments.quiet, arguments.singular
    )
    encoded = json.dumps(ledger, sort_keys=True, separators=(",", ":"))
    digest = sha256(encoded.encode()).hexdigest()
    printable = dict(ledger)
    if arguments.summary:
        printable["record_count"] = len(printable.pop("records"))
    print(json.dumps(printable, indent=2, sort_keys=True))
    print(f"ledger_sha256={digest}")
    if arguments.limit is None and EXPECTED_COMPLETE_LEDGER_SHA256 is not None:
        require(
            digest == EXPECTED_COMPLETE_LEDGER_SHA256,
            "complete finite-Rees ledger changed",
        )


if __name__ == "__main__":
    main()
