#!/usr/bin/env python3
"""Discovery analyzer: does face-matching constrain the attaching map's
sector coefficients?

Per notes/wip-attaching-map-summand-separation-plan.md.  This is an
ANALYZER (exploratory), not a checker: it computes the
solution space of sector-valued attaching-map candidates for the
denominator column d_{v,m_v} under the constraints extractable from the
audited artifacts, and reports whether the chart decoration (alpha,
beta) is coupled or free.

Setup, per face v: the candidate image psi(d_{v,m_v}) lives in the
marked two-sector space, with unknown rational coefficients over the
two sector copies of the three h_v monomials (support restriction to
the h_v fine degree per the compatible-block census).  The audited
constraints from the four-cube note's (11) and its Reynolds uniformity:

  (C1)  for each sector, the three top faces agree: the coefficient of
        the monomial N is the same for all three N in PM(F_v)
        (partial_N psi(d) must be a SINGLE symbol, independent of N);
  (C2)  no-leakage (3): psi(d_{s,a}) = 0 in this fine degree for
        (s,a) != (v, m_v) -- imposed by construction here.

The question: after (C1)-(C2), is the pairing Lambda_v(psi(d)) pinned,
or free?  Lambda_v is +1/6 on pq-copies, -1/6 on pr-copies of the h_v
monomials (the Schur no-go normalization).
"""

from fractions import Fraction
import importlib.util
from pathlib import Path


HERE = Path(__file__).resolve().parent
QQ = Fraction


def require(condition, detail):
    """Keep analyzer sanity checks active under ``python -O``."""
    if not condition:
        raise RuntimeError(detail)


def load(name, filename):
    spec = importlib.util.spec_from_file_location(name, HERE / filename)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


BASE = load(
    "attach_base",
    "verify_h3_direct_free_literal_four_face_full_nine_no_go.py",
)


def main():
    for deleted in BASE.ODD:
        colours = BASE.face_word(deleted)
        h_v = sorted(BASE.face_hafnian(deleted, colours))
        require(len(h_v) == 3, f"face {deleted} has {len(h_v)} monomials")

        # Unknowns: x[(sector, M)] for sector in {pq, pr}, M in h_v.
        # (C1) per sector: x[s, M1] = x[s, M2] = x[s, M3].
        # Solution space: x[pq, *] = alpha, x[pr, *] = beta -- dimension 2.
        # This is immediate linear algebra; the content worth printing is
        # the pairing functional restricted to the solution space.
        #   Lambda_v = (1/6) sum_M [ (pq, M) - (pr, M) ]
        #   on the solution space: Lambda_v = 3*(alpha)/6 - 3*(beta)/6
        #                                   = (alpha - beta)/2.
        # Free parameters: 2.  Pairing image: all of Q.  In particular
        # -1 is realized on the line alpha - beta = -2 and 0 on the
        # diagonal alpha = beta.  No audited constraint couples alpha
        # and beta.
        dimension_before = 6
        constraints_per_sector = 2
        free = dimension_before - 2 * constraints_per_sector
        print(f"face v={deleted}: colours {''.join(map(str, colours))}, "
              f"|h_v|={len(h_v)}, unknowns {dimension_before}, "
              f"C1 constraints {2 * constraints_per_sector}, "
              f"free parameters {free} (alpha, beta)")
        print("   pairing on solution space: (alpha - beta)/2  -> "
              "image = Q (unconstrained)")

    print()
    print("=== cone-restricted Hom computation ===")
    print()
    print("Within the audited four-summand cone (19) of the fourth-Hasse")
    print("audit, the chart block R_v^{pq/pr} is generated by K_v alone")
    print("with dK_v = 0 (its (17)).  Consequences, structural:")
    print()
    print(" 1. A chain component psi: D_v -> R has psi_1(d) in R*K_v and")
    print("    psi_0 = 0 (the chart block has no output degree), so the")
    print("    Hom-differential condition d_R psi_1 = psi_0 delta reads")
    print("    0 = 0: VACUOUS.  Denominator->chart attachments inside")
    print("    the cone are unconstrained R-linear maps into R*K_v.")
    print(" 2. Every element of R*K_v has marked leading symbol")
    print("    f*S_v = f*[(h_v)_pq - (h_v)_pr]: CHART-ODD, always.")
    print("    The chart-neutral combination (h_v)_pq + (h_v)_pr is the")
    print("    symbol of r^pq + r^pr, which is NOT in the cone -- the")
    print("    strict relative block contains only differences.")
    print(" 3. The mass criterion (-3 on the own face) pins the scalar:")
    print("    the repair-capable attachment is psi(d_{v,m_v}) = -K_v")
    print("    at leading order, realizing pairing -1.")
    print()
    print("So: restricted to the audited cone, the fork resolves")
    print("CHART-ODD -- the escape-open branch -- and chart-neutrality")
    print("would require enlarging the cone with symmetric chart")
    print("material that no audited artifact contains.  What the cone")
    print("does NOT supply is the cell's cap/ordinary-residue typing:")
    print("per the frontier, the attaching map's ordinary residue must")
    print("be PROVED zero, and the Reynolds-attach coupled obstruction")
    print("shows that cannot be done sequentially in the old cap span.")
    print("The fork's open question is hereby relocated: not 'which")
    print("decoration?' but 'prove ores = 0 for the -K_v attachment'.")
    print()
    print("reconciled conclusion: in the ABSTRACT two-sector space the")
    print("face-matching constraints leave (alpha, beta) free -- all")
    print("decorations are face-compatible.  RESTRICTED to the audited")
    print("cone (19), the codomain structure (only K_v available) forces")
    print("chart-odd, and the mass criterion pins the scalar to -1.")
    print("Chart-neutrality is not wrong, merely homeless: it needs")
    print("symmetric chart material outside every audited artifact.")
    print("Either way the decision now rests on the cell's ordinary-")
    print("residue proof, not on the decoration.")


if __name__ == "__main__":
    main()
