#!/usr/bin/env python3
"""Parameter-independent quotient for every A_23 plane-locus perturbation.

Only the deleted-pair cofactors 01, 05, 15, and 45 can contain A_23.  We
quotient the six-word output by every coordinate reachable from the variable
part of those cofactors, and also by the fixed normal direction u_+.  On the
remaining coordinates the two-star bilinear map is independent of A_23.

If its complete target/off-diagonal system is inconsistent, that is a single
uniform obstruction for all five-cell supports.  This file constructs the
quotient and optionally performs a direct characteristic-zero unit-ideal
test; it is a discovery driver pending an independent reconstruction.
"""

from __future__ import annotations

import argparse
import collections
import itertools
import shutil
import subprocess
import time

import explore_three_cut_internal_23_perturbation as equations
import explore_three_cut_internal_23_plane_supports as supports
import test_three_cut_internal_23_plane_support_component as worker


Q = equations.Q
SIX = equations.SIX
COLOURS = equations.COLOURS
VARIABLE_PAIRS = ((0, 1), (0, 5), (1, 5), (4, 5))


def subtract(left, right):
    answer = dict(left)
    for word, coefficient in right.items():
        equations.cylinders.add(answer, word, -coefficient)
    return answer


def variable_coordinate_span(mask=31):
    zero = supports.blocks_for_mask(0)
    full = supports.blocks_for_mask(mask)
    coordinates = set()
    details = {}
    for i, j in VARIABLE_PAIRS:
        rest = tuple(site for site in SIX if site not in (i, j))
        variable = subtract(
            equations.cylinders.matching_tensor(rest, full),
            equations.cylinders.matching_tensor(rest, zero),
        )
        details[i, j] = variable
        for rest_word in variable:
            for ci, cj in itertools.product(COLOURS, repeat=2):
                assignment = dict(zip(rest, rest_word))
                assignment[i] = ci
                assignment[j] = cj
                coordinates.add(tuple(assignment[site] for site in SIX))
    return coordinates, details


def project_vector(vector, killed):
    return {word: value for word, value in vector.items() if word not in killed}


def projected_problem(mask=31, preserve=(), preserve_cells=(), normal="plane"):
    killed, details = variable_coordinate_span(mask)
    # Every possible four-cut normal is generated by h_X and u_+.  The h_X
    # coordinates are already in the variable span; add u_+ explicitly.
    killed.update(equations.UPLUS)
    killed.difference_update(preserve)
    for bit in preserve_cells:
        cell_coordinates, _ = variable_coordinate_span(1 << bit)
        killed.difference_update(cell_coordinates)
    actual_terms = equations.reconstruct_word_terms(supports.blocks_for_mask(mask))
    projected = collections.defaultdict(list)
    for word, terms in actual_terms.items():
        if word not in killed:
            projected[word].extend(terms)
    blocks = supports.blocks_for_mask(mask)
    hs = equations.cylinders.matching_tensor(SIX, blocks)
    uplus = equations.cylinders.matching_tensor(
        SIX, supports.blocks_for_mask(0)
    )
    moving = subtract(hs, uplus)
    if normal == "plane":
        raw_basis = (moving, uplus)
    elif normal == "line":
        raw_basis = (hs,)
    else:
        raise ValueError(normal)
    basis = [project_vector(vector, killed) for vector in raw_basis]
    basis = [vector for vector in basis if vector]
    return projected, killed, details, basis


def projected_word_terms(mask=31, preserve=()):
    """Compatibility helper used by quick census snippets."""
    projected, killed, details, _basis = projected_problem(mask, preserve)
    return projected, killed, details


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--singular", action="store_true")
    parser.add_argument("--mask", type=lambda value: int(value, 0), default=31)
    parser.add_argument(
        "--preserve-target", action="append", type=int, choices=(0, 1, 2),
        default=[], help="do not quotient out this pure target coordinate",
    )
    parser.add_argument(
        "--preserve-cell", action="append", type=int, choices=range(5),
        default=[], help="retain every variable coordinate of this cell bit",
    )
    parser.add_argument("--normal", choices=("plane", "line"), default="plane")
    parser.add_argument(
        "--active-colours", default=None,
        help="optional comma-separated necessary subsystem of nonabsorbed colours",
    )
    parser.add_argument("--timeout", type=int, default=3600)
    parser.add_argument("--characteristic", type=int, default=0)
    args = parser.parse_args()

    preserve = tuple((colour,) * 6 for colour in args.preserve_target)
    projected, killed, details, basis = projected_problem(
        args.mask, preserve, tuple(args.preserve_cell), args.normal
    )
    print("mask", args.mask, supports.support_name(args.mask))
    print("variable_pairs", VARIABLE_PAIRS)
    print("variable_cofactor_supports", {
        pair: len(tensor) for pair, tensor in details.items()
    })
    print("killed_coordinates", len(killed))
    print("projected_words", len(projected))
    print("projected_atoms", sum(map(len, projected.values())))
    normal_span = equations.cylinders.echelon(basis)
    absorbed = tuple(
        c for c in COLOURS
        if (c,) * 6 in killed
        or equations.cylinders.member({(c,) * 6: Q(1)}, normal_span)
    )
    active = tuple(c for c in COLOURS if c not in absorbed)
    if args.active_colours is not None:
        requested = tuple(int(value) for value in args.active_colours.split(","))
        if not set(requested) <= set(active) or len(requested) < 2:
            raise SystemExit("requested colours must be at least two nonabsorbed colours")
        active = requested
    print("projected_normal_dimension", len(normal_span))
    print("absorbed_targets", absorbed, "active_targets", active)
    print("target_term_counts", {
        c: len(projected.get((c,) * 6, ())) for c in active
    })
    if not args.singular:
        return
    singular = shutil.which("Singular")
    if singular is None:
        raise SystemExit("Singular is required")
    program, count = worker.direct_program(
        projected, basis, active, args.characteristic
    )
    print("generators", count, flush=True)
    started = time.monotonic()
    completed = subprocess.run(
        [singular, "-q"], input=program, text=True, capture_output=True,
        check=True, timeout=args.timeout,
    )
    elapsed = time.monotonic() - started
    if completed.stderr.strip():
        raise AssertionError(completed.stderr)
    unit = worker.marker_values(completed.stdout, "UNIT", 1)[0]
    size = worker.marker_values(completed.stdout, "GBSIZE", 1)[0]
    print(
        "RESULT", f"characteristic={args.characteristic}", f"unit={unit}",
        f"gbsize={size}", f"seconds={elapsed:.3f}", flush=True,
    )


if __name__ == "__main__":
    main()
