#!/usr/bin/env python3
"""Lazy exact search for arbitrary-complex binomial counterexamples at n=8.

The existing signed search restricts every selected aggregate cell to weight
``+1`` or ``-1``.  This search keeps the same sound support condition -- each
mixed fibre is empty or has exactly two perfect matchings, while every pure
fibre has one prescribed matching -- but tests the resulting Laurent system

    x**(a_M-a_N) = -1

over the full complex torus.  Consistency is decided by an integer HNF, not
by reducing the exponent equations modulo two.  If a support survives, a
Smith decomposition reconstructs rational phases and hence explicit roots
of unity.  A direct independent enumeration then checks all 3**8 fibres.

An inconsistent Laurent chart yields a sound support nogood: a future valid
0/2-fibre support cannot retain both terms of every contradictory binomial.
The learned clause therefore guards the union of their selected cells.
"""

from __future__ import annotations

import argparse
from collections import Counter
from fractions import Fraction
from functools import lru_cache
from itertools import permutations, product
from math import gcd, lcm

from sympy.polys.domains import ZZ
from sympy.polys.matrices import DomainMatrix
from sympy.polys.matrices.normalforms import smith_normal_decomp

import search_n8_signed_binomial_lazy_cegar as signed
import search_parallel_binomial_nonzero_constants_cegar as toric


# Representatives of the two disjoint S_8 x S_3 orbits generated by the
# checked diagonal odd-triangle circuits at the orbit-40 monomial boundary.
DIAGONAL_TRIANGLE_GUARD_REPRESENTATIVES = (
    frozenset({
        (0, 1, 0, 0), (0, 2, 1, 1), (0, 3, 0, 0),
        (1, 4, 0, 0), (1, 6, 0, 0), (2, 4, 2, 2),
        (2, 6, 2, 2), (3, 4, 0, 0), (3, 6, 0, 0),
        (5, 7, 1, 1),
    }),
    frozenset({
        (0, 1, 0, 0), (0, 2, 1, 1), (0, 5, 0, 0),
        (1, 4, 0, 0), (1, 6, 0, 0), (2, 4, 2, 2),
        (2, 6, 2, 2), (3, 7, 2, 2), (4, 5, 0, 0),
        (5, 6, 0, 0),
    }),
)

# Three further schemas discovered only after installing the two diagonal
# boundary orbits.  The first has one genuinely off-diagonal endpoint-colour
# cell; the other two are new diagonal schemas.  Each ten-cell support by
# itself has exactly three nonempty fibres, all binomial, whose exponent rows
# form an odd unit-coefficient circuit.
ADDITIONAL_TRIANGLE_GUARD_REPRESENTATIVES = (
    frozenset({
        (0, 1, 0, 0), (0, 3, 0, 0), (0, 6, 1, 2),
        (1, 2, 0, 0), (1, 4, 0, 0), (2, 3, 0, 0),
        (2, 6, 1, 1), (3, 4, 0, 0), (4, 6, 1, 1),
        (5, 7, 1, 1),
    }),
    frozenset({
        (0, 1, 0, 0), (0, 3, 0, 0), (0, 4, 2, 2),
        (1, 2, 0, 0), (1, 6, 0, 0), (2, 3, 0, 0),
        (2, 4, 0, 0), (3, 6, 0, 0), (4, 6, 1, 1),
        (5, 7, 1, 1),
    }),
    frozenset({
        (0, 1, 0, 0), (0, 3, 0, 0), (0, 6, 0, 0),
        (1, 2, 0, 0), (1, 4, 0, 0), (2, 3, 0, 0),
        (2, 6, 1, 1), (3, 4, 0, 0), (4, 6, 1, 1),
        (5, 7, 1, 1),
    }),
)

# A twelve-cell odd triangle mined from a dense orbit-40 structural chart.
# Its full S_8 x S_3 orbit is regular (241,920 guards), so production uses
# only its inexpensive orbit under the fixed target's automorphism group.
DENSE_TARGET_TRIANGLE_GUARD_REPRESENTATIVE = frozenset({
    (0, 1, 0, 0), (0, 2, 0, 0), (0, 6, 0, 2),
    (1, 3, 1, 1), (1, 4, 0, 0), (2, 3, 0, 0),
    (2, 4, 0, 0), (3, 5, 0, 2), (4, 5, 0, 0),
    (5, 7, 0, 0), (6, 7, 0, 0), (6, 7, 2, 0),
})

ONE_ROW_PURE_ZERO_MIXED_GUARD = frozenset({
    (0, 2, 1, 1), (0, 4, 1, 1), (1, 5, 2, 2),
    (2, 6, 1, 1), (3, 7, 2, 2), (4, 6, 1, 1),
})
ONE_ROW_PURE_ZERO_COLOUR = 1
ONE_ROW_PURE_ZERO_MATCHINGS = frozenset({
    frozenset({(0, 2), (1, 3), (4, 6), (5, 7)}),
    frozenset({(0, 4), (1, 3), (2, 6), (5, 7)}),
})

THREE_ROW_PURE_ZERO_MIXED_GUARD = frozenset({
    (0, 4, 2, 2), (1, 3, 1, 1), (1, 3, 1, 2),
    (1, 5, 1, 1), (1, 5, 1, 2), (2, 6, 2, 2),
    (3, 7, 1, 1), (3, 7, 2, 1), (5, 7, 1, 1),
    (5, 7, 2, 1),
})
THREE_ROW_PURE_ZERO_COLOUR = 1
THREE_ROW_PURE_ZERO_MATCHINGS = frozenset({
    frozenset({(0, 2), (1, 3), (4, 6), (5, 7)}),
    frozenset({(0, 2), (1, 5), (3, 7), (4, 6)}),
})


def image_guard(guard, vertex_permutation, colour_permutation):
    image = []
    for u, v, a, b in guard:
        image_u, image_v = vertex_permutation[u], vertex_permutation[v]
        image_a, image_b = colour_permutation[a], colour_permutation[b]
        if image_u > image_v:
            image_u, image_v = image_v, image_u
            image_a, image_b = image_b, image_a
        image.append((image_u, image_v, image_a, image_b))
    return frozenset(image)


@lru_cache(maxsize=1)
def global_diagonal_triangle_guards():
    """Return all 60,480 relabelings of the two checked guard schemas."""

    vertex_permutations = tuple(permutations(range(signed.N)))
    colour_permutations = tuple(permutations(range(signed.Q)))
    orbits = []
    for representative in DIAGONAL_TRIANGLE_GUARD_REPRESENTATIVES:
        orbit = {
            image_guard(representative, vertex, colour)
            for vertex in vertex_permutations
            for colour in colour_permutations
        }
        assert len(orbit) == 30240
        orbits.append(orbit)
    assert orbits[0].isdisjoint(orbits[1])
    guards = orbits[0] | orbits[1]
    assert len(guards) == 60480
    return tuple(sorted(guards, key=lambda guard: tuple(sorted(guard))))


@lru_cache(maxsize=1)
def global_additional_triangle_guards():
    """Return the 120,960 relabelings of three further checked schemas."""

    vertex_permutations = tuple(permutations(range(signed.N)))
    colour_permutations = tuple(permutations(range(signed.Q)))
    expected_sizes = (30240, 60480, 30240)
    orbits = []
    for representative, expected in zip(
        ADDITIONAL_TRIANGLE_GUARD_REPRESENTATIVES, expected_sizes
    ):
        orbit = {
            image_guard(representative, vertex, colour)
            for vertex in vertex_permutations
            for colour in colour_permutations
        }
        assert len(orbit) == expected
        orbits.append(orbit)
    assert all(
        orbits[i].isdisjoint(orbits[j])
        for i in range(len(orbits))
        for j in range(i + 1, len(orbits))
    )
    guards = set().union(*orbits)
    assert len(guards) == 120960
    return tuple(sorted(guards, key=lambda guard: tuple(sorted(guard))))


@lru_cache(maxsize=1)
def global_triangle_guards():
    """Return all 181,440 currently certified relabeled triangle guards."""

    diagonal = set(global_diagonal_triangle_guards())
    additional = set(global_additional_triangle_guards())
    assert diagonal.isdisjoint(additional)
    guards = diagonal | additional
    assert len(guards) == 181440
    return tuple(sorted(guards, key=lambda guard: tuple(sorted(guard))))


def target_dense_triangle_guards(automorphisms):
    """Relabel the dense twelve-cell circuit by target automorphisms."""

    guards = {
        image_guard(DENSE_TARGET_TRIANGLE_GUARD_REPRESENTATIVE, vertex, colour)
        for vertex, colour in automorphisms
    }
    assert guards
    return tuple(sorted(guards, key=lambda guard: tuple(sorted(guard))))


@lru_cache(maxsize=None)
def target_dense_triangle_high_overlap_guards(targets, minimum_forced=3):
    """Return full-orbit dense guards with many forced target cells."""

    forced = frozenset(
        (u, v, colour, colour)
        for colour, target in enumerate(targets)
        for u, v in target
    )
    guards = {
        image
        for vertex in permutations(range(signed.N))
        for colour in permutations(range(signed.Q))
        for image in (
            image_guard(
                DENSE_TARGET_TRIANGLE_GUARD_REPRESENTATIVE,
                vertex,
                colour,
            ),
        )
        if len(image & forced) >= minimum_forced
    }
    return tuple(sorted(guards, key=lambda guard: tuple(sorted(guard))))


@lru_cache(maxsize=1)
def global_one_row_pure_zero_schemas():
    """Return 7,560 relabelings of a one-row forced-pure-zero schema."""

    schemas = set()
    for vertex in permutations(range(signed.N)):
        image_matchings = frozenset(
            frozenset(
                tuple(sorted((vertex[u], vertex[v]))) for u, v in matching
            )
            for matching in ONE_ROW_PURE_ZERO_MATCHINGS
        )
        for colour in permutations(range(signed.Q)):
            schemas.add((
                image_guard(
                    ONE_ROW_PURE_ZERO_MIXED_GUARD, vertex, colour
                ),
                colour[ONE_ROW_PURE_ZERO_COLOUR],
                image_matchings,
            ))
    assert len(schemas) == 7560
    return tuple(sorted(
        schemas,
        key=lambda item: (
            tuple(sorted(item[0])),
            item[1],
            tuple(sorted(tuple(sorted(matching)) for matching in item[2])),
        ),
    ))


@lru_cache(maxsize=None)
def target_one_row_pure_zero_schemas(targets):
    """Return every one-row pure-zero schema compatible with ``targets``.

    If the exact pure fibre has terms ``P,Q`` and contains its forced target
    ``P``, equality (up to sign) of a mixed exponent-difference row with the
    pure row forces the following form.  The two mixed matchings use precisely
    ``P-Q`` and ``Q-P`` on the alternating-cycle vertices, all colored by the
    pure color, and share an arbitrary perfect matching on the vertices of
    ``P & Q``.  Those shared vertices carry an arbitrary nonconstant color
    assignment.  Conversely every such choice gives the common-factor
    identity, so this enumeration is complete for one-row certificates in a
    fixed-target search.
    """

    pure_targets = tuple(frozenset(matching) for matching in targets)
    assert len(pure_targets) == signed.Q
    assert all(len(matching) == signed.N // 2 for matching in pure_targets)
    matchings = tuple(
        frozenset(matching)
        for matching in signed.core.perfect_matchings(tuple(range(signed.N)))
    )
    schemas = set()
    for colour, target in enumerate(pure_targets):
        for other in matchings:
            if other == target:
                continue
            common = target & other
            if not common:
                # With no shared pure edge every vertex occurs in the pure
                # exponent difference, so an equal mixed row is monochrome.
                continue
            assert len(common) in (1, 2)
            common_vertices = tuple(sorted({
                vertex for edge in common for vertex in edge
            }))
            target_only = target - common
            other_only = other - common
            for shared in signed.core.perfect_matchings(common_vertices):
                mixed_first = tuple(sorted(target_only | set(shared)))
                mixed_second = tuple(sorted(other_only | set(shared)))
                assert len(mixed_first) == len(mixed_second) == signed.N // 2
                for assigned in product(
                    range(signed.Q), repeat=len(common_vertices)
                ):
                    coloring = [colour] * signed.N
                    for vertex, value in zip(common_vertices, assigned):
                        coloring[vertex] = value
                    if all(value == colour for value in coloring):
                        continue
                    coloring = tuple(coloring)
                    guard = frozenset(
                        signed.decorated_term(coloring, mixed_first)
                        + signed.decorated_term(coloring, mixed_second)
                    )
                    schemas.add((
                        guard,
                        colour,
                        frozenset((target, other)),
                    ))

    assert len(schemas) == 9408
    assert Counter(len(guard) for guard, _colour, _terms in schemas) == {
        6: 8640,
        7: 768,
    }
    return tuple(sorted(
        schemas,
        key=lambda item: (
            tuple(sorted(item[0])),
            item[1],
            tuple(sorted(tuple(sorted(matching)) for matching in item[2])),
        ),
    ))


@lru_cache(maxsize=None)
def target_complete_one_row_pure_zero_schemas(targets):
    """Extend the target pair schemas to every one-row zero pure fibre.

    A six-cycle difference has only the target's single pure matching pair.
    A four-cycle difference has three disjoint pure matching pairs, one for
    each perfect matching on the four complementary vertices.  In the latter
    case the exact pure polynomial vanishes precisely when its term set is a
    nonempty union of complete pairs; because the forced target belongs to one
    distinguished pair, there are four allowed unions of sizes 2, 4, 4, 6.
    """

    pure_targets = tuple(frozenset(matching) for matching in targets)
    schemas = set()
    for guard, colour, pure_pair in target_one_row_pure_zero_schemas(targets):
        target = pure_targets[colour]
        assert target in pure_pair
        other, = pure_pair - {target}
        common = target & other
        if len(common) == 1:
            schemas.add((guard, colour, pure_pair))
            continue
        assert len(common) == 2
        common_vertices = tuple(sorted({
            vertex for edge in common for vertex in edge
        }))
        target_only = target - common
        other_only = other - common
        paired_terms = []
        for shared in signed.core.perfect_matchings(common_vertices):
            paired_terms.append(frozenset((
                frozenset(target_only | set(shared)),
                frozenset(other_only | set(shared)),
            )))
        assert len(paired_terms) == 3
        assert len(set(paired_terms)) == 3
        assert pure_pair in paired_terms
        optional = tuple(pair for pair in paired_terms if pair != pure_pair)
        assert len(optional) == 2
        for included in product((False, True), repeat=2):
            present = set(pure_pair)
            for use_pair, pair in zip(included, optional):
                if use_pair:
                    present.update(pair)
            schemas.add((guard, colour, frozenset(present)))

    assert len(schemas) == 35328
    assert Counter(len(terms) for _guard, _colour, terms in schemas) == {
        2: 9408,
        4: 17280,
        6: 8640,
    }
    assert Counter(len(guard) for guard, _colour, _terms in schemas) == {
        6: 34560,
        7: 768,
    }
    return tuple(sorted(
        schemas,
        key=lambda item: (
            tuple(sorted(item[0])),
            item[1],
            tuple(sorted(tuple(sorted(matching)) for matching in item[2])),
        ),
    ))


@lru_cache(maxsize=1)
def global_three_row_pure_zero_schemas():
    """Return 15,120 relabelings of a three-row forced-pure-zero schema."""

    schemas = set()
    for vertex in permutations(range(signed.N)):
        image_matchings = frozenset(
            frozenset(
                tuple(sorted((vertex[u], vertex[v]))) for u, v in matching
            )
            for matching in THREE_ROW_PURE_ZERO_MATCHINGS
        )
        for colour in permutations(range(signed.Q)):
            schemas.add((
                image_guard(
                    THREE_ROW_PURE_ZERO_MIXED_GUARD, vertex, colour
                ),
                colour[THREE_ROW_PURE_ZERO_COLOUR],
                image_matchings,
            ))
    assert len(schemas) == 15120
    return tuple(sorted(
        schemas,
        key=lambda item: (
            tuple(sorted(item[0])),
            item[1],
            tuple(sorted(tuple(sorted(matching)) for matching in item[2])),
        ),
    ))


def exponent_rows(search, fibres):
    mixed = [
        (colouring, terms)
        for colouring, terms in sorted(fibres.items())
        if len(set(colouring)) > 1
    ]
    rows = [
        toric.exponent_row(
            terms[0][1], terms[1][1], search.cell_index, len(search.cells)
        )
        for _colouring, terms in mixed
    ]
    return mixed, rows


def contradictory_row_indices(rows):
    """Return a checked odd integer dependency when FLINT displays one."""

    relation = toric.flint_odd_relation(rows) if rows else None
    if relation is None:
        return tuple(range(len(rows)))
    assert sum(relation) & 1
    assert all(
        sum(relation[row] * rows[row][column] for row in range(len(rows))) == 0
        for column in range(len(rows[0]))
    )
    return tuple(index for index, value in enumerate(relation) if value)


def unit_triangle_circuits(rows):
    """Find all three-row contradictions with coefficients in ``{+1,-1}``.

    If ``s_1 d_i+s_2 d_j+s_3 d_k=0`` for three distinct rows, multiplying
    the corresponding equations gives ``1=(-1)^(s_1+s_2+s_3)=-1``.  These
    tiny circuits occur frequently near the orbit-40 monomial boundary.  A
    hash lookup finds all of them in quadratic rather than cubic time.
    """

    if len(rows) < 3:
        return ()
    row_tuples = tuple(tuple(row) for row in rows)
    locations = {}
    for index, row in enumerate(row_tuples):
        locations.setdefault(row, []).append(index)

    circuits = set()
    for left in range(len(rows)):
        for right in range(left + 1, len(rows)):
            for left_sign in (-1, 1):
                for right_sign in (-1, 1):
                    target = tuple(
                        -(left_sign * a + right_sign * b)
                        for a, b in zip(row_tuples[left], row_tuples[right])
                    )
                    for third in locations.get(target, ()):
                        if third == left or third == right:
                            continue
                        indices = tuple(sorted((left, right, third)))
                        circuits.add(indices)

    answer = tuple(sorted(circuits))
    for indices in answer:
        selected = [rows[index] for index in indices]
        assert not toric.signed_quotient_lattice(
            selected, len(selected[0])
        )[0]
    return answer


def laurent_guard_cells(mixed, row_indices):
    guarded = frozenset({
        cell
        for index in row_indices
        for _matching_number, decorated in mixed[index][1]
        for cell in decorated
    })
    assert guarded
    return guarded


def add_laurent_guard(search, guarded):
    search.add_clauses([
        [-search.support[cell] for cell in sorted(guarded)]
    ])
    return len(guarded)


def add_laurent_nogood(search, mixed, row_indices):
    return add_laurent_guard(
        search, laurent_guard_cells(mixed, row_indices)
    )


def install_pure_term_variables(search):
    """Install exact term indicators for the three constant fibres."""

    variables = {}
    clauses = []
    old_top = search.pool.top
    for colour in range(signed.Q):
        colouring = (colour,) * signed.N
        for matching_number, decorated in enumerate(search.terms(colouring)):
            term = search.pool.new()
            variables[colour, matching_number] = term
            clauses.extend([-term, search.support[cell]] for cell in decorated)
            clauses.append(
                [-search.support[cell] for cell in decorated] + [term]
            )
    search.add_clauses(clauses)
    search.solver.set_phases([
        -variable for variable in range(old_top + 1, search.pool.top + 1)
    ])
    return variables, len(clauses)


def install_pure_fibre_trigger_variables(
    search, pure_term_variables, schemas
):
    """Factor exact pure-fibre tests by existential trigger variables.

    A trigger has only the long implication ``exact_fibre -> trigger``.  Every
    schema then contains ``guard -> not trigger``.  If the exact fibre holds,
    the trigger is forced true and every guard is forbidden; otherwise the
    existential auxiliary can be false.  Thus eliminating it gives precisely
    the original long clauses without needing the reverse implication.
    """

    matching_index = {
        frozenset(matching): number
        for number, matching in enumerate(search.matchings)
    }
    present_sets = {
        (
            colour,
            frozenset(matching_index[matching] for matching in present),
        )
        for _guard, colour, present in schemas
    }
    assert len(present_sets) == 204
    assert Counter(len(present) for _colour, present in present_sets) == {
        2: 132,
        4: 36,
        6: 36,
    }
    variables = {}
    clauses = []
    old_top = search.pool.top
    for colour, present in sorted(
        present_sets, key=lambda item: (item[0], tuple(sorted(item[1])))
    ):
        target = search.targets[colour]
        target_number = matching_index[frozenset(target)]
        assert target_number in present
        trigger = search.pool.new()
        variables[colour, present] = trigger
        clause = [trigger]
        for matching_number in range(len(search.matchings)):
            if matching_number == target_number:
                continue
            term = pure_term_variables[colour, matching_number]
            clause.append(-term if matching_number in present else term)
        assert len(clause) == len(search.matchings)
        clauses.append(clause)
    assert len(variables) == len(clauses) == 204
    search.add_clauses(clauses)
    search.solver.set_phases([
        -variable for variable in range(old_top + 1, search.pool.top + 1)
    ])
    return variables, len(clauses)


def add_zero_product_nogood(
    search,
    fibres,
    mixed,
    pure_term_variables,
    row_indices=None,
    colours=tuple(range(signed.Q)),
):
    """Block unchanged mixed equations and unchanged three pure fibres.

    A future valid 0/2-fibre support retaining both terms of every current
    mixed binomial retains every Laurent equation (a third term would itself
    violate the chart).  Exact pure-term indicators guard the only other data
    used by the quotient-product calculation.  Hence a zero reduced product
    makes the conjunction represented by this clause impossible.
    """

    if row_indices is None:
        row_indices = range(len(mixed))
    clause = {
        -search.support[cell]
        for index in row_indices
        for _colouring, terms in (mixed[index],)
        for _matching_number, decorated in terms
        for cell in decorated
    }
    for colour in colours:
        present = {
            matching_number
            for matching_number, _decorated in fibres[(colour,) * signed.N]
        }
        for matching_number in range(len(search.matchings)):
            variable = pure_term_variables[colour, matching_number]
            clause.add(-variable if matching_number in present else variable)
    assert clause
    search.add_clauses([sorted(clause)])
    return len(clause)


def rational_phase_solution(rows, number_cells):
    """Solve ``D theta = 1/2 (mod Z)`` by Smith normal decomposition."""

    if not rows:
        return [Fraction(0) for _ in range(number_cells)]
    matrix = DomainMatrix.from_list([list(row) for row in rows], ZZ)
    diagonal, left, right = smith_normal_decomp(matrix)

    def integers(domain_matrix):
        return [
            [int(domain_matrix[i, j].element) for j in range(domain_matrix.shape[1])]
            for i in range(domain_matrix.shape[0])
        ]

    s = integers(diagonal)
    u = integers(left)
    v = integers(right)
    number_rows = len(rows)
    transformed_rhs = [
        sum(Fraction(u[i][j], 2) for j in range(number_rows))
        for i in range(number_rows)
    ]
    y = [Fraction(0) for _ in range(number_cells)]
    rank = 0
    for i in range(min(number_rows, number_cells)):
        value = s[i][i]
        if value:
            y[i] = transformed_rhs[i] / value
            rank += 1
        else:
            assert transformed_rhs[i].denominator == 1
    for i in range(rank, number_rows):
        assert not any(s[i])
        assert transformed_rhs[i].denominator == 1

    # U D V = S, so theta = V y.
    theta = [
        sum(Fraction(v[i][j]) * y[j] for j in range(number_cells))
        for i in range(number_cells)
    ]
    for row in rows:
        value = sum(Fraction(coefficient) * phase for coefficient, phase in zip(row, theta))
        assert (value - Fraction(1, 2)).denominator == 1
    return theta


def normalized_root_exponents(search, fibres, rows):
    """Return a common order and exact cell exponents after GHZ gauging."""

    phases = rational_phase_solution(rows, len(search.cells))
    order = 1
    for phase in phases:
        order = lcm(order, phase.denominator)
    # Make ``-1`` be represented exactly even if the Smith solution happened
    # to use only odd denominators before reduction.
    order = lcm(order, 2)
    exponents = {
        cell: int(phases[index] * order) % order
        for cell, index in search.cell_index.items()
    }

    # A diagonal endpoint gauge at vertex zero normalizes the unique pure
    # matching product in each colour to one and preserves every mixed zero.
    for colour in range(signed.Q):
        terms = fibres[(colour,) * signed.N]
        assert len(terms) == 1
        pure_exponent = sum(exponents[cell] for cell in terms[0][1]) % order
        for cell in search.cells:
            u, v, a, b = cell
            if u == 0 and a == colour:
                exponents[cell] = (exponents[cell] - pure_exponent) % order
            elif v == 0 and b == colour:
                exponents[cell] = (exponents[cell] - pure_exponent) % order

    divisor = order
    for cell in search.cells:
        divisor = gcd(divisor, exponents[cell])
    if divisor > 1:
        order //= divisor
        exponents = {cell: value // divisor for cell, value in exponents.items()}
    return order, exponents


def verify_root_solution(search, selected, order, exponents):
    """Audit all coefficients in the group ring of the cyclic roots."""

    fibres = toric.exact_fibres(signed.N, selected, search.matchings)
    assert len(fibres) >= signed.Q
    for colouring in __import__("itertools").product(
        range(signed.Q), repeat=signed.N
    ):
        terms = fibres.get(colouring, ())
        term_exponents = [
            sum(exponents[cell] for cell in decorated) % order
            for _matching_number, decorated in terms
        ]
        if len(set(colouring)) == 1:
            assert term_exponents == [0]
        else:
            assert len(term_exponents) in (0, 2)
            if term_exponents:
                assert order % 2 == 0
                assert (term_exponents[0] - term_exponents[1]) % order == order // 2
    return fibres


def run(orbit, max_cells, solver_name, max_rounds, batch, symmetry_lex,
        allow_extra_constants, monomial_seed, triangle_cuts=True,
        global_diagonal_triangles=True, print_triangle_representatives=False,
        print_zero_supports=False):
    search = signed.LazySearch(
        orbit,
        solver_name,
        max_cells,
        symmetry_lex=symmetry_lex,
        unique_constants=not allow_extra_constants,
    )
    pure_term_variables = None
    if allow_extra_constants:
        pure_term_variables, definition_clauses = install_pure_term_variables(
            search
        )
        print(
            f"installed_pure_term_variables={len(pure_term_variables)} "
            f"definition_clauses={definition_clauses}",
            flush=True,
        )
    laurent_guards = set()
    global_triangle_cuts = 0
    target_triangle_cuts = 0
    if global_diagonal_triangles:
        guards = global_triangle_guards()
        search.add_clauses([
            [-search.support[cell] for cell in sorted(guard)]
            for guard in guards
        ])
        laurent_guards.update(guards)
        global_triangle_cuts = len(guards)
        del guards
        global_triangle_guards.cache_clear()
        global_diagonal_triangle_guards.cache_clear()
        global_additional_triangle_guards.cache_clear()
        print(
            f"preloaded_global_triangle_cuts={global_triangle_cuts}",
            flush=True,
        )
        target_guards = set(
            target_dense_triangle_high_overlap_guards(search.targets, 3)
        ) - laurent_guards
        search.add_clauses([
            [-search.support[cell] for cell in sorted(guard)]
            for guard in target_guards
        ])
        laurent_guards.update(target_guards)
        target_triangle_cuts = len(target_guards)
        del target_guards
        target_dense_triangle_high_overlap_guards.cache_clear()
        print(
            f"preloaded_target_triangle_cuts={target_triangle_cuts}",
            flush=True,
        )
    preloaded_pure_zero_cuts = 0
    if allow_extra_constants:
        assert pure_term_variables is not None
        matching_index = {
            frozenset(matching): number
            for number, matching in enumerate(search.matchings)
        }
        pure_zero_clauses = []
        # This is the complete one-row zero family compatible with the forced
        # target term.  Four-cycle rows may cancel exact pure fibres of sizes
        # four or six as unions of matching pairs, not only two-term fibres.
        schemas = target_complete_one_row_pure_zero_schemas(search.targets)
        pure_fibre_triggers, trigger_definition_clauses = (
            install_pure_fibre_trigger_variables(
                search, pure_term_variables, schemas
            )
        )
        print(
            f"installed_pure_fibre_triggers={len(pure_fibre_triggers)} "
            f"definition_clauses={trigger_definition_clauses}",
            flush=True,
        )
        reduced_guard_sizes = Counter()
        for guard, colour, present_matchings in schemas:
            present = frozenset(
                matching_index[matching] for matching in present_matchings
            )
            assert len(present) in (2, 4, 6)
            target_matching = matching_index[
                frozenset(search.targets[colour])
            ]
            assert target_matching in present
            reduced_guard = guard - search.forced_support
            reduced_guard_sizes[len(reduced_guard)] += 1
            clause = {
                -search.support[cell] for cell in reduced_guard
            }
            clause.add(-pure_fibre_triggers[colour, present])
            assert len(clause) == len(reduced_guard) + 1
            pure_zero_clauses.append(sorted(clause))
        assert reduced_guard_sizes == {2: 96, 3: 3840, 4: 31392}
        assert len({tuple(clause) for clause in pure_zero_clauses}) == 35328
        search.add_clauses(pure_zero_clauses)
        preloaded_pure_zero_cuts = len(pure_zero_clauses)
        del schemas, pure_zero_clauses, pure_fibre_triggers
        target_complete_one_row_pure_zero_schemas.cache_clear()
        target_one_row_pure_zero_schemas.cache_clear()
        print(
            f"preloaded_pure_zero_cuts="
            f"{preloaded_pure_zero_cuts}",
            flush=True,
        )
    seed_triangle_cuts = 0
    seed_triangle_circuits = 0
    if monomial_seed:
        seed_permutations = {
            40: tuple(range(signed.N)),
            44: tuple(range(signed.N)),
            55: (0, 1, 2, 4, 5, 3, 7, 6),
            56: (0, 1, 2, 4, 5, 3, 7, 6),
        }
        if orbit not in seed_permutations or not allow_extra_constants:
            raise ValueError(
                "--monomial-seed requires orbit 40, 44, 55, or 56 "
                "and --allow-extra-constants"
            )
        colour_one = {(0, 2), (1, 3), (4, 6), (5, 7)}
        colour_two = {
            (0, 4), (0, 6), (1, 5), (1, 7),
            (2, 4), (2, 6), (3, 5), (3, 7),
        }
        vertex_permutation = seed_permutations[orbit]
        raw_seed = {
            (u, v,
             1 if (u, v) in colour_one else 2
             if (u, v) in colour_two else 0)
            for u in range(signed.N)
            for v in range(u + 1, signed.N)
        }
        seed = set()
        for u, v, colour in raw_seed:
            image_u = vertex_permutation[u]
            image_v = vertex_permutation[v]
            if image_u > image_v:
                image_u, image_v = image_v, image_u
            seed.add((image_u, image_v, colour, colour))
        assert len(seed) == 28
        assert search.forced_support <= seed
        search.solver.set_phases([
            search.support[cell] if cell in seed else -search.support[cell]
            for cell in search.cells
        ])
        # These clauses are consequences of the Laurent equations, not an
        # assumption that the phased support is selected.  Preloading them
        # removes every known odd triangle at the selected monomial boundary
        # before the first SAT call.
        if triangle_cuts:
            seed_fibres = toric.exact_fibres(
                signed.N, seed, search.matchings
            )
            seed_mixed, seed_rows = exponent_rows(search, seed_fibres)
            for indices in unit_triangle_circuits(seed_rows):
                seed_triangle_circuits += 1
                guard = laurent_guard_cells(seed_mixed, indices)
                if guard in laurent_guards:
                    continue
                add_laurent_guard(search, guard)
                laurent_guards.add(guard)
                seed_triangle_cuts += 1
            print(
                f"preloaded_seed_triangle_cuts={seed_triangle_cuts} "
                f"covered={seed_triangle_circuits - seed_triangle_cuts}",
                flush=True,
            )
    learned = (
        global_triangle_cuts
        + target_triangle_cuts
        + preloaded_pure_zero_cuts
        + seed_triangle_cuts
    )
    laurent_cuts = (
        global_triangle_cuts + target_triangle_cuts + seed_triangle_cuts
    )
    best = None
    try:
        for round_number in range(max_rounds):
            if not search.solver.solve():
                print(
                    f"UNSAT orbit={orbit} max_cells={max_cells} "
                    f"rounds={round_number} variables={search.pool.top} "
                    f"learned={learned} laurent_cuts={laurent_cuts}",
                    flush=True,
                )
                return None
            selected, _weights = search.decode(search.solver.get_model())
            fibres = toric.exact_fibres(
                signed.N, selected, search.matchings
            )
            structural = [
                (colouring, terms)
                for colouring, terms in fibres.items()
                if len(set(colouring)) > 1 and len(terms) != 2
            ]

            if not structural:
                mixed, rows = exponent_rows(search, fibres)
                consistent, _lattice = toric.signed_quotient_lattice(
                    rows, len(search.cells)
                )
                if consistent:
                    _consistent, lattice = toric.signed_quotient_lattice(
                        rows, len(search.cells)
                    )
                    remainder, classes = toric.reduced_constant_product(
                        signed.N,
                        fibres,
                        lattice,
                        search.cells,
                        search.cell_index,
                    )
                    if remainder:
                        if search.unique_constants:
                            order, exponents = normalized_root_exponents(
                                search, fibres, rows
                            )
                            verified = verify_root_solution(
                                search, selected, order, exponents
                            )
                            print(
                                f"SAT EXACT TORIC orbit={orbit} "
                                f"cells={len(selected)} fibres={len(verified)} "
                                f"root_order={order} round={round_number}",
                                flush=True,
                            )
                            for cell in sorted(selected):
                                print(
                                    f"  {cell} zeta^{exponents[cell]}",
                                    flush=True,
                                )
                            return selected, order, exponents
                        print(
                            f"SURVIVOR TORIC orbit={orbit} cells={len(selected)} "
                            f"fibres={len(fibres)} quotient_classes={len(classes)} "
                            f"nonzero_classes={len(remainder)} "
                            f"round={round_number}",
                            flush=True,
                        )
                        for cell in sorted(selected):
                            print(f"  {cell}", flush=True)
                        # Turn the nonzero group-ring class into explicit
                        # algebraic cell weights and recheck all 3^8 fibres.
                        # This import is deliberately lazy: Smith-coordinate
                        # specialization is needed only for a survivor.
                        from reconstruct_n8_toric_witness import (
                            n8_exact_witness,
                        )
                        witness = n8_exact_witness(
                            search, selected, fibres, rows
                        )
                        print(
                            "SAT EXACT TORIC EXTRA "
                            f"root_order={witness['root_order']} "
                            f"integer_base={witness['integer_base']}",
                            flush=True,
                        )
                        for cell in sorted(selected):
                            root = witness["cell_root_exponents"][cell]
                            power = witness["cell_integer_powers"][cell]
                            normalizer = (
                                f" / C_{cell[2]}" if cell[0] == 0 else ""
                            )
                            print(
                                f"  {cell} zeta^{root} * "
                                f"{witness['integer_base']}^{power}"
                                f"{normalizer}",
                                flush=True,
                            )
                        for colour, terms in enumerate(witness["pure_terms"]):
                            print(f"  C_{colour} terms={terms}", flush=True)
                        return selected, witness

                    # Retaining every current mixed pair and the exact three
                    # pure term sets retains this zero quotient product.  The
                    # guarded term-level cut leaves all irrelevant support
                    # bits free.
                    assert pure_term_variables is not None
                    used_zero_rows, used_zero_colours = (
                        toric.minimize_zero_product_certificate(
                            signed.N,
                            fibres,
                            rows,
                            search.cells,
                            search.cell_index,
                        )
                    )
                    zero_cut_size = add_zero_product_nogood(
                        search,
                        fibres,
                        mixed,
                        pure_term_variables,
                        used_zero_rows,
                        used_zero_colours,
                    )
                    learned += 1
                    print(
                        f"round={round_number} structurally_exact "
                        f"cells={len(selected)} mixed={len(mixed)} "
                        f"consistent_but_constant_product_zero "
                        f"classes={len(classes)} zero_cut={zero_cut_size} "
                        f"zero_rows={len(used_zero_rows)}/{len(rows)} "
                        f"zero_colours={used_zero_colours}",
                        flush=True,
                    )
                    if print_zero_supports:
                        print(
                            f"zero_support={tuple(sorted(selected))}",
                            flush=True,
                        )
                    continue
                triangles = unit_triangle_circuits(rows) if triangle_cuts else ()
                if triangles:
                    new_triangles = []
                    for indices in triangles:
                        guard = laurent_guard_cells(mixed, indices)
                        if guard in laurent_guards:
                            continue
                        add_laurent_guard(search, guard)
                        laurent_guards.add(guard)
                        new_triangles.append((indices, guard))
                    # Every circuit in the current SAT model has all of its
                    # guard cells selected, so a previously installed guard
                    # would already exclude this model.
                    assert new_triangles
                    cut_sizes = [len(guard) for _indices, guard in new_triangles]
                    learned += len(new_triangles)
                    laurent_cuts += len(new_triangles)
                    used = new_triangles[0][0]
                    cut_size = min(cut_sizes)
                else:
                    used = contradictory_row_indices(rows)
                    guard = laurent_guard_cells(mixed, used)
                    assert guard not in laurent_guards
                    cut_size = add_laurent_guard(search, guard)
                    laurent_guards.add(guard)
                    learned += 1
                    laurent_cuts += 1
                print(
                    f"round={round_number} structurally_exact cells={len(selected)} "
                    f"mixed={len(mixed)} inconsistent_rows={len(used)}/{len(rows)} "
                    f"guard_cells={cut_size} triangle_cuts="
                    f"{len(new_triangles) if triangles else 0}/{len(triangles)}",
                    flush=True,
                )
                if triangles and print_triangle_representatives:
                    print(
                        "triangle_guard_representative="
                        f"{tuple(sorted(new_triangles[0][1]))}",
                        flush=True,
                    )
                continue

            score = (len(structural), len(selected))
            if best is None or score < best:
                best = score
                print(
                    f"best round={round_number} cells={len(selected)} "
                    f"fibres={len(fibres)} structural={len(structural)}",
                    flush=True,
                )
            added = 0
            clauses = 0
            for colouring, _terms in sorted(
                structural, key=lambda item: (-len(item[1]), item[0])
            ):
                if colouring in search.fibre_gadgets:
                    continue
                _variables, new_clauses = search.add_fibre_gadget(colouring)
                clauses += new_clauses
                added += 1
                if added >= batch:
                    break
            assert added
            learned += clauses
            if round_number < 20 or round_number % 10 == 0:
                histogram = Counter(len(terms) for terms in fibres.values())
                print(
                    f"round={round_number} cells={len(selected)} "
                    f"sizes={dict(sorted(histogram.items()))} "
                    f"structural={len(structural)} add={added} "
                    f"new_clauses={clauses}",
                    flush=True,
                )
        print(f"BOUNDARY rounds={max_rounds} best={best}", flush=True)
        return "boundary"
    finally:
        search.delete()


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--orbit", type=int, default=39)
    parser.add_argument("--max-cells", type=int, default=24)
    parser.add_argument("--solver", default="cadical300")
    parser.add_argument("--max-rounds", type=int, default=5000)
    parser.add_argument("--batch", type=int, default=256)
    parser.add_argument("--symmetry-lex", action="store_true")
    parser.add_argument(
        "--allow-extra-constants",
        action="store_true",
        help="allow complete pure fibres and apply the full quotient test",
    )
    parser.add_argument(
        "--monomial-seed",
        action="store_true",
        help="phase orbits 40/44/55/56 at their exact 28-cell K8 boundary",
    )
    parser.add_argument(
        "--no-triangle-cuts",
        action="store_true",
        help="disable eager exact three-row Laurent circuit cuts",
    )
    parser.add_argument(
        "--no-global-diagonal-triangles",
        action="store_true",
        help="disable all 181,440 exact relabeled triangle guards",
    )
    parser.add_argument(
        "--print-triangle-representatives",
        action="store_true",
        help="print one newly learned exact triangle guard per chart",
    )
    parser.add_argument(
        "--print-zero-supports",
        action="store_true",
        help="print exact supports whose reduced pure product is zero",
    )
    args = parser.parse_args()
    run(
        args.orbit, args.max_cells, args.solver, args.max_rounds,
        args.batch,
        args.symmetry_lex,
        args.allow_extra_constants,
        args.monomial_seed,
        not args.no_triangle_cuts,
        not args.no_global_diagonal_triangles,
        args.print_triangle_representatives,
        args.print_zero_supports,
    )


if __name__ == "__main__":
    main()
