#!/usr/bin/env python3
"""Modular reconnaissance for the residual-pure branch near the Pythagorean guard.

Adjoin two literal endpoint-coloured cells to the five-cell rational common
power.  Retain packets for which X_0 and X_1 lie in the common-cofactor
image, and test whether X_2 enters im(Phi)+R_nt, where R_nt is generated by
products P*N*K with N=ker(Phi) intersect ker(pi_2) and K=ker(Phi).

This is a search script, not a certificate: every positive modular hit must
be reconstructed over Q before it has mathematical force.
"""

from __future__ import annotations

from collections import defaultdict
import argparse
import itertools


PRIME = 1_000_003
SITES = tuple(range(5))
TARGET = 2
WORDS = tuple(itertools.product(range(3), repeat=5))
WORD_INDEX = {word: index for index, word in enumerate(WORDS)}
LABELS = tuple(itertools.product(SITES, range(3)))


def inv(value):
    return pow(value % PRIME, PRIME - 2, PRIME)


def add_cell(cells, u, v, left, right, value):
    if u > v:
        u, v = v, u
        left, right = right, left
    key = ((u, v), left, right)
    cells[key] = (cells.get(key, 0) + value) % PRIME
    if cells[key] == 0:
        del cells[key]


def perfect_matchings(vertices):
    vertices = tuple(vertices)
    if not vertices:
        yield ()
        return
    first = vertices[0]
    for index in range(1, len(vertices)):
        second = vertices[index]
        rest = vertices[1:index] + vertices[index + 1:]
        for matching in perfect_matchings(rest):
            yield ((first, second),) + matching


def cofactor(cells, hole):
    vertices = tuple(site for site in SITES if site != hole)
    out = defaultdict(int)
    for matching in perfect_matchings(vertices):
        choices = []
        for edge in matching:
            entries = [
                (left, right, value)
                for (candidate, left, right), value in cells.items()
                if candidate == edge
            ]
            if not entries:
                break
            choices.append(entries)
        else:
            for selected in itertools.product(*choices):
                colours = {}
                coefficient = 1
                for edge, (left, right, value) in zip(matching, selected):
                    colours[edge[0]] = left
                    colours[edge[1]] = right
                    coefficient = coefficient * value % PRIME
                word = tuple(colours[site] for site in vertices)
                out[word] = (out[word] + coefficient) % PRIME
    return {word: value for word, value in out.items() if value}


def phi_columns(cells, with_projection=False):
    columns = []
    for hole, inserted_colour in LABELS:
        vertices = tuple(site for site in SITES if site != hole)
        column = {}
        for word, value in cofactor(cells, hole).items():
            colours = dict(zip(vertices, word))
            colours[hole] = inserted_colour
            row = WORD_INDEX[tuple(colours[site] for site in SITES)]
            column[row] = value
        if with_projection and inserted_colour == TARGET:
            column[len(WORDS) + hole] = 1
        columns.append(column)
    return columns


def reduce_column(column, pivots):
    column = dict(column)
    while column:
        row = min(column)
        if row not in pivots:
            break
        factor = column[row]
        for other_row, value in pivots[row].items():
            updated = (column.get(other_row, 0) - factor * value) % PRIME
            if updated:
                column[other_row] = updated
            else:
                column.pop(other_row, None)
    return column


def add_to_basis(column, pivots):
    column = reduce_column(column, pivots)
    if not column:
        return False
    row = min(column)
    scalar = inv(column[row])
    column = {other_row: value * scalar % PRIME
              for other_row, value in column.items()}
    pivots[row] = column
    return True


def kernel_basis(columns):
    # Eliminate outputs while tracking domain coefficients.  A zero output
    # yields one exact modular relation among the original columns.
    output_pivots = {}
    combo_pivots = {}
    relations = []
    for index, original in enumerate(columns):
        column = dict(original)
        combo = {index: 1}
        while column:
            row = min(column)
            if row not in output_pivots:
                scalar = inv(column[row])
                column = {r: v * scalar % PRIME for r, v in column.items()}
                combo = {r: v * scalar % PRIME for r, v in combo.items()}
                output_pivots[row] = column
                combo_pivots[row] = combo
                break
            factor = column[row]
            for r, value in output_pivots[row].items():
                updated = (column.get(r, 0) - factor * value) % PRIME
                if updated:
                    column[r] = updated
                else:
                    column.pop(r, None)
            for r, value in combo_pivots[row].items():
                updated = (combo.get(r, 0) - factor * value) % PRIME
                if updated:
                    combo[r] = updated
                else:
                    combo.pop(r, None)
        else:
            relations.append(combo)
    return relations


def vector_rows(vector):
    rows = defaultdict(dict)
    for index, value in vector.items():
        if value:
            site, colour = LABELS[index]
            rows[site][colour] = value
    return rows


def product_column(cells, p_index, n_vector, k_vector):
    x, p_colour = LABELS[p_index]
    n_rows = vector_rows(n_vector)
    k_rows = vector_rows(k_vector)
    out = defaultdict(int)
    for y, n_row in n_rows.items():
        for z, k_row in k_rows.items():
            if len({x, y, z}) < 3:
                continue
            edge = tuple(sorted(set(SITES) - {x, y, z}))
            for (candidate, left, right), edge_value in cells.items():
                if candidate != edge:
                    continue
                for n_colour, n_value in n_row.items():
                    for k_colour, k_value in k_row.items():
                        colours = {
                            x: p_colour,
                            y: n_colour,
                            z: k_colour,
                            edge[0]: left,
                            edge[1]: right,
                        }
                        row = WORD_INDEX[tuple(colours[site]
                                               for site in SITES)]
                        out[row] = (
                            out[row] + n_value * k_value * edge_value
                        ) % PRIME
    return {row: value for row, value in out.items() if value}


def pure(colour):
    return {WORD_INDEX[(colour,) * 5]: 1}


def classify(cells):
    phi = phi_columns(cells)
    phi_pivots = {}
    for column in phi:
        add_to_basis(column, phi_pivots)
    if reduce_column(pure(0), phi_pivots) or reduce_column(pure(1), phi_pivots):
        return None
    kernel = kernel_basis(phi)
    target_free = kernel_basis(phi_columns(cells, with_projection=True))
    residual_pivots = dict(phi_pivots)
    for p_index in range(len(LABELS)):
        for n_vector in target_free:
            for k_vector in kernel:
                add_to_basis(
                    product_column(cells, p_index, n_vector, k_vector),
                    residual_pivots,
                )
    return {
        "phi_rank": len(phi_pivots),
        "kernel_dim": len(kernel),
        "target_free_dim": len(target_free),
        "residual_rank": len(residual_pivots),
        "hit": not reduce_column(pure(TARGET), residual_pivots),
    }


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--added", type=int, default=2, choices=range(1, 7))
    parser.add_argument("--limit", type=int)
    parser.add_argument("--require-target-matching", action="store_true")
    args = parser.parse_args()
    cells = {}
    inv5 = inv(5)
    for u, v, colour, value in (
        (1, 2, 0, 3 * inv5),
        (0, 2, 0, 4 * inv5),
        (3, 4, 0, 1),
        (0, 1, 1, 1),
        (2, 3, 1, 1),
    ):
        add_cell(cells, u, v, colour, colour, value)
    all_cells = [
        ((u, v), left, right)
        for u, v in itertools.combinations(SITES, 2)
        for left, right in itertools.product(range(3), repeat=2)
    ]
    candidates = [key for key in all_cells if key not in cells]
    retained = 0
    hits = []
    profiles = defaultdict(int)
    total = 0
    for combination_index, selected in enumerate(
            itertools.combinations(candidates, args.added), 1):
        if args.limit is not None and combination_index > args.limit:
            break
        if args.require_target_matching:
            target_edges = {
                key[0] for key in selected
                if key[1:] == (TARGET, TARGET)
            }
            if not any(set(left).isdisjoint(right)
                       for left, right in itertools.combinations(target_edges, 2)):
                continue
        trial = dict(cells)
        for key in selected:
            add_cell(trial, *key[0], key[1], key[2], 1)
        result = classify(trial)
        total += 1
        if result is None:
            continue
        retained += 1
        profile = tuple(result[key] for key in (
            "phi_rank", "kernel_dim", "target_free_dim", "residual_rank"
        ))
        profiles[profile] += 1
        if result["hit"]:
            hits.append((selected, result))
            print("HIT", selected, result, flush=True)
        if combination_index % 5000 == 0:
            print("progress", combination_index, "retained", retained,
                  "hits", len(hits), flush=True)
    print("prime", PRIME)
    print("added", args.added)
    print("tested", total)
    print("retained", retained)
    print("profiles", sorted(profiles.items()))
    print("hits", hits)


if __name__ == "__main__":
    main()
