#!/usr/bin/env python3
"""Exact lazy completion search above the repaired orbit-40 boundary.

Let ``S+`` be the 28-cell diagonal orbit-40 support together with
``(0,2,0,0)`` and ``(1,3,0,0)``.  The two new cells turn one old binomial
into a trinomial, but ``S+`` has two mixed singleton fibres and its remaining
binomials are still Laurent-inconsistent.

This program searches over *all* 252 aggregate cells, with ``S+`` fixed.  It
adds only two kinds of sound lazy constraints:

* a currently singleton mixed term must acquire an actual distinct mate;
* if a set of currently binomial fibres has an odd Laurent dependency, then
  at least one of those fibres must acquire an actual third term (or one of
  the guarded pair terms must disappear).

Fibres with three or more terms are never capped.  Consequently ``UNSAT`` is
an exact exhaustive obstruction to a completion at the requested cell cap.
For a survivor, every remaining binomial is simultaneously solvable over the
complex torus.  The script then reduces every multi-term and pure polynomial
exactly in the signed quotient group algebra generated by those binomials.

The implementation deliberately uses only support variables.  The Laurent
test is over arbitrary nonzero complex weights, not merely ``+/-1`` signs.
"""

from __future__ import annotations

import argparse
from collections import Counter, defaultdict
from itertools import combinations, product

from pysat.card import CardEnc, EncType
from pysat.solvers import Solver

import search_n8_signed_binomial_lazy_cegar as signed
import search_n8_toric_binomial_lazy_cegar as toric_search
import search_parallel_binomial_nonzero_constants_cegar as toric
import verify_n8_toric_orbit40_boundary as boundary


N = 8
Q = 3


# First exact no-singleton completion found by the support-only mode at cap
# 46.  It is useful as a reproducible directed starting chart.  Its 224
# binomial fibres are inconsistent, so these cells alone are not a weighted
# solution.
NO_SINGLETON_46_EXTRA = frozenset({
    (1, 3, 0, 1), (1, 3, 0, 2), (1, 3, 1, 0), (1, 3, 1, 2),
    (1, 5, 0, 1), (1, 5, 1, 1), (1, 7, 2, 1), (2, 6, 2, 1),
    (3, 5, 0, 2), (3, 5, 1, 2), (3, 7, 0, 1), (3, 7, 0, 2),
    (3, 7, 1, 1), (3, 7, 1, 2), (3, 7, 2, 1), (5, 7, 1, 2),
})


def repaired_seed():
    return frozenset(
        set(boundary.boundary_support())
        | {(0, 2, 0, 0), (1, 3, 0, 0)}
    )


class CompletionSearch:
    """Lazy SAT model whose support projection is exactly no-singleton."""

    def __init__(self, cap, solver_name="cadical195", proof_prefix=None,
                 symmetry=True):
        self.pool = toric.Pool()
        self.cells = tuple(
            (u, v, a, b)
            for u, v in combinations(range(N), 2)
            for a, b in product(range(Q), repeat=2)
        )
        self.cell_index = {cell: i for i, cell in enumerate(self.cells)}
        self.support = {cell: self.pool.new() for cell in self.cells}
        self.matchings = tuple(toric.perfect_matchings(tuple(range(N))))
        self.seed = repaired_seed()
        assert len(self.cells) == 252
        assert len(self.matchings) == 105
        assert len(self.seed) == 30

        self.clauses = [[self.support[cell]] for cell in sorted(self.seed)]
        # These are exactly the four vertex automorphisms of the repaired
        # seed that preserve all three colour labels.  Lex leaders are a
        # pure search reduction: every completion orbit retains its least
        # support vector.
        self.automorphisms = (
            (0, 1, 2, 3, 4, 5, 6, 7),
            (1, 0, 3, 2, 5, 4, 7, 6),
            (2, 3, 0, 1, 6, 7, 4, 5),
            (3, 2, 1, 0, 7, 6, 5, 4),
        )
        if symmetry:
            variables = [self.support[cell] for cell in self.cells]
            for vertex_permutation in self.automorphisms[1:]:
                image_variables = [
                    self.support[signed.image_cell(
                        cell, vertex_permutation, tuple(range(Q))
                    )]
                    for cell in self.cells
                ]
                signed.add_lex_leader(
                    self.clauses, self.pool, variables, image_variables
                )
        if cap is not None:
            cardinality = CardEnc.atmost(
                lits=[self.support[cell] for cell in self.cells],
                bound=cap,
                top_id=self.pool.top,
                encoding=EncType.kmtotalizer,
            )
            self.pool.top = cardinality.nv
            self.clauses.extend(cardinality.clauses)

        self.all_clauses = [tuple(clause) for clause in self.clauses]
        self.proof_prefix = proof_prefix
        self.solver = Solver(
            name=solver_name,
            bootstrap_with=self.clauses,
            with_proof=proof_prefix is not None,
        )
        self.solver.set_phases([
            self.support[cell] if cell in self.seed else -self.support[cell]
            for cell in self.cells
        ])
        self._terms = {}
        self.singleton_gadgets = set()
        self.core_gadgets = set()
        self.extra_term_gadgets = {}

    def delete(self):
        self.solver.delete()

    def add_clauses(self, clauses):
        for clause in clauses:
            self.solver.add_clause(clause)
            self.all_clauses.append(tuple(clause))

    def terms(self, colouring):
        answer = self._terms.get(colouring)
        if answer is None:
            answer = tuple(
                tuple((u, v, colouring[u], colouring[v]) for u, v in matching)
                for matching in self.matchings
            )
            self._terms[colouring] = answer
        return answer

    def decode(self, model):
        positive = {literal for literal in model if literal > 0}
        return frozenset(
            cell for cell in self.cells if self.support[cell] in positive
        )

    def add_singleton_gadget(self, colouring, trigger_number):
        """If ``trigger`` occurs, one of the other 104 terms must occur."""

        key = colouring, trigger_number
        if key in self.singleton_gadgets:
            return 0, 0
        trigger = frozenset(self.terms(colouring)[trigger_number])
        selectors = []
        clauses = []
        old_top = self.pool.top
        for number, decorated in enumerate(self.terms(colouring)):
            if number == trigger_number:
                continue
            selector = self.pool.new()
            selectors.append(selector)
            for cell in frozenset(decorated) - trigger:
                clauses.append([-selector, self.support[cell]])
        clauses.append(
            [-self.support[cell] for cell in sorted(trigger)] + selectors
        )
        self.add_clauses(clauses)
        self.solver.set_phases([
            -variable for variable in range(old_top + 1, self.pool.top + 1)
        ])
        self.singleton_gadgets.add(key)
        return self.pool.top - old_top, len(clauses)

    def extra_term_variable(self, colouring, pair_numbers, pair_cells):
        """Shared one-way witness that a binomial fibre gains a third term."""

        key = colouring, tuple(sorted(pair_numbers))
        previous = self.extra_term_gadgets.get(key)
        if previous is not None:
            return previous

        extra = self.pool.new()
        selectors = []
        clauses = []
        old_top = self.pool.top
        for number, decorated in enumerate(self.terms(colouring)):
            if number in pair_numbers:
                continue
            selector = self.pool.new()
            selectors.append(selector)
            for cell in frozenset(decorated) - pair_cells:
                clauses.append([-selector, self.support[cell]])
        assert selectors
        clauses.append([-extra] + selectors)
        self.add_clauses(clauses)
        self.solver.set_phases([
            -variable for variable in range(old_top + 1, self.pool.top + 1)
        ])
        self.extra_term_gadgets[key] = extra
        return extra

    def add_core_break_gadget(self, mixed, row_indices):
        """Force an inconsistent binomial core to cease being binomial.

        The current two terms in every chosen fibre are guarded.  If all of
        them remain, an auxiliary selector must exhibit a third supported
        perfect matching in at least one chosen fibre.  The one-way selector
        implications are sufficient because the long clause is active only
        when every guarded pair term is present.
        """

        descriptions = []
        guard = set()
        for index in row_indices:
            colouring, present = mixed[index]
            assert len(present) == 2
            numbers = tuple(number for number, _decorated in present)
            pair_cells = frozenset(present[0][1]) | frozenset(present[1][1])
            guard.update(pair_cells)
            descriptions.append((colouring, numbers, pair_cells))
        key = tuple(sorted((colouring, numbers) for colouring, numbers, _ in descriptions))
        if key in self.core_gadgets:
            return 0, 0

        old_top = self.pool.top
        extras = []
        for colouring, pair_numbers, pair_cells in descriptions:
            extras.append(self.extra_term_variable(
                colouring, pair_numbers, pair_cells
            ))
        assert extras
        clauses = [
            [-self.support[cell] for cell in sorted(guard)] + extras
        ]
        self.add_clauses(clauses)
        self.solver.set_phases(
            [-variable for variable in range(old_top + 1, self.pool.top + 1)]
        )
        self.core_gadgets.add(key)
        return self.pool.top - old_top, len(clauses)

    def dump_proof(self):
        if self.proof_prefix is None:
            return None
        from pathlib import Path

        prefix = Path(self.proof_prefix)
        cnf_path = prefix.with_suffix(".cnf")
        drup_path = prefix.with_suffix(".drup")
        proof = self.solver.get_proof() or []
        additions = [line for line in proof if not line.startswith("d ")]
        # A portable DRUP trace must derive the empty clause.  Some backends
        # expose only a prefix through PySAT; reject such a trace rather than
        # silently publishing an incomplete certificate.
        if not additions or additions[-1].strip() != "0":
            raise RuntimeError(
                "solver proof trace does not end in the empty clause"
            )
        with cnf_path.open("w", encoding="ascii") as stream:
            stream.write(
                f"p cnf {self.pool.top} {len(self.all_clauses)}\n"
            )
            for clause in self.all_clauses:
                stream.write(" ".join(map(str, clause)) + " 0\n")
        with drup_path.open("w", encoding="ascii") as stream:
            for line in additions:
                stream.write(line.rstrip() + "\n")
        return cnf_path, drup_path, len(additions)


def exact_fibres(search, selected):
    return toric.exact_fibres(N, selected, search.matchings)


def binomial_system(search, fibres):
    mixed = []
    rows = []
    for colouring, terms in sorted(fibres.items()):
        if len(set(colouring)) == 1 or len(terms) != 2:
            continue
        mixed.append((colouring, terms))
        rows.append(toric.exponent_row(
            terms[0][1], terms[1][1], search.cell_index, len(search.cells)
        ))
    return mixed, rows


def reduced_polynomial(search, terms, lattice):
    """Reduce one matching polynomial in the signed quotient exactly."""

    coefficients = defaultdict(int)
    for _number, decorated in terms:
        exponent = toric.exponent_vector(
            decorated, search.cell_index, len(search.cells)
        )
        signed_key = toric.quotient_key(tuple(exponent) + (0,), lattice)
        sign = signed_key[-1]
        assert sign in (0, 1)
        coefficients[signed_key[:-1]] += -1 if sign else 1
    return {
        key: coefficient
        for key, coefficient in coefficients.items()
        if coefficient
    }


def quotient_audit(search, fibres, lattice):
    mixed_remainders = {}
    pure_remainders = {}
    for colouring, terms in sorted(fibres.items()):
        remainder = reduced_polynomial(search, terms, lattice)
        if len(set(colouring)) == 1:
            pure_remainders[colouring[0]] = remainder
        elif len(terms) != 2 and remainder:
            mixed_remainders[colouring] = remainder
    return mixed_remainders, pure_remainders


def seed_audit():
    """Return the exact advertised census and initial Laurent obstruction."""

    search = CompletionSearch(None)
    try:
        fibres = exact_fibres(search, search.seed)
        mixed_histogram = Counter(
            len(terms)
            for colouring, terms in fibres.items()
            if len(set(colouring)) > 1
        )
        assert mixed_histogram == {1: 2, 2: 51, 3: 1}
        mixed, rows = binomial_system(search, fibres)
        consistent, _lattice = toric.signed_quotient_lattice(
            rows, len(search.cells)
        )
        triangles = toric_search.unit_triangle_circuits(rows)
        assert not consistent
        assert len(triangles) == 136
        return fibres, mixed_histogram, len(triangles)
    finally:
        search.delete()


def run(cap, solver_name, max_rounds, core_batch, proof_prefix=None,
        symmetry=True, stop_no_singletons=False, preload_seed_cores=True,
        force_base46=False):
    if force_base46 and symmetry:
        raise ValueError("--base46 must be combined with --no-symmetry")
    search = CompletionSearch(cap, solver_name, proof_prefix, symmetry)
    try:
        if force_base46:
            search.add_clauses([
                [search.support[cell]]
                for cell in sorted(NO_SINGLETON_46_EXTRA)
            ])
            forced = search.seed | NO_SINGLETON_46_EXTRA
            search.solver.set_phases([
                search.support[cell] if cell in forced
                else -search.support[cell]
                for cell in search.cells
            ])
        if preload_seed_cores and not stop_no_singletons:
            seed_fibres = exact_fibres(search, search.seed)
            seed_mixed, seed_rows = binomial_system(search, seed_fibres)
            seed_triangles = toric_search.unit_triangle_circuits(seed_rows)
            assert len(seed_triangles) == 136
            for indices in seed_triangles:
                search.add_core_break_gadget(seed_mixed, indices)
            print(
                f"preloaded_seed_cores={len(seed_triangles)} "
                f"variables={search.pool.top} clauses={len(search.all_clauses)}",
                flush=True,
            )
        for round_number in range(max_rounds):
            if not search.solver.solve():
                proof = search.dump_proof()
                print(
                    f"UNSAT cap={cap} rounds={round_number} "
                    f"singleton_gadgets={len(search.singleton_gadgets)} "
                    f"core_gadgets={len(search.core_gadgets)} "
                    f"variables={search.pool.top} clauses={len(search.all_clauses)} "
                    f"proof={proof}",
                    flush=True,
                )
                return None

            selected = search.decode(search.solver.get_model())
            fibres = exact_fibres(search, selected)
            singletons = [
                (colouring, terms[0][0])
                for colouring, terms in sorted(fibres.items())
                if len(set(colouring)) > 1 and len(terms) == 1
            ]
            if singletons:
                added = 0
                for colouring, trigger in singletons:
                    if (colouring, trigger) in search.singleton_gadgets:
                        continue
                    search.add_singleton_gadget(colouring, trigger)
                    added += 1
                assert added
                if round_number < 20 or round_number % 20 == 0:
                    print(
                        f"round={round_number} cells={len(selected)} "
                        f"singletons={len(singletons)} add_singletons={added}",
                        flush=True,
                    )
                continue

            mixed, rows = binomial_system(search, fibres)
            consistent, lattice = toric.signed_quotient_lattice(
                rows, len(search.cells)
            )
            if stop_no_singletons:
                print(
                    f"NO_SINGLETON cap={cap} round={round_number} "
                    f"cells={len(selected)} binomials={len(rows)} "
                    f"binomial_consistent={consistent}",
                    flush=True,
                )
                print("EXTRA", sorted(selected - search.seed), flush=True)
                return selected, fibres, rows
            if not consistent:
                triangles = toric_search.unit_triangle_circuits(rows)
                if triangles:
                    new_cores = [
                        indices for indices in triangles
                        if tuple(sorted(
                            (mixed[index][0], tuple(
                                number for number, _ in mixed[index][1]
                            ))
                            for index in indices
                        )) not in search.core_gadgets
                    ]
                    chosen = new_cores[:core_batch]
                else:
                    relation = toric.flint_odd_relation(rows)
                    chosen = [tuple(
                        i for i, coefficient in enumerate(relation)
                        if coefficient
                    )] if relation is not None else [tuple(range(len(rows)))]
                assert chosen
                for indices in chosen:
                    search.add_core_break_gadget(mixed, indices)
                print(
                    f"round={round_number} cells={len(selected)} "
                    f"no_singletons binomials={len(rows)} "
                    f"inconsistent triangles={len(triangles)} "
                    f"add_cores={len(chosen)}",
                    flush=True,
                )
                print(
                    "INCONSISTENT_EXTRA",
                    sorted(selected - search.seed),
                    flush=True,
                )
                continue

            mixed_remainders, pure_remainders = quotient_audit(
                search, fibres, lattice
            )
            histogram = Counter(
                len(terms)
                for colouring, terms in fibres.items()
                if len(set(colouring)) > 1
            )
            print(
                f"SURVIVOR cap={cap} round={round_number} cells={len(selected)} "
                f"mixed_histogram={dict(sorted(histogram.items()))} "
                f"binomials={len(rows)} "
                f"nonzero_multi_remainders={len(mixed_remainders)} "
                f"pure_remainder_terms="
                f"{tuple(len(pure_remainders.get(c, {})) for c in range(Q))}",
                flush=True,
            )
            print("EXTRA", sorted(selected - search.seed), flush=True)
            for colouring, remainder in mixed_remainders.items():
                print(
                    f"  MIXED {colouring} terms={len(fibres[colouring])} "
                    f"reduced_terms={len(remainder)} coefficients="
                    f"{tuple(sorted(remainder.values()))}",
                    flush=True,
                )
            return selected, fibres, rows, lattice, mixed_remainders

        print(
            f"BOUNDARY cap={cap} max_rounds={max_rounds} "
            f"singleton_gadgets={len(search.singleton_gadgets)} "
            f"core_gadgets={len(search.core_gadgets)}",
            flush=True,
        )
        return "boundary"
    finally:
        search.delete()


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--cap", type=int, default=40)
    parser.add_argument("--solver", default="cadical195")
    parser.add_argument("--max-rounds", type=int, default=5000)
    parser.add_argument("--core-batch", type=int, default=64)
    parser.add_argument("--proof-prefix")
    parser.add_argument("--seed-audit", action="store_true")
    parser.add_argument("--no-symmetry", action="store_true")
    parser.add_argument("--stop-no-singletons", action="store_true")
    parser.add_argument("--no-preload-seed-cores", action="store_true")
    parser.add_argument("--base46", action="store_true")
    args = parser.parse_args()
    if args.seed_audit:
        _fibres, histogram, triangles = seed_audit()
        print(
            f"PASS seed cells=30 mixed_histogram={dict(sorted(histogram.items()))} "
            f"odd_unit_triangles={triangles}"
        )
        return
    run(
        args.cap, args.solver, args.max_rounds, args.core_batch,
        args.proof_prefix, not args.no_symmetry, args.stop_no_singletons,
        not args.no_preload_seed_cores,
        args.base46,
    )


if __name__ == "__main__":
    main()
