#!/usr/bin/env python3
"""Test the multihomogeneous degree-9 source-ideal certificate for n=6,q=3.

Let F_c be the matching coefficient for a coloring c of six vertices and let

    P = F_000000 F_111111 F_222222.

All polynomials are in the 135 entries x_uv(a,b).  If P belongs to the ideal
generated by the 726 mixed F_c, homogeneity and the vertex/color grading give
a certificate

    P = sum_c Q_c F_c,

where every monomial of Q_c uses, at each vertex, the two colors other than
c(v).  Such monomials are perfect matchings of the twelve complementary
colored stubs.  This script constructs the resulting Macaulay map after
taking invariants under S_6 x S_3.  Averaging is lossless in characteristic
zero because P and the ideal map are invariant.

No symbolic-polynomial package is needed: columns and rows are represented
as matchings of 12 and 18 colored stubs, respectively.
"""

from __future__ import annotations

import argparse
import itertools
import pickle
from collections import Counter
from pathlib import Path

import numpy as np


N = 6
Q = 3


def perfect_matchings(items: tuple[int, ...], forbid_same_vertex: bool = False):
    if not items:
        yield ()
        return
    a = items[0]
    for k in range(1, len(items)):
        b = items[k]
        if forbid_same_vertex and a // Q == b // Q:
            continue
        rest = items[1:k] + items[k + 1 :]
        for tail in perfect_matchings(rest, forbid_same_vertex):
            yield ((a, b),) + tail


VERTEX_PMS = tuple(perfect_matchings(tuple(range(N))))


VALID_EDGES = tuple(
    (a, b)
    for a in range(N * Q)
    for b in range(a + 1, N * Q)
    if a // Q != b // Q
)
EDGE_INDEX = {e: k for k, e in enumerate(VALID_EDGES)}


def edge_bit(a: int, b: int) -> int:
    if a > b:
        a, b = b, a
    return 1 << EDGE_INDEX[a, b]


def matching_code(pairs) -> int:
    z = 0
    for a, b in pairs:
        z |= edge_bit(a, b)
    return z


def bit_indices(z: int):
    while z:
        low = z & -z
        yield low.bit_length() - 1
        z ^= low


def transform_coloring(c, vertex_perm, color_perm):
    out = [None] * N
    for v in range(N):
        out[vertex_perm[v]] = color_perm[c[v]]
    return tuple(out)


def build_group_maps():
    actions = []
    for vp in itertools.permutations(range(N)):
        for cp in itertools.permutations(range(Q)):
            stub_map = tuple(3 * vp[v] + cp[a] for v in range(N) for a in range(Q))
            edge_map = []
            for a, b in VALID_EDGES:
                aa, bb = stub_map[a], stub_map[b]
                if aa > bb:
                    aa, bb = bb, aa
                edge_map.append(1 << EDGE_INDEX[aa, bb])
            actions.append((vp, cp, tuple(edge_map)))
    assert len(actions) == 4320
    return tuple(actions)


def transform_code(z: int, edge_map) -> int:
    out = 0
    for k in bit_indices(z):
        out |= edge_map[k]
    return out


def complement_matchings(c):
    stubs = tuple(3 * v + a for v in range(N) for a in range(Q) if a != c[v])
    return tuple(matching_code(m) for m in perfect_matchings(stubs, True))


def f_matching_code(c, pm):
    return matching_code((3 * u + c[u], 3 * v + c[v]) for u, v in pm)


def is_target_monomial(z: int) -> bool:
    for k in bit_indices(z):
        a, b = VALID_EDGES[k]
        if a % Q != b % Q:
            return False
    return True


COLOR_TYPES = (
    (0, 0, 0, 0, 0, 1),
    (0, 0, 0, 0, 1, 1),
    (0, 0, 0, 0, 1, 2),
    (0, 0, 0, 1, 1, 1),
    (0, 0, 0, 1, 1, 2),
    (0, 0, 1, 1, 2, 2),
)


def build_orbit_matrix(cache_path: Path | None = None):
    if cache_path and cache_path.exists():
        with cache_path.open("rb") as fh:
            data = pickle.load(fh)
        if data.get("version") == 2:
            return data
        print("ignoring an obsolete orbit cache")

    actions = build_group_maps()
    columns = []
    raw_rows = set()

    for c in COLOR_TYPES:
        comps = complement_matchings(c)
        assert len(comps) == 6040
        stabilizer = [
            edge_map
            for vp, cp, edge_map in actions
            if transform_coloring(c, vp, cp) == c
        ]
        unseen = set(comps)
        reps = []
        while unseen:
            z = next(iter(unseen))
            orb = {transform_code(z, em) for em in stabilizer}
            unseen.difference_update(orb)
            reps.append(min(orb))
        print(f"color type {c}: stabilizer={len(stabilizer)}, column orbits={len(reps)}")
        for z in reps:
            outputs = tuple(z | f_matching_code(c, pm) for pm in VERTEX_PMS)
            columns.append((c, z, outputs))
            raw_rows.update(outputs)

    # Canonicalize only rows that actually occur.  When an orbit is generated,
    # mark every encountered raw row in that orbit at once.
    row_canon = {}
    row_size = {}
    remaining = set(raw_rows)
    while remaining:
        z = next(iter(remaining))
        inds = tuple(bit_indices(z))
        orb = set()
        for _, _, em in actions:
            zz = 0
            for k in inds:
                zz |= em[k]
            orb.add(zz)
        can = min(orb)
        row_size[can] = len(orb)
        met = remaining.intersection(orb)
        for zz in met:
            row_canon[zz] = can
        remaining.difference_update(met)
        if len(row_size) % 250 == 0:
            print(f"row orbits={len(row_size)}, raw rows remaining={len(remaining)}")

    row_reps = tuple(sorted(row_size))
    row_idx = {z: k for k, z in enumerate(row_reps)}
    entries = []
    for j, (_, _, outputs) in enumerate(columns):
        counts = Counter(row_idx[row_canon[z]] for z in outputs)
        for i, a in counts.items():
            entries.append((i, j, a))

    b = np.zeros(len(row_reps), dtype=np.int64)
    for i, z in enumerate(row_reps):
        if is_target_monomial(z):
            b[i] = row_size[z]

    data = {
        "version": 2,
        "shape": (len(row_reps), len(columns)),
        "entries": entries,
        "b": b,
        "row_reps": row_reps,
        "row_sizes": tuple(row_size[z] for z in row_reps),
        "column_reps": tuple((c, z) for c, z, _ in columns),
    }
    print(
        f"matrix shape={data['shape']}, nnz={len(entries)}, "
        f"target row orbits={np.count_nonzero(b)}"
    )
    assert data["shape"] == (3102, 1314)
    assert len(entries) == 16343
    assert np.count_nonzero(b) == 8 and int(b.sum()) == 15**3
    assert all(4320 % z == 0 for z in data["row_sizes"])
    assert all(sum(a for _, jj, a in entries if jj == j) == 15 for j in range(len(columns)))
    if cache_path:
        with cache_path.open("wb") as fh:
            pickle.dump(data, fh, protocol=pickle.HIGHEST_PROTOCOL)
    return data


def koszul_kernel_rank(data, prime: int):
    """Rank Reynolds averages of the obvious monomial Koszul syzygies.

    If c(v),d(v),e(v) are distinct at every vertex and R is a perfect
    matching, then

        (R_e F_d) F_c - (R_e F_c) F_d = 0.

    We take one representative modulo S_6 x S_3 and project it to the
    invariant column coordinates.
    """
    if "column_reps" not in data:
        raise RuntimeError("cache predates column representatives; delete it and rerun")
    actions = build_group_maps()
    col_lookup = {pair: j for j, pair in enumerate(data["column_reps"])}
    type_set = set(COLOR_TYPES)
    to_type = {}

    def column_index(c, z):
        if c not in to_type:
            choices = []
            for vp, cp, em in actions:
                cc = transform_coloring(c, vp, cp)
                if cc in type_set:
                    choices.append((cc, em))
            assert choices and len({cc for cc, _ in choices}) == 1
            to_type[c] = choices
        cc = to_type[c][0][0]
        zz = min(transform_code(z, em) for _, em in to_type[c])
        return col_lookup[cc, zz]

    r0 = ((0, 1), (2, 3), (4, 5))
    r0_set = {tuple(sorted(e)) for e in r0}
    stabilizer = []
    for vp, cp, _ in actions:
        image = {tuple(sorted((vp[u], vp[v]))) for u, v in r0}
        if image == r0_set:
            stabilizer.append((vp, cp))
    assert len(stabilizer) == 288

    pairs = {
        (c, d)
        for c in itertools.product(range(Q), repeat=N)
        for d in itertools.product(range(Q), repeat=N)
        if all(c[v] != d[v] for v in range(N))
        and len(set(c)) > 1
        and len(set(d)) > 1
    }
    reps = []
    while pairs:
        c, d = next(iter(pairs))
        orb = {
            (transform_coloring(c, vp, cp), transform_coloring(d, vp, cp))
            for vp, cp in stabilizer
        }
        pairs.difference_update(orb)
        reps.append(min(orb))
    print(f"monomial Koszul orbits={len(reps)}")

    vectors = []
    for c, d in reps:
        e = tuple(3 - c[v] - d[v] for v in range(N))
        re = f_matching_code(e, r0)
        vec = Counter()
        for pm in VERTEX_PMS:
            vec[column_index(c, re | f_matching_code(d, pm))] += 1
            vec[column_index(d, re | f_matching_code(c, pm))] -= 1
        vec = {j: a for j, a in vec.items() if a}
        if vec:
            vectors.append(vec)

    # Audit the Reynolds-coordinate normalization over the integers, rather
    # than merely observing a modular kernel.
    col_images = [dict() for _ in range(data["shape"][1])]
    for i, j, a in data["entries"]:
        col_images[j][i] = a
    for k, vec in enumerate(vectors):
        image = Counter()
        for j, z in vec.items():
            for i, a in col_images[j].items():
                image[i] += z * a
        assert all(a == 0 for a in image.values()), k
    print(f"integer Koszul audits passed={len(vectors)}")

    # Row-echelon the syzygy vectors as vectors in the column-coordinate
    # space.  Modular independence certifies rational independence because
    # all displayed syzygies have integral coefficients.
    pivots = {}
    for vec0 in vectors:
        vec = {j: a % prime for j, a in vec0.items() if a % prime}
        while vec:
            j = min(vec)
            a = vec[j] % prime
            if j not in pivots:
                inv = pow(a, prime - 2, prime)
                pivots[j] = {k: z * inv % prime for k, z in vec.items() if z % prime}
                break
            p = pivots[j]
            for k, z in p.items():
                w = (vec.get(k, 0) - a * z) % prime
                if w:
                    vec[k] = w
                elif k in vec:
                    del vec[k]
    print(f"GF({prime}): invariant monomial-Koszul rank={len(pivots)}")
    return len(pivots)


def sparse_column_echelon(data, prime: int, save_dual: Path | None = None):
    """Incremental sparse elimination; returns whether b is in column span."""
    nr, nc = data["shape"]
    cols = [dict() for _ in range(nc)]
    for i, j, a in data["entries"]:
        cols[j][i] = a % prime

    # A pivot vector is normalized to 1 at its smallest-index nonzero row.
    pivots = {}

    def reduce_vec(v):
        while v:
            r = min(v)
            a = v[r] % prime
            if not a:
                del v[r]
                continue
            if r not in pivots:
                inv = pow(a, prime - 2, prime)
                for k in list(v):
                    z = v[k] * inv % prime
                    if z:
                        v[k] = z
                    else:
                        del v[k]
                return r
            p = pivots[r]
            for k, z in p.items():
                w = (v.get(k, 0) - a * z) % prime
                if w:
                    v[k] = w
                elif k in v:
                    del v[k]
        return None

    for j, v in enumerate(cols):
        r = reduce_vec(v)
        if r is not None:
            pivots[r] = v
        if (j + 1) % 250 == 0:
            print(f"columns {j+1}/{nc}: rank={len(pivots)}")

    rhs = {i: int(z % prime) for i, z in enumerate(data["b"]) if z % prime}
    residue = dict(rhs)
    r = reduce_vec(residue)
    in_span = r is None
    print(
        f"GF({prime}): rank(A)={len(pivots)}, "
        f"rank([A|b])={len(pivots) + (not in_span)}, in_span={in_span}"
    )
    if not in_span:
        support = sorted(residue.items())
        print(f"reduced rhs pivot={r}, residual support={len(support)}")
        # Construct the quotient-coordinate functional associated with the
        # first free row r.  Echelon pivot vectors have their pivot as their
        # least row, so backward substitution gives y with y^T A=0,
        # y[r]=1, and all other free coordinates zero.
        y = {r: 1}
        for s in sorted((s for s in pivots if s < r), reverse=True):
            val = 0
            for k, z in pivots[s].items():
                if k != s and k in y:
                    val = (val + z * y[k]) % prime
            if val:
                y[s] = (-val) % prime
        # Exact modular audit against the original sparse matrix.
        for j, col in enumerate(cols):
            assert sum(y.get(i, 0) * z for i, z in col.items()) % prime == 0, j
        pairing = sum(y.get(i, 0) * int(z) for i, z in enumerate(data["b"])) % prime
        assert pairing
        signed = [min(z, prime - z) for z in y.values()]
        print(
            f"dual witness: support={len(y)}, <y,b>={pairing}, "
            f"max signed residue={max(signed)}"
        )
        if save_dual:
            payload = {"prime": prime, "free_row": r, "y": y, "pairing": pairing}
            with save_dual.open("wb") as fh:
                pickle.dump(payload, fh, protocol=pickle.HIGHEST_PROTOCOL)
    return in_span


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--prime", type=int, default=1009)
    ap.add_argument("--save-dual", type=Path)
    ap.add_argument("--koszul", action="store_true")
    ap.add_argument(
        "--cache",
        type=Path,
        default=Path(__file__).with_name("degree9_source_ideal_orbits.pkl"),
    )
    args = ap.parse_args()
    data = build_orbit_matrix(args.cache)
    if args.koszul:
        koszul_kernel_rank(data, args.prime)
    ok = sparse_column_echelon(data, args.prime, args.save_dual)
    raise SystemExit(0 if ok else 1)


if __name__ == "__main__":
    main()
