#!/usr/bin/env python3
"""Test the degree-nine source ideal for the signed six-site Pfaffian map.

For a coloring c put

    G_c = sum_M pf_sign(M) product_(uv in M) x_uv(c_u,c_v).

This is the transversal principal Pfaffian of one alternating matrix on the
18 vertex/color modes.  If

    G_000000 G_111111 G_222222

belongs to the ideal generated by the 726 mixed G_c, then no alternating
bilinear six-site realization of ternary equality exists over any field of
characteristic zero.

The ordinary S_6 action twists every G_c by the sign character.  Restricting
to A_6 x S_3 makes both the map and target invariant, and Reynolds averaging
is lossless in characteristic zero.  Columns and rows are represented by
matchings of the complementary 12 stubs and all 18 stubs respectively.
"""

from __future__ import annotations

import argparse
import itertools
import pickle
from collections import Counter
from pathlib import Path

import numpy as np

from test_degree9_source_ideal import (
    COLOR_TYPES,
    EDGE_INDEX,
    N,
    Q,
    VALID_EDGES,
    VERTEX_PMS,
    bit_indices,
    complement_matchings,
    f_matching_code,
    is_target_monomial,
    sparse_column_echelon,
    transform_code,
    transform_coloring,
)


def permutation_sign(permutation):
    inversions = sum(
        permutation[i] > permutation[j]
        for i in range(len(permutation))
        for j in range(i + 1, len(permutation))
    )
    return -1 if inversions % 2 else 1


PF_SIGNS = tuple(permutation_sign(tuple(v for edge in matching for v in edge))
                 for matching in VERTEX_PMS)


def matching_sign(matching):
    crossings = sum(
        a < c < b < d or c < a < d < b
        for index, (a, b) in enumerate(matching)
        for c, d in matching[index + 1 :]
    )
    return -1 if crossings % 2 else 1


# Audit the compact permutation formula above against crossing parity.
assert PF_SIGNS == tuple(map(matching_sign, VERTEX_PMS))


def build_even_group_maps():
    actions = []
    for vertex_permutation in itertools.permutations(range(N)):
        if permutation_sign(vertex_permutation) < 0:
            continue
        for color_permutation in itertools.permutations(range(Q)):
            stub_map = tuple(
                Q * vertex_permutation[v] + color_permutation[a]
                for v in range(N)
                for a in range(Q)
            )
            edge_map = []
            for a, b in VALID_EDGES:
                aa, bb = stub_map[a], stub_map[b]
                if aa > bb:
                    aa, bb = bb, aa
                edge_map.append(1 << EDGE_INDEX[aa, bb])
            actions.append(
                (vertex_permutation, color_permutation, tuple(edge_map))
            )
    assert len(actions) == 2160
    return tuple(actions)


def target_coefficient(code):
    if not is_target_monomial(code):
        return 0
    matchings = [[] for _ in range(Q)]
    for edge_index in bit_indices(code):
        a, b = VALID_EDGES[edge_index]
        color = a % Q
        assert color == b % Q
        matchings[color].append((a // Q, b // Q))
    assert all(len(matching) == N // 2 for matching in matchings)
    answer = 1
    for matching in matchings:
        answer *= matching_sign(tuple(sorted(matching)))
    return answer


def build_orbit_matrix(cache_path: Path | None = None):
    if cache_path and cache_path.exists():
        with cache_path.open("rb") as handle:
            data = pickle.load(handle)
        if data.get("version") == 1:
            return data

    actions = build_even_group_maps()
    columns = []
    raw_rows = set()

    for coloring in COLOR_TYPES:
        complements = complement_matchings(coloring)
        stabilizer = [
            edge_map
            for vertex_permutation, color_permutation, edge_map in actions
            if transform_coloring(
                coloring, vertex_permutation, color_permutation
            )
            == coloring
        ]
        unseen = set(complements)
        representatives = []
        while unseen:
            code = next(iter(unseen))
            orbit = {transform_code(code, edge_map) for edge_map in stabilizer}
            unseen.difference_update(orbit)
            representatives.append(min(orbit))
        print(
            f"color type {coloring}: stabilizer={len(stabilizer)}, "
            f"column orbits={len(representatives)}",
            flush=True,
        )
        for code in representatives:
            outputs = tuple(
                (
                    code | f_matching_code(coloring, matching),
                    PF_SIGNS[index],
                )
                for index, matching in enumerate(VERTEX_PMS)
            )
            columns.append(outputs)
            raw_rows.update(output for output, _ in outputs)

    row_canonical = {}
    row_size = {}
    remaining = set(raw_rows)
    while remaining:
        code = next(iter(remaining))
        indices = tuple(bit_indices(code))
        orbit = set()
        for _, _, edge_map in actions:
            transformed = 0
            for index in indices:
                transformed |= edge_map[index]
            orbit.add(transformed)
        canonical = min(orbit)
        row_size[canonical] = len(orbit)
        met = remaining.intersection(orbit)
        for transformed in met:
            row_canonical[transformed] = canonical
        remaining.difference_update(met)
        if len(row_size) % 500 == 0:
            print(
                f"row orbits={len(row_size)}, raw rows remaining={len(remaining)}",
                flush=True,
            )

    row_representatives = tuple(sorted(row_size))
    row_index = {
        code: index for index, code in enumerate(row_representatives)
    }
    entries = []
    for column_index, outputs in enumerate(columns):
        counts = Counter()
        for output, coefficient in outputs:
            counts[row_index[row_canonical[output]]] += coefficient
        for index, coefficient in counts.items():
            if coefficient:
                entries.append((index, column_index, coefficient))

    target = np.zeros(len(row_representatives), dtype=np.int64)
    for index, code in enumerate(row_representatives):
        coefficient = target_coefficient(code)
        if coefficient:
            target[index] = coefficient * row_size[code]

    data = {
        "version": 1,
        "shape": (len(row_representatives), len(columns)),
        "entries": entries,
        "b": target,
        "row_reps": row_representatives,
        "row_sizes": tuple(row_size[code] for code in row_representatives),
    }
    print(
        f"matrix shape={data['shape']}, nnz={len(entries)}, "
        f"target row orbits={np.count_nonzero(target)}, "
        f"target mass={sum(abs(int(value)) for value in target)}",
        flush=True,
    )
    assert sum(abs(int(value)) for value in target) == 15**3
    if cache_path:
        with cache_path.open("wb") as handle:
            pickle.dump(data, handle, protocol=pickle.HIGHEST_PROTOCOL)
    return data


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--prime", type=int, default=1009)
    parser.add_argument(
        "--cache",
        type=Path,
        default=Path(__file__).with_name(
            "degree9_pfaffian_source_ideal_a6_orbits.pkl"
        ),
    )
    args = parser.parse_args()
    data = build_orbit_matrix(args.cache)
    in_span = sparse_column_echelon(data, args.prime)
    raise SystemExit(0 if in_span else 1)


if __name__ == "__main__":
    main()
