#!/usr/bin/env python3
r"""Literal two-chart/mapping-cone gate for the residual-q KS cell.

The five-row reduced-Eq/cap calculation uses the pure full-nine column r0.
That column is not a five-entry formal symbol: in every first repeated
P3+K2 component it has a 90-term literal matching boundary and at least 42
features private to its row/multiplier label.

This checker lifts the proposed four-corner correction to those literal
features.  The pq and pr chart copies have identical physical columns, so
their two-chart kernel is generated by pairwise differences.  A private
pivot forces the *sum* of the two chart coefficients to vanish.  The same
sum controls Eq/target/anchor, hence a second chart cannot cancel r0's
private boundary while retaining the r0 contribution needed by the cap
factorization.  The projected reduced-Eq column does not change this.

On the normalized Y=1 clean-C5 slice, the smallest possible positive datum
is one aggregate relative/mapping-cone cell M_v.  If alpha=-delta, its
literal image must contain +sum_j alpha_j B_j and +alpha_j on the four Eq
rows, where B_j is the complete 90-term boundary of the selected r0 label.
Together with sum_j alpha_j(-r0_j+T_j+rho_j), this cancels every literal
boundary and leaves residue alpha.  M_v must simultaneously carry the eta
and sigma terminal packet.  This is an exact image criterion, not a
construction of M_v.
"""

from __future__ import annotations

from collections import Counter, defaultdict
from fractions import Fraction as Q
from hashlib import sha256
import importlib.util
from itertools import combinations
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
EXPECTED_LEDGER_SHA256 = "b0ae90d59463a539a91c5226eace53d55bbeb385fc184af15ebca12cac36d6ff"
PINS = {
    "computations/verify_h3_rootless_c5_complete_multidegree_source_no_go.py":
        "719e48963faac5cd1dc5e7348de41e86f690f3046fefba88dddfa60bae532899",
    "computations/verify_h3_direct_free_complete_first_fine_degree_membership.py":
        "190171b72493e661dedb8e7aa369a9b72f1a71e14487632df2841ca7eeb19bf4",
    "computations/verify_h3_rootless_zero_anchor_collision_edge_source_obstruction.py":
        "8249604a56f7fc8ee8a3c66a33cb905eed6a02202c43ed81283e91c61d748180",
    "computations/verify_h3_residual_q_ks_standard_transport_graph_lock.py":
        "eede8aabd5c4740520ed13f1aacc897326a3a02573f860f5b2613c9df91fd53c",
    "computations/verify_h3_residual_q_eta_one_cell_fiber_product_gate.py":
        "4e84ad031b97ee67e1336c9a9d785acd3c581c2d80aeeb005d4eee784f91eccb",
    "computations/verify_h3_residual_q_physical_duality_interface_counterguard.py":
        "6f7fa68eb081a1dd3c3754cff5e1974e54c4df81c8ce6d36ffe8d37efba953ba",
    "computations/verify_h3_rootless_non_euler_90term_chart_h1_separator.py":
        "6b27d870a87e3f95d274c1cb1a5d785bf04a5d5f3c353d54a11bd231a3fe1950",
}

CORNERS = ("P+q00", "P-q00", "P+q11", "P-q11")
ALPHA = (Q(-1), Q(1), Q(1), Q(-1))  # required -delta
BASE_ROWS = tuple(
    f"{kind}_{corner}"
    for corner in CORNERS
    for kind in ("private", "Eq", "W", "target", "R")
) + ("ainc",)
TERMINAL_ROWS = tuple(f"eta{face}_constant" for face in range(1, 6)) + (
    "eta1_U1", "sigma_qpq22",
)
ROWS = BASE_ROWS + TERMINAL_ROWS


def require(condition: bool, message: object) -> None:
    if not condition:
        raise RuntimeError(message)


def load(relative: str, name: str):
    path = ROOT / relative
    spec = importlib.util.spec_from_file_location(name, path)
    require(spec is not None and spec.loader is not None,
            ("cannot import", relative))
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def pin_dependencies() -> None:
    for relative, expected in PINS.items():
        actual = sha256((ROOT / relative).read_bytes()).hexdigest()
        require(actual == expected,
                f"pinned dependency changed: {relative}: {actual}")


def add_sparse(*vectors):
    answer = defaultdict(Q)
    for vector in vectors:
        for key, value in vector.items():
            answer[key] += Q(value)
    return {key: value for key, value in answer.items() if value}


def scale_sparse(value, vector):
    value = Q(value)
    return {key: value * Q(entry) for key, entry in vector.items()
            if value * Q(entry)}


def vector(**entries) -> tuple[Q, ...]:
    require(set(entries) <= set(ROWS), ("unknown augmented row", entries))
    return tuple(Q(entries.get(row, 0)) for row in ROWS)


def add(*vectors: tuple[Q, ...]) -> tuple[Q, ...]:
    return tuple(sum(values, Q(0)) for values in zip(*vectors, strict=True))


def scale(value, source: tuple[Q, ...]) -> tuple[Q, ...]:
    return tuple(Q(value) * entry for entry in source)


def dot(left, right) -> Q:
    return sum((Q(a) * Q(b)
                for a, b in zip(left, right, strict=True)), Q(0))


def rank(columns: list[tuple[Q, ...]]) -> int:
    if not columns:
        return 0
    height = len(columns[0])
    require(all(len(column) == height for column in columns), "ragged matrix")
    work = [[Q(columns[column][row]) for column in range(len(columns))]
            for row in range(height)]
    pivot_row = 0
    for column in range(len(columns)):
        pivot = next((row for row in range(pivot_row, height)
                      if work[row][column]), None)
        if pivot is None:
            continue
        work[pivot_row], work[pivot] = work[pivot], work[pivot_row]
        value = work[pivot_row][column]
        work[pivot_row] = [entry / value for entry in work[pivot_row]]
        for row in range(height):
            if row == pivot_row or not work[row][column]:
                continue
            value = work[row][column]
            work[row] = [left - value * right for left, right in zip(
                work[row], work[pivot_row], strict=True
            )]
        pivot_row += 1
    return pivot_row


def in_span(columns, target) -> bool:
    return rank(list(columns)) == rank(list(columns) + [target])


def literal_two_chart_audit(complete, base) -> dict[str, object]:
    component_records = []
    selection_count = 0
    aggregate_supports = []
    aggregate_digests = []
    all_private_counts = []

    for component_index, (left_face, right_face, left_cell, _right_cell) in enumerate(
            complete.CUBIC_PAIRS):
        degree = complete.degree_add(
            base.lambda_degree(left_face),
            complete.cell_degree(complete.CYCLE_CELLS[left_cell]),
        )
        record = complete.component(base, degree)
        require(len(record["columns"]) == record["rank"] == 288
                and record["one_chart_kernel"] == 0,
                "one-chart complete component stopped being injective")
        require(record["two_chart_columns"] == 576
                and record["two_chart_rank"] == 288
                and record["two_chart_kernel"] == 288,
                "two-chart duplicate module changed")

        owners = defaultdict(list)
        for column_index, (_word, _multiplier, boundary) in enumerate(
                record["columns"]):
            for feature in boundary:
                owners[feature].append(column_index)
        pure_indices = [
            index for index, (word, _multiplier, _boundary) in enumerate(
                record["columns"])
            if word == complete.PURE_WORD
        ]
        require(len(pure_indices) == 6, "pure r0 label count changed")

        private_counts = []
        private_pivots = {}
        for index in pure_indices:
            boundary = record["columns"][index][2]
            private = [feature for feature in boundary
                       if owners[feature] == [index]]
            require(private, ("pure r0 lost private feature", component_index,
                              index))
            private_counts.append(len(private))
            private_pivots[index] = min(private)
        all_private_counts.extend(private_counts)

        # Audit all choices of four literal pure r0 labels.  The result does
        # not depend on identifying the four residual corners in advance.
        for selected in combinations(pure_indices, 4):
            boundaries = [
                {feature: Q(1) for feature in record["columns"][index][2]}
                for index in selected
            ]
            aggregate = add_sparse(*(
                scale_sparse(ALPHA[position], boundary)
                for position, boundary in enumerate(boundaries)
            ))
            pivots = [private_pivots[index] for index in selected]
            require(len(set(pivots)) == 4, "selected private pivots collided")
            require(all(aggregate[pivot] == ALPHA[position]
                        for position, pivot in enumerate(pivots)),
                    "literal alpha aggregate lost a forced private pivot")
            # pq and pr copies have the identical complete 90-term boundary.
            require(all(not add_sparse(boundary, scale_sparse(-1, boundary))
                        for boundary in boundaries),
                    "a pairwise chart difference acquired physical boundary")
            aggregate_supports.append(len(aggregate))
            aggregate_digests.append(sha256(repr(sorted(
                aggregate.items(), key=lambda item: repr(item[0])
            )).encode()).hexdigest())
            selection_count += 1

        component_records.append({
            "component": component_index,
            "faces": [left_face, right_face],
            "columns_per_chart": len(record["columns"]),
            "one_chart_rank_kernel": [record["rank"],
                                      record["one_chart_kernel"]],
            "two_chart_columns_rank_kernel": [
                record["two_chart_columns"], record["two_chart_rank"],
                record["two_chart_kernel"],
            ],
            "pure_r0_labels": len(pure_indices),
            "private_features_per_pure_r0_min_max": [
                min(private_counts), max(private_counts)
            ],
            "four_label_selections": 15,
        })

    require(selection_count == 5 * 15,
            "complete four-label selection count changed")
    require(min(all_private_counts) >= 42,
            "literal pure r0 private-pivot margin changed")
    return {
        "components": component_records,
        "four_corner_selections_checked": selection_count,
        "minimum_private_features_per_literal_pure_r0":
            min(all_private_counts),
        "literal_alpha_aggregate_support_min_max": [
            min(aggregate_supports), max(aggregate_supports)
        ],
        "distinct_literal_alpha_aggregate_digests":
            len(set(aggregate_digests)),
        "two_chart_boundary_map": "[B B] on every row/multiplier label",
        "two_chart_kernel": "pairwise pq-pr differences",
        "private_pivot_equation": "x_pq+x_pr=0 labelwise",
    }


def augmented_private_pivot_no_go() -> dict[str, object]:
    columns = []
    names = []
    per_corner = {}
    for corner in CORNERS:
        r0 = vector(**{
            f"private_{corner}": 1,
            f"Eq_{corner}": 1,
            f"target_{corner}": 1,
            "ainc": -1,
        })
        target_cap = vector(**{
            f"W_{corner}": -1,
            f"target_{corner}": 1,
        })
        residue_cap = vector(**{
            f"W_{corner}": 1,
            f"R_{corner}": 1,
        })
        projected_reduced_eq = vector(**{f"Eq_{corner}": -1})
        per_corner[corner] = {
            "r0_pq": r0,
            "r0_pr": r0,
            "T": target_cap,
            "rho": residue_cap,
            "C_projected": projected_reduced_eq,
        }
        for name, column in per_corner[corner].items():
            names.append(f"{name}:{corner}")
            columns.append(column)

    desired_residue_only = vector(**{
        f"R_{corner}": ALPHA[index]
        for index, corner in enumerate(CORNERS)
    })
    require(not in_span(columns, desired_residue_only),
            "second chart plus projected C supplied the literal correction")

    separators = []
    for index, corner in enumerate(CORNERS):
        phi = vector(**{
            f"private_{corner}": 1,
            f"W_{corner}": -1,
            f"target_{corner}": -1,
            f"R_{corner}": 1,
        })
        require(all(dot(phi, column) == 0 for column in columns),
                ("private separator stopped killing old columns", corner))
        require(dot(phi, desired_residue_only) == ALPHA[index],
                "private separator stopped detecting -delta")
        separators.append(phi)

    # The literal reduced-Eq cell must carry the negative complete r0
    # boundary as well as -Eq.  Four copies would suffice, but one aggregate
    # mapping-cone generator can carry their forced alpha combination.
    literal_c = {
        corner: vector(**{
            f"private_{corner}": -1,
            f"Eq_{corner}": -1,
        })
        for corner in CORNERS
    }
    old_aggregate = add(*(
        scale(ALPHA[index], add(
            scale(-1, per_corner[corner]["r0_pq"]),
            per_corner[corner]["T"],
            per_corner[corner]["rho"],
        ))
        for index, corner in enumerate(CORNERS)
    ))

    terminal_packet = {
        **{f"eta{face}_constant": 1 for face in range(1, 6)},
        "eta1_U1": 1,
        "sigma_qpq22": -1,
    }
    desired_full = add(desired_residue_only, vector(**terminal_packet))
    mapping_cone = add(
        *(
            scale(-ALPHA[index], literal_c[corner])
            for index, corner in enumerate(CORNERS)
        ),
        vector(**terminal_packet),
    )
    require(add(old_aggregate, mapping_cone) == desired_full,
            "literal mapping-cone criterion stopped landing at the fiber target")
    require(all(old_aggregate[ROWS.index(f"private_{corner}")]
                == -ALPHA[index]
                and mapping_cone[ROWS.index(f"private_{corner}")]
                == ALPHA[index]
                and old_aggregate[ROWS.index(f"Eq_{corner}")]
                == -ALPHA[index]
                and mapping_cone[ROWS.index(f"Eq_{corner}")]
                == ALPHA[index]
                for index, corner in enumerate(CORNERS)),
            "private/Eq mapping-cone signs changed")
    require(sum(old_aggregate[ROWS.index("ainc")] for _ in (0,)) == 0,
            "four-corner old cap aggregate retained anchor incidence")

    available_rank = rank(columns)
    require(rank(columns + [mapping_cone]) == available_rank + 1,
            "one literal mapping-cone column stopped giving the rank jump")
    require(in_span(columns + [mapping_cone], desired_full),
            "mapping-cone extension stopped containing the desired fiber target")

    return {
        "row_model": (
            "one actual private-pivot coordinate plus separately labelled "
            "Eq/W/target/residue rows at each of the four literal corners, "
            "total physical anchor incidence, and eta/sigma terminal rows"
        ),
        "available_column_count": len(columns),
        "available_rank": available_rank,
        "desired_residue_only_in_two_chart_plus_projected_C_span": False,
        "primitive_private_separators": [
            {
                "corner": corner,
                "formula": "private-W-target+R",
                "pairing": int(ALPHA[index]),
            }
            for index, corner in enumerate(CORNERS)
        ],
        "old_cap_aggregate": {
            "formula": "sum_j alpha_j*(-r0_j+T_j+rho_j)",
            "literal_private_coefficients": [int(-value) for value in ALPHA],
            "Eq_coefficients": [int(-value) for value in ALPHA],
            "residue_coefficients": [int(value) for value in ALPHA],
            "W_target_ainc": [0, 0, 0],
        },
        "smallest_literal_mapping_cone_image": {
            "literal_full_nine_boundary": "sum_j alpha_j*B_j",
            "Eq_coefficients": [int(value) for value in ALPHA],
            "ordinary_residue": [0, 0, 0, 0],
            "D_W_target_ainc": [0, 0, 0, 0],
            "eta_z": "1+delta_(1,z)*u_z/t",
            "sigma": "-q_pq^22",
        },
        "with_one_mapping_cone_column_rank": available_rank + 1,
        "desired_full_fiber_target_in_extended_span": True,
        "number_of_new_generators_forced": 1,
        "why_not_four": (
            "four cornerwise literal C_j cells would work, but their fixed "
            "alpha combination is one augmented image vector; current rank "
            "forces one new direction, not four independent directions"
        ),
    }


def chart_terminal_audit(non_euler, eta_gate, graph, physical) -> dict[str, object]:
    chart, chart_digest = non_euler.audit()
    require(chart_digest == non_euler.EXPECTED_DIGEST,
            "non-Euler chart-H1 ledger changed")
    require(chart["primitive_kernel_source_boundary"] == 0
            and chart["primitive_kernel_target"] == [0, 0, 0]
            and not any(chart["primitive_kernel_ordinary_residue"]),
            "literal chart H1 stopped being physically invisible")
    require(chart["marked_readout_on_correction_h1"] == [1, 1]
            and not chart["zero_indeterminate"],
            "known chart-odd marked terminal changed")

    fiber = eta_gate.one_cell_fiber_product(graph, physical)
    require(fiber["residual_projection"]["full_four_corner_value"]
            == [-1, 1, 1, -1]
            and fiber["terminal_projection_on_face_1"]["sigma_qpq22"] == -1
            and not fiber["physical_image_membership_proved"],
            "residual/eta/sigma fiber target changed")

    return {
        "pairwise_chart_difference_physical_boundary": 0,
        "pairwise_chart_difference_W_target_ores_ainc": [0, 0, 0, 0],
        "chart_neutral_physical_terminal_on_pairwise_difference": 0,
        "reason": (
            "a chart-neutral terminal factors through the identical physical "
            "column, so it depends on x_pq+x_pr and kills pq-pr"
        ),
        "known_chart_odd_exception": {
            "non_Euler_marked_readout": 1,
            "descends_to_physical_terminal": False,
            "meaning": (
                "a nonzero value on pq-pr is presentation H1 and itself "
                "requires a higher comparison; it is not the eta/sigma law"
            ),
        },
        "required_physical_terminal": {
            "eta_z": "1+delta_(1,z)*u_z/t",
            "sigma_qpq22": -1,
        },
        "second_chart_supplies_required_terminal": False,
        "mapping_cone_criterion": (
            "a new relative cell M_1 must have the full literal private/Eq "
            "image and the residual/eta/sigma fiber value simultaneously; "
            "membership of that vector in the complete physical relative "
            "source image is still open"
        ),
    }


def audit() -> tuple[dict[str, object], str]:
    pin_dependencies()
    complete = load(
        "computations/verify_h3_rootless_c5_complete_multidegree_source_no_go.py",
        "literal_ks_complete_multidegree",
    )
    base = load(
        "computations/verify_h3_direct_free_complete_first_fine_degree_membership.py",
        "literal_ks_complete_base",
    )
    non_euler = load(
        "computations/verify_h3_rootless_non_euler_90term_chart_h1_separator.py",
        "literal_ks_chart_h1",
    )
    eta_gate = load(
        "computations/verify_h3_residual_q_eta_one_cell_fiber_product_gate.py",
        "literal_ks_eta_fiber",
    )
    graph = load(
        "computations/verify_h3_residual_q_ks_standard_transport_graph_lock.py",
        "literal_ks_graph",
    )
    physical = load(
        "computations/verify_h3_residual_q_physical_duality_interface_counterguard.py",
        "literal_ks_physical",
    )

    ledger = {
        "theorem": "literal residual-q private-boundary mapping-cone gate",
        "normalization_scope": (
            "marked clean-C5 slice with cap normalization Y=1; for general "
            "Y the coefficients must be rederived before this criterion is used"
        ),
        "complete_literal_two_chart_module":
            literal_two_chart_audit(complete, base),
        "private_pivot_no_go_and_minimal_cell":
            augmented_private_pivot_no_go(),
        "chart_and_physical_terminal":
            chart_terminal_audit(non_euler, eta_gate, graph, physical),
        "verdict": (
            "the complete second chart adds only pairwise presentation-kernel "
            "differences and cannot cancel a private full-nine pivot while "
            "retaining the r0 cap contribution.  A projected reduced-Eq face "
            "still fails.  The first sufficient new datum is one literal "
            "relative/mapping-cone image carrying the forced four-corner "
            "full-nine boundary, the opposite Eq aggregate, and the eta/sigma "
            "terminal packet; its physical source membership remains open"
        ),
    }
    digest = sha256(json.dumps(
        ledger, sort_keys=True, separators=(",", ":")
    ).encode()).hexdigest()
    if EXPECTED_LEDGER_SHA256 != "TO_BE_PINNED":
        require(digest == EXPECTED_LEDGER_SHA256,
                ("ledger digest changed", digest, ledger))
    return ledger, digest


def main() -> None:
    _ledger, digest = audit()
    print("h=3 residual-q literal private-boundary mapping cone: SHARP GATE")
    print("complete second chart cancels private pivots compatibly: NO")
    print("projected reduced-Eq face repairs literal module: NO")
    print("smallest sufficient extension: one full literal mapping-cone image")
    print("physical image membership: OPEN")
    print("ledger sha256:", digest)


if __name__ == "__main__":
    main()
