#!/usr/bin/env python3
"""Build the strongest executable/source-derived ``Gen_phys(Gamma_*)`` closure.

The old 17-record operation census was a declared vocabulary.  Here the base
registry is rebuilt by calling the actual constructors used by
``verify_h3_gamma_star_executable_gen_phys_registry``.  We then adjoin only
one canonical source-derived enlargement: the relative Koszul/Tate cell for
the two actual equations ``F=H0-u`` and ``Q=Eq``.  The centered response KS
generator is already an executable registry entry.

The resulting typed operation graph is disconnected between the response and
cap objects.  Consequently its free cellular/DGA closure has no
operation-changing degree-one cell at Gamma_*.  If the single missing
degree-zero comparison schema ``Phi_KS,r0`` is adjoined, the standard
naturality/interchange construction produces exactly eight mixed cells, one
for each one-root neighbour of 0112.  Their strict Leibniz boundaries have
tied private/reduced-Eq coefficients and hence zero Psi charge.

This is an exact positive census for the source-derived free closure, not a
proof that the unwritten full physical complex is that closure.  The smallest
remaining exotic extension is an independently primitive element of
Hom^1(response,cap) at Gamma_*; one such primitive raises the quotient rank
from eight to nine.  Thus the first missing presentation datum is precisely
whether that primitive Hom^1 slot is zero (or generated by the eight standard
interchanges), not another higher-syzygy or Tate face.
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from fractions import Fraction as Q
from hashlib import sha256
import importlib.util
import json
from pathlib import Path
import sys


ROOT = Path(__file__).resolve().parents[1]
PINS = {
    "computations/verify_h3_gamma_star_executable_gen_phys_registry.py":
        "173ebdedcfdadd9891704223ea93731509c18a4d120aa34d6c7bc8a4f3aebddb",
    "computations/verify_h3_universal_response_deformation_e14_orbit_ks_gate.py":
        "39713f3683dd3d2376e5a911987ee3670ec291cf850072d6b4932e7a93745fc7",
    "computations/verify_h3_reduced_eq_koszul_tate_relative_orbit_gate.py":
        "15b47a420a6f1e2e6eb0b89e5e5efb5c895172e30b8ab9339dfa1e451ac03668",
    "computations/verify_h3_response_ks_to_cap_r0_multiplicative_comparison_gate.py":
        "02a28ec54b83b2f786e47b0fdc992f5f28dd95a04ba16219f0e24482d4999097",
    "computations/verify_h3_kappa_lambda_literal_mapping_cone_normalization_gate.py":
        "b60538f9db5b8c2984bbee95e0a05f383408e9ab7c13680216adf56386682522",
    "computations/verify_h3_gamma_star_source_operation_essential_surjectivity_census.py":
        "e5f2664b99c5ba58e0be385ca52dc52c6d2f6d6d0b793e655ebe297542dce291",
}
EXPECTED_LEDGER_SHA256 = "d81dbee5add84bfc72633447b0ada4406b103e7f1f4b6f7dbeeac676ec15b2e4"

LOWER_PARENT = tuple(map(int, "0112"))
KAPPA_WORDS = (
    "0012", "0102", "0110", "0111",
    "0122", "0212", "1112", "2112",
)
DELTA = tuple(map(Q, (1, 1, -1, -1)))
ZERO4 = (Q(0),) * 4


def require(condition: bool, detail: object) -> None:
    if not condition:
        raise RuntimeError(detail)


def load(relative: str, name: str):
    specification = importlib.util.spec_from_file_location(name, ROOT / relative)
    require(specification is not None and specification.loader is not None,
            ("cannot import", relative))
    module = importlib.util.module_from_spec(specification)
    sys.modules[name] = module
    specification.loader.exec_module(module)
    return module


def pin_dependencies() -> None:
    for relative, expected in PINS.items():
        actual = sha256((ROOT / relative).read_bytes()).hexdigest()
        require(actual == expected,
                ("pinned dependency changed", relative, actual, expected))


def dot(left, right) -> Q:
    require(len(left) == len(right), "dot width")
    return sum((Q(a) * Q(b)
                for a, b in zip(left, right, strict=True)), Q(0))


def rank(columns) -> int:
    columns = tuple(tuple(map(Q, column)) for column in columns)
    if not columns:
        return 0
    height = len(columns[0])
    require(all(len(column) == height for column in columns), "rank height")
    rows = [[columns[column][row] for column in range(len(columns))]
            for row in range(height)]
    answer = 0
    for column in range(len(columns)):
        pivot = next((row for row in range(answer, height)
                      if rows[row][column]), None)
        if pivot is None:
            continue
        rows[answer], rows[pivot] = rows[pivot], rows[answer]
        value = rows[answer][column]
        rows[answer] = [entry / value for entry in rows[answer]]
        for row in range(height):
            if row == answer or not rows[row][column]:
                continue
            value = rows[row][column]
            rows[row] = [left - value * right for left, right in
                         zip(rows[row], rows[answer], strict=True)]
        answer += 1
    return answer


@dataclass(frozen=True)
class TypedAtom:
    name: str
    source: str
    target: str
    relative_degree: int
    status: str


def executable_registry_audit(executable) -> tuple[dict[str, object], object]:
    # Rebuild the registry from the actual callable constructors.  This is
    # intentionally not reconstructed from the old ledger counts.
    maximal = executable.load(
        "computations/verify_h3_maximal_pointed_balanced_same_grade_terminal_gate.py",
        "source_derived_maximal",
    )
    private_eq = executable.load(
        "computations/verify_h3_balanced_square_private_eq_projection_gate.py",
        "source_derived_private_eq",
    )
    fixed_window = executable.load(
        "computations/verify_h3_fixed_window_centered_k22_physical_routing_gate.py",
        "source_derived_window",
    )
    response = executable.load(
        "computations/verify_h3_universal_response_deformation_e14_orbit_ks_gate.py",
        "source_derived_response",
    )
    first_pp = executable.load(
        "computations/verify_h3_centered_projector_literal_first_hasse_eq_incidence_gate.py",
        "source_derived_first_pp",
    )
    bar_keq = executable.load(
        "computations/verify_h3_relative_gl3_bar_keq_kappa_normalization_gate.py",
        "source_derived_bar_keq",
    )
    provenance = executable.load(
        "computations/verify_h3_uc4_beq_tie_source_provenance_audit.py",
        "source_derived_provenance",
    )
    registry = executable.build_registry(
        maximal, private_eq, fixed_window, response, first_pp, bar_keq,
        provenance,
    )
    registered = executable.registry_audit(registry, private_eq)
    require(registered["implemented_primitive_count"] == 128
            and registered["Gamma_star_entries"] == 25
            and registered["literal_kappa_columns"] == 0,
            registered)

    atoms = []
    for entry in registry.entries:
        if entry.name.startswith("cap:") or entry.name.startswith("macaulay:"):
            source = target = "cap"
        elif entry.name.startswith("response:"):
            source = target = "response"
        elif entry.name.startswith("window:"):
            source = target = "window"
        elif entry.name.startswith("bar_keq:"):
            source = target = "bar"
        else:
            raise RuntimeError(("untyped executable entry", entry.name))
        atoms.append(TypedAtom(entry.name, source, target, entry.degree,
                               "implemented"))
    require(len(atoms) == 128
            and not any(atom.source != atom.target for atom in atoms),
            "an executable primitive changed operation object")
    return {
        "constructor_invocations": len(atoms),
        "literal_Gamma_entries": registered["Gamma_star_entries"],
        "Gamma_image_rank": registered["Gamma_star_image_rank"],
        "B_Eq_image_rank": registered["B_Eq_image_rank"],
        "Psi_charge_histogram": registered["Psi_charge_histogram"],
        "operation_object_counts": {
            name: sum(atom.source == name for atom in atoms)
            for name in ("response", "cap", "window", "bar")
        },
        "implemented_operation_changing_atoms": 0,
        "literal_kappa_columns": 0,
    }, registry


def source_derived_relative_audit(response, tate) -> dict[str, object]:
    response_data = response.universal_centered_ks_audit()
    koszul = tate.absolute_koszul_audit()
    require(response_data["KS_rank"] == 89
            and response_data["relative_class_modulo_R"] == "-c_f, c_f=N*f-R"
            and koszul["degree_two_cell"] == "theta=eps_F wedge eps_Q"
            and koszul["relative_boundary"] == "dC_K=-F e_Eq",
            (response_data, koszul))
    return {
        "response_relative_atom": {
            "name": "epsilon_s",
            "construction": "monic centered response deformation",
            "operation_type": "response->response",
            "relative_degree": 1,
            "rank": response_data["KS_rank"],
        },
        "Eq_relative_atom": {
            "name": "C_K=-theta",
            "construction": "Koszul cell of actual equations F=H0-u,Q=Eq",
            "absolute_degree": 2,
            "relative_degree_after_Q_base_change": 1,
            "operation_type": "cap->cap (objectwise K_Eq)",
            "boundary": koszul["relative_boundary"],
            "physical_augmented_placement_constructed": False,
        },
        "operation_changing_atom_created_by_relative_shift": False,
        "consequence": (
            "the canonical Tate enlargement adds an objectwise cap atom; "
            "it does not create Hom(response,cap)"
        ),
    }


def one_root_words() -> tuple[str, ...]:
    words = []
    for site, old_colour in enumerate(LOWER_PARENT):
        for colour in range(3):
            if colour == old_colour:
                continue
            value = list(LOWER_PARENT)
            value[site] = colour
            words.append("".join(map(str, value)))
    return tuple(sorted(words))


def typed_free_closure_audit(comparison) -> dict[str, object]:
    ledger, digest = comparison.audit()
    require(digest == comparison.EXPECTED_LEDGER_SHA256, digest)
    hom = ledger["literal_idempotent_Hom"]
    require(hom["Hom_degree0_response_to_cap_in_current_grammar"] == 0
            and not hom["standard_mapping_cylinder_can_create_missing_input_map"],
            hom)

    # Identities and objectwise arrows cannot change a connected component.
    objects = ("response", "cap", "window", "bar")
    reachable = {(value, value) for value in objects}
    for _ in range(len(objects)):
        reachable |= {
            (left_source, right_target)
            for left_source, left_target in tuple(reachable)
            for right_source, right_target in tuple(reachable)
            if left_target == right_source
        }
    require(("response", "cap") not in reachable
            and reachable == {(value, value) for value in objects},
            reachable)
    return {
        "objects": list(objects),
        "degree_zero_reachability": [list(pair) for pair in sorted(reachable)],
        "Hom0_response_cap_dimension": 0,
        "free_closure_operation_changing_C1_count": 0,
        "mapping_cylinder_on_epsilon_s_r0": "MissingPhysicalArrow",
        "first_missing_degree_zero_datum": (
            "Phi_KS,r0: response KS -> cap AugP2/K_Eq"
        ),
    }


def normalized_completion_audit(normalization) -> dict[str, object]:
    ledger, digest = normalization.audit()
    require(digest == normalization.EXPECTED_LEDGER_SHA256, digest)
    standard = ledger["representative"]
    require(standard["normalized_charge"] == 0
            and standard["coefficientwise_result"] ==
                "Pi_BEq(d kappa_std)=(v,v)", standard)
    words = one_root_words()
    require(words == KAPPA_WORDS, words)

    # Use all four signless K2,2 edges twice.  The precise root label changes
    # the word idempotent, but every strict product has the same tied B/Eq
    # form and is killed by Psi.
    edges = tuple(
        tuple(Q(1 if index in (left, right) else 0) for index in range(4))
        for left in (0, 1) for right in (2, 3)
    )
    boundaries = tuple(edges[index % 4] + edges[index % 4]
                       for index in range(8))
    psi = DELTA + tuple(-value for value in DELTA)
    require(all(dot(psi, boundary) == 0 for boundary in boundaries),
            "a strict kappa became bright")
    quotient_basis = tuple(
        tuple(Q(1 if row == column else 0) for row in range(8))
        for column in range(8)
    )
    require(rank(quotient_basis) == 8, "kappa word idempotents collapsed")
    return {
        "granted_schema": "one normalized source-labelled Phi_KS,r0 family",
        "pairwise_feature_truth_table": {
            "word=0,Eq=0": "canonical/local",
            "word=1,Eq=0": "cross-word cylinder, dark",
            "word=0,Eq=1": "objectwise K_Eq, dark",
            "word=1,Eq=1": "standard kappa interchange",
        },
        "literal_words": list(words),
        "standard_operation_changing_C1_count": len(words),
        "quotient_rank": rank(quotient_basis),
        "strict_boundaries": "(v_i,v_i) in (B,Eq)",
        "Psi_charges": [str(dot(psi, boundary)) for boundary in boundaries],
        "higher_Tate_face_adds_new_type": False,
        "reason": (
            "the only canonical cone-shifted Tate atom is objectwise K_Eq; "
            "its interchange with Phi is already kappa"
        ),
    }


def exotic_search_audit() -> dict[str, object]:
    # The smallest possible independent operation-changing atom has the same
    # complete Gamma tag as one kappa but a new generator identity.  Give it
    # primitive private boundary delta and zero Eq/external rows.  This is an
    # admissible presentation extension, not an asserted physical operation.
    psi = DELTA + tuple(-value for value in DELTA)
    exotic_boundary = DELTA + ZERO4
    tied = tuple(
        tuple(Q(1 if row == column else 0) for row in range(8))
        for column in range(8)
    )
    extended = tuple(column + (Q(0),) for column in tied) + (
        (Q(0),) * 8 + (Q(1),),
    )
    require(dot(psi, exotic_boundary) == 4
            and rank(tied) == 8
            and rank(extended) == 9,
            "the minimal exotic control changed")
    return {
        "search_space": (
            "independently primitive total-degree-one atoms with source "
            "response, target cap, and the complete Gamma_* tag"
        ),
        "found_in_executable_constructor_closure": 0,
        "smallest_unexcluded_extension": {
            "name": "omega_0102",
            "operation_type": "response->cap",
            "relative_degree": 1,
            "canonical_shadow": 0,
            "B_Eq_boundary": "(delta,0)",
            "all_external_rows": 0,
            "chi": 4,
            "quotient_rank_effect": "8->9",
            "source_provenant_operation_asserted": False,
        },
        "first_missing_presentation_datum": (
            "an exhaustive declaration/theorem for primitive "
            "Hom^1_Gamma*(response,cap): it must be zero modulo the eight "
            "standard kappa interchanges, or list an additional constructor"
        ),
        "ordinary_higher_syzygy_loophole": False,
        "canonical_relative_Tate_loophole": False,
        "remaining_exotic_loophole": "independent off-diagonal C1 atom only",
    }


def audit() -> tuple[dict[str, object], str]:
    pin_dependencies()
    executable = load(
        "computations/verify_h3_gamma_star_executable_gen_phys_registry.py",
        "source_derived_executable",
    )
    response = load(
        "computations/verify_h3_universal_response_deformation_e14_orbit_ks_gate.py",
        "source_derived_response_top",
    )
    tate = load(
        "computations/verify_h3_reduced_eq_koszul_tate_relative_orbit_gate.py",
        "source_derived_tate",
    )
    comparison = load(
        "computations/verify_h3_response_ks_to_cap_r0_multiplicative_comparison_gate.py",
        "source_derived_comparison",
    )
    normalization = load(
        "computations/verify_h3_kappa_lambda_literal_mapping_cone_normalization_gate.py",
        "source_derived_normalization",
    )

    executable_data, _registry = executable_registry_audit(executable)
    ledger = {
        "theorem": "h3 Gamma-star source-derived executable free-closure census",
        "pins": PINS,
        "executable_Gen_phys": executable_data,
        "canonical_relative_enlargement": source_derived_relative_audit(
            response, tate),
        "typed_free_closure": typed_free_closure_audit(comparison),
        "completion_by_missing_Phi": normalized_completion_audit(normalization),
        "adversarial_exotic_search": exotic_search_audit(),
        "verdict": (
            "Calling the actual source constructors gives 128 entries and no "
            "operation-changing primitive.  Adding the canonical relative "
            "Koszul/Tate cell does not change that fact: it is objectwise on "
            "the cap.  The executable free closure therefore has no kappa. "
            "After adjoining one normalized Phi_KS,r0 schema, standard "
            "naturality produces exactly the eight word-separated kappa "
            "classes, all Psi-dark.  No higher or canonical Tate cell is a "
            "ninth class.  The sole remaining exhaustiveness loophole is an "
            "independently primitive Hom^1(response,cap) atom; the physical "
            "presentation has not declared or excluded that slot."
        ),
        "scope": (
            "exact callable h=3 constructor registry, canonical relative "
            "F/Q Koszul enlargement, and free cellular/DGA closure.  Phi is "
            "not constructed, and the result does not identify the unwritten "
            "full physical complex with this free closure.  The exotic "
            "control is a minimal presentation extension, not a GHZ source."
        ),
    }
    digest = sha256(json.dumps(
        ledger, sort_keys=True, separators=(",", ":")
    ).encode()).hexdigest()
    if EXPECTED_LEDGER_SHA256 != "TO_BE_PINNED":
        require(digest == EXPECTED_LEDGER_SHA256,
                ("source-derived closure ledger changed", digest))
    return ledger, digest


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--mode", choices=("all", "registry", "closure", "exotic"),
                        default="all")
    parser.add_argument("--json", action="store_true")
    arguments = parser.parse_args()
    ledger, digest = audit()
    if arguments.json:
        print(json.dumps({"mode": arguments.mode, "ledger": ledger,
                          "sha256": digest}, indent=2, sort_keys=True))
    else:
        print(f"h3 source-derived Gen_phys closure ({arguments.mode}): PASS")
        print("actual constructors: 128; operation-changing atoms: 0")
        print("canonical Tate enlargement: objectwise; no exotic C1")
        print("after normalized Phi: exactly 8 standard kappa classes")
        print("first unexcluded datum: primitive Hom^1_Gamma(response,cap)")
        print("ledger_sha256=" + digest)


if __name__ == "__main__":
    main()
