#!/usr/bin/env python3
"""Exact signed-lattice classification of the chart-25 physical source graph.

The complete frozen partial-character support has 20 physical rows and 56
individually labelled mixed-source columns.  Its graph is four disjoint
four-leaf multistars.  This checker proves the integral split exact sequence

    0 -> Z^16 -> Z^20 -> Z^4 -> 0,

so the source image is saturated and its four primitive component
characters are the entire cokernel.  The 40 column syzygies are generated by
parallel-edge differences (doubled even cycles); the graph is bipartite and
has no odd handcuff.  Hence cycle/handcuff combinations and ordinary
label-diagonal Koszul closure cannot supply the missing chart-25 4D class.
"""

from collections import Counter, defaultdict
from fractions import Fraction as F
from hashlib import sha256
import importlib.util
import json
from pathlib import Path


HERE = Path(__file__).resolve().parent
EXPECTED_DIGEST = "0ce609a7aaf564f5387d3d4dfb07121a06925a3383bf3b62087cea71aca44165"


def require(condition, message):
    if not condition:
        raise RuntimeError(message)


def load(name, filename):
    spec = importlib.util.spec_from_file_location(name, HERE / filename)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


LITERAL = load(
    "chart25_signed_lattice_literal",
    "verify_n8_literal_hafnian_hpl_no_go.py",
)
RELATIVE = load(
    "chart25_signed_lattice_relative",
    "verify_n8_chart25_relative_4d_obstruction.py",
)
DUAL = LITERAL.DUAL
BASE = DUAL.BASE


def matmul(left, right):
    require(not left or len(left[0]) == len(right), "matrix sizes disagree")
    return [
        [sum((a * right[k][j] for k, a in enumerate(row)), 0)
         for j in range(len(right[0]))]
        for row in left
    ]


def subtract(left, right):
    require(len(left) == len(right), "matrix row counts disagree")
    return [
        [a - b for a, b in zip(lrow, rrow, strict=True)]
        for lrow, rrow in zip(left, right, strict=True)
    ]


def identity(size):
    return [[1 if row == column else 0 for column in range(size)]
            for row in range(size)]


def transpose(matrix):
    return [list(column) for column in zip(*matrix, strict=True)]


def rank(matrix):
    work = [list(map(F, row)) for row in matrix]
    if not work:
        return 0
    answer = 0
    for column in range(len(work[0])):
        pivot = next(
            (row for row in range(answer, len(work)) if work[row][column]),
            None,
        )
        if pivot is None:
            continue
        work[answer], work[pivot] = work[pivot], work[answer]
        value = work[answer][column]
        work[answer] = [entry / value for entry in work[answer]]
        for row in range(len(work)):
            if row == answer or not work[row][column]:
                continue
            value = work[row][column]
            work[row] = [
                left - value * right
                for left, right in zip(work[row], work[answer], strict=True)
            ]
        answer += 1
    return answer


def encode_row(row):
    return row.hex()


def encode_column(column):
    word, multiplier = column
    return "".join(map(str, word)) + ":" + multiplier.hex()


def audit():
    literal_ledger, literal_digest = LITERAL.audit()
    require(
        literal_digest
        == "501f74cb2441c4ce451fc4db2cc8a1d6c13f7a8bc9eec98a14d115d4a406034e",
        "literal physical-source dependency moved",
    )
    relative_ledger, relative_digest = RELATIVE.audit()
    require(
        relative_digest
        == "edc1b143d174ea6ddd0d449080aadc8084b785dce85f9a96c3b0827ec1ffcac4",
        "ordinary label-diagonal dependency moved",
    )

    expanded, orbit_histogram = DUAL.expanded_functional()
    actual_families = DUAL.actual_incident_source_columns(expanded)
    actual_columns = tuple(sorted(actual_families[2], key=repr))
    require(len(expanded) == 20 and len(actual_columns) == 56,
            "complete physical source graph moved")
    require({degree: len(columns) for degree, columns in actual_families.items()}
            == {2: 56, 3: 0, 4: 0},
            "unexpected higher source family entered the fibre")

    negative = tuple(sorted(row for row, value in expanded.items() if value < 0))
    positive = tuple(sorted(row for row, value in expanded.items() if value > 0))
    require((len(negative), len(positive)) == (16, 4),
            "signed row bipartition moved")

    edges = []
    groups = defaultdict(list)
    for column in actual_columns:
        hits = tuple(row for row in BASE.column_rows(column) if row in expanded)
        require(len(hits) == 2, "physical column stopped having two signed hits")
        leaf, = (row for row in hits if expanded[row] < 0)
        centre, = (row for row in hits if expanded[row] > 0)
        require(expanded[leaf] == F(-1, 4)
                and expanded[centre] == F(1, 4),
                "physical edge stopped respecting the partial character")
        groups[leaf, centre].append(column)
        edges.append((leaf, centre, column))

    require(len(groups) == 16, "simple signed edge count moved")
    require(Counter(map(len, groups.values())) == {3: 8, 4: 8},
            "physical label multiplicities moved")
    leaf_to_centre = {}
    for leaf, centre in groups:
        require(leaf not in leaf_to_centre, "a leaf met two positive centres")
        leaf_to_centre[leaf] = centre
    require(set(leaf_to_centre) == set(negative), "some negative leaf is isolated")
    require(Counter(leaf_to_centre.values()) == {centre: 4 for centre in positive},
            "signed graph is no longer four four-leaf stars")

    # Order each component by its positive centre and then its four leaves.
    components = []
    for centre in positive:
        leaves = tuple(sorted(
            leaf for leaf, assigned in leaf_to_centre.items()
            if assigned == centre
        ))
        require(len(leaves) == 4, "component leaf count moved")
        components.append((centre, leaves))
    rows = tuple(row for centre, leaves in components for row in leaves + (centre,))
    require(len(rows) == 20 and len(set(rows)) == 20, "component row order failed")
    row_index = {row: index for index, row in enumerate(rows)}

    # B contains one representative for each of the 16 simple incidence
    # types.  P is the four primitive component partial characters, Q reads
    # leaf coordinates, and T includes the positive centres.  The integral
    # identity I-BQ=TP proves split exactness over Z, not only over Q.
    simple_edges = tuple(
        (leaf, centre) for centre, leaves in components for leaf in leaves
    )
    B = [[0 for _ in simple_edges] for _ in rows]
    Q = [[0 for _ in rows] for _ in simple_edges]
    P = [[0 for _ in rows] for _ in components]
    T = [[0 for _ in components] for _ in rows]
    for edge_index, (leaf, centre) in enumerate(simple_edges):
        B[row_index[leaf]][edge_index] = 1
        B[row_index[centre]][edge_index] = 1
        Q[edge_index][row_index[leaf]] = 1
    for component_index, (centre, leaves) in enumerate(components):
        P[component_index][row_index[centre]] = 1
        T[row_index[centre]][component_index] = 1
        for leaf in leaves:
            P[component_index][row_index[leaf]] = -1

    zero_4_16 = [[0] * 16 for _ in range(4)]
    require(matmul(P, B) == zero_4_16, "partial characters do not kill B")
    require(matmul(P, T) == identity(4), "component characters are not primitive")
    require(subtract(identity(20), matmul(B, Q)) == matmul(T, P),
            "integral split exact-sequence identity failed")
    require(rank(B) == 16 and rank(P) == 4,
            "signed incidence ranks moved")

    # The full 56-column matrix is obtained from B by repeating a simple
    # edge according to its physical labels.  Its integer kernel is the
    # direct sum of the zero-sum lattices inside each parallel class.  A
    # basis is e_j-e_rep: precisely 40 doubled even cycles.
    full_columns = []
    parallel_cycle_basis = []
    column_index = {column: index for index, column in enumerate(actual_columns)}
    for leaf, centre, column in edges:
        vector = [0] * 20
        vector[row_index[leaf]] = 1
        vector[row_index[centre]] = 1
        full_columns.append(vector)
    full_matrix = transpose(full_columns)
    require(rank(full_matrix) == 16, "complete physical-column rank moved")
    for edge_type in simple_edges:
        labelled = tuple(sorted(groups[edge_type], key=repr))
        representative = column_index[labelled[0]]
        for column in labelled[1:]:
            vector = [0] * 56
            vector[column_index[column]] = 1
            vector[representative] = -1
            parallel_cycle_basis.append(vector)
    require(len(parallel_cycle_basis) == 40,
            "parallel even-cycle kernel dimension moved")
    require(rank(parallel_cycle_basis) == 40,
            "parallel differences stopped being independent")
    cycle_boundaries = matmul(full_matrix, transpose(parallel_cycle_basis))
    require(all(value == 0 for row in cycle_boundaries for value in row),
            "a doubled even cycle acquired boundary")
    require(56 - rank(full_matrix) == len(parallel_cycle_basis),
            "parallel cycles do not span the rational kernel")

    # Since every edge crosses the leaf/centre bipartition, every closed walk
    # is even.  The only cycles in a multistar are its doubled parallel
    # edges; no odd cycle and hence no odd handcuff exists.
    bipartition_crossings = all(
        leaf in negative and centre in positive for leaf, centre, _ in edges
    )
    require(bipartition_crossings, "signed graph lost bipartiteness")

    # Locate the canonical D of the missing operation.  Its component
    # character is four, while all source boundaries and all even-cycle
    # syzygies have component character zero.  Granting every cycle/Koszul
    # chain target=ores=0 only enlarges the admissible invisible set; the
    # boundary obstruction therefore remains decisive.
    canonical_d = RELATIVE.frozen_rows()[4]
    require(canonical_d in positive, "canonical D is not a positive centre")
    d_component = next(index for index, (centre, _leaves) in enumerate(components)
                       if centre == canonical_d)
    four_d = [0] * 20
    four_d[row_index[canonical_d]] = 4
    four_d_character = [sum(P[i][j] * four_d[j] for j in range(20))
                        for i in range(4)]
    expected_character = [0] * 4
    expected_character[d_component] = 4
    require(four_d_character == expected_character,
            "missing 4D component character moved")

    ledger = {
        "dependencies": {
            "literal_source_digest": literal_digest,
            "relative_koszul_digest": relative_digest,
        },
        "physical_graph": {
            "rows": 20,
            "negative_leaves": 16,
            "positive_centres": 4,
            "labelled_columns": 56,
            "simple_edge_types": 16,
            "components": 4,
            "component_shapes": ["K1,4"] * 4,
            "edge_multiplicity_histogram": [[3, 8], [4, 8]],
            "expanded_orbit_histogram": sorted(orbit_histogram.items()),
        },
        "saturated_lattice": {
            "source_rank": rank(full_matrix),
            "cokernel_rank": 20 - rank(full_matrix),
            "cokernel_torsion": [],
            "split_identity": "I_20-BQ=T*P, P*T=I_4",
            "primitive_component_characters": 4,
        },
        "signed_cycle_kernel": {
            "kernel_rank": len(parallel_cycle_basis),
            "generators": "differences of parallel physical labels",
            "graph_cycles": "40 doubled even cycles",
            "odd_cycles": 0,
            "odd_handcuffs": 0,
        },
        "canonical_missing_class": {
            "D_row": encode_row(canonical_d),
            "component": d_component,
            "boundary": "4D",
            "component_character": four_d_character,
            "in_saturated_source_image": False,
            "reachable_by_even_cycles_or_odd_handcuffs": False,
            "reachable_after_ordinary_label_diagonal_specialization": False,
            "tgt_ores_guard": (
                "even granting every old cycle/Koszul chain tgt=ores=0, "
                "its boundary character is zero"
            ),
        },
        "required_new_type": {
            "signed_graph_form": (
                "a half-edge at D, or an edge from D to a new target vertex tau"
            ),
            "chain_form": "mixed source-diagonal transgression r",
            "minimal_relative_boundary": "d(r)=4D-tau",
            "augmentation": "a(tau)=a(4D)=1; tgt(r)=ores(r)=0",
            "guard": (
                "the mapping-cylinder edge is formal until its mixed "
                "source-diagonal transgression is derived from physical rows"
            ),
        },
        "sample_physical_labels": [
            encode_column(sorted(groups[edge], key=repr)[0])
            for edge in simple_edges
        ],
        "verdict": (
            "the complete physical signed lattice and all ordinary Koszul "
            "closures leave 4D as a primitive relative target class"
        ),
    }
    digest = sha256(json.dumps(
        ledger, sort_keys=True, separators=(",", ":")
    ).encode()).hexdigest()
    if EXPECTED_DIGEST != "TO_BE_FROZEN":
        require(digest == EXPECTED_DIGEST, ("ledger changed", digest, ledger))
    return ledger, digest


def main():
    ledger, digest = audit()
    print("chart-25 complete signed source lattice: PASS")
    print("source image: saturated rank 16; cokernel Z^4")
    print("source syzygies: 40 doubled even cycles; no odd handcuffs")
    print("missing 4D: primitive component character 4")
    print("required new type: relative D--tau edge / mixed transgression")
    print("sha256:", digest)


if __name__ == "__main__":
    main()
