#!/usr/bin/env python3
"""Reduce the augmented C-plus remainder after the conditional core assembly.

The main-row identity in 649b7eb leaves W, physical q, and eta/sigma.  This
checker separates three logically different conclusions.

* Once the P2/KEq comparison is a complete physical protected map and both
  q rows are physical, q is closed by the 7efd10d dichotomy: its defect is
  either row-nullhomotopic or already gives a normalized relative generator.
* The order-six/ridge commutator is zero, so a *labelled shifted* copy of
  gamma=-dOmega can be attached without another mixed Hasse face.  But the
  degree-zero P2/d_even/KEq signatures do not construct that copy: its pq and
  xv halves have different site degrees.  Eta/sigma are automatic only under
  the stronger fully augmented principal-parts hypothesis.
* Endpoint-evenness does not kill W.  The even projector doubles an even
  W-row, whereas the odd projector kills it.  Hence W is the sole remaining
  scalar compatibility only after the labelled ridge lift is included.
"""

from __future__ import annotations

from fractions import Fraction as Q
from hashlib import sha256
import importlib.util
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
PINS = {
    "computations/verify_h3_cplus_conditional_physical_dressing_assembly.py":
        "e8014fdfd2263a8eb6bffff11e31c339b5b7965989a61324f8d118a91f791f46",
    "computations/verify_dark_cartan_physical_q_protected_quotient_comparison.py":
        "eb56cdb4ab1915f8ce35ab3acf0398b4f526c52a17c9c8ebafcc7a5ad4f86bcc",
    "computations/verify_h3_residual_q_order6_ridge_jet_commutation.py":
        "00a0798b4aa1d901b52645cac3f1dbe2854a3d8ce796191f7a4ff9a6e295b28f",
    "computations/verify_h3_residual_q_terminal_ridge_kahler_identification.py":
        "aea73ce5ff6ce183245d209393ed60192066d38eab7d4d203caa0c82cc5b16d6",
    "computations/verify_uniform_cartan_augmented_grade_naturality_gate.py":
        "d71b2ae71cdfc910e374b498a70edbb5e897867cf624dec49203c34e74647925",
    "computations/verify_h3_tau_plus_connected_sl3_label_orbit_obstruction.py":
        "7048ab1ea5912f1be38014f193970e093c1f5d1259cc56e1e5566b1552358b52",
}
EXPECTED_LEDGER_SHA256 = (
    "dc32ed6288ce40f668f3b0a7f881683b3fd4c95d2900fec57df0d15e46343897"
)


def require(condition: bool, detail: object) -> None:
    if not condition:
        raise RuntimeError(detail)


def load(relative: str, name: str):
    specification = importlib.util.spec_from_file_location(name, ROOT / relative)
    require(specification is not None and specification.loader is not None,
            ("cannot import", relative))
    module = importlib.util.module_from_spec(specification)
    specification.loader.exec_module(module)
    return module


def dot(left, right):
    return sum((Q(a) * Q(b) for a, b in zip(left, right, strict=True)), Q(0))


def row_matrix(row, matrix):
    return tuple(sum(Q(row[index]) * Q(matrix[index][column])
                     for index in range(len(row)))
                 for column in range(len(matrix[0])))


def q_alternative_audit() -> dict[str, object]:
    # Minimal exact model of 7efd10d.  J=(1,0,0), so row(J) is the first
    # coordinate and ker(J) is generated by e1,e2.  Test the homotopy arm
    # and both sides of the nonzero physical-terminal arm.
    protected = (Q(1), Q(0), Q(0))
    kernel = ((Q(0), Q(1), Q(0)), (Q(0), Q(0), Q(1)))

    homotopic_defect = (Q(5), Q(0), Q(0))
    require(homotopic_defect == tuple(5 * value for value in protected)
            and all(dot(homotopic_defect, value) == 0 for value in kernel),
            "q row-homotopy arm changed")

    witness = kernel[0]
    source_q = (Q(0), Q(1), Q(0))
    canonical_q = (Q(0), Q(0), Q(0))
    require(dot(source_q, witness) - dot(canonical_q, witness) == 1
            and dot(source_q, witness) != 0,
            "source-visible q arm changed")
    source_q, canonical_q = canonical_q, (Q(0), Q(-1), Q(0))
    require(dot(source_q, witness) - dot(canonical_q, witness) == 1
            and dot(canonical_q, witness) != 0,
            "canonical-visible q arm changed")

    # Also pin the load-bearing language in the complete theorem.  It is not
    # valid on a projected coefficient matrix with an undefined q row.
    source = (ROOT / next(relative for relative in PINS
                          if "physical_q_protected" in relative)).read_text()
    require("q-q_h3 Phi=lambda J" in source
            and "q is the physical sum_6(m_i)-ainc terminal on L" in source,
            "the physical q typing hypothesis changed")
    return {
        "hypotheses": [
            "J3 Phi=A J on complete physical protected domains",
            "q=sum_6(m_i)-ainc is physically typed on both domains",
        ],
        "zero_defect": "q-q3 Phi=lambda J: augmented q comparison exists",
        "nonzero_defect": (
            "a protected-kernel witness has q!=0 on the source or canonical "
            "side and normalizes to the existing relative generator"
        ),
        "independent_q_construction_after_hypotheses": False,
    }


def ridge_audit() -> dict[str, object]:
    # One-face ridge coordinates (a,t,b,u).  The unique coefficient vector
    # with eta constant=1, eta U=1, sigma=-1, augmentation=0 is gamma.
    gamma = (Q(-1), Q(1), Q(1), Q(-1))
    eta_constant = gamma[1]
    eta_u = -gamma[3]
    sigma = gamma[0]
    augmentation = sum(gamma, Q(0))
    require((eta_constant, eta_u, sigma, augmentation) == (1, 1, -1, 0),
            "the canonical ridge contractions changed")

    # The two halves cannot be put in one site grade by adding a common tail.
    degree_pq = (0, 0, 0, 0, 0, 0, 1, 1)
    degree_xv = (1, 1, 0, 0, 0, 0, 0, 0)
    tail = (2, 1, 3, 0, 1, 2, 4, 1)
    degree_pq_tail = tuple(a + b for a, b in
                           zip(degree_pq, tail, strict=True))
    degree_xv_tail = tuple(a + b for a, b in
                           zip(degree_xv, tail, strict=True))
    require(degree_pq_tail != degree_xv_tail,
            "a common tail repaired the ridge grade mismatch")

    # The exact complete order-six checker proves strict commutation.  Run it
    # rather than replacing its 8,580-operator census by a sampled assertion.
    commutation = load(
        "computations/verify_h3_residual_q_order6_ridge_jet_commutation.py",
        "cplus_terminal_commutation",
    ).audit()
    require(commutation["eligible_order6_operators"] == 8580
            and commutation["complete_hasse_tower_can_tensor_with_ridge_jet"]
            and not commutation[
                "physical_labelled_repeated_grade_tensor_product_constructed"
            ], "the ridge commutation/typing split changed")

    # Adding a formal gamma changes no degree-zero/main/q/W coordinate.  This
    # witnesses that main-row closure plus strict commutation does not select
    # a terminal lift.  Physical image membership remains the missing datum.
    main_q_w = (Q(0), Q(0), Q(0))
    terminal_dark = main_q_w + (Q(0), Q(0), Q(0))
    terminal_ridge = main_q_w + (eta_constant, eta_u, sigma)
    require(terminal_dark[:3] == terminal_ridge[:3]
            and terminal_dark[3:] != terminal_ridge[3:],
            "the terminal forgetful-kernel witness changed")

    return {
        "canonical_relative_class": "gamma_v=-dOmega_v=-da+dt+db-du",
        "terminal_law": {
            "eta_z": "1+delta_(vz)*u_z/t",
            "sigma": "-q_pq^22",
        },
        "main_boundary_q_W": [0, 0, 0],
        "order6_mixed_commutator": 0,
        "additional_mixed_Hasse_correction_needed": False,
        "current_degree_zero_P2_d_even_KEq_implies_terminal_lift": False,
        "first_obstruction": (
            "pq and xv halves have distinct site degrees; the missing datum "
            "is image membership of their labelled shifted Kähler sum"
        ),
        "under_fully_augmented_PP_hypothesis": (
            "eta/sigma close uniquely and require no further generator"
        ),
    }


def w_audit() -> dict[str, object]:
    # Endpoint swap on two pairs.  An endpoint-even row is annihilated by
    # 1-S and doubled by 1+S.  C-plus uses the even projection.
    swap = (
        (0, 1, 0, 0),
        (1, 0, 0, 0),
        (0, 0, 0, 1),
        (0, 0, 1, 0),
    )
    identity = tuple(tuple(Q(row == column) for column in range(4))
                     for row in range(4))
    even = tuple(tuple(identity[row][column] + swap[row][column]
                       for column in range(4)) for row in range(4))
    odd = tuple(tuple(identity[row][column] - swap[row][column]
                      for column in range(4)) for row in range(4))
    w_row = (Q(1), Q(1), Q(0), Q(0))
    require(row_matrix(w_row, odd) == (0, 0, 0, 0)
            and row_matrix(w_row, even) == (2, 2, 0, 0),
            "endpoint parity stopped separating W")
    return {
        "C_plus_projector": "1+rho",
        "endpoint_even_W_times_(1-rho)": 0,
        "endpoint_even_W_times_(1+rho)": "2 W",
        "W_zero_from_C_plus_parity": False,
        "remaining_equation": "W(P2 total)+W(Phi_KEq)=0",
    }


def audit() -> tuple[dict[str, object], str]:
    for relative, expected in PINS.items():
        actual = sha256((ROOT / relative).read_bytes()).hexdigest()
        require(actual == expected,
                ("pinned dependency changed", relative, actual, expected))
    ledger = {
        "theorem": "conditional C-plus q/ridge/W terminal reduction",
        "pins": PINS,
        "physical_q": q_alternative_audit(),
        "eta_sigma_ridge": ridge_audit(),
        "physical_W": w_audit(),
        "frontier": {
            "under_649b7eb_degree_zero_hypotheses": [
                "labelled shifted Kähler ridge image membership",
                "W(P2 total)+W(Phi_KEq)=0",
            ],
            "under_fully_augmented_PP_P2_KEq_hypothesis": [
                "W(P2 total)+W(Phi_KEq)=0",
            ],
            "q_is_independent_remaining_construction": False,
            "eta_sigma_is_independent_numerical_formula": False,
            "eta_sigma_is_independent_physical_typing_clause": True,
        },
        "scope": (
            "generic h3 C-plus terminal reduction after the conditional core; "
            "no construction of P2, d_even, pointed K_Eq, the labelled "
            "shifted ridge, W-nullhomotopy, or beta-zero Bockstein"
        ),
    }
    payload = json.dumps(ledger, sort_keys=True, separators=(",", ":"))
    digest = sha256(payload.encode()).hexdigest()
    if EXPECTED_LEDGER_SHA256 != "TO_BE_PINNED":
        require(digest == EXPECTED_LEDGER_SHA256,
                ("ledger digest changed", digest))
    return ledger, digest


def main() -> None:
    ledger, digest = audit()
    print("h3 C-plus augmented remainder: q CLOSED BY ALTERNATIVE")
    print("eta/sigma: strict commutation, but labelled ridge typing remains")
    print("fully augmented PP hypothesis: W is the sole scalar equation")
    print("current 649b7eb hypotheses: W plus labelled ridge lift")
    print("ledger_sha256=" + digest)


if __name__ == "__main__":
    main()
