#!/usr/bin/env python3
r"""Laurent-character and source-degree audit for the eta compensation.

On the marked clean-C5 open, put t=q_pq^00 and u_v=q_xv^00.  The five
normalized target-stabilizer fields act by

    eta_z(t)=1,  eta_z(u_v)=-delta_zv*u_z/t.

The aggregate correction law 5+u_z/t has the unique affine primitive
5*t-sum(u_v), modulo invariants.  It is not the logarithmic derivative of
any Laurent character.  Moreover t and u_v have distinct endpoint/site
fine degrees; multiplying both by one common P3+K2 tail does not homogenize
their difference.  The first common monomial completion makes the two
terms identical, so a nonzero lift needs a relative endpoint/rootless
comparison cell rather than a coefficient-ring character.

This checker specifies that cell and its exact Fredholm use.  It does not
construct the cell.
"""

from __future__ import annotations

from fractions import Fraction as Q
from hashlib import sha256
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
EXPECTED_LEDGER_SHA256 = "ec31e0e6a6f6ed6c6258f7028e64d03b1c35fa35889d0b13cec9474b65e6893f"
PINS = {
    "computations/verify_h3_rootless_eta_cyclic_compensation_boundary.py":
        "9beab390c8ed2c89f1a8f62ee54857c03199fecd5ad9a69ab6f29d6a04140b6d",
    "computations/verify_h3_rootless_clean_c5_formal_F_full_jacobian_boundary.py":
        "1c17b29f1179416d57acbb2daada0d1f34ee5a69e5f3a68bd6827da0858363e3",
    "computations/verify_h3_rootless_endpoint_to_collision_chain_map_boundary.py":
        "be39a61df8e3723983eea7a20d405fba7ff0f3822bc90e8d48b8039177f69cfc",
    "computations/verify_h3_rootless_normalized_c5_base_column_source_separator.py":
        "635b3e667613049817f04440401d31237db259ab7cf9948989e0da2674efb022",
    "computations/verify_h3_rootless_augmented_pentagon_fredholm_alternative.py":
        "0b0831391416f85302b5f2d89da0672e07dca4c73fc5f3893ad992abd48c1d2b",
}

FACES = (1, 2, 3, 4, 5)
SITES = tuple(range(8))
X, P, QSITE = 0, 6, 7
MIDDLE = {1: 1, 2: 2, 3: 1, 4: 1, 5: 2}


def require(condition: bool, message: object) -> None:
    if not condition:
        raise RuntimeError(message)


def rank(rows: list[list[int]]) -> int:
    work = [[Q(entry) for entry in row] for row in rows]
    if not work:
        return 0
    pivot_row = 0
    for column in range(len(work[0])):
        pivot = next((row for row in range(pivot_row, len(work))
                      if work[row][column]), None)
        if pivot is None:
            continue
        work[pivot_row], work[pivot] = work[pivot], work[pivot_row]
        value = work[pivot_row][column]
        work[pivot_row] = [entry / value for entry in work[pivot_row]]
        for row in range(len(work)):
            if row == pivot_row or not work[row][column]:
                continue
            value = work[row][column]
            work[row] = [left - value * right for left, right in
                         zip(work[row], work[pivot_row], strict=True)]
        pivot_row += 1
    return pivot_row


def eta_character_audit() -> dict[str, object]:
    # A Laurent character M=t^a product_v u_v^b_v has
    # t*eta_z(log M)=a-b_z.  The 5x6 character-weight matrix therefore has
    # rows (1,0,...,-1_z,...,0).
    weights = []
    for index in range(5):
        row = [1] + [0] * 5
        row[1 + index] = -1
        weights.append(row)
    require(rank(weights) == 5, "eta character matrix rank changed")
    invariant = [1] * 6
    require(all(sum(a * b for a, b in zip(row, invariant, strict=True)) == 0
                for row in weights), "t*product(u_v) stopped being invariant")

    # The logarithmic derivative of a character has Laurent support {t^-1}
    # and constant integer numerator a-b_z.  The requested law has support
    # {1,u_z/t}; these two supports are distinct in the Laurent ring.
    log_support = ("t^-1",)
    desired_support = ("1", "u_z*t^-1")
    require(set(log_support) != set(desired_support),
            "a Laurent character unexpectedly acquired affine support")

    # The derivative eta_z(M) itself is also a single Laurent monomial (or
    # zero), so it cannot equal the two-term target either.
    return {
        "coordinate_order": ["t", *[f"u_{v}" for v in FACES]],
        "character_weight_matrix": weights,
        "rank": 5,
        "invariant_character_lattice":
            "Z*(1,1,1,1,1,1), generated by K=t*product_v(u_v)",
        "eta_z_log_character": "(a-b_z)/t",
        "desired_aggregate_law": "5+u_z/t",
        "desired_is_logarithmic_character": False,
        "desired_is_derivative_of_one_character": False,
    }


def affine_primitive_audit() -> dict[str, object]:
    # For C=alpha*t+sum beta_v*u_v,
    # eta_z(C)=alpha-beta_z*u_z/t.  Match 5+u_z/t.
    alpha = 5
    beta = {face: -1 for face in FACES}
    records = []
    for auxiliary in FACES:
        constant = alpha
        u_coefficients = {
            face: -beta[face] if face == auxiliary else 0
            for face in FACES
        }
        require(constant == 5
                and u_coefficients[auxiliary] == 1
                and sum(bool(value) for value in u_coefficients.values()) == 1,
                "affine primitive derivative changed")
        records.append({
            "auxiliary": auxiliary,
            "eta_z(C)": f"5+u_{auxiliary}/t",
        })

    # The difference of any two Laurent-polynomial primitives is killed by
    # all five diagonal derivations.  Weight decomposition and the rank-five
    # matrix above show that its monomials are powers of K.
    return {
        "unique_affine_primitive": "C=5*t-sum_v(u_v)",
        "face_local_primitive": "c_v=t-u_v",
        "derivatives": records,
        "all_Laurent_polynomial_primitives":
            "C+Phi(K), K=t*product_v(u_v)",
        "uniqueness_scope": "Phi is an arbitrary Laurent polynomial",
    }


def stabilizer_and_degree_no_go() -> dict[str, object]:
    # The further target stabilizer sigma_(p,2)=1,sigma_(x,2)=-1 fixes every
    # t,u_v and hence every function of them.  It moves z=q_pq^22 with
    # weight one and fixes w_v=q_xv^(0,m_v).  Therefore the corrected
    # aggregate sum(Omega)+C=5*z-sum(w_v) has derivative 5*z.
    sigma = {
        "t": 0,
        **{f"u_{v}": 0 for v in FACES},
        "z=q_pq^22": 1,
        **{f"w_{v}=q_x{v}^(0,{MIDDLE[v]})": 0 for v in FACES},
    }
    require(sigma["z=q_pq^22"] == 1
            and not any(sigma[f"u_{v}"] for v in FACES),
            "full-stabilizer character audit changed")

    def site_degree(*sites: int) -> tuple[int, ...]:
        return tuple(int(site in sites) for site in SITES)

    degree_t = site_degree(P, QSITE)
    degree_u = {face: site_degree(X, face) for face in FACES}
    for face in FACES:
        require(degree_t != degree_u[face],
                "marked endpoint cells unexpectedly have one site degree")
        arbitrary_tail = tuple((index + face) % 3 for index in SITES)
        require(tuple(a + q for a, q in zip(degree_t, arbitrary_tail,
                                             strict=True))
                != tuple(a + q for a, q in zip(degree_u[face], arbitrary_tail,
                                                strict=True)),
                "a common tail unexpectedly homogenized t-u_v")

    # Minimal complementary factors u_v and t make the two monomials equal,
    # not a nonzero binomial.  A nontrivial lift must retain the endpoint-bar
    # order/source label or use distinct matching tails.
    monomial_tuv = (1, 1)  # exponent order (t,u_v)
    require(monomial_tuv == (1, 1), "minimal lcm changed")
    return {
        "first_extra_full_target_stabilizer": sigma,
        "derivative_of_corrected_scalar": "5*q_pq^22",
        "marked_cell_scalar_repairs_full_kernel": False,
        "site_degree_t": list(degree_t),
        "site_degrees_u": {str(face): list(degree_u[face])
                           for face in FACES},
        "common_tail_homogenizes_t_minus_u": False,
        "minimal_polynomial_completion":
            "t*(u_v*N)-u_v*(t*N)=0 coefficientwise",
        "nonzero_lift_requires":
            "a relative endpoint/rootless comparison cell with bar/source labels",
    }


def minimal_generator_and_fredholm() -> dict[str, object]:
    return {
        "minimal_generator": {
            "name": "G_(v,N) endpoint-to-rootless comparison vertex",
            "common_repeated_degree": "one labelled P3+K2 component",
            "boundary": "dG_(v,N)=t_v*Omega_v-r_v",
            "cancelled_common_rows": ["Q_(v,N)", "ordinary residue"],
            "readouts": {"W": 0, "target": 0, "ores": 0, "ainc": 0},
            "required_eta_value_on_clean_slice":
                "d r_v(eta_z)=1+delta_(vz)*u_z/t",
            "status": "not constructed in the literal source inventory",
        },
        "why_minimal": (
            "endpoint bars and rootless collision routes are the first two "
            "presentations in the common P3+K2 degree; their comparison is "
            "not an ordinary coefficient-ring character, and adjacent "
            "comparison edges leave one primitive C5 vertex aggregate"
        ),
        "fredholm_use": [
            "G makes the rootless ridge readout invariant under the eta_z kernel",
            "a physical reduced-Eq/cap correction must still combine it into "
            "P(e_v)=(-r_v,W=1,ainc=-1,target=ores=0)",
            "clean C5 edges propagate one such physical column to all five faces",
            "for Pbar:k^5->coker(Jhat), either ker(Pbar) contains c with "
            "epsilon(c)!=0 (relative generator) or epsilon factors through "
            "Pbar (rootless annihilator)",
        ],
        "comparison_alone_invokes_fredholm": False,
    }


def main() -> None:
    for relative, expected in PINS.items():
        actual = sha256((ROOT / relative).read_bytes()).hexdigest()
        require(actual == expected,
                ("pinned dependency changed", relative, actual))
    ledger = {
        "theorem": "eta compensation: no Laurent character and exact source interface",
        "character": eta_character_audit(),
        "affine_primitive": affine_primitive_audit(),
        "full_stabilizer_and_source_degree": stabilizer_and_degree_no_go(),
        "physical_interface": minimal_generator_and_fredholm(),
        "verdict": (
            "the eta law has a canonical additive affine primitive but no "
            "Laurent-character primitive; neither a marked-cell scalar nor "
            "a common P3+K2 multiplier is a physical comparison.  The "
            "minimal new datum is the source-labelled endpoint/rootless "
            "comparison vertex, which is necessary but not alone sufficient "
            "to define the Fredholm polar map"
        ),
    }
    payload = json.dumps(ledger, sort_keys=True, separators=(",", ":"))
    digest = sha256(payload.encode()).hexdigest()
    if EXPECTED_LEDGER_SHA256 != "TO_BE_PINNED":
        require(digest == EXPECTED_LEDGER_SHA256,
                ("ledger digest changed", digest))
    print("h3 rootless eta character/source interface: SHARP NO-GO")
    print("eta law: additive primitive 5*t-sum(u), no Laurent character")
    print("common P3+K2 tail homogenizes t-u: NO")
    print("minimal datum: source-labelled Omega/r comparison vertex")
    print("comparison alone invokes Fredholm: NO")
    print("ledger sha256:", digest)


if __name__ == "__main__":
    main()
