#!/usr/bin/env python3
"""Exact degree-five filtered lift of the full n=8 pure product.

This checker streams a frozen 7,861-column rational orbit certificate in
the balanced 24-port Macaulay component and proves

    H_0 H_1 H_2 = sum Q_w H_w  (mod J^6),

where the H_w are mixed and J is generated by the 240 coordinates outside
the twelve-coordinate boundary support.  No large incidence component is
cached.  The result is truncated membership, not full ideal membership.
"""

from collections import Counter, defaultdict
from fractions import Fraction
from hashlib import sha256
from itertools import combinations, product
import importlib.util
import json
from math import lcm
from pathlib import Path


def require(condition, detail):
    if not condition:
        raise RuntimeError(detail)


HERE = Path(__file__).resolve().parent
SOURCE_PATH = HERE / "verify_n8_full_source_cycle_product_membership.py"
SPEC = importlib.util.spec_from_file_location("n8_full_source", SOURCE_PATH)
SOURCE = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(SOURCE)

CERTIFICATE_PATH = (
    HERE / "certificates/n8_full_source_pure_product_degree5_solution.json"
)
EXPECTED_CERTIFICATE_SHA256 = (
    "4430d001038d7db63345054b47ce025a3c53a69e6c41a548a438393193b0c851"
)
EXPECTED_LEDGER_SHA256 = (
    "97621e567428bf34bde8f3a7588370abd21a6cb0a853c4cb38796ae1d5e0b5d4"
)
QQ = Fraction
MAXIMUM_DEGREE = 5


COORDINATES = tuple(
    (left, right, left_colour, right_colour)
    for left, right in combinations(range(8), 2)
    for left_colour in SOURCE.COLOURS
    for right_colour in SOURCE.COLOURS
)
COORDINATE_ID = {coordinate: index for index, coordinate in enumerate(COORDINATES)}
SUPPORT_IDS = frozenset(COORDINATE_ID[item] for item in SOURCE.SUPPORT_PRODUCT)
IS_OFF_SUPPORT = tuple(
    index not in SUPPORT_IDS for index in range(len(COORDINATES))
)
MATCHINGS = SOURCE.perfect_matchings(SOURCE.VERTICES)
GROUP = SOURCE.SUPPORT_STABILIZER


def word_code(word):
    answer = 0
    for colour in word:
        answer = 3 * answer + colour
    return answer


def decode_word(code):
    word = [0] * 8
    for index in range(7, -1, -1):
        word[index] = code % 3
        code //= 3
    return tuple(word)


VARIABLE_TRANSFORMS = tuple(
    bytes(COORDINATE_ID[SOURCE.transform_variable(coordinate, element)]
          for coordinate in COORDINATES)
    for element in GROUP
)


def transform_word_code(code, element):
    word = decode_word(code)
    vertex_permutation, colour_permutation = element
    transformed = [None] * 8
    for vertex in SOURCE.VERTICES:
        transformed[vertex_permutation[vertex]] = colour_permutation[word[vertex]]
    return word_code(transformed)


WORD_TRANSFORMS = tuple(
    tuple(transform_word_code(code, element) for code in range(3 ** 8))
    for element in GROUP
)


def row_degree(row):
    return sum(IS_OFF_SUPPORT[value] for value in row)


def canonical_row(row):
    return min(bytes(sorted(transform[value] for value in row))
               for transform in VARIABLE_TRANSFORMS)


def column_orbit(column):
    code, multiplier = column
    return tuple(sorted(set(
        (
            WORD_TRANSFORMS[group_index][code],
            bytes(sorted(VARIABLE_TRANSFORMS[group_index][value]
                         for value in multiplier)),
        )
        for group_index in range(len(GROUP))
    )))


def canonical_column(column):
    return column_orbit(column)[0]


def iter_word_terms(code):
    word = decode_word(code)
    for matching in MATCHINGS:
        yield bytes(sorted(
            COORDINATE_ID[SOURCE.edge(left, right, word[left], word[right])]
            for left, right in matching
        ))


def iter_column_outputs(column):
    code, multiplier = column
    for term in iter_word_terms(code):
        yield bytes(sorted(multiplier + term))


WORD_MINIMUM_DEGREES = {}


def column_minimum_degree(column):
    code, multiplier = column
    if code not in WORD_MINIMUM_DEGREES:
        WORD_MINIMUM_DEGREES[code] = min(
            row_degree(term) for term in iter_word_terms(code)
        )
    return row_degree(multiplier) + WORD_MINIMUM_DEGREES[code]


def pure_target_rows():
    terms_by_colour_degree = []
    for colour in SOURCE.COLOURS:
        groups = defaultdict(list)
        for term in iter_word_terms(word_code((colour,) * 8)):
            groups[row_degree(term)].append(term)
        terms_by_colour_degree.append(groups)

    actual = set()
    canonical = set()
    for degrees in product(range(MAXIMUM_DEGREE + 1), repeat=3):
        if sum(degrees) > MAXIMUM_DEGREE:
            continue
        groups = [terms_by_colour_degree[colour].get(degree, ())
                  for colour, degree in enumerate(degrees)]
        for terms in product(*groups):
            row = bytes(sorted(sum((tuple(term) for term in terms), ())))
            require(row not in actual,
                    "pure-product target monomial acquired multiplicity")
            actual.add(row)
            canonical.add(canonical_row(row))
    return actual, canonical


def verify_balanced_column(column):
    code, multiplier = column
    word = decode_word(code)
    ports = Counter((vertex, word[vertex]) for vertex in SOURCE.VERTICES)
    for variable_id in multiplier:
        left, right, left_colour, right_colour = COORDINATES[variable_id]
        ports[left, left_colour] += 1
        ports[right, right_colour] += 1
    require(len(multiplier) == 8, "certificate multiplier degree changed")
    require(all(ports[vertex, colour] == 1
                for vertex in SOURCE.VERTICES for colour in SOURCE.COLOURS),
            "certificate column left the balanced 24-port component")
    require(len(set(word)) > 1, "certificate uses a pure generator")


def add_value(vector, row, value):
    result = vector.get(row, QQ(0)) + value
    if result:
        vector[row] = result
    else:
        vector.pop(row, None)


def audit():
    raw_certificate = CERTIFICATE_PATH.read_bytes()
    require(sha256(raw_certificate).hexdigest() == EXPECTED_CERTIFICATE_SHA256,
            "degree-five certificate file digest changed")
    certificate = json.loads(raw_certificate)
    require(certificate["format"]
            == "n8-full-source-pure-product-degree5-rational-v1",
            "degree-five certificate format changed")
    require(certificate["discovery_prime"] == 1009,
            "degree-five discovery prime changed")
    require(certificate["discovery_rank"] == 72904,
            "degree-five modular discovery rank changed")
    require(certificate["discovery_rows"] == 72985
            and certificate["discovery_columns"] == 224153,
            "degree-five coupled discovery census changed")

    actual_target, canonical_target = pure_target_rows()
    require(len(actual_target) == 3049, "pure target actual support changed")
    require(len(canonical_target) == 818, "pure target orbit support changed")
    target = {row: QQ(1) for row in canonical_target}

    image = {}
    columns_seen = set()
    coefficient_histogram = Counter()
    minimum_degree_histogram = Counter()
    orbit_size_histogram = Counter()
    streamed_actual_columns = 0
    streamed_matching_terms = 0
    for item in certificate["solution"]:
        word = tuple(item["word"])
        require(len(word) == 8 and all(colour in SOURCE.COLOURS for colour in word),
                "invalid certificate word")
        multiplier = bytes(
            COORDINATE_ID[tuple(variable)] for variable in item["multiplier"]
        )
        column = (word_code(word), multiplier)
        require(column == canonical_column(column),
                "certificate column is not its orbit representative")
        require(column not in columns_seen, "duplicate certificate column")
        columns_seen.add(column)
        verify_balanced_column(column)
        minimum_degree = column_minimum_degree(column)
        require(minimum_degree <= MAXIMUM_DEGREE,
                "certificate column starts beyond the solved filtration")
        minimum_degree_histogram[minimum_degree] += 1

        value = QQ(item["numerator"], item["denominator"])
        require(value, "zero certificate coefficient")
        coefficient_histogram[value] += 1
        orbit = column_orbit(column)
        orbit_size_histogram[len(orbit)] += 1
        for actual_column in orbit:
            streamed_actual_columns += 1
            for output in iter_column_outputs(actual_column):
                if row_degree(output) > MAXIMUM_DEGREE:
                    continue
                streamed_matching_terms += 1
                if output == canonical_row(output):
                    add_value(image, output, value)

    require(len(columns_seen) == 7861, "certificate solution support changed")
    require(image == target,
            "exact degree-five rational certificate replay left a residual")
    target_degree_histogram = Counter(map(row_degree, canonical_target))
    denominators = [value.denominator for value in coefficient_histogram]
    return {
        "vertices": 8,
        "endpoint_colours": 3,
        "ambient_pair_variables": len(COORDINATES),
        "balanced_ordinary_degree": 12,
        "maximum_solved_off_support_degree": MAXIMUM_DEGREE,
        "modulus_statement": (
            "equality modulo the sixth power of the off-support ideal"
        ),
        "target_actual_rows": len(actual_target),
        "target_row_orbits": len(canonical_target),
        "target_orbits_by_degree": dict(sorted(target_degree_histogram.items())),
        "discovery_prime": certificate["discovery_prime"],
        "coupled_discovery_rows": certificate["discovery_rows"],
        "coupled_discovery_columns": certificate["discovery_columns"],
        "coupled_modular_rank": certificate["discovery_rank"],
        "coupled_modular_left_nullity": (
            certificate["discovery_rows"] - certificate["discovery_rank"]
        ),
        "solution_orbit_columns": len(columns_seen),
        "solution_columns_by_minimum_degree": dict(
            sorted(minimum_degree_histogram.items())
        ),
        "solution_orbit_size_histogram": dict(sorted(orbit_size_histogram.items())),
        "streamed_actual_columns": streamed_actual_columns,
        "streamed_matching_terms_at_degrees_at_most_five": streamed_matching_terms,
        "solution_coefficient_set": [
            [value.numerator, value.denominator]
            for value in sorted(coefficient_histogram)
        ],
        "solution_coefficient_histogram": [
            {
                "value": [value.numerator, value.denominator],
                "count": coefficient_histogram[value],
            }
            for value in sorted(coefficient_histogram)
        ],
        "solution_denominator_lcm": lcm(*denominators),
        "maximum_solution_numerator": max(
            abs(value.numerator) for value in coefficient_histogram
        ),
        "certificate_sha256": EXPECTED_CERTIFICATE_SHA256,
        "exact_replay_residual_rows": 0,
        "identity": "H_0 H_1 H_2 = sum Q_w H_w mod J^6 over Q",
        "scope_guard": "truncated consistency is not full ideal membership",
    }


def main():
    ledger = audit()
    encoded = json.dumps(ledger, sort_keys=True, separators=(",", ":"))
    digest = sha256(encoded.encode()).hexdigest()
    if EXPECTED_LEDGER_SHA256 != "TO_BE_FILLED":
        require(digest == EXPECTED_LEDGER_SHA256,
                "frozen degree-five pure-product ledger changed")
    print(
        "n=8 full-source pure-product degree-five lift: PASS; "
        f"target={ledger['target_row_orbits']}, "
        f"solution={ledger['solution_orbit_columns']}, "
        f"denominator={ledger['solution_denominator_lcm']}, residual=0"
    )
    print(f"sha256: {digest}")


if __name__ == "__main__":
    main()
