#!/usr/bin/env python3
"""All-order edge-03 stability on the literal h=3 same-hole normal form.

The active-clean pencil of c85ff47 is clean exactly while the residual
internal block on physical edge 03 vanishes.  This checker derives three
families of literal complete-row equations and proves, in the completed
local ring of the same-hole normal form, that the ideal I generated by all
nine q03 decorations satisfies I subset m^3 I.  Nakayama gives I=0.

The result allows arbitrary higher internal-q support.  It keeps the
displayed endpoint stars/direct anchors in the same-hole normal form; star
deformations outside that normal form are not covered.
"""

from __future__ import annotations

from collections import Counter
from hashlib import sha256
import importlib
import itertools
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
PINS = {
    "computations/verify_h3_one_bad_same_hole_active_clean_pencil.py":
        "71e78c44ef19faa1db161d15271d53f3931f6d4ef14b57d76b9fc703ec1750cd",
}
EXPECTED_LEDGER_SHA256 = (
    "79787aab4671965776dcba03281f374483d67268ba0514fca7cb4b6bae6f5d43"
)

A, C, T = range(3)
SITES = tuple(range(5))


def require(condition, message):
    if not condition:
        raise RuntimeError(message)


def pin_dependencies():
    for relative, expected in PINS.items():
        actual = sha256((ROOT / relative).read_bytes()).hexdigest()
        require(actual == expected, f"dependency changed: {relative}: {actual}")


def q_name(u, v, a, b):
    if u > v:
        u, v, a, b = v, u, b, a
    return f"q{u}{v}:{a}{b}"


def monomial(*factors):
    return tuple(sorted(factors))


def clean(poly):
    return Counter({term: coefficient for term, coefficient in poly.items()
                    if coefficient})


def add(*polys):
    answer = Counter()
    for poly in polys:
        answer.update(poly)
    return clean(answer)


def hafnian_polynomial(base, vertices, word):
    colour = dict(zip(vertices, word, strict=True))
    answer = Counter()
    for matching in base.perfect_matchings(vertices):
        answer[monomial(*(q_name(u, v, colour[u], colour[v])
                          for u, v in matching))] += 1
    return clean(answer)


def odd_fixed_star(base, hole, colour, word):
    if word[hole] != colour:
        return Counter()
    complement = tuple(site for site in SITES if site != hole)
    return hafnian_polynomial(
        base, complement, tuple(word[site] for site in complement))


def ca_row(base, word):
    """P_t(q^[2]+Q_c R_a q), with holes Pt@1,Qc@0,Ra@2."""
    chord = odd_fixed_star(base, 1, T, word)
    cubic = Counter()
    if word[1] == T and word[0] == C and word[2] == A:
        cubic[monomial(q_name(3, 4, word[3], word[4]))] += 1
    return add(chord, cubic)


def ra_row(base, word):
    """R_a q^[2], with R_a at hole 2 in colour a."""
    return odd_fixed_star(base, 2, A, word)


def tt_row(word):
    """P_t Q_t R_t q, with holes 1,0,4 and remaining edge 23."""
    if word[1] != T or word[0] != T or word[4] != T:
        return Counter()
    return Counter({monomial(q_name(2, 3, word[2], word[3])): 1})


def reduce_tt(poly):
    """Use q23:22=1 and q23:ab=0 for (a,b)!=(2,2)."""
    answer = Counter()
    for factors, coefficient in poly.items():
        kept = []
        killed = False
        for factor in factors:
            if factor.startswith("q23:"):
                if factor != q_name(2, 3, T, T):
                    killed = True
                    break
                continue
            kept.append(factor)
        if not killed:
            answer[tuple(kept)] += coefficient
    return clean(answer)


def main():
    pin_dependencies()
    base = importlib.import_module(
        "verify_h3_one_bad_common_q_cap_extraction_boundary")

    # The literal tt target row fixes the entire decorated 23 block.
    tt_equations = {}
    for a, b in itertools.product(range(3), repeat=2):
        word = (T, T, a, b, T)
        polynomial = tt_row(word)
        expected = Counter({monomial(q_name(2, 3, a, b)): 1})
        require(polynomial == expected,
                f"the tt block equation changed at {(a, b)}: {polynomial}")
        tt_equations[f"{a}{b}"] = (
            "1" if (a, b) == (T, T) else "0")

    equations_03 = {}
    equations_02 = {}
    equations_34 = {}
    for alpha, beta in itertools.product(range(3), repeat=2):
        # ca word (alpha,t,c,beta,c):
        # unit24*u_ab + v_alpha*w_beta = 0.
        word03 = (alpha, T, C, beta, C)
        actual03 = reduce_tt(ca_row(base, word03))
        expected03 = Counter({
            monomial(q_name(0, 3, alpha, beta),
                     q_name(2, 4, C, C)): 1,
            monomial(q_name(0, 2, alpha, C),
                     q_name(3, 4, beta, C)): 1,
        })
        require(actual03 == expected03,
                f"the q03 row changed at {(alpha, beta)}: {actual03}")
        equations_03[f"{alpha}{beta}"] = [list(term) for term in actual03]

        # ca word (alpha,t,c,a,a):
        # unit34*v_alpha + u_(alpha,a)*q24_(c,a) = 0.
        if beta == A:
            word02 = (alpha, T, C, A, A)
            actual02 = reduce_tt(ca_row(base, word02))
            expected02 = Counter({
                monomial(q_name(0, 2, alpha, C),
                         q_name(3, 4, A, A)): 1,
                monomial(q_name(0, 3, alpha, A),
                         q_name(2, 4, C, A)): 1,
            })
            require(actual02 == expected02,
                    f"the q02 repair row changed at {alpha}: {actual02}")
            equations_02[str(alpha)] = [list(term) for term in actual02]

        # Ra word (a,a,a,beta,c):
        # unit01*w_beta + u_(a,beta)*q14_(a,c)
        #                    + q04_(a,c)*q13_(a,beta) = 0.
        if alpha == A:
            word34 = (A, A, A, beta, C)
            actual34 = ra_row(base, word34)
            expected34 = Counter({
                monomial(q_name(0, 1, A, A),
                         q_name(3, 4, beta, C)): 1,
                monomial(q_name(0, 3, A, beta),
                         q_name(1, 4, A, C)): 1,
                monomial(q_name(0, 4, A, C),
                         q_name(1, 3, A, beta)): 1,
            })
            require(actual34 == expected34,
                    f"the q34 repair row changed at {beta}: {actual34}")
            equations_34[str(beta)] = [list(term) for term in actual34]

    require((len(equations_03), len(equations_02), len(equations_34))
            == (9, 3, 3), "the contraction row-family count changed")

    units = {
        q_name(2, 4, C, C),
        q_name(3, 4, A, A),
        q_name(0, 1, A, A),
    }
    require(units == {"q24:11", "q34:00", "q01:00"},
            f"the three localized units changed: {units}")

    # Completed-local ideal bookkeeping.  Let I=(u_ab), V=(v_alpha),
    # W=(w_beta), and m be the maximal ideal of all zero-at-base cells.
    # The exact equations give
    #   V subset m I,
    #   W subset m I + m^2,
    #   I subset V W.
    # Therefore I subset (mI)(mI+m^2) subset m^3 I, since I subset m.
    # Nakayama (equivalently Krull intersection) gives I=0.
    containments = (
        "V subset m*I",
        "W subset m*I + m^2",
        "I subset V*W",
        "I subset m^2*I^2 + m^3*I",
        "I subset m^3*I",
        "I=0 by Nakayama",
    )
    require(2 + 1 == 3 and 3 >= 1,
            "the m-adic contraction exponent changed")

    # A direct coefficient audit of the active-pencil boundary: every q03
    # decoration would create a distinct clean-error word, so I=0 is exactly
    # the needed all-order stability statement.
    error_words = {
        f"{alpha}{beta}": f"{alpha}{T}{A}{beta}{T}{A}"
        for alpha, beta in itertools.product(range(3), repeat=2)
    }
    require(len(set(error_words.values())) == 9,
            "two q03 error coordinates merged")

    ledger = {
        "dependencies": PINS,
        "normal_form": {
            "fixed_stars": ("Pt@1:t", "Qc@0:c", "Ra@2:a",
                            "Qt@0:t", "Rt@4:t"),
            "fixed_directs": ("Dca=1", "Dtt=0", "Dpr=Ecc"),
            "localized_units": sorted(units),
            "arbitrary": "all internal q cells",
        },
        "tt_block": tt_equations,
        "row_families": {
            "q03": equations_03,
            "q02": equations_02,
            "q34": equations_34,
        },
        "completed_local_certificate": {
            "I": "(q03:ab for all nine decorations)",
            "V": "(q02:a1 for a=0,1,2)",
            "W": "(q34:b1 for b=0,1,2)",
            "containments": containments,
            "contraction_power": 3,
        },
        "active_pencil_error_words": error_words,
        "verdict": (
            "no later decorated q03 cell exists on the completed literal "
            "same-hole normal-form branch; the active-clean pencil of "
            "c85ff47 is stable to arbitrary higher internal-q support"
        ),
        "scope": (
            "all-order complete-local statement with arbitrary internal q, "
            "but fixed same-hole endpoint-star/direct normal form and the "
            "three displayed base units.  Endpoint-star deformations or "
            "loss of those units are separate branches"
        ),
    }
    payload = json.dumps(ledger, sort_keys=True, separators=(",", ":"))
    digest = sha256(payload.encode()).hexdigest()
    if EXPECTED_LEDGER_SHA256 != "TO_BE_FILLED":
        require(digest == EXPECTED_LEDGER_SHA256,
                f"the edge03 stability ledger changed: {digest}")

    print("h=3 one-bad same-hole edge03 Nakayama stability: PASS")
    print("literal row families: q03/q02/q34 = 9/3/3")
    print("completed-local contraction: I subset m^3 I")
    print("verdict: I=(all nine q03 decorations)=0")
    print("active-clean pencil stable for arbitrary higher internal-q support")
    print(f"sha256: {digest}")


if __name__ == "__main__":
    main()
