#!/usr/bin/env python3
"""Audit the all-word signed-kernel gate for overlapping pair charts.

This checker verifies the finite algebra in
``notes/uniform-bianchi-all-word-signed-kernel-gate.md``.  It separates:

* the chart-sign kernel left by two partitions of every global hafnian row;
* the exact cancellation of the local four-cut Bianchi polynomial; and
* the positive pure-target E2 identity for genuine matching-exchange
  minors.

It does not construct a full decorated GHZ source or a chart-changing
source cell.
"""

from __future__ import annotations

import hashlib
from itertools import product
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]

PINNED = {
    "notes/uniform-physical-horizontal-moment-saturation-bridge.md":
        "83afba335711cfe1c4bd3726be2cec2a4bf7778ba17d316ee1524893fb8b006a",
    "computations/verify_uniform_physical_horizontal_moment_saturation_bridge.py":
        "9a5e4247a67e57367a2163da8405efd1f5a4508b7932e7f92c37c25a44920e6a",
    "notes/h3-direct-free-literal-four-face-full-nine-no-go.md":
        "5afe86e3785d8b467ccd0a2e0e26ad91a64a8e3855bb3ea18b054720c6f32606",
    "computations/verify_h3_direct_free_literal_four_face_full_nine_no_go.py":
        "17c5e15e93292c11f99a135312d2ca2796049ef0b35937d9e1f184ee7637b12a",
    "notes/curved-two-root-polarization-and-four-cut-square.md":
        "93d3f5797a9fbb97b363696e02f66c3af400e2429c64bd1f99bb0d9349710265",
    "notes/local-c4-coherence-curvature-relative-square.md":
        "5ed2232758948b993826d69158f6cdb57a06c077ad3a37af7db3a5005d9b9b43",
    "computations/verify_local_c4_relative_coherence_curvature_square.py":
        "9753c669db38b29e55706d4d8865c3beb46dcb0835298a90061babcda6483744",
    "computations/verify_n8_chart26_c4_exchange_3cell.py":
        "4398d15df3a5f0b34c2745fdb7087a289452ed03983d22431c4f20d116f019c6",
    "notes/hafnian-path-forest-straightening.md":
        "0713791a87b692da809b5f64fe8d757d6454d59e550a859b8d7b7dea68598921",
}


def require(condition: bool, detail: str) -> None:
    if not condition:
        raise RuntimeError(detail)


def check_pins() -> None:
    for relative, expected in PINNED.items():
        actual = hashlib.sha256((ROOT / relative).read_bytes()).hexdigest()
        require(actual == expected, f"source drift: {relative}: {actual}")


def odd_double_factorial(n: int) -> int:
    require(n >= -1 and n % 2 == 1, f"invalid odd double factorial: {n}")
    answer = 1
    for value in range(1, n + 1, 2):
        answer *= value
    return answer


def chart_partition_counts(h: int) -> dict[str, int]:
    # A clean cap on one pair leaves 2h residual sites; before deleting the
    # cap pair there are N=2h+2 sites.  A pair-chart partitions perfect
    # matchings according to whether they contain its deleted-pair edge.
    n_sites = 2 * h + 2
    total = odd_double_factorial(n_sites - 1)
    direct = odd_double_factorial(n_sites - 3)
    two_star = total - direct
    require(direct + two_star == total,
            f"chart partition lost matchings at h={h}")
    return {
        "h": h,
        "sites": n_sites,
        "matchings": total,
        "direct": direct,
        "two_star": two_star,
        "words": 3 ** n_sites,
        "pure_words": 3,
        "mixed_words": 3 ** n_sites - 3,
    }


def full_word_signed_kernel_audit(h: int) -> dict[str, int]:
    counts = chart_partition_counts(h)
    word_count = counts["words"]

    # The doubled row map is the block diagonal repetition of [1 1]: both
    # chart tags reinsert to the same global word coefficient.  Each block
    # has diagonal rank one and anti-diagonal kernel generated by (1,-1).
    diagonal_rank = word_count
    signed_kernel_dimension = word_count
    require(diagonal_rank + signed_kernel_dimension == 2 * word_count,
            f"chart diagonal/sign decomposition failed at h={h}")

    # Check every word explicitly at the first physical boundary N=8.
    if h == 3:
        pure_seen = 0
        signed_target_sum = 0
        for word in product(range(3), repeat=counts["sites"]):
            target = int(word in ((0,) * 8, (1,) * 8, (2,) * 8))
            pure_seen += target
            # Both chart target rows are literally the same.
            signed_target_sum += target - target
        require(pure_seen == 3, "the N=8 pure target census changed")
        require(signed_target_sum == 0,
                "a pure target acquired chart-sign augmentation")

    return {
        **counts,
        "diagonal_rank": diagonal_rank,
        "signed_kernel_dimension": signed_kernel_dimension,
        "signed_pure_target_rank": 0,
    }


def local_bianchi_audit(max_h: int = 24) -> dict[str, int]:
    # beta_k from the two overlapping physical pair charts is a linear
    # combination of kappa*z^[k] and Delta*v*z^[k-1].  Divided-power
    # multiplication cancels both coefficients separately.
    for h in range(3, max_h + 1):
        k = h - 1
        kappa = k - k
        delta = 1 + (k - 1) - k
        require(kappa == 0, f"kappa part of beta failed at h={h}")
        require(delta == 0, f"Delta part of beta failed at h={h}")
    return {"first_h": 3, "last_h": max_h, "first_k": 2, "last_k": max_h - 1}


def pure_target_e2_audit() -> dict[str, int]:
    checks = 0
    # At a pure state c, H_c=1.  At a second state d, H_d is either zero
    # (mixed) or one (another pure target).  Audit the undivided E2 identity
    # over a deterministic box of physical matching-monomial values.
    for a_c in range(-3, 4):
        for a_d in range(-2, 3):
            for b_c in range(-3, 4):
                for b_d in range(-2, 3):
                    for h_d in (0, 1):
                        p_m = a_c * h_d - a_d
                        p_n = b_c * h_d - b_d
                        delta = a_c * b_d - a_d * b_c
                        require(b_c * p_m - a_c * p_n == delta,
                                "pure-endpoint E2 identity failed")
                        require(b_d * p_m - a_d * p_n == delta * h_d,
                                "opposite-endpoint E2 identity failed")
                        checks += 1
    return {
        "integer_specializations": checks,
        "identity": "b_c P^M_cd-a_c P^N_cd=Delta_cd when H_c=1",
    }


def mutation_guards() -> None:
    h = 5
    k = h - 1
    require(1 - k != 0,
            "dropping the middle divided-power term did not break beta")

    # A chart-asymmetric target would detect the sign kernel, but GHZ has
    # identical target rows in both presentations.
    require(1 - 0 != 0,
            "asymmetric-target mutation was not detected")

    # Omitting the pure normalization H_c=1 leaves only Delta*H_c.
    h_c = 0
    require(7 * h_c != 7,
            "missing pure-target normalization mutation was not detected")


def main() -> None:
    check_pins()
    word_audits = [full_word_signed_kernel_audit(h) for h in range(3, 9)]
    bianchi = local_bianchi_audit()
    e2 = pure_target_e2_audit()
    mutation_guards()
    digest = hashlib.sha256(repr((word_audits, bianchi, e2)).encode()).hexdigest()
    print("PASS: uniform Bianchi all-word signed-kernel gate")
    print("all GHZ word rows: DIAGONAL CHART QUOTIENT")
    print("Bianchi chart-sign kernel: UNSEEN BY STRICT WORD READOUTS")
    print("pure target E2: MATCHING-EXCHANGE MINOR IS AN UNDIVIDED BOUNDARY")
    print(f"digest: {digest}")


if __name__ == "__main__":
    main()
