#!/usr/bin/env python3
"""Exact audits for cauchy-shared-matrix-diagonal-obstruction.md."""

from __future__ import annotations

import sympy as sp


def sym(i: int, j: int) -> sp.Matrix:
    matrix = sp.zeros(3)
    matrix[i, j] = 1
    matrix[j, i] = 1
    return matrix


def rotation(i: int, j: int) -> sp.Matrix:
    matrix = sp.zeros(3)
    matrix[i, j] = 1
    matrix[j, i] = -1
    return matrix


TRACELESS_BASIS = (
    sp.diag(1, -1, 0),
    sp.diag(1, 1, -2),
    sym(0, 1),
    sym(0, 2),
    sym(1, 2),
)


def traceless_coordinates(matrix: sp.Matrix) -> sp.Matrix:
    assert matrix == matrix.T
    assert sp.trace(matrix) == 0
    return sp.Matrix(
        [
            (matrix[0, 0] - matrix[1, 1]) / 2,
            (matrix[0, 0] + matrix[1, 1]) / 2,
            matrix[0, 1],
            matrix[0, 2],
            matrix[1, 2],
        ]
    )


def infinitesimal_action(generator: sp.Matrix) -> sp.Matrix:
    columns = []
    for basis_vector in TRACELESS_BASIS:
        image = generator * basis_vector + basis_vector * generator.T
        columns.append(traceless_coordinates(image))
    return sp.Matrix.hstack(*columns)


def matrix_span_rank(matrices: list[sp.Matrix]) -> int:
    return sp.Matrix.hstack(*(matrix.reshape(25, 1) for matrix in matrices)).rank()


def audit_rotation_algebra() -> None:
    actions = [
        infinitesimal_action(rotation(0, 1)),
        infinitesimal_action(rotation(0, 2)),
        infinitesimal_action(rotation(1, 2)),
    ]

    # Close the rational span under right multiplication by the three
    # generators.  Starting from I, this enumerates the associative algebra
    # generated by the infinitesimal rotations.
    algebra = [sp.eye(5)]
    rank = 1
    while True:
        candidates = algebra + [word * action for word in algebra for action in actions]
        independent: list[sp.Matrix] = []
        for candidate in candidates:
            if matrix_span_rank(independent + [candidate]) > len(independent):
                independent.append(candidate)
        new_rank = len(independent)
        algebra = independent
        if new_rank == rank:
            break
        rank = new_rank
    assert rank == 25


def audit_off_diagonal_trace_intersection() -> None:
    a, b, c = sp.symbols("a b c", nonzero=True)
    H = sp.Matrix([[0, a, b], [a, 0, c], [b, c, 0]])
    assert sp.factor(H.det()) == 2 * a * b * c
    Hinv = H.inv()
    off_diagonal_basis = (sym(0, 1), sym(0, 2), sym(1, 2))
    trace_row = sp.Matrix(
        [[sp.simplify(sp.trace(Hinv * vector)) for vector in off_diagonal_basis]]
    )
    assert trace_row == sp.Matrix([[1 / a, 1 / b, 1 / c]])
    assert trace_row.rank() == 1
    assert sp.simplify(sp.trace(Hinv * H)) == 3
    assert sp.Matrix.hstack(
        *(vector.reshape(9, 1) for vector in off_diagonal_basis)
    ).rank() == 3
    # Hence the kernel of the invariant trace on the off-diagonal
    # three-space has dimension exactly two.
    assert 3 - trace_row.rank() == 2


def main() -> None:
    audit_off_diagonal_trace_intersection()
    audit_rotation_algebra()
    print("Cauchy shared-matrix diagonal obstruction: PASS")


if __name__ == "__main__":
    main()
