#!/usr/bin/env python3
"""Clean-room exact audit of the adjacent A25-line extension.

This file imports no project module and does not consume data emitted by the
primary verifier.  It freshly reconstructs endpoint-ordered matching tensors,
cofactors, insertion cylinders, the six-character torus, all support charts,
safe projected common normals, the shared-star fibre equations, and the 33
characteristic-zero unit ideals.

The computational route is deliberately independent: perfect matchings are
generated by a rightmost-vertex tuple recursion; subspace intersections use
double annihilators and exact least-coordinate Gauss-Jordan elimination; and
the Singular rings use a reversed, interleaved star-variable order.
"""

from __future__ import annotations

from collections import Counter, defaultdict
from concurrent.futures import ThreadPoolExecutor, as_completed
from dataclasses import dataclass
from fractions import Fraction
from functools import lru_cache
from itertools import combinations, product
import os
import shutil
import subprocess
import time


Q = Fraction
COLOURS = (0, 1, 2)
INTERIOR = tuple(range(6))
ALL_SITES = tuple(range(8))
WORDS6 = tuple(product(COLOURS, repeat=6))

# First colour always belongs to the lower endpoint.  The final entry is the
# E00 base point of A25; its E11 direction is inserted separately with t.
BASE_SOURCES = (
    (0, 1, 0, 0),
    (4, 5, 0, 0),
    (0, 2, 1, 1),
    (1, 4, 1, 1),
    (0, 4, 2, 2),
    (1, 3, 2, 2),
    (3, 5, 1, 0),
    (2, 5, 0, 0),
)
T_SOURCE = (2, 5, 1, 1)

CELLS = tuple(product(COLOURS, repeat=2))
CELL_NAMES = tuple(f"x{a}{b}" for a, b in CELLS)
CELL_INDEX = {cell: index for index, cell in enumerate(CELLS)}
X00, X01, X02, X10, X11, X12, X20, X21, X22 = range(9)
OUTSIDE_ORDER = (X10, X12, X20, X22)
OLD_GLOBAL_CELLS = (X00, X01, X02, X11, X21)
X_COFACTOR_PAIRS = ((0, 1), (0, 5), (1, 5), (4, 5))
T_COFACTOR_PAIRS = ((0, 3), (0, 4), (1, 3), (3, 4))

UPLUS_WORDS = (
    (1, 2, 1, 2, 0, 0),
    (1, 1, 1, 1, 1, 0),
    (2, 2, 0, 2, 2, 0),
)
E_WORD = (0, 0, 2, 1, 0, 0)
LOCK_WORD = (0, 0, 1, 1, 0, 0)
V_T_WORDS = (
    (1, 2, 1, 2, 0, 0),
    (0, 0, 1, 1, 0, 0),
    (0, 0, 1, 2, 0, 0),
    (0, 0, 2, 2, 0, 0),
    (1, 1, 1, 1, 1, 0),
    (2, 2, 1, 2, 2, 1),
)

# X weights in (r0,r1,r2,c0,c2); t has the independent sixth weight tau.
X_WEIGHTS = (
    (1, 0, 0, 1, 0),
    (2, 0, 0, 0, 0),
    (1, 0, 0, 0, 1),
    (0, 1, 0, 1, 0),
    (1, 1, 0, 0, 0),
    (0, 1, 0, 0, 1),
    (0, 0, 1, 1, 0),
    (1, 0, 1, 0, 0),
    (0, 0, 1, 0, 1),
)


@dataclass(frozen=True)
class OutsideChart:
    name: str
    first: int
    retained: frozenset[int]
    optional: tuple[int, ...]
    expected_normal_dimension: int


OUTSIDE_CHARTS = (
    OutsideChart("x10", X10, frozenset((X10, X11, X21, X22)),
                 (X11, X21, X22), 2),
    OutsideChart("x12", X12, frozenset((X12, X11, X21, X22)),
                 (X11, X21, X22), 1),
    OutsideChart("x20", X20, frozenset((X10, X20, X11, X21, X22)),
                 (X11, X21, X22), 2),
    OutsideChart("x22", X22,
                 frozenset((X10, X12, X20, X11, X21, X22)),
                 (X11, X21), 1),
)
CHART_BY_FIRST = {chart.first: chart for chart in OUTSIDE_CHARTS}

OUTSIDE_EXPECTED_GENERATORS = {
    "x10": {
        (0, 0): 380, (0, 1): 484, (2, 0): 432, (2, 1): 536,
        (4, 0): 492, (4, 1): 596, (6, 0): 544, (6, 1): 648,
    },
    "x12": {
        (0, 0): 384, (0, 1): 488, (2, 0): 436, (2, 1): 540,
        (4, 0): 496, (4, 1): 600, (6, 0): 548,
    },
    "x20": {
        (0, 0): 440, (0, 1): 544, (2, 0): 492, (2, 1): 596,
        (4, 0): 552, (4, 1): 656, (6, 0): 604, (6, 1): 708,
    },
    "x22": {
        (4, 0): 496, (4, 1): 600, (6, 0): 548, (6, 1): 652,
    },
}


@dataclass(frozen=True)
class OldClass:
    name: str
    maximal_mask: int
    mandatory_bits: tuple[int, ...]
    active_colours: tuple[int, int]
    expected_killed: int
    expected_normal_dimension: int
    expected_generators: int


OLD_CLASSES = (
    OldClass("old_no_x00", 30, (), (0, 2), 141, 1, 292),
    OldClass("old_x00_no_x11_no_x21", 7, (), (1, 2), 107, 1, 376),
    OldClass("old_x00_x21_no_x11", 23, (0, 4), (1, 2), 72, 2, 612),
    OldClass("old_x00_x11_no_x21", 15, (0, 3), (1, 2), 71, 3, 560),
    OldClass("old_x00_x11_x21", 31, (0, 3, 4), (1, 2), 71, 3, 664),
)


def add(vector, key, value):
    value = Q(value)
    total = vector.get(key, Q(0)) + value
    if total:
        vector[key] = total
    else:
        vector.pop(key, None)


def linear_combination(terms):
    answer = {}
    for vector, scalar in terms:
        for key, value in vector.items():
            add(answer, key, Q(scalar) * value)
    return answer


def subtract(left, right):
    return linear_combination(((left, Q(1)), (right, Q(-1))))


def project_vector(vector, killed):
    return {key: value for key, value in vector.items() if key not in killed}


def rref_basis(vectors, coordinates=None):
    """Exact least-coordinate Gauss-Jordan basis in a supplied ambient set."""
    rows = [
        {key: Q(value) for key, value in vector.items() if value}
        for vector in vectors
    ]
    rows = [row for row in rows if row]
    if coordinates is None:
        coordinates = sorted(set().union(*(set(row) for row in rows))) if rows else ()
    else:
        coordinates = tuple(coordinates)
    active = 0
    pivots = []
    for coordinate in coordinates:
        found = next(
            (index for index in range(active, len(rows))
             if rows[index].get(coordinate, Q(0))),
            None,
        )
        if found is None:
            continue
        rows[active], rows[found] = rows[found], rows[active]
        pivot_value = rows[active][coordinate]
        rows[active] = {
            key: value / pivot_value for key, value in rows[active].items()
        }
        for index, row in enumerate(rows):
            if index == active:
                continue
            multiple = row.get(coordinate, Q(0))
            if not multiple:
                continue
            for key, value in rows[active].items():
                add(row, key, -multiple * value)
        pivots.append(coordinate)
        active += 1
        if active == len(rows):
            break
    assert all(not row for row in rows[active:])
    return tuple(rows[:active]), tuple(pivots)


def rank(vectors):
    return len(rref_basis(vectors)[0])


def annihilator(vectors, coordinates):
    """Basis of the orthogonal complement in the named coordinate space."""
    coordinates = tuple(coordinates)
    rows, pivots = rref_basis(vectors, coordinates)
    pivot_set = set(pivots)
    answer = []
    for free in coordinates:
        if free in pivot_set:
            continue
        functional = {free: Q(1)}
        for row, pivot in zip(rows, pivots):
            coefficient = -row.get(free, Q(0))
            if coefficient:
                functional[pivot] = coefficient
        answer.append(functional)
    for row in vectors:
        for functional in answer:
            assert sum(
                value * functional.get(key, Q(0))
                for key, value in row.items()
            ) == 0
    return tuple(answer)


def intersection_two(left, right):
    """Use (U intersection V)^perp = U^perp + V^perp exactly."""
    left_basis = rref_basis(left)[0]
    right_basis = rref_basis(right)[0]
    if not left_basis or not right_basis:
        return ()
    coordinates = tuple(sorted(
        set().union(*(set(row) for row in left_basis + right_basis))
    ))
    dual_left = annihilator(left_basis, coordinates)
    dual_right = annihilator(right_basis, coordinates)
    return rref_basis(annihilator(dual_left + dual_right, coordinates))[0]


def intersection_many(spaces):
    result = rref_basis(spaces[0])[0]
    for space in spaces[1:]:
        result = intersection_two(result, space)
    return result


def in_span(vector, space):
    if not vector:
        return True
    return rank(tuple(space) + (vector,)) == rank(space)


def same_span(left, right):
    return rank(left) == rank(right) and all(in_span(row, right) for row in left)


def matrix_rank(rows):
    return rank(tuple(
        {column: Q(value) for column, value in enumerate(row) if value}
        for row in rows
    ))


def nullspace_numeric(rows, width):
    sparse = tuple(
        {column: Q(value) for column, value in enumerate(row) if value}
        for row in rows
    )
    vectors = annihilator(sparse, tuple(range(width)))
    return tuple(
        tuple(vector.get(column, Q(0)) for column in range(width))
        for vector in vectors
    )


@lru_cache(maxsize=None)
def perfect_matchings(vertices):
    """Rightmost-vertex recursion; all returned edges are endpoint ordered."""
    vertices = tuple(vertices)
    if not vertices:
        return ((),)
    pivot = vertices[-1]
    answer = []
    for index, mate in enumerate(vertices[:-1]):
        rest = vertices[:index] + vertices[index + 1:-1]
        for tail in perfect_matchings(rest):
            answer.append(tail + ((mate, pivot),))
    return tuple(answer)


def internal_blocks(x_coefficients, t_value):
    blocks = defaultdict(dict)
    for left, right, colour_left, colour_right in BASE_SOURCES:
        blocks[left, right][colour_left, colour_right] = Q(1)
    if t_value:
        left, right, colour_left, colour_right = T_SOURCE
        blocks[left, right][colour_left, colour_right] = Q(t_value)
    for index, coefficient in enumerate(x_coefficients):
        if coefficient:
            blocks[2, 3][CELLS[index]] = Q(coefficient)
    return {edge: dict(cells) for edge, cells in blocks.items()}


def matching_tensor(vertices, blocks):
    vertices = tuple(vertices)
    position = {site: index for index, site in enumerate(vertices)}
    answer = {}
    for matching in perfect_matchings(vertices):
        choices = [tuple(blocks.get(edge, {}).items()) for edge in matching]
        if any(not options for options in choices):
            continue
        for selected in product(*choices):
            word = [-1] * len(vertices)
            coefficient = Q(1)
            for (left, right), ((left_colour, right_colour), value) in zip(
                matching, selected
            ):
                word[position[left]] = left_colour
                word[position[right]] = right_colour
                coefficient *= value
            add(answer, tuple(word), coefficient)
    return answer


def coefficients_for(indices, values=None):
    coefficients = [Q(0)] * 9
    if values is None:
        values = (Q(1),) * len(indices)
    for index, value in zip(indices, values):
        coefficients[index] = Q(value)
    return tuple(coefficients)


def mask_coefficients(mask):
    return tuple(Q(1) if mask & (1 << index) else Q(0) for index in range(9))


def insertion_columns(cut, x_coefficients, t_value):
    """Fixed list of 45 raw columns; its ordering differs from the primary."""
    blocks = internal_blocks(x_coefficients, t_value)
    five_sites = tuple(site for site in INTERIOR if site != cut)
    columns = []
    for hole in reversed(five_sites):
        rest = tuple(site for site in five_sites if site != hole)
        cofactor = matching_tensor(rest, blocks)
        for hole_colour in COLOURS:
            for cut_colour in COLOURS:
                vector = {}
                for rest_word, coefficient in cofactor.items():
                    assignment = dict(zip(rest, rest_word))
                    assignment[hole] = hole_colour
                    assignment[cut] = cut_colour
                    add(vector,
                        tuple(assignment[site] for site in INTERIOR),
                        coefficient)
                columns.append(vector)
    assert len(columns) == 45
    return tuple(columns)


def atom_map(x_coefficients, t_value):
    blocks = internal_blocks(x_coefficients, t_value)
    atoms = {}
    for right in reversed(INTERIOR):
        for left in reversed(tuple(site for site in INTERIOR if site < right)):
            rest = tuple(site for site in INTERIOR if site not in (left, right))
            cofactor = matching_tensor(rest, blocks)
            for rest_word, coefficient in cofactor.items():
                for right_colour in reversed(COLOURS):
                    for left_colour in reversed(COLOURS):
                        assignment = dict(zip(rest, rest_word))
                        assignment[left] = left_colour
                        assignment[right] = right_colour
                        word = tuple(assignment[site] for site in INTERIOR)
                        key = (word, left, left_colour, right, right_colour)
                        assert key not in atoms
                        atoms[key] = coefficient
    return atoms


def atoms_by_word(atoms):
    grouped = defaultdict(list)
    for (word, left, left_colour, right, right_colour), coefficient in atoms.items():
        grouped[word].append(
            (left, left_colour, right, right_colour, coefficient)
        )
    return {
        word: tuple(sorted(terms, reverse=True))
        for word, terms in grouped.items()
    }


def project_atoms(atoms, killed):
    return {key: value for key, value in atoms.items() if key[0] not in killed}


def projected_cylinder(cut, x_coefficients, t_value, killed):
    return rref_basis(
        tuple(project_vector(column, killed)
              for column in insertion_columns(cut, x_coefficients, t_value))
    )[0]


def four_cut_normal(x_coefficients, t_value, killed, final_cut):
    return intersection_many(tuple(
        projected_cylinder(cut, x_coefficients, t_value, killed)
        for cut in (2, 3, 4, final_cut)
    ))


def delta_map(one, zero):
    return {
        key: one.get(key, Q(0)) - zero.get(key, Q(0))
        for key in set(one) | set(zero)
        if one.get(key, Q(0)) != zero.get(key, Q(0))
    }


def output_blocks():
    zero_x = coefficients_for(())
    base_atoms = atom_map(zero_x, Q(0))
    x_blocks = []
    x_pairs = []
    for cell in range(9):
        delta = delta_map(atom_map(coefficients_for((cell,)), Q(0)), base_atoms)
        x_blocks.append(frozenset(key[0] for key in delta))
        x_pairs.append(tuple(sorted({(key[1], key[3]) for key in delta})))
    t_delta = delta_map(atom_map(zero_x, Q(1)), base_atoms)
    t_block = frozenset(key[0] for key in t_delta)
    t_pairs = tuple(sorted({(key[1], key[3]) for key in t_delta}))

    assert all(len(block) == 35 for block in x_blocks)
    assert all(left.isdisjoint(right)
               for left, right in combinations(x_blocks, 2))
    assert len(set().union(*x_blocks)) == 315
    assert all(pairs == X_COFACTOR_PAIRS for pairs in x_pairs)
    assert len(t_block) == 35
    assert t_pairs == T_COFACTOR_PAIRS
    assert tuple(len(t_block & x_blocks[index]) for index in (X10, X11, X12)) == (9, 9, 9)
    assert all(not (t_block & x_blocks[index])
               for index in (X00, X01, X02, X20, X21, X22))

    uplus = matching_tensor(INTERIOR, internal_blocks(zero_x, Q(0)))
    assert uplus == {word: Q(1) for word in UPLUS_WORDS}
    assert t_block.isdisjoint(uplus)
    assert (((0,) * 6) in t_block, ((1,) * 6) in t_block,
            ((2,) * 6) in t_block) == (False, True, False)
    for index, block in enumerate(x_blocks):
        for colour in COLOURS:
            assert (((colour,) * 6) in block) == (
                index == CELL_INDEX[(colour, colour)]
            )
    return tuple(x_blocks), t_block, uplus


def audit_no_mixed_terms_and_explicit_t():
    zero_x = coefficients_for(())
    h00 = matching_tensor(INTERIOR, internal_blocks(zero_x, Q(0)))
    a00 = atom_map(zero_x, Q(0))
    c00 = {cut: insertion_columns(cut, zero_x, Q(0)) for cut in INTERIOR}
    for cell in range(9):
        x = coefficients_for((cell,))
        h10 = matching_tensor(INTERIOR, internal_blocks(x, Q(0)))
        h01 = matching_tensor(INTERIOR, internal_blocks(zero_x, Q(1)))
        h11 = matching_tensor(INTERIOR, internal_blocks(x, Q(1)))
        assert not subtract(subtract(h11, h10), subtract(h01, h00))

        a10 = atom_map(x, Q(0))
        a01 = atom_map(zero_x, Q(1))
        a11 = atom_map(x, Q(1))
        for key in set(a00) | set(a10) | set(a01) | set(a11):
            assert (a11.get(key, 0) - a10.get(key, 0)
                    - a01.get(key, 0) + a00.get(key, 0)) == 0
        for cut in INTERIOR:
            c10 = insertion_columns(cut, x, Q(0))
            c01 = insertion_columns(cut, zero_x, Q(1))
            c11 = insertion_columns(cut, x, Q(1))
            for v00, v10, v01, v11 in zip(c00[cut], c10, c01, c11):
                assert not subtract(subtract(v11, v10), subtract(v01, v00))

    # A separate non-binary affine check at t=2 and a dense rational X.
    dense_x = tuple(Q(19 + 2 * index, 31 + index) for index in range(9))
    h0 = matching_tensor(INTERIOR, internal_blocks(dense_x, Q(0)))
    h1 = matching_tensor(INTERIOR, internal_blocks(dense_x, Q(1)))
    h2 = matching_tensor(INTERIOR, internal_blocks(dense_x, Q(2)))
    assert h2 == linear_combination(((h1, Q(2)), (h0, Q(-1))))
    a0, a1, a2 = (atom_map(dense_x, Q(t)) for t in (0, 1, 2))
    for key in set(a0) | set(a1) | set(a2):
        assert a2.get(key, 0) == 2 * a1.get(key, 0) - a0.get(key, 0)
    for cut in INTERIOR:
        c0 = insertion_columns(cut, dense_x, Q(0))
        c1 = insertion_columns(cut, dense_x, Q(1))
        c2 = insertion_columns(cut, dense_x, Q(2))
        for v0, v1, v2 in zip(c0, c1, c2):
            assert v2 == linear_combination(((v1, Q(2)), (v0, Q(-1))))


def audit_torus_and_moduli():
    # Independent 18-variable stabilizer kernel calculation.
    coordinate = {(site, colour): 3 * site + colour
                  for site in INTERIOR for colour in COLOURS}
    fixed_rows = []
    for left, right, left_colour, right_colour in BASE_SOURCES:
        row = [0] * 18
        row[coordinate[left, left_colour]] = 1
        row[coordinate[right, right_colour]] = 1
        fixed_rows.append(row)
    assert matrix_rank(fixed_rows) == 8
    kernel = nullspace_numeric(fixed_rows, 18)
    assert len(kernel) == 10

    def character_values(edge_cell):
        left, right, left_colour, right_colour = edge_cell
        return tuple(
            vector[coordinate[left, left_colour]]
            + vector[coordinate[right, right_colour]]
            for vector in kernel
        )

    x_character_rows = [character_values((2, 3, a, b)) for a, b in CELLS]
    t_character = character_values(T_SOURCE)
    assert matrix_rank(x_character_rows) == 5
    assert matrix_rank(x_character_rows + [t_character]) == 6

    census = Counter()
    for mask in range(1 << 9):
        support_rows = [X_WEIGHTS[index] for index in range(9)
                        if mask & (1 << index)]
        census[len(support_rows) - matrix_rank(support_rows)] += 1
    assert tuple(census[index] for index in range(5)) == (328, 132, 42, 9, 1)
    assert set(census) == set(range(5))
    for old_mask in range(1 << 5):
        old_rows = [
            X_WEIGHTS[OLD_GLOBAL_CELLS[bit]]
            for bit in range(5) if old_mask & (1 << bit)
        ]
        assert matrix_rank(old_rows) == len(old_rows)

    # Literal six-character extension and target preservation.
    zero = (0,) * 6
    exponents = {(site, colour): zero
                 for site in ALL_SITES for colour in COLOURS}
    exponents[2, 0] = exponents[3, 1] = exponents[4, 0] = (1, 0, 0, 0, 0, 0)
    exponents[5, 0] = (-1, 0, 0, 0, 0, 0)
    exponents[3, 0] = (0, 0, 0, 1, 0, 0)
    exponents[3, 2] = (0, 0, 0, 0, 1, 0)
    exponents[2, 1] = (0, 1, 0, 0, 0, 0)
    exponents[2, 2] = (0, 0, 1, 0, 0, 0)
    exponents[0, 1] = (0, -1, 0, 0, 0, 0)
    exponents[1, 2] = (0, 0, 0, 0, -1, 0)
    exponents[5, 1] = (0, -1, 0, 0, 0, 1)

    def plus(*rows):
        return tuple(sum(row[column] for row in rows) for column in range(6))

    for left, right, left_colour, right_colour in BASE_SOURCES:
        assert plus(exponents[left, left_colour],
                    exponents[right, right_colour]) == zero
    observed_x = tuple(
        plus(exponents[2, a], exponents[3, b])[:5] for a, b in CELLS
    )
    assert observed_x == X_WEIGHTS
    assert plus(exponents[2, 1], exponents[5, 1]) == (0, 0, 0, 0, 0, 1)
    for colour in COLOURS:
        interior_total = plus(*(exponents[site, colour] for site in INTERIOR))
        exponents[6, colour] = zero
        exponents[7, colour] = tuple(-entry for entry in interior_total)
        assert plus(*(exponents[site, colour] for site in ALL_SITES)) == zero


def first_outside(mask):
    for index in OUTSIDE_ORDER:
        if mask & (1 << index):
            return index
    return None


def outside_signature(mask):
    d = 2 * bool(mask & (1 << X11)) + 4 * bool(mask & (1 << X22))
    b = int(bool(mask & (1 << X21)))
    return d, b


def representative_support(chart, signature):
    d, b = signature
    support = {chart.first}
    if d & 2:
        support.add(X11)
    if d & 4:
        support.add(X22)
    if b:
        support.add(X21)
    return frozenset(support)


def audit_support_partition():
    masks_by_chart = defaultdict(list)
    old_masks = []
    for mask in range(1 << 9):
        first = first_outside(mask)
        if first is None:
            old_masks.append(mask)
        else:
            masks_by_chart[CHART_BY_FIRST[first].name].append(mask)
    assert len(old_masks) == 32
    assert tuple(len(masks_by_chart[chart.name]) for chart in OUTSIDE_CHARTS) == (
        256, 128, 64, 32
    )

    finite = []
    cross_masks = []
    for chart in OUTSIDE_CHARTS:
        signatures = sorted({outside_signature(mask)
                             for mask in masks_by_chart[chart.name]})
        expected = set(OUTSIDE_EXPECTED_GENERATORS[chart.name])
        if chart.name == "x12":
            assert set(signatures) == expected | {(6, 1)}
        else:
            assert set(signatures) == expected
        for signature in signatures:
            support = representative_support(chart, signature)
            weight_rows = [X_WEIGHTS[index] for index in sorted(support)]
            if chart.name == "x12" and signature == (6, 1):
                assert support == frozenset((X11, X12, X21, X22))
                assert matrix_rank(weight_rows) == 3
                rectangle = (X11, X12, X21, X22)
                relation = (-1, 1, 1, -1)
                assert all(
                    sum(relation[row] * X_WEIGHTS[rectangle[row]][column]
                        for row in range(4)) == 0
                    for column in range(5)
                )
                assert matrix_rank([X_WEIGHTS[index]
                                    for index in (X12, X11, X22)]) == 3
                cross_masks.extend(
                    mask for mask in masks_by_chart[chart.name]
                    if outside_signature(mask) == signature
                )
            else:
                assert matrix_rank(weight_rows) == len(weight_rows)
                # Adding normalized nonzero t increases both ranks by one.
                assert matrix_rank([tuple(row) + (0,) for row in weight_rows]
                                   + [(0, 0, 0, 0, 0, 1)]) == len(weight_rows) + 1
                finite.append((chart, signature, support))
    assert len(finite) == 27
    assert len(cross_masks) == 16
    return masks_by_chart, tuple(old_masks), tuple(finite), tuple(cross_masks)


def killed_for_outside(chart, x_blocks):
    omitted = set(range(9)) - set(chart.retained)
    return frozenset().union(*(x_blocks[index] for index in omitted))


def old_class_name(old_mask):
    if not old_mask & 1:
        return "old_no_x00"
    has_x11 = bool(old_mask & (1 << 3))
    has_x21 = bool(old_mask & (1 << 4))
    if not has_x11:
        return "old_x00_x21_no_x11" if has_x21 else "old_x00_no_x11_no_x21"
    return "old_x00_x11_x21" if has_x21 else "old_x00_x11_no_x21"


def old_global_support(old_mask):
    return frozenset(
        OLD_GLOBAL_CELLS[bit] for bit in range(5) if old_mask & (1 << bit)
    )


def old_killed(spec, x_blocks, uplus):
    killed = set(uplus)
    for bit in range(5):
        if spec.maximal_mask & (1 << bit):
            killed.update(x_blocks[OLD_GLOBAL_CELLS[bit]])
    for bit in spec.mandatory_bits:
        killed.difference_update(x_blocks[OLD_GLOBAL_CELLS[bit]])
    return frozenset(killed)


def audit_killed_coefficients(x_blocks, t_block, uplus):
    zero_x = coefficients_for(())
    expected_t_overlap_killed = {"x10": 9, "x12": 9, "x20": 9, "x22": 0}
    for chart in OUTSIDE_CHARTS:
        killed = killed_for_outside(chart, x_blocks)
        assert len(t_block & killed) == expected_t_overlap_killed[chart.name]
        baseline_h = matching_tensor(INTERIOR, internal_blocks(zero_x, Q(1)))
        baseline_atoms = atom_map(zero_x, Q(1))
        baseline_columns = {
            cut: insertion_columns(cut, zero_x, Q(1)) for cut in INTERIOR
        }
        for cell in set(range(9)) - set(chart.retained):
            one_x = coefficients_for((cell,))
            assert not project_vector(
                subtract(matching_tensor(INTERIOR,
                                         internal_blocks(one_x, Q(1))),
                         baseline_h), killed)
            one_atoms = atom_map(one_x, Q(1))
            for key in set(baseline_atoms) | set(one_atoms):
                if one_atoms.get(key, 0) != baseline_atoms.get(key, 0):
                    assert key[0] in killed
            for cut in INTERIOR:
                one_columns = insertion_columns(cut, one_x, Q(1))
                for baseline, observed in zip(baseline_columns[cut], one_columns):
                    assert not project_vector(subtract(observed, baseline), killed)

    # Repeat the same coefficientwise check for each old-locus interval.
    for spec in OLD_CLASSES:
        killed = old_killed(spec, x_blocks, uplus)
        maximal = old_global_support(spec.maximal_mask)
        reference_x = coefficients_for(sorted(maximal))
        reference_h = project_vector(
            matching_tensor(INTERIOR, internal_blocks(reference_x, Q(1))), killed)
        reference_atoms = project_atoms(atom_map(reference_x, Q(1)), killed)
        reference_columns = {
            cut: tuple(project_vector(column, killed) for column in
                       insertion_columns(cut, reference_x, Q(1)))
            for cut in INTERIOR
        }
        members = [mask for mask in range(32) if old_class_name(mask) == spec.name]
        for mask in members:
            observed_x = coefficients_for(sorted(old_global_support(mask)))
            assert project_vector(
                matching_tensor(INTERIOR, internal_blocks(observed_x, Q(1))),
                killed) == reference_h
            assert project_atoms(atom_map(observed_x, Q(1)), killed) == reference_atoms
            for cut in INTERIOR:
                observed = tuple(project_vector(column, killed) for column in
                                 insertion_columns(cut, observed_x, Q(1)))
                assert observed == reference_columns[cut]


def audit_literal_eight_site_identity():
    x_coefficients = tuple(Q(41 + 5 * index, 67 + index) for index in range(9))
    t_value = Q(137, 79)
    p = {
        (boundary, site, colour): Q(211 + 61 * boundary + 7 * site + colour, 83)
        for boundary, site, colour in product(COLOURS, INTERIOR, COLOURS)
    }
    q = {
        (boundary, site, colour): Q(601 + 67 * boundary + 11 * site + colour, 89)
        for boundary, site, colour in product(COLOURS, INTERIOR, COLOURS)
    }
    direct = {
        (a, b): Q(1009 + 19 * a + 23 * b, 97)
        for a, b in product(COLOURS, repeat=2)
    }
    blocks = internal_blocks(x_coefficients, t_value)
    for site in INTERIOR:
        blocks[site, 6] = {
            (internal_colour, boundary_colour): p[
                boundary_colour, site, internal_colour
            ]
            for internal_colour, boundary_colour in product(COLOURS, repeat=2)
        }
        blocks[site, 7] = {
            (internal_colour, boundary_colour): q[
                boundary_colour, site, internal_colour
            ]
            for internal_colour, boundary_colour in product(COLOURS, repeat=2)
        }
    blocks[6, 7] = dict(direct)
    observed8 = matching_tensor(ALL_SITES, blocks)
    hs = matching_tensor(INTERIOR, internal_blocks(x_coefficients, t_value))
    grouped = atoms_by_word(atom_map(x_coefficients, t_value))
    for a, b in product(COLOURS, repeat=2):
        observed = {
            word[:6]: value for word, value in observed8.items()
            if word[6:] == (a, b)
        }
        predicted = linear_combination(((hs, direct[a, b]),))
        for word, terms in grouped.items():
            for left, left_colour, right, right_colour, coefficient in terms:
                add(predicted, word, coefficient * (
                    p[a, left, left_colour] * q[b, right, right_colour]
                    + p[a, right, right_colour] * q[b, left, left_colour]
                ))
        assert observed == predicted


def qtext(value):
    value = Q(value)
    if value.denominator == 1:
        return str(value.numerator)
    return f"({value.numerator}/{value.denominator})"


def star_name(side, boundary, site, colour):
    return f"{side}{boundary}v{site}c{colour}"


def star_variables(active_colours):
    # Reversed side/boundary/site/colour order.  This is intentionally unlike
    # the primary ring order, while keeping each boundary-star block contiguous.
    variables = [
        star_name(side, boundary, site, colour)
        for side in ("q", "p")
        for boundary in reversed(active_colours)
        for site in reversed(INTERIOR)
        for colour in reversed(COLOURS)
    ]
    assert len(variables) == len(set(variables)) == 72
    return variables


def coordinate_polynomial(grouped_atoms, a, b, word, symbolic=False):
    terms = []
    for left, left_colour, right, right_colour, coefficient in grouped_atoms.get(word, ()):
        if symbolic:
            constant, slope = coefficient
            coefficient_text = qtext(constant)
            if slope:
                coefficient_text = f"({coefficient_text}+({qtext(slope)})*lam)"
        else:
            coefficient_text = qtext(coefficient)
        terms.append(
            f"({coefficient_text})*{star_name('p', a, left, left_colour)}*"
            f"{star_name('q', b, right, right_colour)}"
        )
        terms.append(
            f"({coefficient_text})*{star_name('p', a, right, right_colour)}*"
            f"{star_name('q', b, left, left_colour)}"
        )
    return "+".join(terms) if terms else "0"


def finite_fibre_equations(grouped_atoms, normal, a, b):
    targets = tuple((colour,) * 6 for colour in COLOURS)
    normal_coordinates = set().union(*(set(vector) for vector in normal)) if normal else set()
    coordinates = tuple(sorted(set(grouped_atoms) | set(targets) | normal_coordinates))
    target = (a,) * 6 if a == b else None
    equations = []
    for functional in annihilator(normal, coordinates):
        parts = [
            f"({qtext(coefficient)})*({coordinate_polynomial(grouped_atoms, a, b, word)})"
            for word, coefficient in functional.items()
        ]
        if target is not None and functional.get(target, Q(0)):
            parts.append(qtext(-functional[target]))
        equations.append("+".join(parts) if parts else "0")
    return equations


def finite_singular_program(grouped_atoms, normal, active_colours):
    generators = []
    for a, b in product(active_colours, repeat=2):
        generators.extend(finite_fibre_equations(grouped_atoms, normal, a, b))
    lines = [
        "ring R=0,(" + ",".join(star_variables(active_colours)) + "),dp;",
        "option(redSB);",
        "ideal I=" + ",".join(generators) + ";",
        "ideal G=std(I);",
        'print("CLEAN_UNIT"); if(reduce(1,G)==0){1;}else{0;}',
        'print("CLEAN_SIZE"); size(G);',
    ]
    return "\n".join(lines) + "\n", len(generators)


def linear_atom_map(atoms0, atoms1):
    answer = {}
    for key in set(atoms0) | set(atoms1):
        constant = atoms0.get(key, Q(0))
        slope = atoms1.get(key, Q(0)) - constant
        if constant or slope:
            answer[key] = (constant, slope)
    return answer


def symbolic_line_equations(grouped_atoms, a, b):
    line_words = set(V_T_WORDS) | {E_WORD}
    coordinates = tuple(sorted(set(grouped_atoms) | line_words
                               | {(1,) * 6, (2,) * 6}))
    pivot = V_T_WORDS[0]
    target = (a,) * 6 if a == b else None
    pivot_beta = coordinate_polynomial(grouped_atoms, a, b, pivot, symbolic=True)
    pivot_target = Q(1) if target == pivot else Q(0)
    equations = []
    for word in coordinates:
        if word == pivot:
            continue
        beta = coordinate_polynomial(grouped_atoms, a, b, word, symbolic=True)
        target_value = Q(1) if target == word else Q(0)
        if word == E_WORD:
            line_coefficient = "lam"
        elif word in V_T_WORDS:
            line_coefficient = "1"
        else:
            line_coefficient = "0"
        equations.append(
            f"({beta})-({qtext(target_value)})-({line_coefficient})*"
            f"(({pivot_beta})-({qtext(pivot_target)}))"
        )
    return equations


def symbolic_singular_program(grouped_atoms):
    active = (1, 2)
    generators = []
    for a, b in product(active, repeat=2):
        generators.extend(symbolic_line_equations(grouped_atoms, a, b))
    lines = [
        "ring R=0,(lam," + ",".join(star_variables(active)) + "),dp;",
        "option(redSB);",
        "ideal I=" + ",".join(generators) + ";",
        "ideal G=std(I);",
        'print("CLEAN_UNIT"); if(reduce(1,G)==0){1;}else{0;}',
        'print("CLEAN_SIZE"); size(G);',
    ]
    return "\n".join(lines) + "\n", len(generators)


def build_outside_finite_data(families, x_blocks):
    answer = []
    for chart, signature, support in families:
        killed = killed_for_outside(chart, x_blocks)
        x_coefficients = coefficients_for(sorted(support))
        normals = {
            final: four_cut_normal(x_coefficients, Q(1), killed, final)
            for final in (0, 1, 5)
        }
        assert all(len(normal) == chart.expected_normal_dimension
                   for normal in normals.values())
        assert same_span(normals[0], normals[1])
        assert same_span(normals[0], normals[5])
        normal = normals[0]
        hs = project_vector(
            matching_tensor(INTERIOR, internal_blocks(x_coefficients, Q(1))),
            killed)
        assert in_span(hs, normal)
        for colour in (1, 2):
            target = {(colour,) * 6: Q(1)}
            assert (colour,) * 6 not in killed
            assert not in_span(target, normal)
        atoms = project_atoms(atom_map(x_coefficients, Q(1)), killed)
        grouped = atoms_by_word(atoms)
        program, generators = finite_singular_program(grouped, normal, (1, 2))
        expected = OUTSIDE_EXPECTED_GENERATORS[chart.name][signature]
        assert generators == expected, (chart.name, signature, generators, expected)
        answer.append({
            "name": f"outside_{chart.name}_d{signature[0]}_b{signature[1]}",
            "chart": chart,
            "signature": signature,
            "support": support,
            "killed": killed,
            "normal": normal,
            "generators": generators,
            "program": program,
        })
    return tuple(answer)


def audit_cross_ratio(x_blocks):
    chart = next(chart for chart in OUTSIDE_CHARTS if chart.name == "x12")
    killed = killed_for_outside(chart, x_blocks)
    support0 = (X11, X12, X22)
    support1 = (X11, X12, X21, X22)
    x0 = coefficients_for(support0)
    x1 = coefficients_for(support1)
    x2 = coefficients_for(support1, (Q(1), Q(1), Q(2), Q(1)))

    expanded = {}
    for cut in INTERIOR:
        columns0 = tuple(project_vector(column, killed) for column in
                         insertion_columns(cut, x0, Q(1)))
        columns1 = tuple(project_vector(column, killed) for column in
                         insertion_columns(cut, x1, Q(1)))
        columns2 = tuple(project_vector(column, killed) for column in
                         insertion_columns(cut, x2, Q(1)))
        for at_zero, at_one, at_two in zip(columns0, columns1, columns2):
            assert at_two == linear_combination(((at_one, Q(2)), (at_zero, Q(-1))))
        expanded[cut] = rref_basis(columns0 + columns1)[0]

    expected_e = {E_WORD: Q(1)}
    expected_v = {word: Q(1) for word in V_T_WORDS}
    expected_plane = (expected_e, expected_v)
    for final in (0, 1, 5):
        upper = intersection_many(tuple(expanded[cut]
                                        for cut in (2, 3, 4, final)))
        assert len(upper) == 2
        assert same_span(upper, expected_plane)

    for final in (0, 1, 5):
        columns0 = tuple(project_vector(column, killed) for column in
                         insertion_columns(final, x0, Q(1)))
        columns1 = tuple(project_vector(column, killed) for column in
                         insertion_columns(final, x1, Q(1)))
        for constant, at_one in zip(columns0, columns1):
            slope = subtract(at_one, constant)
            coefficients = (
                constant.get(E_WORD, Q(0)),
                slope.get(E_WORD, Q(0)) - constant.get(LOCK_WORD, Q(0)),
                -slope.get(LOCK_WORD, Q(0)),
            )
            assert coefficients == (0, 0, 0)

    hs0 = project_vector(
        matching_tensor(INTERIOR, internal_blocks(x0, Q(1))), killed)
    hs1 = project_vector(
        matching_tensor(INTERIOR, internal_blocks(x1, Q(1))), killed)
    assert hs0 == expected_v
    assert subtract(hs1, hs0) == expected_e

    atoms0 = project_atoms(atom_map(x0, Q(1)), killed)
    atoms1 = project_atoms(atom_map(x1, Q(1)), killed)
    atoms2 = project_atoms(atom_map(x2, Q(1)), killed)
    for key in set(atoms0) | set(atoms1) | set(atoms2):
        assert atoms2.get(key, 0) == 2 * atoms1.get(key, 0) - atoms0.get(key, 0)
    symbolic_atoms = linear_atom_map(atoms0, atoms1)
    grouped = atoms_by_word(symbolic_atoms)
    program, generators = symbolic_singular_program(grouped)
    assert generators == 648, (generators, len(grouped))
    return {
        "name": "outside_x12_crossratio_lambda",
        "killed": killed,
        "generators": generators,
        "program": program,
    }


def build_old_locus_data(x_blocks, uplus):
    members = defaultdict(list)
    for mask in range(32):
        members[old_class_name(mask)].append(mask)
    assert tuple(len(members[spec.name]) for spec in OLD_CLASSES) == (16, 4, 4, 4, 4)
    assert sorted(mask for group in members.values() for mask in group) == list(range(32))

    answer = []
    for spec in OLD_CLASSES:
        killed = old_killed(spec, x_blocks, uplus)
        assert len(killed) == spec.expected_killed
        support = old_global_support(spec.maximal_mask)
        x_coefficients = coefficients_for(sorted(support))
        normals = {
            final: four_cut_normal(x_coefficients, Q(1), killed, final)
            for final in (0, 1, 5)
        }
        assert all(len(normal) == spec.expected_normal_dimension
                   for normal in normals.values())
        assert same_span(normals[0], normals[1])
        assert same_span(normals[0], normals[5])
        normal = normals[0]
        hs = project_vector(
            matching_tensor(INTERIOR, internal_blocks(x_coefficients, Q(1))),
            killed)
        assert in_span(hs, normal)
        for colour in spec.active_colours:
            target = {(colour,) * 6: Q(1)}
            assert (colour,) * 6 not in killed
            assert not in_span(target, normal)
        atoms = project_atoms(atom_map(x_coefficients, Q(1)), killed)
        grouped = atoms_by_word(atoms)
        program, generators = finite_singular_program(
            grouped, normal, spec.active_colours)
        assert generators == spec.expected_generators, (
            spec.name, generators, spec.expected_generators)
        answer.append({
            "name": spec.name,
            "spec": spec,
            "killed": killed,
            "normal": normal,
            "word_count": len(grouped),
            "atom_count": sum(map(len, grouped.values())),
            "generators": generators,
            "program": program,
        })
    return tuple(answer)


def marker(output, name):
    lines = [line.strip() for line in output.splitlines() if line.strip()]
    return int(lines[lines.index(name) + 1])


def run_singular_job(item):
    name, program = item
    singular = shutil.which("Singular")
    if singular is None:
        raise RuntimeError("Singular is required for this exact-Q audit")
    started = time.monotonic()
    completed = subprocess.run(
        [singular, "-q"], input=program, text=True, capture_output=True,
        check=True, timeout=1800)
    if completed.stderr.strip():
        raise AssertionError(f"{name}: {completed.stderr}")
    assert marker(completed.stdout, "CLEAN_UNIT") == 1
    assert marker(completed.stdout, "CLEAN_SIZE") == 1
    return name, time.monotonic() - started


def audit_all_unit_ideals(old_data, finite_data, cross_data):
    all_data = tuple(old_data) + tuple(finite_data) + (cross_data,)
    jobs = {data["name"]: data["program"] for data in all_data}
    assert len(jobs) == 33
    elapsed = {}
    workers = min(12, max(1, os.cpu_count() or 1), len(jobs))
    with ThreadPoolExecutor(max_workers=workers) as executor:
        futures = {
            executor.submit(run_singular_job, item): item[0]
            for item in jobs.items()
        }
        for future in as_completed(futures):
            name, duration = future.result()
            elapsed[name] = duration
            print(f"certificate {name}: unit ({duration:.3f}s)", flush=True)
    assert set(elapsed) == set(jobs)
    return elapsed


def main():
    started = time.monotonic()
    x_blocks, t_block, uplus = output_blocks()
    audit_no_mixed_terms_and_explicit_t()
    audit_torus_and_moduli()
    masks_by_chart, old_masks, finite_families, cross_masks = audit_support_partition()
    assert sum(len(masks_by_chart[chart.name]) for chart in OUTSIDE_CHARTS) == 480
    assert len(old_masks) + 480 == 512
    audit_killed_coefficients(x_blocks, t_block, uplus)
    audit_literal_eight_site_identity()
    finite_data = build_outside_finite_data(finite_families, x_blocks)
    cross_data = audit_cross_ratio(x_blocks)
    old_data = build_old_locus_data(x_blocks, uplus)
    elapsed = audit_all_unit_ideals(old_data, finite_data, cross_data)

    print("independent adjacent-A25-line audit: PASS")
    print("t=0 reduces literally to the audited arbitrary-A23 theorem; t!=0 normalized: PASS")
    print("512 masks, 32+480 partition, modulus census 328/132/42/9/1: PASS")
    print("rightmost matching recursion; 35-cell T block and overlaps 9+9+9: PASS")
    print("no X*t terms; explicit dense-X t=0,1,2 affine test: PASS")
    print("safe double-annihilator projected normals; killed coefficients termwise: PASS")
    print("108 shared stars, ordered four-fibre packets, and arbitrary A67: PASS")
    for data in old_data:
        print(f"{data['name']}: {data['generators']} generators, exact-Q unit "
              f"({elapsed[data['name']]:.3f}s): PASS")
    for data in finite_data:
        print(f"{data['name']}: {data['generators']} generators, exact-Q unit "
              f"({elapsed[data['name']]:.3f}s): PASS")
    name = cross_data["name"]
    print(f"{name}: {cross_data['generators']} generators, exact-Q[lambda] unit "
          f"({elapsed[name]:.3f}s): PASS")
    print(f"independent audit wall time: {time.monotonic() - started:.3f}s")


if __name__ == "__main__":
    main()
