#!/usr/bin/env python3
"""Where the terminal class sits in the nine-row ideal: the multigraded pin.

Research evidence only.  Krenn's conjecture remains open, `SP-CLEAN-BRIDGE` is
untouched, and no certified dependency changes.

The h=3 landing asks whether the terminal class chi vanishes at every common
zero of the nine physical rows.  The ideal-theoretic form of that question is

    is chi in the ideal I generated by the 6561 polynomials
        F(i,j,w) = Row(i,j,w) - target(i,j,w)  ?

A certificate would prove the landing.  This checker does not produce one; it
pins the shape every certificate must have, and decides the first bounded class
of certificates exactly.  All statements below are formal polynomial identities
or exact finite-rank computations, not sampling.

  PRIOR ART, AND WHAT IS AND IS NOT NEW HERE.  The site-colour multigrading of
  G1 is *not* new: it is the grading of notes/ideal-membership-route.md
  section 1 ("degree one at each of the two labels (u,a) and (v,b)"), there
  used on the bare six-vertex source ideal.  Two committed items ON THIS CHART
  are closer precedent still: block B1 of
  computations/verify_fourhole_allword_row_identity_grade_ladder.py records
  that every row monomial has p-degree equal to s-degree and at most one (the
  unlabelled endpoint grading), and
  notes/terminal-class-weight-invisibility-and-fourhole-grade-ladder.md carries
  the tau-weight grading -- and weight is a linear functional of the
  multidegree, so the weight statement is implied by the grading statement.
  What is added here is the
  endpoint-label refinement Z^3 x Z^3 -- the decorated chart has two endpoints
  whose colours are the row's label pair -- and the application to the terminal
  class rather than to the product of the three pure coefficients.  That note's
  conclusion should be read alongside G5: on its own object the direct
  degree-nine certificate provably does not exist either, and one must pass to
  a higher power or a localized argument.  Two independent negatives at the
  first natural bound are the current state of this route, not an accident of
  one target.

  METHOD.  G5 is a multigraded Nullstellensatz Linear Algebra computation:
  fix a degree bound, write the cofactor ansatz, and solve the resulting linear
  system exactly.  The attribution to De Loera-Lee-Malkin-Margulies
  (J. Symbolic Comput. 46(11), 2011; arXiv:0801.3788) and the remarks below
  about the standard NuLA setting are RELAYED -- no committed artifact in this
  repository backs them, and nothing here depends on them.  The only reason it is runnable at all is
  that the grading block-diagonalizes the Macaulay matrix -- the block at chi's
  own multidegree is 1 x 1 (G3), and the next blocks have 20985, 20985 and 2520
  columns instead of the astronomically many a plain degree bound over 252
  variables and 6561 generators would produce.  Note the standard NuLA setting
  adds Boolean constraints x^2 - x, which make the ideal radical and
  zero-dimensional and bound the Nullstellensatz degree; nothing of that kind is
  available here, so no small-degree expectation transfers.

  G1  THE MULTIGRADING (formal, all 6561 rows).  Give the ring the grading by
      Z^{6x3} x Z^3 x Z^3: the site-colour degree records, for each site x and
      colour c, how many half-edges the monomial puts at (x,c); the two label
      degrees record the colours carried at the two endpoints.  Then

          Row(i,j,w) is multihomogeneous of degree D(i,j,w) = (sigma(w), e_i, e_j)

      where sigma(w) = sum_x e_{(x,w_x)} is a 0/1 vector with one 1 per site.
      Proof in one line: every monomial of a row covers each site exactly once
      -- three internal edges, or one p, one s and two internal edges -- with
      the colour the word prescribes at that site, and carries exactly one
      left-label object (a p_i or a d_ij) and one right-label object.  The
      targets are constants, of degree 0.  Also verified: every row monomial has
      tau-weight zero (q:-1, p,s:+1, d:+3) and one of exactly three fine shapes
      (#p,#s,#d,#q) in {(0,0,1,3), (1,1,0,2)}, plus (0,0,0,0) for the target.

  G2  chi's DEGREE.  chi = alpha*Q_2 + Q_3 for the selected pair (0,1) at pure
      colour 2 is multihomogeneous of degree D* = (sigma(2^6), 3e_0, 3e_1) and
      of weight 6, with fine shapes (2,2,1,1) and (3,3,0,0).

  G3  THE TOP-LEVEL THEOREM (exhaustive over all 6561 generators).  Of the 6561
      generator degrees, exactly one satisfies D(i,j,w) <= D*, namely
      D(0,1,2^6); and the forced multiplier degree D* - D(0,1,2^6) carries
      exactly one weight-six monomial, d_01^2.  Hence *every* representation
      chi = sum_g m_g F_g has, at chi's own multidegree, the form

          chi = c * d_01^2 * Row(0,1,2^6) - N,      c a rational scalar,
          N   = m_{00,0^6}^{D*} + m_{11,1^6}^{D*} + m_{22,2^6}^{D*}.

      Only the three pure-word diagonal generators carry a constant, so N is
      supplied by the anchors alone: the anchors must literally hand over chi,
      modulo one scalar multiple of the selected row.  (Compare the audited cap
      split haf(alpha q + R) = alpha^2 Row(0,1,2^6) + chi, which this checker
      re-derives; it is the c = -1 member of that family.)

  G4  A DEGREE LOWER BOUND.  For every c the supply
      N = c*d_01^2*Row(0,1,2^6) - chi contains the twenty p^3 s^3 monomials of
      -Q_3, each with coefficient -6.  Those have total degree six.  So every
      three anchors, so some anchor multiplier has total degree AT LEAST six
      -- it may carry higher-degree monomials at other multidegrees -- and no
      certificate exists with all multipliers of total degree <= 5.

  G5  NO DEPTH-ONE CERTIFICATE (exact finite rank).  Call a certificate
      depth-one when its three anchor multipliers are multihomogeneous, i.e.
      m_{cc,c^6} = N_c.  Then the identity at degree D* + D(c,c,c^6) is an exact
      syzygy, and the generators available there are exactly those whose degree
      sits below it (enumerated by exhaustion, not by rule).  Define

          W_c = { N in V : N*Row(c,c,c^6) lies in the span of the multiplier
                  images of the *other* available generators },

      V being the 215-dimensional space of weight-six monomials of degree D*.
      Exactly:  dim W_0 = dim W_1 = dim W_2 = 1, NOT zero.  Each W_c is spanned
      by the trivial Koszul syzygy
          N_c = d_01^2 Row(0,1,2^6),
          N_c Row(c,c,c^6) = [d_01^2 Row(c,c,c^6)] Row(0,1,2^6),
      whose right-hand side is an available generator at that level with its
      multiplier inside the enumerated space.  The Koszul identity is verified
      here directly, needing no linear algebra.

      Depth one is closed anyway, by a SHAPE argument rather than by W_c = 0:
      dim W_c = 1 forces N = Lambda d_01^2 Row(0,1,2^6), so
      chi = (c - Lambda) d_01^2 Row(0,1,2^6).  Every monomial on the right has
      d-degree at least two; chi carries twenty d-FREE monomials of shape
      (p,s,q,d) = (3,3,0,0).  Hence chi = 0, which is false.

      The computation is done in the monochromatic model, which suffices:
      killing the cross-colour internal edges is a graded ring homomorphism
      fixing chi and mapping any depth-one certificate to a depth-one
      certificate.

  G6  THE SAME TEST ON THE CONSTANT 1 (the discriminating control).  1 has
      degree 0; no generator degree sits below it, so at the top level
      1 = -(k_0+k_1+k_2) with k_c rational scalars, and the only generator below
      D(c,c,c^6) is that anchor itself, so a depth-one certificate would force
      k_c * Row(c,c,c^6) = 0, i.e. k_c = 0 and 1 = 0.  So the constant 1 has no
      depth-one certificate either: at this bound the method separates nothing,
      and no result here may be read as evidence about the emptiness of the
      nine-row variety.

  G7  STANDARD PROBES.  The rank-two clean packet stays clean; the committed
      seven-row guard satisfies 6559 of the 6561 generators with chi = -2, which
      independently forces every certificate to consume Row(0,0,0^6)-1 or
      Row(1,1,1^6)-1.

  T   THE TEMPLATE (independent re-derivation).  On the audited guard's frozen
      colour-2 slice with everything else free and monochromatic, the seven
      supplied rows force exactly 32 symbols to zero, the anchor peels as
      Row(c,c,c^6) = q_c(2,3)*rho_c, and the five-term combination of
      notes/h3-star-sector-pure-word-anchor-witness-and-colour-asymmetry.md
      section 4 closes exactly for colour 1 while leaving sixteen monomials for
      colour 0.

WHAT THIS DOES NOT SAY.  It does not decide chi in I.  A negative at any bound
is a statement about certificates, not about the landing: the landing is radical
membership, which is weaker -- exactly the ideal-versus-radical gap that
notes/ideal-membership-route.md records on its own object.  And membership
itself is implied by emptiness of the nine-row variety: the chart has |B| = 8
sites (six residual sites and the two endpoints), so that emptiness is the
n = 8 case, which notes/final-resolution-foundations-draft.md Theorem A leaves
unclaimed (k_max(6) = 2 is proved there; k_max(n) <= 2 for even n >= 8 is not).
A parallel literature sweep, relayed and not verified here, reports the same
case open in the published literature.  So 1 in I is not available, no argument
here bears on Krenn's conjecture in either direction, and a full non-membership
proof would refute the conjecture at that order.

Python standard library only, exact Fraction arithmetic, deterministic, live
under -O.
"""

from fractions import Fraction as Q
from itertools import combinations, permutations, product


def require(condition, message):
    if not condition:
        raise AssertionError(message)


COLORS = (0, 1, 2)
SITES = tuple(range(6))
PAIRS = tuple(combinations(SITES, 2))
LEFT, RIGHT = 6, 7
PURE = 2
SEVEN = ((0, 1), (0, 2), (1, 0), (1, 2), (2, 0), (2, 1), (2, 2))

_MATCH = {}


def matchings(vertices):
    vertices = tuple(vertices)
    if vertices in _MATCH:
        return _MATCH[vertices]
    if not vertices:
        answer = ((),)
    elif len(vertices) % 2:
        answer = ()
    else:
        first = vertices[0]
        acc = []
        for position, partner in enumerate(vertices[1:], start=1):
            remainder = vertices[1:position] + vertices[position + 1:]
            for tail in matchings(remainder):
                acc.append(((first, partner),) + tail)
        answer = tuple(acc)
    _MATCH[vertices] = answer
    return answer


# --------------------------------------------------------------------------
# exact sparse polynomials; a monomial is a sorted tuple of variable keys
# --------------------------------------------------------------------------
ONE = {(): Q(1)}


def var(key):
    return {(key,): Q(1)}


def padd(left, right):
    out = dict(left)
    for monomial, coefficient in right.items():
        total = out.get(monomial, Q(0)) + coefficient
        if total:
            out[monomial] = total
        elif monomial in out:
            del out[monomial]
    return out


def pmul(left, right):
    out = {}
    for m1, c1 in left.items():
        for m2, c2 in right.items():
            monomial = tuple(sorted(m1 + m2))
            total = out.get(monomial, Q(0)) + c1 * c2
            if total:
                out[monomial] = total
            elif monomial in out:
                del out[monomial]
    return out


def pscale(poly, factor):
    if not factor:
        return {}
    return {monomial: coefficient * factor for monomial, coefficient in poly.items()}


# --------------------------------------------------------------------------
# the general symbolic packet and the physical rows
# --------------------------------------------------------------------------
def q_key(x, y, cx, cy):
    if x > y:
        x, y = y, x
        cx, cy = cy, cx
    return ("q", x, y, cx, cy)


CROSS = [True]                         # cross-colour internal edges present?


def q_var(x, y, cx, cy):
    if cx != cy and not CROSS[0]:
        return {}                      # the monochromatic specialization
    return var(q_key(x, y, cx, cy))


def set_cross(flag):
    """Killing the cross-colour internal edges is a graded ring homomorphism
    that fixes chi and every label; a depth-one certificate maps to a
    depth-one certificate, so deciding the monochromatic model decides the
    general one in the negative direction."""
    CROSS[0] = flag
    _HAF.clear()
    _ROW.clear()


def p_var(i, x, c):
    return var(("p", i, x, c))


def s_var(j, y, c):
    return var(("s", j, y, c))


def d_var(i, j):
    return var(("d", i, j))


_HAF = {}


def haf_poly(sites, word):
    sites = tuple(sites)
    key = (sites, tuple(word[x] for x in sites))
    cached = _HAF.get(key)
    if cached is not None:
        return cached
    total = {}
    for matching in matchings(sites):
        term = ONE
        for x, y in matching:
            term = pmul(term, q_var(x, y, word[x], word[y]))
            if not term:
                break
        total = padd(total, term)
    _HAF[key] = total
    return total


def response(i, j, x, y, word):
    return padd(pmul(p_var(i, x, word[x]), s_var(j, y, word[y])),
                pmul(p_var(i, y, word[y]), s_var(j, x, word[x])))


_ROW = {}


def row_poly(i, j, word):
    key = (i, j, word)
    cached = _ROW.get(key)
    if cached is not None:
        return cached
    total = pmul(d_var(i, j), haf_poly(SITES, word))
    for x, y in PAIRS:
        piece = haf_poly(tuple(v for v in SITES if v not in (x, y)), word)
        if piece:
            total = padd(total, pmul(response(i, j, x, y, word), piece))
    _ROW[key] = total
    return total


def ghz_target(i, j, word):
    return Q(1) if (i == j and all(c == i for c in word)) else Q(0)


def chi_poly(a=0, b=1, colour=PURE):
    word = (colour,) * 6
    layers = [{} for _ in range(4)]
    for matching in matchings(SITES):
        for flags in product((0, 1), repeat=3):
            term = ONE
            for flag, (x, y) in zip(flags, matching):
                term = pmul(term, response(a, b, x, y, word) if flag
                            else q_var(x, y, colour, colour))
            layers[sum(flags)] = padd(layers[sum(flags)], term)
    return padd(pmul(d_var(a, b), layers[2]), layers[3]), layers


# --------------------------------------------------------------------------
# the grading
# --------------------------------------------------------------------------
WEIGHT = {"q": -1, "p": 1, "s": 1, "d": 3}


def weight_of(monomial):
    return sum(WEIGHT[key[0]] for key in monomial)


def shape_of(monomial):
    counts = {"p": 0, "s": 0, "d": 0, "q": 0}
    for key in monomial:
        counts[key[0]] += 1
    return (counts["p"], counts["s"], counts["d"], counts["q"])


def degree_of(monomial):
    site = {}
    left = {}
    right = {}
    for key in monomial:
        if key[0] == "q":
            _, x, y, cx, cy = key
            site[(x, cx)] = site.get((x, cx), 0) + 1
            site[(y, cy)] = site.get((y, cy), 0) + 1
        elif key[0] == "p":
            _, i, x, c = key
            site[(x, c)] = site.get((x, c), 0) + 1
            left[i] = left.get(i, 0) + 1
        elif key[0] == "s":
            _, j, y, c = key
            site[(y, c)] = site.get((y, c), 0) + 1
            right[j] = right.get(j, 0) + 1
        else:
            left[key[1]] = left.get(key[1], 0) + 1
            right[key[2]] = right.get(key[2], 0) + 1
    return (frozenset(site.items()), frozenset(left.items()),
            frozenset(right.items()))


def as_dict(degree):
    return tuple(dict(part) for part in degree)


def dominates(big, small):
    for part_big, part_small in zip(as_dict(big), as_dict(small)):
        for key, value in part_small.items():
            if part_big.get(key, 0) < value:
                return False
    return True


def degree_of_generator(i, j, word):
    site = frozenset(((x, word[x]), 1) for x in SITES)
    return (site, frozenset({(i, 1)}), frozenset({(j, 1)}))


def homogeneous_degree(poly, name):
    degrees = {degree_of(m) for m in poly}
    require(len(degrees) == 1, ("not multihomogeneous", name, len(degrees)))
    return degrees.pop()


# --------------------------------------------------------------------------
# G1/G2/G3/G4
# --------------------------------------------------------------------------
def audit_normalization():
    ones = {e: Q(1) for e in PAIRS}

    def plain(sites, entries):
        total = Q(0)
        for matching in matchings(tuple(sites)):
            term = Q(1)
            for x, y in matching:
                term *= entries[(min(x, y), max(x, y))]
            total += term
        return total

    require(plain(SITES, ones) == 15, "all-ones six-site hafnian is not 15")
    polar = {e: plain(tuple(v for v in SITES if v not in e), ones) for e in PAIRS}
    require(polar[(0, 1)] == 3, "all-ones polar entry is not 3")
    require(plain((2, 3, 4, 5), polar) == 27, "all-ones double polar is not 27")
    outside = (2, 3, 4, 5)
    cross = sum(1 for _ in combinations(outside, 2))
    require(cross == 6 and 27 - 15 == 2 * cross == 12,
            "all-ones cross-star defect is not 12")
    require(sum(ones[e] * polar[e] for e in PAIRS) == 3 * 15,
            "Euler failed on all ones")


def audit_row_multigrading():
    shapes = set()
    seen = 0
    require(CROSS[0], "the grading audit must run with cross-colour edges live")
    for word in product(COLORS, repeat=6):
        for i, j in product(COLORS, repeat=2):
            row = row_poly(i, j, word)
            require(len(row) == 105, ("a row lost a matching", i, j, word))
            require(homogeneous_degree(row, ("row", i, j, word))
                    == degree_of_generator(i, j, word),
                    ("row multidegree wrong", i, j, word))
            for monomial in row:
                require(weight_of(monomial) == 0,
                        ("row monomial not weight zero", i, j, word, monomial))
                shapes.add(shape_of(monomial))
            seen += 1
    require(seen == 9 * 729, ("row census changed", seen))
    require(shapes == {(0, 0, 1, 3), (1, 1, 0, 2)},
            ("row fine shapes changed", sorted(shapes)))


def audit_chi(chi, layers):
    star = (frozenset(((x, PURE), 1) for x in SITES),
            frozenset({(0, 3)}), frozenset({(1, 3)}))
    require(homogeneous_degree(chi, "chi") == star, "chi multidegree wrong")
    require({weight_of(m) for m in chi} == {6}, "chi is not weight six")
    require({shape_of(m) for m in chi} == {(2, 2, 1, 1), (3, 3, 0, 0)},
            ("chi fine shapes changed", sorted({shape_of(m) for m in chi})))
    require(len(chi) == 110, ("chi monomial count changed", len(chi)))
    # the audited cap split, re-derived
    cap = {}
    for matching in matchings(SITES):
        term = ONE
        for x, y in matching:
            term = pmul(term, padd(pmul(d_var(0, 1), q_var(x, y, PURE, PURE)),
                                   response(0, 1, x, y, (PURE,) * 6)))
        cap = padd(cap, term)
    alpha2 = pmul(d_var(0, 1), d_var(0, 1))
    require(cap == padd(pmul(alpha2, row_poly(0, 1, (PURE,) * 6)), chi),
            "haf(A_cap) = alpha^2 Row(0,1,2^6) + chi failed")
    require(padd(pmul(d_var(0, 1), layers[0]), layers[1])
            == row_poly(0, 1, (PURE,) * 6),
            "the pure-word row is not the source jet alpha Q_0 + Q_1")
    return star


def audit_top_level(chi, star):
    below = [(i, j, word) for word in product(COLORS, repeat=6)
             for i, j in product(COLORS, repeat=2)
             if dominates(star, degree_of_generator(i, j, word))]
    require(below == [(0, 1, (PURE,) * 6)],
            ("more than one generator sits below chi's degree", below))
    # the forced multiplier: site-colour degree 0, left 2e_0, right 2e_1
    candidates = set()
    for i1, j1, i2, j2 in product(COLORS, repeat=4):
        monomial = tuple(sorted((("d", i1, j1), ("d", i2, j2))))
        if degree_of(monomial) != (frozenset(), frozenset({(0, 2)}),
                                   frozenset({(1, 2)})):
            continue
        if weight_of(monomial) == 6:
            candidates.add(monomial)
    require(candidates == {(("d", 0, 1), ("d", 0, 1))},
            ("the forced multiplier is not d_01^2", sorted(candidates)))


def audit_degree_lower_bound(chi):
    alpha2row = pmul(pmul(d_var(0, 1), d_var(0, 1)), row_poly(0, 1, (PURE,) * 6))
    for c in (Q(0), Q(1), Q(-1), Q(7), Q(-3, 5)):
        supply = padd(pscale(chi, Q(-1)), pscale(alpha2row, c))
        require(supply, ("the anchor supply vanished", c))
        cubic = {m: v for m, v in supply.items() if shape_of(m) == (3, 3, 0, 0)}
        require(len(cubic) == 20 and set(cubic.values()) == {Q(-6)},
                ("the p^3s^3 part of the supply moved", c, len(cubic)))
        require({len(m) for m in cubic} == {6},
                ("a p^3s^3 monomial is not of total degree six", c))
        require(max(len(m) for m in supply) == 6,
                ("the supply grew past total degree six", c))
    return alpha2row


# --------------------------------------------------------------------------
# G5: the depth-one decision
# --------------------------------------------------------------------------
class Reducer:
    """row echelon store over the monomial order, with provenance vectors"""

    __slots__ = ("pivots",)

    def __init__(self):
        self.pivots = {}

    def reduce(self, poly, vector=None):
        residue = dict(poly)
        vector = dict(vector) if vector is not None else None
        while residue:
            head = max(residue)
            entry = self.pivots.get(head)
            if entry is None:
                break
            prow, pvec = entry
            factor = residue[head] / prow[head]
            for monomial, value in prow.items():
                new = residue.get(monomial, Q(0)) - factor * value
                if new:
                    residue[monomial] = new
                elif monomial in residue:
                    del residue[monomial]
            if vector is not None and pvec is not None:
                for key, value in pvec.items():
                    new = vector.get(key, Q(0)) - factor * value
                    if new:
                        vector[key] = new
                    elif key in vector:
                        del vector[key]
        return residue, vector

    def insert(self, poly, vector=None):
        residue, vector = self.reduce(poly, vector)
        if residue:
            self.pivots[max(residue)] = (residue, vector)
            return True
        return False


def splits(slots):
    """every way to split a tuple of (site,colour) slots into pairs+singletons"""
    slots = tuple(slots)
    if not slots:
        yield ((), ())
        return
    first, rest = slots[0], slots[1:]
    for pairs, singles in splits(rest):
        yield pairs, (first,) + singles
    for index, partner in enumerate(rest):
        remainder = rest[:index] + rest[index + 1:]
        for pairs, singles in splits(remainder):
            yield ((first, partner),) + pairs, singles


def multiset(counts):
    out = []
    for label in sorted(counts):
        out.extend([label] * counts[label])
    return tuple(out)


def choose(items, count):
    seen = set()
    for picked in combinations(range(len(items)), count):
        taken = tuple(sorted(items[k] for k in picked))
        rest = tuple(sorted(items[k] for k in range(len(items))
                            if k not in picked))
        if (taken, rest) in seen:
            continue
        seen.add((taken, rest))
        yield taken, rest


def monomial_space(slots, left_counts, right_counts, weight=6):
    """all weight-`weight` monomials of the given site-colour and label degrees"""
    left = multiset(left_counts)
    right = multiset(right_counts)
    out = []
    seen = set()
    for pairs, singles in splits(slots):
        if any(a[1] != b[1] or a[0] == b[0] for a, b in pairs):
            continue                                  # monochromatic, no loops
        edges = [q_key(a[0], b[0], a[1], b[1]) for a, b in pairs]
        for mask in range(1 << len(singles)):
            p_slots = [singles[k] for k in range(len(singles)) if mask >> k & 1]
            s_slots = [singles[k] for k in range(len(singles))
                       if not mask >> k & 1]
            n_d = len(left) - len(p_slots)
            if n_d < 0 or len(right) - len(s_slots) != n_d:
                continue
            if (len(p_slots) + len(s_slots) + 3 * n_d - len(pairs)) != weight:
                continue
            for p_labels, d_left in choose(left, len(p_slots)):
                for s_labels, d_right in choose(right, len(s_slots)):
                    for p_perm in set(permutations(p_labels)):
                        for s_perm in set(permutations(s_labels)):
                            for d_perm in set(permutations(d_right)):
                                monomial = list(edges)
                                for (x, c), label in zip(p_slots, p_perm):
                                    monomial.append(("p", label, x, c))
                                for (y, c), label in zip(s_slots, s_perm):
                                    monomial.append(("s", label, y, c))
                                for li, rj in zip(d_left, d_perm):
                                    monomial.append(("d", li, rj))
                                key = tuple(sorted(monomial))
                                if key in seen:
                                    continue
                                seen.add(key)
                                out.append(key)
    return out


def sum_degrees(first, second):
    parts = []
    for a, b in zip(as_dict(first), as_dict(second)):
        merged = dict(a)
        for key, value in b.items():
            merged[key] = merged.get(key, 0) + value
        parts.append(frozenset(merged.items()))
    return tuple(parts)


def difference(big, small):
    parts = []
    for a, b in zip(as_dict(big), as_dict(small)):
        merged = dict(a)
        for key, value in b.items():
            merged[key] = merged.get(key, 0) - value
            require(merged[key] >= 0, "negative multidegree")
            if not merged[key]:
                del merged[key]
        parts.append(merged)
    return parts


def branch(anchor_colour, star, include_anchor_space=False):
    """dim W_c, by exhaustive enumeration of the generators available at
    degree D* + D(c,c,c^6)."""
    anchor_word = (anchor_colour,) * 6
    level = sum_degrees(star, degree_of_generator(anchor_colour, anchor_colour,
                                                  anchor_word))
    span = Reducer()
    columns = 0
    for word in product(COLORS, repeat=6):
        for i, j in product(COLORS, repeat=2):
            generator = degree_of_generator(i, j, word)
            if not dominates(level, generator):
                continue
            if (i, j, word) == (anchor_colour, anchor_colour, anchor_word) \
                    and not include_anchor_space:
                continue
            site, left, right = difference(level, generator)
            slots = tuple(slot for slot, count in sorted(site.items())
                          for _ in range(count))
            row = row_poly(i, j, word)
            for monomial in monomial_space(slots, left, right):
                span.insert(pmul({monomial: Q(1)}, row))
                columns += 1
    anchor = row_poly(anchor_colour, anchor_colour, anchor_word)
    site, left, right = difference(star, (frozenset(), frozenset(), frozenset()))
    slots = tuple(slot for slot, count in sorted(site.items())
                  for _ in range(count))
    basis = monomial_space(slots, left, right)
    rank_before = len(span.pivots)

    # ONE accumulator, deliberately.  Reducing each anchor image against the
    # span and then measuring independence in a SEPARATE Reducer is wrong:
    # ``reduce`` stops at the first leading monomial with no pivot, so a
    # residue can still contain span pivot heads further down its tail, and a
    # dependency modulo the span becomes invisible.  That is a real defect, not
    # a tuning detail -- it reported dim W_c = 0 when the true value is 1.
    gained = 0
    for index, monomial in enumerate(basis):
        image = pmul({monomial: Q(1)}, anchor)
        residue, vector = span.reduce(image, {index: Q(1)})
        if residue:
            span.pivots[max(residue)] = (residue, vector)
            gained += 1
    kernel = len(basis) - gained
    return len(basis), columns, rank_before, kernel


def audit_depth_one(star):
    """dim W_c = 1, spanned by the Koszul element, and no depth-one certificate.

    W_c is ONE-dimensional, not zero.  It contains the trivial Koszul syzygy
        N_c = d_01^2 Row(0,1,2^6),      N_c Row(c,c,c^6)
             = [d_01^2 Row(c,c,c^6)] Row(0,1,2^6),
    whose right-hand side is an available generator at level D* + D(c,c,c^6)
    with its multiplier inside the enumerated space.  So the depth-one closure
    does NOT follow from W_c = 0; it follows from a SHAPE argument:

      dim W_c = 1 forces N = Lambda d_01^2 Row(0,1,2^6) for a scalar Lambda,
      so chi = (c - Lambda) d_01^2 Row(0,1,2^6).  Every monomial on the right
      carries d_01^2.  But chi has 20 monomials of shape (p,s,q,d) = (3,3,0,0),
      carrying no d at all.  Hence chi = 0 -- false.  No depth-one certificate
      exists.
    """
    dimensions = {}
    for colour in COLORS:
        size, columns, rank, kernel = branch(colour, star)
        dimensions[colour] = (size, columns, rank, kernel)
        require(size == 215, ("dim V changed", colour, size))
        require(kernel == 1,
                ("W_%d is not one-dimensional" % colour, kernel))

    # the Koszul element explicitly, needing no linear algebra at all
    d01 = ("d", 0, 1)
    d01sq = {(d01, d01): Q(1)}
    koszul = pmul(d01sq, row_poly(0, 1, (PURE,) * 6))
    require(koszul, "the Koszul element is zero")
    for colour in COLORS:
        anchor_word = (colour,) * 6
        anchor_row = row_poly(colour, colour, anchor_word)
        left = pmul(koszul, anchor_row)
        right = pmul(pmul(d01sq, anchor_row), row_poly(0, 1, (PURE,) * 6))
        require(left == right,
                ("the Koszul identity fails at colour", colour))
    # Row(0,1,2^6) itself carries a d_01 in its direct term, so the product
    # has d_01-degree two or three -- the point is only that it is never zero.
    for monomial in koszul:
        require(sum(1 for v in monomial if v == d01) >= 2,
                ("a Koszul monomial does not carry d_01^2", monomial))

    # the shape argument that actually closes depth one: every element of
    # W_c carries d_01^2, while chi has d-free monomials.
    chi, _ = chi_poly()
    shapes = set()
    for monomial in chi:
        counts = {"p": 0, "s": 0, "q": 0, "d": 0}
        for variable in monomial:
            counts[variable[0]] += 1
        shapes.add((counts["p"], counts["s"], counts["q"], counts["d"]))
    d_free = {shape for shape in shapes if shape[3] == 0}
    require((3, 3, 0, 0) in d_free,
            ("chi has no d-free (3,3,0,0) monomial, so the shape argument "
             "does not close depth one", sorted(shapes)))
    require(sum(1 for m in chi if not any(v[0] == "d" for v in m)) == 20,
            "chi does not carry exactly twenty d-free monomials")
    return dimensions


def audit_cascade_census(star):
    """How far the next bound is: how many generators become available when the
    anchor multipliers are allowed one, two, ... extra multidegree components."""
    census = {}
    generators = [(i, j, word) for word in product(COLORS, repeat=6)
                  for i, j in product(COLORS, repeat=2)]
    degrees = {g: degree_of_generator(*g) for g in generators}
    for chain in ((), (0,), (1,), (2,), (0, 0), (0, 1), (0, 2), (2, 2)):
        level = star
        for colour in chain:
            level = sum_degrees(level,
                                degree_of_generator(colour, colour, (colour,) * 6))
        census[chain] = sum(1 for g in generators
                            if dominates(level, degrees[g]))
    require(census[()] == 1, ("the top level gained a generator", census[()]))
    require(census[(0,)] == census[(1,)] == 128 and census[(2,)] == 4,
            ("the depth-one census changed", census))
    require(census[(0, 0)] == 128 and census[(2, 2)] == 4
            and census[(0, 1)] == 2916 and census[(0, 2)] == 384,
            ("the depth-two census changed", census))
    return census


def audit_constant_control(star):
    """the same bound applied to the target 1: no depth-one certificate either"""
    zero = (frozenset(), frozenset(), frozenset())
    below = [(i, j, word) for word in product(COLORS, repeat=6)
             for i, j in product(COLORS, repeat=2)
             if dominates(zero, degree_of_generator(i, j, word))]
    require(below == [], ("a generator sits below the constant's degree", below))
    for colour in COLORS:
        anchor_word = (colour,) * 6
        level = degree_of_generator(colour, colour, anchor_word)
        available = [(i, j, word) for word in product(COLORS, repeat=6)
                     for i, j in product(COLORS, repeat=2)
                     if dominates(level, degree_of_generator(i, j, word))]
        require(available == [(colour, colour, anchor_word)],
                ("the constant's level-two system gained a generator", colour,
                 available))


# --------------------------------------------------------------------------
# G7: the two standard probes
# --------------------------------------------------------------------------
def numeric_layers(q, r):
    layers = [Q(0)] * 4
    for matching in matchings(SITES):
        for flags in product((0, 1), repeat=3):
            term = Q(1)
            for flag, e in zip(flags, matching):
                term *= (r if flag else q)[e]
            layers[sum(flags)] += term
    return tuple(layers)


def audit_clean_packet():
    q = {e: Q(0) for e in PAIRS}
    for e in ((0, 1), (2, 3), (4, 5)):
        q[e] = Q(1)
    u = (1, -1, 2, 0, 1, 1)
    v = (1, 2, -2, 1, -2, 1)
    r = {(x, y): Q(u[x] * v[y] + v[x] * u[y]) for x, y in PAIRS}
    layers = numeric_layers(q, r)
    require(layers == (Q(1), Q(2), Q(6), Q(12)), ("clean packet layers", layers))
    require(Q(-2) * layers[0] + layers[1] == 0, "clean packet source row moved")
    require(Q(-2) * layers[2] + layers[3] == 0, "the clean packet is not clean")


GUARD = ((0, 1, 2, 2, 1), (4, 5, 2, 2, 1), (LEFT, RIGHT, 0, 1, 1),
         (LEFT, 0, 0, 2, 1), (LEFT, 1, 0, 2, 1), (LEFT, 4, 1, 2, 1),
         (LEFT, 2, 2, 2, 1), (LEFT, 3, 2, 2, 1), (RIGHT, 5, 0, 2, 1),
         (RIGHT, 2, 1, 2, 1), (RIGHT, 3, 1, 2, -1),
         (RIGHT, 2, 2, 2, Q(1, 2)), (RIGHT, 3, 2, 2, Q(1, 2)))


def audit_seven_row_guard():
    blocks = {}
    for x, y, cx, cy, value in GUARD:
        if x > y:
            x, y, cx, cy = y, x, cy, cx
        blocks[(x, y, cx, cy)] = Q(value)

    def entry(x, y, cx, cy):
        if x > y:
            x, y, cx, cy = y, x, cy, cx
        return blocks.get((x, y, cx, cy), Q(0))

    def haf(word, sites):
        total = Q(0)
        for matching in matchings(tuple(sites)):
            term = Q(1)
            for x, y in matching:
                term *= entry(x, y, word[x], word[y])
                if not term:
                    break
            total += term
        return total

    ledger = []
    for word in product(COLORS, repeat=6):
        for i, j in product(COLORS, repeat=2):
            value = entry(LEFT, RIGHT, i, j) * haf(word, SITES)
            for x, y in PAIRS:
                piece = (entry(LEFT, x, i, word[x]) * entry(RIGHT, y, j, word[y])
                         + entry(LEFT, y, i, word[y])
                         * entry(RIGHT, x, j, word[x]))
                if piece:
                    value += piece * haf(word,
                                         tuple(v for v in SITES
                                               if v not in (x, y)))
            residual = value - ghz_target(i, j, word)
            if residual:
                ledger.append((i, j, word, residual))
    require(ledger == [(0, 0, (0,) * 6, Q(-1)), (1, 1, (1,) * 6, Q(-1))],
            ("the guard ledger changed", ledger))
    alpha = entry(LEFT, RIGHT, 0, 1)
    internal = {e: entry(e[0], e[1], PURE, PURE) for e in PAIRS}
    u = [entry(LEFT, x, 0, PURE) for x in SITES]
    v = [entry(RIGHT, x, 1, PURE) for x in SITES]
    r = {(x, y): u[x] * v[y] + v[x] * u[y] for x, y in PAIRS}
    layers = numeric_layers(internal, r)
    require(alpha * layers[2] + layers[3] == -2, "the guard chi changed")
    return len(ledger)


# --------------------------------------------------------------------------
# T: the template certificate, re-derived on the frozen slice
# --------------------------------------------------------------------------
FROZEN_Q2 = {(0, 1): Q(1), (4, 5): Q(1)}
FROZEN_P2 = {(0, 0): Q(1), (0, 1): Q(1), (1, 4): Q(1), (2, 2): Q(1), (2, 3): Q(1)}
FROZEN_S2 = {(0, 5): Q(1), (1, 2): Q(1), (1, 3): Q(-1),
             (2, 2): Q(1, 2), (2, 3): Q(1, 2)}


def frozen_edge(x, y, cx, cy):
    if x > y:
        x, y, cx, cy = y, x, cy, cx
    if cx == PURE and cy == PURE:
        value = FROZEN_Q2.get((x, y), 0)
        return {(): Q(value)} if value else {}
    if cx != cy:
        return {}
    return var(("q", cx, min(x, y), max(x, y)))


def frozen_p(i, x, c):
    if c == PURE:
        value = FROZEN_P2.get((i, x), 0)
        return {(): Q(value)} if value else {}
    return var(("p", i, x, c))


def frozen_s(j, y, c):
    if c == PURE:
        value = FROZEN_S2.get((j, y), 0)
        return {(): Q(value)} if value else {}
    return var(("s", j, y, c))


def frozen_haf(vertices, word):
    total = {}
    for matching in matchings(tuple(vertices)):
        term = ONE
        for x, y in matching:
            term = pmul(term, frozen_edge(x, y, word[x], word[y]))
            if not term:
                break
        total = padd(total, term)
    return total


def frozen_row(i, j, word, vertices=SITES):
    vertices = tuple(vertices)
    total = pmul(var(("d", i, j)), frozen_haf(vertices, word))
    for x, y in combinations(vertices, 2):
        piece = frozen_haf(tuple(v for v in vertices if v not in (x, y)), word)
        if not piece:
            continue
        resp = padd(pmul(frozen_p(i, x, word[x]), frozen_s(j, y, word[y])),
                    pmul(frozen_p(i, y, word[y]), frozen_s(j, x, word[x])))
        if resp:
            total = padd(total, pmul(resp, piece))
    return total


def kill(poly, zeros):
    return {m: v for m, v in poly.items() if not any(k in zeros for k in m)}


def audit_template():
    system = {(i, j, w): frozen_row(i, j, w)
              for w in product(COLORS, repeat=6)
              for i, j in product(COLORS, repeat=2)}
    ledger = []
    for (i, j, word), poly in system.items():
        value = Q(0)
        for monomial, coefficient in poly.items():
            term = coefficient
            for key in monomial:
                term *= Q(1) if key == ("d", 0, 1) else Q(0)
            value += term
        residual = value - ghz_target(i, j, word)
        if residual:
            ledger.append((i, j, word, residual))
    require(sorted(ledger) == [(0, 0, (0,) * 6, Q(-1)), (1, 1, (1,) * 6, Q(-1))],
            ("the frozen model misses the committed guard ledger",
             sorted(ledger)))

    equations = [(k, padd(p, {(): -ghz_target(*k)}))
                 for k, p in system.items() if (k[0], k[1]) in SEVEN]
    zeros = set()
    while True:
        fresh = set()
        for key, poly in equations:
            reduced = kill(poly, zeros)
            if len(reduced) != 1:
                continue
            monomial = next(iter(reduced))
            require(monomial, ("premature contradiction", key))
            if len(set(monomial)) == 1:
                require(len(monomial) == 1, ("a forcing is not linear", key))
                fresh.add(monomial[0])
        if not fresh - zeros:
            break
        zeros |= fresh
    require(len(zeros) == 32, ("forced zero count", len(zeros)))
    for colour in (0, 1):
        alive = tuple(pair for pair in PAIRS
                      if ("q", colour, pair[0], pair[1]) not in zeros)
        require(alive == ((0, 4), (0, 5), (1, 4), (1, 5), (2, 3)),
                ("colour-%d support collapse changed" % colour, alive))
        anchor = kill(system[(colour, colour, (colour,) * 6)], zeros)
        rho = kill(frozen_row(colour, colour, {x: colour for x in SITES},
                              vertices=(0, 1, 4, 5)), zeros)
        require(anchor == pmul(var(("q", colour, 2, 3)), rho),
                ("the anchor peel identity failed", colour))

    residuals = {}
    for colour in (0, 1):
        anchor = kill(system[(colour, colour, (colour,) * 6)], zeros)
        words = {"E3": tuple(PURE if x in (2, 3) else colour for x in SITES),
                 "E4": tuple(PURE if x == 0 else colour for x in SITES),
                 "E5": tuple(PURE if x == 1 else colour for x in SITES),
                 "E6": tuple(PURE if x in (1, 4, 5) else colour for x in SITES),
                 "E7": tuple(PURE if x in (0, 4, 5) else colour for x in SITES)}
        labels = {"E3": (2, 2), "E4": (0, 1), "E5": (0, 1),
                  "E6": (0, 1), "E7": (0, 1)}
        piece = {}
        for name, word in words.items():
            i, j = labels[name]
            require((i, j) in SEVEN, ("certificate used a non-supplied row", name))
            require(ghz_target(i, j, word) == 0,
                    ("certificate word has a target", name))
            piece[name] = kill(system[(i, j, word)], zeros)
        require(piece["E3"] == padd(pmul(var(("q", colour, 0, 4)),
                                         var(("q", colour, 1, 5))),
                                    pmul(var(("q", colour, 0, 5)),
                                         var(("q", colour, 1, 4)))),
                ("E3 is not the four-site permanent", colour))
        a_prime = padd(pmul(var(("q", colour, 1, 5)), var(("p", colour, 4, colour))),
                       pmul(var(("q", colour, 1, 4)), var(("p", colour, 5, colour))))
        c_prime = padd(pmul(var(("q", colour, 0, 5)), var(("p", colour, 4, colour))),
                       pmul(var(("q", colour, 0, 4)), var(("p", colour, 5, colour))))
        combination = pmul(pmul(var(("d", colour, colour)),
                                var(("q", colour, 2, 3))), piece["E3"])
        combination = padd(combination, pmul(var(("p", colour, 0, colour)),
                                             piece["E4"]))
        combination = padd(combination, pmul(var(("p", colour, 1, colour)),
                                             piece["E5"]))
        combination = padd(combination, pmul(a_prime, piece["E6"]))
        combination = padd(combination, pmul(c_prime, piece["E7"]))
        residuals[colour] = len(padd(anchor, pscale(combination, Q(-1))))
    require(residuals[1] == 0, ("the colour-1 certificate failed", residuals[1]))
    require(residuals[0] == 16,
            ("the colour-0 residual is not sixteen monomials", residuals[0]))
    return len(zeros)


def main():
    audit_normalization()
    audit_row_multigrading()
    chi, layers = chi_poly()
    star = audit_chi(chi, layers)
    audit_top_level(chi, star)
    audit_degree_lower_bound(chi)
    set_cross(False)
    dimensions = audit_depth_one(star)
    census = audit_cascade_census(star)
    audit_constant_control(star)
    set_cross(True)
    audit_clean_packet()
    missing = audit_seven_row_guard()
    zeros = audit_template()
    print(
        "PASS: all 6561 rows are multihomogeneous of degree (sigma(w),e_i,e_j) "
        "and weight zero, with fine shapes {(0,0,1,3),(1,1,0,2)}; chi has "
        "degree (sigma(2^6),3e_0,3e_1), weight 6 and shapes "
        "{(2,2,1,1),(3,3,0,0)}; exactly one generator degree lies below chi's, "
        "(0,1,2^6), with forced multiplier d_01^2, so every certificate reads "
        "chi = c*d_01^2*Row(0,1,2^6) - N with N supplied by the three pure-word "
        "anchors alone, and N always carries the twenty p^3s^3 monomials of "
        "-Q_3, so no certificate has all multipliers of total degree <= 5; "
        "at the next level dim W_0 = dim W_1 = dim W_2 = 1 out of dim V = %d "
        "(columns %d/%d/%d, ranks %d/%d/%d), so there is no depth-one "
        "certificate -- by a d-degree shape argument, since each W_c is "
        "spanned by the Koszul element d_01^2 Row(0,1,2^6) and chi has twenty "
        "d-free monomials -- and the "
        "constant 1 has no depth-one certificate either; the clean packet stays "
        "clean, the seven-row guard misses exactly %d generators with chi = -2, "
        "and the frozen-slice template forces %d symbols to zero and closes the "
        "five-term colour-1 certificate exactly (colour-0 residual 16); the "
        "cascade census of available generators is %d at chi's own degree and "
        "%d/%d/%d one anchor step out, so the next bound is strictly larger."
        % (dimensions[0][0], dimensions[0][1], dimensions[1][1],
           dimensions[2][1], dimensions[0][2], dimensions[1][2],
           dimensions[2][2], missing, zeros, census[()], census[(0,)],
           census[(1,)], census[(2,)])
    )


if __name__ == "__main__":
    main()
