#!/usr/bin/env python3
"""Exact multi-spoke exposure on the selected chart-26 terminal face.

There are three separate assertions in this checker.

1.  At the chart-support boundary, the linear parts of 358 mixed hafnians
    contain an exact 240 by 240 identity minor.  Thus the 240 off-support
    coordinates are generated by the mixed ideal in the local ring at that
    boundary (Nakayama).
2.  On the selected Hamilton-row face, retain the 96 non-support coordinates
    on off-path edges incident to endpoint 2 or 5.  Raw support-unit
    triangular division exposes 80 of them.  The remaining sixteen lie on
    edges 24 and 56.  Each is exposed by a two-row Bezout identity, so all 96
    coordinates, and hence every clean-cap error on this restricted face,
    lie in the support-localized mixed ideal.
3.  Six path-edge decorations are the next clean-error directions outside
    that face.  They have Bezout identities after quotienting by the 96
    off-path coordinates, but adjoining them simultaneously creates genuine
    quadratic alternate-matching cycles.  No full-face conclusion is made.

All coordinates and all mixed words are retained with their literal source
labels.  Support normalization means localization at the twelve chart-26
support coordinates followed by setting those units to one.
"""

from collections import Counter, defaultdict
from hashlib import sha256
from itertools import combinations, product
import importlib.util
import json
from pathlib import Path
from struct import pack


HERE = Path(__file__).resolve().parent
EXPECTED_LEDGER_SHA256 = (
    "86c7bef5437c2b5c6f41e511367177d0d358c349f7dac9734461eabe13846ada"
)
EXPECTED_ERROR_SHA256 = (
    "89ddd5380642f1a75b3991696a4cf6478e525d3aeeeb14e93fe7ffcfb5270d40"
)


def load_module(name, filename):
    path = HERE / filename
    spec = importlib.util.spec_from_file_location(name, path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


AUGMENTED = load_module(
    "n8_chart26_terminal_triangular_base",
    "verify_n8_chart26_augmented_terminal_chain.py",
)
TERMINAL = AUGMENTED.TERMINAL
D5 = AUGMENTED.D5

SUPPORT = frozenset(D5.SUPPORT_IDS)
TERMINAL_ROW = frozenset(TERMINAL.SELECTED_ROW)
BASE = SUPPORT | TERMINAL_ROW
ENDPOINTS = frozenset(TERMINAL.SELECTED_ENDPOINTS)
RESIDUAL_VERTICES = frozenset(range(8)) - ENDPOINTS
PATH_EDGES = frozenset(
    D5.COORDINATES[variable_id][:2]
    for variable_id in TERMINAL.SELECTED_ROW
)


def require(condition, detail):
    if not condition:
        raise RuntimeError(detail)


def word_text(word):
    return "".join(map(str, word))


def coordinate_text(variable_id):
    left, right, left_colour, right_colour = D5.COORDINATES[variable_id]
    return f"x{left}{right}_{left_colour}{right_colour}"


def normalized_hafnian(word, active_variables):
    """Restrict H_word, invert support, and return a sparse polynomial."""
    active = SUPPORT | frozenset(active_variables)
    answer = Counter()
    for term in D5.iter_word_terms(D5.word_code(word)):
        if set(term).issubset(active):
            answer[bytes(
                variable_id for variable_id in term
                if variable_id not in SUPPORT
            )] += 1
    return dict(answer)


def mixed_words():
    for word in product(range(3), repeat=8):
        if len(set(word)) != 1:
            yield word


def polynomial_without_ideal(polynomial, ideal_variables):
    ideal = frozenset(ideal_variables)
    return {
        monomial: coefficient
        for monomial, coefficient in polynomial.items()
        if not set(monomial).intersection(ideal)
    }


def support_boundary_audit():
    off_support = frozenset(range(len(D5.COORDINATES))) - SUPPORT
    linear_rows = {}
    options = defaultdict(list)
    full_polynomials = {}

    for word in mixed_words():
        polynomial = normalized_hafnian(word, off_support)
        linear = {
            monomial[0]: coefficient
            for monomial, coefficient in polynomial.items()
            if len(monomial) == 1
        }
        if not linear:
            continue
        require(b"" not in polynomial,
                "a support-boundary exposure row acquired a constant")
        require(len(linear) == 1 and set(linear.values()) == {1},
                "a support-boundary linear row stopped being one-hot")
        variable_id = next(iter(linear))
        linear_rows[word] = variable_id
        options[variable_id].append(word)
        full_polynomials[word] = polynomial

    require(len(off_support) == 240,
            "off-support coordinate census changed")
    require(len(linear_rows) == 358,
            "support-boundary mixed linear-row census changed")
    require(set(options) == off_support,
            "the support-boundary linearization lost a coordinate")
    option_histogram = Counter(map(len, options.values()))
    require(option_histogram == Counter({1: 130, 2: 102, 3: 8}),
            "support-boundary exposure-option histogram changed")

    # Every nonzero row has exactly one entry 1, so choosing one row for each
    # coordinate literally gives an identity matrix over Z, not merely full
    # rank modulo a prime.  The remaining terms have off-support degree >= 2.
    pivots = {}
    for variable_id in sorted(off_support):
        word = min(options[variable_id])
        polynomial = full_polynomials[word]
        require(polynomial.get(bytes((variable_id,))) == 1,
                "selected support-boundary pivot changed")
        require(all(
            monomial == bytes((variable_id,)) or len(monomial) >= 2
            for monomial in polynomial
        ), "a support-boundary pivot gained another linear term")
        pivots[variable_id] = word

    pivot_digest = sha256()
    for variable_id, word in sorted(pivots.items()):
        pivot_digest.update(bytes((variable_id,)))
        pivot_digest.update(bytes(word))

    return {
        "off_support_coordinates": len(off_support),
        "nonzero_mixed_linear_rows": len(linear_rows),
        "row_support_histogram": {1: len(linear_rows)},
        "coordinate_option_histogram": dict(sorted(option_histogram.items())),
        "selected_identity_minor_size": len(pivots),
        "selected_identity_minor_determinant": 1,
        "selected_pivot_digest": pivot_digest.hexdigest(),
        "nakayama_conclusion": (
            "in the support-boundary local ring, m=I_mix+m^2 and hence "
            "m=I_mix for the ideal m of all 240 off-support coordinates"
        ),
    }


def off_path_endpoint_coordinates():
    """The 96-coordinate face requested by the one-spoke calculation."""
    return frozenset(
        variable_id
        for variable_id, coordinate in enumerate(D5.COORDINATES)
        if variable_id not in BASE
        and coordinate[:2] not in PATH_EDGES
        and ENDPOINTS.intersection(coordinate[:2])
    )


def endpoint_unit_rows(candidates):
    active = TERMINAL_ROW | candidates
    rows = {}
    options = defaultdict(list)
    for word in mixed_words():
        polynomial = normalized_hafnian(word, active)
        unit_variables = tuple(
            monomial[0]
            for monomial, coefficient in polynomial.items()
            if len(monomial) == 1
            and monomial[0] in candidates
            and coefficient == 1
        )
        if not unit_variables:
            continue
        require(len(unit_variables) == 1,
                "an endpoint unit row stopped being one-hot")
        require(b"" not in polynomial,
                "an endpoint unit row acquired a candidate-free term")
        variable_id = unit_variables[0]
        rows[word] = (variable_id, polynomial)
        options[variable_id].append(word)
    return rows, options


def strict_option(variable_id, word, polynomial, candidates):
    """Return the dependency hyperedges for a raw support-unit pivot.

    A non-pivot term is admissible precisely when it contains some candidate
    other than the pivot.  It can then be discarded once at least one member
    of that dependency hyperedge has already been exposed.
    """
    dependencies = []
    for monomial in polynomial:
        if monomial == bytes((variable_id,)):
            continue
        candidate_support = frozenset(monomial).intersection(candidates)
        dependency = candidate_support - {variable_id}
        if not dependency:
            return None
        dependencies.append(dependency)
    # Supersets are redundant for the condition "meets the exposed set".
    reduced = frozenset(
        dependency for dependency in dependencies
        if not any(other < dependency for other in dependencies)
    )
    return word, tuple(sorted(reduced, key=lambda item: (len(item), tuple(item))))


def triangular_peel(candidates, rows, options):
    strict_options = defaultdict(list)
    for variable_id in candidates:
        for word in options[variable_id]:
            option = strict_option(
                variable_id, word, rows[word][1], candidates
            )
            if option is not None:
                strict_options[variable_id].append(option)

    exposed = set()
    rounds = []
    chosen = {}
    while True:
        eligible = []
        for variable_id in sorted(candidates - exposed):
            available = [
                (word, dependencies)
                for word, dependencies in strict_options[variable_id]
                if all(set(dependency).intersection(exposed)
                       for dependency in dependencies)
            ]
            if available:
                word, dependencies = min(
                    available,
                    key=lambda item: (
                        sum(map(len, item[1])), item[0]
                    ),
                )
                eligible.append((variable_id, word, dependencies))
        if not eligible:
            break
        prior = frozenset(exposed)
        round_variables = []
        for variable_id, word, dependencies in eligible:
            require(all(set(item).intersection(prior) for item in dependencies),
                    "one triangular round depends on itself")
            exposed.add(variable_id)
            round_variables.append(variable_id)
            chosen[variable_id] = (word, dependencies)
        rounds.append(tuple(round_variables))
    return frozenset(exposed), tuple(rounds), chosen, strict_options


def expected_cycle_words(variable_id):
    left, right, left_colour, right_colour = D5.COORDINATES[variable_id]
    if (left, right) == (2, 4):
        unit = (1, 1, left_colour, 1, right_colour, 1, 1, 1)
        monomial = (0, 0, left_colour, 1, right_colour, 1, 1, 1)
        first_row_variable = D5.COORDINATE_ID[(0, 1, 1, 1)]
        second_row_variable = D5.COORDINATE_ID[(3, 6, 1, 1)]
    elif (left, right) == (5, 6):
        unit = (2, 2, 2, 2, 2, left_colour, right_colour, 2)
        monomial = (1, 2, 1, 1, 1, left_colour, right_colour, 2)
        first_row_variable = D5.COORDINATE_ID[(0, 4, 2, 2)]
        second_row_variable = D5.COORDINATE_ID[(1, 7, 2, 2)]
    else:
        raise RuntimeError("unexpected terminal cycle edge")
    return unit, monomial, first_row_variable, second_row_variable


def endpoint_face_audit():
    candidates = off_path_endpoint_coordinates()
    require(len(candidates) == 96,
            "off-path endpoint-coordinate census changed")
    rows, options = endpoint_unit_rows(candidates)
    require(len(rows) == 148,
            "endpoint-face unit-row census changed")
    require(set(options) == candidates,
            "an endpoint coordinate lost every support-unit row")
    option_histogram = Counter(map(len, options.values()))
    require(option_histogram == Counter({1: 52, 2: 36, 3: 8}),
            "endpoint-face exposure-option histogram changed")

    exposed, rounds, chosen, strict_options = triangular_peel(
        candidates, rows, options
    )
    require(tuple(map(len, rounds)) == (18, 30, 29, 3),
            "endpoint triangular-round census changed")
    require(len(exposed) == 80,
            "endpoint raw triangular exposure count changed")
    remaining = candidates - exposed
    expected_remaining = frozenset(
        variable_id
        for variable_id in candidates
        if D5.COORDINATES[variable_id][:2] in ((2, 4), (5, 6))
    )
    require(remaining == expected_remaining and len(remaining) == 16,
            "the first endpoint cycle block changed")
    require(all(not strict_options[variable_id] for variable_id in remaining),
            "a cycle-block coordinate acquired a raw strict pivot")

    # The sixteen raw unit rows have a self-contaminated diagonal block.
    # A second mixed row supplies the monomial part of that coefficient, so
    # a literal two-row Bezout subtraction leaves z.  All discarded terms
    # contain one of the already-exposed eighty coordinates.
    cycle_records = []
    active = TERMINAL_ROW | candidates
    for variable_id in sorted(remaining):
        unit_word, monomial_word, first_row, second_row = (
            expected_cycle_words(variable_id)
        )
        unit_polynomial = polynomial_without_ideal(
            normalized_hafnian(unit_word, active), exposed
        )
        monomial_polynomial = polynomial_without_ideal(
            normalized_hafnian(monomial_word, active), exposed
        )
        pivot = bytes((variable_id,))
        self_term = bytes(sorted((first_row, second_row, variable_id)))
        second_term = bytes(sorted((second_row, variable_id)))
        require(unit_polynomial == {pivot: 1, self_term: 1},
                "a cycle-block unit equation changed")
        require(monomial_polynomial == {second_term: 1},
                "a cycle-block monomial equation changed")
        bezout = AUGMENTED.add(
            unit_polynomial,
            AUGMENTED.scale(
                AUGMENTED.multiply(
                    AUGMENTED.variable(first_row), monomial_polynomial
                ),
                -1,
            ),
        )
        require(bezout == {pivot: 1},
                "the terminal cycle Bezout repair changed")
        cycle_records.append({
            "coordinate": list(D5.COORDINATES[variable_id]),
            "unit_word": word_text(unit_word),
            "monomial_word": word_text(monomial_word),
            "unit_coefficient": (
                f"1+{coordinate_text(first_row)}*"
                f"{coordinate_text(second_row)}"
            ),
            "monomial_coefficient": coordinate_text(second_row),
            "bezout_multiplier": coordinate_text(first_row),
        })

    triangular_digest = sha256()
    for round_index, round_variables in enumerate(rounds):
        for variable_id in round_variables:
            word, dependencies = chosen[variable_id]
            triangular_digest.update(pack(">BH", round_index, variable_id))
            triangular_digest.update(bytes(word))
            for dependency in dependencies:
                triangular_digest.update(bytes(sorted(dependency)))
                triangular_digest.update(b"|")

    return {
        "candidates": candidates,
        "exposed": exposed,
        "remaining": remaining,
        "unit_rows": len(rows),
        "unit_row_support_histogram": {1: len(rows)},
        "coordinate_option_histogram": dict(sorted(option_histogram.items())),
        "strict_round_sizes": list(map(len, rounds)),
        "strictly_exposed_coordinates": len(exposed),
        "raw_unit_cycle_block": len(remaining),
        "cycle_edges": [[2, 4], [5, 6]],
        "cycle_block_records": cycle_records,
        "bezout_repaired_coordinates": len(remaining),
        "total_exposed_coordinates": len(candidates),
        "triangular_digest": triangular_digest.hexdigest(),
    }


def normalized_cap_blocks(active_ids):
    """Build cap blocks with chart support already specialized to one."""
    coordinates = {}
    for variable_id in BASE | frozenset(active_ids):
        coordinate = D5.COORDINATES[variable_id]
        coordinates[coordinate] = (
            {b"": 1} if variable_id in SUPPORT
            else AUGMENTED.variable(variable_id)
        )

    blocks = {edge: {} for edge in combinations(range(8), 2)}
    for coordinate, polynomial in coordinates.items():
        left, right, left_colour, right_colour = coordinate
        blocks[left, right][left_colour, right_colour] = polynomial

    def matrix(left, right):
        if left < right:
            return blocks[left, right]
        return {
            (right_colour, left_colour): polynomial
            for (left_colour, right_colour), polynomial
            in blocks[right, left].items()
        }

    cap = TERMINAL.SELECTED_CAP
    p, q = TERMINAL.SELECTED_ENDPOINTS
    residual = tuple(vertex for vertex in range(8) if vertex not in (p, q))
    scalar = {}
    for (left_colour, right_colour), polynomial in matrix(p, q).items():
        scalar = AUGMENTED.add(
            scalar,
            AUGMENTED.scale(polynomial, cap[left_colour][right_colour]),
        )

    direct = {}
    response = {}
    for position, left in enumerate(residual):
        for right in residual[position + 1:]:
            direct[left, right] = matrix(left, right)
            output = {}
            for (p_colour, left_colour), first in matrix(p, left).items():
                for (q_colour, right_colour), second in matrix(q, right).items():
                    key = (left_colour, right_colour)
                    output[key] = AUGMENTED.add(
                        output.get(key, {}),
                        AUGMENTED.scale(
                            AUGMENTED.multiply(first, second),
                            cap[p_colour][q_colour],
                        ),
                    )
            for (p_colour, right_colour), first in matrix(p, right).items():
                for (q_colour, left_colour), second in matrix(q, left).items():
                    key = (left_colour, right_colour)
                    output[key] = AUGMENTED.add(
                        output.get(key, {}),
                        AUGMENTED.scale(
                            AUGMENTED.multiply(first, second),
                            cap[p_colour][q_colour],
                        ),
                    )
            response[left, right] = output
    return residual, scalar, direct, response


def iter_cap_errors(active_ids):
    residual, scalar, direct, response = normalized_cap_blocks(active_ids)
    zero = {}
    matchings = TERMINAL.perfect_matchings(residual)
    for word in product(range(3), repeat=6):
        colour = dict(zip(residual, word))
        coefficient = {}
        for matching in matchings:
            coefficient = AUGMENTED.add(
                coefficient,
                AUGMENTED.product_polynomials(
                    response[edge].get(
                        (colour[edge[0]], colour[edge[1]]), zero
                    )
                    for edge in matching
                ),
            )
            for direct_edge in matching:
                left, right = direct_edge
                coefficient = AUGMENTED.add(
                    coefficient,
                    AUGMENTED.product_polynomials((
                        scalar,
                        direct[direct_edge].get(
                            (colour[left], colour[right]), zero
                        ),
                        *(response[edge].get(
                            (colour[edge[0]], colour[edge[1]]), zero
                        ) for edge in matching if edge != direct_edge),
                    )),
                )
        if coefficient:
            yield word, coefficient


def cap_error_audit(candidates):
    # The base Hamilton face is polynomially clean, not just clean at the
    # all-one row specialization.
    base_errors = tuple(iter_cap_errors(()))
    require(not base_errors,
            "the symbolic base terminal face stopped being clean")

    error_digest = sha256()
    output_words = 0
    term_count = 0
    degree_histogram = Counter()
    coefficient_histogram = Counter()
    for word, polynomial in iter_cap_errors(candidates):
        output_words += 1
        error_digest.update(bytes(word))
        for monomial, coefficient in sorted(polynomial.items()):
            require(set(monomial).intersection(candidates),
                    "a cap-error term escaped the exposed-coordinate ideal")
            term_count += 1
            degree_histogram[len(monomial)] += 1
            coefficient_histogram[coefficient] += 1
            error_digest.update(bytes((len(monomial),)))
            error_digest.update(monomial)
            error_digest.update(pack(">i", coefficient))

    require(output_words == 729,
            "simultaneous endpoint-spoke error word census changed")
    digest = error_digest.hexdigest()
    if EXPECTED_ERROR_SHA256 != "TO_BE_FILLED":
        require(digest == EXPECTED_ERROR_SHA256,
                "frozen simultaneous cap-error expansion changed")
    return {
        "base_error_outputs": 0,
        "simultaneous_error_outputs": output_words,
        "simultaneous_error_terms": term_count,
        "error_degree_histogram": dict(sorted(degree_histogram.items())),
        "error_coefficient_histogram": dict(sorted(
            coefficient_histogram.items()
        )),
        "every_error_term_meets_exposed_ideal": True,
        "error_expansion_digest": digest,
        "source_membership_conclusion": (
            "on the 96-coordinate off-path endpoint face, every clean-cap "
            "error lies in I_mix after chart-support localization"
        ),
    }


def beyond_face_audit(off_path_candidates):
    off_face = frozenset(range(len(D5.COORDINATES))) - BASE
    base_error = TERMINAL.cap_error()[2]
    influential = []
    for variable_id in sorted(off_face):
        coordinate = D5.COORDINATES[variable_id]
        if TERMINAL.cap_error((coordinate,))[2] != base_error:
            influential.append(variable_id)
    require(len(influential) == 45,
            "one-coordinate clean-error influence census changed")
    outside = frozenset(influential) - off_path_candidates
    expected_outside = frozenset((120, 121, 122, 240, 241, 242))
    require(outside == expected_outside,
            "the first clean-error directions outside the off-path face changed")

    # In the quotient by the 96 off-path coordinate ideal, each of these six
    # directions has exactly the same two-row Bezout repair as the 16-cycle
    # block.  This is a quotient statement only.
    quotient_records = []
    active = TERMINAL_ROW | expected_outside
    x04 = D5.COORDINATE_ID[(0, 4, 2, 2)]
    x17 = D5.COORDINATE_ID[(1, 7, 2, 2)]
    x01 = D5.COORDINATE_ID[(0, 1, 1, 1)]
    x36 = D5.COORDINATE_ID[(3, 6, 1, 1)]
    for variable_id in sorted(expected_outside):
        left, right, left_colour, right_colour = D5.COORDINATES[variable_id]
        if (left, right) == (2, 3):
            unit_word = (
                2, 2, left_colour, right_colour, 2, 2, 2, 2
            )
            monomial_word = (
                2, 1, left_colour, right_colour, 2, 1, 1, 1
            )
            first_row, second_row = x17, x04
        elif (left, right) == (5, 7):
            unit_word = (
                1, 1, 1, 1, 1, left_colour, 1, right_colour
            )
            monomial_word = (
                0, 0, 1, 1, 1, left_colour, 1, right_colour
            )
            first_row, second_row = x01, x36
        else:
            raise RuntimeError("unexpected path-edge error direction")

        pivot = bytes((variable_id,))
        unit = normalized_hafnian(unit_word, active)
        monomial = normalized_hafnian(monomial_word, active)
        require(unit == {
            pivot: 1,
            bytes(sorted((first_row, second_row, variable_id))): 1,
        }, "a path-edge quotient unit equation changed")
        require(monomial == {
            bytes(sorted((second_row, variable_id))): 1,
        }, "a path-edge quotient monomial equation changed")
        repaired = AUGMENTED.add(
            unit,
            AUGMENTED.scale(AUGMENTED.multiply(
                AUGMENTED.variable(first_row), monomial
            ), -1),
        )
        require(repaired == {pivot: 1},
                "a path-edge quotient Bezout repair changed")
        quotient_records.append({
            "coordinate": list(D5.COORDINATES[variable_id]),
            "unit_word": word_text(unit_word),
            "monomial_word": word_text(monomial_word),
        })

    # Adjoining the six variables at the same time as the 96 is not the same
    # as taking the quotient.  The original one-spoke boundary immediately
    # acquires an alternating-matching quadratic term.
    combined = off_path_candidates | expected_outside
    first_cycle = normalized_hafnian(AUGMENTED.BOUNDARY_WORD,
                                     TERMINAL_ROW | combined)
    x02 = D5.COORDINATE_ID[(0, 2, 0, 0)]
    x05 = D5.COORDINATE_ID[(0, 5, 0, 1)]
    x27 = D5.COORDINATE_ID[(2, 7, 0, 1)]
    require(first_cycle == {
        bytes((x02,)): 1,
        bytes(sorted((x05, x27))): 1,
    }, "the first simultaneous alternate-matching cycle changed")

    x23 = D5.COORDINATE_ID[(2, 3, 1, 0)]
    x26 = D5.COORDINATE_ID[(2, 6, 1, 2)]
    x35 = D5.COORDINATE_ID[(3, 5, 0, 2)]
    path_cycle_23 = normalized_hafnian(
        (2, 2, 1, 0, 2, 2, 2, 2), TERMINAL_ROW | combined
    )
    require(path_cycle_23 == {
        bytes((x23,)): 1,
        bytes(sorted((x26, x35))): 1,
        bytes(sorted((x04, x17, x23))): 1,
        bytes(sorted((x04, x17, x26, x35))): 1,
    }, "the first 23-path alternate-matching packet changed")

    x57 = D5.COORDINATE_ID[(5, 7, 2, 0)]
    x27_second = D5.COORDINATE_ID[(2, 7, 1, 0)]
    x45 = D5.COORDINATE_ID[(4, 5, 1, 2)]
    path_cycle_57 = normalized_hafnian(
        (1, 1, 1, 1, 1, 2, 1, 0), TERMINAL_ROW | combined
    )
    require(path_cycle_57 == {
        bytes((x57,)): 1,
        bytes(sorted((x27_second, x45))): 1,
        bytes(sorted((x01, x36, x57))): 1,
        bytes(sorted((x01, x27_second, x36, x45))): 1,
    }, "the first 57-path alternate-matching packet changed")

    combined_rows, combined_options = endpoint_unit_rows(combined)
    initial_strict_pivots = 0
    for variable_id in combined:
        for word in combined_options[variable_id]:
            option = strict_option(
                variable_id, word, combined_rows[word][1], combined
            )
            if option is not None and not option[1]:
                initial_strict_pivots += 1
    require(initial_strict_pivots == 0,
            "the combined path/off-path face acquired an initial raw pivot")

    return {
        "all_off_face_coordinates": len(off_face),
        "one_coordinate_error_directions": len(influential),
        "directions_inside_off_path_face": len(
            set(influential).intersection(off_path_candidates)
        ),
        "first_directions_outside_off_path_face": [
            list(D5.COORDINATES[variable_id])
            for variable_id in sorted(expected_outside)
        ],
        "path_edge_quotient_bezout_records": quotient_records,
        "first_simultaneous_cycle": {
            "source_word": word_text(AUGMENTED.BOUNDARY_WORD),
            "identity": (
                f"H_{word_text(AUGMENTED.BOUNDARY_WORD)}="
                f"{coordinate_text(x02)}+"
                f"{coordinate_text(x05)}*{coordinate_text(x27)}"
            ),
        },
        "path_edge_cycle_packets": [{
            "source_word": "22102222",
            "identity": (
                f"H_22102222=(1+{coordinate_text(x04)}*"
                f"{coordinate_text(x17)})*({coordinate_text(x23)}+"
                f"{coordinate_text(x26)}*{coordinate_text(x35)})"
            ),
        }, {
            "source_word": "11111210",
            "identity": (
                f"H_11111210=(1+{coordinate_text(x01)}*"
                f"{coordinate_text(x36)})*({coordinate_text(x57)}+"
                f"{coordinate_text(x27_second)}*{coordinate_text(x45)})"
            ),
        }],
        "combined_face_initial_strict_pivots": initial_strict_pivots,
        "scope_guard": (
            "the six path-edge directions are exposed only after quotienting "
            "by the solved 96-coordinate face; simultaneous adjoining creates "
            "quadratic matching cycles, so no full terminal-face membership "
            "is asserted"
        ),
    }


def audit():
    support_boundary = support_boundary_audit()
    endpoint = endpoint_face_audit()
    cap_error = cap_error_audit(endpoint["candidates"])
    beyond = beyond_face_audit(endpoint["candidates"])

    # Remove working sets from the JSON ledger.
    endpoint_ledger = {
        key: value for key, value in endpoint.items()
        if key not in ("candidates", "exposed", "remaining")
    }
    ledger = {
        "terminal_row": TERMINAL.SELECTED_ROW.hex(),
        "terminal_endpoints": list(TERMINAL.SELECTED_ENDPOINTS),
        "support_boundary": support_boundary,
        "off_path_endpoint_face": endpoint_ledger,
        "clean_cap_error": cap_error,
        "beyond_off_path_face": beyond,
        "conclusion": (
            "the selected 96-coordinate off-path endpoint face has exact "
            "mixed-source exposure: 80 raw triangular pivots plus sixteen "
            "two-row cycle repairs; every clean-cap error on that face is a "
            "support-localized mixed boundary"
        ),
        "scope_guard": (
            "this does not expose arbitrary simultaneous off-face coordinates; "
            "six path-edge error directions begin a quadratic alternate-"
            "matching cycle block"
        ),
    }
    digest = sha256(json.dumps(
        ledger, sort_keys=True, separators=(",", ":")
    ).encode()).hexdigest()
    if EXPECTED_LEDGER_SHA256 != "TO_BE_FILLED":
        require(digest == EXPECTED_LEDGER_SHA256,
                "frozen terminal triangular-exposure ledger changed")
    return ledger, digest


def main():
    ledger, digest = audit()
    print(
        "n=8 chart26 terminal triangular exposure: PASS; "
        "support rank=240, endpoint face=80+16=96"
    )
    print(json.dumps(ledger, sort_keys=True))
    print("sha256:", digest)


if __name__ == "__main__":
    main()
