#!/usr/bin/env python3
"""Reduce the beta=0 selected D0 branch to one protected target membership.

The genuine unary equation q^[3]=X0 proves selected-colour incidence, and
the genuine third cofactor J_M=1 is the first polynomial coefficient capable
of cancelling the unary Euler conormal.  Neither statement constructs the
needed selected-root target nullhomotopy.

The third cofactor is the top of the full-row four-cube.  Its formal Hasse
tail has the right coarse protected signature, but the same top sends H_m
to 1, leaves a primitive endpoint ridge, and has the wrong residual word.
The collision coefficient W_02 is likewise dormant through order two and
visible on 02|13|45 at order three, but that is an evaluated occurrence
coefficient, not a source chain with the D0 target readout.

Thus the exact remaining datum is the unit membership 1 in theta(Z), where
Z is the kernel of every protected/descent/ridge/word readout in the exact
grade and theta is the one-dimensional selected-root target quotient.  Over
a field the alternative is a normalized dual target covector.
"""

from __future__ import annotations

from fractions import Fraction as Q
from hashlib import sha256
from itertools import combinations_with_replacement
import importlib.util
import json
from pathlib import Path
import sys


ROOT = Path(__file__).resolve().parents[1]
PINS = {
    "computations/verify_h3_trace_cartan_lower_rees_typing_gate.py":
        "0190a8fa16dddf9cecf2de676d4f3ff87d184f031e523d87e1f80937ff55be94",
    "computations/verify_h3_post_ks_full_nine_overlap_visibility_reduction.py":
        "3a18ddb3cf717d41dd3d8033d128382093d33561c98ab164bec9876b74fb8eb8",
    "computations/verify_collision_cofactor_bianchi.py":
        "34a768e749891a0a51c5feac30ff6702f40d70e12069a52c83cbf160f3876ceb",
    "computations/verify_complete_normal_block_countermodel.py":
        "4077b60c696d9223bc9159ab2c3119ea6593f670b380855b35c8cf61ef7bb030",
    "computations/verify_h3_pure_unary_cofactor_incidence_attachment.py":
        "3295183db431e14733eceea645a28113eccd086eebbf256afaa7127cc826b8cd",
    "computations/verify_h3_rootless_third_cofactor_bianchi_total_complex_obstruction.py":
        "ebd25f79a6fe8db936fe5601b9220f152c5349dd794bbc4e08b2095f1c1d059f",
    "computations/verify_h3_rootless_one_face_third_cofactor_comparison_vertex_gate.py":
        "37251145d805861b2d1b15b7bf37cf9f98ba30b03fbcffa1daa4fc35789efe84",
    "computations/verify_h3_source_valid_tower_first_obstruction.py":
        "ba37c966c2ef2cca2f8909a91e8ff8a8567282e68a847ac4eef75d3bb78a56ac",
}
EXPECTED_LEDGER_SHA256 = (
    "c39179ccecb69e53acd00cb151e87b93f97ee61b77b4568a21c5820a1a0c17cc"
)


def require(condition: bool, message: object) -> None:
    if not condition:
        raise RuntimeError(message)


def load(relative: str, name: str):
    specification = importlib.util.spec_from_file_location(name, ROOT / relative)
    require(specification is not None and specification.loader is not None,
            ("cannot import", relative))
    module = importlib.util.module_from_spec(specification)
    specification.loader.exec_module(module)
    return module


def dot(left, right):
    return sum((Q(a) * Q(b) for a, b in
                zip(left, right, strict=True)), Q(0))


def rank(rows):
    work = [list(map(Q, row)) for row in rows]
    if not work:
        return 0
    pivot_row = 0
    for column in range(len(work[0])):
        pivot = next((row for row in range(pivot_row, len(work))
                      if work[row][column]), None)
        if pivot is None:
            continue
        work[pivot_row], work[pivot] = work[pivot], work[pivot_row]
        value = work[pivot_row][column]
        work[pivot_row] = [entry / value for entry in work[pivot_row]]
        for row in range(len(work)):
            if row == pivot_row or not work[row][column]:
                continue
            value = work[row][column]
            work[row] = [left - value * right for left, right in
                         zip(work[row], work[pivot_row], strict=True)]
        pivot_row += 1
    return pivot_row


def audit_beta_zero(trace):
    record = trace.audit_beta_zero()
    require(record["Jstar"] == 0
            and record["surviving_root_branch"] == "D2 only"
            and record["missing_root_branch"] == "D0"
            and record["J_row_selected_D0_coefficient"] == 0
            and record["selected_target_first_PP_order"] == 3
            and record["complementary_target_first_PP_order"] == 2,
            "the intrinsic beta-zero root split changed")

    # After quotienting by the complementary D2 branch and the pure target
    # cap, the selected target quotient is one-dimensional, generated by D0.
    d0 = (Q(1), Q(0))
    d2 = (Q(0), Q(1))
    required = (Q(1), Q(1))
    require(rank((d2, required)) == 2
            and rank((d2, d0)) == 2,
            "D0 stopped being the primitive beta-zero target quotient")
    return {
        "Jstar": 0,
        "existing_root_span": "D2",
        "selected_root_quotient_generator": "[D0]",
        "selected_first_principal_part_order": 3,
        "complementary_first_principal_part_order": 2,
        "quotient_rank": 1,
    }


def audit_unary_incidence(overlap):
    incidence = overlap.audit_h3_six_site_incidence()
    require(incidence["residual_boundary_sites"] == 6
            and incidence["minimum_target_full_sites"] == 2
            and incidence["uniform_reason"].startswith(
                "q^[3]=X_0 gives D_0=U"),
            "the unary/full-nine incidence theorem changed")
    return {
        "equation": "q^[3]=X0",
        "consequence": "the selected colour is incident at all six sites",
        "minimum_sites_full_in_all_three_target_axes": 2,
        "does_not_construct_selected_root_nullhomotopy": True,
        "reason": (
            "incidence is a statement about the q-star ideal; it does not "
            "give a source chain in the mixed D0 target word and exact "
            "adjacent Rees grade"
        ),
    }


def audit_cofactor_and_full_row(pure, total, vertex):
    tower = pure.cofactor_tower_audit()
    require(tower["first_polynomially_capable_order"] == 3
            and tower["third_cofactors"] == 15
            and tower["closed_identity"].startswith(
                "3F0-sum_e q_e H_e+3u J_M=0"),
            "the genuine unary third-cofactor identity changed")

    total_ledger = total.audit()
    complex_record = total_ledger["third_cofactor_total_complex"]
    bridge = complex_record["source_labelled_bridge"]
    descent = complex_record["descent_obstruction"]
    grade = total_ledger["endpoint_midpoint_grade"]
    require(complex_record["formal_total_complex"]["tail_signature"]
            == [-1, 0, 0, 0]
            and complex_record["formal_total_complex"]["d_squared"] == 0
            and descent["fourth_operator_on_source_equation"] == 1
            and bridge["ridge_mismatch_rank"] == 6
            and bridge["primitive_omega_rank"] == 5
            and grade["midpoint_hits"] == 0,
            "the full-row third-cofactor descent guard changed")

    canonical = vertex.canonical_cube_and_unit()
    coarse = vertex.coarse_candidate()
    adjacent = vertex.one_adjacent_edge_gate()
    fine = vertex.fine_grade_and_word_gate()
    require(canonical["fourth_operator_on_H_m"] == 1
            and canonical["fourth_operator_on_H_0_minus_u"] == 0
            and coarse["coarse_signature_is_desired"] is True
            and coarse["source_valid"] is False
            and coarse["selected_fourth_operator_value"] == "1/2"
            and adjacent["remaining_rows"] == [0, 1, 1, -1]
            and fine["word_change_supplied_by_multiplication_or_adjacent_edge"]
                is False,
            "the one-face physical guard changed")
    return {
        "unary_cofactor": {
            "third_matching_units": tower["third_cofactors"],
            "first_polynomially_capable_order": 3,
            "exact_identity": tower["closed_identity"],
            "physical_lower_face_constructed": False,
        },
        "full_row_identification": (
            "J_M=d_M(q^[3])=d_(pq,M)(H_m)=1; the order-three unary "
            "cofactor is the order-four full-row top"
        ),
        "formal_Hasse_totalization": {
            "tail_signature_ainc_W_target_ores": [-1, 0, 0, 0],
            "d_squared": 0,
            "coarse_half_sum_has_desired_signature": True,
        },
        "physical_obstructions": {
            "source_descent_unit": descent["fourth_operator_on_source_equation"],
            "endpoint_ridge_rank": bridge["ridge_mismatch_rank"],
            "primitive_Omega_rank": bridge["primitive_omega_rank"],
            "one_adjacent_edge_remainder": adjacent["remaining_rows"],
            "selected_midpoint_word_hits": grade["midpoint_hits"],
            "polynomial_homogenization_changes_source_word": False,
        },
    }


def audit_dormant_third_bianchi(collision):
    n = 6
    q0 = {
        (0, 1, collision.X, collision.X): Q(2),
        (2, 3, collision.X, collision.X): Q(1),
        (4, 5, collision.X, collision.X): Q(1),
        (1, 2, collision.Y, collision.Y): Q(1),
        (3, 4, collision.Y, collision.Y): Q(1),
        (0, 5, collision.Y, collision.Y): Q(1),
    }
    tangent = {(1, 3, collision.Z, collision.X): Q(1)}
    zero_direct = {}
    live_direct = {(0, 2): Q(1)}
    colourings = tuple(__import__("itertools").product(
        (collision.X, collision.Y, collision.Z), repeat=n
    ))
    for colouring in colourings:
        zero = collision.source_polynomial(
            n, q0, tangent, zero_direct, colouring)
        live = collision.source_polynomial(
            n, q0, tangent, live_direct, colouring)
        require(all(zero.get(order, Q(0)) == live.get(order, Q(0))
                    for order in range(3)),
                ("W02 stopped being dormant below order three", colouring))
    marked = (collision.Z, collision.Z, collision.Z,
              collision.X, collision.X, collision.X)
    zero_third = collision.source_polynomial(
        n, q0, tangent, zero_direct, marked).get(3, Q(0))
    live_third = collision.source_polynomial(
        n, q0, tangent, live_direct, marked).get(3, Q(0))
    require((zero_third, live_third) == (Q(0), Q(1)),
            "the 02|13|45 third-Bianchi carrier changed")

    # Logical independence guard.  Keep unary incidence and the exact
    # third-Bianchi occurrence evaluation fixed.  The target lift can still
    # be zero or the identity: an occurrence covector is not a target chain.
    common_source_data = (Q(1), Q(1))  # (unary incidence, Bianchi carrier)
    bad_target_lift = Q(0)
    good_target_lift = Q(1)
    require(common_source_data == (Q(1), Q(1))
            and bad_target_lift != good_target_lift,
            "the occurrence/target independence guard collapsed")
    return {
        "dormant_cell": "W_02",
        "orders_zero_one_two_equal_for_all_colourings": len(colourings),
        "first_visible_order": 3,
        "unique_marked_matching": "02|13|45",
        "third_coefficient_without_W02": str(zero_third),
        "third_coefficient_with_W02": str(live_third),
        "interpretation": (
            "third Bianchi detects/determines an occurrence coefficient; "
            "it does not define its mixed D0 target or protected source lift"
        ),
        "same_unary_and_Bianchi_data_allow_target_lift_ranks": [0, 1],
    }


def audit_membership_alternative():
    # Model the exact one-output theorem after restricting the complete
    # source domain to Z=ker(protected, descent, ridge, word).  theta:Z->S
    # is the coefficient of [D0].  Over a field its image has rank 0 or 1.
    records = []
    for theta_rows in ((), (Q(0),), (Q(1),), (Q(0), Q(1))):
        image_rank = int(any(theta_rows))
        unit_membership = image_rank == 1
        dual_exists = image_rank == 0
        require(unit_membership != dual_exists,
                "the rank-one membership/dual alternative failed")
        records.append({
            "theta_values_on_test_basis": [str(value)
                                            for value in theta_rows],
            "image_rank": image_rank,
            "unit_D0_membership": unit_membership,
            "normalized_target_dual": dual_exists,
        })
    return {
        "exact_grade_domain": (
            "Z=kernel of lower/W/ores/ainc, source-descent, endpoint-ridge, "
            "and source-word mismatch readouts in the selected order-3 grade"
        ),
        "target_map": "theta:Z -> Q0=S*[D0]",
        "positive_branch": "1 belongs to theta(Z)",
        "field_dual_branch": (
            "theta(Z)=0, so [D0]^* kills every protected physical chain "
            "and evaluates to 1 on the desired normalized cell"
        ),
        "ring_version": (
            "the ideal theta(Z) is the primary object; if it is proper, "
            "reduce modulo a maximal ideal containing it to obtain the dual"
        ),
        "finite_rank_one_alternatives": records,
    }


def audit_source_validity_order(source_valid):
    ledger, digest = source_valid.audit()
    require(digest == source_valid.EXPECTED_LEDGER_SHA256
            and ledger["phi_filtration_surviving"]
                == {"1": 0, "2": 0, "3": 0, "4": 90}
            and ledger["coordinate_transversality_checks"] == 90
            and ledger["witness_point"]["u"] == 90,
            "the source-valid Hasse-order obstruction changed")
    return {
        "pure_sector_survivors_orders_1_to_4": [0, 0, 0, 90],
        "coordinate_fourth_top_checks": 90,
        "source_valid_template_informative": False,
        "reason": (
            "the unit full-row top is exactly the transversality needed by "
            "the formal tail, while a source-valid tower sends that top "
            "back into the source ideal and cannot make it an informative unit"
        ),
    }


def audit_dold_kan_degeneracy():
    """Normalized chains of the standard 4-simplex.

    A nondecreasing vertex string is degenerate exactly when a vertex is
    repeated.  The normalized quotient kills those strings.  Its alternating
    boundary also vanishes after normalization.  The unique nondegenerate
    four-simplex instead has all five nondegenerate codimension-one faces.
    """
    top_simplices = tuple(combinations_with_replacement(range(5), 5))
    require(len(top_simplices) == 126,
            "the standard 4-simplex top census changed")

    def normalized_boundary(simplex):
        coefficients = {}
        for index in range(len(simplex)):
            face = simplex[:index] + simplex[index + 1:]
            if len(set(face)) != len(face):
                continue
            coefficients[face] = coefficients.get(face, 0) + (-1) ** index
            if not coefficients[face]:
                del coefficients[face]
        return coefficients

    nondegenerate = tuple(simplex for simplex in top_simplices
                          if len(set(simplex)) == len(simplex))
    degenerate = tuple(simplex for simplex in top_simplices
                       if len(set(simplex)) != len(simplex))
    require(nondegenerate == ((0, 1, 2, 3, 4),)
            and len(degenerate) == 125
            and all(not normalized_boundary(simplex)
                    for simplex in degenerate),
            "a Dold-Kan degeneracy acquired normalized boundary")
    top_boundary = normalized_boundary(nondegenerate[0])
    require(len(top_boundary) == 5
            and set(top_boundary.values()) == {-1, 1},
            "the nondegenerate 4-simplex lost a proper face")
    return {
        "standard_four_simplex_top_strings": len(top_simplices),
        "degenerate_top_strings": len(degenerate),
        "degeneracies_surviving_normalization": 0,
        "normalized_boundaries_of_degeneracies": 0,
        "nondegenerate_top_strings": 1,
        "nondegenerate_normalized_boundary_faces": len(top_boundary),
        "consequence": (
            "declaring J_M a degeneracy makes it zero and cannot produce "
            "u*J_M*Eq.  Treating it as a nondegenerate Spencer/Hasse top "
            "retains every proper face; in the physical labelled cube these "
            "include the already nonzero endpoint ridge Omega"
        ),
        "Dold_Kan_scope": (
            "normalization is an equivalence for an already constructed "
            "simplicial source module; it does not adjoin a missing physical "
            "syzygy or turn a non-ideal-preserving operator into one"
        ),
    }


def audit_order_three_product_rule():
    # The selected unary matching monomial is e1*e2*e3.  Use squarefree
    # subsets as monomials and literal partial derivatives.
    variables = frozenset(("e1", "e2", "e3"))

    def derivative(monomial, selected):
        output = set(monomial)
        for variable in selected:
            if variable not in output:
                return None
            output.remove(variable)
        return frozenset(output)

    top = derivative(variables, ("e1", "e2", "e3"))
    require(top == frozenset(),
            "the unary matching third cofactor stopped being one")
    proper = {
        size: sum(1 for simplex in __import__("itertools").combinations(
            variables, size
        ) if derivative(variables, simplex) is not None)
        for size in range(4)
    }
    require(proper == {0: 1, 1: 3, 2: 3, 3: 1},
            "the order-three product-rule face census changed")

    # Exact coarse rows from the canonical one-face calculation.  The
    # order-three proper-face tail and the exceptional unary lift cancel
    # lower incidence after the half-sum while retaining physical anchor -1.
    # Row order: (lower, ainc, W, target, ores).
    formal_tail = (Q(-1), Q(-1), Q(0), Q(0), Q(0))
    exceptional_unary = (Q(1), Q(-1), Q(0), Q(0), Q(0))
    half_sum = tuple((left + right) / 2 for left, right in
                     zip(formal_tail, exceptional_unary, strict=True))
    require(half_sum == (Q(0), Q(-1), Q(0), Q(0), Q(0)),
            "the unary/product-rule protected signature changed")
    connecting_value = Q(1, 2)  # tail has Psi=1, unary has Psi=0.
    require(connecting_value,
            "the formal order-three candidate unexpectedly descended")
    return {
        "selected_matching_monomial": "q_e1*q_e2*q_e3",
        "squarefree_face_counts_orders_0_to_3": [1, 3, 3, 1],
        "third_cofactor": "d_e1 d_e2 d_e3(q_e1 q_e2 q_e3)=1",
        "row_order": ["lower", "ainc", "W", "target", "ores"],
        "proper_face_tail": [str(value) for value in formal_tail],
        "exceptional_unary_lift": [str(value) for value in exceptional_unary],
        "half_sum": [str(value) for value in half_sum],
        "target_cancelled": True,
        "ordinary_residue_zero": True,
        "physical_anchor_incidence": -1,
        "source_connecting_value": str(connecting_value),
        "source_valid": False,
        "conclusion": (
            "the product rule constructs the correct coarse lower/anchor "
            "packet only in the prolonged Hasse module.  It neither cancels "
            "the source-descent unit nor supplies the selected mixed D0 "
            "upper target label"
        ),
    }


def audit():
    for relative, expected in PINS.items():
        actual = sha256((ROOT / relative).read_bytes()).hexdigest()
        require(actual == expected,
                ("pinned dependency changed", relative, actual))
    trace = load(
        "computations/verify_h3_trace_cartan_lower_rees_typing_gate.py",
        "beta0_trace",
    )
    overlap = load(
        "computations/verify_h3_post_ks_full_nine_overlap_visibility_reduction.py",
        "beta0_overlap",
    )
    # The collision audit uses this sibling by its historical bare module
    # name.  Register the pinned file explicitly so isolated ``-I -S`` mode
    # does not depend on the script directory being placed on sys.path.
    normal = load(
        "computations/verify_complete_normal_block_countermodel.py",
        "verify_complete_normal_block_countermodel",
    )
    sys.modules["verify_complete_normal_block_countermodel"] = normal
    collision = load(
        "computations/verify_collision_cofactor_bianchi.py",
        "beta0_collision",
    )
    pure = load(
        "computations/verify_h3_pure_unary_cofactor_incidence_attachment.py",
        "beta0_pure",
    )
    total = load(
        "computations/verify_h3_rootless_third_cofactor_bianchi_total_complex_obstruction.py",
        "beta0_total",
    )
    vertex = load(
        "computations/verify_h3_rootless_one_face_third_cofactor_comparison_vertex_gate.py",
        "beta0_vertex",
    )
    source_valid = load(
        "computations/verify_h3_source_valid_tower_first_obstruction.py",
        "beta0_source_valid",
    )
    ledger = {
        "theorem": "beta-zero D0 unary/third-Bianchi membership gate",
        "pins": PINS,
        "intrinsic_beta_zero_target": audit_beta_zero(trace),
        "genuine_unary_full_nine": audit_unary_incidence(overlap),
        "third_cofactor_full_row": audit_cofactor_and_full_row(
            pure, total, vertex),
        "source_valid_Hasse_order": audit_source_validity_order(source_valid),
        "Dold_Kan_Spencer_degeneracy": audit_dold_kan_degeneracy(),
        "order_three_product_rule": audit_order_three_product_rule(),
        "collision_third_Bianchi": audit_dormant_third_bianchi(collision),
        "exact_membership_or_dual": audit_membership_alternative(),
        "verdict": (
            "the genuine unary equation and third-order cofactor/Bianchi "
            "hierarchy do not construct the beta-zero selected D0 target "
            "nullhomotopy.  Unary gives incidence; J_M gives a formal tail "
            "whose full-row lift is non-descending; W02 gives an occurrence "
            "carrier without a target map.  The remaining theorem is the "
            "single unit membership 1 in theta(Z), or its residue-field dual"
        ),
        "first_new_physical_type": (
            "a source-valid endpoint-word-changing Cartan/Spencer or higher "
            "occurrence-splitting cell landing in the selected exact final "
            "word and order-3 grade, killing the descent unit and Omega "
            "ridge and mapping nontrivially to [D0]"
        ),
    }
    digest = sha256(json.dumps(
        ledger, sort_keys=True, separators=(",", ":")
    ).encode()).hexdigest()
    if EXPECTED_LEDGER_SHA256 != "TO_BE_PINNED":
        require(digest == EXPECTED_LEDGER_SHA256,
                ("beta-zero D0 ledger changed", digest))
    return ledger, digest


def main():
    _ledger, digest = audit()
    print("h3 beta=0 selected D0 unary/third-Bianchi gate: PASS")
    print("q^[3]=X0: selected incidence YES; D0 nullhomotopy NO")
    print("third cofactor: formal tail YES; physical descent NO")
    print("W02 on 02|13|45: first visible order 3; target lift NOT IMPLIED")
    print("remaining: one protected D0 unit membership or residue-field dual")
    print("ledger_sha256=" + digest)


if __name__ == "__main__":
    main()
