#!/usr/bin/env python3
"""Audit the relative Tate completion of the centered occurrence shear.

Let ``S=k[u_M]`` be the polynomial algebra on the ninety formal occurrence
coordinates and let ``A=S/I`` be their physical monomial image in
``k[p,s,q]``.  The centered shear derivation is

    delta_0(u_M)=-L,       L=z^T u,       1^T z=0.

It does not preserve ``I``.  On a relation ``r`` its defect is
``delta_0(r)=-L*partial_1(r)``, where
``partial_1=sum_M partial/partial u_M``.  After adjoining the *relative*
Koszul/Tate cell ``epsilon`` with ``d epsilon=L``, set

    delta(e_r)=-epsilon*partial_1(r)

for a degree-one Tate generator ``d e_r=r``.  This cancels every relation
defect, not only the first quadratic minor.

Because A is a toric domain and L is nonzero, L is A-regular.  Therefore a
semi-free resolution Q of A satisfies

    H_i(Q tensor K(L)) = 0 for i>0.

At every later Tate generator, the failure of ``[d,delta]=0`` is a positive
degree cycle and hence has a filler.  This gives a noncanonical recursive
homotopy-coherent lift over k and over k[beta].  It is a relative extension
resolving A/(L), not a quasi-isomorphic strict lift of A itself.

The checker also measures why this is not a finite Koszul source theorem.
The occurrence semigroup has rank 20, so I has height 70, while its minimal
quadratic relation space already has dimension 225.  In internal degree 3
there are 5160 additional binomials not generated by the quadrics, plus 350
linear syzygies among the quadratic generators.  The algebra is not a
complete intersection; its minimal commutative Tate/acyclic closure is
infinite.  The first explicit quadratic-disconnected cubic fibre is

    u_0*u_4*u_13-u_1*u_3*u_14=0.

Its shear defect is again ``-L*partial_1(r_3)`` and is filled by the same
epsilon formula.  Thus there is no new abstract obstruction beyond the
relative comparison cell, but there is no finite explicit physical cell
package supplied by formal Tate recursion either.
"""

from __future__ import annotations

from collections import Counter, defaultdict
from fractions import Fraction as Q
from hashlib import sha256
from itertools import combinations_with_replacement
import json
from math import comb
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
N = 90
PINS = {
    "computations/verify_h3_universal_occurrence_shear_physical_toric_lift_gate.py":
        "ca5ede5e7a2cc11bf9f62bdcca8349813c3585b401ea614b8622fa40e63c7609",
    "notes/h3-universal-occurrence-shear-physical-toric-lift-gate.md":
        "9764018dcccd47e774c285c4bff51ca095fa219e879c8d4a2a7cd51394da5d7e",
    "computations/verify_h3_universal_response_toric_minor_terminal_gate.py":
        "c40790270ef38ea72ec1601037f81319e02638d80828d96ee341e73d9f665e37",
    "notes/h3-universal-response-toric-minor-terminal-gate.md":
        "9718c4bda2e411a65c9b18d2e4ffd42a270b2458374b92690b40d3e0f0b23cd4",
    "computations/verify_h3_universal_occurrence_shear_toric_lift_gate.py":
        "097ef9de606f10ed8fd43069b72e70d0ab027a06ac3e98bfeb786325ae08423c",
    "notes/h3-universal-occurrence-shear-toric-lift-gate.md":
        "85ae5c956ddd1b08433b07c1b45238cc88a542fe5434604e48635b6ef4efc1e3",
}
EXPECTED_LEDGER_SHA256 = (
    "553516dd148e4e85ce5848aa444fe16500eb94f82a30c5b5ac4dc4dcb8eec786"
)


def require(condition: bool, detail: object) -> None:
    if not condition:
        raise RuntimeError(detail)


def pin_dependencies() -> None:
    for relative, expected in PINS.items():
        actual = sha256((ROOT / relative).read_bytes()).hexdigest()
        require(actual == expected,
                ("pinned dependency changed", relative, actual, expected))


def perfect_matchings(vertices):
    vertices = tuple(sorted(vertices))
    if not vertices:
        yield ()
        return
    first = vertices[0]
    for index, second in enumerate(vertices[1:], start=1):
        rest = vertices[1:index] + vertices[index + 1:]
        for tail in perfect_matchings(rest):
            yield tuple(sorted(((first, second),) + tail))


def occurrence_data():
    occurrences = []
    for p_site in range(6):
        for s_site in range(6):
            if p_site == s_site:
                continue
            residual = tuple(site for site in range(6)
                             if site not in (p_site, s_site))
            for matching in perfect_matchings(residual):
                occurrences.append((p_site, s_site, matching))
    require(len(occurrences) == len(set(occurrences)) == N,
            "the occurrence inventory changed")

    variables = (
        tuple(("p", site) for site in range(6))
        + tuple(("s", site) for site in range(6))
        + tuple(("q", left, right)
                for left in range(6) for right in range(left + 1, 6))
    )
    variable_index = {variable: index
                      for index, variable in enumerate(variables)}
    exponents = []
    for p_site, s_site, matching in occurrences:
        exponent = [0] * len(variables)
        exponent[variable_index[("p", p_site)]] = 1
        exponent[variable_index[("s", s_site)]] = 1
        for left, right in matching:
            exponent[variable_index[("q", left, right)]] += 1
        exponents.append(tuple(exponent))
    return tuple(occurrences), tuple(variables), tuple(exponents)


def rank(columns) -> int:
    if not columns:
        return 0
    height = len(columns[0])
    require(all(len(column) == height for column in columns), "rank width")
    rows = [[Q(columns[column][row]) for column in range(len(columns))]
            for row in range(height)]
    answer = 0
    for column in range(len(columns)):
        pivot = next((row for row in range(answer, height)
                      if rows[row][column]), None)
        if pivot is None:
            continue
        rows[answer], rows[pivot] = rows[pivot], rows[answer]
        pivot_value = rows[answer][column]
        rows[answer] = [value / pivot_value for value in rows[answer]]
        for row in range(height):
            if row == answer or not rows[row][column]:
                continue
            coefficient = rows[row][column]
            rows[row] = [left - coefficient * right
                         for left, right in
                         zip(rows[row], rows[answer], strict=True)]
        answer += 1
    return answer


def exponent_sum(exponents, indices):
    return tuple(sum(exponents[index][coordinate] for index in indices)
                 for coordinate in range(len(exponents[0])))


def quadratic_fibres(exponents):
    fibres = defaultdict(list)
    for pair in combinations_with_replacement(range(N), 2):
        fibres[exponent_sum(exponents, pair)].append(pair)
    return fibres


def degree_two_audit(exponents) -> tuple[dict[str, object], dict[tuple[int, int], tuple[int, int]]]:
    semigroup_rank = rank(exponents)
    height = N - semigroup_rank
    fibres = quadratic_fibres(exponents)
    source_monomials = comb(N + 1, 2)
    relation_dimension = source_monomials - len(fibres)
    profile = Counter(len(fibre) for fibre in fibres.values())
    require(semigroup_rank == 20 and height == 70
            and source_monomials == 4095
            and len(fibres) == 3870
            and relation_dimension == 225
            and profile == {1: 3645, 2: 225},
            ("the quadratic toric census changed",
             semigroup_rank, height, relation_dimension, profile))

    replacements = {}
    for fibre in fibres.values():
        if len(fibre) != 2:
            continue
        left, right = fibre
        replacements[left] = right
        replacements[right] = left
    require(len(replacements) == 450,
            "the quadratic replacement inventory changed")
    return ({
        "physical_coefficient_variables": 27,
        "occurrence_generators": N,
        "semigroup_rank": semigroup_rank,
        "toric_ideal_height": height,
        "quadratic_source_monomials": source_monomials,
        "distinct_physical_quadratic_images": len(fibres),
        "minimal_independent_quadratic_relations": relation_dimension,
        "quadratic_fibre_profile": {
            str(size): multiplicity
            for size, multiplicity in sorted(profile.items())
        },
        "complete_intersection": False,
        "non_CI_witness": "mu(I)>=225>height(I)=70",
    }, replacements)


def degree_three_audit(occurrences, exponents, replacements) -> dict[str, object]:
    fibres = defaultdict(list)
    for triple in combinations_with_replacement(range(N), 3):
        fibres[exponent_sum(exponents, triple)].append(triple)
    source_monomials = comb(N + 2, 3)
    ideal_dimension = source_monomials - len(fibres)
    profile = Counter(len(fibre) for fibre in fibres.values())

    total_components = 0
    disconnected = []
    for signature, vertices in fibres.items():
        lookup = {vertex: index for index, vertex in enumerate(vertices)}
        parent = list(range(len(vertices)))

        def find(index):
            while parent[index] != index:
                parent[index] = parent[parent[index]]
                index = parent[index]
            return index

        def union(left, right):
            left = find(left)
            right = find(right)
            if left != right:
                parent[right] = left

        for vertex_index, vertex in enumerate(vertices):
            for left, right, remaining in ((0, 1, 2), (0, 2, 1), (1, 2, 0)):
                pair = tuple(sorted((vertex[left], vertex[right])))
                if pair not in replacements:
                    continue
                target = tuple(sorted(replacements[pair] + (vertex[remaining],)))
                if target in lookup:
                    union(vertex_index, lookup[target])
        components = len({find(index) for index in range(len(vertices))})
        total_components += components
        if components > 1:
            disconnected.append((signature, tuple(vertices), components))

    quadratic_ideal_degree_three_rank = source_monomials - total_components
    new_cubic_generators = total_components - len(fibres)
    linear_quadratic_syzygies = (
        N * 225 - quadratic_ideal_degree_three_rank
    )
    disconnected_profile = Counter(
        (len(vertices), components)
        for _, vertices, components in disconnected
    )
    require(source_monomials == 125580
            and len(fibres) == 100520
            and ideal_dimension == 25060
            and quadratic_ideal_degree_three_rank == 19900
            and new_cubic_generators == 5160
            and linear_quadratic_syzygies == 350
            and disconnected_profile == {(2, 2): 5160},
            ("the cubic toric census changed", source_monomials,
             len(fibres), ideal_dimension,
             quadratic_ideal_degree_three_rank,
             new_cubic_generators, linear_quadratic_syzygies,
             disconnected_profile))

    # Freeze the lexicographically first quadratic-disconnected cubic fibre.
    first = min(disconnected, key=lambda item: item[1])
    _, vertices, components = first
    require(vertices == ((0, 4, 13), (1, 3, 14)) and components == 2,
            ("the first primitive cubic changed", vertices, components))
    require(exponent_sum(exponents, vertices[0])
            == exponent_sum(exponents, vertices[1]),
            "the primitive cubic stopped being a physical relation")
    explicit_occurrences = {
        str(index): [
            occurrences[index][0],
            occurrences[index][1],
            [list(edge) for edge in occurrences[index][2]],
        ]
        for index in sorted(set(vertices[0] + vertices[1]))
    }
    return {
        "cubic_source_monomials": source_monomials,
        "distinct_physical_cubic_images": len(fibres),
        "full_toric_I3_dimension": ideal_dimension,
        "quadratic_ideal_degree_three_rank": quadratic_ideal_degree_three_rank,
        "new_minimal_cubic_generators": new_cubic_generators,
        "linear_syzygies_among_225_quadrics": linear_quadratic_syzygies,
        "quadratic_disconnected_fibre_profile": {
            f"size_{size}_components_{components}": multiplicity
            for (size, components), multiplicity
            in sorted(disconnected_profile.items())
        },
        "first_primitive_cubic": "u0*u4*u13-u1*u3*u14",
        "first_primitive_cubic_occurrences": explicit_occurrences,
        "first_primitive_cubic_directional_derivative": (
            "k3=u4*u13+u0*u13+u0*u4-u3*u14-u1*u14-u1*u3"
        ),
        "first_primitive_cubic_shear_defect": "-L*k3",
        "first_primitive_cubic_relative_filler": "-epsilon*k3",
    }


def relative_tate_audit() -> dict[str, object]:
    # These exact scalar checks freeze the two signs used at the first Tate
    # stage and the centered invariance delta(L)=0.
    z_sum = Q(0)
    delta_L_coefficient = -z_sum
    require(delta_L_coefficient == 0,
            "a centered shear stopped fixing L")
    relation_defect_sign = Q(-1)
    filler_boundary_sign = Q(-1) * Q(1)
    require(relation_defect_sign == filler_boundary_sign,
            "the relative Tate filler sign changed")
    return {
        "base_algebra": "A=k[f_M] subset k[p,s,q] is a toric domain",
        "centered_scalar": "L=z^T*u, sum(z)=0",
        "centered_shear": "delta_0(u_M)=-L",
        "delta_0_of_L": 0,
        "relative_cell": "degree(epsilon)=1, d(epsilon)=L",
        "relation_formula": (
            "delta_0(r)=-L*partial_1(r), partial_1=sum_i partial_i"
        ),
        "degree_one_Tate_formula": (
            "d(e_r)=r; delta(e_r)=-epsilon*partial_1(r)"
        ),
        "commutator_on_relations": "[d,delta](e_r)=0",
        "regularity": "L nonzero in the domain A, hence A-regular",
        "positive_homology_after_relative_Koszul": 0,
        "recursive_step": (
            "at a Tate generator x of degree >=2, delta(d x) is a "
            "positive-degree cycle and therefore has a filler"
        ),
        "all_higher_tate_obstructions": "recursively fillable, noncanonically",
        "extension_is_quasi_isomorphic_to_original_A": False,
        "extension_resolves": "A/(L)",
        "strict_physical_shear_lift": False,
        "base_change_to_k_beta": {
            "A_beta": "A tensor k[beta] is a domain",
            "L_regular": True,
            "positive_homology": 0,
            "beta_torsion_or_new_Bockstein": False,
        },
        "grading_scope": (
            "a homogeneous Tate model gives homogeneous fillers in the "
            "occurrence word/fine/repeated grading"
        ),
        "augmented_physical_readouts_constructed": False,
    }


def finiteness_audit(quadratic, cubic) -> dict[str, object]:
    require(quadratic["minimal_independent_quadratic_relations"]
            > quadratic["toric_ideal_height"],
            "the non-complete-intersection witness disappeared")
    require(cubic["new_minimal_cubic_generators"] > 0,
            "the quadratic-only completion unexpectedly closed")
    return {
        "finite_quadratic_Koszul_totalization": False,
        "first_failure_beyond_quadrics": (
            "5160 primitive cubic binomials in I3/(S1*I2)"
        ),
        "first_quadratic_syzygy_packet": (
            "350 linear syzygies among the 225 quadratic generators"
        ),
        "standard_minimal_commutative_tate_closure_finite": False,
        "reason": (
            "a finite minimal acyclic closure over a regular polynomial "
            "ring would force complete-intersection; mu(I)>=225>70"
        ),
        "finite_free_module_resolution_exists": True,
        "finite_free_module_resolution_is_multiplicative_cofibrant_model": False,
        "finite_truncation_at_each_fixed_homological_degree": True,
        "universal_all_coherence_construction": "infinite filtered completion",
    }


def audit() -> tuple[dict[str, object], str]:
    pin_dependencies()
    occurrences, variables, exponents = occurrence_data()
    quadratic, replacements = degree_two_audit(exponents)
    cubic = degree_three_audit(occurrences, exponents, replacements)
    relative = relative_tate_audit()
    finiteness = finiteness_audit(quadratic, cubic)
    ledger = {
        "theorem": "centered occurrence shear / relative Tate completion gate",
        "scope": "canonical h=3 over characteristic zero and k[beta]",
        "pins": PINS,
        "occurrence_presentation": {
            "occurrences": len(occurrences),
            "physical_variables": len(variables),
            "monomial_degree": 4,
        },
        "degree_two_toric_census": quadratic,
        "degree_three_toric_census": cubic,
        "relative_tate_extension": relative,
        "finiteness": finiteness,
        "conclusion": {
            "positive_formal_result": (
                "after adjoining d epsilon=L, the shear extends over the "
                "full filtered Tate resolution by acyclicity"
            ),
            "first_beyond_quadrics": (
                "5160 cubic relation generators; the first is "
                "u0*u4*u13-u1*u3*u14"
            ),
            "new_higher_obstruction_after_relative_epsilon": False,
            "finite_physical_source_theorem": False,
            "remaining_physical_datum": (
                "a finite source-labelled augmented realization of epsilon "
                "and the required finite coherence truncation"
            ),
        },
    }
    payload = json.dumps(ledger, sort_keys=True, separators=(",", ":"))
    return ledger, sha256(payload.encode()).hexdigest()


def main() -> None:
    ledger, digest = audit()
    require(EXPECTED_LEDGER_SHA256 != "TO_BE_FROZEN",
            ("freeze EXPECTED_LEDGER_SHA256", digest))
    require(digest == EXPECTED_LEDGER_SHA256,
            ("ledger changed", digest, EXPECTED_LEDGER_SHA256))
    print(json.dumps(ledger, indent=2, sort_keys=True))
    print(f"ledger sha256: {digest}")
    print("relative Tate lift: EXISTS recursively after d(epsilon)=L")
    print("strict physical lift: NO; relative extension resolves A/(L)")
    print("toric presentation: height 70, 225 quadrics, 5160 new cubics")
    print("universal commutative completion: infinite (non-CI)")


if __name__ == "__main__":
    main()
