#!/usr/bin/env python3
"""Exact degree-four filtered lift of the n=8 pure product.

In the balanced 24-port Macaulay component of the full 252-variable ring,
this checker solves the invariant incidence equations through fourth
off-support filtration degree and proves

    H_0 H_1 H_2 = sum Q_w H_w  (mod J^5),

where every H_w on the right is mixed and J is generated by coordinates
outside the twelve-coordinate boundary support.  This is a truncated
certificate, not full ideal membership.
"""

from collections import Counter
from fractions import Fraction
from hashlib import sha256
from itertools import product
import importlib.util
import json
from math import lcm
from pathlib import Path


def require(condition, detail):
    if not condition:
        raise RuntimeError(detail)


HERE = Path(__file__).resolve().parent
SOURCE_CHECKER = HERE / "verify_n8_full_source_cycle_product_membership.py"
SPEC = importlib.util.spec_from_file_location("n8_full_source", SOURCE_CHECKER)
SOURCE = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(SOURCE)

QQ = Fraction
MAXIMUM_DEGREE = 4
EXPECTED_LEDGER_SHA256 = (
    "8c6c233ee270ef9a37b9ad76fbfbcfdaa5f06a9c4ec1f863c8fcfd66f94a5a8c"
)


def pure_target_rows(maximum_degree):
    """All canonical rows of H_0 H_1 H_2 through the requested degree."""
    terms_by_colour_degree = []
    for colour in SOURCE.COLOURS:
        groups = {}
        for term in SOURCE.word_terms((colour,) * 8):
            degree = SOURCE.row_off_support_degree(term)
            groups.setdefault(degree, []).append(term)
        terms_by_colour_degree.append(groups)

    actual_rows = set()
    canonical_rows = set()
    for degrees in product(range(maximum_degree + 1), repeat=3):
        if sum(degrees) > maximum_degree:
            continue
        groups = [
            terms_by_colour_degree[colour].get(degree, ())
            for colour, degree in enumerate(degrees)
        ]
        for terms in product(*groups):
            row = tuple(sorted(sum(terms, ())))
            require(row not in actual_rows,
                    "pure-product monomial acquired multiplicity")
            actual_rows.add(row)
            canonical_rows.add(SOURCE.canonical_row(row))
    return actual_rows, canonical_rows


def exact_solve(rows, columns, target_rows):
    """Solve the invariant integer incidence system over Q."""
    row_index = {row: index for index, row in enumerate(rows)}
    equations = [dict() for _row in rows]
    matrix_nonzeros = 0
    for column_index, column in enumerate(columns):
        entries = SOURCE.invariant_column_entries(
            column, row_index, MAXIMUM_DEGREE
        )
        matrix_nonzeros += len(entries)
        for index, coefficient in entries.items():
            equations[index][column_index] = QQ(coefficient)

    # Sparse rows first keeps the exact echelon basis tiny and deterministic.
    ordered_equations = sorted([
        (
            equations[index],
            QQ(1 if row in target_rows else 0),
            index,
        )
        for index, row in enumerate(rows)
    ], key=lambda item: (len(item[0]), item[2]))
    pivots = {}
    for incoming, incoming_rhs, _original_index in ordered_equations:
        coefficients = dict(incoming)
        rhs = incoming_rhs
        while coefficients:
            pivot = min(coefficients)
            value = coefficients[pivot]
            if pivot not in pivots:
                coefficients = {
                    index: coefficient / value
                    for index, coefficient in coefficients.items()
                }
                rhs /= value
                pivots[pivot] = (coefficients, rhs)
                break
            pivot_row, pivot_rhs = pivots[pivot]
            for index, coefficient in pivot_row.items():
                new_value = (
                    coefficients.get(index, QQ(0)) - value * coefficient
                )
                if new_value:
                    coefficients[index] = new_value
                else:
                    coefficients.pop(index, None)
            rhs -= value * pivot_rhs
        else:
            require(not rhs, "pure-product truncated system is inconsistent")

    solution = {}
    for pivot in sorted(pivots, reverse=True):
        pivot_row, rhs = pivots[pivot]
        value = rhs - sum(
            coefficient * solution.get(index, QQ(0))
            for index, coefficient in pivot_row.items()
            if index != pivot
        )
        if value:
            solution[pivot] = value

    # Exact replay against every row, including the three dependent rows.
    image = [QQ(0)] * len(rows)
    for column_index, scalar in solution.items():
        entries = SOURCE.invariant_column_entries(
            columns[column_index], row_index, MAXIMUM_DEGREE
        )
        for index, coefficient in entries.items():
            image[index] += scalar * coefficient
    require(all(
        image[index] == (1 if row in target_rows else 0)
        for index, row in enumerate(rows)
    ), "exact truncated pure-product solution replay failed")
    return solution, len(pivots), matrix_nonzeros


def secondary_component(start_rows):
    """Filtered incidence closure of target rows outside the main component."""
    rows = set(start_rows)
    frontier = set(start_rows)
    columns = set()
    layers = []
    while frontier:
        new_rows = set()
        new_columns = 0
        for row in frontier:
            for raw_column in SOURCE.incident_columns(row):
                column = SOURCE.canonical_column(raw_column)
                if column in columns:
                    continue
                if SOURCE.column_minimum_degree(column) > MAXIMUM_DEGREE:
                    continue
                columns.add(column)
                new_columns += 1
                for output in SOURCE.column_rows(column):
                    if SOURCE.row_off_support_degree(output) <= MAXIMUM_DEGREE:
                        representative = SOURCE.canonical_row(output)
                        if representative not in rows:
                            new_rows.add(representative)
        layers.append((len(new_rows), new_columns))
        rows.update(new_rows)
        frontier = new_rows
    return (
        tuple(sorted(rows)),
        tuple(sorted(columns, key=repr)),
        tuple(layers),
    )


def first_tail(component_solutions):
    """Degree-five residue of the chosen exact truncated correction."""
    target_actual, target_canonical = pure_target_rows(MAXIMUM_DEGREE + 1)
    degree_five_target = {
        row for row in target_canonical
        if SOURCE.row_off_support_degree(row) == MAXIMUM_DEGREE + 1
    }
    target_actual_five = sum(
        SOURCE.row_off_support_degree(row) == MAXIMUM_DEGREE + 1
        for row in target_actual
    )

    residual = Counter({row: QQ(-1) for row in degree_five_target})
    correction_actual_columns = 0
    correction_degree_five_terms = 0
    for columns, solution in component_solutions:
        for column_index, scalar in solution.items():
            column = columns[column_index]
            orbit = SOURCE.column_orbit(column)
            correction_actual_columns += len(orbit)
            for actual_column in orbit:
                for output in SOURCE.column_rows(actual_column):
                    if SOURCE.row_off_support_degree(
                            output) != MAXIMUM_DEGREE + 1:
                        continue
                    correction_degree_five_terms += 1
                    if output == SOURCE.canonical_row(output):
                        residual[output] += scalar
    residual = {row: value for row, value in residual.items() if value}
    return {
        "target_actual_rows": target_actual_five,
        "target_row_orbits": len(degree_five_target),
        "correction_actual_columns": correction_actual_columns,
        "correction_degree_five_terms": correction_degree_five_terms,
        "residual_row_orbits": len(residual),
        "residual_coefficient_set": [
            [value.numerator, value.denominator]
            for value in sorted(set(residual.values()))
        ],
    }


def audit():
    require(SOURCE.audit_support_stabilizer() == 4,
            "support stabilizer order changed")
    main_rows, main_columns, main_layers = (
        SOURCE.truncated_orbit_component(MAXIMUM_DEGREE)
    )
    actual_target, canonical_target = pure_target_rows(MAXIMUM_DEGREE)
    main_target = canonical_target & set(main_rows)
    missing_target = canonical_target - set(main_rows)
    secondary_rows, secondary_columns, secondary_layers = (
        secondary_component(missing_target)
    )
    secondary_target = canonical_target & set(secondary_rows)
    require(not (set(main_rows) & set(secondary_rows)),
            "filtered incidence components unexpectedly overlap")
    require(main_target | secondary_target == canonical_target,
            "a low-degree pure-product orbit escaped both components")
    require(len(actual_target) == 745, "low-degree actual target support changed")
    require(len(canonical_target) == 226,
            "low-degree target orbit support changed")
    require(len(main_target) == 204 and len(secondary_target) == 22,
            "target component split changed")

    main_solution, main_rank, main_nonzeros = exact_solve(
        main_rows, main_columns, main_target
    )
    secondary_solution, secondary_rank, secondary_nonzeros = exact_solve(
        secondary_rows, secondary_columns, secondary_target
    )
    values = sorted(set(main_solution.values()) | set(secondary_solution.values()))
    denominator_lcm = lcm(*(value.denominator for value in values))
    degree_histogram = Counter(
        SOURCE.row_off_support_degree(row) for row in canonical_target
    )
    tail = first_tail((
        (main_columns, main_solution),
        (secondary_columns, secondary_solution),
    ))
    return {
        "vertices": 8,
        "endpoint_colours": 3,
        "ambient_pair_variables": 252,
        "balanced_ordinary_degree": 12,
        "maximum_solved_off_support_degree": MAXIMUM_DEGREE,
        "modulus_statement": "equality modulo the fifth power of the off-support ideal",
        "components": [
            {
                "name": "boundary-connected",
                "layers": [list(layer) for layer in main_layers],
                "row_orbits": len(main_rows),
                "column_orbits": len(main_columns),
                "matrix_nonzeros": main_nonzeros,
                "rank": main_rank,
                "left_nullity": len(main_rows) - main_rank,
                "target_row_orbits": len(main_target),
                "solution_orbit_columns": len(main_solution),
            },
            {
                "name": "degree-four-secondary",
                "layers": [list(layer) for layer in secondary_layers],
                "row_orbits": len(secondary_rows),
                "column_orbits": len(secondary_columns),
                "matrix_nonzeros": secondary_nonzeros,
                "rank": secondary_rank,
                "left_nullity": len(secondary_rows) - secondary_rank,
                "target_row_orbits": len(secondary_target),
                "solution_orbit_columns": len(secondary_solution),
            },
        ],
        "row_orbits": len(main_rows) + len(secondary_rows),
        "column_orbits": len(main_columns) + len(secondary_columns),
        "matrix_nonzeros": main_nonzeros + secondary_nonzeros,
        "rank": main_rank + secondary_rank,
        "left_nullity": (
            len(main_rows) + len(secondary_rows) - main_rank - secondary_rank
        ),
        "target_actual_rows": len(actual_target),
        "target_row_orbits": len(canonical_target),
        "target_orbits_by_degree": dict(sorted(degree_histogram.items())),
        "solution_orbit_columns": (
            len(main_solution) + len(secondary_solution)
        ),
        "solution_coefficient_set": [
            [value.numerator, value.denominator] for value in values
        ],
        "solution_denominator_lcm": denominator_lcm,
        "degree_five_tail": tail,
        "identity": "H_0 H_1 H_2 = sum Q_w H_w mod J^5",
        "scope_guard": "truncated consistency is not full ideal membership",
    }


def main():
    ledger = audit()
    encoded = json.dumps(ledger, sort_keys=True, separators=(",", ":"))
    digest = sha256(encoded.encode()).hexdigest()
    if EXPECTED_LEDGER_SHA256 != "TO_BE_FILLED":
        require(digest == EXPECTED_LEDGER_SHA256,
                "frozen degree-four pure-product lift ledger changed")
    print(
        "n=8 full-source pure-product degree-four lift: PASS; "
        f"component={ledger['row_orbits']}x{ledger['column_orbits']}, "
        f"rank={ledger['rank']}, "
        f"solution={ledger['solution_orbit_columns']}, "
        f"tail5={ledger['degree_five_tail']['residual_row_orbits']}"
    )
    print(f"sha256: {digest}")


if __name__ == "__main__":
    main()
