#!/usr/bin/env python3
"""Exact h=3 audit for the derived-base-change cap obstruction.

This checker covers only the split two-term universal target/residue cap block and the
smallest hypothetical invisible-lift extension from
``notes/derived-base-change-relative-cap-obstruction.md``.  It is a bounded
module audit, not the full all-label EqSystem and not a proof of the invisible
cross-word lift lemma.  In particular it does not rule out the
``Tor_1(coker(b), S)`` kernel-enlargement mechanism in the full source
complex.
"""

from fractions import Fraction as F
from hashlib import sha256
import json


ZERO = F(0)
ONE = F(1)


def require(condition, message):
    if not condition:
        raise RuntimeError(message)


def rank(matrix):
    rows = [list(map(F, row)) for row in matrix]
    if not rows:
        return 0
    width = len(rows[0])
    pivot_row = 0
    for column in range(width):
        pivot = next(
            (row for row in range(pivot_row, len(rows))
             if rows[row][column]),
            None,
        )
        if pivot is None:
            continue
        rows[pivot_row], rows[pivot] = rows[pivot], rows[pivot_row]
        value = rows[pivot_row][column]
        rows[pivot_row] = [entry / value for entry in rows[pivot_row]]
        for row in range(len(rows)):
            if row == pivot_row or not rows[row][column]:
                continue
            value = rows[row][column]
            rows[row] = [
                entry - value * pivot_entry
                for entry, pivot_entry in zip(rows[row], rows[pivot_row])
            ]
        pivot_row += 1
        if pivot_row == len(rows):
            break
    return pivot_row


def dot(row, column):
    require(len(row) == len(column), "dot-product dimensions disagree")
    return sum((a * b for a, b in zip(row, column)), ZERO)


def audit_packet(A, B, Fq, U, Y):
    A, B, Fq, U, Y = map(F, (A, B, Fq, U, Y))
    kappa = A * U - B * Fq
    require(kappa != 0 and Y != 0, "the active localization failed")

    # Universal cap block d(T,rho)=(-Y*T+rho)w.  The graph vector and the
    # contractible lift rho give a unimodular basis change with determinant 1.
    cap_d = [-Y, ONE]
    graph = [ONE, Y]
    rho = [ZERO, ONE]
    basis_change = [[ONE, ZERO], [Y, ONE]]
    require(dot(cap_d, graph) == ZERO, "cap graph is not a cycle")
    require(dot(cap_d, rho) == ONE, "rho does not split the cap row")
    require(
        basis_change[0][0] * basis_change[1][1]
        - basis_change[0][1] * basis_change[1][0] == ONE,
        "the graph/contractible basis is not unimodular",
    )
    require(rank([cap_d]) == 1, "the universal cap differential lost rank")

    # The desired relative vector has the right response but its connecting
    # value is the nonzero obstruction -kappa*Y*w.
    relative = [ZERO, -kappa * Y]
    connecting = dot(cap_d, relative)
    require(connecting == -kappa * Y, "wrong relative connecting value")
    require(connecting != ZERO, "the active relative obstruction vanished")

    # The actual selected filtered-d2 representative is a graph cycle.
    filtered_d2 = [-kappa, -kappa * Y]
    require(dot(cap_d, filtered_d2) == ZERO,
            "the filtered d2 graph is not a cap cycle")
    require(filtered_d2 == [-kappa * entry for entry in graph],
            "the filtered d2 representative left the graph line")

    # Diagnostic extension: n is invisible and d(n)=kappa*Y*w.  Its
    # difference with kappa*Y*rho is the unique target-zero kernel line.
    extended_d = [-Y, ONE, kappa * Y]
    invisible_cycle = [ZERO, -kappa * Y, ONE]
    extended_graph = [ONE, Y, ZERO]
    require(dot(extended_d, invisible_cycle) == ZERO,
            "the invisible-lift cycle is not closed")
    require(dot(extended_d, extended_graph) == ZERO,
            "the graph stopped being a cycle after extension")
    require(rank([extended_d]) == 1,
            "the invisible-lift differential has the wrong rank")

    # Kernel dimension is two.  Imposing target coordinate zero leaves one
    # dimension, generated by the desired invisible-lift cycle.
    augmented_constraints = [extended_d, [ONE, ZERO, ZERO]]
    require(3 - rank([extended_d]) == 2,
            "extended kernel dimension changed")
    require(3 - rank(augmented_constraints) == 1,
            "target-zero kernel is not one-dimensional")
    require(invisible_cycle[0] == ZERO,
            "invisible-lift cycle acquired a target")
    require(invisible_cycle[1] == -kappa * Y,
            "invisible-lift cycle has the wrong response")

    return {
        "A": str(A),
        "B": str(B),
        "F": str(Fq),
        "U": str(U),
        "Y": str(Y),
        "kappa": str(kappa),
        "direct_free": B == ZERO,
        "cap_rank": rank([cap_d]),
        "relative_connecting": str(connecting),
        "extended_kernel_dimension": 3 - rank([extended_d]),
        "target_zero_kernel_dimension": 3 - rank(augmented_constraints),
        "target_zero_response": str(invisible_cycle[1]),
    }


EXPECTED_DIGEST = "581041fd9b13ea5db29207404d67698472638e14970c18e5a3e573ff23b629d1"


def main():
    samples = (
        (F(2), F(3), F(5), F(11), F(7, 5)),
        (F(3), F(0), F(2), F(5), F(-4, 9)),  # direct-free boundary
        (F(-2), F(7), F(3), F(-5), F(13, 6)),
        (F(5, 3), F(-7, 4), F(11, 5), F(2, 9), F(-8, 7)),
    )
    records = [audit_packet(*sample) for sample in samples]
    payload = json.dumps(records, sort_keys=True, separators=(",", ":"))
    digest = sha256(payload.encode("utf-8")).hexdigest()
    require(digest == EXPECTED_DIGEST, "derived cap packet digest changed")
    print("derived-base-change relative cap obstruction: PASS")
    print("exact rational packets:", len(records))
    print("direct-free packets:", sum(r["direct_free"] for r in records))
    print("split cap block: base change creates no positive Tor source")
    print("full-source non-flat kernel enlargement: outside this checker")
    print("relative Yoneda class: nonzero obstruction -kappa*Y*w")
    print("hypothetical invisible lift: unique target-zero response line")
    print("sha256:", digest)


if __name__ == "__main__":
    main()
