#!/usr/bin/env python3
"""Audit the endpoint-parity fork for the two h=3 lower c_2 faces.

An order-two occurrence on four sites is an ordered endpoint pair; the
remaining edge is forced.  Endpoint reversal splits the marked centered
class c_f=12e_f-1 into

    c_f^- = 6(e_f-e_Sf),
    c_f^+ = 6(e_f+e_Sf)-1.

Nonzero c_f^- has a nonzero oriented endpoint coordinate, but its landing in
the physical active-clean quotient still needs the missing typed comparison.
If c_f^- is dark, c_f^+ is not killed by the complete H0 line: the even
augmentation-zero quotient has dimension five and an explicit primitive
symmetric dual reads 12.  Coefficientwise it is nevertheless generated by
the
endpoint-difference operator.  For the degree-four endpoint adjacency B,

    Pi_even=B(B+2I)/24,
    c_f^+=-(B+6I)(B-4I)c_f^+/24.

Thus an occurrence-local physical lift of B-4I closes the even branch; the
existing complete-row bars do not construct that lift.
"""

from __future__ import annotations

from fractions import Fraction
from hashlib import sha256
import importlib.util
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
PINS = {
    "notes/uniform-centered-occurrence-restriction-insertion-gate.md":
        "c3161b740606a19d1fb238921986a6ab3b9c2f9cec9d7bc9a9410059f8c213da",
    "computations/verify_uniform_centered_occurrence_restriction_insertion_gate.py":
        "cb328adc1f23b38f6f9f9305635ddbaef888178633f8db91c205fdfbdca1ff34",
    "notes/scalar-unit-c0-four-cut-common-carrier-gate.md":
        "a06018da73d6a954f14706fcfdeaae5ace1c2424e02530ab87602c1e77271000",
    "computations/verify_scalar_unit_c0_four_cut_common_carrier_gate.py":
        "56421c894acd613300841b7ae41d1bafecc6d65fcc9618982dc61ac198c2fa66",
    "notes/uniform-centered-occurrence-endpoint-association-projector.md":
        "6be3edc16be3b429f517fe007886fd3289281f8e8acdde1f13ebebf2a20bb836",
    "computations/verify_uniform_centered_occurrence_endpoint_association_projector.py":
        "0ef88312cead100120e4600ea3a2d0616262a96bf27726d07817610d11b43f59",
    "notes/uniform-physical-bar-occurrence-splitter-cokernel.md":
        "5aecb6fecbb3dffc720efaeb412d366a4c4c7b4475f61535280cc0df4c2b3007",
    "computations/verify_uniform_physical_bar_occurrence_splitter_cokernel.py":
        "403819751753802f4bb01b07cca2540fc6abf0479b9be5569ee74f414ea667ad",
    "notes/h3-gamma1-affine-raw-occurrence-cut-gate.md":
        "01095345226fc4e580bd0007c55d936f37d74e596f28eaaaf719e6a52caaa3d8",
    "computations/verify_h3_gamma1_affine_raw_occurrence_cut_gate.py":
        "34f39ba15de4e4fb0673b883d29ea86c92c1a359b6a3361ad61c17fc2368db1c",
}
EXPECTED_LEDGER_SHA256 = (
    "fbd28a813ee0590fdb8bfb7948f74f63270fa200ae75bf6e26f6a5c8f3b963b1"
)


def require(condition: bool, detail: object) -> None:
    if not condition:
        raise RuntimeError(detail)


def pin_dependencies() -> None:
    for relative, expected in PINS.items():
        actual = sha256((ROOT / relative).read_bytes()).hexdigest()
        require(actual == expected,
                ("pinned dependency changed", relative, actual, expected))


def load_occurrence_module():
    relative = (
        "computations/"
        "verify_uniform_centered_occurrence_restriction_insertion_gate.py"
    )
    specification = importlib.util.spec_from_file_location(
        "h2_lower_occurrence", ROOT / relative
    )
    require(specification is not None and specification.loader is not None,
            "cannot load occurrence module")
    module = importlib.util.module_from_spec(specification)
    specification.loader.exec_module(module)
    return module


def add(*vectors):
    require(vectors and len({len(vector) for vector in vectors}) == 1,
            "add width")
    return tuple(sum(entries, Fraction(0))
                 for entries in zip(*vectors, strict=True))


def scale(coefficient, vector):
    return tuple(Fraction(coefficient) * entry for entry in vector)


def dot(left, right) -> Fraction:
    require(len(left) == len(right), "dot width")
    return sum((a * b for a, b in zip(left, right, strict=True)), Fraction(0))


def rank(columns) -> int:
    if not columns:
        return 0
    height = len(columns[0])
    require(all(len(column) == height for column in columns), "rank height")
    rows = [list(entries) for entries in zip(*columns, strict=True)]
    answer = 0
    for column in range(len(columns)):
        pivot = next(
            (row for row in range(answer, height) if rows[row][column]), None
        )
        if pivot is None:
            continue
        rows[answer], rows[pivot] = rows[pivot], rows[answer]
        value = rows[answer][column]
        rows[answer] = [entry / value for entry in rows[answer]]
        for row in range(height):
            if row == answer or not rows[row][column]:
                continue
            value = rows[row][column]
            rows[row] = [
                entry - value * pivot_entry
                for entry, pivot_entry in zip(
                    rows[row], rows[answer], strict=True
                )
            ]
        answer += 1
    return answer


def matvec(matrix, vector):
    return tuple(dot(row, vector) for row in matrix)


def matmul(left, right):
    columns = tuple(zip(*right, strict=True))
    return tuple(tuple(dot(row, column) for column in columns) for row in left)


def identity(size):
    return tuple(tuple(Fraction(int(row == column)) for column in range(size))
                 for row in range(size))


def matrix_add(*matrices):
    return tuple(tuple(sum(entries, Fraction(0))
                       for entries in zip(*rows, strict=True))
                 for rows in zip(*matrices, strict=True))


def matrix_scale(coefficient, matrix):
    return tuple(tuple(Fraction(coefficient) * entry for entry in row)
                 for row in matrix)


def endpoint_data():
    occurrence = load_occurrence_module()
    vertices = (0, 1, 2, 3)
    values = occurrence.occurrences(vertices)
    require(len(values) == 12, "order-two occurrence count changed")
    lookup = {value: index for index, value in enumerate(values)}

    def swap(value):
        p_site, s_site, matching = value
        return (s_site, p_site, matching)

    def endpoint_neighbors(value):
        p_site, s_site, matching = value
        require(len(matching) == 1, "order-two residual edge changed")
        residual = matching[0]
        answer = []
        for selected in residual:
            mate = residual[0] if residual[1] == selected else residual[1]
            answer.append((
                selected,
                s_site,
                (occurrence.edge(p_site, mate),),
            ))
            answer.append((
                p_site,
                selected,
                (occurrence.edge(s_site, mate),),
            ))
        require(len(answer) == len(set(answer)) == 4,
                ("endpoint neighbor degree changed", value, answer))
        return tuple(answer)

    size = len(values)
    b_matrix = [[Fraction(0) for _ in range(size)] for _ in range(size)]
    s_matrix = [[Fraction(0) for _ in range(size)] for _ in range(size)]
    for column, value in enumerate(values):
        for neighbor in endpoint_neighbors(value):
            b_matrix[lookup[neighbor]][column] += 1
        s_matrix[lookup[swap(value)]][column] = 1
    return occurrence, values, lookup, swap, tuple(map(tuple, b_matrix)), tuple(map(tuple, s_matrix))


def parity_and_active_fork_audit() -> dict[str, object]:
    occurrence, values, lookup, swap, b_matrix, s_matrix = endpoint_data()
    size = len(values)
    one = tuple(Fraction(1) for _ in values)
    marked = (0, 1, (occurrence.edge(2, 3),))
    swapped = swap(marked)
    require(marked in lookup and swapped in lookup, "marked pair disappeared")
    c = tuple(Fraction(12 if value == marked else 0) - 1
              for value in values)
    sc = matvec(s_matrix, c)
    even = scale(Fraction(1, 2), add(c, sc))
    odd = scale(Fraction(1, 2), add(c, scale(-1, sc)))
    expected_even = tuple(
        Fraction(6 if value in (marked, swapped) else 0) - 1
        for value in values
    )
    expected_odd = tuple(
        Fraction(6 if value == marked else -6 if value == swapped else 0)
        for value in values
    )
    require(even == expected_even and odd == expected_odd
            and add(even, odd) == c,
            "endpoint parity split changed")
    require(matvec(s_matrix, even) == even
            and matvec(s_matrix, odd) == scale(-1, odd),
            "endpoint parity eigenvalues changed")
    require(sum(even, Fraction(0)) == sum(odd, Fraction(0)) == 0,
            "centered parity acquired augmentation")

    even_basis = []
    odd_basis = []
    for left in range(4):
        for right in range(left + 1, 4):
            forward = (left, right, (occurrence.edge(*(
                tuple(site for site in range(4) if site not in (left, right))
            )),))
            reverse = swap(forward)
            pair_sum = [Fraction(0) for _ in values]
            pair_difference = [Fraction(0) for _ in values]
            pair_sum[lookup[forward]] = pair_sum[lookup[reverse]] = 1
            pair_difference[lookup[forward]] = 1
            pair_difference[lookup[reverse]] = -1
            even_basis.append(tuple(pair_sum))
            odd_basis.append(tuple(pair_difference))
    require(rank(even_basis) == rank(odd_basis) == 6
            and rank(even_basis + odd_basis) == 12,
            "endpoint parity dimensions changed")

    # This primitive symmetric hole difference kills every endpoint-odd
    # class and the common H0 line, but detects the selected even class.
    comparison = next(
        value for value in values
        if value not in (marked, swapped) and value[0] < value[1]
    )
    comparison_swapped = swap(comparison)
    even_dual = tuple(
        Fraction(1 if value in (marked, swapped) else
                 -1 if value in (comparison, comparison_swapped) else 0)
        for value in values
    )
    require(dot(even_dual, one) == 0
            and all(dot(even_dual, column) == 0 for column in odd_basis)
            and dot(even_dual, even) == 12,
            "even centered separator changed")
    require(rank([one]) == 1 and rank([one, even]) == 2,
            "common H0 line acquired selected even class")

    # At coefficient level odd!=0 means at least one of the two oriented
    # coordinates is nonzero.  The physical landing remains conditional.
    oriented_coordinates = (
        odd[lookup[marked]], odd[lookup[swapped]]
    )
    require(oriented_coordinates == (Fraction(6), Fraction(-6)),
            "oriented odd coordinates changed")
    return {
        "order_two_occurrences": size,
        "marked": repr(marked),
        "endpoint_swap": repr(swapped),
        "c_minus": "6*(e_f-e_Sf)",
        "c_plus": "6*(e_f+e_Sf)-1",
        "odd_dimension": rank(odd_basis),
        "even_dimension": rank(even_basis),
        "even_augmentation_zero_dimension": rank(even_basis) - 1,
        "selected_odd_oriented_coordinates": [
            str(entry) for entry in oriented_coordinates
        ],
        "odd_nonzero_implication": (
            "at least one ordered-orientation projection is nonzero; "
            "active-clean landing is conditional on the physical typed map"
        ),
        "odd_dark_residual": "the selected c_plus class",
        "common_H0_contains_c_plus": False,
        "even_dual": (
            "+1 on f,Sf, -1 on one comparison pair and 0 elsewhere"
        ),
        "even_dual_on_H0": str(dot(even_dual, one)),
        "even_dual_on_all_odd": "0",
        "even_dual_on_c_plus": str(dot(even_dual, even)),
    }


def even_endpoint_projector_audit() -> dict[str, object]:
    _occurrence, values, _lookup, _swap, b_matrix, s_matrix = endpoint_data()
    size = len(values)
    i_matrix = identity(size)
    require(matmul(b_matrix, s_matrix) == matmul(s_matrix, b_matrix),
            "endpoint adjacency stopped commuting with swap")
    one = tuple(Fraction(1) for _ in values)
    require(matvec(b_matrix, one) == scale(4, one),
            "endpoint adjacency degree changed")

    even_projector = matrix_scale(
        Fraction(1, 24),
        matmul(b_matrix, matrix_add(b_matrix, matrix_scale(2, i_matrix))),
    )
    require(matvec(even_projector, one) == one,
            "even endpoint projector lost H0")

    # Rebuild the selected even class.
    marked_index = next(index for index, value in enumerate(values)
                        if value[0:2] == (0, 1))
    marked = values[marked_index]
    swapped_index = next(index for index, value in enumerate(values)
                         if value[0:2] == (1, 0))
    swapped = values[swapped_index]
    require(marked[2] == swapped[2], "selected pair residual edge changed")
    c_plus = tuple(
        Fraction(6 if index in (marked_index, swapped_index) else 0) - 1
        for index in range(size)
    )
    require(matvec(even_projector, c_plus) == scale(0, c_plus),
            "even centered class acquired H0 projection")

    b_minus_four = matrix_add(b_matrix, matrix_scale(-4, i_matrix))
    b_plus_six = matrix_add(b_matrix, matrix_scale(6, i_matrix))
    formal_filler = scale(
        Fraction(-1, 24),
        matvec(b_plus_six, matvec(b_minus_four, c_plus)),
    )
    require(formal_filler == c_plus,
            "quadratic endpoint-difference filler identity changed")

    # On the even subspace, B has eigenvalues 4,0,-2.  On the odd
    # subspace it has eigenvalues 2,-2.  Verify the annihilating polynomials
    # directly on parity bases and verify that the selected odd vector has
    # nonzero components in both odd eigenspaces.
    occurrence, values, lookup, swap, _b, _s = endpoint_data()
    even_basis = []
    odd_basis = []
    for left in range(4):
        for right in range(left + 1, 4):
            rest = tuple(site for site in range(4)
                         if site not in (left, right))
            forward = (left, right, (occurrence.edge(*rest),))
            reverse = swap(forward)
            pair_sum = [Fraction(0)] * size
            pair_difference = [Fraction(0)] * size
            pair_sum[lookup[forward]] = pair_sum[lookup[reverse]] = 1
            pair_difference[lookup[forward]] = 1
            pair_difference[lookup[reverse]] = -1
            even_basis.append(tuple(pair_sum))
            odd_basis.append(tuple(pair_difference))

    even_polynomial = matmul(
        matrix_add(b_matrix, matrix_scale(2, i_matrix)),
        matmul(b_matrix, matrix_add(b_matrix, matrix_scale(-4, i_matrix))),
    )
    odd_polynomial = matmul(
        matrix_add(b_matrix, matrix_scale(2, i_matrix)),
        matrix_add(b_matrix, matrix_scale(-2, i_matrix)),
    )
    zero = tuple(Fraction(0) for _ in values)
    require(all(matvec(even_polynomial, vector) == zero
                for vector in even_basis)
            and all(matvec(odd_polynomial, vector) == zero
                    for vector in odd_basis),
            "endpoint parity minimal polynomials changed")

    selected_odd = scale(6, odd_basis[0])
    plus_two = scale(
        Fraction(1, 4),
        matvec(matrix_add(b_matrix, matrix_scale(2, i_matrix)), selected_odd),
    )
    minus_two = scale(
        Fraction(1, 4),
        matvec(matrix_add(matrix_scale(2, i_matrix),
                          matrix_scale(-1, b_matrix)), selected_odd),
    )
    require(add(plus_two, minus_two) == selected_odd
            and plus_two != zero and minus_two != zero,
            "selected odd class stopped meeting both odd endpoint sectors")

    difference_columns = [
        matvec(b_minus_four, vector) for vector in even_basis
    ]
    require(rank(difference_columns) == 5,
            "formal endpoint differences stopped spanning even centered part")
    return {
        "endpoint_adjacency_degree": 4,
        "endpoint_swap_commutes_with_B": True,
        "even_spectrum": [4, 0, -2],
        "odd_spectrum": [2, -2],
        "even_H0_projector": "Pi_even=B(B+2I)/24",
        "Pi_even_on_H0": "identity",
        "Pi_even_on_c_plus": "zero",
        "formal_even_filler": "c_plus=-(B+6I)(B-4I)c_plus/24",
        "formal_B_minus_4_image_rank_on_even_module":
            rank(difference_columns),
        "selected_odd_is_one_B_eigenline": False,
        "selected_odd_meets_both_B_eigenvalues": [2, -2],
        "physical_requirement": (
            "an occurrence-local source bar/Cartan-Hasse lift of B-4I, "
            "with its quadratic product-rule face and augmentation"
        ),
    }


def lower_word_and_physical_scope_audit() -> dict[str, object]:
    full_word = tuple(map(int, "01211222"))
    selected_occurrence_sites = set(range(6))
    records = []
    for selected in ((2, 3), (4, 5)):
        lower_sites = tuple(sorted(selected_occurrence_sites - set(selected)))
        lower_word = "".join(str(full_word[site]) for site in lower_sites)
        reinsertion = "".join(str(full_word[site]) for site in selected)
        records.append({
            "deleted_edge": "".join(map(str, selected)),
            "lower_sites": list(lower_sites),
            "lower_word": lower_word,
            "reinsertion_q_colour": reinsertion,
            "endpoint_colour_pair_before_swap": [full_word[0], full_word[1]],
            "endpoint_colour_pair_after_role_swap": [full_word[1], full_word[0]],
        })
    require([record["lower_word"] for record in records] == ["0112", "0121"]
            and [record["reinsertion_q_colour"] for record in records]
            == ["21", "12"],
            "literal lower words or reinsertion labels changed")

    c_zero = (ROOT / "notes/scalar-unit-c0-four-cut-common-carrier-gate.md").read_text()
    endpoint = (ROOT / (
        "notes/uniform-centered-occurrence-endpoint-association-projector.md"
    )).read_text()
    splitter = (ROOT / (
        "notes/uniform-physical-bar-occurrence-splitter-cokernel.md"
    )).read_text()
    gamma = (ROOT / "notes/h3-gamma1-affine-raw-occurrence-cut-gate.md").read_text()
    require("The identification in the second sentence is essential" in c_zero
            and "not yet an active clean-line class" in c_zero,
            "active-clean physical typing guard changed")
    require("remaining obstruction is entirely physical" in endpoint
            and "product-rule faces" in endpoint,
            "endpoint projector physical scope changed")
    require("localized at `x`" in splitter
            and "constructed from complete source rows" in splitter,
            "occurrence-local physical bar scope changed")
    require("asserted to be physical terminal readouts" in gamma,
            "lower occurrence dual terminal guard changed")
    return {
        "marked_lower_cuts": records,
        "top_reinsertion_grade": "01211222 / labelled repeated P3+K2",
        "coefficient_swap_scope": (
            "reverses p/s endpoint roles and preserves the four-site word, "
            "but exchanges the ordered endpoint-colour decoration"
        ),
        "physical_swap_scope": (
            "no pinned theorem realizes this coefficient S as one fixed-"
            "fine-grade source chain map on both lower cuts"
        ),
        "active_clean_scope": (
            "odd nonzero reaches the existing alternative only after its "
            "ordered projection is identified in the physical relative quotient"
        ),
        "even_scope": (
            "complete H0 supplies only the constant projector; the needed "
            "B-4 occurrence-local source bar and quadratic Hasse face remain open"
        ),
        "terminal_scope": (
            "the symmetric even covector is presentation-level until it "
            "extends across all protected and physical-q source columns"
        ),
    }


def audit() -> tuple[dict[str, object], str]:
    pin_dependencies()
    ledger = {
        "theorem": "h2 lower-centered endpoint-parity terminal fork",
        "pins": PINS,
        "parity_and_active_fork": parity_and_active_fork_audit(),
        "even_endpoint_projector": even_endpoint_projector_audit(),
        "physical_scope": lower_word_and_physical_scope_audit(),
        "verdict": (
            "The lower order-two centered class splits exactly as "
            "c_minus=6(e_f-e_Sf) and c_plus=6(e_f+e_Sf)-1.  A physically "
            "typed nonzero odd projection enters the existing active-clean/"
            "terminal branch, but coefficient oddness alone does not supply "
            "that typing, and the selected odd class meets both odd B sectors. "
            "If the odd class is dark, complete response/common H0 does not "
            "force c_plus: the even centered quotient has dimension five and "
            "a primitive symmetric H0/odd-annihilating dual reads 12.  "
            "Coefficientwise "
            "the remaining branch is sharply soluble: Pi_even=B(B+2)/24 and "
            "c_plus=-(B+6)(B-4)c_plus/24.  Therefore the shortest positive "
            "cell is an occurrence-local physical lift of B-4, with the "
            "quadratic Hasse/product-rule and complete augmented readouts, "
            "in lower words 0112 and 0121 before reinsertion into the common "
            "01211222/P3+K2 grade."
        ),
    }
    digest = sha256(json.dumps(
        ledger, sort_keys=True, separators=(",", ":")
    ).encode()).hexdigest()
    if EXPECTED_LEDGER_SHA256 != "TO_BE_PINNED":
        require(digest == EXPECTED_LEDGER_SHA256,
                ("lower endpoint parity ledger changed", digest))
    return ledger, digest


def main() -> None:
    _ledger, digest = audit()
    print("lower c2 endpoint parity: c-=6(e_f-e_Sf), c+=6(e_f+e_Sf)-1")
    print("odd nonzero -> active-clean: CONDITIONAL ON PHYSICAL PROJECTION")
    print("odd-dark + H0 -> c+=0: FALSE (even residual dimension 5)")
    print("physical B-4 lift -> even closure: EXACT CONDITIONAL REDUCTION")
    print("ledger_sha256=" + digest)


if __name__ == "__main__":
    main()
