#!/usr/bin/env python3
"""Decompose the selected h=3 four-site source frontier.

The rank-126/127 local supermap is projection-complete for every physical
response/target/PP/reinsertion column which stays inside the four-site
operation fan.  Operation-parent typing then leaves only four cross-shore
DQ/PS mate types.  They pair into the two root-labelled A/B and A/C word
sections.

This is an exact exhaustiveness theorem for the primitive cellular grammar:
one operation-parent incidence per primitive source face, followed by
linear totalization.  It is also an exact guard on the still unproved full
decorated source census.  No committed theorem says that every possible
higher source column is generated by that primitive grammar.

The four shore-gauged top mate incidences are signless K2,2 edges, hence
they have chi=delta.(B-Eq)=0.  After the two word sections are formally
granted, the first unclassified physical family is the mixed reduced-Eq
naturality lift.  If its top private incidence is the signless edge u and
its reduced-Eq occurrence vector is e, then exactly

    chi = -delta.e,

because delta.u=0.  The current source inventory does not construct e, so
assigning chi=0 or a nonzero number would be an extra hypothesis.
"""

from __future__ import annotations

from fractions import Fraction as Q
from hashlib import sha256
import importlib.util
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
PINS = {
    "computations/verify_h3_uc4_four_site_response_private_eq_local_terminal_gate.py":
        "6c42cd4dc7dca1544dc0b675f5f4543ec348f1fba34b7ea14bf80cc6a20b9cf1",
    "computations/verify_h3_maximal_pointed_balanced_same_grade_terminal_gate.py":
        "262e1dd08dd1842d60515d45aea53ea406d7e1e5ea55ab506bb6e81d64b07741",
    "computations/verify_h3_gate_ii_primitive_c4_joint_cobar_label_gate.py":
        "d77f4fd853673c434d4a0bb4027bf9ba046f1bb7ea4d752028a609e832255f44",
    "computations/verify_h3_shear_collision_augp2_packaging_map_gate.py":
        "bd3f008eb2faf00bbebccb09ef9692908f2e0ae4a795706de2c32f0b2ef342af",
    "computations/verify_h3_hyperbolic_root_pair_cross_word_eq_ridge_gate.py":
        "0760703ace1498cc9c255dd8a2017395ece9a7750ab6a21c88233518e1314bba",
    "computations/verify_h3_balanced_square_private_eq_projection_gate.py":
        "bbfb690a73844169574351ad019171a6d9c5fe332e59cc9694a1f67dcf31cf8e",
}
EXPECTED_LEDGER_SHA256 = "596c31bc593ac6ce36ab629f4e68b81658e432f66de434ed9913c208aff07440"

CORNERS = (
    "A_[a|b]=DQ[a|b]",
    "A_[b|a]=DQ[b|a]",
    "B=PS[P0,S1]",
    "C=PS[P1,S0]",
)
PROFILES = (
    (1, 0, 0, 1),
    (1, 0, 0, 1),
    (0, 1, 1, 0),
    (0, 1, 1, 0),
)
DELTA = tuple(map(Q, (1, 1, -1, -1)))
DIRECT = (0, 1)
ENDPOINT = (2, 3)
CROSS_EDGES = tuple((left, right)
                    for left in DIRECT for right in ENDPOINT)
SAME_SHORE_EDGES = ((0, 1), (2, 3))


def require(condition: bool, detail: object) -> None:
    if not condition:
        raise RuntimeError(detail)


def load(relative: str, name: str):
    specification = importlib.util.spec_from_file_location(name, ROOT / relative)
    require(specification is not None and specification.loader is not None,
            ("cannot import", relative))
    module = importlib.util.module_from_spec(specification)
    specification.loader.exec_module(module)
    return module


def dot(left, right):
    require(len(left) == len(right), "dot width")
    return sum((Q(a) * Q(b) for a, b in
                zip(left, right, strict=True)), Q(0))


def add(*vectors):
    require(vectors and len({len(vector) for vector in vectors}) == 1,
            "add width")
    return tuple(sum((Q(vector[index]) for vector in vectors), Q(0))
                 for index in range(len(vectors[0])))


def scale(coefficient, vector):
    return tuple(Q(coefficient) * Q(value) for value in vector)


def rank(columns) -> int:
    columns = tuple(columns)
    if not columns:
        return 0
    height = len(columns[0])
    require(all(len(column) == height for column in columns), "rank height")
    rows = [[Q(columns[column][row]) for column in range(len(columns))]
            for row in range(height)]
    answer = 0
    for column in range(len(columns)):
        pivot = next((row for row in range(answer, height)
                      if rows[row][column]), None)
        if pivot is None:
            continue
        rows[answer], rows[pivot] = rows[pivot], rows[answer]
        value = rows[answer][column]
        rows[answer] = [entry / value for entry in rows[answer]]
        for row in range(height):
            if row == answer or not rows[row][column]:
                continue
            value = rows[row][column]
            rows[row] = [left - value * right for left, right in
                         zip(rows[row], rows[answer], strict=True)]
        answer += 1
    return answer


def basis(width: int, *positions: int) -> tuple[Q, ...]:
    return tuple(Q(1 if index in positions else 0)
                 for index in range(width))


def be_vector(*, B=(0, 0, 0, 0), Eq=(0, 0, 0, 0)):
    return tuple(map(Q, B + Eq))


def chi(value) -> Q:
    return dot(DELTA + scale(-1, DELTA), value)


def pin_dependencies() -> None:
    for relative, expected in PINS.items():
        actual = sha256((ROOT / relative).read_bytes()).hexdigest()
        require(actual == expected,
                ("pinned dependency changed", relative, actual, expected))


def dependency_scope_audit(modules):
    local, maximal, joint, packaging, hyperbolic, projection = modules
    local_ledger, local_digest = local.audit()
    maximal_ledger, maximal_digest = maximal.audit()
    joint_ledger, joint_digest = joint.audit()
    packaging_ledger, packaging_digest = packaging.audit()
    hyperbolic_ledger, hyperbolic_digest = hyperbolic.audit()
    projection_ledger, projection_digest = projection.audit()
    require(local_digest == local.EXPECTED_LEDGER_SHA256
            and maximal_digest == maximal.EXPECTED_LEDGER_SHA256
            and joint_digest == joint.EXPECTED_LEDGER_SHA256
            and packaging_digest == packaging.EXPECTED_LEDGER_SHA256
            and hyperbolic_digest == hyperbolic.EXPECTED_LEDGER_SHA256
            and projection_digest == projection.EXPECTED_LEDGER_SHA256,
            "a dependency ledger changed")
    local_map = local_ledger["exhaustive_local_supermap"]
    maximal_map = maximal_ledger["maximal_named_literal_map"]
    word = packaging_ledger["literal_word_and_fine_map"]
    mixed = hyperbolic_ledger["conditional_paired_augmented_test"]
    require(local_map["output_dimension"] == 127
            and local_map["rank"] == 126
            and local_map["cokernel_dimension"] == 1
            and maximal_map["total_named_columns"] == 146
            and joint_ledger["physical_source_label_gate"]
                ["profile_violations"] == 4
            and word["response_word_display"] == "11:110000"
            and word["canonical_cap_word"] == "01211222"
            and word["word_hamming_distance"] == 6
            and mixed["strong_grant_base_rank"] == 4
            and mixed["rank_after_paired_mixed_comparison"] == 5
            and projection_ledger["projection"]["old_projection_rank"] == 7,
            "the decomposition frontier changed")
    scope = {
        "four_site_local_supermap_dimension_rank": [127, 126],
        "maximal_named_union_coordinates_columns_rank": [
            maximal_map["total_coordinates"],
            maximal_map["total_named_columns"],
            maximal_map["total_rank"],
        ],
        "formal_DQ_PS_mates_violating_operation_profile": 4,
        "response_word": word["response_word_display"],
        "cap_word": word["canonical_cap_word"],
        "word_hamming_distance": word["word_hamming_distance"],
        "paired_mixed_Eq_rank_jump": [4, 5],
        "B_Eq_projection_rank_dimension": [7, 8],
    }
    ledgers = {
        "local": local_ledger,
        "maximal": maximal_ledger,
        "joint": joint_ledger,
        "packaging": packaging_ledger,
        "hyperbolic": hyperbolic_ledger,
        "projection": projection_ledger,
    }
    return scope, ledgers


def local_factorization_audit(local) -> dict[str, object]:
    top = local.top_projection_columns()
    lower = local.lower_face_and_reinsertion_columns()
    external = local.external_augmented_columns()
    columns = tuple(value for _name, value in top + lower + external)
    detector = local.integral_terminal_dual()
    require(len(detector) == 127 and rank(columns) == 126
            and all(dot(detector, column) == 0 for column in columns),
            "the exhaustive four-site factorization changed")

    # The old untyped selected db01/dL01 question is decided inside the
    # physical response derivative grammar: product rule applies identical
    # incidence to B and Eq.  The aggregate direction and tail packets are
    # explicit tied controls in the rank-126 supermap.
    direction_tied = add(local.primitive_direction_face("B"),
                         local.primitive_direction_face("Eq"))
    tail_tied = add(local.balanced_tail_face("B"),
                    local.balanced_tail_face("Eq"))
    require(dot(detector, direction_tied) == 0
            and dot(detector, tail_tied) == 0,
            "a physical local PP derivative became B/Eq-untied")

    return {
        "category": "four-site local operation fan",
        "generators": {
            "top_projection": len(top),
            "individual_PP_reinsertions": len(lower),
            "external_and_named_augmentation": len(external),
        },
        "rank_dimension": [rank(columns), len(detector)],
        "unique_quotient_character": "delta.(B-Eq)",
        "physical_selected_db01_response_derivative_chi": "0",
        "physical_eighteen_direction_response_derivative_chi": "0",
        "qualification": (
            "this classifies derivatives of the physical four-site response; "
            "an independently adjoined absolute db01 carrier is a gluing "
            "datum, not a local derivative"
        ),
    }


def operation_parent_partition_audit(joint_ledger) -> dict[str, object]:
    all_unordered = tuple((left, right) for left in range(4)
                          for right in range(left + 1, 4))
    cross = tuple(pair for pair in all_unordered
                  if (pair[0] in DIRECT) != (pair[1] in DIRECT))
    same = tuple(pair for pair in all_unordered if pair not in cross)
    require(cross == CROSS_EDGES and same == SAME_SHORE_EDGES,
            (cross, same))

    # Four cross-shore generators, with the two face-complete pairings.
    signless = tuple(basis(4, left, right) for left, right in cross)
    oriented = tuple(tuple(Q(1) if index == left else
                            Q(-1) if index == right else Q(0)
                            for index in range(4))
                     for left, right in cross)
    gauged = tuple(tuple(DELTA[index] * value[index]
                         for index in range(4)) for value in oriented)
    require(gauged == signless and rank(signless) == 3
            and all(dot(DELTA, value) == 0 for value in signless),
            "the DQ/PS K2,2 quotient changed")

    physical = joint_ledger["physical_source_label_gate"]
    formal = joint_ledger["formal_primitive_C4_shadow"]
    expected_edges = [[CORNERS[left].split("=")[0],
                       CORNERS[right].split("=")[0]]
                      for left, right in cross]
    # Compare the invariant information rather than spelling conventions.
    require(physical["profile_violations"] == 4
            and physical["root_cobar_edges_realized"] == 0
            and formal["incidence_rank"] == 3
            and formal["alternating_charge"] == ["1", "1", "-1", "-1"]
            and formal["projected_mate_row_types"] == ["A+B", "A+C"],
            (physical, formal, expected_edges))

    records = []
    for index, (left, right) in enumerate(cross):
        top_be = be_vector(B=signless[index])
        tied_be = be_vector(B=signless[index], Eq=signless[index])
        records.append({
            "name": f"g_{left}{right}",
            "source": CORNERS[left],
            "target": CORNERS[right],
            "profiles_DPSQ": [list(PROFILES[left]), list(PROFILES[right])],
            "shore_gauged_private_top": [int(value)
                                           for value in signless[index]],
            "chi_private_top": str(chi(top_be)),
            "chi_tied_lift": str(chi(tied_be)),
        })
    return {
        "corner_order": list(CORNERS),
        "same_corner_types": 4,
        "same_shore_pair_types": [list(pair) for pair in same],
        "cross_shore_pair_types": [list(pair) for pair in cross],
        "cross_shore_generator_count": len(cross),
        "cross_shore_incidence_rank": rank(signless),
        "generators": records,
        "face_complete_pairings": {
            "tau_a": ["g_02", "g_13"],
            "tau_b": ["g_03", "g_12"],
        },
        "three_chart_projection": ["A+B", "A+C"],
        "linear_exhaustiveness": (
            "self and same-shore incidences stay in the local operation fan; "
            "every primitive incidence which changes DQ/PS shore has exactly "
            "one of the four displayed endpoint types, and a multi-face "
            "totalization is a linear sum of them"
        ),
    }


def word_and_augmented_frontier_audit(packaging_ledger, hyperbolic_ledger) \
        -> dict[str, object]:
    word = packaging_ledger["literal_word_and_fine_map"]
    augmented = packaging_ledger["augmented_packaging"]
    section = hyperbolic_ledger["degree_zero_word_section"]
    mixed = hyperbolic_ledger["conditional_paired_augmented_test"]
    require(not word["literal_grade_preserving_map"]
            and not word["cap_word_in_existing_D4_cube"]
            and section["old_relative_cross_word_rank"] == 0
            and section["rank_after_two_root_labelled_arrows"] == 2
            and augmented["rank_before_mixed_cell"] == 2
            and augmented["rank_after_mixed_cell"] == 3
            and augmented["rank_after_labelled_ridge"] == 4
            and mixed["first_augmented_obstruction"].startswith(
                "mixed reduced-Eq naturality-square incidence"),
            (word, section, augmented, mixed))
    return {
        "block_diagonal_or_off_grade": {
            "response_word": word["response_word_display"],
            "cap_word": word["canonical_cap_word"],
            "hamming_distance": word["word_hamming_distance"],
            "old_cross_word_rank": section["old_relative_cross_word_rank"],
            "B_Eq_projection": "0 until a physical word/fine arrow is supplied",
        },
        "finite_word_sections": {
            "root_labels": ["A/B return", "A/C return"],
            "required_arrows": 2,
            "rank_after_both": section["rank_after_two_root_labelled_arrows"],
            "operation_faces": {
                "A/B return": ["g_02", "g_12"],
                "A/C return": ["g_03", "g_13"],
            },
        },
        "after_granting_word_sections": {
            "first_augmented_family": mixed["first_augmented_obstruction"],
            "paired_rank_jump": [
                mixed["strong_grant_base_rank"],
                mixed["rank_after_paired_mixed_comparison"],
            ],
            "second_family": mixed["second_augmented_obstruction"],
            "rootwise_mixed_rank": mixed[
                "rank_with_two_individual_mixed_cells"],
        },
    }


def exact_chi_frontier_audit() -> dict[str, object]:
    # Work in one cross-shore generator.  Its physical shore-gauged top B
    # incidence u is delta-dark.  The missing mixed naturality square must
    # specify an Eq occurrence vector e.  The scalar is therefore exactly
    # -delta.e.  Test a spanning set and the balanced controls.
    u = basis(4, 0, 2)
    require(dot(DELTA, u) == 0, "the top gluing edge became chi-bright")
    samples = []
    for eq in (
            (1, 0, 0, 0),
            (0, 1, 0, 0),
            (0, 0, 1, 0),
            (0, 0, 0, 1),
            (1, 1, -1, -1),
            u):
        value = be_vector(B=u, Eq=eq)
        expected = -dot(DELTA, eq)
        require(chi(value) == expected,
                ("mixed Eq formula changed", eq, chi(value), expected))
        samples.append({
            "Eq": [int(Q(value)) for value in eq],
            "chi": str(expected),
            "normalized_Psi": str(expected / 4),
        })
    require(samples[-2]["chi"] == "-4"
            and samples[-1]["chi"] == "0",
            samples)
    return {
        "known_private_top": "u=e_DQ+e_PS after the physical shore gauge",
        "known_top_value": "delta.u=0",
        "first_unclassified_family": (
            "root-labelled cross-word mixed reduced-Eq naturality-square "
            "lift kappa_AB (and independently kappa_AC)"
        ),
        "write_missing_Eq_occurrence_vector_as": "e_kappa",
        "exact_projection": "(B,Eq)=(u,e_kappa)",
        "exact_scalar": "chi(kappa)=-delta.e_kappa",
        "normalized_scalar": "Psi(kappa)=-delta.e_kappa/4",
        "paired_scalar": "chi(kappa_AB+kappa_AC)=chi_AB+chi_AC",
        "controls": samples,
        "numeric_value_currently_proved": False,
        "why": (
            "the committed source constructs neither cross-word section nor "
            "the mixed Eq occurrence map; zero would assume a tied lift and "
            "nonzero would assume the desired bright mismatch"
        ),
    }


def exhaustiveness_statement_audit() -> dict[str, object]:
    primitive_categories = (
        "four-site local: same corner or same-shore operation incidence",
        "block-diagonal/off-grade: selected B/Eq projection zero",
        "cross-shore: one of g_02,g_03,g_12,g_13",
    )
    require(len(primitive_categories) == 3
            and len(CROSS_EDGES) == 4,
            "the primitive exhaustiveness partition changed")
    return {
        "primitive_cellular_decomposition_is_exhaustive": True,
        "categories": list(primitive_categories),
        "proof": (
            "the selected interface has exactly four operation parents. "
            "An incidence either preserves a parent, joins the two vertices "
            "on one shore, changes word/fine out of the selected block, or "
            "joins one of 2 direct parents to one of 2 endpoint parents; "
            "these cases are disjoint and exhaustive, and linear "
            "totalization adds no new quotient generator type"
        ),
        "unconditional_full_decorated_source_decomposition_proved": False,
        "missing_census_hypothesis": (
            "every full decorated same-grade source column is a linear "
            "totalization of primitive one-incidence cells with the retained "
            "operation-parent/word/fine/repeated labels"
        ),
        "counterguard": (
            "a higher multi-parent source generator not admitting that "
            "cellular decomposition could carry an independent balanced "
            "B/Eq packet and is not constrained by the rank-126 local map"
        ),
        "finite_reduction_consequence": (
            "under the census hypothesis, full terminality reduces to the "
            "two mixed-Eq scalars for the A/B and A/C word sections"
        ),
    }


def audit():
    pin_dependencies()
    local = load(
        "computations/verify_h3_uc4_four_site_response_private_eq_local_terminal_gate.py",
        "four_site_decomposition_local",
    )
    maximal = load(
        "computations/verify_h3_maximal_pointed_balanced_same_grade_terminal_gate.py",
        "four_site_decomposition_maximal",
    )
    joint = load(
        "computations/verify_h3_gate_ii_primitive_c4_joint_cobar_label_gate.py",
        "four_site_decomposition_joint",
    )
    packaging = load(
        "computations/verify_h3_shear_collision_augp2_packaging_map_gate.py",
        "four_site_decomposition_packaging",
    )
    hyperbolic = load(
        "computations/verify_h3_hyperbolic_root_pair_cross_word_eq_ridge_gate.py",
        "four_site_decomposition_hyperbolic",
    )
    projection = load(
        "computations/verify_h3_balanced_square_private_eq_projection_gate.py",
        "four_site_decomposition_projection",
    )
    modules = (local, maximal, joint, packaging, hyperbolic, projection)
    dependency_scope, dependency_ledgers = dependency_scope_audit(modules)
    ledger = {
        "theorem": "h3 four-site full-source exhaustiveness decomposition gate",
        "pins": PINS,
        "dependency_scope": dependency_scope,
        "exhaustive_four_site_local_factorization":
            local_factorization_audit(local),
        "operation_parent_partition": operation_parent_partition_audit(
            dependency_ledgers["joint"]),
        "word_and_augmented_frontier":
            word_and_augmented_frontier_audit(
                dependency_ledgers["packaging"],
                dependency_ledgers["hyperbolic"]),
        "exact_first_unclassified_chi": exact_chi_frontier_audit(),
        "exhaustiveness_scope_and_counterguard":
            exhaustiveness_statement_audit(),
        "verdict": (
            "The rank-126/127 supermap exhausts every physical four-site "
            "response/target/PP/reinsertion derivative and forces chi=0, "
            "including the selected db01 and eighteen-direction response "
            "derivatives.  Operation-parent typing leaves exactly four "
            "cross-shore DQ/PS mate types, paired into the A/B and A/C "
            "root-labelled word sections.  Their shore-gauged top edges are "
            "chi-dark.  After granting the word sections, the first "
            "unclassified physical family is the mixed reduced-Eq "
            "naturality lift, with exact scalar -delta.e_kappa.  No numeric "
            "value follows because the physical Eq occurrence map is absent."
        ),
        "scope": (
            "Exact primitive-cell decomposition in the canonical h=3 "
            "selected four-site interface over Q.  It reduces the remaining "
            "test to two mixed-Eq scalars.  It does not prove the separate "
            "global census assertion that every higher full decorated source "
            "column is generated by this primitive cellular grammar."
        ),
    }
    digest = sha256(json.dumps(
        ledger, sort_keys=True, separators=(",", ":")
    ).encode()).hexdigest()
    if EXPECTED_LEDGER_SHA256 != "TO_BE_PINNED":
        require(digest == EXPECTED_LEDGER_SHA256,
                ("four-site decomposition ledger changed", digest))
    return ledger, digest


def main() -> None:
    ledger, digest = audit()
    local = ledger["exhaustive_four_site_local_factorization"]
    frontier = ledger["exact_first_unclassified_chi"]
    print("h3 four-site primitive exhaustiveness decomposition: PASS")
    print("local supermap rank/dimension: {}/{}".format(
        *local["rank_dimension"]))
    print("cross-shore DQ/PS generator types: 4; top chi=0")
    print("first unclassified family: MIXED REDUCED-EQ NATURALITY LIFT")
    print("exact chi: " + frontier["exact_scalar"])
    print("unconditional higher-source census: NOT PROVED")
    print("ledger_sha256=" + digest)


if __name__ == "__main__":
    main()
