#!/usr/bin/env python3
"""Complete order-four Spencer-output census in the committed OO model.

The checker combines four exact pieces.

* It reruns the committed 16-face Hasse/denominator/reset lock, including all
  6561 full-nine rows, all fifteen denominator columns, cap target/residue,
  and pq/pr parity.
* It exhausts every differential-direction multiset of ordinary order at
  most four in the 55-variable bounded ring.  Exactly the 90 perfect
  matchings of H_m have a nonzero q-zero top; 15 are pq-direct/pr-two-star
  and the other 75 are two-star/two-star.
* It compresses every literal physical column by edge-zero evaluation and
  extraction of the homogenizing-u Eq coefficient.  In coordinates
  (u*Eq,w,target,ordinary-residue), all columns are generated by four
  displayed types of rank three.
* The integral polynomial covector (Y,1,Y,-1) kills those types but reads
  kappa*Y on q=(0,kappa*Y,0,0), proving exact nonmembership.

This is complete for the committed polynomial physical-row/chart/
denominator/cap codomain and total ordinary order <=4.  It does not exclude
an uncommitted new source-resolution generator or localization by a source
equation.
"""

from __future__ import annotations

from collections import Counter
from fractions import Fraction
from hashlib import sha256
from itertools import combinations_with_replacement, permutations
import importlib.util
import io
import json
from pathlib import Path
from contextlib import redirect_stdout


HERE = Path(__file__).resolve().parent
Q = Fraction
EXPECTED_DIGEST = "6bd1fe74846c6e3fbcb04618ebb369922593060791e97216c76d376f82e36206"
RESET_LOCK_DIGEST = (
    "07a9b589df4b4708133c0849d64bf9e98d7d53d4a4aeeed2f6103a2a3945a828"
)


def require(condition, message):
    if not condition:
        raise RuntimeError(message)


def load(name, filename):
    spec = importlib.util.spec_from_file_location(name, HERE / filename)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


LOCK = load(
    "oo_complete_order4_reset_lock",
    "verify_h3_reset_lane_ores_descent_lock.py",
)
HASSE = LOCK.tot


def rerun_committed_complete_face_module():
    captured = io.StringIO()
    with redirect_stdout(captured):
        LOCK.main()
    output = captured.getvalue()
    require(RESET_LOCK_DIGEST in output,
            "the committed reset/Hasse lock lost its frozen digest")
    require(LOCK.LEDGER["reconstruction_objects"] == 15,
            "the selected Hasse-cube census changed")
    require(len(LOCK.LEDGER["per_face_dU_Hm"]) == 16,
            "the complete 16-face ledger changed")
    require(LOCK.LEDGER["leak_rank"] == 12
            and LOCK.LEDGER["leak_monomial_count"] == 22,
            "the denominator face module changed")
    require(LOCK.LEDGER["lock"]["rows_checked"] == 6561,
            "the full-nine row census changed")
    return {
        "baseline_digest": RESET_LOCK_DIGEST,
        "selected_cubes": LOCK.LEDGER["reconstruction_objects"],
        "faces_per_cube": len(LOCK.LEDGER["per_face_dU_Hm"]),
        "selected_cube_faces": (
            LOCK.LEDGER["reconstruction_objects"]
            * len(LOCK.LEDGER["per_face_dU_Hm"])
        ),
        "full_nine_rows": LOCK.LEDGER["lock"]["rows_checked"],
        "denominator_columns": 15,
        "denominator_internal_face_probes": 20,
        "denominator_leak_rank": LOCK.LEDGER["leak_rank"],
        "denominator_leak_monomials": LOCK.LEDGER["leak_monomial_count"],
        "cap_columns": 2,
        "strict_chart_global_boundary": 0,
    }


def is_edge(item):
    return len(item) == 5 and item[0] == "w"


def edge_pair(item):
    require(is_edge(item), "a non-edge reached the physical-pair map")
    return item[1], item[2]


def site_colour_degree(term):
    degree = [[0, 0, 0] for _ in HASSE.SITES]
    for item in term:
        require(is_edge(item), "the mixed row acquired a non-edge variable")
        _tag, left, right, left_colour, right_colour = item
        degree[left][left_colour] += 1
        degree[right][right_colour] += 1
    return tuple(tuple(row) for row in degree)


def audit_complete_direction_multisets():
    mixed_support = sorted({item for term in LOCK.H_MIXED for item in term})
    pure_support = sorted({item for term in LOCK.H_PURE for item in term})
    homogenizer = LOCK.U_ITEM
    variables = sorted(set(mixed_support) | set(pure_support) | {homogenizer})
    require(len(mixed_support) == 27 and len(pure_support) == 27,
            "the mixed/pure edge supports changed")
    require(set(mixed_support).isdisjoint(pure_support)
            and len(variables) == 55,
            "the bounded ring stopped having 54 edges plus u")
    require(homogenizer not in {item for term in LOCK.H_MIXED for item in term},
            "H_m acquired the homogenizer")

    mixed_terms = set(LOCK.H_MIXED)
    require(len(mixed_terms) == 90
            and all(len(term) == len(set(term)) == 4 for term in mixed_terms),
            "H_m stopped being a squarefree 90-term quartic")
    expected_degree = tuple(
        tuple(1 if colour == LOCK.MIXED[site] else 0 for colour in range(3))
        for site in HASSE.SITES
    )
    require({site_colour_degree(term) for term in mixed_terms}
            == {expected_degree},
            "H_m lost its fine site-colour multidegree")

    totals = {}
    u_containing = {}
    top_sources = []
    order_four_reasons = Counter()
    for order in range(5):
        total = 0
        with_u = 0
        for direction_multiset in combinations_with_replacement(variables, order):
            total += 1
            if homogenizer in direction_multiset:
                with_u += 1
            if order != 4:
                continue
            if homogenizer in direction_multiset:
                order_four_reasons["contains_u"] += 1
            elif any(item in pure_support for item in direction_multiset):
                order_four_reasons["contains_pure_edge"] += 1
            elif len(set(direction_multiset)) < 4:
                order_four_reasons["repeated_mixed_direction"] += 1
            elif direction_multiset in mixed_terms:
                order_four_reasons["qzero_matching_top"] += 1
                top_sources.append(direction_multiset)
            else:
                order_four_reasons["distinct_mixed_nonmatching"] += 1
        totals[order] = total
        u_containing[order] = with_u

    require(totals == {0: 1, 1: 55, 2: 1540, 3: 29260, 4: 424270},
            "the complete order<=4 multiset census changed")
    require(u_containing == {0: 0, 1: 1, 2: 55, 3: 1540, 4: 29260},
            "the u-containing direction census changed")
    require(sum(order_four_reasons.values()) == totals[4]
            and order_four_reasons["qzero_matching_top"] == 90,
            "the order-four pruning ceased to be exhaustive")

    pq_pair = (HASSE.P, HASSE.QSITE)
    pr_pair = (HASSE.P, HASSE.R)
    pq_direct = [term for term in top_sources if pq_pair in map(edge_pair, term)]
    pr_direct = [term for term in top_sources if pr_pair in map(edge_pair, term)]
    require(len(pq_direct) == 15 and not pr_direct,
            "the q-zero pq/pr sector census changed")
    selected = {
        tuple(sorted(LOCK.directions_for(LOCK.MIXED, deleted, matching)))
        for deleted in HASSE.ODD
        for matching in HASSE.matchings(LOCK.face(deleted))
    }
    require(selected == set(pq_direct) and len(selected) == 15,
            "the 15 committed cubes are not exactly the pq-direct tops")

    # Secondary hybrid lemma.  A and A^2 contain no u, so every differential
    # monomial containing partial_u kills both generators.  A coefficient on
    # the left cannot change zero.  This is only the A/A^2 generator test;
    # it does not claim closure on arbitrary polynomial multiples f*A^2.
    square = HASSE.multiply(LOCK.H_MIXED, LOCK.H_MIXED)
    require(all(homogenizer not in term for term in square),
            "A^2 acquired u")
    for order in range(1, 5):
        probe = (homogenizer,) + tuple(mixed_support[:order - 1])
        require(not HASSE.derivative(LOCK.H_MIXED, probe)
                and not HASSE.derivative(square, probe),
                "a u-containing order<=4 probe stopped killing A and A^2")

    return {
        "ring_variables": len(variables),
        "mixed_edges": len(mixed_support),
        "pure_edges": len(pure_support),
        "direction_multisets_by_order": totals,
        "direction_multisets_total": sum(totals.values()),
        "u_containing_by_order": u_containing,
        "u_containing_total": sum(u_containing.values()),
        "order_four_pruning": dict(sorted(order_four_reasons.items())),
        "qzero_top_sources": len(top_sources),
        "pq_direct_pr_two_star": len(pq_direct),
        "pq_two_star_pr_two_star": len(top_sources) - len(pq_direct),
        "committed_selected_tops": len(selected),
        "fine_degree": [list(row) for row in expected_degree],
        "u_hybrid_lemma": (
            "every order<=4 differential monomial containing partial_u "
            "annihilates A and A^2; it cannot change D(A) or the A^2 "
            "generator constraint (no claim for arbitrary multiples f*A^2)"
        ),
    }


# Sparse polynomials in kappa,Y for the final four-coordinate module.
KAPPA_INDEX, Y_INDEX = 0, 1


def poly_constant(value=1):
    value = Q(value)
    return {(0, 0): value} if value else {}


def poly_variable(index):
    exponent = [0, 0]
    exponent[index] = 1
    return {tuple(exponent): Q(1)}


def poly_add(*polynomials):
    answer = {}
    for polynomial in polynomials:
        for monomial, value in polynomial.items():
            answer[monomial] = answer.get(monomial, Q(0)) + value
            if not answer[monomial]:
                del answer[monomial]
    return answer


def poly_scale(scalar, polynomial):
    scalar = Q(scalar)
    return {monomial: scalar * value for monomial, value in polynomial.items()
            if scalar * value}


def poly_multiply(left, right):
    answer = {}
    for left_monomial, left_value in left.items():
        for right_monomial, right_value in right.items():
            monomial = (left_monomial[0] + right_monomial[0],
                        left_monomial[1] + right_monomial[1])
            answer[monomial] = answer.get(monomial, Q(0)) + (
                left_value * right_value
            )
            if not answer[monomial]:
                del answer[monomial]
    return answer


def vector_add(*vectors):
    return tuple(poly_add(*(vector[index] for vector in vectors))
                 for index in range(4))


def vector_scale(scalar, vector):
    return tuple(poly_scale(scalar, value) for value in vector)


def pairing(covector, vector):
    return poly_add(*(poly_multiply(left, right)
                      for left, right in zip(covector, vector, strict=True)))


def determinant(columns):
    require(len(columns) == 4 and all(len(column) == 4 for column in columns),
            "the determinant needs four four-coordinate columns")
    answer = {}
    for permutation in permutations(range(4)):
        inversions = sum(permutation[i] > permutation[j]
                         for i in range(4) for j in range(i + 1, 4))
        term = poly_constant(-1 if inversions % 2 else 1)
        for row, column in enumerate(permutation):
            term = poly_multiply(term, columns[column][row])
        answer = poly_add(answer, term)
    return answer


def evaluate(polynomial, kappa=1, y=1):
    return sum(value * Q(kappa) ** exponent[0] * Q(y) ** exponent[1]
               for exponent, value in polynomial.items())


def rational_rank(columns, kappa=1, y=1):
    rows = [[evaluate(column[row], kappa, y) for column in columns]
            for row in range(4)]
    rank = 0
    for column in range(len(columns)):
        pivot = next((row for row in range(rank, 4) if rows[row][column]), None)
        if pivot is None:
            continue
        rows[rank], rows[pivot] = rows[pivot], rows[rank]
        pivot_value = rows[rank][column]
        rows[rank] = [value / pivot_value for value in rows[rank]]
        for row in range(4):
            if row == rank or not rows[row][column]:
                continue
            factor = rows[row][column]
            rows[row] = [value - factor * lead
                         for value, lead in zip(rows[row], rows[rank])]
        rank += 1
    return rank


def encode_polynomial(polynomial):
    names = ("kappa", "Y")
    terms = []
    for exponent, value in sorted(polynomial.items()):
        factors = [str(value)]
        for name, power in zip(names, exponent, strict=True):
            if power:
                factors.append(name if power == 1 else f"{name}^{power}")
        terms.append("*".join(factors))
    return "+".join(terms) if terms else "0"


def audit_specialized_augmented_module():
    one = poly_constant()
    minus_one = poly_constant(-1)
    zero = {}
    y = poly_variable(Y_INDEX)
    kappa = poly_variable(KAPPA_INDEX)
    kappa_y = poly_multiply(kappa, y)

    # Coordinates: coefficient of u*e_Eq after edges=0, w, target, ores.
    # HYP-L gives F_alpha|_0=-target(g_alpha)*u, so every one of the
    # 6561 physical rows specializes to a multiple of physical_row.
    physical_row = (minus_one, zero, one, zero)
    cap_t = (zero, poly_scale(-1, y), one, zero)
    cap_rho = (zero, one, zero, one)
    # Every nonbottom Hasse/denominator readout with q-zero value carries
    # the exact Eq defect B=H0-u, hence u coefficient -1.
    top_with_eq_defect = (minus_one, y, zero, zero)
    desired = (zero, kappa_y, zero, zero)

    require(top_with_eq_defect
            == vector_add(physical_row, vector_scale(-1, cap_t)),
            "the q-zero top stopped being the physical-row/cap graph")
    physical_generators = [physical_row, cap_t, cap_rho, top_with_eq_defect]
    require(rational_rank(physical_generators, 1, 1) == 3,
            "the specialized physical module rank changed")
    require(rational_rank(physical_generators + [desired], 1, 1) == 4,
            "the desired class stopped raising rank 3 to 4")

    covector = (y, one, y, minus_one)
    require(all(not pairing(covector, column)
                for column in physical_generators),
            "the integral cokernel covector stopped killing a physical type")
    desired_pairing = pairing(covector, desired)
    require(desired_pairing == kappa_y and desired_pairing,
            "the cokernel covector stopped reading kappa*Y")
    det = determinant([physical_row, cap_t, cap_rho, desired])
    require(det == poly_scale(-1, kappa_y),
            "the augmented determinant stopped being -kappa*Y")

    # The formal prolonged top omits the Eq coordinate and is exactly the
    # desired column.  Its source-faithful diagonal projection adds the
    # top_with_eq_defect type, on which the covector vanishes.
    require(pairing(covector, top_with_eq_defect) == {}
            and pairing(covector, desired) == kappa_y,
            "the prolonged/physical distinction collapsed")

    return {
        "coordinates": ["u*Eq after edges=0", "w", "target", "ores"],
        "physical_type_columns": {
            "full_nine_target_row": ["-1", "0", "1", "0"],
            "T": ["0", "-Y", "1", "0"],
            "rho": ["0", "1", "0", "1"],
            "qzero_top_with_Eq_defect": ["-1", "Y", "0", "0"],
        },
        "physical_rank": 3,
        "rank_with_desired": 4,
        "desired": ["0", "kappa*Y", "0", "0"],
        "integral_cokernel_covector": ["Y", "1", "Y", "-1"],
        "desired_pairing": encode_polynomial(desired_pairing),
        "augmented_determinant": encode_polynomial(det),
        "formal_prolonged_top": "desired column, but not source-faithful",
        "physical_projection": "adds (-u)*Eq and lies in the rank-3 graph",
    }


def main():
    ledger = {
        "committed_face_module": rerun_committed_complete_face_module(),
        "complete_direction_census": audit_complete_direction_multisets(),
        "specialized_augmented_module": audit_specialized_augmented_module(),
        "verdict": {
            "order4_source_provenant_chain_found": False,
            "membership": (
                "q=(0,+kappa*Y) is not in the committed polynomial "
                "physical-row/chart/denominator/cap module"
            ),
            "smallest_missing_type": (
                "a new source-resolution generator whose edge-zero u*Eq "
                "coefficient is zero but whose w-boundary is kappa*Y"
            ),
            "stop_before_order5": True,
        },
        "scope": {
            "proved": (
                "complete total ordinary-order<=4 direction census and "
                "complete literal-column membership in the committed "
                "polynomial codomain"
            ),
            "not_proved": [
                "nonexistence in an uncommitted larger source resolution",
                "nonexistence after inverting an edge-dependent source equation",
                "any order >= 5 statement",
                "the curved OO overlap theorem or Krenn's conjecture",
            ],
        },
    }
    payload = json.dumps(ledger, sort_keys=True, separators=(",", ":"))
    digest = sha256(payload.encode()).hexdigest()
    if EXPECTED_DIGEST != "TO_BE_FILLED":
        require(digest == EXPECTED_DIGEST,
                f"complete order-four ledger changed: {digest}")
    print("OO complete order-four Spencer output cascade: PASS")
    print("all order<=4 direction multisets: 455126; q-zero tops: 90")
    print("sector split: 15 pq-direct/pr-two-star + 75 two-star/two-star")
    print("literal physical module rank 3; desired q raises rank to 4")
    print("cokernel covector (Y,1,Y,-1) reads +kappa*Y on q")
    print("u-containing order<=4 operators annihilate A and A^2")
    print("verdict: no source-provenant n_c in the committed order-four module")
    print(f"sha256: {digest}")


if __name__ == "__main__":
    main()
