//! Independent exact replay of the compact hidden-child K3/K4 charge ledger.
#![allow(dead_code,unused_imports)]
include!("../unaudited-codex-orbit0-filtered-k16-run-2026-08-23/run_filtered_k17.rs");
use std::io::{BufReader,Read};

const DIR:&str="computations/unaudited-codex-orbit0-hidden-k16-children-prefix-2026-08-23/";
const LEDGER:&str="computations/unaudited-codex-orbit0-hidden-k16-children-prefix-2026-08-23/hidden_child_profiles_prefix.bin";
const K4FILE:&str="computations/unaudited-codex-orbit0-filtered-k18-charge-2026-08-23/filtered_k18_k4.bin";
const CYCLEFILE:&str="computations/unaudited-codex-orbit0-filtered-k16-run-2026-08-23/filtered_k17_cycle_aux.bin";
const U:i128=400_591_699_200;

#[derive(Clone,Copy,Eq,Hash,Ord,PartialEq,PartialOrd)]struct PKey{profile:[u8;29],sig:[u8;12],pivot:u8}
#[derive(Clone,Copy,Debug,Eq,Hash,Ord,PartialEq,PartialOrd)]struct CKey([u8;13]);
struct CEnv{cells:[[u8;4];252],dual:HashMap<CKey,i64>,k4:Vec<Vec<[u8;4]>>}
fn cenv()->CEnv{
 let b=read(CYCLEFILE).unwrap();assert_eq!(&b[..8],b"K17CYC1\0");let mut p=8;let mut cells=[[0;4];252];for c in &mut cells{c.copy_from_slice(&b[p..p+4]);p+=4}let n=u32le(&b[p..p+4])as usize;p+=4;let mut dual=HashMap::new();for _ in 0..n{let mut k=[0;13];k.copy_from_slice(&b[p..p+13]);p+=13;let v=i64le(&b[p..p+8]);p+=8;dual.insert(CKey(k),v);}assert_eq!(p,b.len());
 let z=read(K4FILE).unwrap();assert_eq!(&z[..7],b"K18K4A1");let mut q=7;let mut k4=vec![Vec::new();78];for row in &mut k4{for _ in 0..60{let mut t=[0;4];t.copy_from_slice(&z[q..q+4]);q+=4;row.push(t)}}assert_eq!(q,z.len());CEnv{cells,dual,k4}
}
fn remove4(row:&Row,a:&[u8;4])->[u8;20]{let mut x=[0;20];let(mut j,mut k)=(0,0);for &c in &row.0{if j<4&&c==a[j]{j+=1}else{x[k]=c;k+=1}}assert_eq!((j,k),(4,20));x}
fn path_profile(row:&Row,p:usize,e:&Engine,c:&CEnv)->[u8;29]{
 let m=remove4(row,&e.anchors[p]);let mut edges=[(0u8,0u8);20];let mut adj=[[255u8;2];24];let mut deg=[0usize;24];for(i,&cell)in m.iter().enumerate(){let[u,v,a,b]=c.cells[cell as usize];let x=3*u+a;let y=3*v+b;edges[i]=(x,y);adj[x as usize][deg[x as usize]]=i as u8;deg[x as usize]+=1;adj[y as usize][deg[y as usize]]=i as u8;deg[y as usize]+=1}
 let mut eid=[-1i8;24];for(i,&cell)in e.anchors[p].iter().enumerate(){let[u,v,a,b]=c.cells[cell as usize];eid[(3*u+a)as usize]=(2*i)as i8;eid[(3*v+b)as usize]=(2*i+1)as i8}
 let mut partner=[255;8];let mut lens=[0;8];let mut used=[false;20];for s in 0..8{if partner[s]!=255{continue}let mut v=eid.iter().position(|&x|x==s as i8).unwrap();let mut prev=255;let mut len=0;loop{let edge=*adj[v].iter().find(|&&x|x!=255&&x!=prev).unwrap();used[edge as usize]=true;let(a,b)=edges[edge as usize];v=if a as usize==v{b as usize}else{a as usize};prev=edge;len+=1;if eid[v]>=0{let t=eid[v]as usize;partner[s]=t as u8;partner[t]=s as u8;lens[s]=len;lens[t]=len;break}}}
 let mut closed=[0;12];let mut nc=0;for seed in 0..20{if used[seed]{continue}let mut edge=seed as u8;let mut v=edges[seed].0 as usize;let start=v;let mut len=0;loop{used[edge as usize]=true;let(a,b)=edges[edge as usize];v=if a as usize==v{b as usize}else{a as usize};len+=1;if v==start{break}edge=*adj[v].iter().find(|&&x|x!=edge).unwrap()}closed[nc]=len;nc+=1}closed[..nc].sort_unstable();let mut out=[0;29];out[..8].copy_from_slice(&partner);out[8..16].copy_from_slice(&lens);out[16]=nc as u8;out[17..17+nc].copy_from_slice(&closed[..nc]);out
}
fn literal_ckey(row:&Row,c:&CEnv)->CKey{let mut adj=[[0u8;2];24];let mut deg=[0usize;24];for &cell in &row.0{let[u,v,a,b]=c.cells[cell as usize];let x=(3*u+a)as usize;let y=(3*v+b)as usize;adj[x][deg[x]]=y as u8;deg[x]+=1;adj[y][deg[y]]=x as u8;deg[y]+=1}assert!(deg.iter().all(|&d|d==2));let mut seen=[false;24];let mut parts=[0;12];let mut n=0;for st in 0..24{if seen[st]{continue}let mut stack=[0u8;24];let(mut top,mut size)=(1,0);stack[0]=st as u8;seen[st]=true;while top>0{top-=1;let x=stack[top]as usize;size+=1;for &yy in &adj[x]{let y=yy as usize;if !seen[y]{seen[y]=true;stack[top]=yy;top+=1}}}parts[n]=size;n+=1}parts[..n].sort_unstable();let mut k=[0;13];k[0]=n as u8;k[1..1+n].copy_from_slice(&parts[..n]);CKey(k)}
fn abstract_ckey(prof:&[u8;29],p:usize,t:&[u8;4],e:&Engine,c:&CEnv)->CKey{let mut eid=[-1i8;24];for(i,&cell)in e.anchors[p].iter().enumerate(){let[u,v,a,b]=c.cells[cell as usize];eid[(3*u+a)as usize]=(2*i)as i8;eid[(3*v+b)as usize]=(2*i+1)as i8}let mut tp=[255;8];for &cell in t{let[u,v,a,b]=c.cells[cell as usize];let x=eid[(3*u+a)as usize];let y=eid[(3*v+b)as usize];assert!(x>=0&&y>=0);tp[x as usize]=y as u8;tp[y as usize]=x as u8}assert!(tp.iter().all(|&x|x!=255));let mut seen=[false;8];let mut parts=[0u8;12];let mut n=0;for st in 0..8{if seen[st]{continue}let mut stack=[0u8;8];let(mut top,mut nodes,mut pathsum)=(1,0u8,0u16);stack[0]=st as u8;seen[st]=true;while top>0{top-=1;let x=stack[top]as usize;nodes+=1;pathsum+=prof[8+x]as u16;for y in[prof[x],tp[x]]{let yy=y as usize;if !seen[yy]{seen[yy]=true;stack[top]=y;top+=1}}}parts[n]=(pathsum/2+(nodes as u16)/2)as u8;n+=1}let nc=prof[16]as usize;for &x in &prof[17..17+nc]{parts[n]=x;n+=1}parts[..n].sort_unstable();let mut k=[0;13];k[0]=n as u8;k[1..1+n].copy_from_slice(&parts[..n]);CKey(k)}

fn main(){let begun=Instant::now();let e=parse();let c=cenv();let mut reader=BufReader::with_capacity(1<<20,File::open(LEDGER).unwrap());let mut h=[0u8;64];reader.read_exact(&mut h).unwrap();assert_eq!(&h[..8],b"HCPROF1\0");assert_eq!(i128::from_le_bytes(h[8..24].try_into().unwrap()),U);assert_eq!(u64::from_le_bytes(h[24..32].try_into().unwrap()),0);let count=u64::from_le_bytes(h[32..40].try_into().unwrap());assert_eq!(u16::from_le_bytes(h[40..42].try_into().unwrap()),90);assert_eq!(count,62_678);
 let(mut prior,mut weight_sum,mut uses_sum)=(None,0i128,0u64);let(mut k3n,mut k3i,mut k4n,mut k4i,mut guards)=(0u64,0u64,0u64,0u64,0u64);let(mut k3q,mut k3iq,mut k4q,mut k4iq)=(0i128,0i128,0i128,0i128);
 for _ in 0..count{let mut rec=[0u8;90];reader.read_exact(&mut rec).unwrap();let mut prof=[0u8;29];prof.copy_from_slice(&rec[..29]);let mut sig=[0u8;12];sig.copy_from_slice(&rec[29..41]);let pivot=rec[41]as usize;let key=PKey{profile:prof,sig,pivot:pivot as u8};assert!(prior.map_or(true,|x|x<key));prior=Some(key);let weight=i128::from_le_bytes(rec[42..58].try_into().unwrap());let uses=u64::from_le_bytes(rec[58..66].try_into().unwrap());let mut rr=[0u8;24];rr.copy_from_slice(&rec[66..90]);let row=Row(rr);assert_eq!(signature(&row.0,&e),sig);assert!(available(sig,&e).contains(&pivot));assert_eq!(path_profile(&row,pivot,&e,&c),prof);weight_sum+=weight;uses_sum+=uses;
  for degree in[3usize,4]{let tails:&[[u8;4]]=if degree==3{&e.all_k3[pivot]}else{&c.k4[pivot]};for tail in tails{let child=replace_anchor(&row,&e.anchors[pivot],tail);let ak=abstract_ckey(&prof,pivot,tail,&e,&c);assert_eq!(ak,literal_ckey(&child,&c));guards+=1;let q=*c.dual.get(&ak).unwrap_or(&0)as i128;let irr=available(signature(&child.0,&e),&e).is_empty();if degree==3{k3n+=uses;k3q+=weight*q;if irr{k3i+=uses;k3iq+=weight*q}}else{k4n+=uses;k4q+=weight*q;if irr{k4i+=uses;k4iq+=weight*q}}}}
 }
 let mut extra=[0u8;1];assert_eq!(reader.read(&mut extra).unwrap(),0);assert_eq!((uses_sum,weight_sum,guards),(1_054_592,-2_407_088_221_087_334_400,5_766_376));assert_eq!((k3n,k3i,k3q,k3iq),(33_746_944,23_070_720,-4_310_060_400_861_511_680,-3_762_784_545_831_124_992));assert_eq!((k4n,k4i,k4q,k4iq),(63_275_520,53_606_400,460_536_785_434_312_704,440_759_609_843_318_784));
 let text=format!("{{\"status\":\"PASS_INDEPENDENT_HIDDEN_PROFILE_CHARGES\",\"profile_keys\":{},\"uses\":{},\"weight_sum_scaled\":\"{}\",\"abstract_literal_guards\":{},\"K3\":{{\"full_occurrences\":{},\"irreducible_occurrences\":{},\"full_charge_scaled\":\"{}\",\"irreducible_charge_scaled\":\"{}\"}},\"K4\":{{\"full_occurrences\":{},\"irreducible_occurrences\":{},\"full_charge_scaled\":\"{}\",\"irreducible_charge_scaled\":\"{}\"}},\"elapsed_seconds\":{:.6}}}\n",count,uses_sum,weight_sum,guards,k3n,k3i,k3q,k3iq,k4n,k4i,k4q,k4iq,begun.elapsed().as_secs_f64());std::fs::write(format!("{}results_hidden_profile_charge_referee.json",DIR),text.as_bytes()).unwrap();print!("{}",text)
}
