#!/usr/bin/env python3
"""Target-specific t-free degree-six blocks for the lex y10*t^2 dead row.

For each distinct t-free degree-six divisor q of the frozen y10 monomial, assemble
the exact top-y-degree fine-grade block generated by

  * every normalized mixed generator times every degree-two y monomial, and
  * every one of the 84,005 complete degree-five cells times one y variable.

Only providers in q's 24 site-colour port grade can enter.  Since q is
t-free, lower-y terms (and hence positive powers of t) are later in the
t-last order and cannot affect whether q is a top-degree-six pivot.

The actual residual is y^10*t^2.  Its total-degree-six divisors also include
y^5*t and y^4*t^2.  Those shorter encoded rows are explicitly counted below
but are NOT decided by the fine-grade computation in this file.
"""

from __future__ import annotations

from collections import Counter, defaultdict
from fractions import Fraction
from hashlib import sha256
from itertools import combinations, combinations_with_replacement
import importlib.util
import json
from pathlib import Path


HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
CENSUS_PATH = ROOT / "computations/verify_n8_chart26_weighted_degree6_census.py"
COMPLETE_PATH = ROOT / "computations/verify_n8_chart26_complete_degree5_buchberger.py"
RESULT_PATH = HERE / "results_y10_degree6_blocks.json"
TARGET_HEX = "0111202020494f4f50f8"


def require(condition, detail):
    if not condition:
        raise RuntimeError(detail)


def load(path, name):
    spec = importlib.util.spec_from_file_location(name, path)
    module = importlib.util.module_from_spec(spec)
    require(spec.loader is not None, f"cannot load {path}")
    spec.loader.exec_module(module)
    return module


def add_value(vector, row, value):
    output = vector.get(row, 0) + value
    if output:
        vector[row] = output
    else:
        vector.pop(row, None)


def weight(row, coordinates):
    answer = [0] * 24
    for identifier in row:
        i, j, a, b = coordinates[identifier]
        answer[3 * i + a] += 1
        answer[3 * j + b] += 1
    return tuple(answer)


def subtract(left, right):
    answer = tuple(a - b for a, b in zip(left, right))
    return answer if min(answer, default=0) >= 0 else None


def word_from_weight(value):
    colours = []
    for site in range(8):
        block = value[3 * site:3 * site + 3]
        if sum(block) != 1 or max(block) != 1:
            return None
        colours.append(block.index(1))
    return tuple(colours)


def encode_word(word):
    code = 0
    for value in word:
        code = 3 * code + value
    return code


def top_multiply(polynomial, multiplier, degree):
    answer = {}
    for row, coefficient in polynomial.items():
        if len(row) + len(multiplier) != degree:
            continue
        output = bytes(sorted(row + multiplier))
        add_value(answer, output, int(coefficient))
    return answer


def reduce_mod(vector, pivots, prime):
    work = {row: value % prime for row, value in vector.items()
            if value % prime}
    while work:
        lead = min(work)
        reducer = pivots.get(lead)
        if reducer is None:
            inverse = pow(work[lead], prime - 2, prime)
            return {row: value * inverse % prime for row, value in work.items()}
        scale = work[lead]
        for row, value in reducer.items():
            updated = (work.get(row, 0) - scale * value) % prime
            if updated:
                work[row] = updated
            else:
                work.pop(row, None)
    return {}


def reduce_Q(vector, pivots):
    work = {row: Fraction(value) for row, value in vector.items() if value}
    while work:
        lead = min(work)
        reducer = pivots.get(lead)
        if reducer is None:
            scale = work[lead]
            return {row: value / scale for row, value in work.items()}
        scale = work[lead]
        for row, value in reducer.items():
            updated = work.get(row, Fraction(0)) - scale * value
            if updated:
                work[row] = updated
            else:
                work.pop(row, None)
    return {}


def build_block(q, q_weight, originals, code_to_lead, degree5_by_weight,
                pair_by_weight, variable_by_weight, complete, coordinates):
    columns = []
    provenance = []

    # Original x degree-two multiplier.  The residual port weight must be a
    # one-hot output word, which identifies at most one mixed generator.
    for multiplier_weight, multipliers in pair_by_weight.items():
        residual_weight = subtract(q_weight, multiplier_weight)
        if residual_weight is None:
            continue
        word = word_from_weight(residual_weight)
        if word is None or len(set(word)) == 1:
            continue
        code = encode_word(word)
        polynomial = originals.get(code)
        if polynomial is None:
            continue
        for multiplier in multipliers:
            column = top_multiply(polynomial, multiplier, 6)
            if column:
                require(all(weight(row, coordinates) == q_weight for row in column),
                        "original provider left its fine grade")
                columns.append(column)
                provenance.append(("d4", code, multiplier.hex()))

    # Complete degree-five cell x one y variable.
    for variable_weight, variables in variable_by_weight.items():
        residual_weight = subtract(q_weight, variable_weight)
        if residual_weight is None:
            continue
        for lead, source in degree5_by_weight.get(residual_weight, ()):
            first, second, _distance = source
            lcm = bytes(sorted(set(code_to_lead[first]) | set(code_to_lead[second])))
            polynomial = complete.s_polynomial(
                lcm, first, second, originals, code_to_lead
            )
            for variable in variables:
                column = top_multiply(polynomial, bytes((variable,)), 6)
                if column:
                    require(all(weight(row, coordinates) == q_weight for row in column),
                            "degree-five provider left its fine grade")
                    columns.append(column)
                    provenance.append(("d5", first, second, f"{variable:02x}"))

    require(len(columns) == len(provenance), "provider provenance drift")
    return columns, provenance


def audit(mutate=False, exact=True):
    census = load(CENSUS_PATH, "target_d6_census")
    complete = census.COMPLETE
    D5 = census.D5
    originals, degree4, code_to_lead, degree5, _words = census.build_leads()
    require((len(degree4), len(degree5)) == (6558, 84005),
            "complete lower lead census changed")

    target = bytes.fromhex(TARGET_HEX)
    divisors = sorted({bytes(target[index] for index in positions)
                       for positions in combinations(range(len(target)), 6)})
    require(len(divisors) == 72, "target degree-six divisor count changed")
    coordinates = D5.COORDINATES
    off_variables = tuple(index for index in range(len(coordinates))
                          if D5.IS_OFF_SUPPORT[index])
    require(len(off_variables) == 240, "off-support variable count changed")

    variable_by_weight = defaultdict(list)
    for variable in off_variables:
        variable_by_weight[weight(bytes((variable,)), coordinates)].append(variable)
    pair_by_weight = defaultdict(list)
    for left, right in combinations_with_replacement(off_variables, 2):
        multiplier = bytes((left, right))
        pair_by_weight[weight(multiplier, coordinates)].append(multiplier)
    degree5_by_weight = defaultdict(list)
    for lead, source in degree5.items():
        degree5_by_weight[weight(lead, coordinates)].append((lead, source))

    records = []
    all_Q_pivots = []
    for q_index, q in enumerate(divisors):
        q_weight = weight(q, coordinates)
        columns, provenance = build_block(
            q, q_weight, originals, code_to_lead, degree5_by_weight,
            pair_by_weight, variable_by_weight, complete, coordinates
        )
        modular = {}
        modular_ranks = {}
        modular_q_pivot = {}
        for prime in (1009, 1013):
            pivots = {}
            for column in columns:
                reduced = reduce_mod(column, pivots, prime)
                if reduced:
                    pivots[min(reduced)] = reduced
            modular[str(prime)] = len(pivots)
            modular_ranks[str(prime)] = len(pivots)
            modular_q_pivot[str(prime)] = q in pivots

        q_pivot_Q = None
        Q_rank = None
        if exact:
            pivots_Q = {}
            for column in columns:
                reduced = reduce_Q(column, pivots_Q)
                if reduced:
                    pivots_Q[min(reduced)] = reduced
            Q_rank = len(pivots_Q)
            q_pivot_Q = q in pivots_Q
            all_Q_pivots.append(q_pivot_Q)
            require(all(rank == Q_rank for rank in modular_ranks.values()),
                    "modular/Q block rank mismatch")
            require(all(value == q_pivot_Q for value in modular_q_pivot.values()),
                    "modular/Q q-pivot mismatch")

        if mutate and q_index == 0:
            q_pivot_Q = True
        records.append({
            "q": q.hex(),
            "port_weight": list(q_weight),
            "provider_columns": len(columns),
            "provider_type_histogram": dict(sorted(Counter(
                item[0] for item in provenance
            ).items())),
            "row_union": len(set().union(*(set(column) for column in columns))
                             if columns else set()),
            "rank_mod_primes": modular_ranks,
            "q_pivot_mod_primes": modular_q_pivot,
            "Q_rank": Q_rank,
            "q_pivot_Q": q_pivot_Q,
        })

    if exact:
        require(not any(all_Q_pivots),
                "a degree-six divisor became a Q pivot")
    if mutate:
        require(not records[0]["q_pivot_Q"], "hostile pivot mutation survived")

    # Missing total-degree-six divisors.  The y^5*t and y^4*t^2 rows can be
    # touched because t hides one or two normalized support edges.  Enumerate
    # original-source incidences only as a guard against overclaiming the
    # t-free result; incidence is not a pivot certificate.
    shorter_d6_original_providers = []
    shorter_divisors = {}
    for encoded_degree in (4, 5):
        shorter_divisors[encoded_degree] = sorted({
            bytes(target[index] for index in positions)
            for positions in combinations(range(len(target)), encoded_degree)
        })
    require({key: len(value) for key, value in shorter_divisors.items()}
            == {4: 72, 5: 82}, "shorter d6 divisor counts changed")
    for encoded_degree, selected_divisors in sorted(shorter_divisors.items()):
      for q in selected_divisors:
        for code, polynomial in originals.items():
            for row, coefficient in polynomial.items():
                multiplier = census.FIRST.quotient(q, row)
                if multiplier is None or len(multiplier) > 2:
                    continue
                shorter_d6_original_providers.append({
                    "encoded_y_degree": encoded_degree,
                    "q": q.hex(),
                    "source_code": code,
                    "source_word": "".join(map(str, D5.decode_word(code))),
                    "generator_term": row.hex(),
                    "degree2_multiplier_y_part": multiplier.hex(),
                    "coefficient": int(coefficient),
                })
    require(shorter_d6_original_providers,
            "the shorter degree-six raw providers disappeared")
    first_short = min(shorter_d6_original_providers, key=lambda item: (
        item["encoded_y_degree"],
        item["q"], item["source_code"], item["generator_term"],
        item["degree2_multiplier_y_part"]
    ))
    require(first_short == {
        "encoded_y_degree": 4,
        "q": "01112049",
        "source_code": 2322,
        "source_word": "10012000",
        "generator_term": "2049",
        "degree2_multiplier_y_part": "0111",
        "coefficient": 1,
    }, "lex-first shorter degree-six provider changed")
    raw_literals = []
    for literal in D5.iter_word_terms(first_short["source_code"]):
        row = bytes(sorted(value for value in literal
                           if D5.IS_OFF_SUPPORT[value]))
        if row == bytes.fromhex(first_short["generator_term"]):
            raw_literals.append(bytes(literal))
    require(raw_literals == [bytes.fromhex("204987f3")],
            "first shorter degree-six provider lost its unique raw matching")
    omitted_support = [value for value in raw_literals[0]
                       if not D5.IS_OFF_SUPPORT[value]]
    require(omitted_support == [0x87, 0xF3]
            and [D5.COORDINATES[value] for value in omitted_support]
            == [(2, 5, 0, 0), (6, 7, 0, 0)],
            "first shorter degree-six provider lost its two anchors")

    target_coordinates = [list(coordinates[value]) for value in target]
    result = {
        "format": "n8-chart26-y10-dead-degree6-blocks-v1",
        "status": "T_FREE_DEGREE6_BLOCKS_EMPTY_SHORTER_DIVISORS_OPEN" if exact
                  else "MODULAR_SCREEN_ONLY",
        "target": TARGET_HEX,
        "target_coordinates": target_coordinates,
        "target_missing_physical_sites": sorted(
            set(range(8)) - {site for coordinate in target_coordinates
                             for site in coordinate[:2]}
        ),
        "t_free_degree6_divisors": len(divisors),
        "all_total_degree6_divisors_of_y10_t2": (
            len(divisors) + sum(map(len, shorter_divisors.values()))
        ),
        "distinct_port_fine_grades": len({tuple(record["port_weight"])
                                          for record in records}),
        "complete_lower_basis": {
            "degree4_leads": len(degree4),
            "degree5_leads": len(degree5),
        },
        "divisor_Q_pivots": sum(bool(record["q_pivot_Q"]) for record in records),
        "shorter_degree6_provider_guard": {
            "original_provider_columns": len({
                (item["source_code"], item["degree2_multiplier_y_part"])
                for item in shorter_d6_original_providers
            }),
            "divisors_touched": len({item["q"]
                                    for item in shorter_d6_original_providers}),
            "by_encoded_y_degree": {
                str(degree): {
                    "divisors": len(shorter_divisors[degree]),
                    "divisors_touched": len({item["q"] for item in
                                              shorter_d6_original_providers
                                              if item["encoded_y_degree"] == degree}),
                    "provider_columns": len({
                        (item["source_code"], item["degree2_multiplier_y_part"])
                        for item in shorter_d6_original_providers
                        if item["encoded_y_degree"] == degree
                    }),
                } for degree in (4, 5)
            },
            "lex_first": first_short,
            "raw_matching": raw_literals[0].hex(),
            "implicit_t_support_cells": [{
                "id": f"{value:02x}",
                "coordinate": list(D5.COORDINATES[value]),
            } for value in omitted_support],
            "scope": (
                "exact original-generator provider incidence only; the shorter "
                "d6 divisors require a target-rooted collision/Macaulay test"
            ),
        },
        "records": records,
        "theorem": (
            "No t-free y6 divisor q of the lex y10*t2 dead monomial is a pivot "
            "in its exact top-y-degree fine-grade block generated by "
            "all original-degree4 times degree2 and all complete-degree5 times "
            "degree1 columns. This does not decide the y5*t or y4*t2 divisors."
        ),
        "scope": (
            "exact t-free top-y-degree-six pivot test after the complete d4/d5 "
            "basis; the 154 shorter encoded total-degree-six divisors, degree7+ "
            "layers, and full y10*t2 residual remain undecided"
        ),
        "source_sha256": {
            str(CENSUS_PATH.relative_to(ROOT)): sha256(CENSUS_PATH.read_bytes()).hexdigest(),
            str(COMPLETE_PATH.relative_to(ROOT)): sha256(COMPLETE_PATH.read_bytes()).hexdigest(),
        },
    }
    result["logical_sha256"] = sha256(json.dumps(
        result, sort_keys=True, separators=(",", ":")
    ).encode("ascii")).hexdigest()
    return result


def main():
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("--modular-only", action="store_true")
    parser.add_argument("--mutate", action="store_true")
    args = parser.parse_args()
    result = audit(mutate=args.mutate, exact=not args.modular_only)
    if not args.mutate:
        RESULT_PATH.write_text(json.dumps(result, indent=2, sort_keys=True) + "\n",
                               encoding="ascii")
    print(json.dumps({
        "status": result["status"],
        "t_free_degree6_divisors": result["t_free_degree6_divisors"],
        "divisor_Q_pivots": result["divisor_Q_pivots"],
        "logical_sha256": result["logical_sha256"],
    }, sort_keys=True))


if __name__ == "__main__":
    main()
