//! Independent distributed replay of every nonzero continuation in the
//! producer's 257-record witness grid.  This explicitly traverses K19->K21.
mod audit {
#![allow(dead_code,unused_imports)]
include!("../unaudited-codex-orbit0-filtered-k18-charge-2026-08-23/run_k18_charge.rs");
use std::fs::File;
use std::io::{Read,Seek,SeekFrom};
const U:i128=400_591_699_200;
const N:u64=24_097_095;
const INPUT:&str="computations/unaudited-codex-orbit0-filtered-k16-run-2026-08-23/checkpoint_direct_k16.bin";
const TSV:&str="computations/unaudited-codex-orbit0-k21-direct-k16-32-2026-08-24/results_k21_direct_k16_32.json.samples.tsv";
const OUT:&str="computations/unaudited-codex-orbit0-k21-direct-k16-32-2026-08-24/results_nonzero_k19_k21_referee.json";
fn rowhex(r:&Row)->String{r.0.iter().map(|x|format!("{:02x}",x)).collect()}
pub fn run(){let begun=Instant::now();let e=parse();assert_eq!(e.piv.len(),78);assert!(e.piv.iter().all(|p|p.iter().map(|&x|x as usize).sum::<usize>()==4));assert!(e.tails.iter().flatten().filter(|_|true).count()>0);for p in 0..78{assert_eq!(e.tails[p][0].len(),12);assert_eq!(e.tails[p][1].len(),32);assert!(e.tails[p][0].iter().all(|t|tsig(t,&e).iter().map(|&x|x as usize).sum::<usize>()==2));assert!(e.tails[p][1].iter().all(|t|tsig(t,&e).iter().map(|&x|x as usize).sum::<usize>()==1))}
 let text=std::fs::read_to_string(TSV).unwrap();let mut lines=text.lines();assert_eq!(lines.next().unwrap(),"sample_ordinal\trecord_index\tK16_row\tcoefficient\tm1\tp1\tpivotable_K19_children\tp2_uses\tK21_children\tcharge_per_source_coefficient_scaled_U");let mut input=File::open(INPUT).unwrap();let mut h=[0;16];input.read_exact(&mut h).unwrap();assert_eq!(&h[..8],b"K16DIR1\0");assert_eq!(u64::from_le_bytes(h[8..].try_into().unwrap()),N);
 let(mut witnesses,mut first,mut last,mut k3,mut k19,mut p2n,mut k21,mut comparisons,mut weighted_charge)=(0u64,N,0u64,0u64,0u64,0u64,0u64,0u64,0i128);let mut denom=std::collections::BTreeMap::<(u8,u8),u64>::new();
 for line in lines{let f:Vec<_>=line.split('\t').collect();assert_eq!(f.len(),10);let expected_p2=f[7].parse::<u64>().unwrap();if expected_p2==0{continue}let ordinal=f[0].parse::<u64>().unwrap();let index=f[1].parse::<u64>().unwrap();assert_eq!(index,ordinal*(N-1)/256);input.seek(SeekFrom::Start(16+32*index)).unwrap();let mut z=[0;32];input.read_exact(&mut z).unwrap();let mut rr=[0;24];rr.copy_from_slice(&z[..24]);let row=Row(rr);let v=i64::from_le_bytes(z[24..].try_into().unwrap());assert_eq!(rowhex(&row),f[2]);assert_eq!(v,f[3].parse::<i64>().unwrap());let s1=sig(&row,&e);assert_eq!(s1.iter().map(|&x|x as usize).sum::<usize>(),8);let ps1=avail(s1,&e);let m1=ps1.len();let p1=f[5].parse::<usize>().unwrap();assert_eq!(m1,f[4].parse::<usize>().unwrap());assert_eq!(p1,ps1[0]);let(mut zpiv,mut zuses,mut zchildren,mut zcharge)=(0u64,0u64,0u64,0i128);
  for t1 in &e.tails[p1][1]{k3+=1;let s2=child_sig(s1,p1,t1,&e);assert_eq!(s2.iter().map(|&x|x as usize).sum::<usize>(),5);let row19=replace(&row,&e.anchors[p1],t1);assert_eq!(sig(&row19,&e),s2);let ps2=avail(s2,&e);if ps2.is_empty(){continue}zpiv+=1;k19+=1;let m2=ps2.len();assert_eq!(U%((m1*m2)as i128),0);*denom.entry((m1 as u8,m2 as u8)).or_default()+=1;let unit=U/((m1*m2)as i128);for p2 in ps2{zuses+=1;p2n+=1;let prof=profile(&row19,p2,&e);for t2 in &e.tails[p2][0]{let predicted=child_sig(s2,p2,t2,&e);assert_eq!(predicted.iter().map(|&x|x as usize).sum::<usize>(),3);assert!(avail(predicted,&e).is_empty());let row21=replace(&row19,&e.anchors[p2],t2);assert_eq!(sig(&row21,&e),predicted);assert_eq!(profile(&row19,p2,&e),prof);let q=charge(&row21,&e)as i128;zchildren+=1;k21+=1;comparisons+=1;zcharge+=unit*q}}
  }
  assert!(zpiv>0&&zuses>0&&zchildren>0);assert_eq!(zpiv,f[6].parse::<u64>().unwrap());assert_eq!(zuses,expected_p2);assert_eq!(zchildren,f[8].parse::<u64>().unwrap());assert_eq!(zcharge,f[9].parse::<i128>().unwrap());weighted_charge+=(v as i128)*zcharge;witnesses+=1;first=first.min(index);last=last.max(index)
 }
 assert_eq!(witnesses,91);assert_eq!(k3,32*witnesses);assert_eq!(k21,12*p2n);assert_eq!(comparisons,k21);let hist=denom.iter().map(|(&(a,b),v)|format!("\"{}_{}\":{}",a,b,v)).collect::<Vec<_>>().join(",");let out=format!("{{\n  \"status\":\"PASS_INDEPENDENT_DISTRIBUTED_NONZERO_K19_K21_REPLAY\",\n  \"source_grid_records\":257,\n  \"nonzero_continuation_witnesses\":{},\n  \"first_record_index\":{},\n  \"last_record_index\":{},\n  \"K3_tails_replayed\":{},\n  \"pivotable_K19_children\":{},\n  \"p2_uses\":{},\n  \"literal_terminal_K21_children\":{},\n  \"literal_child_signature_and_charge_checks\":{},\n  \"sample_weighted_charge_scaled_U\":\"{}\",\n  \"m1_m2_hist\":{{{}}},\n  \"all_U_divisions_exact\":true,\n  \"all_K21_children_terminal\":true,\n  \"producer_ledger_continuation_fields_match\":true,\n  \"elapsed_seconds\":{:.6}\n}}\n",witnesses,first,last,k3,k19,p2n,k21,comparisons,weighted_charge,hist,begun.elapsed().as_secs_f64());std::fs::write(OUT,&out).unwrap();print!("{}",out)}
}
fn main(){audit::run()}
