//! Independent literal replay of 257 distributed prefix-million witnesses.
mod referee {
include!("../unaudited-codex-orbit0-hidden-k16-children-prefix-2026-08-23/run_hidden_children_prefix.rs");
const INPUT:&str="computations/unaudited-codex-orbit0-hidden-k16-k2-full-orbit-2026-08-23/checkpoint_k18_22_pivotable.bin";
const TSV:&str="computations/unaudited-codex-orbit0-k23-hidden-collected-k18-2026-08-24/results_prefix1000000.json.samples.tsv";
const OUT:&str="computations/unaudited-codex-orbit0-k23-hidden-collected-k18-2026-08-24/results_k23_hidden_prefix1000000_referee.json";
const N:u64=1_000_000;
fn hex(row:&Row)->String{row.0.iter().map(|x|format!("{:02x}",x)).collect()}
pub fn run(){let begun=Instant::now();let e=parse();let c=cenv();let mut f=File::open(INPUT).unwrap();let raw=std::fs::read_to_string(TSV).unwrap();let mut lines=raw.lines();assert_eq!(lines.next().unwrap(),"input_index\tK18_row\tretained_K16_pair_witness\tweight_before_p3_scaled_U\tp2\tt2\tpair_uses\torbit\tstabilizer\tm2\tm3\tselected_p3_uses\tpivotable_K20_children\tselected_p4_uses\tterminal_K3_children\tliteral_charge_scaled_U");let(mut rows,mut k20,mut terminals,mut charge_sum)=(0u64,0u64,0u64,0i128);
 for line in lines{let x:Vec<_>=line.split('\t').collect();assert_eq!(x.len(),16);let idx=x[0].parse::<u64>().unwrap();assert_eq!(idx,rows*(N-1)/256);f.seek(SeekFrom::Start(80+80*idx)).unwrap();let mut rec=[0u8;80];f.read_exact(&mut rec).unwrap();assert_eq!(rec[78],1);let mut rr=[0;24];rr.copy_from_slice(&rec[..24]);let row=Row(rr);let mut ww=[0;24];ww.copy_from_slice(&rec[40..64]);assert_eq!(hex(&row),x[1]);assert_eq!(hex(&Row(ww)),x[2]);let w=i128::from_le_bytes(rec[24..40].try_into().unwrap());assert_eq!(w,x[3].parse().unwrap());assert_eq!(rec[64],x[4].parse().unwrap());assert_eq!(rec[65],x[5].parse().unwrap());assert_eq!(u64::from_le_bytes(rec[66..74].try_into().unwrap()),x[6].parse().unwrap());assert_eq!(u16::from_le_bytes(rec[74..76].try_into().unwrap()),x[7].parse().unwrap());assert_eq!(u16::from_le_bytes(rec[76..78].try_into().unwrap()),x[8].parse().unwrap());let m2=rec[79]as usize;assert_eq!(m2,x[9].parse().unwrap());let s18=signature(&row.0,&e);assert_eq!(s18.iter().map(|&z|z as usize).sum::<usize>(),6);let ps3=available(s18,&e);let m3=ps3.len();assert_eq!(m3,x[10].parse().unwrap());assert_eq!(m3,x[11].parse().unwrap());assert_eq!(w%(m3 as i128),0);assert_eq!(U%((m2*m3)as i128),0);let(mut mids,mut p4n,mut children,mut q)=(0u64,0u64,0u64,0i128);
  for p3 in ps3{for t1 in &e.all_k2[p3]{let row20=replace_anchor(&row,&e.anchors[p3],t1);let s20=signature(&row20.0,&e);assert_eq!(s20.iter().map(|&z|z as usize).sum::<usize>(),4);let ps4=available(s20,&e);if ps4.is_empty(){continue}assert_eq!(ps4.len(),1);mids+=1;let m4=ps4.len();assert_eq!(U%((m2*m3*m4)as i128),0);assert_eq!(w%((m3*m4)as i128),0);let weight=w/((m3*m4)as i128);for p4 in ps4{p4n+=1;for t3 in &e.all_k3[p4]{let child=replace_anchor(&row20,&e.anchors[p4],t3);let s23=signature(&child.0,&e);assert_eq!(s23.iter().map(|&z|z as usize).sum::<usize>(),1);assert!(available(s23,&e).is_empty());q+=weight*(*c.dual.get(&literal_ckey(&child,&c)).unwrap_or(&0)as i128);children+=1}}}}
  assert_eq!(mids,x[12].parse().unwrap());assert_eq!(p4n,x[13].parse().unwrap());assert_eq!(children,x[14].parse().unwrap());assert_eq!(q,x[15].parse().unwrap());rows+=1;k20+=mids;terminals+=children;charge_sum+=q;
 }
 assert_eq!(rows,257);assert_eq!(terminals,32*k20);let text=format!("{{\n  \"status\":\"PASS_INDEPENDENT_257_LITERAL_H18PIV2_K23_SINGLETON_PREFIX_REFEREE\",\n  \"strict_id\":\"D14:222|R:2-2-2-3\",\n  \"source_interval\":[0,{}],\n  \"distributed_parents\":{},\n  \"first_index\":0,\n  \"last_index\":{},\n  \"literal_pivotable_K20_children\":{},\n  \"literal_terminal_K23_children\":{},\n  \"sample_charge_scaled_U\":\"{}\",\n  \"all_divisions_exact\":true,\n  \"all_K23_children_terminal\":true,\n  \"source_provenance_replayed\":true,\n  \"elapsed_seconds\":{:.6},\n  \"scope\":\"257 distributed prefix-million literal parents only; no full scalar rerun, rows, or K24\"\n}}\n",N,rows,N-1,k20,terminals,charge_sum,begun.elapsed().as_secs_f64());std::fs::write(OUT,&text).unwrap();print!("{}",text)}
}
fn main(){referee::run()}
