//! Source-linear grouped direct-K15 K22 fold with four strict recurrence sinks.
mod fold{
#![allow(dead_code,unused_imports)]
include!("../unaudited-codex-orbit0-filtered-k18-charge-2026-08-23/run_k18_charge.rs");
use std::collections::BTreeMap;use std::fs::rename;
const U21:i128=400_591_699_200;const SLICES:usize=485;const HPS:u64=13_824;
const NAMES:[&str;4]=["D15:{223,232,322}|R:4-3","D15:{223,232,322}|R:2-2-3","D15:{223,232,322}|R:2-3-2","D15:{223,232,322}|R:3-2-2"];
const IDS:[[&str;3];4]=[["D15:223|R:4-3","D15:232|R:4-3","D15:322|R:4-3"],["D15:223|R:2-2-3","D15:232|R:2-2-3","D15:322|R:2-2-3"],["D15:223|R:2-3-2","D15:232|R:2-3-2","D15:322|R:2-3-2"],["D15:223|R:3-2-2","D15:232|R:3-2-2","D15:322|R:3-2-2"]];
#[derive(Clone,Default)]struct St{heads:u64,mass:i128,l1:i128,piv:[u64;3],cand:[u64;3],pivable:[u64;2],terminal:u64,charge:i128,hist:BTreeMap<u16,u64>}
impl St{fn add(&mut self,x:St){self.heads+=x.heads;self.mass+=x.mass;self.l1+=x.l1;for i in 0..3{self.piv[i]+=x.piv[i];self.cand[i]+=x.cand[i]}for i in 0..2{self.pivable[i]+=x.pivable[i]}self.terminal+=x.terminal;self.charge+=x.charge;for(k,v)in x.hist{*self.hist.entry(k).or_default()+=v}}}
type Plan=Vec<(u8,[u8;12],Vec<usize>)>;
fn row(r:&R8,packet:usize,a:&[u8;4],b:&[u8;4],c:&[u8;4])->Row{match packet{0=>make(r,c,a,b),1=>make(r,a,c,b),2=>make(r,a,b,c),_=>unreachable!()}}
#[allow(clippy::too_many_arguments)]fn walk(row:&Row,s:[u8;12],ps:Vec<usize>,positive:i128,degs:&[usize],d:usize,den:&mut[usize;3],st:&mut St,plans:&mut HashMap<([u8;12],u8,u8),Plan>,terminal:&mut HashMap<RKey,(i64,i64,u64,u64)>,e:&E){let m=ps.len();assert!(m>0);den[d]=m;st.piv[d]+=m as u64;let degree=degs[d];for p in ps{if d+1==degs.len(){let n=e.tails[p][degree-2].len()as u64;st.cand[d]+=n;let product=den[..=d].iter().product::<usize>();assert_eq!(U21%(product as i128),0);let sign=if degs.len()%2==0{-positive}else{positive};let unit=sign*U21/(product as i128);let z=resp(row,s,p,degree,e,terminal);assert_eq!((z.2,z.3),(n,n));assert_eq!(z.0,z.1);st.terminal+=n;st.charge+=unit*(z.0 as i128);*st.hist.entry(product as u16).or_default()+=1}else{let tails=e.tails[p][degree-2].len()as u64;st.cand[d]+=tails;let key=(s,p as u8,degree as u8);let plan=plans.entry(key).or_insert_with(||{let mut v=Vec::new();for(ti,t)in e.tails[p][degree-2].iter().enumerate(){let sc=child_sig(s,p,t,e);let q=avail(sc,e);if !q.is_empty(){v.push((ti as u8,sc,q))}}v}).clone();st.pivable[d]+=plan.len()as u64;for(ti,sc,q)in plan{let child=replace(row,&e.anchors[p],&e.tails[p][degree-2][ti as usize]);assert_eq!(sig(&child,e),sc);walk(&child,sc,q,positive,degs,d+1,den,st,plans,terminal,e)}}}}
fn worker(e:Arc<E>,start:usize,end:usize,step:usize)->[St;4]{let mut out:[St;4]=std::array::from_fn(|_|St::default());let mut plans=HashMap::new();for ri in(start..end).step_by(step){let r=&e.records[ri];let positive=(r.coefficient as i128)*(r.size as i128);let mut terminal=HashMap::new();for packet in 0..3{let o:Vec<_>=(0..3).filter(|&x|x!=packet).collect();for a in &e.factor[o[0]][0]{for b in &e.factor[o[1]][0]{for c in &e.factor[packet][1]{let h=row(r,packet,a,b,c);let s=sig(&h,&e);assert_eq!(s.iter().map(|&x|x as usize).sum::<usize>(),9);let ps=avail(s,&e);assert!(!ps.is_empty());for(k,degs)in [&[4usize,3][..],&[2usize,2,3][..],&[2usize,3,2][..],&[3usize,2,2][..]].iter().enumerate(){out[k].heads+=1;out[k].mass-=positive;out[k].l1+=positive.abs();walk(&h,s,ps.clone(),positive,degs,0,&mut[0;3],&mut out[k],&mut plans,&mut terminal,&e)}}}}}}out}
fn hist(h:&BTreeMap<u16,u64>)->String{h.iter().map(|(k,v)|format!("\"{}\":{}",k,v)).collect::<Vec<_>>().join(",")}
fn js(k:usize,s:&St)->String{let ids=IDS[k].iter().map(|x|format!("\"{}\"",x)).collect::<Vec<_>>().join(",");format!("\"{}\":{{\"ids\":[{}],\"individual_id_charges\":null,\"source_heads\":{},\"source_mass\":\"{}\",\"source_l1\":\"{}\",\"stage_pivot_uses\":[{},{},{}],\"stage_tail_candidates\":[{},{},{}],\"stage_pivotable_children\":[{},{}],\"terminal_K22_occurrences\":{},\"full_occurrences\":{},\"irreducible_occurrences\":{},\"full_charge_scaled_U\":\"{}\",\"irreducible_charge_scaled_U\":\"{}\",\"denominator_product_hist\":{{{}}}}}",NAMES[k],ids,s.heads,s.mass,s.l1,s.piv[0],s.piv[1],s.piv[2],s.cand[0],s.cand[1],s.cand[2],s.pivable[0],s.pivable[1],s.terminal,s.terminal,s.terminal,s.charge,s.charge,hist(&s.hist))}
pub fn run(){let args:Vec<_>=std::env::args().collect();let(mut begin,mut count,mut workers)=(0usize,SLICES,8usize);let mut output="computations/unaudited-codex-orbit0-k22-direct-k15-four-sink-2026-08-24/results_k22_direct_k15_four_sink.json".to_string();let mut i=1;while i<args.len(){match args[i].as_str(){"--start-slice"=>{begin=args[i+1].parse().unwrap();i+=2},"--count-slices"=>{count=args[i+1].parse().unwrap();i+=2},"--workers"=>{workers=args[i+1].parse().unwrap();i+=2},"--output"=>{output=args[i+1].clone();i+=2},_=>panic!("bad arg")}}assert!(begin<=SLICES&&count>0&&count<=SLICES-begin&&(1..=8).contains(&workers));let begun=Instant::now();let e=Arc::new(parse());let mut jobs=Vec::new();for w in 0..workers{let x=e.clone();jobs.push(thread::spawn(move||worker(x,begin+w,begin+count,workers)))}let mut all:[St;4]=std::array::from_fn(|_|St::default());for j in jobs{let z=j.join().unwrap();for k in 0..4{all[k].add(z[k].clone())}}for s in &all{assert_eq!(s.heads,count as u64*HPS);assert_eq!((s.mass,s.l1),(all[0].mass,all[0].l1));assert_eq!(s.terminal,s.cand[if s.piv[2]>0{2}else{1}]);assert!(s.hist.keys().all(|&x|U21%(x as i128)==0))}if begin==0&&count==SLICES{for s in &all{assert_eq!((s.heads,s.mass,s.l1),(6_704_640,322_486_272,3_085_516_800))}assert_eq!((all[1].piv[0],all[1].cand[0],all[1].pivable[0],all[1].piv[1],all[1].cand[1]),(55_934_080,671_208_960,451_445_760,1_876_057_600,22_512_691_200))}let elapsed=begun.elapsed().as_secs_f64();let projected=elapsed*SLICES as f64/count as f64;let status=if begin==0&&count==SLICES{"PASS_COMPLETE_GROUPED_DIRECT_K15_FOUR_SINK_K22_CHARGE"}else{"PASS_BOUNDED_GROUPED_DIRECT_K15_FOUR_SINK_K22_GATE"};let text=format!("{{\n  \"status\":\"{}\",\n  \"scale_U\":\"{}\",\n  \"slice_interval\":[{},{}],\n  \"source_slices\":{},\n  \"workers\":{},\n  \"sinks\":{{{},{},{},{}}},\n  \"packet_grouping_guard\":\"packet witnesses 322/232/223 retained only as grouped source classes; no individual scalar split\",\n  \"terminality\":\"every K22 output has anchor mass 2 below pivot mass 4, so full equals irreducible\",\n  \"scope\":\"four separate grouped K22 sinks covering exactly 12 IDs; no rows, K23, or K24\",\n  \"elapsed_seconds\":{:.6},\n  \"projected_full_seconds\":{:.6}\n}}\n",status,U21,begin,begin+count,count,workers,js(0,&all[0]),js(1,&all[1]),js(2,&all[2]),js(3,&all[3]),elapsed,projected);let tmp=format!("{}.tmp",output);std::fs::write(&tmp,&text).unwrap();rename(tmp,&output).unwrap();print!("{}",text)}
}
fn main(){fold::run()}
