#!/usr/bin/env python3
"""Emit a core refutation as pure Lean literals, for KERNEL-checked replay.

UNAUDITED — lane L1.

WHY
---
`Std.Tactic.BVDecide.Reflect.verifyCert cnf (cert : String)` parses the LRAT
with `Std.Tactic.BVDecide.LRAT.Parser`, whose `parseActions`, `parseLit`,
`manyTillZero`, `manyTillNegOrZero` are all `partial def`. A `partial def` has
no equational theory, so the KERNEL cannot reduce it: `decide` on `verifyCert`
gets stuck (not merely slow) no matter how small the certificate is. That, and
not size, is why the kernel route looked closed.

`LRAT.check_sound (lratProof : Array IntAction) (cnf : CNF Nat)` takes the
proof ALREADY PARSED. Emitting the CNF and the certificate as Lean literals
therefore removes every `partial` definition from the reduction path, leaving
only `LRAT.check`, which is ordinary structural/well-founded code.

This script emits, for one orbit:
    def coreCNF   : CNF Nat            -- List (List (Nat x Bool))
    def coreProof : Array LRAT.IntAction
    theorem coreUnsat : coreCNF.Unsat := LRAT.check_sound _ _ (by decide)

DIMACS literal `l` maps to `(l.natAbs - 1, l > 0)`, matching the convention of
`Std.Tactic.BVDecide.LRAT.Internal.intActionToDefaultClauseAction`.

Usage: python3 gen_lean_core.py <orbit> <out.lean> [--native]
"""
from __future__ import annotations

import os
import sys

LANE = ("/Users/rishi/workplace/krenn-conjecture/computations/"
        "unaudited-lean-l1-2026-08-20")
CORES = f"{LANE}/cores/n8z0"


def read_cnf(path):
    cls = []
    for line in open(path):
        line = line.strip()
        if not line or line[0] in "cp":
            continue
        toks = line.split()
        assert toks[-1] == "0", line
        cls.append([int(t) for t in toks[:-1]])
    return cls


def read_lrat(path):
    """Parse LRAT text into (kind, ...) tuples. Fails loudly on RAT steps."""
    acts = []
    for line in open(path):
        toks = line.split()
        if not toks:
            continue
        ident = int(toks[0])
        if len(toks) > 1 and toks[1] == "d":
            ids = [int(t) for t in toks[2:]]
            assert ids[-1] == 0, line
            acts.append(("del", ids[:-1]))
            continue
        rest = [int(t) for t in toks[1:]]
        z = rest.index(0)
        lits, tail = rest[:z], rest[z + 1:]
        assert tail and tail[-1] == 0, line
        hints = tail[:-1]
        if any(h < 0 for h in hints):
            raise SystemExit(
                f"RAT step in {path}: negative hint. This emitter handles "
                f"RUP-only proofs; extend it before using this certificate.")
        acts.append(("add", ident, lits, hints))
    return acts


def lit(l: int) -> str:
    return f"({abs(l) - 1}, {'true' if l > 0 else 'false'})"


def main():
    orbit = int(sys.argv[1])
    out = sys.argv[2]
    native = "--native" in sys.argv
    cnf = read_cnf(f"{CORES}/core_{orbit}.cnf")
    acts = read_lrat(f"{CORES}/core_{orbit}.lrat")

    tac = "native_decide" if native else "decide"
    L = []
    L.append("/-")
    L.append("UNAUDITED — lane L1, generated by encoder/gen_lean_core.py.")
    L.append(f"Kernel-checked refutation of orbit {orbit} of the 87-case ledger.")
    L.append("")
    L.append("The CNF is the drat-trim-extracted UNSAT core of")
    L.append(f"  canonical/n8z0/n8z0k4_{orbit}.cnf")
    L.append("and every one of its clauses occurs in that file (checked by")
    L.append("encoder/emit_cores.py, which refuses to emit otherwise). A subset of")
    L.append("an unsatisfiable set being unsatisfiable is all that is used, so the")
    L.append("core never strengthens the claim.")
    L.append("")
    L.append("No `partial` definition appears on the reduction path: the")
    L.append("certificate is supplied already parsed, as an `Array IntAction`.")
    L.append("-/")
    L.append("import Std.Tactic.BVDecide.Reflect")
    L.append("")
    L.append(f"namespace L1Core{orbit}")
    L.append("")
    L.append("open Std.Sat")
    L.append("open Std.Tactic.BVDecide")
    L.append("")
    L.append(f"/-- The UNSAT core of orbit {orbit}: "
             f"{len(cnf)} clauses. -/")
    L.append("def coreCNF : CNF Nat :=")
    body = ",\n   ".join("[" + ", ".join(lit(l) for l in c) + "]" for c in cnf)
    L.append("  [" + body + "]")
    L.append("")
    L.append(f"/-- The LRAT certificate, pre-parsed: {len(acts)} actions. -/")
    L.append("def coreProof : Array LRAT.IntAction :=")
    rows = []
    for a in acts:
        if a[0] == "del":
            rows.append(f".del #[{', '.join(map(str, a[1]))}]")
        else:
            _, ident, lits, hints = a
            hs = f"#[{', '.join(map(str, hints))}]"
            if not lits:
                rows.append(f".addEmpty {ident} {hs}")
            else:
                cs = f"#[{', '.join(map(str, lits))}]"
                rows.append(f".addRup {ident} {cs} {hs}")
    L.append("  #[" + ",\n    ".join(rows) + "]")
    L.append("")
    L.append("/-- The refutation. -/")
    L.append("theorem coreUnsat : coreCNF.Unsat :=")
    L.append(f"  LRAT.check_sound coreProof coreCNF (by {tac})")
    L.append("")
    L.append(f"end L1Core{orbit}")
    open(out, "w").write("\n".join(L) + "\n")
    print(f"orbit {orbit}: {len(cnf)} clauses, {len(acts)} actions -> {out} "
          f"({os.path.getsize(out)} bytes, tactic={tac})")


if __name__ == "__main__":
    main()
