#!/usr/bin/env python3
import hashlib,json,os
from pathlib import Path
HERE=Path(__file__).resolve().parent
def sha(path):return hashlib.sha256(path.read_bytes()).hexdigest()
def atomic(path,value):tmp=path.with_suffix(path.suffix+'.tmp');tmp.write_text(json.dumps(value,indent=2,sort_keys=True)+'\n');os.replace(tmp,path)
P={'ledger':'fa301fd4d1e61626781cedd3ecb362189671b042c9cba8cfbe68977bb79ceb38','future':'18b7cae58e965187bcbb97ef7a319aacd92fccb6be4010d9630caad83ef77e75','verifier':'fc44d47caef2915dc8cf7dc384d544e8c858e4be8de372b08d01a30abb3b90eb','normalizer':'08f1f5c834499939a06635d7fd95bf4fddb12d9eae047e9ecb3a15dcf87a661f','runner':'959ab7cfa85ddf23f328ae03edeaefabc0a775ede98b4768953b46c91fe0022a','hostiles':'b15cdacc3ff88d14b43760f430bd9ba327fe332d1d34a99d1b5ffb989dcfcc90'};SELECTED=list(range(126,162));CLOSED=list(range(126))
assert sha(HERE/'source_ledger.json')==P['ledger'] and sha(HERE/'future_dependencies.json')==P['future'] and sha(HERE/'dependency_verifier.py')==P['verifier'] and sha(HERE/'normalize_dependencies.py')==P['normalizer'] and sha(HERE/'run_groups126_161.py')==P['runner'] and sha(HERE/'results_hostile_tests.json')==P['hostiles'];ledger=json.loads((HERE/'source_ledger.json').read_text());future=json.loads((HERE/'future_dependencies.json').read_text());assert ledger['selection']['selected_group_ids']==SELECTED and len(ledger['lanes'])==36 and all(d['manifest_sha256'] is d['result_sha256'] is None and d['satisfied'] is False for d in future['dependencies'])
plan={'schema':'KRENN_X5_REP4_GROUPS126_161_EXACT_Q_CONDITIONAL_HELD_V1','status':'HELD_THREE_FUTURE_PASSES_ABSENT_ZERO_RUN','selection':ledger['selection'],'authoritative_census':ledger['authoritative_census'],'future_dependencies':{'path':'future_dependencies.json','sha256':P['future'],'dependency_pairs':3,'null_hashes':6,'artifacts_absent':6,'satisfied':False,'normalized_dependencies_present':False},'verifier':{'path':'dependency_verifier.py','sha256':P['verifier'],'reopens_all_six_artifacts':True,'replays_all_manifest_entries':True,'verifies_terminal_schema_status_groups':True,'derives_exact_union_0_125':True},'normalizer':{'path':'normalize_dependencies.py','sha256':P['normalizer']},'source_ledger':{'path':'source_ledger.json','sha256':P['ledger'],'source_count':36,'total_bytes':sum(x['source_bytes'] for x in ledger['lanes'])},'lanes':ledger['lanes'],'runner':{'path':'run_groups126_161.py','sha256':P['runner'],'strict_sequential':True,'direct_libproc_process_group_rss':True,'fail_closed_rusage':True,'atomic_per_lane_results':True,'single_use_batch_marker':True},'hostiles':{'path':'results_hostile_tests.json','sha256':P['hostiles'],'passed':21,'includes_fabricated_stale_normalized':True},'execution':{'native_wall_seconds_each':240,'wrapper_wall_seconds_each':250,'rss_cap_bytes_each':8589934592,'maximum_lane_count':36,'order':SELECTED,'parallel':False,'skip':False,'reorder':False,'relaunch':False,'stop_first':True},'scope':{'representative':'rep4 only','final_canonical_groups':True,'solver_launches':0,'results':0,'attempts':0,'acceptances':0,'clearances':0,'groups_newly_closed':0,'mathematical_coverage_added':False,'rep4_closed':False}};atomic(HERE/'held_schedule.json',plan)
hex64={'type':'string','pattern':'^[0-9a-f]{64}$'};a={'schema':{'const':'KRENN_X5_REP4_GROUPS126_161_EXACT_Q_INDEPENDENT_ACCEPTANCE_V1'},'status':{'const':'PASS_APPROVE_CONDITIONAL_REP4_GROUPS126_161_ONLY'},'held_manifest_sha256':hex64,'source_ledger_sha256':{'const':P['ledger']},'dependency_verifier_sha256':{'const':P['verifier']},'normalized_dependencies_sha256':hex64,'runner_sha256':{'const':P['runner']},'required_closed_union':{'const':CLOSED},'selected_group_ids':{'const':SELECTED},'maximum_lane_count':{'const':36},'exact_Q_authorized':{'const':True},'parallel_authorized':{'const':False},'skip_reorder_relaunch_authorized':{'const':False}};c={'schema':{'const':'KRENN_X5_REP4_GROUPS126_161_EXACT_Q_EXPLICIT_CLEARANCE_V1'},'status':{'const':'CLEARED_CONDITIONAL_REP4_GROUPS126_161_ONLY'},'held_manifest_sha256':hex64,'independent_referee_acceptance_sha256':hex64,'source_ledger_sha256':{'const':P['ledger']},'dependency_verifier_sha256':{'const':P['verifier']},'normalized_dependencies_sha256':hex64,'runner_sha256':{'const':P['runner']},'singular_sha256':{'const':'9436b32ff7565719240230de8a6fb1d27af5e65f0ca4c9c5b756a77e82409b88'},'gtimeout_sha256':{'const':'1e26c50fa8c439fe1f4e6c6edd106e95030e16582c1c8c32e73d8a889cdf5b95'},'required_closed_union':{'const':CLOSED},'selected_group_ids':{'const':SELECTED},'native_wall_seconds_each':{'const':240},'wrapper_wall_seconds_each':{'const':250},'rss_cap_bytes_each':{'const':8589934592},'no_overlap_confirmed':{'const':True},'maximum_lane_count':{'const':36},'parallel_authorized':{'const':False},'skip_reorder_relaunch_authorized':{'const':False}}
for name,properties in [('independent_referee_acceptance.schema.json',a),('launch_clearance.schema.json',c)]:atomic(HERE/name,{'$schema':'https://json-schema.org/draft/2020-12/schema','type':'object','additionalProperties':False,'required':list(properties),'properties':properties})
print(json.dumps({'status':plan['status'],'selected':[126,161],'sources':36,'hostiles':21,'solver_runs':0},sort_keys=True))
