//! Independent literal replay of the 257 distributed K23 witnesses.
#![allow(dead_code)]
mod audit {
include!("../unaudited-codex-orbit0-filtered-k18-charge-2026-08-23/run_k18_charge.rs");
use std::fs::rename;

const U:i128=400_591_699_200;
const EXPECTED_HEADER:&str="group_index\tsample_ordinal\tr8_index\tsource_mass\tsource_row\tintermediate_row\tterminal_row\tp1\tintermediate_tail_index\tterminal_pivot\tterminal_tail_index\tm1\tm2\tfirst_degree\tfinal_degree\tterminal_child_q\tresponse_charge_sum\tunit_scaled_U\tnonzero_contribution_scaled_U\tpath_kind";

fn hex_row(s:&str)->Row{assert_eq!(s.len(),48);let mut out=[0u8;24];for(i,x)in out.iter_mut().enumerate(){*x=u8::from_str_radix(&s[2*i..2*i+2],16).unwrap()}assert!(out.windows(2).all(|w|w[0]<=w[1]));Row(out)}
fn source_member(row:&Row,ri:usize,g:usize,e:&E)->bool{let r=&e.records[ri];match g{
 0|1=>{let specs=[(0usize,1usize,2usize),(0,2,1),(1,0,2),(1,2,0),(2,0,1),(2,1,0)];for &(d2,d3,d4)in &specs{for a in &e.factor[d2][0]{for b in &e.factor[d3][1]{for c in &e.factor[d4][2]{let mut f:[Option<&[u8;4]>;3]=[None,None,None];f[d2]=Some(a);f[d3]=Some(b);f[d4]=Some(c);if make(r,f[0].unwrap(),f[1].unwrap(),f[2].unwrap())==*row{return true}}}}}for a in &e.factor[0][1]{for b in &e.factor[1][1]{for c in &e.factor[2][1]{if make(r,a,b,c)==*row{return true}}}}false},
 2=>{for low in 0..3{let o:Vec<_>=(0..3).filter(|&x|x!=low).collect();for a in &e.factor[low][0]{for b in &e.factor[o[0]][2]{for c in &e.factor[o[1]][2]{let x=match low{0=>make(r,a,b,c),1=>make(r,b,a,c),_=>make(r,b,c,a)};if x==*row{return true}}}}}for high in 0..3{let o:Vec<_>=(0..3).filter(|&x|x!=high).collect();for a in &e.factor[o[0]][1]{for b in &e.factor[o[1]][1]{for c in &e.factor[high][2]{let x=match high{0=>make(r,c,a,b),1=>make(r,a,c,b),_=>make(r,a,b,c)};if x==*row{return true}}}}}false},
 3=>{for low in 0..3{let o:Vec<_>=(0..3).filter(|&x|x!=low).collect();for a in &e.factor[low][1]{for b in &e.factor[o[0]][2]{for c in &e.factor[o[1]][2]{let x=match low{0=>make(r,a,b,c),1=>make(r,b,a,c),_=>make(r,b,c,a)};if x==*row{return true}}}}}false},
 _=>unreachable!()}}

pub fn run(){let a:Vec<_>=std::env::args().collect();assert_eq!(a.len(),3,"usage: verifier SAMPLE_TSV OUTPUT_JSON");let begun=Instant::now();let e=parse();assert_eq!(e.records.len(),485);let text=std::fs::read_to_string(&a[1]).unwrap();let mut lines=text.lines();assert_eq!(lines.next().unwrap(),EXPECTED_HEADER);let mut seen=[false;257];let mut groups=[0usize;4];let mut fallback=Vec::new();let mut terminal_children=0u64;
 for line in lines{let c:Vec<_>=line.split('\t').collect();assert_eq!(c.len(),20);let g:usize=c[0].parse().unwrap();let ord:usize=c[1].parse().unwrap();let ri:usize=c[2].parse().unwrap();let mass:i128=c[3].parse().unwrap();let source=hex_row(c[4]);let intermediate=hex_row(c[5]);let terminal=hex_row(c[6]);let p1:i32=c[7].parse().unwrap();let t1:i32=c[8].parse().unwrap();let pt:usize=c[9].parse().unwrap();let tt:usize=c[10].parse().unwrap();let m1:usize=c[11].parse().unwrap();let m2:usize=c[12].parse().unwrap();let first:usize=c[13].parse().unwrap();let finald:usize=c[14].parse().unwrap();let child_q:i64=c[15].parse().unwrap();let response_q:i64=c[16].parse().unwrap();let unit:i128=c[17].parse().unwrap();let contribution:i128=c[18].parse().unwrap();
  assert!(g<4&&ord<257&&!seen[ord]);seen[ord]=true;groups[g]+=1;assert_eq!(ri,ord*484/256);assert_eq!(mass,(e.records[ri].size as i128)*(e.records[ri].coefficient as i128));assert!(source_member(&source,ri,g,&e));let expected_degrees=match g{0=>(2,4),1=>(3,3),2=>(2,3),3=>(0,4),_=>unreachable!()};assert_eq!((first,finald),expected_degrees);
  let (base,base_sig,divisor)=if g<3{assert_eq!(c[19],"two_response");let p=p1 as usize;let ti=t1 as usize;let s1=sig(&source,&e);let ps1=avail(s1,&e);assert_eq!(ps1.len(),m1);assert!(ps1.contains(&p));assert!(ti<e.tails[p][first-2].len());let s2=child_sig(s1,p,&e.tails[p][first-2][ti],&e);let rebuilt=replace(&source,&e.anchors[p],&e.tails[p][first-2][ti]);assert!(rebuilt==intermediate);assert_eq!(sig(&intermediate,&e),s2);let ps2=avail(s2,&e);assert_eq!(ps2.len(),m2);assert!(ps2.contains(&pt));assert_eq!(unit,-U/((m1*m2)as i128));(intermediate,s2,m1*m2)}else{assert_eq!(c[19],"one_response");assert_eq!((p1,t1,first,m2),(-1,-1,0,1));assert!(source==intermediate);let s=sig(&source,&e);let ps=avail(s,&e);assert_eq!(ps.len(),m1);assert!(ps.contains(&pt));assert_eq!(unit,U/(m1 as i128));(source,s,m1)};
  assert_eq!(U%(divisor as i128),0);assert!(tt<e.tails[pt][finald-2].len());let mut sum=0i64;let mut rebuilt_witness=None;for(ti,t)in e.tails[pt][finald-2].iter().enumerate(){let cs=child_sig(base_sig,pt,t,&e);assert!(avail(cs,&e).is_empty());let child=replace(&base,&e.anchors[pt],t);assert_eq!(sig(&child,&e),cs);let q=charge(&child,&e);sum+=q;terminal_children+=1;if ti==tt{rebuilt_witness=Some((child,q))}}let(child,q)=rebuilt_witness.unwrap();assert!(child==terminal);assert_eq!(q,child_q);assert_ne!(child_q,0);assert_eq!(sum,response_q);assert_eq!(mass*unit*(response_q as i128),contribution);assert_ne!(contribution,0);if g!=ord%4{fallback.push(format!("{{\"ordinal\":{},\"r8_index\":{},\"preferred_group\":{},\"actual_group\":{}}}",ord,ri,ord%4,g))}
 }
 assert!(seen.iter().all(|&x|x));assert_eq!(groups,[66,64,64,63]);assert_eq!(fallback.len(),1);assert_eq!(fallback[0],"{\"ordinal\":227,\"r8_index\":429,\"preferred_group\":3,\"actual_group\":0}");let elapsed=begun.elapsed().as_secs_f64();let out=format!("{{\n  \"status\":\"PASS_INDEPENDENT_K23_DIRECT23_LITERAL_SAMPLE_REPLAY\",\n  \"witnesses\":257,\n  \"source_membership_replays\":257,\n  \"literal_intermediate_replays\":194,\n  \"literal_terminal_replays\":257,\n  \"terminal_children_exhaustively_checked\":{},\n  \"group_counts\":[{},{},{},{}],\n  \"fallbacks\":[{}],\n  \"checks\":\"source mass and physical family membership; literal pivots and tails; exact m1/m2 and U division; every response tail nonpivotable; terminal row and charge; aggregate response sum; signed nonzero contribution\",\n  \"elapsed_seconds\":{:.6}\n}}\n",terminal_children,groups[0],groups[1],groups[2],groups[3],fallback.join(","),elapsed);let tmp=format!("{}.tmp",a[2]);std::fs::write(&tmp,&out).unwrap();rename(tmp,&a[2]).unwrap();print!("{}",out)}
}
fn main(){audit::run()}
