#!/usr/bin/env python3
"""UNAUDITED PROBE (W7 / Route T.1) -- is the GENERATOR-level initial system at
a surviving cone TORUS-feasible?

Pinned HEAD: a41949965d41e5c63fb4bc1caf7b20c0df017856

WHY THIS IS THE DECISIVE EXPERIMENT.  T.1 asks for a monomial in in_w(I).  What
a cone-by-cone argument can certify is that the ideal generated by the initial
forms OF THE GIVEN GENERATORS has no torus zero.  If a cone's generator-level
initial system DOES have a torus solution, no extra lemma can close that cone
by this route: the generators are not a tropical basis there.

METHOD.  Substitute x = exp(z), z complex, which parametrises the torus.  The
danger is escape to the boundary: |x| = exp(Re z) -> 0 makes any monomial
equation solvable in the limit without a torus point existing.  So a SOFT BOX
is imposed -- a penalty on max(0, |Re z_k| - R) with R = 4, i.e. cells are held
in |x| in [e^-4, e^4] -- and a solution is only reported when the residual is
below 1e-9 AND every cell is inside the box.  Overall scale is pinned by
sum_k Re z_k = 0 so that homogeneous (all-anchors-zero) instances cannot be
rescaled into or out of the box.

CONTROLS (these must FAIL, and the script says so explicitly):
  * a singleton cone -- the initial system contains a single monomial;
  * the g>0 chamber -- killed by LEMMA H4 (N=8) / the (2,2,2) singleton (N=6);
  * w = 0 -- the initial system IS the six-site system, known insoluble.
An earlier version of this script without the box reported all three as
solvable; the box is what makes the probe discriminating.
"""

from __future__ import annotations

from fractions import Fraction
from itertools import combinations, product
import json
import sys

import numpy as np

R_BOX = 4.0


def perfect_matchings(vertices):
    vertices = tuple(vertices)
    if not vertices:
        return ((),)
    first = vertices[0]
    out = []
    for index in range(1, len(vertices)):
        rest = vertices[1:index] + vertices[index + 1:]
        for tail in perfect_matchings(rest):
            out.append(((first, vertices[index]),) + tail)
    return tuple(out)


class Instance:
    def __init__(self, nsites, g, diag):
        self.n = nsites
        self.sites = tuple(range(nsites))
        self.edges = tuple(combinations(self.sites, 2))
        self.eindex = {e: i for i, e in enumerate(self.edges)}
        self.ncell = len(self.edges) * 9
        self.matchings = perfect_matchings(self.sites)
        f = {}
        for c in range(3):
            f[(c, c)] = Fraction(diag[c])
        gg = {(0, 1): Fraction(g[0]), (0, 2): Fraction(g[1]),
              (1, 2): Fraction(g[2])}
        for (a, b), val in gg.items():
            v = val + (f[(a, a)] + f[(b, b)]) * Fraction(1, 2)
            f[(a, b)] = v
            f[(b, a)] = v
        self.f = f

    def cell(self, edge, i, j):
        return self.eindex[edge] * 9 + 3 * i + j

    def build(self):
        """(monomials, eq_of_monomial, rhs) or (None, None, None) if a pure
        initial form is the unit -1."""
        monos, eq_of, rhs = [], [], []
        neq = 0
        for chi in product(range(3), repeat=self.n):
            weights = [sum(self.f[(chi[u], chi[v])] for u, v in M)
                       for M in self.matchings]
            best = min(weights)
            sel = [M for M, wt in zip(self.matchings, weights) if wt == best]
            if len(set(chi)) == 1:
                if best > 0:
                    return None, None, None
                rhs.append(1.0 if best == 0 else 0.0)
            else:
                rhs.append(0.0)
            for M in sel:
                monos.append(tuple(self.cell((u, v), chi[u], chi[v])
                                   for u, v in M))
                eq_of.append(neq)
            neq += 1
        return monos, np.array(eq_of), np.array(rhs)


def solve(inst, restarts=8, iters=250, seed=0):
    monos, eq_of, rhs = inst.build()
    if monos is None:
        return {"status": "KILLED (pure initial form is the unit -1)"}
    ncell, neq = inst.ncell, len(rhs)
    M = np.zeros((len(monos), ncell))
    for k, mono in enumerate(monos):
        for idx in mono:
            M[k, idx] += 1.0
    A = np.zeros((neq, len(monos)))
    A[eq_of, np.arange(len(monos))] = 1.0
    ones = np.ones(ncell)

    def parts(z):
        mv = np.exp(M @ z)
        F = A @ mv - rhs
        re = z.real
        over = np.sign(re) * np.maximum(np.abs(re) - R_BOX, 0.0)
        return mv, F, over, re.sum()

    def full_residual(z):
        mv, F, over, scale = parts(z)
        return np.concatenate([F, over.astype(complex),
                               np.array([scale + 0j])]), mv, over

    def jac(z, mv):
        JM = A @ (mv[:, None] * M)                 # d F / d z
        Jover = np.zeros((ncell, ncell), dtype=complex)
        re = z.real
        mask = np.abs(re) > R_BOX
        Jover[np.arange(ncell), np.arange(ncell)] = mask.astype(float)
        Jscale = ones.astype(complex)[None, :]
        return np.vstack([JM, Jover, Jscale])

    rng = np.random.default_rng(seed)
    best = None
    for _ in range(restarts):
        z = rng.normal(size=ncell) * 0.4 + 1j * rng.normal(size=ncell) * 1.2
        lam = 1e-2
        for _ in range(iters):
            F, mv, over = full_residual(z)
            nrm = float(np.max(np.abs(F)))
            if nrm < 1e-12:
                break
            J = jac(z, mv)
            try:
                step, *_ = np.linalg.lstsq(
                    np.vstack([J, lam * np.eye(ncell)]),
                    np.concatenate([-F, np.zeros(ncell)]), rcond=None)
            except np.linalg.LinAlgError:
                break
            trial = z + step
            Ft, _, _ = full_residual(trial)
            if np.max(np.abs(Ft)) < nrm:
                z, lam = trial, max(lam * 0.6, 1e-10)
            else:
                z, lam = z + 0.25 * step, min(lam * 4, 1e4)
        F, mv, over = full_residual(z)
        eqres = float(np.max(np.abs(A @ mv - rhs)))
        x = np.exp(z)
        rec = {"eq_residual": eqres,
               "min_abs_cell": float(np.min(np.abs(x))),
               "max_abs_cell": float(np.max(np.abs(x))),
               "box_violation": float(np.max(np.abs(over))),
               "z": z.copy()}
        if best is None or (rec["eq_residual"], rec["box_violation"]) < \
                (best["eq_residual"], best["box_violation"]):
            best = rec
        if eqres < 1e-10 and rec["box_violation"] < 1e-9:
            break
    ok = best["eq_residual"] < 1e-9 and best["box_violation"] < 1e-8
    best["status"] = ("TORUS SOLUTION of the initial system" if ok
                      else "no torus solution found")
    best["n_equations"] = neq
    best["n_cells"] = ncell
    return best


CASES = {
    "6": [
        ("CONTROL singleton cone g=(1,1,1) s=(0,0,0)", 6, (1, 1, 1), (0, 0, 0),
         "must FAIL"),
        ("CONTROL singleton cone g=(1,1,1) s=(-,-,-)", 6, (1, 1, 1),
         (-1, -1, -1), "must FAIL"),
        ("CONTROL w=0 (= the whole six-site system)", 6, (0, 0, 0), (0, 0, 0),
         "must FAIL"),
        ("OPEN g=(-1,-1,-1) s=(0,0,0)", 6, (-1, -1, -1), (0, 0, 0), ""),
        ("OPEN g=(-1,-1,-1) s=(-,-,-)", 6, (-1, -1, -1), (-1, -1, -1), ""),
        ("OPEN g=(-5,-3,-4) s=(0,0,0)", 6, (-5, -3, -4), (0, 0, 0), ""),
        ("OPEN g=(-5,-3,-4) s=(-,-,-)", 6, (-5, -3, -4), (-1, -1, -1), ""),
    ],
    "8": [
        ("CONTROL H4 cone g=(1,1,1) s=(0,0,0)", 8, (1, 1, 1), (0, 0, 0),
         "must FAIL"),
        ("CONTROL H4 cone g=(1,1,1) s=(-,-,-)", 8, (1, 1, 1), (-1, -1, -1),
         "must FAIL"),
        ("OPEN g=(-1,-1,-1) s=(-,-,-)", 8, (-1, -1, -1), (-1, -1, -1), ""),
        ("OPEN g=(-1,-1,-1) s=(0,0,0)", 8, (-1, -1, -1), (0, 0, 0), ""),
    ],
}


def main():
    which = sys.argv[1] if len(sys.argv) > 1 else "6"
    out = {}
    for name, nsites, g, diag, note in CASES[which]:
        inst = Instance(nsites, g, diag)
        rec = solve(inst, restarts=(8 if nsites == 6 else 4),
                    iters=(250 if nsites == 6 else 150),
                    seed=abs(hash(name)) % 9999)
        tag = (" [%s]" % note) if note else ""
        print("%-46s%s\n     %s" % (name, tag, rec["status"]))
        for k in ("eq_residual", "min_abs_cell", "max_abs_cell",
                  "box_violation", "n_equations"):
            if k in rec:
                print("       %-15s %s" % (k, rec[k]))
        out[name] = rec
        sys.stdout.flush()
    with open("results_initial_probe_N%s.json" % which, "w") as h:
        json.dump(out, h, indent=1, default=str)
    print("wrote results_initial_probe_N%s.json" % which)


if __name__ == "__main__":
    main()
