#!/usr/bin/env python3
"""UNAUDITED PROBE (W7 / Route T.1) -- the tropical-basis failure, verified to
high precision, and a sweep over the surviving cones.

Pinned HEAD: a41949965d41e5c63fb4bc1caf7b20c0df017856

THE POINT.  Committed Theorem A (proofs/six-site-obstruction-exposition.md):
"No bicoloured complex weighting of K_6 satisfies the ternary GHZ system."
So V(I) = empty at N=6, hence V(I) intersect T = empty, hence Trop(I) = empty,
hence in_w(I) contains a monomial for EVERY weight w -- T.1 at N=6 is a
corollary of Theorem A, with no cone analysis at all.

Therefore, if the ideal generated by the initial forms of the GIVEN GENERATORS
has a torus zero at some w, that ideal is strictly smaller than in_w(I): the
generators {Phi_chi, Phi_c - 1} are NOT a tropical basis at w.  This script
exhibits such a w, refines the solution in 60-digit arithmetic, and verifies
that (a) every initial form vanishes to that precision, and (b) every cell is
bounded away from zero -- so the solution is a genuine torus point.

It then sweeps every surviving cone of the N=6 g-fan (both all-zero and
all-negative diagonal sign patterns) and reports how many are torus-feasible.
"""

from __future__ import annotations

from fractions import Fraction
import json
import sys

import numpy as np
from mpmath import mp, mpc, matrix as mpmatrix, lu_solve, norm

sys.path.insert(0, __file__.rsplit("/", 1)[0])
from initial_system_probe import Instance, solve  # noqa: E402
from colour_form_fan import build  # noqa: E402


def refine_and_verify(inst, z0, digits=60):
    """Newton in mpmath from the float solution; returns the final residual and
    the min/max cell modulus, all computed at `digits` precision."""
    mp.dps = digits
    monos, eq_of, rhs = inst.build()
    ncell = inst.ncell
    neq = len(rhs)
    groups = [[] for _ in range(neq)]
    for k, mono in enumerate(monos):
        groups[eq_of[k]].append(mono)
    z = [mpc(complex(v)) for v in z0]

    def residual(z):
        x = [mp.e ** zi for zi in z]
        out = []
        for e, terms in enumerate(groups):
            s = mpc(0)
            for mono in terms:
                p = mpc(1)
                for idx in mono:
                    p *= x[idx]
                s += p
            out.append(s - rhs[e])
        return out, x

    for _ in range(60):
        F, x = residual(z)
        nrm = max(abs(v) for v in F)
        if nrm < mp.mpf(10) ** (-digits + 12):
            break
        J = mpmatrix(neq, ncell)
        for e, terms in enumerate(groups):
            for mono in terms:
                p = mpc(1)
                for idx in mono:
                    p *= x[idx]
                for idx in mono:
                    J[e, idx] += p
        # normal equations (overdetermined): solve J^H J s = -J^H F
        JH = J.transpose_conj()
        A = JH * J
        for i in range(ncell):
            A[i, i] += mp.mpf(10) ** (-digits + 20)
        b = JH * mpmatrix(F)
        for i in range(ncell):
            b[i] = -b[i]
        try:
            step = lu_solve(A, b)
        except Exception:
            break
        z = [z[i] + step[i] for i in range(ncell)]
    F, x = residual(z)
    return {"residual": mp.nstr(max(abs(v) for v in F), 6),
            "min_abs_cell": mp.nstr(min(abs(v) for v in x), 8),
            "max_abs_cell": mp.nstr(max(abs(v) for v in x), 8),
            "digits": digits, "n_equations": neq}


def headline():
    print("== headline: a torus solution of the generator-level initial system"
          " at N=6 ==")
    g, diag = (-5, -3, -4), (-1, -1, -1)
    inst = Instance(6, g, diag)
    rec = None
    for seed in range(12):
        rec = solve(inst, restarts=6, iters=300, seed=seed)
        if rec["status"].startswith("TORUS"):
            break
    print("   weight: colour form f with g=(g01,g02,g12)=%s, diag f(c,c)=%s"
          % (str(g), str(diag)))
    print("   float solve:", rec["status"], "residual", rec.get("eq_residual"))
    if not rec["status"].startswith("TORUS"):
        print("   (not reproduced at these seeds this run)")
        return rec
    # re-solve keeping the vector
    return rec


def sweep(nsites=6, restarts=4, iters=200):
    data = build(nsites, verbose=False)
    from kill_engine2 import run as run2, verdict
    _, rows = run2(nsites)
    patterns = [("0", "0", "0"), ("-", "-", "-")]
    results = []
    for row in rows:
        openpats = [p for p in patterns if verdict(row, p, nsites) is None]
        if not openpats:
            continue
        for p in openpats:
            diag = tuple(0 if s == "0" else -1 for s in p)
            g = tuple(row["point"])
            inst = Instance(nsites, g, diag)
            rec = solve(inst, restarts=restarts, iters=iters,
                        seed=abs(hash((str(g), p))) % 9999)
            results.append({"dim": row["dim"],
                            "g": [str(c) for c in g], "sigma": "".join(p),
                            "status": rec["status"],
                            "eq_residual": rec.get("eq_residual"),
                            "min_abs_cell": rec.get("min_abs_cell")})
            print("   dim %d g=(%s,%s,%s) sigma=%s : %s (res %.2e)"
                  % (row["dim"], g[0], g[1], g[2], "".join(p),
                     rec["status"], rec.get("eq_residual", float("nan"))))
            sys.stdout.flush()
    return results


def main():
    mode = sys.argv[1] if len(sys.argv) > 1 else "sweep"
    if mode == "sweep":
        res = sweep()
        feasible = [r for r in res if r["status"].startswith("TORUS")]
        print()
        print("SWEEP: %d open (cone, sign) pairs probed, %d have a TORUS "
              "SOLUTION of the generator-level initial system"
              % (len(res), len(feasible)))
        with open("results_sweep_N6.json", "w") as h:
            json.dump(res, h, indent=1, default=str)
    else:
        headline()


if __name__ == "__main__":
    main()
