//! Restartable literal child provider for the recovered hidden K16 parents.
#![allow(dead_code,unused_imports)]
include!("../unaudited-codex-orbit0-k19-profile-census-2026-08-23/run_k19_profile_census.rs");
use std::io::{Read,Seek,SeekFrom,BufReader};

const PDIR:&str="computations/unaudited-codex-orbit0-k14-hidden-k16-parent-full-2026-08-23/";
const K4_PATH:&str="computations/unaudited-codex-orbit0-filtered-k18-charge-2026-08-23/filtered_k18_k4.bin";
const PU:i128=400_591_699_200;
fn k4()->Vec<Vec<[u8;4]>>{let b=read(K4_PATH).unwrap();assert_eq!(&b[..7],b"K18K4A1");let mut p=7;let mut out=vec![Vec::new();78];for row in &mut out{for _ in 0..60{let mut x=[0;4];x.copy_from_slice(&b[p..p+4]);p+=4;row.push(x)}}assert_eq!(p,b.len());out}
fn main(){let args:Vec<_>=std::env::args().collect();assert_eq!(args.len(),6,"usage: provider DEGREE RUN_START PARENT_START PARENT_COUNT OUT.bin");let degree:usize=args[1].parse().unwrap();assert!([2,3,4].contains(&degree));let run_start:usize=args[2].parse().unwrap();assert_eq!(run_start%16,0);let run_end=(run_start+16).min(485);let parent_start:u64=args[3].parse().unwrap();let requested:u64=args[4].parse().unwrap();let output=&args[5];let e=parse();let k4tails=if degree==4{Some(k4())}else{None};let path=format!("{}parents_{:03}_{:03}.bin",PDIR,run_start,run_end);let mut r=BufReader::with_capacity(1<<20,File::open(path).unwrap());let mut h=[0;40];r.read_exact(&mut h).unwrap();assert_eq!(&h[..8],b"H16RUN2\0");assert_eq!(i128::from_le_bytes(h[8..24].try_into().unwrap()),PU);assert_eq!((u16::from_le_bytes(h[24..26].try_into().unwrap())as usize,u16::from_le_bytes(h[26..28].try_into().unwrap())as usize,u16::from_le_bytes(h[28..30].try_into().unwrap())),(run_start,run_end,64));let total=u64::from_le_bytes(h[32..40].try_into().unwrap());assert!(parent_start<=total);let take=if requested==0{total-parent_start}else{requested.min(total-parent_start)};r.seek(SeekFrom::Start(40+64*parent_start)).unwrap();
 let tmp=format!("{}.tmp",output);let mut w=BufWriter::with_capacity(1<<20,File::create(&tmp).unwrap());w.write_all(b"H16CHD2\0").unwrap();w.write_all(&PU.to_le_bytes()).unwrap();w.write_all(&[degree as u8]).unwrap();w.write_all(&(run_start as u16).to_le_bytes()).unwrap();w.write_all(&[0;5]).unwrap();w.write_all(&parent_start.to_le_bytes()).unwrap();w.write_all(&take.to_le_bytes()).unwrap();w.write_all(&0u64.to_le_bytes()).unwrap();w.write_all(&52u16.to_le_bytes()).unwrap();w.write_all(&[0;6]).unwrap();
 let mut children=0u64;for parent_offset in 0..take{let mut rec=[0;64];r.read_exact(&mut rec).unwrap();let mut row=[0;24];row.copy_from_slice(&rec[..24]);let row=Row(row);let weight=i128::from_le_bytes(rec[24..40].try_into().unwrap());let mut s=[0;12];s.copy_from_slice(&rec[40..52]);assert_eq!(sig(&row,&e),s);let m2=rec[60]as usize;let ps=avail(s,&e);assert_eq!(ps.len(),m2);assert_eq!(weight%(m2 as i128),0);let child_weight=-weight/(m2 as i128);for &p2 in &ps{let tails:&[[u8;4]]=match degree{2=>&e.tails[p2][0],3=>&e.tails[p2][1],4=>k4tails.as_ref().unwrap()[p2].as_slice(),_=>unreachable!()};assert_eq!(tails.len(),match degree{2=>12,3=>32,_=>60});for(ti,t)in tails.iter().enumerate(){let child=replace(&row,&e.anchors[p2],t);w.write_all(&child.0).unwrap();w.write_all(&child_weight.to_le_bytes()).unwrap();w.write_all(&(parent_start+parent_offset).to_le_bytes()).unwrap();w.write_all(&[p2 as u8,ti as u8,m2 as u8,degree as u8]).unwrap();children+=1}}}
 w.flush().unwrap();let mut f=w.into_inner().unwrap();f.seek(SeekFrom::Start(48)).unwrap();f.write_all(&children.to_le_bytes()).unwrap();f.sync_all().unwrap();drop(f);rename(tmp,output).unwrap();println!("{{\"status\":\"PASS_CHILD_PROVIDER\",\"degree\":{},\"run_start\":{},\"parent_start\":{},\"parent_records\":{},\"children\":{},\"output_bytes\":{}}}",degree,run_start,parent_start,take,children,64+52*children)}
