#!/usr/bin/env python3
import hashlib,json,os
from pathlib import Path
HERE=Path(__file__).resolve().parent
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def atomic(p,v):t=p.with_suffix(p.suffix+'.tmp');t.write_text(json.dumps(v,indent=2,sort_keys=True)+'\n');os.replace(t,p)
LEDGER='48e9fb104efd69a1267f5ff1015a2142af33d481a430bebab2f794442afa8341';FUTURE='14914c42a19896d680a8cab0c154795ea15b7e8fae0d52b0a0b58e26c8f40a5d';ADAPTER='3fca6f290c810bbf9e15d524de79510ab7c7bad11069890e85d12ab8843895a9';RUNNER='b29a78c495517ddb9c43147c5c9ec1091c921a63e4a8285cf7549d0926d721aa';SELECTED=list(range(26,76));CLOSED=list(range(26))
assert sha(HERE/'source_ledger.json')==LEDGER and sha(HERE/'future_dependency.json')==FUTURE and sha(HERE/'normalize_dependency.py')==ADAPTER and sha(HERE/'run_groups26_75.py')==RUNNER;l=json.loads((HERE/'source_ledger.json').read_text());f=json.loads((HERE/'future_dependency.json').read_text());assert l['selection']['selected_group_ids']==SELECTED and f['manifest_sha256'] is f['result_sha256'] is None and f['satisfied'] is False
plan={'schema':'KRENN_X5_REP4_GROUPS26_75_EXACT_Q_CONDITIONAL_HELD_V1','status':'HELD_FUTURE_FIRST25_PASS_ABSENT_ZERO_RUN','selection':l['selection'],'future_dependency':{'path':'future_dependency.json','sha256':FUTURE,'manifest_sha256':None,'result_sha256':None,'satisfied':False,'normalized_dependency_present':False},'adapter':{'path':'normalize_dependency.py','sha256':ADAPTER,'required_closed_union':CLOSED,'fail_closed':True},'lanes':l['lanes'],'source_ledger':{'path':'source_ledger.json','sha256':LEDGER,'total_bytes':sum(x['source_bytes'] for x in l['lanes'])},'runner':{'path':'run_groups26_75.py','sha256':RUNNER,'strict_sequential':True,'direct_libproc_process_group_rss':True,'fail_closed_rusage':True,'internal_gtimeout_wrapper':True,'atomic_per_lane_results':True,'single_use_batch_marker':True},'execution':{'native_wall_seconds_each':240,'wrapper_wall_seconds_each':250,'rss_cap_bytes_each':8589934592,'maximum_lane_count':50,'order':SELECTED,'parallel':False,'skip':False,'reorder':False,'relaunch':False,'stop_whole_batch_on':['NONUNIT','RESOURCE','PROCESS','SCHEMA_OR_TRANSCRIPT_MISMATCH']},'scope':{'representative':'rep4 only','source_regeneration_only':True,'solver_launches':0,'result_files':0,'attempt_markers':0,'clearances':0,'groups_newly_closed':0,'rep4_closed':False,'mathematical_coverage_added':False,'cross_representative_transport':False}};atomic(HERE/'held_schedule.json',plan)
hex64={'type':'string','pattern':'^[0-9a-f]{64}$'};a={'schema':{'const':'KRENN_X5_REP4_GROUPS26_75_EXACT_Q_INDEPENDENT_ACCEPTANCE_V1'},'status':{'const':'PASS_APPROVE_CONDITIONAL_REP4_GROUPS26_75_ONLY'},'held_manifest_sha256':hex64,'source_ledger_sha256':{'const':LEDGER},'normalized_dependency_sha256':hex64,'runner_sha256':{'const':RUNNER},'required_closed_union':{'const':CLOSED},'selected_group_ids':{'const':SELECTED},'maximum_lane_count':{'const':50},'exact_Q_authorized':{'const':True},'parallel_authorized':{'const':False},'skip_reorder_relaunch_authorized':{'const':False}};c={'schema':{'const':'KRENN_X5_REP4_GROUPS26_75_EXACT_Q_EXPLICIT_CLEARANCE_V1'},'status':{'const':'CLEARED_CONDITIONAL_REP4_GROUPS26_75_ONLY'},'held_manifest_sha256':hex64,'independent_referee_acceptance_sha256':hex64,'source_ledger_sha256':{'const':LEDGER},'normalized_dependency_sha256':hex64,'runner_sha256':{'const':RUNNER},'singular_sha256':{'const':'9436b32ff7565719240230de8a6fb1d27af5e65f0ca4c9c5b756a77e82409b88'},'gtimeout_sha256':{'const':'1e26c50fa8c439fe1f4e6c6edd106e95030e16582c1c8c32e73d8a889cdf5b95'},'required_closed_union':{'const':CLOSED},'selected_group_ids':{'const':SELECTED},'native_wall_seconds_each':{'const':240},'wrapper_wall_seconds_each':{'const':250},'rss_cap_bytes_each':{'const':8589934592},'no_overlap_confirmed':{'const':True},'maximum_lane_count':{'const':50},'parallel_authorized':{'const':False},'skip_reorder_relaunch_authorized':{'const':False}}
for name,p in (('independent_referee_acceptance.schema.json',a),('launch_clearance.schema.json',c)):atomic(HERE/name,{'$schema':'https://json-schema.org/draft/2020-12/schema','type':'object','additionalProperties':False,'required':list(p),'properties':p})
print(json.dumps({'status':plan['status'],'selected':[26,75],'future_hashes_null':2,'runner_sha256':RUNNER},sort_keys=True))
