#!/usr/bin/env python3
import hashlib,json,os
from pathlib import Path
HERE=Path(__file__).resolve().parent
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def atomic(p,v):t=p.with_suffix(p.suffix+'.tmp');t.write_text(json.dumps(v,indent=2,sort_keys=True)+'\n');os.replace(t,p)
LEDGER='b311e566fab04932f0c49a285ac3190ae4ac7a02f102799a9a2c6b34a949e4bb';FUTURE='02e042533a68fb7a9a08d230caa7de915c3176e4d7e54b8f68a9704da7e6916e';ADAPTER='5afc90779b09c31950e30cb7f11cb198d9c37f5d655e6926fcfad2980561733c';RUNNER='3e5a744b6017dc0ba4a4d9789039bb4697d20fd1b42332195dc015cfd1e91abd';SELECTED=list(range(76,126));CLOSED=list(range(76))
assert sha(HERE/'source_ledger.json')==LEDGER and sha(HERE/'future_dependencies.json')==FUTURE and sha(HERE/'normalize_dependencies.py')==ADAPTER and sha(HERE/'run_groups76_125.py')==RUNNER;l=json.loads((HERE/'source_ledger.json').read_text());f=json.loads((HERE/'future_dependencies.json').read_text());assert l['selection']['selected_group_ids']==SELECTED and f['satisfied'] is False and all(d['manifest_sha256'] is d['result_sha256'] is None and d['satisfied'] is False for d in f['dependencies'])
plan={'schema':'KRENN_X5_REP4_GROUPS76_125_EXACT_Q_CONDITIONAL_HELD_V1','status':'HELD_BOTH_FUTURE_PASSES_ABSENT_ZERO_RUN','selection':l['selection'],'future_dependencies':{'path':'future_dependencies.json','sha256':FUTURE,'dependency_count':2,'null_hash_count':4,'satisfied':False,'normalized_dependencies_present':False},'adapter':{'path':'normalize_dependencies.py','sha256':ADAPTER,'required_closed_union':CLOSED,'fail_closed':True},'lanes':l['lanes'],'source_ledger':{'path':'source_ledger.json','sha256':LEDGER,'total_bytes':sum(x['source_bytes'] for x in l['lanes'])},'runner':{'path':'run_groups76_125.py','sha256':RUNNER,'strict_sequential':True,'direct_libproc_process_group_rss':True,'fail_closed_rusage':True,'internal_gtimeout_wrapper':True,'atomic_per_lane_results':True,'single_use_batch_marker':True},'execution':{'native_wall_seconds_each':240,'wrapper_wall_seconds_each':250,'rss_cap_bytes_each':8589934592,'maximum_lane_count':50,'order':SELECTED,'parallel':False,'skip':False,'reorder':False,'relaunch':False,'stop_whole_batch_on':['NONUNIT','RESOURCE','PROCESS','SCHEMA_OR_TRANSCRIPT_MISMATCH']},'scope':{'representative':'rep4 only','source_regeneration_only':True,'solver_launches':0,'result_files':0,'attempt_markers':0,'clearances':0,'groups_newly_closed':0,'rep4_closed':False,'mathematical_coverage_added':False,'cross_representative_transport':False}};atomic(HERE/'held_schedule.json',plan)
hex64={'type':'string','pattern':'^[0-9a-f]{64}$'};a={'schema':{'const':'KRENN_X5_REP4_GROUPS76_125_EXACT_Q_INDEPENDENT_ACCEPTANCE_V1'},'status':{'const':'PASS_APPROVE_CONDITIONAL_REP4_GROUPS76_125_ONLY'},'held_manifest_sha256':hex64,'source_ledger_sha256':{'const':LEDGER},'normalized_dependencies_sha256':hex64,'runner_sha256':{'const':RUNNER},'required_closed_union':{'const':CLOSED},'selected_group_ids':{'const':SELECTED},'maximum_lane_count':{'const':50},'exact_Q_authorized':{'const':True},'parallel_authorized':{'const':False},'skip_reorder_relaunch_authorized':{'const':False}};c={'schema':{'const':'KRENN_X5_REP4_GROUPS76_125_EXACT_Q_EXPLICIT_CLEARANCE_V1'},'status':{'const':'CLEARED_CONDITIONAL_REP4_GROUPS76_125_ONLY'},'held_manifest_sha256':hex64,'independent_referee_acceptance_sha256':hex64,'source_ledger_sha256':{'const':LEDGER},'normalized_dependencies_sha256':hex64,'runner_sha256':{'const':RUNNER},'singular_sha256':{'const':'9436b32ff7565719240230de8a6fb1d27af5e65f0ca4c9c5b756a77e82409b88'},'gtimeout_sha256':{'const':'1e26c50fa8c439fe1f4e6c6edd106e95030e16582c1c8c32e73d8a889cdf5b95'},'required_closed_union':{'const':CLOSED},'selected_group_ids':{'const':SELECTED},'native_wall_seconds_each':{'const':240},'wrapper_wall_seconds_each':{'const':250},'rss_cap_bytes_each':{'const':8589934592},'no_overlap_confirmed':{'const':True},'maximum_lane_count':{'const':50},'parallel_authorized':{'const':False},'skip_reorder_relaunch_authorized':{'const':False}}
for name,p in (('independent_referee_acceptance.schema.json',a),('launch_clearance.schema.json',c)):atomic(HERE/name,{'$schema':'https://json-schema.org/draft/2020-12/schema','type':'object','additionalProperties':False,'required':list(p),'properties':p})
print(json.dumps({'status':plan['status'],'selected':[76,125],'future_hashes_null':4,'runner_sha256':RUNNER},sort_keys=True))
