//! Independent 257-source literal continuation referee for the four K23 sinks.
mod referee {
#![allow(dead_code,unused_imports)]
include!("../unaudited-codex-orbit0-filtered-k18-charge-2026-08-23/run_k18_charge.rs");
use std::fs::rename;
const U23:i128=400_591_699_200;
const SLICES:usize=485;
const NAMES:[&str;4]=["D15:{223,232,322}|R:2-2-4","D15:{223,232,322}|R:2-3-3","D15:{223,232,322}|R:3-2-3","D15:{223,232,322}|R:4-4"];
const IDS:[[&str;3];4]=[
 ["D15:223|R:2-2-4","D15:232|R:2-2-4","D15:322|R:2-2-4"],
 ["D15:223|R:2-3-3","D15:232|R:2-3-3","D15:322|R:2-3-3"],
 ["D15:223|R:3-2-3","D15:232|R:3-2-3","D15:322|R:3-2-3"],
 ["D15:223|R:4-4","D15:232|R:4-4","D15:322|R:4-4"]];
const PATHS:[&[usize];4]=[&[2,2,4],&[2,3,3],&[3,2,3],&[4,4]];
fn packet_row(r:&R8,packet:usize,a:&[u8;4],b:&[u8;4],c:&[u8;4])->Row{match packet{0=>make(r,c,a,b),1=>make(r,a,c,b),2=>make(r,a,b,c),_=>unreachable!()}}
#[derive(Clone)]struct W{a:usize,b:usize,c:usize,ms:Vec<usize>,steps:Vec<(usize,usize)>,terminal:u64,q:i64,scaled:i128}
fn seek(row:&Row,s:[u8;12],positive:i128,degs:&[usize],d:usize,mut ms:Vec<usize>,steps:Vec<(usize,usize)>,e:&E)->Option<W>{
 let ps=avail(s,e);if ps.is_empty(){return None}ms.push(ps.len());let degree=degs[d];
 if d+1==degs.len(){let mut terminal=0u64;let mut q=0i64;for p in ps{for t in &e.tails[p][degree-2]{let child=replace(row,&e.anchors[p],t);let sc=child_sig(s,p,t,e);assert_eq!(sig(&child,e),sc);assert_eq!(sc.iter().map(|&x|x as usize).sum::<usize>(),1);assert!(avail(sc,e).is_empty());terminal+=1;q+=charge(&child,e)}}assert!(terminal>0);let product=ms.iter().product::<usize>()as i128;assert_eq!(U23%product,0);let sign=if degs.len()%2==0{-positive}else{positive};return Some(W{a:0,b:0,c:0,ms,steps,terminal,q,scaled:sign*(U23/product)*(q as i128)})}
 for p in ps{for(ti,t)in e.tails[p][degree-2].iter().enumerate(){let child=replace(row,&e.anchors[p],t);let sc=child_sig(s,p,t,e);assert_eq!(sig(&child,e),sc);let expected=9-degs[..=d].iter().sum::<usize>();assert_eq!(sc.iter().map(|&x|x as usize).sum::<usize>(),expected);if avail(sc,e).is_empty(){continue}let mut next=steps.clone();next.push((p,ti));if let Some(w)=seek(&child,sc,positive,degs,d+1,ms.clone(),next,e){return Some(w)}}}None}
fn witness(e:&E,r:&R8,packet:usize,degs:&[usize])->W{let other:Vec<_>=(0..3).filter(|&x|x!=packet).collect();for(ai,a)in e.factor[other[0]][0].iter().enumerate(){for(bi,b)in e.factor[other[1]][0].iter().enumerate(){for(ci,c)in e.factor[packet][1].iter().enumerate(){let row=packet_row(r,packet,a,b,c);let s=sig(&row,e);assert_eq!(s.iter().map(|&x|x as usize).sum::<usize>(),9);let positive=r.coefficient as i128*r.size as i128;if let Some(mut w)=seek(&row,s,positive,degs,0,Vec::new(),Vec::new(),e){w.a=ai;w.b=bi;w.c=ci;return w}}}}panic!("no literal continuation")}
fn steps(x:&[(usize,usize)])->String{x.iter().map(|(p,t)|format!("{}:{}",p,t)).collect::<Vec<_>>().join(",")}
fn ints(x:&[usize])->String{x.iter().map(|v|v.to_string()).collect::<Vec<_>>().join(",")}
pub fn run(){let args:Vec<_>=std::env::args().collect();let mut count=257usize;let mut out="computations/unaudited-codex-orbit0-k23-direct-k15-four-sink-2026-08-24/results_k23_direct_k15_literal_referee.json".to_string();let mut tsv="computations/unaudited-codex-orbit0-k23-direct-k15-four-sink-2026-08-24/k23_direct_k15_literal_samples.tsv".to_string();let mut i=1;while i<args.len(){match args[i].as_str(){"--count"=>{count=args[i+1].parse().unwrap();i+=2},"--output"=>{out=args[i+1].clone();i+=2},"--tsv"=>{tsv=args[i+1].clone();i+=2},_=>panic!("bad arg")}}assert!((1..=257).contains(&count));let begun=Instant::now();let e=parse();assert_eq!(e.records.len(),SLICES);let labels=["322","232","223"];let mut lines=vec!["ordinal\tsource_slice\tpacket\tpacket_label\tsink\tsource_positive\ta\tb\tc\tintermediate_pivot_tail\tpivot_counts\tterminal_K23_children\tliteral_charge\tweighted_charge_scaled_U".to_string()];let mut samples=[0usize;4];let mut children=[0u64;4];let mut qsum=[0i64;4];let mut scaled=[0i128;4];let mut packets=[[0usize;3];4];
 for j in 0..count{let ri=j*(SLICES-1)/256;let packet=j%3;let positive=e.records[ri].coefficient as i128*e.records[ri].size as i128;for k in 0..4{let w=witness(&e,&e.records[ri],packet,PATHS[k]);samples[k]+=1;packets[k][packet]+=1;children[k]+=w.terminal;qsum[k]+=w.q;scaled[k]+=w.scaled;lines.push(format!("{}\t{}\t{}\t{}\t{}\t{}\t{}\t{}\t{}\t{}\t{}\t{}\t{}\t{}",j,ri,packet,labels[packet],NAMES[k],positive,w.a,w.b,w.c,steps(&w.steps),ints(&w.ms),w.terminal,w.q,w.scaled))}}
 assert_eq!(lines.len(),1+4*count);if count==257{for k in 0..4{assert_eq!(samples[k],257);assert_eq!(packets[k],[86,86,85])}}
 let sink_json=(0..4).map(|k|{let ids=IDS[k].iter().map(|x|format!("\"{}\"",x)).collect::<Vec<_>>().join(",");format!("\"{}\":{{\"strict_grouped_ids\":[{}],\"degrees\":[{}],\"samples\":{},\"packet_witness_counts\":{{\"322\":{},\"232\":{},\"223\":{}}},\"literal_terminal_K23_children\":{},\"literal_charge_sum\":\"{}\",\"sample_weighted_charge_scaled_U\":\"{}\"}}",NAMES[k],ids,PATHS[k].iter().map(|x|x.to_string()).collect::<Vec<_>>().join(","),samples[k],packets[k][0],packets[k][1],packets[k][2],children[k],qsum[k],scaled[k])}).collect::<Vec<_>>().join(",");
 let status=if count==257{"PASS_INDEPENDENT_257_DISTRIBUTED_LITERAL_DIRECT_K15_FOUR_SINK_K23_REPLAY"}else{"PASS_BOUNDED_LITERAL_DIRECT_K15_FOUR_SINK_K23_GATE"};let text=format!("{{\n  \"status\":\"{}\",\n  \"source_samples\":{},\n  \"first_slice\":0,\n  \"last_slice\":{},\n  \"sinks\":{{{}}},\n  \"all_divisions_exact\":true,\n  \"all_literal_K23_children_terminal\":true,\n  \"terminal_anchor_signature_mass\":1,\n  \"source_provenance_preserved_through_all_pivots\":true,\n  \"cache_abstraction_used\":false,\n  \"elapsed_seconds\":{:.6},\n  \"scope\":\"257 distributed nonzero literal continuations only; not a full scalar pass; no rows or K24\"\n}}\n",status,count,(count-1)*(SLICES-1)/256,sink_json,begun.elapsed().as_secs_f64());let ttmp=format!("{}.tmp",tsv);std::fs::write(&ttmp,format!("{}\n",lines.join("\n"))).unwrap();rename(ttmp,&tsv).unwrap();let otmp=format!("{}.tmp",out);std::fs::write(&otmp,&text).unwrap();rename(otmp,&out).unwrap();print!("{}",text)}
}
fn main(){referee::run()}
