#!/usr/bin/env python3
"""Render a core refutation for the kernel-reducible RUP checker.

UNAUDITED — lane L1.

Emits, for one orbit:

    def coreCNF   : List Rup.Clause     -- the UNSAT core, DIMACS lit v -> (v-1, v>0)
    def coreSteps : List Rup.Step       -- RUP additions, hints as store indices
    theorem coreUnsat : Rup.Unsat coreCNF := Rup.check_sound _ _ (by decide)

The store is `coreCNF.toArray` followed by one `push` per step, so LRAT clause
ids map to store indices as

    original id k (1-based)  ->  index k - 1
    j-th derived clause      ->  index (#core clauses) + j

Deletions are dropped: the Lean checker ignores them, and dropping them only
leaves more clauses in the store, which is sound (see `Rup.lean`).

RAT steps are rejected loudly; every certificate this project uses is RUP-only.

Usage: python3 gen_rup_core.py <orbit> <out.lean> [--native]
"""
from __future__ import annotations

import os
import sys

LANE = ("/Users/rishi/workplace/krenn-conjecture/computations/"
        "unaudited-lean-l1-2026-08-20")
CORES = f"{LANE}/cores/n8z0"


def read_cnf(path):
    cls = []
    for line in open(path):
        line = line.strip()
        if not line or line[0] in "cp":
            continue
        toks = line.split()
        assert toks[-1] == "0", line
        cls.append([int(t) for t in toks[:-1]])
    return cls


def read_lrat(path):
    acts = []
    for line in open(path):
        toks = line.split()
        if not toks:
            continue
        ident = int(toks[0])
        if len(toks) > 1 and toks[1] == "d":
            continue                     # deletions are ignored, soundly
        rest = [int(t) for t in toks[1:]]
        z = rest.index(0)
        lits, tail = rest[:z], rest[z + 1:]
        assert tail and tail[-1] == 0, line
        hints = tail[:-1]
        if any(h < 0 for h in hints):
            raise SystemExit(
                f"RAT step in {path}: negative hint. The Lean checker is "
                f"RUP-only; extend it before using this certificate.")
        acts.append((ident, lits, hints))
    return acts


def lit(l: int) -> str:
    return f"({abs(l) - 1}, {'true' if l > 0 else 'false'})"


def main():
    orbit = int(sys.argv[1])
    out = sys.argv[2]
    native = "--native" in sys.argv
    cnf = read_cnf(f"{CORES}/core_{orbit}.cnf")
    acts = read_lrat(f"{CORES}/core_{orbit}.lrat")

    M = len(cnf)
    idx = {k + 1: k for k in range(M)}          # LRAT id -> store index
    steps = []
    for j, (ident, lits, hints) in enumerate(acts):
        mapped = []
        for h in hints:
            if h not in idx:
                raise SystemExit(f"orbit {orbit}: hint {h} refers to an unknown "
                                 f"clause id (deleted then reused?)")
            mapped.append(idx[h])
        steps.append((lits, mapped))
        idx[ident] = M + j
    if steps[-1][0]:
        raise SystemExit(f"orbit {orbit}: last step is not the empty clause")

    tac = "native_decide" if native else "decide +kernel"
    L = [
        "/-",
        "UNAUDITED (lane L1 staging) — generated by encoder/gen_rup_core.py.",
        f"Kernel-checked refutation of orbit {orbit} of the 87-case ledger.",
        "",
        "`coreCNF` is the drat-trim-extracted UNSAT core of",
        f"  canonical/n8z0/n8z0k4_{orbit}.cnf",
        "and every one of its clauses occurs verbatim in that file, checked by",
        "encoder/emit_cores.py, which refuses to emit otherwise. A subset of an",
        "unsatisfiable set is unsatisfiable, so the core never strengthens the claim.",
        "",
        "No `partial` definition and no compiler-executed code lies on the",
        "reduction path: `Rup.check` is structurally recursive and `decide`",
        "discharges it in the kernel.",
        "-/",
        "import N8Diagonal.Rup",
        "",
        "-- The clause and step literals are large; both the elaborator's",
        "-- heartbeat budget and its recursion depth must be raised at FILE level,",
        "-- not merely on the theorem, or the definitions themselves fail to",
        "-- elaborate and the theorem then reports an unknown identifier.",
        "set_option maxHeartbeats 4000000",
        "set_option maxRecDepth 1000000",
        "",
        f"namespace N8Diagonal.Orbit{orbit}",
        "",
        "open N8Diagonal.Rup",
        "",
        f"/-- The UNSAT core of orbit {orbit}: {M} clauses. -/",
        "def coreCNF : List Clause :=",
        "  [" + ",\n   ".join("[" + ", ".join(lit(l) for l in c) + "]" for c in cnf) + "]",
        "",
        f"/-- The RUP refutation: {len(steps)} steps. -/",
        "def coreSteps : List Step :=",
        "  [" + ",\n   ".join(
            "⟨[" + ", ".join(lit(l) for l in c) + "], ["
            + ", ".join(map(str, h)) + "]⟩" for c, h in steps) + "]",
        "",
        "/-- The refutation, checked by the kernel. -/",
        "theorem coreUnsat : Unsat coreCNF :=",
        f"  check_sound coreCNF coreSteps (by {tac})",
        "",
        f"end N8Diagonal.Orbit{orbit}",
    ]
    open(out, "w").write("\n".join(L) + "\n")
    print(f"orbit {orbit}: {M} clauses, {len(steps)} steps, "
          f"{sum(len(h) for _, h in steps)} hints -> {out} "
          f"({os.path.getsize(out)} bytes, tactic={tac})")


if __name__ == "__main__":
    main()
