#!/usr/bin/env python3
"""T2(b) -- reproduce the committed 3P2 odd-holonomy certificate by Laurent
elimination, then run the spanning-tree pairing-scheme test against it.

Method (this is the repo's own elimination, rebuilt):
  * relations R = {(lambda, value)} with x^lambda = value in Q^*.
    seeds:  two-term mixed fibres            value -1
            2x2 minors of the rank-one blocks value +1
  * L = the lattice generated by the lambdas, with the character
    rho : L -> Q^*.  Consistency is checked at every step.
  * a multi-term mixed fibre sum_k m_k = 0 is reduced by merging terms whose
    exponent difference lies in L (m' = rho(exp m' - exp m) * m).
      - one surviving class with nonzero coefficient  -> O2 kill
      - exactly two classes (c0, c1)                  -> NEW relation
        x^{exp(r1)-exp(r0)} = -c0/c1
  * iterate to a fixed point; the obstruction O1 is an integer dependency
    sum n_r lambda_r = 0 with prod value_r^{n_r} != 1.

All arithmetic exact (Python ints / Fraction).
"""
from collections import Counter, defaultdict
from fractions import Fraction as Q
from itertools import combinations, product
import json

import fliptree_lib as F

out = {"pinned_head": open("PINNED_HEAD.txt").read().strip()}
N = 6
PALETTE = (0, 1, 2)
MATCHINGS = F.all_matchings(N)
MIDX = {M: i for i, M in enumerate(MATCHINGS)}

RANK_ONE = {(0, 2): ((0,), (0,)), (0, 3): ((2,), (2,)), (0, 4): ((0,), (1,)),
            (0, 5): ((0, 1, 2), (0, 1, 2)), (1, 2): ((1,), (0,)),
            (1, 3): ((0, 1, 2), (0, 1, 2)), (1, 4): ((2,), (2,)),
            (1, 5): ((1,), (1,)), (2, 4): ((0, 1, 2), (0, 1, 2)),
            (2, 5): ((2,), (2,)), (3, 4): ((1,), (1,)), (3, 5): ((0,), (0,))}
EXCEPTIONAL = [(0, 1), (2, 3), (4, 5)]
S = frozenset([(u, v, i, j) for (u, v) in EXCEPTIONAL
               for i, j in product(PALETTE, repeat=2)]
              + [(u, v, i, j) for (u, v), (L, R) in RANK_ONE.items()
                 for i in L for j in R])

CELLS = sorted(S)
CIDX = {c: i for i, c in enumerate(CELLS)}
NC = len(CELLS)


def vec(d):
    v = [0] * NC
    for c, e in d.items():
        v[CIDX[c]] += e
    return v


def expvec(M, chi):
    return vec({F.cell(u, v, chi): 1 for u, v in M})


def vsub(a, b):
    return [x - y for x, y in zip(a, b)]


# --------------------------------------------------------- live occurrences
live = defaultdict(list)
for chi in product(PALETTE, repeat=N):
    for M in MATCHINGS:
        if all(F.cell(u, v, chi) in S for u, v in M):
            live[chi].append(M)
out["live_occurrences"] = sum(len(v) for v in live.values())
out["matching_lex_index_check"] = {
    "M0": repr(MATCHINGS[0]), "M1": repr(MATCHINGS[1]),
    "M3": repr(MATCHINGS[3]), "M13": repr(MATCHINGS[13]),
    "M14": repr(MATCHINGS[14])}


# --------------------------------------------------- lattice with provenance
class Lattice:
    """Integer lattice in Z^NC with a Q^* character, maintained in echelon
    form with provenance so that rho is computable on any member."""

    def __init__(self):
        self.rows = []          # (pivot, vector, value)  echelon by pivot

    def _reduce(self, v, val):
        v = list(v)
        val = Q(val)
        for p, w, wv in self.rows:
            if v[p]:
                q, r = divmod(v[p], w[p])
                if q:
                    v = [a - q * b for a, b in zip(v, w)]
                    val = val / (wv ** q) if q > 0 else val * (wv ** (-q))
                if v[p]:
                    # need a gcd step: swap roles
                    return v, val, p
        return v, val, None

    def add(self, v, val):
        """Insert x^v = val.  Returns 'consistent' bool."""
        v = list(v)
        val = Q(val)
        while True:
            piv = None
            for i in range(NC):
                if v[i]:
                    piv = i
                    break
            if piv is None:
                return val == 1          # 0 = trivial: value must be 1
            hit = None
            for k, (p, w, wv) in enumerate(self.rows):
                if p == piv:
                    hit = k
                    break
            if hit is None:
                if v[piv] < 0:
                    v = [-x for x in v]
                    val = Q(1) / val
                self.rows.append((piv, v, val))
                self.rows.sort(key=lambda t: t[0])
                return True
            p, w, wv = self.rows[hit]
            if abs(w[piv]) <= abs(v[piv]):
                q = v[piv] // w[piv]
                v = [a - q * b for a, b in zip(v, w)]
                val = val / (wv ** q) if q >= 0 else val * (wv ** (-q))
            else:
                self.rows[hit] = (piv, v, val)
                v, val = w, wv
                q = v[piv] // self.rows[hit][1][piv]
                v = [a - q * b for a, b in zip(v, self.rows[hit][1])]
                val = val / (self.rows[hit][2] ** q)

    def member_value(self, v):
        """If v is in the lattice return its rho value, else None."""
        v = list(v)
        val = Q(1)
        for p, w, wv in self.rows:
            if v[p]:
                if v[p] % w[p]:
                    return None
                q = v[p] // w[p]
                v = [a - q * b for a, b in zip(v, w)]
                val = val * (wv ** q)
        if any(v):
            return None
        return val


LAT = Lattice()
seeds = []
inconsistent = []

for (u, v), (L, R) in RANK_ONE.items():
    if len(L) < 2 or len(R) < 2:
        continue
    for i, ip in combinations(L, 2):
        for j, jp in combinations(R, 2):
            mu = vec({(u, v, i, j): 1, (u, v, ip, jp): 1,
                      (u, v, i, jp): -1, (u, v, ip, j): -1})
            seeds.append(("minor", (u, v), mu, Q(1)))

two_term = 0
for chi in sorted(live):
    if len(set(chi)) == 1:
        continue
    Ms = sorted(live[chi])
    if len(Ms) == 2:
        two_term += 1
        lam = vsub(expvec(Ms[0], chi), expvec(Ms[1], chi))
        seeds.append(("fibre2", chi, lam, Q(-1)))

for kind, tag, lam, val in seeds:
    if not LAT.add(lam, val):
        inconsistent.append((kind, repr(tag)))
out["seed_relations"] = len(seeds)
out["seed_two_term_fibres"] = two_term
out["seed_minors"] = len(seeds) - two_term
out["lattice_rank_after_seeds"] = len(LAT.rows)
out["seeds_consistent"] = not inconsistent

# ------------------------------------------------------- Laurent elimination
rounds = []
kills = []
for it in range(12):
    new_rel = 0
    reduced = 0
    for chi in sorted(live):
        if len(set(chi)) == 1:
            continue
        Ms = sorted(live[chi])
        if len(Ms) < 3:
            continue
        reps = []                       # (rep_M, coefficient)
        for M in Ms:
            ev = expvec(M, chi)
            placed = False
            for k, (rM, coef) in enumerate(reps):
                r = LAT.member_value(vsub(ev, expvec(rM, chi)))
                if r is not None:
                    reps[k] = (rM, coef + r)
                    placed = True
                    break
            if not placed:
                reps.append((M, Q(1)))
        nz = [(rM, c) for rM, c in reps if c != 0]
        if len(reps) < len(Ms):
            reduced += 1
        if len(nz) == 1:
            kills.append({"chi": "".join(map(str, chi)),
                          "type": "O2 single class, nonzero",
                          "terms": len(Ms)})
        elif len(nz) == 2:
            (A, c0), (B, c1) = nz
            lam = vsub(expvec(B, chi), expvec(A, chi))
            val = Q(-c0) / c1
            cur = LAT.member_value(lam)
            if cur is None:
                assert LAT.add(lam, val), "new relation inconsistent"
                new_rel += 1
            elif cur != val:
                kills.append({"chi": "".join(map(str, chi)),
                              "type": "O1 value clash",
                              "existing": str(cur), "forced": str(val),
                              "terms": len(Ms),
                              "A": repr(A), "B": repr(B),
                              "A_index": MIDX[A], "B_index": MIDX[B],
                              "c0": str(c0), "c1": str(c1)})
    rounds.append({"round": it, "fibres_reduced": reduced,
                   "new_relations": new_rel,
                   "lattice_rank": len(LAT.rows),
                   "kills_so_far": len(kills)})
    if new_rel == 0:
        break
out["elimination_rounds"] = rounds
out["obstructions_found"] = kills[:20]
out["n_obstructions"] = len(kills)
out["O1_value_clashes"] = sum(1 for k in kills if k["type"].startswith("O1"))
out["O2_single_class"] = sum(1 for k in kills if k["type"].startswith("O2"))
out["support_is_killed"] = bool(kills)

# ---- the character's values: is any -1 forced on a trivial-exponent class?
vals = Counter(str(r[2]) for r in LAT.rows)
out["character_values_on_lattice_basis"] = sorted(vals.items())

json.dump(out, open("t2b_laurent.json", "w"), indent=1, sort_keys=True)
print(json.dumps(out, indent=1, sort_keys=True)[:6000])
