#!/usr/bin/env python3
"""Hostiles for exact rep4 all-162 ledger, structural branch, and future coverage."""
import copy,hashlib,json,os
from pathlib import Path
HERE=Path(__file__).resolve().parent
def sha(path):return hashlib.sha256(path.read_bytes()).hexdigest()
def validate(result,future):
 assert result['schema']=='KRENN_X5_REP4_ALL162_TERMINAL_PROMOTION_CONDITIONAL_DESIGN_V1' and result['status']=='HELD_PROMOTION_FOUR_FUTURE_PASS_SEALS_ABSENT';c=result['authoritative_contraction'];assert c['raw_charts']==972 and c['canonical_s3_charts']==162 and c['members_per_chart']==6 and c['y_groups']==c['z_groups']==81 and c['y_raw']==c['z_raw']==486 and c['independent_referee_pass'] is True
 rank0=result['rank_zero_structural_branch'];assert rank0['representative_id']==4 and rank0['scope']==[0] and rank0['outside_pair']=='47' and 'A47=0' in rank0['zero_outside_implication'] and 'L67=0' in rank0['zero_outside_implication'] and 'nonzero pairing-only claims are not used' in rank0['source_pin_scope']
 group0=result['sealed_group0'];assert group0['group_id']==0 and group0['chart']==[0,0,0,0,'y',0,0,1] and group0['family']=='y' and group0['unit_remainder']==0 and group0['dependency_hashes_null'] is False
 expected=[[0],list(range(1,26)),list(range(26,76)),list(range(76,126)),list(range(126,162))];assert [s['group_ids'] for s in result['closure_shards']]==expected;flat=sum(expected,[]);assert flat==list(range(162)) and len(flat)==len(set(flat))==162 and result['prospective_union_proof']=={'group_count':162,'union':list(range(162)),'duplicates':[],'missing':[],'extra':[],'all_four_future_required':True}
 transport=result['raw_s3_transport'];assert [x['group_id'] for x in transport]==list(range(162)) and all(x['raw_member_count']==len(x['raw_s3_members'])==6 for x in transport);raw=[tuple(m) for x in transport for m in x['raw_s3_members']];assert len(raw)==len(set(raw))==972 and sum(x['family']=='y' for x in transport)==sum(x['family']=='z' for x in transport)==81 and sum(m[4]=='y' for m in raw)==sum(m[4]=='z' for m in raw)==486
 scope=result['scope'];assert scope['representative']=='rep4 only' and scope['cross_representative_transport'] is False and scope['other_representatives_closed']==[] and scope['full_conjecture'] is False and scope['promotion_currently_authorized'] is False and scope['solver_runs']==0
 assert future['status']=='UNSATISFIED_FOUR_NULL_HASH_PAIRS' and future['sealed_group0'] is True and future['satisfied'] is False and [d['group_ids'] for d in future['dependencies']]==expected[1:] and all(d['manifest_sha256'] is d['result_sha256'] is None and d['satisfied'] is False for d in future['dependencies'])
result=json.loads((HERE/'results_terminal_promotion_design.json').read_text());future=json.loads((HERE/'future_dependencies.json').read_text());validate(result,future);tests={}
def reject(name,mutate):
 r,f=copy.deepcopy(result),copy.deepcopy(future);mutate(r,f)
 try:validate(r,f)
 except (AssertionError,KeyError,TypeError):tests[name]=True
 else:tests[name]=False
reject('missing_group',lambda r,f:r['closure_shards'][2]['group_ids'].pop());reject('duplicate_group',lambda r,f:r['closure_shards'][3]['group_ids'].__setitem__(0,75));reject('extra_group',lambda r,f:r['closure_shards'][4]['group_ids'].append(162));reject('group0_unsealed',lambda r,f:r['sealed_group0'].__setitem__('dependency_hashes_null',True));reject('group0_wrong_chart',lambda r,f:r['sealed_group0']['chart'].__setitem__(4,'z'));reject('rank_zero_scope_removed',lambda r,f:r['rank_zero_structural_branch'].__setitem__('scope',[]));reject('rank_zero_expanded',lambda r,f:r['rank_zero_structural_branch'].__setitem__('scope',[0,1]));reject('missing_raw_member',lambda r,f:r['raw_s3_transport'][0]['raw_s3_members'].pop());reject('duplicate_raw_member',lambda r,f:r['raw_s3_transport'][1]['raw_s3_members'].__setitem__(0,r['raw_s3_transport'][0]['raw_s3_members'][0]));reject('drop_y_group',lambda r,f:r['raw_s3_transport'][0].__setitem__('family','z'));first_z=next(i for i,x in enumerate(result['raw_s3_transport']) if x['family']=='z');reject('drop_z_raw',lambda r,f:r['raw_s3_transport'][first_z]['raw_s3_members'][0].__setitem__(4,'y'));reject('cross_rep_transport',lambda r,f:r['scope'].__setitem__('cross_representative_transport',True));reject('other_rep_closed',lambda r,f:r['scope'].__setitem__('other_representatives_closed',[1]));reject('full_conjecture',lambda r,f:r['scope'].__setitem__('full_conjecture',True));reject('future_null_treated_satisfied',lambda r,f:f.__setitem__('satisfied',True));reject('future_hash_injected',lambda r,f:f['dependencies'][0].__setitem__('manifest_sha256','0'*64));assert len(tests)==16 and all(tests.values())
out={'schema':'KRENN_X5_REP4_ALL162_PROMOTION_HOSTILE_TESTS_V1','status':'PASS_EXACT_LEDGER_AND_16_HOSTILES','design_sha256':sha(HERE/'results_terminal_promotion_design.json'),'future_dependencies_sha256':sha(HERE/'future_dependencies.json'),'hostile_tests':tests,'hostile_count':16,'solver_runs':0};tmp=HERE/'results_hostile_tests.json.tmp';tmp.write_text(json.dumps(out,indent=2,sort_keys=True)+'\n');os.replace(tmp,HERE/'results_hostile_tests.json');print(json.dumps({'status':out['status'],'hostiles':16,'solver_runs':0},sort_keys=True))
