#!/usr/bin/env python3
"""Complete homogeneous d6 incidence guard for the lex-first y10*t^2 row.

The chart encoding suppresses t: a total-degree-D monomial represented by k
off-support bytes has t exponent D-k.  The target has total degree 12 and is
represented by ten y bytes, hence carries t^2.  Its homogeneous degree-six
divisors therefore have encoded y lengths 4, 5, or 6 (t exponents 2, 1, 0).

This checker streams every degree-six Macaulay column generated by original
d4 rows times homogeneous degree two and all complete d5 cells times
homogeneous degree one, but materializes only columns incident to one of the
target divisors.  Zero incidence is a pivot obstruction.  Nonzero incidence
is exported honestly and requires a connected-block solve.
"""

from collections import Counter, defaultdict
from hashlib import sha256
import importlib.util
from itertools import combinations
import json
from pathlib import Path


HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
COMPLETE_PATH = ROOT / "computations/verify_n8_chart26_complete_degree5_buchberger.py"
RESULTS = HERE / "results_y10_dead_row_complete_d6.json"


def require(condition, detail):
    if not condition:
        raise RuntimeError(detail)


spec = importlib.util.spec_from_file_location("y10_dead_complete_d6", COMPLETE_PATH)
COMPLETE = importlib.util.module_from_spec(spec)
require(spec.loader is not None, "cannot load complete d5 checker")
spec.loader.exec_module(COMPLETE)
FIRST = COMPLETE.FIRST


def quotient(dividend, divisor):
    answer = list(dividend)
    for value in divisor:
        require(value in answer, "requested non-divisor quotient")
        answer.remove(value)
    return bytes(answer)


def target_divisors(target, total_degree, target_t_exponent):
    answer = []
    by_t = {}
    for t_exponent in range(target_t_exponent + 1):
        y_degree = total_degree - t_exponent
        rows = sorted({
            bytes(target[index] for index in positions)
            for positions in combinations(range(len(target)), y_degree)
        })
        by_t[t_exponent] = rows
        answer.extend(rows)
    require(len(answer) == len(set(answer)), "cross-y-degree divisor collision")
    return sorted(answer, key=lambda row: (len(row), row)), by_t


def build_subterm_index(divisors, source_degree, multiplier_degree):
    """Map every possible encoded source term to target divisors it can hit."""
    index = defaultdict(set)
    for divisor in divisors:
        minimum = max(0, len(divisor) - multiplier_degree)
        maximum = min(source_degree, len(divisor))
        for degree in range(minimum, maximum + 1):
            for positions in combinations(range(len(divisor)), degree):
                row = bytes(divisor[index] for index in positions)
                index[row].add(divisor)
    return index


def main():
    target = bytes.fromhex("0111202020494f4f50f8")
    target_total_degree = 12
    target_t_exponent = target_total_degree - len(target)
    require(target_t_exponent == 2, "target t exponent changed")
    divisors, by_t = target_divisors(target, 6, target_t_exponent)
    require({key: len(value) for key, value in by_t.items()}
            == {0: 72, 1: 82, 2: 72}, "homogeneous d6 divisor census changed")

    original_index = build_subterm_index(divisors, 4, 2)
    degree5_index = build_subterm_index(divisors, 5, 1)
    originals, lead_to_code = FIRST.original_basis()
    code_to_lead = {code: lead for lead, code in lead_to_code.items()}
    pairs, _cores, _histogram = COMPLETE.build_pairs(code_to_lead)
    target_y4_divisors = set(by_t[2])
    target_y5_divisors = set(by_t[1])
    original_leads_dividing_target = sorted(
        lead.hex() for lead in lead_to_code if lead in target_y4_divisors
    )

    original_columns = defaultdict(Counter)
    original_terms_scanned = 0
    for code, polynomial in originals.items():
        for row, coefficient in polynomial.items():
            original_terms_scanned += 1
            for divisor in sorted(original_index.get(row, ())):
                multiplier = quotient(divisor, row)
                require(len(multiplier) <= 2, "original multiplier exceeds d2")
                original_columns[(code, multiplier)][divisor] += coefficient

    degree5_columns = defaultdict(Counter)
    degree5_terms_scanned = 0
    degree5_leads_dividing_target = []
    stream_digest = sha256()
    for cell_index, (lcm, first_code, second_code) in enumerate(pairs, 1):
        polynomial = COMPLETE.s_polynomial(
            lcm, first_code, second_code, originals, code_to_lead
        )
        lead = FIRST.leading_monomial(polynomial)
        if lead in target_y5_divisors:
            degree5_leads_dividing_target.append(
                [cell_index, lead.hex(), first_code, second_code]
            )
        for row, coefficient in polynomial.items():
            degree5_terms_scanned += 1
            for divisor in sorted(degree5_index.get(row, ())):
                multiplier = quotient(divisor, row)
                require(len(multiplier) <= 1, "d5 multiplier exceeds d1")
                degree5_columns[(cell_index, multiplier)][divisor] += coefficient
                stream_digest.update(cell_index.to_bytes(4, "big"))
                stream_digest.update(bytes((len(multiplier),)))
                stream_digest.update(multiplier)
                stream_digest.update(divisor)
                stream_digest.update(b"+" if coefficient > 0 else b"-")

    def clean(columns):
        answer = {}
        for key, values in columns.items():
            values = Counter({row: value for row, value in values.items() if value})
            if values:
                answer[key] = values
        return answer

    original_columns = clean(original_columns)
    degree5_columns = clean(degree5_columns)
    row_incidence = Counter()
    for values in original_columns.values():
        row_incidence.update(values.keys())
    for values in degree5_columns.values():
        row_incidence.update(values.keys())

    records = []
    for (code, multiplier), values in sorted(original_columns.items()):
        records.append({
            "kind": "original_times_homogeneous_d2",
            "source_code": code,
            "multiplier_y": multiplier.hex(),
            "multiplier_t_exponent": 2 - len(multiplier),
            "target_rows": [[row.hex(), value.numerator, value.denominator]
                            for row, value in sorted(values.items())],
        })
    for (cell_index, multiplier), values in sorted(degree5_columns.items()):
        lcm, first_code, second_code = pairs[cell_index - 1]
        records.append({
            "kind": "degree5_cell_times_homogeneous_d1",
            "cell_index": cell_index,
            "source_codes": [first_code, second_code],
            "source_lcm": lcm.hex(),
            "multiplier_y": multiplier.hex(),
            "multiplier_t_exponent": 1 - len(multiplier),
            "target_rows": [[row.hex(), int(value), 1]
                            for row, value in sorted(values.items())],
        })

    status = ("EXACT_NO_HOMOGENEOUS_D6_INCIDENCE" if not records else
              "HOMOGENEOUS_D6_INCIDENCE_REQUIRES_CONNECTED_BLOCK_SOLVE")
    result = {
        "format": "n8-orbit26-y10-dead-row-complete-homogeneous-d6-v2",
        "status": status,
        "supersedes_t_free_v1": True,
        "target_y10_row": target.hex(),
        "target_total_degree": target_total_degree,
        "target_t_exponent": target_t_exponent,
        "divisor_total_degree": 6,
        "divisor_census_by_t_exponent": {
            str(key): len(value) for key, value in sorted(by_t.items())
        },
        "distinct_homogeneous_divisors": len(divisors),
        "original_generators": len(originals),
        "original_terms_scanned": original_terms_scanned,
        "complete_degree5_cells": len(pairs),
        "complete_degree5_terms_scanned": degree5_terms_scanned,
        "original_leads_dividing_target": original_leads_dividing_target,
        "degree5_leads_dividing_target": degree5_leads_dividing_target,
        "original_incident_columns": len(original_columns),
        "degree5_incident_columns": len(degree5_columns),
        "total_incident_columns": len(records),
        "incident_target_rows": len(row_incidence),
        "incident_row_t_histogram": dict(sorted(Counter(
            6 - len(row) for row in row_incidence).items())),
        "incident_records": records,
        "incident_stream_sha256": stream_digest.hexdigest(),
        "theorem_if_empty": (
            "No homogeneous degree-six divisor of y10*t^2 occurs in any d6 "
            "Macaulay column generated by originals*d2 or complete-d5*d1; hence "
            "none can be a pivot or a d6-cell leading monomial in that span."
        ),
        "scope_if_nonempty": (
            "This is a complete literal incidence census only. Nonzero incidence "
            "does not decide pivot status until connected blocks are reduced."
        ),
        "source_sha256": sha256(COMPLETE_PATH.read_bytes()).hexdigest(),
    }
    encoded = json.dumps(result, sort_keys=True, separators=(",", ":"))
    result["logical_sha256"] = sha256(encoded.encode("ascii")).hexdigest()
    RESULTS.write_text(json.dumps(result, indent=2, sort_keys=True) + "\n")
    print("y10 complete homogeneous d6 incidence:", status)
    print("divisors/original-cols/d5-cols/rows:", len(divisors),
          len(original_columns), len(degree5_columns), len(row_incidence))
    print("logical sha256:", result["logical_sha256"])


if __name__ == "__main__":
    main()
