#!/usr/bin/env python3
"""Target-local homogeneous d7 incidence for the lex-first y10*t^2 row.

The homogenized chart encodes only off-support variables; a homogeneous
degree-D monomial of encoded length e has t exponent D-e.  The target has
total degree twelve, so its d7 divisors have y lengths 7, 6, or 5.  Such a
divisor can occur in degree seven only in

  * an original d4 term times a homogeneous degree-three multiplier, or
  * a complete d5-cell term times a homogeneous degree-two multiplier.

The checker streams the complete 6,558 + 84,005 source packet and records
every such literal incident column.  If the census is empty, no d7 element
in the full span generated by originals*y3 and complete-d5*y2 can have one
of the target divisors as a row (and hence none can pivot there).  A nonempty
census is exported with source labels for a separate connected-block solve.
"""

from collections import Counter, defaultdict
from hashlib import sha256
import importlib.util
from itertools import combinations
import json
from pathlib import Path


HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
COMPLETE_PATH = ROOT / "computations/verify_n8_chart26_complete_degree5_buchberger.py"
RESULTS = HERE / "results_y10_dead_row_complete_d7.json"


def require(condition, detail):
    if not condition:
        raise RuntimeError(detail)


spec = importlib.util.spec_from_file_location("y10_dead_complete_d7", COMPLETE_PATH)
COMPLETE = importlib.util.module_from_spec(spec)
require(spec.loader is not None, "cannot load complete d5 checker")
spec.loader.exec_module(COMPLETE)
FIRST = COMPLETE.FIRST


def target_divisors(target, total_degree, target_t_exponent):
    answer = []
    by_t = {}
    for t_exponent in range(target_t_exponent + 1):
        y_degree = total_degree - t_exponent
        rows = sorted({
            bytes(target[index] for index in positions)
            for positions in combinations(range(len(target)), y_degree)
        })
        by_t[t_exponent] = rows
        answer.extend(rows)
    require(len(answer) == len(set(answer)), "cross-y-degree divisor collision")
    return sorted(answer, key=lambda row: (len(row), row)), by_t


def build_subterm_index(divisors7, source_degree, multiplier_degree):
    index = defaultdict(set)
    for divisor7 in divisors7:
        minimum = max(0, len(divisor7) - multiplier_degree)
        maximum = min(source_degree, len(divisor7))
        for degree in range(minimum, maximum + 1):
            for positions in combinations(range(len(divisor7)), degree):
                subterm = bytes(divisor7[position] for position in positions)
                index[subterm].add(divisor7)
    return index


def quotient(dividend, divisor):
    answer = list(dividend)
    for value in divisor:
        require(value in answer, "requested non-divisor quotient")
        answer.remove(value)
    return bytes(answer)


def main():
    target = bytes.fromhex("0111202020494f4f50f8")
    target_total_degree = 12
    target_t_exponent = target_total_degree - len(target)
    require(target_t_exponent == 2, "target t exponent changed")
    divisors7, by_t = target_divisors(target, 7, target_t_exponent)
    require({key: len(value) for key, value in by_t.items()}
            == {0: 48, 1: 72, 2: 82}, "degree-seven divisor census changed")
    index4 = build_subterm_index(divisors7, 4, 3)
    index5 = build_subterm_index(divisors7, 5, 2)

    originals, lead_to_code = FIRST.original_basis()
    code_to_lead = {code: lead for lead, code in lead_to_code.items()}
    pairs, _cores, _histogram = COMPLETE.build_pairs(code_to_lead)

    # A column is (source label, encoded-y multiplier).  Aggregate its target
    # rows exactly, in case repeated source terms ever collide after a
    # multiplier (the current source is squarefree, but the guard is cheap).
    original_columns = defaultdict(Counter)
    original_terms_scanned = 0
    for code, polynomial in originals.items():
        for row, coefficient in polynomial.items():
            original_terms_scanned += 1
            for divisor7 in sorted(index4.get(row, ())):
                multiplier = quotient(divisor7, row)
                require(len(multiplier) <= 3, "original multiplier exceeds d3")
                original_columns[(code, multiplier)][divisor7] += coefficient

    degree5_columns = defaultdict(Counter)
    degree5_terms_scanned = 0
    degree5_stream_digest = sha256()
    for cell_index, (lcm, first_code, second_code) in enumerate(pairs, 1):
        polynomial = COMPLETE.s_polynomial(
            lcm, first_code, second_code, originals, code_to_lead
        )
        for row, coefficient in polynomial.items():
            degree5_terms_scanned += 1
            for divisor7 in sorted(index5.get(row, ())):
                multiplier = quotient(divisor7, row)
                require(len(multiplier) <= 2, "d5 multiplier exceeds d2")
                degree5_columns[(cell_index, multiplier)][divisor7] += coefficient
                degree5_stream_digest.update(cell_index.to_bytes(4, "big"))
                degree5_stream_digest.update(multiplier)
                degree5_stream_digest.update(divisor7)
                degree5_stream_digest.update(b"+" if coefficient > 0 else b"-")

    original_columns = {
        key: Counter({row: value for row, value in values.items() if value})
        for key, values in original_columns.items()
    }
    original_columns = {key: values for key, values in original_columns.items()
                        if values}
    degree5_columns = {
        key: Counter({row: value for row, value in values.items() if value})
        for key, values in degree5_columns.items()
    }
    degree5_columns = {key: values for key, values in degree5_columns.items()
                       if values}

    target_row_incidence = Counter()
    for values in original_columns.values():
        target_row_incidence.update(values.keys())
    for values in degree5_columns.values():
        target_row_incidence.update(values.keys())

    incident_records = []
    for (code, multiplier), values in sorted(original_columns.items()):
        incident_records.append({
            "kind": "original_times_homogeneous_d3",
            "source_code": code,
            "multiplier_y": multiplier.hex(),
            "multiplier_t_exponent": 3 - len(multiplier),
            "target_rows": [
                [row.hex(), value.numerator, value.denominator]
                for row, value in sorted(values.items())
            ],
        })
    for (cell_index, multiplier), values in sorted(degree5_columns.items()):
        lcm, first_code, second_code = pairs[cell_index - 1]
        incident_records.append({
            "kind": "degree5_cell_times_homogeneous_d2",
            "cell_index": cell_index,
            "source_codes": [first_code, second_code],
            "source_lcm": lcm.hex(),
            "multiplier_y": multiplier.hex(),
            "multiplier_t_exponent": 2 - len(multiplier),
            "target_rows": [
                [row.hex(), int(value), 1]
                for row, value in sorted(values.items())
            ],
        })

    status = ("EXACT_NO_HOMOGENEOUS_D7_INCIDENCE" if not incident_records
              else "HOMOGENEOUS_D7_INCIDENCE_REQUIRES_CONNECTED_BLOCK_SOLVE")
    result = {
        "format": "n8-orbit26-y10-dead-row-complete-homogeneous-d7-v2",
        "status": status,
        "target_y10_row": target.hex(),
        "target_total_degree": target_total_degree,
        "target_t_exponent": target_t_exponent,
        "divisor_total_degree": 7,
        "divisor_census_by_t_exponent": {
            str(key): len(value) for key, value in sorted(by_t.items())
        },
        "distinct_degree7_divisors": len(divisors7),
        "degree7_divisors": [row.hex() for row in divisors7],
        "original_generators": len(originals),
        "original_terms_scanned": original_terms_scanned,
        "complete_degree5_cells": len(pairs),
        "complete_degree5_terms_scanned": degree5_terms_scanned,
        "original_times_homogeneous_d3_incident_columns": len(original_columns),
        "degree5_times_homogeneous_d2_incident_columns": len(degree5_columns),
        "total_incident_columns": len(incident_records),
        "incident_target_rows": len(target_row_incidence),
        "target_row_incidence_histogram": dict(sorted(Counter(
            target_row_incidence.values()).items())),
        "incident_records": incident_records,
        "incident_stream_sha256": degree5_stream_digest.hexdigest(),
        "incident_row_t_histogram": dict(sorted(Counter(
            7 - len(row) for row in target_row_incidence).items())),
        "normalization_guard": (
            "The target carries t^2. Its homogeneous d7 divisors have encoded y "
            "lengths 7,6,5; all terms of originals*d3 and complete-d5*d2 with the "
            "corresponding implicit multiplier t exponent are included."
        ),
        "scope": (
            "complete literal incident census in the degree-seven Macaulay span "
            "generated by all original d4 generators and all 84,005 complete d5 "
            "cells; a nonempty census is not a pivot/membership result until its "
            "connected fine-grade blocks are reduced"
        ),
        "source_sha256": sha256(COMPLETE_PATH.read_bytes()).hexdigest(),
    }
    encoded = json.dumps(result, sort_keys=True, separators=(",", ":"))
    result["logical_sha256"] = sha256(encoded.encode("ascii")).hexdigest()
    RESULTS.write_text(json.dumps(result, indent=2, sort_keys=True) + "\n")
    print("y10 dead-row complete d7 incidence:", status)
    print("divisors/incident columns/rows:", len(divisors7),
          len(incident_records), len(target_row_incidence))
    print("logical sha256:", result["logical_sha256"])


if __name__ == "__main__":
    main()
