#!/usr/bin/env python3
"""Replay one exact C10 quotient dual against the complete 3780/5108 component."""

from collections import Counter
from hashlib import sha256
import importlib.util
import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
AUDIT_PATH = HERE / "audit_c10_constant_kernel_dead_projection.py"
spec = importlib.util.spec_from_file_location("dead_audit", AUDIT_PATH)
A = importlib.util.module_from_spec(spec)
assert spec.loader is not None
spec.loader.exec_module(A)

ROW = bytes.fromhex("032631696b6f70a7a7e5")
RESULT = HERE / "results_c10_constant_kernel_quotient_dual.json"


def require(condition, detail):
    if not condition:
        raise RuntimeError(detail)


def coefficient_y7(row, multiplier, d2, d3, quadratic):
    complement = A.subtract(row, multiplier)
    coefficient = d3.get(complement, 0)
    for term, value in d2.items():
        degree9 = bytes(sorted(multiplier + term))
        cell, remainder = degree9[0], degree9[1:]
        tail = A.subtract(row, remainder)
        if tail is not None and len(tail) == 2:
            coefficient -= value * quadratic[cell].get(tail, 0)
    return coefficient


def main():
    originals, _ = A.FIRST.original_basis()
    delta = Counter(originals[5108]); delta.subtract(originals[3780])
    delta = Counter({row: value for row, value in delta.items() if value})
    d2 = Counter({row: value for row, value in delta.items() if len(row) == 2})
    d3 = Counter({row: value for row, value in delta.items() if len(row) == 3})
    d4 = Counter({row: value for row, value in delta.items() if len(row) == 4})
    h2 = Counter({row: value for row, value in originals[3780].items() if len(row) == 2})
    quadratic = A.providers()

    dead_coefficients = {}
    for line in A.DEAD.read_text(encoding="ascii").splitlines()[1:]:
        _, row, coefficient = line.split()
        dead_coefficients[bytes.fromhex(row)] = int(coefficient)
    require(dead_coefficients.get(ROW) == 4, "deterministic C10 coordinate changed")

    pm4_terms = set()
    for line in (A.HERE / "quadratic_pm4_blocks.txt").read_text(encoding="ascii").splitlines():
        fields = line.split()
        if not fields or fields[0] != "BLOCK":
            continue
        terms = next(field[6:] for field in fields if field.startswith("TERMS="))
        pm4_terms.update(bytes.fromhex(term) for term in terms.split(","))
    require(len(pm4_terms) == 6618, "PM4 term census changed")
    incident = {ROW[i:i+1] + ROW[j:j+1] for i in range(10) for j in range(i + 1, 10)}
    require(not (incident & pm4_terms), "dual row acquired PM4 incidence")

    values = {}
    divisors6 = A.divisors(ROW, 6)
    values[6] = [A.transfer_coefficient(ROW, multiplier, d2, d3, d4,
                                                h2, quadratic)
                 for multiplier in divisors6]
    divisors7 = A.divisors(ROW, 7)
    values[7] = [coefficient_y7(ROW, multiplier, d2, d3, quadratic)
                 for multiplier in divisors7]
    divisors8 = A.divisors(ROW, 8)
    values[8] = [d2.get(A.subtract(ROW, multiplier), 0)
                 for multiplier in divisors8]
    require(all(not value for degree in values for value in values[degree]),
            "complete constant-provider family crosses dual")

    result = {
        "format": "n8-orbit26-c10-constant-kernel-quotient-dual-v1",
        "status": "EXACT_RELATIVE_NONMEMBER",
        "dual_coordinate_y10": ROW.hex(),
        "deterministic_c10_pairing": 4,
        "pm4_n4_column_pairing": 0,
        "constant_provider_codes": [3780, 5108],
        "constant_provider_words": [list(A.FIRST.D5.decode_word(code))
                                     for code in (3780, 5108)],
        "complete_total_degree8_multiplier_census": {
            "y6_t2": len(divisors6),
            "y7_t1": len(divisors7),
            "y8_t0": len(divisors8),
            "nonzero_pairings": 0,
            "lower_y_degree_0_through_5": "cannot reach y10 because generator difference has maximum y degree 4",
        },
        "theorem": (
            "Evaluation at the displayed y10*t2 coordinate annihilates every "
            "degree-ten PM4/N4 leading column and every degree-ten transferred "
            "tail generated by m*(G5108-G3780) for every homogeneous total-degree-eight "
            "multiplier m. It pairs deterministic C10 by 4, so that C10 class cannot "
            "be killed by the full 3780/5108 constant-provider component."
        ),
        "scope": (
            "Exact normalized orbit26 chart, homogeneous total degree 12, quotient by "
            "literal PM4/N4 degree-ten columns, and the complete lower-kernel component "
            "generated by codes 3780/5108. Other lower-kernel components are not "
            "annihilated here; this is not full ideal nonmembership."
        ),
        "source_sha256": {
            A.DEAD.name: sha256(A.DEAD.read_bytes()).hexdigest(),
            "quadratic_pm4_blocks.txt": sha256((A.HERE / "quadratic_pm4_blocks.txt").read_bytes()).hexdigest(),
            A.PROVIDER.name: sha256(A.PROVIDER.read_bytes()).hexdigest(),
            str(A.FIRST_PATH.relative_to(A.ROOT)): sha256(A.FIRST_PATH.read_bytes()).hexdigest(),
        },
    }
    encoded = json.dumps(result, sort_keys=True, separators=(",", ":"))
    result["logical_sha256"] = sha256(encoded.encode("ascii")).hexdigest()
    RESULT.write_text(json.dumps(result, indent=2, sort_keys=True) + "\n", encoding="ascii")
    print(json.dumps(result, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
