#!/usr/bin/env python3
"""UNAUDITED PROBE -- P1: decide (a) vs (b) on the near-exact STAGE_A source.

Pinned HEAD: 86a9479bef38169bbfd8d9100c6d81ce4c66209a

STAGE_A is the committed near-exact eight-site tensor of
verify_n8_d2_kill_and_monochrome_rigidity.py (6559 of 6561 GHZ rows exact).
At every one of its 28 pairs the cap-error matrix C has rank <= 6, so the
ideal I = (E_w) is generated by at most six cubics and the Rabinowitsch
1-membership test

        witness exists  <=>  1 not in I + (t*s*k_0*k_1*k_2 - 1)

is directly computable.  Any reported witness is re-verified independently
with the square-zero evaluator (E(K) = 0 and s k_0 k_1 k_2 != 0 exactly).

Run: python3 wsplit_stage_a_saturation.py
"""

from __future__ import annotations

import json
import sys
from itertools import combinations

import sympy

import wsplit_core as core
import wsplit_sources as sources
from wsplit_core import NCAP, error_matrix, require
from wsplit_dichotomy import (linear_forms, reduced_generators, split_pattern,
                              to_sympy, verify_witness)


def analyze_pair(physical, p: int, q: int) -> dict:
    src = sources.rechart(physical, p, q)
    matrix = error_matrix(src)
    gens = reduced_generators(matrix)
    forms = linear_forms(src)
    syms = sympy.symbols("K00 K01 K02 K10 K11 K12 K20 K21 K22")
    t = sympy.Symbol("t")
    g = 1
    for name in ("s", "kappa_0", "kappa_1", "kappa_2"):
        g *= sum(sympy.Rational(forms[name][k]) * syms[k] for k in range(NCAP))
    record = {"pair": [p, q], "generators": len(gens),
              "s_identically_zero": all(v == 0 for v in forms["s"])}
    if not gens:
        record["verdict"] = "E == 0 identically (plan case (c))"
        record["witness_exists"] = not record["s_identically_zero"]
        return record
    if len(gens) == 1:
        record["patterns"] = [p_["pattern"] for p_ in
                              split_pattern(gens[0], forms)]
    polys = [to_sympy(c, syms) for c in gens] + [t * g - 1]
    basis = sympy.groebner(polys, *syms, t, order="grevlex")
    trivial = list(basis.exprs) == [sympy.Integer(1)]
    record["witness_exists"] = not trivial
    record["verdict"] = ("(a) active clean cap exists" if not trivial
                         else "(b) no active clean cap: g in sqrt(I)")
    if not trivial:
        # extract one rational point of V(I) off the divisors
        record["witness_search"] = search_witness(src, gens, syms)
    return record


def search_witness(src, gens, syms, bound: int = 4) -> dict:
    """Look for a small exact integer witness by solving the ideal on a
    random rational line/plane; returns a verified witness or a note."""
    import random
    rng = random.Random(20260815)
    solutions = []
    polys = [to_sympy(c, syms) for c in gens]
    for _attempt in range(60):
        # fix seven coordinates at random small integers, solve for two
        free = rng.sample(range(9), 2)
        subs = {syms[k]: sympy.Integer(rng.randint(-bound, bound))
                for k in range(9) if k not in free}
        for k in (core.kidx(0, 0), core.kidx(1, 1), core.kidx(2, 2)):
            if syms[k] in subs and subs[syms[k]] == 0:
                subs[syms[k]] = sympy.Integer(1)
        reduced = [sympy.expand(poly.subs(subs)) for poly in polys]
        reduced = [poly for poly in reduced if poly != 0]
        if not reduced:
            cap = tuple(int(subs.get(syms[k], 0)) for k in range(9))
            checked = verify_witness(src, cap)
            if checked["is_witness"]:
                return checked
            continue
        sol = sympy.solve(reduced, [syms[k] for k in free], dict=True)
        for candidate in sol:
            values = dict(subs)
            values.update(candidate)
            try:
                cap = tuple(sympy.Rational(values.get(syms[k], 0))
                            for k in range(9))
            except TypeError:
                continue
            if any(not value.is_rational for value in cap):
                continue
            from fractions import Fraction
            capf = tuple(Fraction(int(v.p), int(v.q)) for v in cap)
            checked = verify_witness(src, capf)
            if checked["is_witness"]:
                return checked
            solutions.append(str(capf))
    return {"is_witness": False,
            "note": "no rational witness found by the bounded line search",
            "tried": len(solutions)}


def main() -> int:
    physical = sources.load_stage_a()
    records = []
    for p, q in combinations(range(8), 2):
        rec = analyze_pair(physical, p, q)
        records.append(rec)
        print(f"  pair ({p},{q}): gens={rec['generators']:2d} "
              f"s==0:{rec['s_identically_zero']!s:5s} {rec['verdict']}"
              + (f"  witness verified: "
                 f"{rec.get('witness_search', {}).get('is_witness')}"
                 if rec.get("witness_exists") else ""))
    live = [r for r in records if not r["s_identically_zero"]]
    print(f"live pairs: {len(live)}/28; "
          f"witness at {sum(1 for r in live if r['witness_exists'])} of them")
    with open("stage_a_saturation.json", "w") as handle:
        json.dump(records, handle, indent=1, sort_keys=True, default=str)
    print("wrote stage_a_saturation.json")
    return 0


if __name__ == "__main__":
    sys.exit(main())
