#!/usr/bin/env python3
"""UNAUDITED PROBE W32 (general X_4-emptiness at N=8) -- core engine.

Pinned HEAD: see PINNED_HEAD.txt.  Exact arithmetic throughout (Fraction /
own Q(omega) / F_p); mod-p only as a screen with exact re-checks.

INDEPENDENT re-implementation.  Deliberately different code paths from
w25_core / w27_core / w28_core:
  * hafnians by an explicit perfect-matching enumeration with a cached
    matching list per site-tuple (W25 bitmask DP, W28 lowest-site recursion);
  * sources stored as a flat dict edge -> 3x3 list with A_vu = A_uv^T;
  * word sets generated by profile, not by Hamming-ball expansion, and the
    two constructions are cross-checked in run_01.

SETTING.  A "source" on K_N assigns to each edge {u,v} (u<v) a 3x3 matrix
A_uv; A_vu = A_uv^T.  For a word w in {0,1,2}^N,

    H_w(A) = sum_{M in PM(K_N)} prod_{{u,v} in M, u<v} A_uv[w_u][w_v].

X_k = { A : H_w = 1 for the three constant words and H_w = 0 for every
non-constant word of off-count <= k }, off-count(w) = N - max_c |w^{-1}(c)|.

EXACT = X_N.  W27-P1: at N=8 the only profile of off-count > 4 is (3,3,2),
so EXACT subset X_4 and "X_4 = empty at N=8" proves Krenn-Gu at n=8.

GENERATING FORM (used throughout this lane).  With xi_i in C^3,

    Phi_A(xi) := haf( M(xi) ),   M(xi)_ij = xi_i^T A_ij xi_j
               = sum_w H_w(A) prod_i xi_i[w_i],

so Phi is multilinear (degree 1 in each xi_i) and X_k says Phi agrees with
the GHZ polynomial sum_c prod_i xi_i[c] on every monomial of off-count <= k.
"""
from __future__ import annotations

import itertools
import os
import subprocess
import tempfile
from fractions import Fraction
from functools import lru_cache

NCOL = 3


def require(cond, detail):
    if not cond:
        raise AssertionError(detail)


# ------------------------------------------------------------------- Q(omega)

class Cyc:
    """a + b*w with w^2 + w + 1 = 0.  Own arithmetic (cross-checked in run_01
    against an independent Fraction-pair implementation of the same field)."""

    __slots__ = ("a", "b")

    def __init__(self, a=0, b=0):
        self.a = Fraction(a)
        self.b = Fraction(b)

    @staticmethod
    def of(x):
        return x if isinstance(x, Cyc) else Cyc(x, 0)

    def __repr__(self):
        return f"Cyc({self.a},{self.b})"

    def __eq__(self, o):
        if isinstance(o, Cyc):
            return self.a == o.a and self.b == o.b
        return self.b == 0 and self.a == Fraction(o)

    def __hash__(self):
        return hash((self.a, self.b))

    def __bool__(self):
        return bool(self.a) or bool(self.b)

    def __neg__(self):
        return Cyc(-self.a, -self.b)

    def __add__(self, o):
        o = Cyc.of(o)
        return Cyc(self.a + o.a, self.b + o.b)

    __radd__ = __add__

    def __sub__(self, o):
        o = Cyc.of(o)
        return Cyc(self.a - o.a, self.b - o.b)

    def __rsub__(self, o):
        return Cyc.of(o) - self

    def __mul__(self, o):
        o = Cyc.of(o)
        a, b, c, d = self.a, self.b, o.a, o.b
        return Cyc(a * c - b * d, a * d + b * c - b * d)

    __rmul__ = __mul__

    def inv(self):
        n = self.a * self.a - self.a * self.b + self.b * self.b
        require(n != 0, "Cyc: division by zero")
        return Cyc((self.a - self.b) / n, -self.b / n)

    def __truediv__(self, o):
        return self * Cyc.of(o).inv()

    def __rtruediv__(self, o):
        return Cyc.of(o) * self.inv()


OMEGA = Cyc(0, 1)


class Fp:
    """F_p element (p prime), for the two-primes discipline (ledger 19)."""

    __slots__ = ("v", "p")

    def __init__(self, v, p):
        self.v = v % p
        self.p = p

    def __repr__(self):
        return f"Fp({self.v},{self.p})"

    def _o(self, o):
        return o if isinstance(o, Fp) else Fp(int(o), self.p)

    def __eq__(self, o):
        if isinstance(o, Fp):
            return self.v == o.v and self.p == o.p
        return self.v == int(o) % self.p

    def __hash__(self):
        return hash((self.v, self.p))

    def __bool__(self):
        return self.v != 0

    def __neg__(self):
        return Fp(-self.v, self.p)

    def __add__(self, o):
        return Fp(self.v + self._o(o).v, self.p)

    __radd__ = __add__

    def __sub__(self, o):
        return Fp(self.v - self._o(o).v, self.p)

    def __rsub__(self, o):
        return self._o(o) - self

    def __mul__(self, o):
        return Fp(self.v * self._o(o).v, self.p)

    __rmul__ = __mul__

    def inv(self):
        require(self.v != 0, "Fp: division by zero")
        return Fp(pow(self.v, self.p - 2, self.p), self.p)

    def __truediv__(self, o):
        return self * self._o(o).inv()

    def __rtruediv__(self, o):
        return self._o(o) * self.inv()


def zeroe(sample):
    if isinstance(sample, Cyc):
        return Cyc(0, 0)
    if isinstance(sample, Fp):
        return Fp(0, sample.p)
    return Fraction(0)


def onee(sample):
    if isinstance(sample, Cyc):
        return Cyc(1, 0)
    if isinstance(sample, Fp):
        return Fp(1, sample.p)
    return Fraction(1)


# --------------------------------------------------------------- combinatorics

def ekey(a, b):
    return (a, b) if a < b else (b, a)


@lru_cache(maxsize=None)
def perfect_matchings(sites):
    """All perfect matchings of the complete graph on `sites` (sorted tuple),
    each as a tuple of ekey pairs.  Explicit enumeration + cache."""
    sites = tuple(sorted(sites))
    if len(sites) % 2:
        return ()
    if not sites:
        return ((),)
    h, rest = sites[0], sites[1:]
    out = []
    for i, x in enumerate(rest):
        sub = perfect_matchings(rest[:i] + rest[i + 1:])
        e = ekey(h, x)
        for M in sub:
            out.append((e,) + M)
    return tuple(out)


def profile(word, ncol=NCOL):
    return tuple(sorted((sum(1 for x in word if x == c) for c in range(ncol)),
                        reverse=True))


def offcount(word, ncol=NCOL):
    return len(word) - max(sum(1 for x in word if x == c) for c in range(ncol))


def all_words(n, ncol=NCOL):
    return tuple(itertools.product(range(ncol), repeat=n))


def words_offcount_le(n, k, ncol=NCOL):
    return tuple(w for w in all_words(n, ncol) if offcount(w, ncol) <= k)


def near_constant_ball(n, k, ncol=NCOL):
    """Independent construction: Hamming balls of radius k around the constant
    words.  run_01 asserts this equals words_offcount_le."""
    out = set()
    for g in range(ncol):
        base = (g,) * n
        out.add(base)
        for size in range(1, k + 1):
            for S in itertools.combinations(range(n), size):
                for vals in itertools.product(
                        [c for c in range(ncol)], repeat=size):
                    w = list(base)
                    for i, s in enumerate(S):
                        w[s] = vals[i]
                    out.add(tuple(w))
    return tuple(sorted(out))


# ------------------------------------------------------------------- sources

def zero_source(n, sample=None, ncol=NCOL):
    z = Fraction(0) if sample is None else zeroe(sample)
    return {(a, b): [[z] * ncol for _ in range(ncol)]
            for a, b in itertools.combinations(range(n), 2)}


def copy_source(src):
    return {e: [r[:] for r in m] for e, m in src.items()}


def cell(src, u, v, a, b):
    """A_uv[a][b] with the A_vu = A_uv^T convention."""
    if u < v:
        return src[(u, v)][a][b]
    return src[(v, u)][b][a]


def setcell(src, u, v, a, b, val):
    if u < v:
        src[(u, v)][a][b] = val
    else:
        src[(v, u)][b][a] = val


def haf_word(src, word, sites=None, ncol=NCOL):
    """H_w over `sites` (default: all sites of the word's index set).

    Explicit PM enumeration -- independent of W25/W27/W28 recursions."""
    n = len(word) if sites is None else None
    sites = tuple(range(n)) if sites is None else tuple(sorted(sites))
    sample = src[(0, 1)][0][0]
    zz, oo = zeroe(sample), onee(sample)
    if len(sites) % 2:
        return zz
    tot = zz
    for M in perfect_matchings(sites):
        prod = oo
        for (u, v) in M:
            c = cell(src, u, v, word[u], word[v])
            if c == 0:
                prod = zz
                break
            prod = prod * c
        if prod != 0:
            tot = tot + prod
    return tot


def in_Xk(src, n, k, ncol=NCOL, words=None):
    """(bool, first violating word)."""
    words = words_offcount_le(n, k, ncol) if words is None else words
    for w in words:
        tgt = 1 if len(set(w)) == 1 else 0
        if haf_word(src, w) != tgt:
            return False, w
    return True, None


def violations(src, n, k, ncol=NCOL, words=None):
    words = words_offcount_le(n, k, ncol) if words is None else words
    bad = []
    for w in words:
        tgt = 1 if len(set(w)) == 1 else 0
        if haf_word(src, w) != tgt:
            bad.append(w)
    return bad


def restrict_pair(src, pair, n):
    """The 2-colour restriction A^{pair}: a source with ncol = 2 whose cells
    are A_uv[pair[a]][pair[b]]."""
    out = {}
    for (u, v) in src:
        out[(u, v)] = [[src[(u, v)][pair[a]][pair[b]] for b in range(2)]
                       for a in range(2)]
    return out


# --------------------------------------------------------- diagonal sources

def diag_source(n, edgesets, weights=None):
    """edgesets[c] = iterable of edges carrying colour c; weights[(c,e)]."""
    src = zero_source(n)
    for c, L in enumerate(edgesets):
        for e in L:
            e = ekey(*e)
            src[e][c][c] = (Fraction(1) if weights is None
                            else weights[(c, e)])
    return src


def delta3_pms(n):
    m0 = [ekey(i, i + 1) for i in range(0, n, 2)]
    m1 = [ekey(i, (i + 1) % n) for i in range(1, n, 2)]
    h = n // 2
    m2 = [ekey(i, i + h) for i in range(h)]
    return [m0, m1, m2]


# ------------------------------------------------------------ linear algebra

def rref(rows, rhs, ncols):
    """Exact reduced row echelon.  Returns (pivots, matrix, consistent)."""
    sample = None
    for r in rows:
        for x in r:
            sample = x
            break
        if sample is not None:
            break
    if sample is None:
        sample = Fraction(0)
    zz = zeroe(sample)
    m = [list(r) + [b] for r, b in zip(rows, rhs)]
    piv, rr = [], 0
    for c in range(ncols):
        p = None
        for i in range(rr, len(m)):
            if m[i][c] != 0:
                p = i
                break
        if p is None:
            continue
        m[rr], m[p] = m[p], m[rr]
        inv = (m[rr][c].inv() if hasattr(m[rr][c], "inv")
               else Fraction(1) / m[rr][c])
        m[rr] = [x * inv for x in m[rr]]
        for i in range(len(m)):
            if i != rr and m[i][c] != 0:
                f = m[i][c]
                m[i] = [a - f * b for a, b in zip(m[i], m[rr])]
        piv.append(c)
        rr += 1
    ok = True
    for i in range(len(m)):
        if m[i][ncols] != 0 and all(x == 0 for x in m[i][:ncols]):
            ok = False
            break
    return piv, m, ok


def solve_system(rows, rhs, ncols):
    piv, m, ok = rref(rows, rhs, ncols)
    if not ok:
        return None, None
    sample = m[0][ncols] if m else Fraction(0)
    zz, oo = zeroe(sample), onee(sample)
    part = [zz] * ncols
    for i, c in enumerate(piv):
        part[c] = m[i][ncols]
    kern = []
    for f in [c for c in range(ncols) if c not in piv]:
        v = [zz] * ncols
        v[f] = oo
        for i, c in enumerate(piv):
            v[c] = -m[i][f]
        kern.append(v)
    return part, kern


# ------------------------------------------- W27-R1 site reduction (general)

def background_rows(bg, n, z=None):
    """The rows R_u for the K_{n-1} background `bg` (a source on V' = V - z,
    relabelled 0..n-2 is NOT done: bg is indexed by the original sites).

    R_u[(y,d)] = [u_y = d] * haf_{V' - y}(bg)_u  for u in {0,1,2}^{V'}.
    The rows do NOT depend on the solve colour c (W32 observation: the
    cofactors never see w_z), so the three colour systems share them.
    Returns (cols, {u: row}).
    """
    z = n - 1 if z is None else z
    VP = tuple(x for x in range(n) if x != z)
    cols = [(y, d) for y in VP for d in range(NCOL)]
    idx = {t: i for i, t in enumerate(cols)}
    sample = bg[(VP[0], VP[1])][0][0]
    zz = zeroe(sample)
    rows = {}
    for u in itertools.product(range(NCOL), repeat=len(VP)):
        wd = {y: u[i] for i, y in enumerate(VP)}
        row = [zz] * len(cols)
        for i, y in enumerate(VP):
            U = tuple(x for x in VP if x != y)
            row[idx[(y, u[i])]] = haf_word(bg, wd, sites=U)
        rows[u] = row
    return cols, rows


def colour_system(n, rows, c, k, z=None):
    """(mixed_rows, const_row) for colour c at level k, from background_rows."""
    z = n - 1 if z is None else z
    mixed, const = [], None
    for u, row in rows.items():
        w = list(u)
        w.insert(z, c) if z < len(u) else w.append(c)
        w = tuple(w)
        if offcount(w) > k:
            continue
        if len(set(w)) == 1:
            const = row
        else:
            mixed.append(row)
    return mixed, const


# ------------------------------------------------------------------ Singular

def run_singular(script, timeout=3600):
    """Ledger 6/11/14: RC 0 is not enough -- parse stdout for '?' lines."""
    with tempfile.NamedTemporaryFile("w", suffix=".sing", delete=False) as fh:
        fh.write(script + "\nquit;\n")
        path = fh.name
    try:
        proc = subprocess.run(["Singular", "-q", "--no-warn", path],
                              capture_output=True, text=True, timeout=timeout)
    finally:
        os.unlink(path)
    out = proc.stdout
    bad = [ln for ln in out.splitlines() if ln.strip().startswith("?")]
    if proc.returncode != 0 or bad:
        raise RuntimeError(f"Singular rc={proc.returncode} bad={bad[:6]} "
                           f"stderr={proc.stderr[:1200]}")
    return out


def no_shadow_guard(script, ringvars):
    """Ledger 13: never name a generator after a ring variable."""
    kws = ("poly ", "ideal ", "int ", "number ", "matrix ", "list ", "map ",
           "vector ", "def ", "ring ", "intvec ", "string ")
    for ln in script.splitlines():
        t = ln.strip()
        for kw in kws:
            if t.startswith(kw):
                name = t[len(kw):].split("=")[0].split("(")[0].split(",")[0]
                name = name.strip().rstrip(";")
                if name in ringvars:
                    raise AssertionError(f"ledger-13 shadowing hazard: {ln}")
                if not name.startswith("zz") and name not in ("R", "r"):
                    raise AssertionError(f"ledger-13 zz-prefix rule: {ln}")
    return True


# ----------------------------------------------------------------- manifests

class Manifest:
    """Ledger 21: a control file must fail loudly if a control never ran."""

    def __init__(self, declared):
        self.declared = list(declared)
        self.ran = []

    def mark(self, name):
        require(name in self.declared, f"undeclared control {name}")
        self.ran.append(name)

    def assert_complete(self):
        missing = [c for c in self.declared if c not in self.ran]
        require(not missing, f"CONTROLS NEVER RAN: {missing}")
        return {"declared": self.declared, "ran": self.ran, "complete": True}


__all__ = [n for n in dir() if not n.startswith("_")]
