#!/usr/bin/env python3
"""W16 -- the PHI-FORCING kill engine for family (R), m = 25..28.

MECHANISM (W15-A, k=1 form).  Every matching of FULL blocks is supported on
every word, so H_w = Phi_w + (extras).  A word is EFFECTIVELY CLEAN when it
has no extras (exact criterion: enumerate the fibre, ask whether it equals
F(Gamma)); then the mixed equation reads Phi_w = 0.  If a mixed word w*
has EXACTLY ONE extra, H_{w*} = Phi_{w*} + (a monomial in occupied cells);
so forcing Phi_{w*} = 0 forces that monomial to vanish -- impossible on a
source with template T.  Likewise a mixed word with TWO extras yields a
binomial relation between two occupied-cell monomials.

FORCING TEST (exact, over Q).  Let I = ideal generated by Phi_w over a set
of effectively-clean words, and P = product of all occupied Gamma cells.
Phi_{w*} vanishes on the closure of  V(I) \\ V(P)  iff

        Phi_{w*}  in  sat(I, P)                                   (*)

(equivalently P^d Phi_{w*} in I for some d).  (*) is decided by Singular
over Q.  A4 trap guards are in w16_sing (errors on stdout with rc 0;
`list L = sat(I,J); ideal S = L[1];`).
"""
from __future__ import annotations
import os, sys, json, itertools
from fractions import Fraction
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from w16_core import (EDGES, EIDX, FULL, W8_IMMUNE, VarMap, phi_poly,
                      full_pm_indices, extras_at, support, PM_E, cell,
                      MIXED, pmul)
from w16_sing import run_singular, poly_str

HERE = os.path.dirname(os.path.abspath(__file__))


def classify(T):
    fullm = full_pm_indices(T)
    out = {}
    for w in itertools.product(range(3), repeat=8):
        out[w] = len(extras_at(T, w, fullm))
    return out, fullm


def box_words(alpha):
    return list(itertools.product(*alpha))


def forcing_test(T, target, words, timeout=1800, saturate=True,
                 max_power=None):
    """Is Phi_target forced to vanish by {Phi_w = 0 : w in words} away from
    the vanishing of the occupied cells?  Returns dict."""
    vm = VarMap(T)
    fullm = full_pm_indices(T)
    eqs = [phi_poly(T, vm, w, fullm) for w in words]
    tgt = phi_poly(T, vm, target, fullm)
    used = set()
    for p in eqs + [tgt]:
        for mon in p:
            used.update(mon)
    used = sorted(used)
    names = {v: "z%d" % i for i, v in enumerate(used)}
    ll = ['LIB "elim.lib";',
          "ring r = 0,(%s),dp;" % ",".join(names[v] for v in used)]
    for i, p in enumerate(eqs, 1):
        ll.append("poly g%d = %s;" % (i, poly_str(p, names)))
    ll.append("poly tt = %s;" % poly_str(tgt, names))
    ll.append("ideal Iid = %s;" % ",".join("g%d" % i
                                           for i in range(1, len(eqs) + 1)))
    ll.append("poly PP = %s;" % "*".join(names[v] for v in used))
    if saturate:
        ll.append("ideal Jid = PP;")
        ll.append("list LL = sat(Iid,Jid);")
        ll.append("ideal SS = LL[1];")
        ll.append("ideal GS = groebner(SS);")
        ll.append('"FORCED:"; (reduce(tt,GS)==0);')
    else:
        ll.append("ideal GI = groebner(Iid);")
        ll.append("poly cur = tt;")
        for d in range(1, (max_power or 6) + 1):
            ll.append("cur = cur*PP;")
            ll.append('"POW%d:"; (reduce(cur,GI)==0);' % d)
    ll.append("quit;")
    out, st = run_singular("\n".join(ll) + "\n", timeout=timeout)
    if st == "TIMEOUT":
        return dict(verdict=None, reason="timeout", n_vars=len(used),
                    n_eqs=len(eqs))
    if saturate:
        v = out.split("FORCED:")[1].strip().split()[0] == "1"
        return dict(verdict=v, n_vars=len(used), n_eqs=len(eqs))
    v = False
    for d in range(1, (max_power or 6) + 1):
        if out.split("POW%d:" % d)[1].strip().split()[0] == "1":
            v = True
            break
    return dict(verdict=v, n_vars=len(used), n_eqs=len(eqs))


def enumerate_boxes(T, kmap, target, budget_words=None):
    """Alphabet boxes containing `target`, at most 2 colours per site, whose
    non-target words are ALL effectively clean (so every one is an equation)."""
    boxes = []
    sites = range(8)
    for extra in itertools.product(*[[None] + [c for c in range(3)
                                               if c != target[s]]
                                     for s in sites]):
        alpha = [tuple(sorted({target[s]} | ({extra[s]} if extra[s] is not None
                                             else set()))) for s in sites]
        ws = box_words(alpha)
        if len(ws) < 4:
            continue
        ok = all(kmap[w] == 0 for w in ws if w != target)
        if not ok:
            continue
        if budget_words and len(ws) > budget_words:
            continue
        boxes.append((alpha, [w for w in ws if w != target]))
    boxes.sort(key=lambda b: -len(b[1]))
    return boxes


def main():
    ms = [int(a) for a in sys.argv[1:]] or [25]
    res = {}
    for m in ms:
        T = W8_IMMUNE[m]
        kmap, fullm = classify(T)
        k1 = [w for w in MIXED if kmap[w] == 1]
        print("m=%d: |F(Gamma)|=%d  k=1 words: %d" % (m, len(fullm), len(k1)))
        entry = []
        seen = 0
        for tgt in k1:
            boxes = enumerate_boxes(T, kmap, tgt, budget_words=64)
            if not boxes:
                continue
            alpha, ws = boxes[0]
            seen += 1
            if seen > 6:
                break
            r = forcing_test(T, tgt, ws, timeout=600)
            r["target"] = "".join(map(str, tgt))
            r["alphabet"] = [list(a) for a in alpha]
            r["n_box_words"] = len(ws)
            print("   target %s box=%s eqs=%d vars=%d -> %s"
                  % (r["target"], r["alphabet"], r["n_eqs"], r["n_vars"],
                     r["verdict"]))
            entry.append(r)
        res[m] = entry
    json.dump(res, open(os.path.join(HERE, "results_kill_%s.json"
                                     % "_".join(map(str, ms))), "w"), indent=1)


if __name__ == "__main__":
    main()
