#!/usr/bin/env python3
"""W16 T3 -- the k = 2 (binomial re-entry) route, m = 28 and friends.

At m = 28 every word has an EVEN number of extras, so there is no k = 1
target; the designated route is k = 2.  If a site t FACTORS (mechanism
W16-B: all Gamma blocks at t are rank one with a common t-vector), then for
any pair (w, w') of words agreeing off t with w EFFECTIVELY CLEAN we get
Phi_{w'} = (gamma_{w'_t}/gamma_{w_t}) Phi_w = 0, so for a k = 2 word w'

        M_a + M_b = 0                                            (binomial)

where M_a, M_b are the two extra matchings' monomials in the OCCUPIED cells
(each a product of 4 cells, all nonzero).  Write x^{d} = -1 with
d = exp(M_a) - exp(M_b) in Z^Sigma.

O1 TEST (the odd-relation kill, exact integer linear algebra -- no Groebner).
Any integer dependency  sum_i c_i d_i = 0  forces  (-1)^{sum_i c_i} = 1.
So the system is UNSATISFIABLE over any field of characteristic != 2 as soon
as the kernel lattice K = { c : sum c_i d_i = 0 } contains a vector with ODD
coordinate sum.  Equivalently: the all-ones functional does NOT vanish
identically mod 2 on K.  Decided here by an exact Hermite-style elimination
over Z (fraction-free), plus a mutation control.
"""
from __future__ import annotations
import os, sys, json, itertools
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from w16_core import (W8_IMMUNE, EDGES, EIDX, VarMap, PM_E, cell, support,
                      full_pm_indices, extras_at, MIXED)

HERE = os.path.dirname(os.path.abspath(__file__))


def extra_monomials(T, vm, w, fullm):
    """exponent vectors (in the occupied-cell variables) of the extras"""
    out = []
    for mi in extras_at(T, w, fullm):
        v = [0] * len(vm)
        for e in PM_E[mi]:
            v[vm.v(e, cell(e, w))] += 1
        out.append(v)
    return out


def binomials_at_site(T, t):
    """(clean w, k=2 w') pairs differing only at t -> exponent differences"""
    vm = VarMap(T)
    fullm = full_pm_indices(T)
    km = {w: len(extras_at(T, w, fullm))
          for w in itertools.product(range(3), repeat=8)}
    clean = set(w for w in MIXED if km[w] == 0)
    diffs, tags = [], []
    for w in sorted(clean):
        for c in range(3):
            if c == w[t]:
                continue
            wp = tuple(list(w[:t]) + [c] + list(w[t + 1:]))
            if km.get(wp) != 2 or len(set(wp)) == 1:
                continue
            ms = extra_monomials(T, vm, wp, fullm)
            d = [a - b for a, b in zip(ms[0], ms[1])]
            if any(d):
                diffs.append(d)
                tags.append(("".join(map(str, w)), "".join(map(str, wp))))
    return vm, diffs, tags


def _insert(basis, row, ncol):
    """incremental integer row-echelon insertion (Hermite-style).

    `basis` is a dict pivot-column -> row; the Z-row-space is preserved
    exactly (only unimodular row operations are used)."""
    row = row[:]
    for c in range(ncol):
        if row[c] == 0:
            continue
        if c not in basis:
            basis[c] = row
            return
        b = basis[c]
        # extended gcd combine: replace (b,row) by (g-row, 0-in-column row)
        a, bb = b[c], row[c]
        old_r, r = a, bb
        old_s, sarg = 1, 0
        old_t, t = 0, 1
        while r:
            q = old_r // r
            old_r, r = r, old_r - q * r
            old_s, sarg = sarg, old_s - q * sarg
            old_t, t = t, old_t - q * t
        g = old_r
        u, v = old_s, old_t                     # u*a + v*bb = g
        nb = [u * x + v * y for x, y in zip(b, row)]
        nr = [(-bb // g) * x + (a // g) * y for x, y in zip(b, row)]
        basis[c] = nb
        row = nr
    return


def odd_relation_exists(diffs):
    """EXACT test.  A point with all coordinates nonzero satisfying
    x^{d_i} = -1 for all i exists over C iff the character d_i |-> -1 is
    well defined on the lattice generated by the d_i, i.e. iff EVERY
    integer relation sum_i c_i d_i = 0 has sum_i c_i EVEN.

    Set M = [ d_i | 1 ].  Then c^T M = (0,...,0,s) with s = sum c_i, so the
    achievable s form a subgroup g*Z, computed by integer row reduction of
    M echelonised on the FIRST n columns: the rows that vanish there carry
    the last coordinates generating g*Z.  An ODD RELATION (hence the kill)
    exists iff g is odd."""
    if not diffs:
        return dict(n=0, g=0, odd_relation=False)
    n = len(diffs[0])
    basis = {}
    for d in diffs:
        _insert(basis, list(d) + [1], n + 1)
    g = 0
    for c, row in basis.items():
        if c >= n:                                # pivot in the last column
            g = abs(row[n])
    from math import gcd
    for c, row in basis.items():
        if c < n:
            continue
        g = gcd(g, abs(row[n]))
    return dict(n=len(diffs), g=g, odd_relation=(g % 2 == 1 and g != 0))


def main():
    out = {}
    for m in (28, 27, 26, 25):
        T = W8_IMMUNE[m]
        entry = {}
        for t in range(8):
            vm, diffs, tags = binomials_at_site(T, t)
            res = odd_relation_exists(diffs)
            res["examples"] = tags[:2]
            entry[t] = res
            print("m=%d site %d: %4d binomials, parity subgroup g = %s, "
                  "ODD RELATION = %s" % (m, t, res["n"], res["g"],
                                         res["odd_relation"]))
        out[m] = entry
    # MUTATION CONTROL: a fabricated system that MUST show an odd relation
    fake_odd = [[1, -1, 0], [0, 1, -1], [1, 0, -1]]   # d1+d2-d3 = 0, sum = 1
    fake_even = [[1, -1, 0], [0, 1, -1], [2, -2, 0]]   # 2*d1 - d3 = 0, sum = 1
    print("mutation control ODD (must be True):",
          odd_relation_exists(fake_odd)["odd_relation"])
    print("mutation control EVEN-only (must be False):",
          odd_relation_exists([[1, -1, 0], [2, -2, 0]])["odd_relation"])
    out["mutation_control_odd"] = odd_relation_exists(fake_odd)["odd_relation"]
    out["mutation_control_even"] = odd_relation_exists(
        [[1, -1, 0], [2, -2, 0]])["odd_relation"]
    del fake_even
    json.dump(out, open(os.path.join(HERE, "results_k2lattice.json"), "w"),
              indent=1)


if __name__ == "__main__":
    main()
