//! Independent streaming census, degree/balance guard, and 77-cycle pairing.
use std::collections::HashMap;
use std::convert::TryInto;
use std::fs::{read,File};
use std::io::{Read,Write,BufReader};
use std::time::Instant;

const DIR:&str="computations/unaudited-codex-orbit0-filtered-k16-run-2026-08-23/";
const SCALE:i128=281_801_520;
#[derive(Clone,Copy,Eq,Hash,PartialEq)]struct Key([u8;13]);
fn u32le(x:&[u8])->u32{u32::from_le_bytes(x.try_into().unwrap())}
fn u64le(x:&[u8])->u64{u64::from_le_bytes(x.try_into().unwrap())}
fn gcd(mut a:i128,mut b:i128)->i128{a=a.abs();b=b.abs();while b!=0{let r=a%b;a=b;b=r}a}
fn fraction(x:i128)->String{let g=gcd(x,SCALE);format!("{}/{}",x/g,SCALE/g)}
fn cycle_key(row:&[u8;24],cells:&[[u8;4];252])->Key{let mut adj=[[0u8;2];24];let mut deg=[0usize;24];for &c in row{let [u,v,a,b]=cells[c as usize];let x=(3*u+a)as usize;let y=(3*v+b)as usize;assert!(deg[x]<2&&deg[y]<2);adj[x][deg[x]]=y as u8;deg[x]+=1;adj[y][deg[y]]=x as u8;deg[y]+=1}assert!(deg.iter().all(|&d|d==2));let mut seen=[false;24];let mut parts=[0u8;12];let mut np=0usize;for start in 0..24{if seen[start]{continue}let mut stack=[0u8;24];let(mut top,mut size)=(1usize,0u8);stack[0]=start as u8;seen[start]=true;while top>0{top-=1;let x=stack[top]as usize;size+=1;for &yy in &adj[x]{let y=yy as usize;if !seen[y]{seen[y]=true;stack[top]=yy;top+=1}}}parts[np]=size;np+=1}parts[..np].sort_unstable();let mut key=[0u8;13];key[0]=np as u8;key[1..1+np].copy_from_slice(&parts[..np]);Key(key)}
fn audit(path:&str,magic:&[u8;8],cells:&[[u8;4];252],anchors:&[bool;252],dual:&HashMap<Key,i64>)->(u64,i128,i128,i128,usize){let f=File::open(path).unwrap();let mut r=BufReader::with_capacity(1<<20,f);let mut m=[0u8;8];r.read_exact(&mut m).unwrap();assert_eq!(&m,magic);let mut b8=[0u8;8];r.read_exact(&mut b8).unwrap();let n=u64::from_le_bytes(b8);let(mut signed,mut l1,mut pairing)=(0i128,0i128,0i128);let mut hist=HashMap::<Key,i128>::new();for _ in 0..n{let mut row=[0u8;24];let mut vb=[0u8;16];r.read_exact(&mut row).unwrap();r.read_exact(&mut vb).unwrap();let value=i128::from_le_bytes(vb);assert_eq!(row.iter().filter(|&&c|!anchors[c as usize]).count(),17);let key=cycle_key(&row,cells);signed+=value;l1+=value.abs();pairing+=value*(*dual.get(&key).unwrap_or(&0)as i128);*hist.entry(key).or_default()+=value}assert_eq!(r.read(&mut[0u8;1]).unwrap(),0);hist.retain(|_,v|*v!=0);(n,signed,l1,pairing,hist.len())}
fn main(){let begun=Instant::now();let aux=read(format!("{}filtered_k17_cycle_aux.bin",DIR)).unwrap();let mut p=0usize;assert_eq!(&aux[p..p+8],b"K17CYC1\0");p+=8;let mut cells=[[0u8;4];252];for cell in &mut cells{cell.copy_from_slice(&aux[p..p+4]);p+=4}let nd=u32le(&aux[p..p+4])as usize;p+=4;let mut dual=HashMap::new();for _ in 0..nd{let mut key=[0u8;13];key.copy_from_slice(&aux[p..p+13]);p+=13;let coeff=i64::from_le_bytes(aux[p..p+8].try_into().unwrap());p+=8;dual.insert(Key(key),coeff);}assert_eq!((p,dual.len()),(aux.len(),77));let structure=read(format!("{}filtered_k16_structure.bin",DIR)).unwrap();let mut anchors=[false;252];for &c in &structure[27..39]{anchors[c as usize]=true}
    let items=[("direct","checkpoint_k17_direct.bin",b"K17DIR2\0"),("from_K14_K3","checkpoint_k17_from_k14.bin",b"K17K142\0"),("from_K15_K2","checkpoint_k17_from_k15.bin",b"K17K152\0"),("combined","checkpoint_reduced_k17.bin",b"K17RED2\0")];let mut lines=Vec::new();for(label,file,magic)in items{let s=audit(&format!("{}{}",DIR,file),magic,&cells,&anchors,&dual);lines.push(format!("    \"{}\": {{\"support\":{},\"signed_scaled\":{},\"signed\":\"{}\",\"l1_scaled\":{},\"l1\":\"{}\",\"cycle_pairing_scaled\":{},\"cycle_pairing\":\"{}\",\"nonzero_cycle_partitions\":{}}}",label,s.0,s.1,fraction(s.1),s.2,fraction(s.2),s.3,fraction(s.3),s.4))}let text=format!("{{\n  \"status\":\"PASS exact streaming K17 checkpoint replay\",\n  \"global_scale\":{},\n  \"dual_support\":77,\n  \"components\":{{\n{}\n  }},\n  \"elapsed_seconds\":{:.3}\n}}\n",SCALE,lines.join(",\n"),begun.elapsed().as_secs_f64());File::create(format!("{}results_filtered_k17_checkpoint_audit.json",DIR)).unwrap().write_all(text.as_bytes()).unwrap();print!("{}",text)}
