#!/usr/bin/env python3
"""AUDIT A2 / claim B.6 -- independent re-verification of W2's 28 full-support
no-singleton templates and of their O1 (odd holonomy) kills.

INDEPENDENT O1 ROUTE.  For a template in R_cell (one cell per edge) let
x_e in C^* be the value of the cell on edge e.  A mixed word whose fibre is
exactly two matchings M1, M2 forces

        x^{a(M1)} + x^{a(M2)} = 0     i.e.   x^{d} = -1,  d = a(M1) - a(M2),

where a(M) in Z^{28} is the indicator vector of M's edges.  Collect the rows
d_1..d_k.  Because C^* is divisible, a solution exists iff the assignment
d_i -> -1 is a well-defined homomorphism on the lattice <d_1..d_k>, i.e. iff

        NOT exists lambda in Z^k with sum_i lambda_i d_i = 0 and sum_i lambda_i odd.

Equivalently, writing L for the sublattice of Z^{29} generated by the rows
(d_i, 1) together with (0,...,0,2):

        the template is O1-DEAD  <=>  (0,...,0,1) in L.

W2 decides this by Hermite normal form WITH transform and a search through the
kernel rows for an odd sign; here it is decided by pure LATTICE MEMBERSHIP
(HNF of the generator matrix versus HNF of the matrix with the target
appended), a different route with no kernel bookkeeping at all.
"""

from __future__ import annotations

import json
from itertools import combinations

from sympy import Matrix
from sympy.matrices.normalforms import hermite_normal_form

from a2_core import audit_template, geom, normalise_template

W2 = ("/Users/rishi/workplace/krenn-conjecture/computations/"
      "unaudited-witness-splitting-w2-2026-08-15")
N = 8
EDGES = tuple(combinations(range(N), 2))
EIDX = {e: i for i, e in enumerate(EDGES)}


def perfect_matchings(vs):
    if not vs:
        return [()]
    first, out = vs[0], []
    for i in range(1, len(vs)):
        rest = vs[1:i] + vs[i + 1:]
        for tail in perfect_matchings(rest):
            out.append(((first, vs[i]),) + tail)
    return out


MATCHINGS = perfect_matchings(tuple(range(N)))


def fibre_partition(labels):
    """{word: [matching indices]} for an R_cell label list (None or (a,b))."""
    out = {}
    for n, M in enumerate(MATCHINGS):
        w = [-1] * N
        ok = True
        for u, v in M:
            lab = labels[EIDX[(u, v)]]
            if lab is None:
                ok = False
                break
            w[u], w[v] = lab
        if ok:
            out.setdefault(tuple(w), []).append(n)
    return out


def indicator(M):
    row = [0] * len(EDGES)
    for e in M:
        row[EIDX[e]] += 1
    return row


def lattice_contains(generators, target):
    """Is `target` in the Z-row-lattice of `generators`?  HNF comparison."""
    A = Matrix(generators)
    B = Matrix(generators + [target])
    ha = hermite_normal_form(A.T)
    hb = hermite_normal_form(B.T)
    return ha == hb


def o1_verdict(labels):
    table = fibre_partition(labels)
    binomials = [(w, ms) for w, ms in sorted(table.items())
                 if len(set(w)) > 1 and len(ms) == 2]
    if not binomials:
        return {"binomials": 0, "o1_dead": False, "reason": "no binomial fibre"}
    gens = []
    for _w, (i, j) in binomials:
        a, b = indicator(MATCHINGS[i]), indicator(MATCHINGS[j])
        gens.append([x - y for x, y in zip(a, b)] + [1])
    gens.append([0] * len(EDGES) + [2])
    target = [0] * len(EDGES) + [1]
    dead = lattice_contains(gens, target)
    return {"binomials": len(binomials), "o1_dead": bool(dead)}


def to_template(labels):
    return [frozenset() if lab is None else frozenset({tuple(lab)})
            for lab in labels]


def main():
    g = geom(N)
    blob = json.load(open(f"{W2}/hunt8_models.json"))
    models = []
    for key, res in sorted(blob["results"].items()):
        for mod in res["models"]:
            models.append((key, mod))
    print(f"loaded {len(models)} W2 models (claim: exactly 28)")
    rows = []
    ok_all = True
    for key, mod in models:
        labels = [None if x is None else tuple(x) for x in mod["labels"]]
        t = normalise_template(g, to_template(labels))
        rep = audit_template(g, t, exact=True)
        table = fibre_partition(labels)
        hist = {}
        for w, ms in table.items():
            if len(set(w)) > 1:
                hist[len(ms)] = hist.get(len(ms), 0) + 1
        o1 = o1_verdict(labels)
        good = (rep["m"] == mod["support"] and rep["mixed_singletons"] == 0
                and rep["constants_all_nonempty"] and o1["o1_dead"])
        ok_all &= good
        rows.append({"orbit": key, "support": rep["m"],
                     "sigma": rep["sigma"],
                     "mixed_singletons": rep["mixed_singletons"],
                     "const_fibres": rep["const_fibres"],
                     "mixed_hist": dict(sorted(hist.items())),
                     "o1": o1, "pass": bool(good)})
        print(f"  {key}: m={rep['m']} sigma={rep['sigma']} "
              f"singletons={rep['mixed_singletons']} "
              f"const={rep['const_fibres']} hist={dict(sorted(hist.items()))} "
              f"binomials={o1['binomials']} O1-dead={o1['o1_dead']} "
              f"-> {'PASS' if good else 'FAIL'}", flush=True)

    # ---- mutation controls for the O1 engine -------------------------------
    controls = {}
    # (C1) a template with NO binomial mixed fibre must not be declared dead
    labels = [None] * len(EDGES)
    for c, M in enumerate((((0, 1), (2, 3), (4, 5), (6, 7)),
                           ((0, 2), (1, 3), (4, 6), (5, 7)),
                           ((0, 3), (1, 2), (4, 7), (5, 6)))):
        for e in M:
            labels[EIDX[e]] = (c, c)
    controls["three_disjoint_constant_matchings"] = o1_verdict(labels)
    print("control C1 (3 disjoint constant matchings): "
          f"{controls['three_disjoint_constant_matchings']}")

    # (C2) a KNOWN-CONSISTENT binomial system must be declared alive:
    #      one relation only, x^d = -1 with d != 0, is always solvable.
    gens = [[1] + [0] * (len(EDGES) - 1) + [1], [0] * len(EDGES) + [2]]
    controls["single_relation_alive"] = not lattice_contains(
        gens, [0] * len(EDGES) + [1])
    print(f"control C2 (single relation x_0 = -1 must be SOLVABLE): "
          f"alive={controls['single_relation_alive']}")

    # (C3) a hand-built INCONSISTENT system must be caught:
    #      x^d = -1 and x^d = -1 twice with the same d and a third relation
    #      x^{2d} = -1 gives 1 = -1 (lambda = (1,1,-1), sum = 1 odd).
    d = [1, -1] + [0] * (len(EDGES) - 2)
    gens = [d + [1], [2 * x for x in d] + [1], [0] * len(EDGES) + [2]]
    controls["forced_contradiction_caught"] = lattice_contains(
        gens, [0] * len(EDGES) + [1])
    print(f"control C3 (x^d=-1 and x^2d=-1 must be INCONSISTENT): "
          f"caught={controls['forced_contradiction_caught']}")

    out = {"models": rows, "all_pass": bool(ok_all), "controls": controls,
           "model_count": len(models)}
    with open("results_w2_o1_audit.json", "w") as h:
        json.dump(out, h, indent=1, default=str)
    print(f"ALL PASS: {ok_all}; wrote results_w2_o1_audit.json")


if __name__ == "__main__":
    main()
