#!/usr/bin/env python3
"""UNAUDITED PROBE (W12) -- exact integer lattice tools + system reduction.

All integer arithmetic (Python ints).  Used to
  * compute the DIFFERENCE LATTICE of a value system (the monomial ratios
    that actually appear), which is the coordinate ring of the torus the
    system really lives on after the diagonal gauge is quotiented out;
  * compute the BINOMIAL SUBLATTICE generated by the two-term fibres, with
    the sign character, and its consistency;
  * produce a substitution that eliminates the binomial directions exactly.
"""

from __future__ import annotations

from fractions import Fraction


def hnf(rows):
    """Row-style Hermite normal form over Z.  Returns (H, U) with U*rows = H,
    H in row echelon form, zero rows dropped."""
    m = len(rows)
    n = len(rows[0]) if m else 0
    H = [list(r) for r in rows]
    U = [[1 if i == j else 0 for j in range(m)] for i in range(m)]
    pivot = 0
    for col in range(n):
        target = None
        for r in range(pivot, m):
            if H[r][col] != 0:
                target = r
                break
        if target is None:
            continue
        H[pivot], H[target] = H[target], H[pivot]
        U[pivot], U[target] = U[target], U[pivot]
        for r in range(pivot + 1, m):
            while H[r][col] != 0:
                a, b = H[pivot][col], H[r][col]
                if abs(b) >= abs(a):
                    f = b // a
                    for c in range(n):
                        H[r][c] -= f * H[pivot][c]
                    for c in range(m):
                        U[r][c] -= f * U[pivot][c]
                else:
                    H[pivot], H[r] = H[r], H[pivot]
                    U[pivot], U[r] = U[r], U[pivot]
        if H[pivot][col] < 0:
            H[pivot] = [-x for x in H[pivot]]
            U[pivot] = [-x for x in U[pivot]]
        pivot += 1
        if pivot == m:
            break
    keep = [i for i in range(m) if any(H[i])]
    return [H[i] for i in keep], [U[i] for i in keep]


def rank_z(rows):
    if not rows:
        return 0
    H, _ = hnf(rows)
    return len(H)


def rank_q(rows):
    """Rational rank by fraction-free Gaussian elimination."""
    if not rows:
        return 0
    M = [[Fraction(x) for x in r] for r in rows]
    n = len(M[0])
    r = 0
    for c in range(n):
        piv = None
        for i in range(r, len(M)):
            if M[i][c] != 0:
                piv = i
                break
        if piv is None:
            continue
        M[r], M[piv] = M[piv], M[r]
        inv = M[r][c]
        M[r] = [x / inv for x in M[r]]
        for i in range(len(M)):
            if i != r and M[i][c] != 0:
                f = M[i][c]
                M[i] = [a - f * b for a, b in zip(M[i], M[r])]
        r += 1
        if r == len(M):
            break
    return r


def exponent_vector(mono, nvars):
    v = [0] * nvars
    for x in mono:
        v[x] += 1
    return v


def difference_lattice(system, words=None):
    """Rows spanning the lattice of exponent differences a_k - a_1."""
    rows = []
    src = system.mixed_eqs if words is None else \
        {w: system.mixed_eqs[w] for w in words}
    for w, monos in src.items():
        if len(monos) < 2:
            continue
        base = exponent_vector(monos[0], system.nvars)
        for mono in monos[1:]:
            cur = exponent_vector(mono, system.nvars)
            rows.append([a - b for a, b in zip(cur, base)])
    return rows


def binomial_lattice(system):
    """(rows, signs) from the two-term fibres:  x^{d} = -1  for each row d."""
    rows = []
    for w, monos in system.mixed_eqs.items():
        if len(monos) != 2:
            continue
        a = exponent_vector(monos[0], system.nvars)
        b = exponent_vector(monos[1], system.nvars)
        rows.append([p - q for p, q in zip(a, b)])
    return rows


def gauge_matrix(system):
    """Rows = the 24 gauge directions (v,c): the exponent of mu_{v,c} in each
    variable.  x_{uv,i,j} picks up mu_{u,i} mu_{v,j}."""
    geo = system.geo
    rows = []
    for site in range(geo.size):
        for colour in range(3):
            row = [0] * system.nvars
            for n, (e, i, j) in enumerate(system.vars):
                u, v = geo.edges[e]
                if u == site and i == colour:
                    row[n] += 1
                if v == site and j == colour:
                    row[n] += 1
            rows.append(row)
    return rows


def binomial_consistency(system):
    """Is  x^{d}=-1 for all binomial rows d  solvable in (C*)^n ?

    Solvable iff for every integer relation sum n_k d_k = 0 the parity
    sum n_k is even.  Equivalently: writing D for the matrix of rows, the
    system D z = (1,...,1) mod 2 restricted to ker_Z(D^T) ... we test it
    directly by Smith-like reduction: reduce [D | 1] over Z and check no row
    reduces to [0 | odd]."""
    rows = binomial_lattice(system)
    if not rows:
        return {"rows": 0, "rank": 0, "consistent": True}
    n = system.nvars
    aug = [list(r) + [1] for r in rows]          # last column tracks parity
    # HNF on the D-part only, carrying the parity column along.
    m = len(aug)
    pivot = 0
    for col in range(n):
        target = None
        for r in range(pivot, m):
            if aug[r][col] != 0:
                target = r
                break
        if target is None:
            continue
        aug[pivot], aug[target] = aug[target], aug[pivot]
        for r in range(pivot + 1, m):
            while aug[r][col] != 0:
                a, b = aug[pivot][col], aug[r][col]
                if abs(b) >= abs(a):
                    f = b // a
                    for c in range(n + 1):
                        aug[r][c] -= f * aug[pivot][c]
                else:
                    aug[pivot], aug[r] = aug[r], aug[pivot]
        pivot += 1
        if pivot == m:
            break
    bad = [r for r in aug if not any(r[:n]) and r[n] % 2 == 1]
    return {"rows": len(rows), "rank": rank_z(rows),
            "consistent": not bad, "bad_rows": len(bad)}
