"""What the U7H import buys: the certificate lattice of the active core.

UNAUDITED EXTERNAL IMPORT AUDIT.

If A_R is matching covered (the external Theorem 2), Lovasz's matching
lattice theorem applies.  This script computes, exactly over Z, the two
lattices that the programme note (notes/2026-08-11-signed-matching-holonomy-
programme.md Problem 2) cares about:

  Lat0(A_R) = lattice generated by the flip exponents  1_M - 1_M'
              over all perfect matchings M, M' of A_R;
              this is exactly the fibre restriction of L_S.

  Frame(A_R) = { x in Z^E : x(boundary v) = 0 for every vertex v }
              = ker_Z(unsigned incidence) = Zaslavsky's even-cycle/frame
              lattice of the programme note section 1.

Always Lat0 <= Frame.  A first, NAIVE reading of the import is that
matching-coveredness alone forces index 1 (no Petersen brick exists below 10
vertices).  That reading is FALSE and this script refutes it: the correct
statement is Edmonds-Lovasz-Pulleyblank,

    rank Lat0(G) = |E| - |V| + 1 - b(G) = beta(G) - b(G),

with b(G) the number of BRICKS in the tight cut decomposition.  So index 1
holds exactly when b = 1 (G a brick, non-bipartite) or b = 0 (G a brace,
bipartite); a matching-covered graph with several bricks has a strictly
smaller flip lattice.  The script tests that refined prediction.

Exact integer arithmetic only.

Run:  python3 lattice_corollary.py
"""

from __future__ import annotations

import random
from fractions import Fraction
from itertools import combinations
from typing import Dict, List, Optional, Sequence, Set, Tuple

from u7h_core import (
    ONE,
    Edge,
    active_cofactor_graph,
    all_least_cancellations,
    is_matching_covered,
    supported_matchings,
)
import verify_u7h_theorem as V


# ------------------------------------------------------- integer linear algebra


def hnf_with_transform(mat: List[List[int]], pivot_cols: int):
    """Row-style HNF on the first `pivot_cols` columns.

    Returns (H, U) with U * mat == H and U unimodular over Z.
    """
    m = len(mat)
    n = len(mat[0]) if m else 0
    H = [row[:] for row in mat]
    U = [[1 if i == j else 0 for j in range(m)] for i in range(m)]
    row = 0
    for col in range(pivot_cols):
        # find a pivot by repeated gcd elimination
        while True:
            nz = [r for r in range(row, m) if H[r][col] != 0]
            if len(nz) <= 1:
                break
            nz.sort(key=lambda r: abs(H[r][col]))
            p = nz[0]
            for r in nz[1:]:
                q = H[r][col] // H[p][col]
                if q:
                    for c in range(n):
                        H[r][c] -= q * H[p][c]
                    for c in range(m):
                        U[r][c] -= q * U[p][c]
        nz = [r for r in range(row, m) if H[r][col] != 0]
        if not nz:
            continue
        p = nz[0]
        H[row], H[p] = H[p], H[row]
        U[row], U[p] = U[p], U[row]
        if H[row][col] < 0:
            H[row] = [-x for x in H[row]]
            U[row] = [-x for x in U[row]]
        row += 1
    return H, U


def integer_kernel_basis(B: List[List[int]], ncols: int) -> List[List[int]]:
    """A Z-basis of { x in Z^ncols : B x^T = 0 }, B given as rows over vertices."""
    # rows of Bt are the columns of B (one per edge)
    Bt = [[B[r][c] for r in range(len(B))] for c in range(ncols)]
    aug = [Bt[i] + [1 if i == j else 0 for j in range(ncols)] for i in range(ncols)]
    H, _ = hnf_with_transform(aug, len(B))
    basis = []
    for row in H:
        if all(x == 0 for x in row[: len(B)]):
            vec = row[len(B) :]
            if any(vec):
                basis.append(vec)
    return basis


def rank_q(mat: List[List[int]]) -> int:
    rows = [[Fraction(x) for x in r] for r in mat]
    if not rows:
        return 0
    n = len(rows[0])
    rank = 0
    for col in range(n):
        piv = next((r for r in range(rank, len(rows)) if rows[r][col]), None)
        if piv is None:
            continue
        rows[rank], rows[piv] = rows[piv], rows[rank]
        pv = rows[rank][col]
        for r in range(len(rows)):
            if r != rank and rows[r][col]:
                f = rows[r][col] / pv
                rows[r] = [rows[r][c] - f * rows[rank][c] for c in range(n)]
        rank += 1
    return rank


def solve_in_basis(vec: List[int], basis: List[List[int]]) -> Optional[List[int]]:
    """Express vec as an integer combination of the rows of `basis`."""
    r = len(basis)
    if r == 0:
        return [] if not any(vec) else None
    n = len(vec)
    # pick r independent columns
    cols = []
    for c in range(n):
        trial = cols + [c]
        sub = [[row[c2] for c2 in trial] for row in basis]
        if rank_q(sub) == len(trial):
            cols = trial
        if len(cols) == r:
            break
    if len(cols) < r:
        return None
    A = [[Fraction(basis[i][c]) for i in range(r)] for c in cols]  # r x r
    b = [Fraction(vec[c]) for c in cols]
    # gaussian elimination
    for i in range(r):
        piv = next((k for k in range(i, r) if A[k][i]), None)
        if piv is None:
            return None
        A[i], A[piv] = A[piv], A[i]
        b[i], b[piv] = b[piv], b[i]
        pv = A[i][i]
        A[i] = [x / pv for x in A[i]]
        b[i] = b[i] / pv
        for k in range(r):
            if k != i and A[k][i]:
                f = A[k][i]
                A[k] = [A[k][j] - f * A[i][j] for j in range(r)]
                b[k] = b[k] - f * b[i]
    coeffs = []
    for x in b:
        if x.denominator != 1:
            return None
        coeffs.append(int(x))
    # verify
    for c in range(n):
        if sum(coeffs[i] * basis[i][c] for i in range(r)) != vec[c]:
            return None
    return coeffs


def lattice_index(sub_gens: List[List[int]], basis: List[List[int]]) -> Optional[int]:
    """[ <basis> : <sub_gens> ] when both have the same rank; None if not."""
    r = len(basis)
    if r == 0:
        return 1 if not any(any(g) for g in sub_gens) else None
    coeff = []
    for g in sub_gens:
        c = solve_in_basis(g, basis)
        if c is None:
            return None
        coeff.append(c)
    if not coeff:
        return None
    if rank_q(coeff) != r:
        return None
    H, _ = hnf_with_transform(coeff, r)
    diag = []
    row = 0
    for col in range(r):
        if row < len(H) and H[row][col]:
            diag.append(abs(H[row][col]))
            row += 1
    if len(diag) != r:
        return None
    prod = 1
    for d in diag:
        prod *= d
    return prod


# --------------------------------------------------------------- the corollary


def analyse_core(R: Sequence[int], A: Set[Edge]) -> Dict[str, object]:
    E = sorted(A)
    idx = {e: k for k, e in enumerate(E)}
    unit = {e: ONE for e in E}
    pms = supported_matchings(tuple(R), unit)
    assert pms
    B = [[1 if v in e else 0 for e in E] for v in R]
    frame = integer_kernel_basis(B, len(E))
    base = pms[0]
    gens = []
    for m in pms[1:]:
        vec = [0] * len(E)
        for e in base:
            vec[idx[e]] += 1
        for e in m:
            vec[idx[e]] -= 1
        gens.append(vec)
    bipartite = is_bipartite(R, A)
    beta = len(E) - len(R) + 1
    expected_rank = beta if bipartite else beta - 1
    flip_rank = rank_q(gens) if gens else 0
    out = {
        "n": len(R),
        "edges": len(E),
        "beta": beta,
        "bipartite": bipartite,
        "brick": (not bipartite) and is_brick(R, A),
        "perfect_matchings": len(pms),
        "frame_rank": len(frame),
        "expected_frame_rank": expected_rank,
        "flip_rank": flip_rank,
        "defect": len(frame) - flip_rank,
        "index": lattice_index(gens, frame) if (gens and flip_rank == len(frame)) else None,
    }
    return out


def is_three_connected(vertices: Sequence[int], edges: Set[Edge]) -> bool:
    vs = list(vertices)
    if len(vs) < 4:
        return False
    from u7h_core import components as _comp
    for u, v in combinations(vs, 2):
        rest = [x for x in vs if x != u and x != v]
        sub = {e for e in edges if e[0] in rest and e[1] in rest}
        if len(_comp(rest, sub)) != 1:
            return False
    return True


def is_bicritical(vertices: Sequence[int], edges: Set[Edge]) -> bool:
    """G - u - v has a perfect matching for every pair of distinct vertices."""
    vs = list(vertices)
    for u, v in combinations(vs, 2):
        rest = tuple(x for x in vs if x != u and x != v)
        sub = {e: ONE for e in edges if e[0] in rest and e[1] in rest}
        if not supported_matchings(rest, sub):
            return False
    return True


def is_brick(vertices: Sequence[int], edges: Set[Edge]) -> bool:
    """A brick: 3-connected and bicritical (hence matching covered)."""
    return is_three_connected(vertices, edges) and is_bicritical(vertices, edges)


def is_bipartite(vertices: Sequence[int], edges: Set[Edge]) -> bool:
    adj: Dict[int, List[int]] = {v: [] for v in vertices}
    for a, b in edges:
        adj[a].append(b)
        adj[b].append(a)
    colour: Dict[int, int] = {}
    for s in vertices:
        if s in colour:
            continue
        colour[s] = 0
        stack = [s]
        while stack:
            u = stack.pop()
            for w in adj[u]:
                if w not in colour:
                    colour[w] = 1 - colour[u]
                    stack.append(w)
                elif colour[w] == colour[u]:
                    return False
    return True


def main() -> None:
    rng = random.Random(31337)
    seen: Set[Tuple] = set()
    rows = []
    bad = []
    for n, trials in ((4, 250), (6, 500), (8, 60)):
        for t in range(trials):
            w = V.build_cancelling(rng, n, bool(t % 2))
            if w is None:
                continue
            for R in all_least_cancellations(tuple(range(n)), w):
                A = active_cofactor_graph(R, w)
                if not is_matching_covered(R, A):
                    bad.append(("NOT MATCHING COVERED", R, sorted(A)))
                    continue
                key = (len(R), tuple(sorted(A)))
                if key in seen:
                    continue
                seen.add(key)
                rec = analyse_core(R, A)
                rows.append(rec)
                if rec["frame_rank"] != rec["expected_frame_rank"]:
                    bad.append(("FRAME RANK", R, sorted(A), rec))
                # refined prediction: brick or brace  =>  Lat0 == Frame
                if (rec["bipartite"] or rec["brick"]) and rec["index"] != 1:
                    bad.append(("BRICK/BRACE INDEX != 1", R, sorted(A), rec))
                # several bricks => strictly smaller flip lattice
                if not (rec["bipartite"] or rec["brick"]) and rec["defect"] < 0:
                    bad.append(("NEGATIVE DEFECT", R, sorted(A), rec))

    naive = [r for r in rows if r["index"] != 1]
    print("Lattice corollary of the U7H import (exact over Z)")
    print(f"  distinct matching-covered active cores examined : {len(rows)}")
    by_n: Dict[int, int] = {}
    for r in rows:
        by_n[r["n"]] = by_n.get(r["n"], 0) + 1
    print(f"  by |R|                                          : {dict(sorted(by_n.items()))}")
    print(f"  bipartite (braces) / non-bipartite              : "
          f"{sum(1 for r in rows if r['bipartite'])} / {sum(1 for r in rows if not r['bipartite'])}")
    print(f"  non-bipartite that are bricks                   : "
          f"{sum(1 for r in rows if r['brick'])}")
    print(f"  cores with beta >= 2 (branching branch)         : {sum(1 for r in rows if r['beta'] >= 2)}")
    print(f"  frame rank == beta - [non-bipartite] everywhere : "
          f"{all(r['frame_rank'] == r['expected_frame_rank'] for r in rows)}")
    print()
    print(f"  NAIVE claim  'matching covered => Lat0 == Frame': REFUTED on "
          f"{len(naive)}/{len(rows)} cores")
    dd: Dict[int, int] = {}
    for r in rows:
        dd[r["defect"]] = dd.get(r["defect"], 0) + 1
    print(f"  lattice defect (frame_rank - flip_rank) census  : {dict(sorted(dd.items()))}")
    print(f"  REFINED claim 'brick or brace => Lat0 == Frame' : "
          f"{'CONFIRMED' if not any(b[0] == 'BRICK/BRACE INDEX != 1' for b in bad) else 'REFUTED'} "
          f"on {sum(1 for r in rows if r['bipartite'] or r['brick'])} brick/brace cores")
    print(f"  every core with defect >= 1 is neither brick nor brace : "
          f"{all(not (r['bipartite'] or r['brick']) for r in rows if r['defect'] >= 1)}")
    print(f"  (the converse fails, as expected: a non-brick core may still")
    print(f"   tight-cut-decompose into a single brick plus braces, b=1, defect 0;")
    print(f"   such cores here: "
          f"{sum(1 for r in rows if not (r['bipartite'] or r['brick']) and r['defect'] == 0)})")
    if bad:
        print("\n  ANOMALIES:")
        for b in bad[:20]:
            print("   ", b)
        raise SystemExit(1)
    print("\n  => matching-coveredness ALONE does not pin the certificate lattice.")
    print("     The importable statement is the brick-count one: Lat0(A_R) is the")
    print("     full Zaslavsky frame lattice iff A_R is a single brick or a brace;")
    print("     otherwise it has corank b(A_R)-1 inside it.")


if __name__ == "__main__":
    main()
