"""Independent adversarial re-verification of the external U7H theorem.

External source: github.com/YesterdaysLemon/krenn-gu-research @ f17afa1c8e72
File: claims/arbitrary-order/
      MATRIX_UNIT_MINIMAL_PURE_COFACTOR_MATCHING_COVERED_CORE_AND_SINGLE_CYCLE_THEOREM.md

We re-test, on exactly-constructed instances, every numbered conclusion:

  T0  P subset A_R and delta(A_R) >= 2                (their eq. (4))
  T1  A_R == Allow(G_R)                               (their Theorem 1)
  T2  A_R connected and matching-covered              (their Theorem 2)
  T3  every edge of A_R on a P-alternating even cycle
      for EVERY perfect matching P of A_R             (their Theorem 3)
  T4a 2-regular case: single even cycle, exactly two PMs,
      primitive exponent, monomial first cofactors    (their Theorem 4A)
  T4b branching case: >= 3 PMs, beta >= 2,
      sum(deg-2) = 2(beta-1) > 0 and even             (their Theorem 4B)

Instances are generated by the *linear solve* trick: the hafnian is affine in
each single edge weight, so for a chosen support graph and random exact
weights on all but one edge, the remaining weight is determined exactly by
h = 0.  This produces genuinely cancelling instances over Q and over Q(i)
rather than the three hand-picked models the external repo ships.

Exact arithmetic only.  Run:  python3 verify_u7h_theorem.py
"""

from __future__ import annotations

import random
from fractions import Fraction
from itertools import combinations
from math import gcd
from typing import Dict, List, Optional

from u7h_core import (
    GQ,
    ONE,
    ZERO,
    Edge,
    active_cofactor_graph,
    allowed_edge_graph,
    alternating_cycle_witness,
    components,
    cyclomatic_rank,
    degrees,
    hafnian,
    is_connected,
    is_matching_covered,
    least_cancellation,
    all_least_cancellations,
    matching_weight,
    perfect_matchings,
    support_graph,
    supported_matchings,
)

# ---------------------------------------------------------------- generation

SMALL = [-3, -2, -1, 1, 2, 3]


def random_weight(rng: random.Random, gaussian: bool) -> GQ:
    re = Fraction(rng.choice(SMALL), rng.choice([1, 1, 1, 2, 3]))
    if not gaussian:
        return GQ(re, 0)
    im = Fraction(rng.choice(SMALL + [0, 0]), rng.choice([1, 1, 2]))
    return GQ(re, im)


def random_support(rng: random.Random, n: int) -> List[Edge]:
    """A random support graph on n vertices that has a perfect matching."""
    verts = list(range(n))
    while True:
        p = rng.uniform(0.3, 0.85)
        edges = [e for e in combinations(verts, 2) if rng.random() < p]
        if not edges:
            continue
        unit = {e: ONE for e in edges}
        if supported_matchings(tuple(verts), unit):
            return edges


def build_cancelling(rng: random.Random, n: int, gaussian: bool) -> Optional[Dict[Edge, GQ]]:
    """Exact weights on a random support with hafnian zero on all of range(n)."""
    verts = tuple(range(n))
    edges = random_support(rng, n)
    w: Dict[Edge, GQ] = {e: random_weight(rng, gaussian) for e in edges}
    rng.shuffle(edges)
    for pivot in edges:
        rest = tuple(v for v in verts if v not in pivot)
        w[pivot] = ZERO
        base = hafnian(verts, w)          # h with z_pivot = 0
        coeff = hafnian(rest, w)          # h(R - endpoints(pivot)) with z_pivot = 0
        if not coeff:
            w[pivot] = random_weight(rng, gaussian)
            continue
        z = ZERO - (base / coeff)
        if not z:
            w[pivot] = random_weight(rng, gaussian)
            continue
        w[pivot] = z
        assert not hafnian(verts, w)
        if supported_matchings(verts, w):
            return w
        w[pivot] = random_weight(rng, gaussian)
    return None


# ---------------------------------------------------------------- the checks


class Failure(Exception):
    pass


def check_instance(n: int, w: Dict[Edge, GQ], tags: Dict[str, int]) -> None:
    verts = tuple(range(n))
    if not supported_matchings(verts, w):
        return
    if hafnian(verts, w):
        return

    minimisers = all_least_cancellations(verts, w)
    if not minimisers:
        raise Failure("no least cancellation despite h=0 with a supported PM")

    for R in minimisers:
        A = active_cofactor_graph(R, w)
        Allow = allowed_edge_graph(R, w)
        Sup = support_graph(R, w)
        pms = supported_matchings(R, w)

        # ---- T1 : active == allowed
        if A != Allow:
            raise Failure(f"T1 FAILED  R={R} A={sorted(A)} Allow={sorted(Allow)}")
        if not Allow:
            raise Failure(f"empty allowed graph on R={R}")
        tags["T1"] += 1
        if Sup != Allow:
            tags["inactive_support_edge_present"] += 1

        # ---- T0 : P subset A_R, min degree >= 2, row sums vanish
        deg = degrees(R, A)
        for P in pms:
            if not set(P) <= A:
                raise Failure(f"T0 FAILED  P not inside A_R, R={R}")
        if min(deg.values()) < 2:
            raise Failure(f"T0 FAILED  min degree {min(deg.values())} on R={R}")
        for i in R:
            s = ZERO
            for j in R:
                if j == i:
                    continue
                e = (min(i, j), max(i, j))
                rest = tuple(v for v in R if v != i and v != j)
                s = s + w.get(e, ZERO) * hafnian(rest, w)
            if s:
                raise Failure(f"T0 FAILED  cofactor row sum nonzero at {i}, R={R}")
        tags["T0"] += 1

        # ---- T2 : connected + matching covered
        if not is_connected(R, A):
            raise Failure(f"T2 FAILED  A_R disconnected: {components(R, A)}  R={R}")
        if not is_matching_covered(R, A):
            raise Failure(f"T2 FAILED  A_R not matching covered  R={R}")
        tags["T2"] += 1

        # ---- component factorisation identity (their eq. (9)) on the FULL set
        # (checked separately below on the ambient vertex set)

        # ---- T3 : alternating generation, for EVERY reference matching
        for P in pms:
            alternating_cycle_witness(R, A, P)
        tags["T3"] += 1

        beta = cyclomatic_rank(R, A)
        excess = sum(d - 2 for d in deg.values())
        if excess != 2 * (beta - 1):
            raise Failure(f"T4 FAILED  excess {excess} != 2(beta-1) {2*(beta-1)}")

        if set(deg.values()) == {2}:
            # ---- T4a : one even cycle
            if len(A) != len(R):
                raise Failure(f"T4a FAILED  2-regular but |A|={len(A)} |R|={len(R)}")
            if len(pms) != 2:
                raise Failure(f"T4a FAILED  cycle with {len(pms)} perfect matchings")
            m0, m1 = pms
            if set(m0) & set(m1):
                raise Failure("T4a FAILED  the two cycle matchings share an edge")
            if matching_weight(m0, w) + matching_weight(m1, w):
                raise Failure("T4a FAILED  binomial does not cancel")
            expo = [
                (1 if e in set(m0) else 0) - (1 if e in set(m1) else 0)
                for e in sorted(A)
            ]
            g = 0
            for x in expo:
                g = gcd(g, abs(x))
            if g != 1:
                raise Failure(f"T4a FAILED  exponent not primitive, gcd={g}")
            # monomial first cofactors on cycle edges
            for e in A:
                rest = tuple(v for v in R if v not in e)
                if len(supported_matchings(rest, w)) != 1:
                    raise Failure(f"T4a FAILED  cofactor of {e} is not a monomial")
            # off-cycle support edges have structurally empty cofactors
            for e in Sup - A:
                rest = tuple(v for v in R if v not in e)
                if supported_matchings(rest, w):
                    raise Failure(f"T4a FAILED  off-core edge {e} has a supported complement")
            tags["T4a"] += 1
        else:
            # ---- T4b : branching core
            if len(pms) < 3:
                raise Failure(f"T4b FAILED  branching core with {len(pms)} matchings")
            if beta < 2:
                raise Failure(f"T4b FAILED  beta={beta}")
            if excess <= 0 or excess % 2:
                raise Failure(f"T4b FAILED  excess={excess}")
            hi = sum(1 for d in deg.values() if d >= 3)
            if not (any(d >= 4 for d in deg.values()) or hi >= 2):
                raise Failure("T4b FAILED  branching excess localised at one degree-3 vertex")
            cycles = set()
            for P in pms:
                cycles.update(alternating_cycle_witness(R, A, P).values())
            if len(cycles) < 2:
                raise Failure("T4b FAILED  fewer than two distinct alternating cycles")
            tags["T4b"] += 1

    # ---- eq. (9): component factorisation on the ambient vertex set
    Allow_full = allowed_edge_graph(verts, w)
    comps = components(verts, Allow_full)
    prod = ONE
    ok = True
    for c in comps:
        if len(c) % 2:
            ok = False
            break
        prod = prod * hafnian(c, w)
    if ok and prod != hafnian(verts, w):
        raise Failure("eq.(9) FAILED  component factorisation of the hafnian")
    if len(comps) > 1:
        tags["ambient_allowed_graph_disconnected"] += 1


def main() -> None:
    rng = random.Random(20260813)
    tags = {
        k: 0
        for k in (
            "instances",
            "T0",
            "T1",
            "T2",
            "T3",
            "T4a",
            "T4b",
            "inactive_support_edge_present",
            "ambient_allowed_graph_disconnected",
            "R_proper_subset_of_V",
            "multiple_minimisers",
        )
    }
    plan = [(4, 400, False), (4, 400, True), (6, 900, False), (6, 900, True),
            (8, 90, False), (8, 90, True)]
    for n, trials, gaussian in plan:
        for _ in range(trials):
            w = build_cancelling(rng, n, gaussian)
            if w is None:
                continue
            tags["instances"] += 1
            ms = all_least_cancellations(tuple(range(n)), w)
            if ms and len(ms[0]) < n:
                tags["R_proper_subset_of_V"] += 1
            if len(ms) > 1:
                tags["multiple_minimisers"] += 1
            check_instance(n, w, tags)

    print("U7H independent re-verification: PASS")
    for k, v in tags.items():
        print(f"  {k:38s} {v}")


if __name__ == "__main__":
    main()
