use std::convert::TryInto;
use std::fs::{read_dir,File};
use std::io::{BufReader,Read};
use std::path::PathBuf;
use std::time::Instant;
const DIR:&str="computations/unaudited-codex-orbit0-k15-k3-full-export-plan-2026-08-23/stage1_shards/";
const REC:usize=104;const HEADER:usize=96;const U:u64=400_591_699_200;
fn i128le(x:&[u8])->i128{i128::from_le_bytes(x.try_into().unwrap())}
fn main(){let begun=Instant::now();let mut paths:Vec<PathBuf>=read_dir(DIR).unwrap().map(|x|x.unwrap().path()).filter(|p|p.extension().map_or(false,|x|x=="bin")).collect();paths.sort();assert_eq!(paths.len(),242);let(mut tn,mut tu,mut tw)=(0u64,0u64,0i128);let mut b=[0u8;REC];for path in paths{let mut r=BufReader::with_capacity(8<<20,File::open(&path).unwrap());let mut h=[0u8;HEADER];r.read_exact(&mut h).unwrap();assert_eq!(&h[..8],b"K18PRF2\0");assert_eq!((h[12],h[13]),(2,2));assert_eq!(u16::from_le_bytes(h[14..16].try_into().unwrap())as usize,REC);assert_eq!(u64::from_le_bytes(h[16..24].try_into().unwrap()),U);let n=u64::from_le_bytes(h[32..40].try_into().unwrap());let hu=u64::from_le_bytes(h[40..48].try_into().unwrap());let hw=i128le(&h[48..64]);let(mut prior,mut uses,mut weight)=(None,0u64,0i128);for _ in 0..n{r.read_exact(&mut b).unwrap();let mut key=[0u8;42];key.copy_from_slice(&b[..42]);if let Some(p)=prior{assert!(p<key)}prior=Some(key);let w=i128le(&b[42..58]);let u=u64::from_le_bytes(b[58..66].try_into().unwrap());assert_ne!(w,0);assert!(u>0);weight+=w;uses+=u}let mut one=[0u8;1];assert_eq!(r.read(&mut one).unwrap(),0);assert_eq!((uses,weight),(hu,hw));tn+=n;tu+=uses;tw+=weight}assert_eq!(tn,112_628_530);assert_eq!(tw,-318_525_115_738_462_617_600);let out=format!("{{\"status\":\"PASS_ALL_242_PART_STRICT_ORDER_AND_SUM_REPLAY\",\"records\":{},\"header_uses\":{},\"signed_weight_scaled\":\"{}\",\"elapsed_seconds\":{:.6}}}\n",tn,tu,tw,begun.elapsed().as_secs_f64());std::fs::write("computations/unaudited-codex-orbit0-k15-k3-full-export-plan-2026-08-23/results_stage1_record_order.json",&out).unwrap();print!("{}",out)}
