#!/usr/bin/env python3
import hashlib,json,os
from pathlib import Path
HERE=Path(__file__).resolve().parent
def sha(path):return hashlib.sha256(path.read_bytes()).hexdigest()
def atomic(path,value):tmp=path.with_suffix(path.suffix+'.tmp');tmp.write_text(json.dumps(value,indent=2,sort_keys=True)+'\n');os.replace(tmp,path)
LEDGER='4aa023638d439fd1250b66593d93dd29dd4472831449ff571e2730bf6950b4ce';FUTURE='5173f8f03b8eb7feff428573cb6a0b2813ef1e6cb1d4c4696543c30585e522e4';ADAPTER='887762ea499c3dbf8b566987fe1ba234f518e72ba9733f6b96accd4435dee1fb';RUNNER='c1aa9303186a1a1e1efaa867471192b69b746aac52741ad227d901db34cbe24a';SELECTED=list(range(76,126))
for path,want in ((HERE/'source_ledger.json',LEDGER),(HERE/'future_dependencies.json',FUTURE),(HERE/'normalize_dependencies.py',ADAPTER),(HERE/'run_groups76_125.py',RUNNER)):assert sha(path)==want
ledger=json.loads((HERE/'source_ledger.json').read_text());future=json.loads((HERE/'future_dependencies.json').read_text());assert ledger['selection']['selected_group_ids']==SELECTED and future['required_closed_union']==list(range(76))
plan={'schema':'KRENN_X5_REP2_GROUPS76_125_EXACT_Q_CONDITIONAL_HELD_SCHEDULE_V1','status':'HELD_BOTH_FUTURE_DEPENDENCIES_ABSENT_ZERO_RUNS','selection':ledger['selection'],'future_dependencies':{'path':'future_dependencies.json','sha256':FUTURE,'satisfied':False,'both_hash_pairs_null':True,'normalized_dependencies_present':False},'adapter':{'path':'normalize_dependencies.py','sha256':ADAPTER,'required_closed_union':list(range(76)),'fail_closed':True},'lanes':ledger['lanes'],'source_ledger':{'path':'source_ledger.json','sha256':LEDGER,'total_bytes':sum(x['source_bytes'] for x in ledger['lanes'])},'authoritative_census':ledger['authoritative_census'],'runner':{'path':'run_groups76_125.py','sha256':RUNNER,'strict_sequential':True,'direct_libproc_process_group_rss':True,'fail_closed_rusage':True,'internal_gtimeout_wrapper':True,'atomic_per_lane_results':True,'single_use_batch_marker':True},'execution':{'native_wall_seconds_each':240,'wrapper_wall_seconds_each':250,'rss_cap_bytes_each':8589934592,'maximum_lane_count':50,'order':SELECTED,'parallel':False,'skip':False,'reorder':False,'relaunch':False,'stop_whole_batch_on':['NONUNIT','RESOURCE','PROCESS','SCHEMA_OR_TRANSCRIPT_MISMATCH']},'scope':{'representative':'rep2 only','source_regeneration_only':True,'solver_launches':0,'result_files':0,'attempt_markers':0,'clearances':0,'groups_newly_closed':0,'mathematical_coverage_added':False,'rep2_closed':False,'cross_representative_transport':False}}
atomic(HERE/'held_schedule.json',plan)
hex64={'type':'string','pattern':'^[0-9a-f]{64}$'}
acceptance={'schema':{'const':'KRENN_X5_REP2_GROUPS76_125_EXACT_Q_INDEPENDENT_ACCEPTANCE_V1'},'status':{'const':'PASS_APPROVE_CONDITIONAL_REP2_GROUPS76_125_ONLY'},'held_manifest_sha256':hex64,'source_ledger_sha256':{'const':LEDGER},'normalized_dependencies_sha256':hex64,'runner_sha256':{'const':RUNNER},'required_closed_union':{'const':list(range(76))},'selected_group_ids':{'const':SELECTED},'maximum_lane_count':{'const':50},'exact_Q_authorized':{'const':True},'parallel_authorized':{'const':False},'skip_reorder_relaunch_authorized':{'const':False}}
clearance={'schema':{'const':'KRENN_X5_REP2_GROUPS76_125_EXACT_Q_EXPLICIT_CLEARANCE_V1'},'status':{'const':'CLEARED_CONDITIONAL_REP2_GROUPS76_125_ONLY'},'held_manifest_sha256':hex64,'independent_referee_acceptance_sha256':hex64,'source_ledger_sha256':{'const':LEDGER},'normalized_dependencies_sha256':hex64,'runner_sha256':{'const':RUNNER},'singular_sha256':{'const':'9436b32ff7565719240230de8a6fb1d27af5e65f0ca4c9c5b756a77e82409b88'},'gtimeout_sha256':{'const':'1e26c50fa8c439fe1f4e6c6edd106e95030e16582c1c8c32e73d8a889cdf5b95'},'required_closed_union':{'const':list(range(76))},'selected_group_ids':{'const':SELECTED},'native_wall_seconds_each':{'const':240},'wrapper_wall_seconds_each':{'const':250},'rss_cap_bytes_each':{'const':8589934592},'no_overlap_confirmed':{'const':True},'maximum_lane_count':{'const':50},'parallel_authorized':{'const':False},'skip_reorder_relaunch_authorized':{'const':False}}
for name,properties in (('independent_referee_acceptance.schema.json',acceptance),('launch_clearance.schema.json',clearance)):atomic(HERE/name,{'$schema':'https://json-schema.org/draft/2020-12/schema','type':'object','additionalProperties':False,'required':list(properties),'properties':properties})
print(json.dumps({'status':plan['status'],'selected':[76,125],'sources':50,'runner_sha256':RUNNER,'solver_runs':0},sort_keys=True))
