#!/usr/bin/env python3
"""UNAUDITED PROBE (W4 / task C2) -- the Arf / odd-handcuff alignment test.

Pinned HEAD: 26ba69f7e643694c6a58464af6e9e1de9ec92f01

TWO MOD-2 STRUCTURES ARE COMPARED.

(A) SPIN.  The genus-1 Kasteleyn decomposition of the K_6 hafnian
    (pfaff_k6.py) supplies four Kasteleyn orientations eps_0..eps_3, one per
    class modulo vertex flips, with Arf signs c = (+1,-1,+1,+1) and
        2 haf(W) = sum_i c_i Pf(A^{eps_i}).
    Their matching signs satisfy sigma_i(M) = sigma_0(M) * chi_i(cls(M)),
    where cls : {15 matchings} -> H_1(T^2; F_2) = (Z/2)^2 is the homology
    class of M Delta M_0 and chi_0..chi_3 are the four characters.  So the
    "spin sectors" are literally the four homology classes of matchings.
    Class sizes are computed below (4,4,4,3).

(B) O1 / ZASLAVSKY.  (notes/2026-08-11-signed-matching-holonomy-programme.md)
    Cells a_uv(i,j) are the edges of the CELL GRAPH on the 18 ports (v,i);
    the gauge-invariant lattice L = ker(unsigned incidence) is Zaslavsky's
    even-cycle (frame) lattice, generated by even cycles and ODD HANDCUFFS.
    Each two-term ("binomial") mixed fibre {M,N} at colouring c forces
        x^{d_c} = -1,     d_c = a(c,M) - a(c,N)  in L,
    and an O1 certificate is an integer relation sum_j n_j d_j = 0 whose
    coefficient sum is ODD, giving 1 = -1.  The sign character is
        epsilon(lambda) = (-1)^{sum_j n_j},   epsilon(d_j) = -1 for every j.

THE PREDICTION TESTED.  Does the four-Pfaffian decomposition diagonalize the
O1 sign local system?  Two sharp questions:

  Q1 (sector reading).  A binomial fibre {M,N} makes Pf_i vanish on that word
     exactly when sigma_i(M) = sigma_i(N), i.e. when chi_i(alpha) = +1 for
     alpha = cls(M) + cls(N).  So a fibre with alpha != 0 kills exactly TWO of
     the four spin sectors, and a fibre with alpha = 0 kills ALL FOUR.
     Verified exactly below.

  Q2 (factorization).  Does epsilon factor through the spin grading?  That is,
     is there a character phi of H_1(T^2;F_2) with epsilon(d) = phi(alpha(d))
     for every binomial relation d?  Since epsilon(d) = -1 always, this holds
     iff every binomial fibre of the certificate has alpha != 0 AND all the
     alphas avoid one common index-two subgroup.  A single fibre with
     alpha = 0 refutes it outright (phi(0) = +1 != -1).

The committed six-site O1 certificates are read off the notes verbatim:
  * notes/n6-unrestricted-minimum-closure-phase-obstruction.md display (3):
    three binomial fibres, D_{000002} - D_{000122} - D_{011102} = 0;
  * notes/generalized-laurent-elimination.md section 5 (6P1) and section 4
    (P3+3P1, 2P2+2P1): further explicit binomial triples.
Matching indices are the lexicographic enumeration shared by
computations/search_f5_support_sat.py (verified against the note's table).
"""

from __future__ import annotations

from itertools import combinations
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

from pfaff_k6 import MATCHINGS6, sign_vector
from descent_pfaffian import kasteleyn_quadruple

PORTS = [(v, i) for v in range(6) for i in range(3)]


def matching_index_table():
    """Check our enumeration against the note's published table."""
    published = {0: ((0, 1), (2, 3), (4, 5)), 1: ((0, 1), (2, 4), (3, 5)),
                 3: ((0, 2), (1, 3), (4, 5)), 13: ((0, 5), (1, 3), (2, 4)),
                 14: ((0, 5), (1, 4), (2, 3)), 11: ((0, 4), (1, 5), (2, 3)),
                 8: ((0, 3), (1, 5), (2, 4)), 6: ((0, 3), (1, 2), (4, 5)),
                 9: ((0, 4), (1, 2), (3, 5)), 10: ((0, 4), (1, 3), (2, 5)),
                 2: ((0, 1), (2, 5), (3, 4)), 4: ((0, 2), (1, 4), (3, 5)),
                 7: ((0, 3), (1, 4), (2, 5))}
    for index, matching in published.items():
        assert MATCHINGS6[index] == matching, (index, MATCHINGS6[index])
    return len(published)


# ------------------------------------------------------------ spin sectors

def spin_data():
    reps, signs = kasteleyn_quadruple()
    sigmas = [sign_vector(o) for o in reps]
    classes = {}
    for n in range(len(MATCHINGS6)):
        key = tuple(sigmas[i][n] * sigmas[0][n] for i in range(4))
        classes.setdefault(key, []).append(n)
    keys = sorted(classes, key=lambda k: (-len(classes[k]), k))
    label = {key: n for n, key in enumerate(keys)}
    cls = {}
    for key, members in classes.items():
        for n in members:
            cls[n] = label[key]
    return reps, signs, sigmas, cls, {label[k]: classes[k] for k in keys}, keys


# --------------------------------------------------- committed certificates

CERTIFICATES = [
    {"name": "n6 unrestricted-minimum closure, display (3)",
     "source": "notes/n6-unrestricted-minimum-closure-phase-obstruction.md",
     "fibres": [((0, 0, 0, 0, 0, 2), 0, 11),
                ((0, 0, 0, 1, 2, 2), 1, 8),
                ((0, 1, 1, 1, 0, 2), 6, 9)],
     "coefficients": (1, -1, -1)},
    {"name": "6P1 (empty exceptional graph)",
     "source": "notes/generalized-laurent-elimination.md sec 5",
     "fibres": [((0, 2, 0, 0, 0, 1), 9, 10),
                ((0, 2, 0, 0, 1, 1), 3, 6),
                ((0, 2, 0, 0, 2, 1), 4, 7)],
     "coefficients": (-1, -1, 1)},
    {"name": "P3+3P1 on {01,12}",
     "source": "notes/generalized-laurent-elimination.md sec 4",
     "fibres": [((0, 0, 0, 0, 1, 1), 2, 9),
                ((0, 0, 1, 0, 0, 0), 2, 9),
                ((0, 0, 1, 0, 1, 0), 2, 9)],
     "coefficients": (-1, -1, 1)},
    {"name": "2P2+2P1 on {01,23}",
     "source": "notes/generalized-laurent-elimination.md sec 4",
     "fibres": [((0, 0, 0, 0, 0, 1), 1, 14),
                ((0, 0, 0, 0, 0, 2), 1, 14),
                ((0, 0, 0, 0, 1, 2), 1, 14)],
     "coefficients": (-1, 1, -1)},
]


def cells_of(word, matching):
    return tuple((u, v, word[u], word[v]) for u, v in MATCHINGS6[matching])


def cell_graph_cycle_shape(cells_plus, cells_minus):
    """Shape of the port-graph subgraph of a binomial exponent row."""
    degree = {}
    edges = []
    for cell in list(cells_plus) + list(cells_minus):
        u, v, i, j = cell
        a, b = (u, i), (v, j)
        edges.append((a, b))
        degree[a] = degree.get(a, 0) + 1
        degree[b] = degree.get(b, 0) + 1
    # bipartite?  (all-negative signed graph: balanced circle = even circle)
    adjacency = {}
    for a, b in edges:
        adjacency.setdefault(a, []).append(b)
        adjacency.setdefault(b, []).append(a)
    colour = {}
    bipartite = True
    for start in adjacency:
        if start in colour:
            continue
        colour[start] = 0
        stack = [start]
        while stack:
            node = stack.pop()
            for other in adjacency[node]:
                if other not in colour:
                    colour[other] = 1 - colour[node]
                    stack.append(other)
                elif colour[other] == colour[node]:
                    bipartite = False
    degrees = sorted(degree.values())
    return {"ports": len(degree), "edges": len(edges), "bipartite": bipartite,
            "degree_sequence": degrees}


EDGES6 = tuple(combinations(range(6), 2))
EDGE_INDEX = {e: n for n, e in enumerate(EDGES6)}


def symmetric_difference(m, n):
    """M Delta N as a vector in F_2^{edges of K_6}."""
    vector = [0] * 15
    for u, v in MATCHINGS6[m]:
        vector[EDGE_INDEX[(u, v)]] ^= 1
    for u, v in MATCHINGS6[n]:
        vector[EDGE_INDEX[(u, v)]] ^= 1
    return vector


def homology_quotient():
    """H_1(T^2;F_2) = Z_1(K_6;F_2) / <face boundaries> from the embedding."""
    from pfaff_k6 import delete_vertex, k7_torus_rotation, trace_faces
    faces = trace_faces(delete_vertex(k7_torus_rotation(), 6))
    rows = []
    for walk in faces:
        vector = [0] * 15
        for u, v in walk:
            vector[EDGE_INDEX[(min(u, v), max(u, v))]] ^= 1
        rows.append(vector)
    basis, pivots = [], []
    for vector in rows:
        row = list(vector)
        for pivot, brow in zip(pivots, basis):
            if row[pivot]:
                row = [a ^ b for a, b in zip(row, brow)]
        pivot = next((n for n, value in enumerate(row) if value), None)
        if pivot is None:
            continue
        basis.append(row)
        pivots.append(pivot)
    faces_dim = len(basis)
    # choose two cycles completing the face span to the full cycle space
    representatives = []
    extended, extended_pivots = list(basis), list(pivots)
    for m, n in combinations(range(15), 2):
        cycle = symmetric_difference(m, n)
        row = list(cycle)
        for pivot, brow in zip(extended_pivots, extended):
            if row[pivot]:
                row = [a ^ b for a, b in zip(row, brow)]
        pivot = next((k for k, value in enumerate(row) if value), None)
        if pivot is None:
            continue
        extended.append(row)
        extended_pivots.append(pivot)
        representatives.append((cycle, len(representatives)))
        if len(representatives) == 2:
            break

    def quotient(vector):
        """Coordinates of [vector] in H_1 with respect to the two generators."""
        for bits in ((0, 0), (1, 0), (0, 1), (1, 1)):
            test = list(vector)
            for bit, (cycle, _n) in zip(bits, representatives):
                if bit:
                    test = [a ^ b for a, b in zip(test, cycle)]
            row = list(test)
            for pivot, brow in zip(pivots, basis):
                if row[pivot]:
                    row = [a ^ b for a, b in zip(row, brow)]
            if not any(row):
                return list(bits)
        raise RuntimeError("not in the cycle space")

    return quotient, faces_dim


SECTOR_COORDS = {}


def sector_class(a, b, keys):
    """The H_1 coordinates of the difference of two spin sectors."""
    if not SECTOR_COORDS:
        raise RuntimeError("sector coordinates not initialised")
    return [(x + y) % 2 for x, y in zip(SECTOR_COORDS[a], SECTOR_COORDS[b])]


def initialise_sector_coords(cls, keys):
    """Match the sector labels to H_1 coordinates via one reference pair."""
    quotient, _ = homology_quotient()
    base = next(n for n in range(15) if cls[n] == cls[0])
    for sector in range(4):
        member = next(n for n in range(15) if cls[n] == sector)
        SECTOR_COORDS[sector] = quotient(symmetric_difference(0, member))
    return SECTOR_COORDS


def main():
    print("UNAUDITED PROBE (W4, task C2) -- Arf / odd-handcuff alignment")
    print("pinned HEAD 26ba69f7e643694c6a58464af6e9e1de9ec92f01")
    print("matching enumeration checked against the published table:",
          matching_index_table(), "entries")
    reps, signs, sigmas, cls, members, keys = spin_data()
    initialise_sector_coords(cls, keys)
    print("Arf signs of the four spin structures:", signs)
    print("spin sectors (homology classes of matchings), sizes:",
          {k: len(v) for k, v in members.items()})
    for k, v in members.items():
        print("   sector %d (character %s): matchings %s"
              % (k, keys[k], v))
    report = {"arf_signs": signs,
              "sector_sizes": {str(k): len(v) for k, v in members.items()},
              "certificates": []}

    print()
    print("Q1  sector reading of a two-term fibre (exact, all 105 pairs)")
    same, different = 0, 0
    for m, n in combinations(range(15), 2):
        killed = [i for i in range(4) if sigmas[i][m] == sigmas[i][n]]
        if cls[m] == cls[n]:
            assert len(killed) == 4, (m, n, killed)
            same += 1
        else:
            assert len(killed) == 2, (m, n, killed)
            different += 1
    print("   pairs in the SAME sector      : %3d  -> all four Pf_i vanish"
          % same)
    print("   pairs in DIFFERENT sectors    : %3d  -> exactly two Pf_i vanish"
          % different)
    report["pairs_same_sector"] = same
    report["pairs_different_sector"] = different

    print()
    print("Q2  does the O1 sign character factor through the spin grading?")
    for certificate in CERTIFICATES:
        print()
        print(" *", certificate["name"])
        print("   source:", certificate["source"])
        alphas, rows = [], []
        for (word, m, n), coefficient in zip(certificate["fibres"],
                                             certificate["coefficients"]):
            alpha_zero = cls[m] == cls[n]
            alphas.append((cls[m], cls[n], alpha_zero))
            killed = [i for i in range(4) if sigmas[i][m] == sigmas[i][n]]
            shape = cell_graph_cycle_shape(cells_of(word, m), cells_of(word, n))
            rows.append({"word": "".join(map(str, word)), "matchings": [m, n],
                         "coefficient": coefficient,
                         "sectors": [cls[m], cls[n]],
                         "alpha_zero": alpha_zero,
                         "spin_sectors_killed": killed,
                         "cell_graph": shape})
            print("   word %s  matchings {%2d,%2d}  sectors (%d,%d)%s"
                  "  kills Pf %s  cell-graph %s"
                  % ("".join(map(str, word)), m, n, cls[m], cls[n],
                     "  alpha = 0" if alpha_zero else "          ",
                     killed,
                     "bipartite(even)" if shape["bipartite"]
                     else "NON-bipartite(odd)"))
        coefficient_sum = sum(certificate["coefficients"])
        print("   coefficient sum = %d (%s)  =>  epsilon = %+d"
              % (coefficient_sum, "ODD" if coefficient_sum % 2 else "even",
                 (-1) ** (coefficient_sum % 2)))
        # factorization test
        any_zero = any(z for _a, _b, z in alphas)
        verdict = None
        if any_zero:
            verdict = ("REFUTED: a binomial fibre has alpha = 0, so phi(0)=+1"
                       " would have to equal epsilon(d) = -1")
        else:
            # do the three alphas avoid a common index-two subgroup?
            witnesses = []
            for i in range(4):
                if all(sigmas[i][m] != sigmas[i][n]
                       for _w, m, n in certificate["fibres"]):
                    witnesses.append(i)
            verdict = ("consistent via characters %s" % witnesses
                       if witnesses else
                       "REFUTED: no single character phi is -1 on every fibre")
        print("   factorization verdict:", verdict)
        report["certificates"].append({"name": certificate["name"],
                                       "rows": rows,
                                       "coefficient_sum": coefficient_sum,
                                       "verdict": verdict})

    print()
    print("Q2b what the spin grading IS, as a map on the cell lattice")
    quotient, faces_dim = homology_quotient()
    agree = 0
    for m, n in combinations(range(15), 2):
        cycle = symmetric_difference(m, n)
        assert quotient(cycle) == sector_class(cls[m], cls[n], keys), (m, n)
        agree += 1
    print("   H_1(T^2;F_2) from the embedding: cycle space dim %d, face"
          " boundary span dim %d, quotient dim %d"
          % (10, faces_dim, 10 - faces_dim))
    print("   [M Delta N] in that quotient equals the spin-sector difference"
          " for all %d pairs: PASS" % agree)
    print("   => the spin grading is the composite homomorphism")
    print("        h : Z^{cells} -> F_2^{edges of K_6} -> H_1(T^2;F_2)")
    print("      (forget the colours, reduce mod 2, take the homology class).")
    print("      It is COLOUR-BLIND, so it is a quotient of the O1 lattice;")
    print("      hence every O1 relation sum n_j d_j = 0 automatically has")
    print("      sum n_j alpha_j = 0.  Checked on the certificates:")
    report["alpha_sums"] = []
    for certificate in CERTIFICATES:
        total = [0, 0]
        for (word, m, n), coefficient in zip(certificate["fibres"],
                                             certificate["coefficients"]):
            if coefficient % 2:
                alpha = sector_class(cls[m], cls[n], keys)
                total = [(a + b) % 2 for a, b in zip(total, alpha)]
        print("     %-42s sum n_j alpha_j = %s"
              % (certificate["name"], tuple(total)))
        report["alpha_sums"].append({"name": certificate["name"],
                                     "alpha_sum": total})
    print()
    print("   BUT epsilon does not factor through h: epsilon(d) = -1 on every")
    print("   binomial row, including rows with h(d) = 0.  The two mod-2")
    print("   structures are therefore independent characters of L_S:")
    print("     * h  (spin) is colour-blind and sees only the 15 matchings;")
    print("     * epsilon (O1) is colour-aware and needs an odd cycle in the")
    print("       cell graph over the 18 ports, which h cannot see.")

    with open("results_arf_handcuff.json", "w") as handle:
        json.dump(report, handle, indent=1, default=str)
    print()
    print("wrote results_arf_handcuff.json")


if __name__ == "__main__":
    main()
